### ISSUE TITLE
The backend fails periodically

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1001]
With the following error:
`Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 182.`

**Comment by kittaakos** [comment]
Is it possible, that this error still comes from `chokidar`, should not, right?
See: https://github.com/parcel-bundler/parcel/issues/52 and the following `chokidar` issue.

**Comment by akosyakov** [comment]
To reproduce: reload a page several times with an opened workspace.

**Comment by akosyakov** [comment]
@kittaakos it was chokidar issue, I was using an outdated version of Theia. It is not reproducible with the latest.
