### ISSUE TITLE
[Linux] keyboard navigation is broken

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1007]
When creating a new file or folder, you have to use the mouse to click "ok" to validate and close the dialog.  It should be possible to just press enter to do the same.

I am testing on Chromium on Linux.

**Comment by MarkZ3** [comment]
Same on Safari.

**Comment by akosyakov** [comment]
And esc should close the dialog. It is a regression, used to work.

**Comment by akosyakov** [comment]
It works on the master on MacOS, it seems to be related only to Linux. I also noticed that keyboard navigation does not seem to work in the file navigator on Linux.
