### ISSUE TITLE
how can I use it in a angular project?

### ISSUE THREAD

**Issue by linpengfei** [theia-ide/theia#1023]
I have a angular project, how can I use the ide in the project?

**Comment by svenefftinge** [comment]
Are you asking about developing your project with Theia or integrating Theia in your angular app?

**Comment by linpengfei** [comment]
@svenefftinge yes,I mean how can I integrating Theia in my angular app.Can you give me a demo?

**Comment by svenefftinge** [comment]
Usually, Theia is integrated as an iframe. There are some assumptions that it sits in the document.body element. We should be able to remove that restriction if you could elaborate your motivation and requirements.

**Comment by linpengfei** [comment]
@svenefftinge In fact,my angular app have some tools,every tool is a module,I can use router to decided what tool to be show to user ,I hope Theia is a module in the app.

**Comment by bdresdner** [comment]
Hi @linpengfei, were you able to get this to work?  I have to do the same thing.  Thanks
