### ISSUE TITLE
JavaScript files aren't highlighted 

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#1024]
Tested with [yangster-electron](https://github.com/theia-ide/yangster-electron) Release v1.1.0

Monaco seems not to recognize the JavaScript file

**Comment by svenefftinge** [comment]
The highlighting and the rest of the language support come with [`@theia/typescript`](https://www.npmjs.com/package/@theia/typescript). That extension is not inckuded in Yangster as it is meant to be used for YANG. If you think it should be included for YANG authors, please file the same issue over at [`theia-apps`](https://github.com/theia-ide/yangster-electron).
