### ISSUE TITLE
Enhance the Shell

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1025]
The Shell in Theia currently has two fixed side panels and a flexible main area, where the user can open and close widgets (editors and views). Also, drag & drop within the main area works, such that widgets can be split and so on.

We would like to extend this, such that the user can also adjust the side bars, using drag and drop and even can drag widgets from one of the side bars to another area and vice-versa. This will allow users to change the shell to fit their preferences.

Moreover a bottom panel should be added, that has the behavior of the sidebars, i.e. it is collapsible and is a drag and drop target for widgets.

**Comment by spoenemann** [comment]
Fixed with #1028 and #1082.
