### ISSUE TITLE
[markers] add a way to prune stale markers

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#1031]
I am switching between different Theia apps a lot. On each start, Theia reads the persisted markers from local storage. In my case these often refer to a completely different workspace and Theia app, so the neither the referred files nor the marker types exist in the current instance. The only way I found to get rid of the stale markers is to clear the local storage in the developer tools of Chrome.  This should be improved.

**Comment by svenefftinge** [comment]
The root cause for this is https://github.com/theia-ide/theia/issues/904

**Comment by vince-fugnitto** [comment]
fixed since markers are no longer kept in local storage https://github.com/theia-ide/theia/pull/2316

**Comment by vince-fugnitto** [comment]
fixed since markers are no longer kept in local storage https://github.com/theia-ide/theia/pull/2316
