### ISSUE TITLE
modular editor with language services

### ISSUE THREAD

**Issue by veeramarni** [theia-ide/theia#1033]
Thanks for the very useful project. I sincerely apologize if this is not the place to post this question if not please let me know whether StackOverflow is the right place for it.

I like the architecture of this project which is a plug and play with container modules. So I want to customize the editor part just the monaco package `@theia/monaco` and maybe `@theia/languages` packages for the browser needs. I want to eventually test it by converting into a react project similar to [this project](https://github.com/superRaytin/react-monaco-editor). Instead of using the original `monaco-editor`, `@theia/monaco` comes with some additional features such as QuickOpenModel, TextModel, Widgets, languages etc. so I want to experiment this to make it work independently.

I have started to create this for experimental need [here](https://github.com/veeramarni/theia-editor). But I could not have it running as it fails with error `monaco is undefined`. I looked into this project and I'm not sure how the `monaco` will be injected in the `dom`. If you could give me some insight would be great.

**Comment by akosyakov** [comment]
Monaco is loaded by `@theia/monaco` extension: https://github.com/theia-ide/theia/blob/cba7536ed303ab6a51bb6da8155f014539dc7012/packages/monaco/src/browser/monaco-browser-module.ts#L13-L14

If you try to import monaco before loading the monaco extension it is not going to work.

**Comment by veeramarni** [comment]
looks to be the issue.
