### ISSUE TITLE
[languages] Allow languages to override command registration

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#1034]
Currently, we have a problem in the theia-full docker image https://github.com/theia-ide/theia-apps/issues/13 because both, yangster and go, override the `DefaultCommands` in order to do side-effects when the language server registers a command to the client.

We should add a language-specific hook to interact with the external command registration.

**Comment by akosyakov** [comment]
@JanKoehnlein to migrate to a new `monaco-languageclient`, we will need to have a single commands instance for all languages. Would it be possible to rewrite go and yangster that they contribute commands to global command registry instead?
