### ISSUE TITLE
[Theia][UI]Vertical scroll bar hide the last char of the key accelerator in the command menu list

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1038]
Last char of the keyboard accelerator is hidden by the vertical scrollbar in the command menu list(CTRL + SHIFT + P)
![peek2018-01-09 menuwithscroll](https://user-images.githubusercontent.com/419051/34724262-2d1b3196-f51b-11e7-9410-4dfa5b0add40.gif)

**Comment by epatpol** [comment]
I guess we could have padding so that nothing gets under the scrollbar (unlike in the editor for example).
