### ISSUE TITLE
Embedding Theia on an existing page

### ISSUE THREAD

**Issue by tritao** [theia-ide/theia#1045]
Hey, really nice work so far on Theia so far!

I was wondering if there is any documentation on how to embed Theia into an existing page?

And how to customize builds (for instance, enable/disable extensions by default)?

**Comment by akosyakov** [comment]
> I was wondering if there is any documentation on how to embed Theia into an existing page?

Right now only with iframe. There is an assumption that Theia should be attached to `document.body`. Please open a feature request if in your case iframe is not enough.

> And how to customize builds (for instance, enable/disable extensions by default)?

[Theia extensions](https://www.npmjs.com/browse/keyword/theia-extension) are node packages as well as [Theia applications](https://github.com/theia-ide/theia-apps/blob/master/theia-docker/latest.package.json). You can compose a new application package with extension packages and use [Theia CLI](https://github.com/theia-ide/theia/blob/master/dev-packages/cli/README.md) to build and start it.

**Comment by spoenemann** [comment]
>> I was wondering if there is any documentation on how to embed Theia into an existing page?

> Right now only with iframe. There is an assumption that Theia should be attached to document.body. Please open a feature request if in your case iframe is not enough.

Now there is a way to do it without iframe: Create a subclass of FrontendApplication, register it via dependency injection, and override `getHost` to return some HTML element. The default returns `document.body`.

**Comment by tritao** [comment]
Thanks, we will check it out when we get a chance.

**Comment by hojas** [comment]
How to do this specifically?

**Comment by johnwiseheart** [comment]
Also interested:

> register it via dependency injection

How would this look, @spoenemann?

**Comment by spoenemann** [comment]
* Create a subclass of FrontendApplication (`@theia/core/lib/browser/frontent-application`)
 * Override `getHost()` so it returns the DOM element where the IDE shall be embedded.

Default implementation:

https://github.com/theia-ide/theia/blob/63365dc1d787df19f47898a2aa0204bb4c2dadda/packages/core/src/browser/frontend-application.ts#L128-L138

**Comment by johnwiseheart** [comment]
Hey @spoenemann, thanks for the update. I have created a minimal repo to try to help out this issue, and once we solve it I can add an example for future use. On my repo, I have gotten much closer to things working - but I am running into the issue:

```
Uncaught Error: Could not unbind serviceIdentifier: FrontendApplication
    at Container.unbind (container.js:174)
    at Container.rebind (container.js:166)
    at eval (container.js:280)
    at ContainerModule.inversify_1.ContainerModule [as registry] (index.tsx:28)
    at Container.load (container.js:113)
    at runApplication (index.tsx:34)
    at eval (index.tsx:53)
    at Object../src/index.tsx (main.js:9405)
    at __webpack_require__ (main.js:20)
    at eval (webpack:///multi_(:8082/webpack)-dev-server/client?:2:18)
```

If I try to just call `bind(...)` instead of `rebind(...)`, I get:

```
webpack:///./src/index.tsx?:49 Error: No matching bindings found for serviceIdentifier: MyFrontendApplication
    at _validateActiveBindingCount (webpack:///./node_modules/inversify/lib/planning/planner.js?:62)
    at _getActiveBindings (webpack:///./node_modules/inversify/lib/planning/planner.js?:48)
    at _createSubRequests (webpack:///./node_modules/inversify/lib/planning/planner.js?:85)
    at Object.plan (webpack:///./node_modules/inversify/lib/planning/planner.js?:136)
    at eval (webpack:///./node_modules/inversify/lib/container/container.js?:317)
    at Container._get (webpack:///./node_modules/inversify/lib/container/container.js?:310)
    at Container.get (webpack:///./node_modules/inversify/lib/container/container.js?:230)
    at runApplication (webpack:///./src/index.tsx?:43)
    at eval (webpack:///./src/index.tsx?:53)
    at Object../src/index.tsx (main.js:9405)
```

Is there a better way that I should be binding my subclass, or perhaps I am just doing something wrong here?


My repo: https://github.com/johnwiseheart/theia-embedded-demo/blob/master/src/index.tsx

**Comment by spoenemann** [comment]
You need to make sure the modules are loaded in the correct order, in particular the `frontendApplicationModule` from `@theia/core` needs to be loaded before your own one.

I never tried to manage the module loading order myself, always took the one generated by [@theia/cli](https://www.npmjs.com/package/@theia/cli).

**Comment by spoenemann** [comment]
Which documentation do you mean?

**Comment by johnwiseheart** [comment]
Documentation on how to run theia embedded in a larger web-app - aka my example repo (and I could do a small write-up explaining)

**Comment by spoenemann** [comment]
I guess that should go to https://www.theia-ide.org/doc/

The source is here: https://github.com/theia-ide/theia-website

**Comment by sanakanchha** [comment]
@johnwiseheart looking for something similar.. is there a doc I can look into? If you could add a readme to your repo, that would work as well, thanks.

**Comment by MasterMann** [comment]
While getHost() rebinding works for most components, I noticed that some have a hardcoded dependency on document.body, including notification alerts and command bar (2nd one is part of default Monaco packages). That leads to them not showing on screen at all.

**Comment by spoenemann** [comment]
@MasterMann please create a separate issue about that. We should probably refactor such services so they use the host element defined in the FrontendApplication.

**Comment by diloreto** [comment]
Thanks team Theia! How would Theia work if we wanted to embed it into a website/webapp and allow every team to work independently? If we install and run this from a server (and then embed on the page), wouldn't all users share the same files? We would every team to be able to run the editor from our web app, and then connect to their specific version control software (GitHub/GitLab) - basically multi-tenant Theia. Thoughts?

**Comment by spoenemann** [comment]
Running the IDE in multi-tenant mode is not in the scope of the Theia project. You can use something like https://www.gitpod.io/ for that.

**Comment by diloreto** [comment]
Thanks @spoenemann for the link. Given how quickly this could help scale the project, maybe multi-tenancy could get on the roadmap?

**Comment by spoenemann** [comment]
I don't think it will get on the roadmap, it's rather something to be solved by other projects building on top of Theia (or VS Code). Eclipse Che is another example of such a project.

**Comment by maxloosmu** [comment]
hi, is there a way to embed 3 or more IDEs inside a HTML page?  
```
        <div class="columns is-desktop">
          <div class="column is-3">
          <!-- First bottom quarter column -->
          <section class="section">
            <h1 class="title"><b>CHAPTERS</b></h1>
          </section>
        </div>
        <div class="column is-3">
          <!-- Second bottom quarter column -->
          <section class="section">
            <h1 class="title"><b>Embedded Repo 1</b></h1>
          </section>
        </div>
        <div class="column is-3">
          <!-- Third bottom quarter column -->
          <section class="section">
            <h1 class="title"><b>Embedded Repo 2</b></h1>
          </section>
        </div>
        <div class="column is-3">
          <!-- Fourth bottom quarter column -->
          <section class="section">
            <h1 class="title"><b>Embedded Repo 3</b></h1>
          </section>
```

**Comment by maxloosmu** [comment]
hi @spoenemann , thanks, i've tried last week, but no one has responded yet...
[https://community.theia-ide.org/t/how-to-open-3-or-more-tabs-in-a-theia-ide-in-a-html-file-programmatically/2874](https://community.theia-ide.org/t/how-to-open-3-or-more-tabs-in-a-theia-ide-in-a-html-file-programmatically/2874)
