### ISSUE TITLE
[theia] Need a clear distinction between the navigator  and the editor

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1057]
We need a clear distinction between the navigator and the editor. Both use the same background colour. If you look at the sidebar menu, the background is another colour and the user can see a proper distinction between the side menu-bar and the navigator or 
![peek 2018-01-15 10-14 nodistinction betweennavigator-editor](https://user-images.githubusercontent.com/419051/34949480-34ea95ca-f9de-11e7-81b6-edb1a4430bed.gif)
editor. The distinction is not there between the navigator and the editor

**Comment by svenefftinge** [comment]
Just so you are aware, the fact that the separator line is not always shown is because you are not running on the default zoom-level.

**Comment by svenefftinge** [comment]
We are going to make layouts quite flexible, so that you can move any widget anywhere. Different backgrounds will therefore not work.

**Comment by lmcbout** [comment]
I don't know exactly what is the default zoom-level, but there is more than just one window size when the line separator is not shown. Here another video when the separator is not visible , with
![peek 2018-01-16 nodistinction betweennavigator-editorzoom](https://user-images.githubusercontent.com/419051/34989710-9477af24-fa91-11e7-8ef2-3cb32f7831b3.gif)
 a different size:

**Comment by hexa00** [comment]
@lmcbout you can use Ctrl-0 to get to the default zoom level (that's Ctrl-zero)

**Comment by epatpol** [comment]
A different tone of "gray" or the editor color would help also, I think it's like that in Atom and vscode afaik.

**Comment by lmcbout** [comment]
Using a different background make a good difference. Theia with three editors and navigator and the outline view,
1-  as it is currently:
![theiabeforeissue_1057](https://user-images.githubusercontent.com/419051/35102506-242af05e-fc31-11e7-81fc-b923b4f0377e.png)

2- only change the editor background a with "theia-layout-color2"
![theiaonlyeditorissue1057](https://user-images.githubusercontent.com/419051/35102598-5648fcf2-fc31-11e7-8cbc-13a15a8b28dc.png)

3-  change the editor and the margin beside the editor with "theia-layout-color2"
![theiaafter marginandeditorissue1057](https://user-images.githubusercontent.com/419051/35102881-3a60b5ba-fc32-11e7-8ad1-95858c38b11e.png)

**Comment by svenefftinge** [comment]
Besides that it doesn't look good (IMHO), it won't solve the issue as it only increases contrast between editors and non-editors (see https://github.com/theia-ide/theia/issues/1057#issuecomment-357777308)

**Comment by epatpol** [comment]
#2 and #3 increases the contrast which makes it easier to see the limits of the editor and the panel on the side. However it greatly decreases editor usability in itself with the contrast being wrong with the text. I agree with above and think we should wait until flexible layout is in and see if we can improve something then.

**Comment by vince-fugnitto** [comment]
there is a distinction between editors/widgets with the added border
