### ISSUE TITLE
NAVIGATOR_CONTEXT_MENU is not exported

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/theia#1059]
https://github.com/theia-ide/theia/blob/4a9d238eb67a2f5f7c6124128ef1373aae18e47b/packages/navigator/src/browser/navigator-menu.ts#L13

This is not a bug, but better to support I think.
The NAVIGATOR_CONTEXT_MENU const is not exported, so we as extension developers, can't contribute our Menu/Command into Navigator Widget.

**Comment by AlexTugarev** [comment]
You can import it from `@theia/navigator/lib/browser/navigator-menu`.

**Comment by huyuwen** [comment]
Yes, thanks for quickly support.
