### ISSUE TITLE
Application shell widgets must take focus on activation

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1061]
When a widget is activated, its `onActivateRequest` method is invoked. However, the default implementation does nothing! For widgets that are added directly to the application shell, this is a problem, because ApplicationShell tracks the active widget through a FocusTracker, which listens to focus changes. So if a widget that is added to the shell does not implement `onActivateRequest`, it will never be seen as active. This causes peculiar side effects; for example the tab bar context menu commands operate on the current (last active) widget, so doing right-click and _Close_ on a widget's tab can cause the wrong tab to close (the last one that took focus instead of the one that was right-clicked).

I fixed this problem for the already implemented views in #1028, but it remains an issue for every new Theia widget. It is not obvious for widget implementers that they need to take care of the focus.

**Comment by spoenemann** [comment]
One possible solution could be to create a common abstract superclass for all application shell widgets that has some default behavior regarding focus, e.g.

```
    protected onActivateRequest(msg: Message): void {
        this.node.focus();
    }
```

However, this works only if the `node` of the widget can take focus. HTML elements that do not have any default user interaction, such as `div`, are focusable only if the [tabindex](https://developer.mozilla.org/de/docs/Web/HTML/Global_attributes/tabindex) attribute is set.

**Comment by svenefftinge** [comment]
Instead of solving it generically, which seems to be hard. We could maybe improve the error reporting for widgets, that didn't get focus.
