### ISSUE TITLE
[terminal] add padding to the left

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1064]
The terminal should get some space on the left-hand side as soon as
https://github.com/xtermjs/xterm.js/pull/1208 is merged and consumed by us.

**Comment by svenefftinge** [comment]
I see a comment in the code https://github.com/theia-ide/theia/blob/master/packages/terminal/src/browser/terminal.css#L21

But I don't really understand what the issue is. At least I could move the `padding-left`up to the `.terminal-container` class it looks good.

**Comment by mofux** [comment]
@svenefftinge I think you are right, adding a left padding to the parent container should work fine as of now. https://github.com/xtermjs/xterm.js/pull/1208 is especially useful if you want to maintain a padding to the right, top or bottom edges while still having the scrollbar of the viewport filling the whole space.
