### ISSUE TITLE
'Format Document' command isn't functional in Java Language.

### ISSUE THREAD

**Issue by DustFinger001** [theia-ide/theia#1068]
Clicked the menu item 'Format Document' is no effect,When editing a java source code document.
![image](https://user-images.githubusercontent.com/16345979/35024107-afa45ee0-fb78-11e7-8c8e-4599f4c191ce.png)
But in a javascript document, this command would preformed an act of expectation.
![image](https://user-images.githubusercontent.com/16345979/35024222-3a37d03c-fb79-11e7-95d6-efde7dd66164.png)
And I want 'Format Document' command is functional in a **custom language**. what should l do ?

**Comment by svenefftinge** [comment]
It is part of the language server protocol, that Theia supports. Does your language have a language server?

**Comment by DustFinger001** [comment]
My custom language had not have a language server, i will work it out.
The 'Format Document' was not working in java language. Was it a issue or to-do?

**Comment by svenefftinge** [comment]
https://github.com/eclipse/eclipse.jdt.ls supports it so it should work.
@gorkem Could it be that the java LS expects specific settings on initialize to enable formatting?

**Comment by gorkem** [comment]
@svenefftinge There should not be anything specific I will check it out.

**Comment by gorkem** [comment]
This is due to initialization issue as described on https://github.com/eclipse/eclipse.jdt.ls/issues/601. It is also affected #1577
