### ISSUE TITLE
[tests] make the UI tests contribute to coverage report

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#107]
The pull request to add test coverage reporting (https://github.com/TypeFox/Theia/pull/97) is reporting the coverage of the Mocha unit tests. I wonder if we cold make the Selenium tests also contribute to the coverage report.

**Comment by bd82** [comment]
If you instrument code with istanbul it will save the coverage information in the
[**window.__coverage__**](https://github.com/gotwarlost/istanbul/blob/89e338fcb1c8a7dea3b9e8f851aa55de2bc3abee/test/browser/support/index.html#L44) global variable.

So if you ensure the selenium tests run on **instrumented client** source code,
you can extract this coverage information from the browser after each test/suite (probably using: [executeScript](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html#executeScript-java.lang.String-java.lang.Object...-))

Now that the coverage information is available in the node.js process running selenium.
you can aggregate it and write it to a file. 

However I'm not sure UI testing is really relevant for code coverage.
It will certainly increase the coverage status, but would it be a real increase?
Just opening the login screen for many applications could cause 50% statement coverage
but ti does not mean that those 50% of the statements are actually properly tested.

**Comment by hexa00** [comment]
Indeed I think what we want more is to have Units test that can run in the browser context.

At the moment we only have those for node.

I'm looking at https://github.com/testem/testem with https://github.com/testem/testem/tree/master/examples/coverage_istanbul and possibly jasmine + https://github.com/jasmine/gulp-jasmine-browser

The idea would be to have  test suite that can:
 - Run node unit tests
 - Run browsers unit tests in chrome and possibly others
 - Support LCOV output code coverage for node and browser tests

**Comment by hexa00** [comment]
This is done now.
