### ISSUE TITLE
[Java] Handle commands expected by eclipse.java.lsp

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1078]
The Java language server seems to expect a couple of commands to be available on the client.
For example, on first start when the classpath is incomplete, we see a message with three options.

<img width="722" alt="screen shot 2018-01-18 at 14 30 02" src="https://user-images.githubusercontent.com/372735/35100432-1d5835cc-fc5c-11e7-8987-89e1026e7f5d.png">

Clicking e.g. on the first results in the following error message:
```
The command 'java.ignoreIncompleteClasspath.help' cannot be executed. There are no active handlers available for the command.
```

**Comment by tsmaeder** [comment]
See also #4050. To fix this for pure Theia language server extensions, thought, I guess it would have to be addressed in monaco-languageclient.
