### ISSUE TITLE
[Tasks] potential improvement ideas

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1080]
In PR #690 there is a list of potential improvements for the Task extension. That PR page has a lot of things in it, and fails to load most of the time. So here's the list: 

~~- [ ] add "global" user-level task configurations, using user-storage~~ #1099
~~- [ ] add support for VS Code task configuration format, including ProblemMatchers~~ #1096
~~- [ ] Integrate output parser (original #605, latest: #653) . Each task configuration can, optionally, have a matcher sub-configuration, that contains information for the parser to identify interesting outputs, and parse them. The resulting parsed matches can then be sent to the client(s). e.g. a C++ build task might contain a matcher that can identify GCC errors and warnings, from which problem markers can be created.~~ #1102
~~- [ ] add support for "onStart" tasks, that are executed automatically upon a workspace being "started". e.g. initial cloning of git repos.~~ #1097
~~- [ ] Assisted task configuration creation, from the Run Task command. Open tasks.json in editor and add a skeleton for a new task configuration and let the user complete it.~~ #1098
~~- [ ] use a JSON schema to validate tasks config file, so we can have help in the editor, for the user to fill-in configurations correctly.~~ #1098
~~- [ ] fix issue: task terminal widget restore works well when the task is still running. But if it's no longer, TerminalWidget.start() fails to attach to the task's process, and fallbacks to creating an interactive terminal. In that instance the layout manager calls widget.start(), not the task service, so it can't, e.g. check if a process still exists and if not skip calling start().~~ #1103
~~- [ ] notifications about tasks being started / terminated: its a bit annoying to have to click on them to dismiss them. Would be cool to have auto-dismissed notifications, that dismiss after a delay.~~(#1081)
~~- [ ] add status bar contribution for tasks. e.g. the "show running tasks" status bar button in VS Code. Calls 'attach to running task' task command, that opens the candidate running tasks, in the quick open menu.~~ #1100

**Comment by svenefftinge** [comment]
edited (created #1081)

**Comment by marcdumais-work** [comment]
@svenefftinge done.
