### ISSUE TITLE
Have a Theia Help -> About dialog, where we can see application, extensions versions

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1084]
AT the moment it can be tricky for a user to find the exact version of Theia and misc extensions, they are running. This information is very important for troubleshooting reported issues. 

One way is to hunt down the package.json of the Theia application, but that might not always be obvious where that would be, e.g. when the user gets a baked-in docker image to connect-to. 

I think most users would expect to find this information under the "Help -> About" menu. There is something like that in Eclipse, where plug-ins are listed.

**Comment by hexa00** [comment]
Note that we should also have this in the metrics extension so that we can get it from prometheus

**Comment by svenefftinge** [comment]
@hexa00 could you elaborate a bit? It's not clear to me what you mean.

**Comment by hexa00** [comment]
@svenefftinge I mean we should expose the versions of theia and it's extension in the metrics extension so an API can fetch this remotely.

Thus in an environment we control we would not have to ask the user for the version we could just see  it using prometheus/grafan.

**Comment by akosyakov** [comment]
This information is available via application-package and used in the extension manager to display installed extensions for example.

**Comment by epatpol** [comment]
@akosyakov I would like to fetch that information and create a menu contribution for that. However the issue I have is that this menu contribution would not exist if the extension-manager isn't included in the theia app, and I feel like this help menu really should be part of a core app (To quickly fetch the version you have). I guess I would need to use the application-package, but where would the code live? Core seems like would add a dependency to application-package, and elsewhere might mean that this contribution would not always be there no?

**Comment by epatpol** [comment]
After splititng application-package I could theoretically fetch the info from the application-manager but to get to the frontend menu contribution I need to do some sort of service on the backend, and I feel like this would duplicate a bit of code that is already in extension-manager. Also if core depends on application-manager I guess extension-manager wouldn't need that explicit dependency anymore right?

**Comment by akosyakov** [comment]
> After splititng application-package I could theoretically fetch the info from the application-manager but to get to the frontend menu contribution I need to do some sort of service on the backend...

You should NOT use the application manager in the core extension, only the application package extension. The application manager is heavy and should be used only by the cli and the extension manager.

> and I feel like this would duplicate a bit of code that is already in extension-manager.

What do you want to reuse? If it is the case we should encapsulate such functionality in the application package itself.

As for now you can get installed extensions like that:
```ts
const appPck = new ApplicationPackage({ projectPath: process.cwd() });
const installedExtensions = appPck.extensionPackages;
```

**Comment by epatpol** [comment]
What other infos do you think could be useful in that about dialog? Extensions and their versions seem to be the obvious ones but looking at VScode they seem to show things like commit hash of that version, node version etc. If needed I could fetch some more information from the backend.
