### ISSUE TITLE
Add a revealWidget method to ApplicationShell

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1093]
Usually `activateWidget` is called after `addWidget` in order to make a new widget visible. In some cases the new widget needs to become visible without taking the focus. Due to #1061 it is not a viable solution to decline focus in the `onActivateRequest` method of the widget. We should add a method `revealWidget` to ApplicationShell, which should make a widget visible without changing the focus.

**Comment by akosyakov** [comment]
Could you try to call `Widget.show` instead: https://github.com/phosphorjs/phosphor/blob/4d787b32136861adae4ebadc6c877a130d0cb216/packages/widgets/src/widget.ts#L382

**Comment by spoenemann** [comment]
> Could you try to call Widget.show instead

I'm not sure whether that would be sufficient to also update the current title of the tab bar where the widget is contained.

**Comment by spoenemann** [comment]
No, it doesn't work. Maybe it would work if we adapt the processing of `'child-shown'` messages.

**Comment by akosyakov** [comment]
My concern is that if there is phosphor widget api to do it we should not invent our own, but make sure that existing is working propertly. If `show` is designated to do something else i am fine with new api.

**Comment by spoenemann** [comment]
`show()` makes a widget visible if it has been hidden with `hide()` before. It does not take care of switching to the correct tab in a tab bar.

**Comment by akosyakov** [comment]
ok
