### ISSUE TITLE
[git] Support `--depth x` option for the `git clone` command

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1095]

**Comment by svenefftinge** [comment]
Could you elaborate why you want to expose this option through the UI?

**Comment by kittaakos** [comment]
I wanted to expose it to the core Git interface so for instance, when writing tests, we can clone a repository without history to speed up things.

**Comment by kittaakos** [comment]
Meanwhile, it turned it, it was a bad idea.

 - From the UI, we never planned to support it.
 - From a terminal, inside Theia it is possible.
 - From the tests, and the was the **main goal** of this task, it does not make any sense. No historical information, no branches, or revisions, nothing can be retrieved from a shallow clone. It does not help the testing (speed) at all.

Closing.
