### ISSUE TITLE
Assist the user in creating task configuration

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1098]
ATM is the user has no or an empty task configuration file (tasks.json), the quick command dialog will be empty, for tasks. 

![peek 2018-01-22 10-02](https://user-images.githubusercontent.com/25749063/35227179-5a58a4dc-ff5b-11e7-81ae-d7b0da2d7912.gif)

In VS Code, a skeleton tasks.json is created and opened in an editor, in this situation. 

Maybe we could do something similar. 

Bonus: add a JSON schema for tasks.json, so that the editor knows about the file format's, can suggest completions, validate the content.

**Comment by svenefftinge** [comment]
This is now relatively easy to do (see #3078)

**Comment by marcdumais-work** [comment]
@svenefftinge I quickly went through the PR. Can you confirm that all we need is to do, to get completion assist when editing a task configuration, is to provide a Task schema? 

https://github.com/theia-ide/theia/pull/3078/files#diff-2a4648379e27a94a05b69fbe6595b486R21

**Comment by svenefftinge** [comment]
Yes, but we need to collect the contributions from task kind providers. AFAIR we don't have that yet, but we need to support it if we want to support vs code extension API.
