### ISSUE TITLE
Better connection failure handling

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#110]
Currently, if the backend becomes inaccessible, some errors are printed in the JS console.  We will eventually need a more friendly handling of these errors.  We will also need to notify the user that the backend can't be reached and handle reconnection.

**Comment by akosyakov** [comment]
Are you referring to `failed: Error in connection establishment: net:ERR_CONNECTION_REFUSED`?
I did not find a way to catch it programmatically. It seems to be just logged to the console from `WebSocket` implementation by the browser.

**Comment by akosyakov** [comment]
See http://stackoverflow.com/questions/43012334/silence-neterr-connection-refused

**Comment by epatpol** [comment]
We have this now with the status bar changing color no? Although I'm not exactly sure about the error handling part.
