### ISSUE TITLE
Support parsing tasks output in a nice way

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1102]
In VS Code they have Problem Parsers, that are quite nice and can be configured to use Problem Matchers, to parse almost anything. 

For example, when we eventually want to do builds, using tasks, we may want to parse the build's output according to criteria that are specific to the language/compiler being used, and be able to detect errors/warnings from the output, and report them to the user (create problem markers?). 

We have an unmerged WIP that is a simplified version of what they have in VS Code. We called it "Output Parser / Output Matcher". See: (original #605, latest: #653)

**Comment by svenefftinge** [comment]
It would be good, to be able to contribute hyperlinks, as well.

**Comment by marcdumais-work** [comment]
@svenefftinge Do you have an example of this in mind?

**Comment by elaihau** [comment]
does #5024 resolve this issue? @marcdumais-work

**Comment by elaihau** [comment]
I will close it for now. please reopen if you feel needed.
