### ISSUE TITLE
[git] git log parser: errors when paragraphs in commit message

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#1104]
Happens in branch "git-diff".
If the commit message respectively the message body contains two "newline", then the git log output gets splitted in a wrong way.
 
https://github.com/theia-ide/theia/blob/d98a90919deeae6eed3b269bec80bc8df3611ee3/packages/git/src/browser/diff/git-diff-service.ts#L100

**Comment by kittaakos** [comment]
@jbicker, you tell me how urgent this is. I have to adjust the `git log` parser a bit so ping me when I have to start to work on this.

**Comment by jbicker** [comment]
@kittaakos, can this be closed?

**Comment by kittaakos** [comment]
Can you please verify it?

**Comment by kittaakos** [comment]
@jbicker ping. Is this still valid? As far as I know, you used this functionality in the Git history.

**Comment by jbicker** [comment]
@kittaakos pong. No. Works fine for weeks ;-) I'll close it.
