### ISSUE TITLE
Support language specific editor preferences

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1106]
Makefile syntax requires tab character for indentation, not spaces.  Is it possible to do this currently with Theia?  If so, how?

**Comment by hexa00** [comment]
You can set the monaco editor settings in .theia/settings.json IIRC
@epatpol I think you would know more ?

**Comment by epatpol** [comment]
Yes you can set settings available [here](https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-preferences.ts#L291), however I'm not sure if the monaco editor supports doing tabs instead of spaces... Maybe it's there somewhere in their documentation I'm not sure.

**Comment by simark** [comment]
But this is not really practical if you need other files to use space as indentation.  I guess my question is more, how do we better handle per-file indentation settings.  In VScode you can click in the status bar to change them quickly.

**Comment by akosyakov** [comment]
In VS code also such preferences can be configured per a language.

**Comment by epatpol** [comment]
Yes there should be different editors for different file types, maybe not completely different editors like in Eclipse (open with -> tons of choice) but maybe a user could create a new "editor", associate custom preferences to this one only and decide to use this one for certain files etc. 

I'm not even sure this setting exists for monaco to solve this issue though.

**Comment by akosyakov** [comment]
It is not supported at the moment. We can do it like in VS code: https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

**Comment by kittaakos** [comment]
> Yes there should be different editors for different file types

Related? https://github.com/theia-ide/theia/issues/335
