### ISSUE TITLE
[git][Enhancement] Discuss about git navigator view, what to include and how to show it

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1112]
Suggestion to discuss about the git navigator view: 
- Prevent scrollable for the git buttons when navigating through the file/folders, the scroll should apply only to the file/folders and keep the git buttons always visible
- Insert a separator between the file/folders and the git buttons, it would make it easier to see the git options.
- What git commands should be available on the git navigator view or through a git sub-menu?
   - git diff
   - git merge
   - git tree
   - others

**Comment by kittaakos** [comment]
> Prevent scrollable for the git buttons when navigating through the file/folders, the scroll should apply only to the file/folders and keep the git buttons always visible

This seems to work as expected.

![gh-1112](https://user-images.githubusercontent.com/1405703/35377858-12740c8a-01b1-11e8-8148-189d85ac2b62.gif)

**Comment by vince-fugnitto** [comment]
@lmcbout can we close the issue? or perhaps update the issue?

**Comment by lmcbout** [comment]
Lets close it, we can create a new ticket to discuss functionalite for the Git view when needed
