### ISSUE TITLE
Path does not handle dots gracefully when getting the name

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1132]
Path `/foo/a.b.c` will return `a.b` when getting the `name` property.
See failing test case.

```diff
diff --git a/packages/core/src/common/path.spec.ts b/packages/core/src/common/path.spec.ts
index 14eccae9..bf192e71 100644
--- a/packages/core/src/common/path.spec.ts
+++ b/packages/core/src/common/path.spec.ts
@@ -109,4 +109,9 @@ describe("Path", () => {
         assert.deepEqual(path.ext, '');
     });

+    it('dots should be handled gracefully for names', () => {
+        const path = new Path('/foo/a.b.c');
+        assert.equal(path.name, 'a.b.c');
+    });
+
 });
```

@akosyakov, could you please confirm whether this is a bug or not. I think it is.

**Comment by akosyakov** [comment]
It should be aligned with `path` from Node.js. If it is different then it is a bug.

**Comment by kittaakos** [comment]
Aligned with which method, is it [`path.basename`](https://nodejs.org/dist/latest-v8.x/docs/api/path.html#path_path_basename_path_ext)?

**Comment by akosyakov** [comment]
with [path.parse](https://nodejs.org/dist/latest-v8.x/docs/api/path.html#path_path_parse_path)

**Comment by kittaakos** [comment]
Same behavior with node.
```js
console.log('a.b' === require('path').parse('/foo/a.b.c').name); // true
```

One has to use `path.base` instead. I am closing this.
