### ISSUE TITLE
[git] Having a counter to indicate the numbers of modified files in the branch

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1144]
In the Git view, it would be nice ti have a counter beside the "CHANGED"  label indicating how many files  are modified

**Comment by svenefftinge** [comment]
I find it relatively useless to have it there, but it would be nice to have such overlay on the widget label, such that you can see, you have changes without activating the panel.
The status bar indicator, does the same, though, so not super important IMHO.

**Comment by kittaakos** [comment]
> a counter beside the "CHANGED" label

Related: #758.

I am planning to [add a counter since we might want to truncate the result set](https://github.com/theia-ide/theia/issues/758#issuecomment-341073398) in case it is huge.

**Comment by lmcbout** [comment]
I am testing with the clangd and llvm project. When switching from branch "release-16" to "master" branch, there are so many items in the git repo that it is hard to find.
 Another option could be to be able to filter the content. For example, show me the "D" files, show me the "U" files, show me the "M" files. This would reduce the number of files shown in the navigator

![image](https://user-images.githubusercontent.com/419051/35514156-4addf87c-04d3-11e8-876d-0daa621ecd6c.png)

**Comment by svenefftinge** [comment]
> When switching from branch "release-16" to "master" branch, there are so many items in the git repo that it is hard to find.

Why would you do that? IMHO we should not work on solving such impractical use cases these days (and maybe never). What is important, though is that doing such things by accident should not blow up the frontend or backend. So I think we need to have reasonable limits of e.g. how many file changes we show in the UI.

**Comment by lmcbout** [comment]
A user can work on two or more branches of a project, this issue will be the same when he has to switch from one branch to another, many files will show as "D", "U",  "M", etc...
One branch could be new development, one or two branches for bug fixes.

**Comment by kittaakos** [comment]
> A user can work on two or more branches of a project, this issue will be the same when he has to switch from one branch to another, many files will show as "D", "U", "M", etc...
> One branch could be new development, one or two branches for bug fixes.

Most likely, it is just me, but I do not understand this. Could you please clarify?

**Comment by lmcbout** [comment]
When I do development, I create a branch for that new development ex: dev_Task1
When I received a new ticket to fix something urgent, I will create a new branch ex: fix_issue_1
May be I did  some changes on a branch which is not merged yet, because of a review ex:issue_2

Now I am working on three branches.  When I changes branches with Theia git extension, There will be files with the tag "U", "M", "D", ....
For example, on the branch "fix"issue_1", I have to change all "Copyrights", so all files will show in the git view as "M" in this case . So there will be many changes shown.

**Comment by hexa00** [comment]
@lmcbout when you switch branches you should clean it up...

1st you should never have a M there because this means your switching a branch with local changes.
If you have a U git means you need to clean your working directory.
Same with D

So I don't think a counter is helpful... maybe we could have a git clean command instead? but that's a bit scary for me to use in a UI...

In general however I do think it would be helpful to group the files based on the status changed like git status does... maybe using a column sort ?

**Comment by marcdumais-work** [comment]
closing this, please re-open if there is more to add
