### ISSUE TITLE
[git] Have a tool-tip when hovering the element in the git navigator view

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1145]
In Git view, there should be a tool-tip to let the user know what the letter means: "U", "M", ... when hovering it.
![image](https://user-images.githubusercontent.com/419051/35459143-05ad53ce-02ad-11e8-8395-20b0dac1eae0.png)

**Comment by jbicker** [comment]
I've added such tool-tips in https://github.com/theia-ide/theia/pull/1092.
