### ISSUE TITLE
[git]Error 128 need to be handled

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1162]
A git error (128) to be handle, otherwise it prevent the browser to be updated :
Error on the server node:

 The command `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128. The caller should either handle this error, or expect that exit code.
fatal: This operation must be run in a work tree

[2018-01-29T16:19:34.363Z] ERROR: Theia/22477 on elxa8z6zp12:
    Error occurred while synchronizing the status of the repository. [ 'file:///home/lmcbout/yyy/aLongProjectNameToTest.git',
      { GitError: fatal: This operation must be run in a work tree
    
        at new GitError (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:79:28)
        at Object.<anonymous> (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:155:27)
        at step (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
        at Object.next (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
        at fulfilled (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
        at <anonymous>
        name: 'GitError',
        result: 
         { stdout: '',
           stderr: 'fatal: This operation must be run in a work tree\n',
           exitCode: 128,
           gitError: undefined,
           gitErrorDescription: undefined },
        args: 
         [ 'status',
           '--untracked-files=all',
           '--branch',
           '--porcelain=2',
           '-z' ] } ]

**Comment by marcdumais-work** [comment]
@lmcbout Do you have some context information?

**Comment by lmcbout** [comment]
If I run the command in the theia repository from a terminal, I get an error alos:
 git status --untracked-files=all --branch --porcelain=2 -z
error: option `porcelain' takes no value

**Comment by kittaakos** [comment]
OK, then please check your Git version and share it with us. Thank you!

**Comment by kittaakos** [comment]
Please bump up to a newer version as the [minimum is 2.11](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites). Once you are done, please re-verify this issue and update or close this ticket. Thanks!

**Comment by lmcbout** [comment]
Tested with latest git (2.16.1) in a terminal, seems OK
