### ISSUE TITLE
Add a toggle button for the bottom panel

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1168]
Tab bars created by the dock panel in the bottom area of the application shell should include a button that invokes the `Toggle Bottom Panel` command (see #1082).

**Comment by svenefftinge** [comment]
The description sounds like you want to add it to every tab, but I think it should only be added to the top right tab bar in the bottom panel. 
People in the office are concerned about not having an 'open bottom panel' button, too. 
Could we move out the bottom panel when the mouse is close to the bottom, maybe? I.e. similar to how the dock on OSX hides/reveals?

**Comment by spoenemann** [comment]
We could, but that might be a bit annoying for some users. Maybe allow to switch that behavior off?

**Comment by svenefftinge** [comment]
> We could, but that might be a bit annoying for some users. Maybe allow to switch that behavior off?

Right especially since the status bar below is actionable. So whenever you go with the mouse cursor down to the status bar the panel would peak out. Not nice. We need another approach.

**Comment by spoenemann** [comment]
We could start with a button in the status bar.
