### ISSUE TITLE
"The file <x> had been changed on the file system" dialog pops-up excessively

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1169]
Reported by internal users. When user typing in a file the pop-up below is triggered excessively.

At first look,  this might be a situation where adverse network conditions are present, causing the editor to somehow enter a weird state vs the saved file in the backend (vicious update cycle?) 

![image](https://user-images.githubusercontent.com/25749063/35570157-5aa0b78a-059c-11e8-9b46-97bc70f4377d.png)

**Comment by akosyakov** [comment]
Do they use Theia version which contains this commit: https://github.com/theia-ide/theia/commit/4a9d238eb67a2f5f7c6124128ef1373aae18e47b?

**Comment by hexa00** [comment]
I don't think they did at the time, this needs to be restested

**Comment by marcdumais-work** [comment]
thanks for the info @akosyakov - we will observe if this happens still and update or close this issue.

**Comment by marcdumais-work** [comment]
duplicate of https://github.com/theia-ide/theia/issues/1185
