### ISSUE TITLE
Preferences do not return a copy of the value 

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1173]
i.e 
```typescript
methodThatIsCalledSeveralTimes() {
    /* Here we get the preferences from the injected pref service */
    const prefValues: string[] = this.PrefService['testKey'];
    /* We can then modify that preference by adding stuff to it, and this would directly edit the array in the 
       service's preference cache, as it returned a reference in the first case */
    prefValues.push('something');
    /* Next time the function is called, prefValues will have 'something' in it (plus the preferences that were there before) */
}
```

**Comment by epatpol** [comment]
@akosyakov we could use http://phosphorjs.github.io/phosphor/api/coreutils/modules/jsonext.html#deepcopy wdyt?

**Comment by akosyakov** [comment]
What is the real issue? Why will someone change preferences like that?

**Comment by epatpol** [comment]
@akosyakov I discussed with @simark and I think it happens in cpp-contribution where the preference returns an array. You think we could leave it like that and just make sure preference consumers don't modify the values?

**Comment by akosyakov** [comment]
Could you point to code?

**Comment by epatpol** [comment]
I think this is it

https://github.com/theia-ide/theia/blob/master/packages/cpp/src/node/cpp-contribution.ts#L46

**Comment by akosyakov** [comment]
Ok, let's do it, otherwise, clients should not forget to copy before modifying. Pay attention that it should be implemented in `PreferenceService`, work for events and default values as well.

**Comment by akosyakov** [comment]
For time being, in the cpp extension an array should be spread.

**Comment by epatpol** [comment]
Ok that makes sense. I agree with you about adding too many dependencies to core however (see comments in the PR). I used `clone` as it was the most downloaded clone related npm package, but maybe it's better if we implement a small function ourselves as the cases are limited?

**Comment by akosyakov** [comment]
Looked at yarn.lock, we already using `clone`, so it is fine.

**Comment by akosyakov** [comment]
Fixed by https://github.com/theia-ide/theia/pull/1175, preferences are not cloned, but frozen that clients cannot mutate them without copying, it let us to avoid unnecessary copying
