### ISSUE TITLE
Merge-Conflict Code Lens

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1180]
Resolving merge conflicts shall be supported by providing a code lens with actions for choosing one, none or both changes, similar to how Vs Code does it.

Here's the respective extension for vs code :
https://github.com/Microsoft/vscode/tree/master/extensions/merge-conflict

**Comment by AlexTugarev** [comment]
@svenefftinge how should we integrate the merge-conflict resolution? 

I assume it's injected into editor. currently, the diff viewer is opened for files with conflicts. should we open editor instead?

|theia|code|
|-----|-----|
|![2018-01-31 15 12 23](https://user-images.githubusercontent.com/914497/35627949-c0d8b7d8-069a-11e8-8022-96ec3c648d24.gif)|![2018-01-31 15 13 12](https://user-images.githubusercontent.com/914497/35627951-c33d33fa-069a-11e8-9dc2-47291416edad.gif)|

**Comment by akosyakov** [comment]
It looks like opening a diff editor, in this case of merge conflicts, does not make much sense.

**Comment by AlexTugarev** [comment]
That's also my opinion. But I started with integration with editor first, then we can have a look at Git view. BTW, I think in case of merge conflicts, the status should be `branch!` instead of `branch*`.

**Comment by kittaakos** [comment]
> the status should be branch! instead of branch*.

Yeah, and when you have everything staged, then `branch+`.

**Comment by kittaakos** [comment]
> the status should be branch! instead of branch*.

Follow-up: https://github.com/theia-ide/theia/issues/1183

**Comment by AlexTugarev** [comment]
Fixed in #1231.
