### ISSUE TITLE
[editor] Auto-save makes the editor loosing chars.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1185]
It looks like Theia is opening a fresh file each time an auto-save is triggered. When the file is large, it makes it easier to drop chars. Tested on a smaller file (10K) and the same happens, but harder to reproduce. 
Tested on a local computer: so no latency about the network, but it would also happen when the network is slow (some latency) between the server-client.

First video: typing + get popup looses some char even after selecting "Yes" in the popup Editor in dirty state
Test, typing at a different speed the text: "JACQUES"
We can see the popup and after pressing yes, a dirty state appears and we loose the letters"UES" 
![peek 2018-02-01 08-39typingpopupwithkey](https://user-images.githubusercontent.com/419051/35682291-3012814a-072e-11e8-87a7-e694fb61d581.gif)

Second Video: typing "jacques bouthillier"
Auto-save kicks-in and at the end, the text in the editor: "jacques boillier" Missing the letters: "UTH"
![peek 2018-02-01 07-45typing_missingchar](https://user-images.githubusercontent.com/419051/35682324-4ec14fea-072e-11e8-96ff-063e55e15e09.gif)

**Comment by marcdumais-work** [comment]
This also seems easier to reproduce with a smallish file, using a Docker image. Even more-so if the image runs remotely. 

W-A: Disable auto-save using preferences: 
in the user's home (e.g. /home/<user>/.theia/settings.json ) add this entry: 
```
{
   "editor.autoSave" : "off"
}
```

**Comment by akosyakov** [comment]
> When the file is large

@lmcbout how big is the file?

**Comment by lmcbout** [comment]
Hi Anton,

 here the script I use to create large file



You put it as executable

It will create the file in your current folder

ex: createBIGFile 1500000  -> create a file of 3 Meg  (The number is half the size )


BR

Jacques

________________________________
De : Anton Kosyakov <notifications@github.com>
Envoyé : 1 février 2018 09:39:19
À : theia-ide/theia
Cc : Jacques Bouthillier; Mention
Objet : Re: [theia-ide/theia] [editor] Auto-save makes the editor loosing chars. (#1185)


When the file is large

@lmcbout<https://github.com/lmcbout> how big is the file?
