### ISSUE TITLE
Pick-up tasks.json when it's created

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#1196]
`Task extension` picks-up `.theia/tasks.json` when a client opens a workspace. But the config file isn't picked-up when it's created in the already opened workspace.
It would be nice to be able to start using the commands from the newly created `.theia/tasks.json` w/o the need to reopen a workspace (F5).

**Comment by azatsarynnyy** [comment]
I've proposed a possible solution in PR https://github.com/theia-ide/theia/pull/1202

**Comment by marcdumais-work** [comment]
Thanks @azatsarynnyy . Will do a review ASAP

**Comment by azatsarynnyy** [comment]
Fixed in PR https://github.com/theia-ide/theia/pull/1202
