### ISSUE TITLE
[preferences] Preferences

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#12]
We should go with json-schema based user preferences.

A plugin should be able to contribute a schema and read the actual preferences.
Different scopes would be good, too.

In addition to good textual support like in vscode, we could provide a graphical editor (similar to atom) as well. For that we could use http://jeremydorn.com/json-editor/

**Comment by akosyakov** [comment]
I've put more thoughts into it and thinking about such design:
- `CommonPreferenceService` is a common preference API, very minimal and abstract over format, that provides basic capabilities, as was discussed in the PR.
- `PreferenceService` is a convenient preference API that implements `CommonPreferenceService` by delegating to its instance and provides an extension to the common API similar to it, but in terms of well-known js types, like `boolean`, `string`, `number`, `Array`, `object`.
- **possible** implementations of `CommonPreferenceService`:
   - `AbstractFilePreferenceService` is an abstract implementation that uses `FileSystem` for a file tracking and provides hooks for subclasses to react to file changes;
   - `JsonPreferenceService` implements `AbstractFilePreferenceService` to parse and save preferences in a single JSON file.
  - `CompositePreferenceService` is a composition of `PreferenceService`, it could be used to implement generic scoping, e.g. a composition of 3 instances of `JsonBasedPreferenceService` for `setting.json` to model default, workspace, and user settings.
  - `YamlPreferenceService` implements `AbstractFilePreferenceService` to parse and save preferences in a single YAML file, the same true for other formats.
  - `JsonRpcPreferenceService` delegates to the server side `PreferenceService`, could be added later to be used for big files, at the beginning we can use `JsonPreferenceService` directly on the client side.
- **possible** extensions (they extend by using not implementing) of `PreferenceService`, not `CommonPreferenceService`:
   - `WorkspacePreferenceService` is a programmatic implementation of workspace settings, with defaults, that uses `PreferenceService` to access user and project settings, which can be instances of `JsonPreferenceService` for `settings.json` in a user home and project directory.
    - `EditorPreferenceService` uses `PreferenceService` to provide a statically typed API for an editor part of settings. An instance of `WorkspacePreferenceService` will be provided for `EditorPreferenceService` as `PreferenceService`. It could also use `WorkspacePreferenceService` directly instead of `PreferenceService`, but I would stick with `PreferenceService` if it is possible.
   - `KeybindingPreferenceService` uses `PreferenceService` to provide a keybinding preference API similar to the preference API but in terms of keybinding types. `KeybindingPreferenceService` and `EditorPreferenceService` should only use `PreferenceService` but don't implement it. `PreferenceService` is their implementation details as well as for most extensions of `PreferenceService`.
   - `TaskPreferenceService` the same idea as for keybindings, but for tasks types.

So scoping and support of different formats can be achieved by composing and changing implementations of `PreferenceService`. inversify `named` annotation can be used to inject differently configured instances of `PreferenceService`. Extension developers can:
- use specialized statically typed preference API extensions, like `WorkspacePreferenceService`,  `KeybindingPreferenceService` and so on;
-  support new formats, cache, lazy loading strategies and so on., by implementing `CommonPreferenceService` and composing them with existent;
- provide a specialized preferences API for their plugins by using `PreferenceService`, or even more specialized API, e.g. `MyPluginTaskPreferenceService` can use `TaskPreferenceService` and provide API for my plugin's tasks.

For the start having `CommonPreferenceService`, `PreferenceService`, `JsonPreferenceService`  and `WorkspacePreferenceService` should be enough.

**Comment by akosyakov** [comment]
Could we also consider to work with a preference path, not a name, where a path is a set of strings, so `CommonPreferenceService` will look like:

```ts
export type Path = string | string[];
export interface PreferenceChanged {
  readonly path: Path;
  readonly oldValue?: any;
  readonly newValue?: any;
}
export interface CommonPreferenceService {
  readonly paths: Path[];
  has(path: Path): boolean;
  get<T>(path: Path): T | undefined;
  get<T>(path: Path, defaultValue: T): T;
  set<T>(path: Path, value: T): void;
  remove(path: Path);
  /**
   * I'm not conviced that is useful to provide an old and new value,
   * first, only the client knows how to properly convert them,
   * second the old value usually don't provide any interest, 
   * probably Event<Path> would be enough,
   * VS code somehow gets away even with Event<void>.
   */
  readonly onPreferenceChanged: Event<PreferenceChanged>;
}
```

It should provide a better editing experience, e.g:

```json
{
  'editor.foo.bar': 1
  'editor.baz': true
}
```

can be restructured to show a hierarchical nature

```json
{
  'editor': {
    'foo.bar': 1,
    'baz': true
  }
}
```

There following paths: `editor`, `editor.foo`,  `editor.foo.bar` and `editor.baz`.
If a value of bar is added, changed or removed then events should be fired for:  `editor`, `editor.foo`,  `editor.foo.bar`;
If a value of baz is added, changed or removed then events should be fired for: `editor` and `editor.baz`

**Comment by akosyakov** [comment]
It also would be nice to have `Path` type net to `URI`, with functions similar to `node`, since it could be useful in contexts outside of `URI`.

For example a path can be used to look up `PreferenceService` like in the following example:
```ts
export interface ConfigurationService {
  /**
   * Provide a preference service managing preferences in a user and project `${path}` files.
   */ 
  getConfiguration(path: Path): PreferenceService;
}

export const TaskPreferneceService = Symbol('TaskPreferneceService');
export interface TaskPreferneceService {
  version: number;
  tasks: Task[];
  readonly defaultTasks: Task[];
  readonly onChanged: Event<void>;
}

export class TaskPreferneceServiceImpl implements TaskPreferneceService {

  constructor(
    @inject(PreferenceService) @named(TaskPreferneceService) 
    protected readonly preferenceService: PreferenceService
  ) {}

  get tasks(): Task[] {
    if(this.preferenceService.has('tasks')) {
      const tasks = this.preferenceService.getArray<Task>('tasks', []);
      // merge with defaults;
      return tasks;
    }
    return this.defaultTasks;
  }

  get defaultTasks(): Task[] {
    return [
    ];
  }

  ...

}

export const taskModule = new ContainerModule(bind => {
  bind(TaskPreferneceService).to(TaskPreferneceServiceImpl).inSingletonScope();
  /**
   * Bind a preference service managing preferences in a user and project `tasks.json` files.
   */
  bind(PreferenceService).toDynamicValue(ctx => {
    const configurationService = ctx.container.get(ConfigurationService);
    return preferenceService.getConfiguration('tasks.json');
  }).whenTargetNamed(TaskPreferneceService).inSingletonScope();
})
```

PS

**Comment by svenefftinge** [comment]
_re: paths_  it would complicate the overriding logic a bit, also in most cases you don't override multiple properties of one kind (at least if I look at my settings). So I would not benefit from this feature. I would prefer a simple map for the different preference scopes, where the key is a string with the convention to use dot-separated identifiers (i.e. qualified names). So basically how it is done in vscode.

**Comment by svenefftinge** [comment]
To me a preference is a string-value pair, where the value can be a JSON object, JSON array or a primitive. We have three scopes (default, user, workspace).

- The `default preferences` are initialized on start, by calling all preference initializers. They are not changed afterwards.
- The `user preferences` shadow `default preferences`. They are loaded from a file in the user directory, that is watch for changes.
- The `workspace preferences` shadow `user preferences`.They are loaded from a file in the workspace directory, that is watch for changes. 

So there would be three preference services (default, user, workspace). They would run on the backend, while the frontend would have a proxy facade to the workspace facade.

**Comment by epatpol** [comment]
@akosyakov @svenefftinge thanks for the detailed comments! I see you've put quite a bit of thought in this, now I think I get what you meant by "minimal" and "convenient" in the comments.

As for the strings as paths, I'm not sure they're ideal/really needed. I understand it might be more modular but I'm not sure the use cases can justify adding that complexity.

I agree with the different scopes. @svenefftinge are the preference initializers called by the clients (i.e a client loads the default prefs into Theia before the config files are loaded) or the preference service loads all the defaults (which were passed down to it prior to the start, when installing a plugin for instance)?

**Comment by akosyakov** [comment]
re: in vs code they use paths, you can actually restructure

**Comment by akosyakov** [comment]
From programming perspective paths are kind of queries. One can fetch the value of a very deep property with them, without first getting JSONObject and then analyzing it down, so instead of:
```ts
const editorPreference = preferenceService.getObject<EditorPreference>('editor')
const fontSize = editorPreference ? editorPreference.fontSize || 12 : 12;
```
one does:
```ts
const fontSize = preferenceService.getInt(['editor', 'size'], 12)
```
but at the same time one can do something like:
```ts
preferenceService.has('editor')
```
just to check whether there are any editor properties.


But thinking about it again, it should be possible to add it later on the top of a name-value map.

**Comment by akosyakov** [comment]
Another question: How editors will get aware about new properties and their possible values?

Should I as an extension developer just register new content assist providers and report diagnostics for editors? It is already possible btw.

Or there should be preference metadata contributors which would be used by the browser part of the preference extension to integrate with editors?

**Comment by svenefftinge** [comment]
We had some more discussion about this offline. 
There doesn't seem to be much value in having the `path`concept instead of using plain strings, so let's go with simply strings.

On initialization of preferences for a preference we should have at least the following information:
```
{
    name: string
    value: any
    description?: string
}
``` 
Later we might want to add JSON schema validation information to constrain the values.

We might need to use promises when retrieving preferences because they might be obtained from remote services and also the frontend will obtain them from the backend through JSON-RPC.
