### ISSUE TITLE
Command Palette can only show 2 key cords of a keysequence

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#1200]

**Comment by hexa00** [comment]
See #472

**Comment by vince-fugnitto** [comment]
I'm closing as I believe the issue has been addressed, `key chords` are displayed correctly in the command-palette. Please re-open if this isn't the case :)

<div align='center'>

<img width="604" alt="Screen Shot 2019-06-20 at 9 17 12 PM" src="https://user-images.githubusercontent.com/40359487/59890902-1140fc00-93a1-11e9-9a80-dd42d19c1f25.png">


</div>
