### ISSUE TITLE
Switch to the latest typescript

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1209]
TS 2.7 was released: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by AlexTugarev** [comment]
can we also add `"typescript.tsdk": "node_modules/typescript/lib"` to `settings.json`?

**Comment by akosyakov** [comment]
@AlexTugarev What for?

**Comment by AlexTugarev** [comment]
vscode will use then version from `package.json` instead of the bundled one.

**Comment by akosyakov** [comment]
ok, it is fine with me, more about this setting: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions
