### ISSUE TITLE
[generator] Update the webpack generator to gracefully handle UMD modules

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1232]
Such as `jsonc-parse`. Before the `1.0.1` version on `jsonc-parse` we, were able to live with the UMD modules by adding them to the `noParse`section in the `webpack` configuration.

With the `1.0.1` version it does not work anymore. Fortunately, there is a [workaround](https://github.com/Microsoft/vscode-css-languageservice/issues/60#issuecomment-357656451).
```json
{
    test: /node_modules\/jsonc-parser/,
    use: {loader: "umd-compat-loader"}
}
```

Make sure that this change works for all currently ignored packages.

**Comment by kittaakos** [comment]
The fix only works on UNIX but fails on Windows. It seems the generated `bundle.js` is different. If I just copy the `bundle.js` generated on UNIX to the `examples/browser/lib/` folder on Windows, it works.

**Comment by akosyakov** [comment]
Can you see the difference? How hard would it make a fix for umd-compat-loader?

**Comment by kittaakos** [comment]
> Can you see the difference?

 - The occurrence of a couple of modules is different. (That should be OK.)
 - Also, a couple of modules look different regarding the AMD wrapper and factory.

[osx_bundle.js.txt](https://github.com/theia-ide/theia/files/1710589/osx_bundle.js.txt)
[win_bundle.js.txt](https://github.com/theia-ide/theia/files/1710590/win_bundle.js.txt)

> How hard would it make a fix for umd-compat-loader?

I did not see any OS specific code in the umd-compat-loader so far. Maybe there is one in its dependencies.

**Comment by kittaakos** [comment]
Maybe the `test` regexp does not work like I have expected on Windows. Could be related to file separators:
```js
{
    test: /node_modules\/(vscode-languageserver-types|vscode-uri|jsonc-parser)/,
    use: { loader: 'umd-compat-loader' }
}
```

**Comment by kittaakos** [comment]
> related to file separators

Yes. It was due to the regexp for the separators.
