### ISSUE TITLE
Ctrl-P shows native browser print dialog in some situations

### ISSUE THREAD

**Issue by geropl** [theia-ide/theia#1236]
Steps to reproduce:
  1. No editor, file navigator left, terminal open
  2. Focus navigator, Ctrl-P: Shows "Open file..." dialog (expected)
  3. Focus terminal, Ctrl-P: Cycles terminal command history (expected)
  4. Click the empty editor pane, Ctrl-P: Show the browser native print dialog (NOT expected)

@akosyakov 

**Update:**
  - Only on Firefox, may be related to different focus handling

**Comment by epatpol** [comment]
@geropl It seems to work now no? I just tested under Linux and firefox with the exact steps you mentionned above. Can you try it again against master?

**Comment by geropl** [comment]
Awesome, thx!
