### ISSUE TITLE
'yarn watch' results in non-starting backend

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1239]
On the latest master, compiling using "yarn" works fine. However, compiling in watch mode, "yarn watch" results in the following exception, when starting the backend: 
```
Failed to start the backend application.
ReferenceError: raw_process_1 is not defined
    at ContainerModule.registry (/opt/ericsson-dev/theia/packages/process/lib/node/process-backend-module.js:11:10)
    at /opt/ericsson-dev/theia/node_modules/inversify/lib/container/container.js:107:20
    at Array.forEach (native)
    at Container.load (/opt/ericsson-dev/theia/node_modules/inversify/lib/container/container.js:102:17)
    at Promise.resolve.then.module (/opt/ericsson-dev/theia/examples/browser/src-gen/backend/server.js:19:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 ```

So I did a diff between the resulting "process-backend-module.js", compiled with and without watch. It seems that with watch, there is some missing code, that explains the exception above: 

![image](https://user-images.githubusercontent.com/25749063/35994390-4014b1a2-0cde-11e8-8316-3b5f7b1660f5.png)

Looking at other file sizes, this might also be happening with some other extensions as well.

**Comment by marcdumais-work** [comment]
Whatever is happening seems to affect some (but not all) compiled  *-backend-module.js of various extensions.

Also running watch on an individual extension seems not to reproduce the issue. e.g.:
```
npx run watch @theia/process
```

**Comment by akosyakov** [comment]
probably this one https://github.com/Microsoft/TypeScript/issues/21478?

**Comment by AlexTugarev** [comment]
should be fixed with 2.7.2, as `typescript@next` doesn't have this issue. I was wondering about this. doesn't happen with all .ts files, so far only with container module files for me.

**Comment by benoitf** [comment]
should I revert 2.7 typescript upgrade or we're waiting 2.7.2 ?

**Comment by marianmeres** [comment]
This is fixed in `typescript@next` and according to @mhegazy fix will be published in `2.7.2`. 

Just for reference: https://github.com/marianmeres/typescript-2.7.1-issue

**Comment by svenefftinge** [comment]
Is there a date for `2.7.2`already?

**Comment by AlexTugarev** [comment]
[in a week or so](https://github.com/Microsoft/TypeScript/issues/21713#issuecomment-363851032)

**Comment by akosyakov** [comment]
One also can use `npx run watch mypackage` as a workaround for a week, it eats less CPU as well

**Comment by AlexTugarev** [comment]
@akosyakov this is affected too

**Comment by akosyakov** [comment]
ok, strangely have not noticed it yesterday

**Comment by marcdumais-work** [comment]
> One also can use npx run watch mypackage as a workaround for a week, it eats less CPU as well

That seems to work for me

**Comment by marcdumais-work** [comment]
@benoitf thanks, but I am ok with waiting for ```2.7.2```.
