### ISSUE TITLE
[shell] Improve initial width of sidebars

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1241]
The side-bars are much too small on first open. We should calculate the initial width based on the absolute width.

**Comment by spoenemann** [comment]
> We should calculate the initial width based on the absolute width.

What does that mean?

**Comment by svenefftinge** [comment]
I mean the width of a side panel should be a fraction of the total width of the shell. I propose 1/6.
Same for the height of the bottom panel.

**Comment by svenefftinge** [comment]
For the bottom panel it seems to already be the case that it uses 50% of the available space. Can we reduce that to 30%?
