### ISSUE TITLE
Programmatically opening directory or git project on IFrame-embedded Theia

### ISSUE THREAD

**Issue by snoop244** [theia-ide/theia#1247]
I understand that I need to embed Theia in my application as an iframe.  When I instantiate Theia, can I pass in a directory or specific git repo?  I understand how to pass a message to an application running in an iframe, I just can't seem to find an integration point in Theia to load a specific directory and, ideally, a specific file.

My use case, in case you are interested, is to embed Theia inside a Business Process Modeling & Notation (BPMN) application.  Simple templated code snippets will be generated by the BPMN modeling application and saved to a directory (and/or commited to git).  I would like to point Theia at the generated code to give the user the option to edit that code.

An alternative approach is that I use TypeFox's Monaco LSP client - which makes loading the editor with the generated code quite trivial.  The problem with that approach is that adding language servers has proven too challenging for me.  In addition to the out-of-the-box languages, I need Java and Python - which Theia seems to support.

Thank you for these great projects!

Thanks,
Steve

**Comment by akosyakov** [comment]
You can write an extension which talks to the parent window to get a file URI and open it with `OpenerService`.

**Comment by snoop244** [comment]
Thanks
