### ISSUE TITLE
electron example not picking up framework changes

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#126]
Steps to reproduce

In theia directory run:

npm run watch

In examples/electron run:

npm start

Then change something in the framework , I try the terminial-backend-module.ts to change the terminal to a non existing one...

Ctrl-c the app

npm start

The changes are not picked up (still runs bash)

Doing npm install doesn't help either...

**Comment by hexa00** [comment]
My bad editing the wrong file hehe

**Comment by hexa00** [comment]
Nope wit h

**Comment by kittaakos** [comment]
I will take care of this.

**Comment by hexa00** [comment]
The only way I was able to get a change picked up is:

In examples/electron
rm -rf node_modules/theia
npm install

**Comment by kittaakos** [comment]
That is exactly the expected behavior based on the current state. The `file-dependency-updater` is not yet configured for the Electron-based example, but we could easily add support to it.

**Comment by hexa00** [comment]
OK sounds like a good idea

**Comment by hexa00** [comment]
Fixed by #170
