### ISSUE TITLE
[editor] Symbol highlighting shows ghosts 

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1262]
It looks like one can see highlighted symbols from editor in background:

![2018-02-13 12 24 08](https://user-images.githubusercontent.com/914497/36147754-b9b44002-10b9-11e8-93cc-4b493410db08.gif)

**Comment by svenefftinge** [comment]
Any hints on how to reproduce it?

**Comment by AlexTugarev** [comment]
I double-checked this with current master states. It's still present. 
0. clone `https://github.com/theia-ide/theia-plantuml-extension`
1.  open `plantuml-preview-handler.ts`
2. click on `PreviewHandler` occurrence.

**Comment by akosyakov** [comment]
During debugging I can see that ts server returns bogus highlight ranges.

**Comment by akosyakov** [comment]
PR for the ts lang server: https://github.com/theia-ide/typescript-language-server/pull/26
