### ISSUE TITLE
[performance] unnecessary stat-ing files finding user's home directory, opening WS

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1288]
I noticed that when we start Theia, the server side try to load/register many files not needed. I have a workspace with just a few files, but the parent folder of that workspace has hundreds of files/folders. I noticed that  "node-filesystem.doCreateFileStat()" is called for all the files/folders on the parent workspace. 
Why do we need to load / track all those  files on the node server? This is not necessary, it uses resources which could be usefull to run the server, is causing degradtion in performance, has many files watcher which are not necessary, 
The only place I see the parent of the workspace folder is when you select "File -> Open". Even here, having a list of files/folders would be suficient until one of it is selected to create a new workspace. WE can see that if we go two levels down, we still have the list of files/folders being selectable and we did not load anything before on those folders, no watcher, ...

i.e.
workspace folder:     /home/user1/theiaWorkspace -> have file watcher on the files/folders
parent folder:            /home/user1   -> No need to load / track those files ???
parent/parent folder: /home   -> When selecting "File->Open", we can still see all files/folders and no watcher on those yet which is fine

**Comment by akosyakov** [comment]
If it is true then it is a bug. Could someone verify?

**Comment by akosyakov** [comment]
Please make sure that you have only one client opened during verification. If you have 2 clients and more for workspaces of all clients should be watched.

**Comment by marcdumais-work** [comment]
@lmcbout I think what you saw is a coincidence. Your workspace is directly under your home directory. Mine is not. When I add a console.log, I still see that all regular files from my home directory are passed to ```"node-filesystem.doCreateFileStat()"```, even if no workspace is set and I then restart the client.

**Comment by lmcbout** [comment]
You are right Marc, no mather where my workspace is, it always read my home directory and it also reads the folder for my workspace
i.e. current workspace: /tmp
new workspace folder: /opt/firefox/icons
switching with those workspace (current to new), I see that "node-filesystem.doCreateFileStat()" is executed for all my files/folders from my home directory, i.e. /home/lmcbout
It doesn't make sense here.

**Comment by lmcbout** [comment]
Adjust code to prevent reading the user home folder when initiating Theia. On ly read the workspace file and the watching file in the user home folder.

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/1297

**Comment by lmcbout** [comment]
I created a new issue ( issue #1300 ) to reference the workspace FileStat when saving a file. This is  concerning my last comment previously.

**Comment by marcdumais-work** [comment]
While trying to reproduce #1300, I noticed another case: when we open a workspace, I see that we stat all files in its root and one level of sub-directories from the root. The weird thing is that it seems to be repeated many times. 

Using a the LLVM git repo as workspace, I see that the above happens ~30 times. See attached log, that shows every time doGetStat() is called. All in all, it means, in this case, that we stat ~900 files. I got similar results using the Theia git repo as workspace.

[file-stats-open-llvm-workspace.txt.gz](https://github.com/theia-ide/theia/files/1733137/file-stats-open-llvm-workspace.txt.gz)

**Comment by svenefftinge** [comment]
Multiple calls for the workspace root stat are caused by all clients waiting for the `workspaceService.root`. As they get their own promise which fetches the filestat.
See 
https://github.com/theia-ide/theia/blob/4556384f5c48b9afbadbb493203b80345afb0515/packages/workspace/src/browser/workspace-service.ts#L63

**Comment by svenefftinge** [comment]
The multiple `getFileStat` calls from `workspaceService.root` are fixed with https://github.com/theia-ide/theia/pull/1302.

**Comment by svenefftinge** [comment]
The rest of this ticket seems to be mostly false observations. 
Can we close it?

**Comment by lmcbout** [comment]
Seems ok to close and uses issue #1302
