### ISSUE TITLE
Is there a way to turn off autosave?

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1298]
When you make a change to a file, Theia automatically save the change.  Is there a way to turn this off, so that the file is only saved via an explicit save action (ctrl-s)?

**Comment by hexa00** [comment]
Yes create a `.theia/settings.json` file in your home directory with the contents:

```
{
    "editor.autoSave": "off"
}
```

**Comment by epatpol** [comment]
You can also put this file under the workspace root in `.theia/settings.json` with the config mentionned above if you want it per workspace, or if you want to override a user setting.
