### ISSUE TITLE
[performance] Getting the workspace fileStat each time I save a file is not required

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1300]
Why running "node-filesystem.doGetStat()" on the whole workspace each time I save a file ?

When a file is saved on the client side, node-filesystem.doGetStat() is executed for the file and the function is also executed for the whole workspace, so all files try to get the FileStat again for no reason. If I save a file, we can get the FileStat for the file, but certainly no need to get the FileStat for all files in the workspace. When the auto-save is on, looking for the FileStat for the workspace is executed a lot. To see how often it is used, just put the following line in node-filesystem.doGetStat at line 280.
console.log("doGetStat() depth: " + depth + " for: " + uri.toString());
Bigger is the workspace (ex: llvm project), more time is required to save the file and the cpu get crazy.

**Comment by marcdumais-work** [comment]
I am not (at least yet) able to quite reproduce this issue. When I add the trace suggested above, I see that every time a file is saved, it seems all files in the same folders and one level of sub-folders, are 'stat-ed', but I do not see this spread recursively to the whole workspace. Still not good, but at least a bit more contained... 

I wonder if you tried this on a clean branch? 

We have noticed in the past that your laptop seems to be somehow more affected by timing issues, e.g. enabling you to more easily reproduce file corruption by auto-saving big files - it's possible this is at play again.

**Comment by svenefftinge** [comment]
The file tree widget fetches the folder of a changed file. See https://github.com/theia-ide/theia/blob/master/packages/filesystem/src/browser/file-tree/file-tree-model.ts#L89
We need this for 'ADDED' and 'DELETED' types but could possibly filter 'CHANGED'. @akosyakov?

**Comment by akosyakov** [comment]
yes, sounds reasonable, but it is used to be like that and I changed it in https://github.com/theia-ide/theia/commit/7dfe0825106729313287d90c3de3f572d692f374, i cannot remember why but it was somehow related to moving files
