### ISSUE TITLE
[editor][question] Auto-save can revive a deleted file in the WS

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1307]
I hit this when I was trying to reproduce a defect in the navigator; is it a bug or a feature?
![gh-1307](https://user-images.githubusercontent.com/1405703/36352194-802cc8ea-14b5-11e8-9859-1494748f16c7.gif)

**Comment by akosyakov** [comment]
The resource deletion is still not handled properly. I've started working on it in https://github.com/theia-ide/theia/pull/950#issuecomment-352351340.
