### ISSUE TITLE
New Terminal is available in menu before the contribution inits

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#133]
It seems if your start the browser example and try to start a terminal quickly the widget will be created but since the service has not started yet you wont see the terminal.

Waiting a bit to see like
```
 backend] Launching Python Server failed: Error: spawn pyls ENOENT
[backend] Launching Python Server failed: Error: spawn pyls ENOENT
[backend] Java Server: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[backend] 
[backend] Java Server: SLF4J: Defaulting to no-operation (NOP) logger implementation
[backend] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[backend] 
[backend] --root-dir= was not present. Falling back to current working directory: '/home/eantotr/ownCloud/work/theia/examples/browser.'
```

Then the terminal starts...

Maybe the menu should not be there or disabled ? 
Or there should be some message to the user that things are still starting...

**Comment by svenefftinge** [comment]
Generally, frontend parts that rely on backend services need to deal with them being offline. 
I think in this particular case the terminal widget should show some indicator, that it is trying to connect.

**Comment by svenefftinge** [comment]
Related to #110 (the notify user part of it)

**Comment by hexa00** [comment]
Yes that sounds like the right way to fix it

**Comment by svenefftinge** [comment]
close as fixed (no longer reproducible)
