### ISSUE TITLE
[terminal] After a restore, the restore text doesn't wrap

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1330]
After a restore, the data in the terminal has a proper size now (from issue #1303) and it looks good.
One  thing I notice, execute a command in the terminal "la -alF" and the result will wrap if the terminal size isn't wide enough.  On restart, the data in the terminal doesn't wrap, it tries to show data on one line but the terminal width isn't wide enough to display the text on a single line. 

If I execute the command again, it wraps 

![peek 2018-02-20 13-24_terminal2](https://user-images.githubusercontent.com/419051/36443943-32b15150-1648-11e8-85b6-949dd59dd841.gif)

**Comment by lmcbout** [comment]
While discussing with Marc, we also notice the terminal size is around 80 columns after a restore, it doesn't take the whole viewer area.
See the following video after a restore :
![peek 2018-02-20 15-26_terminalwide](https://user-images.githubusercontent.com/419051/36447582-c6bbb12e-1652-11e8-85c6-5b483737685e.gif)

**Comment by svenefftinge** [comment]
The issue here is that the terminal process is always initialized with the defaults of 80 * 24. We need to make sure that the xterm is opened and a resize event came in, before starting/attaching to the backend process, so that we can immediately call resize with proper numbers.

**Comment by spoenemann** [comment]
Is it possible to reflow the shell history after the widget has been resized?

**Comment by marcdumais-work** [comment]
IIRC reflow is not supported by Xterm.js

**Comment by spoenemann** [comment]
> IIRC reflow is not supported by Xterm.js

xtermjs/xterm.js#622

Would be cool to have that.

**Comment by spoenemann** [comment]
Same in VS Code: Microsoft/vscode#23688

**Comment by svenefftinge** [comment]
I think this ticket can be closed, since the initial issue was solved.
