### ISSUE TITLE
Remove the placeholder `quit` command that bounds to Ctrl/Cmd+Q

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1331]
Cannot quit the electron application with Ctrl/Cmd+Q.

**Edited**:
 - [x] Get rid of the placeholder `quit` command that supposed to terminate a key sequence.
 - [ ] Make sure that the key sequence either continues if a proper subsequent key was pressed and terminates if not. We can mimic VSCode which does the followings:
    -  User presses <kbd>blabla</kbd>.
    - `(blabla) was pressed. Waiting for second key chord...`
    - For instance, user presses <kbd>Escape</kbd>, and no match in the registry.
    - `The key combination (blabla, Escape) is not a command.`

Please, use the `chrod` word on UI if possible.

**Comment by epatpol** [comment]
Just tested it and the same happens on linux with ctrl-q, looking at the code it seems it seems it was intended to be for cancelling a key sequence (I think?) [here](https://github.com/theia-ide/theia/blob/d1c2c40ed069c6b979104526712ed69749431d61/packages/core/src/browser/common-frontend-contribution.ts#L343)

I can try to fix it but I'm not sure the current command was made so that it can also exit the application? WDYT

**Comment by kittaakos** [comment]
Good catch! I have no idea why did we introduce it. Could you please try to remove it and see if it works. If it works, +1 for excluding it, as it does nothing but breaks the electron quit functionality.

What's your take on that @akosyakov?

**Comment by akosyakov** [comment]
don't have an idea, cc @hexa00 if you find a minute

**Comment by svenefftinge** [comment]
Quitting the application doesn't make any sense. The comment says quiting the most recent command. But again I don't understand when we would want that. Since it is not implemented we should remove it.

**Comment by akosyakov** [comment]
Maybe it was done that one does not close the browser page by hitting ctrl+q by accident.

**Comment by kittaakos** [comment]
> Maybe it was done that one does not close the browser page by hitting ctrl+q by accident?

Could be, but it closes, unfortunately.

**Comment by hexa00** [comment]
@svenefftinge It is used to cancel a key sequence at the moment for example you type `ctrl+x` and there's a key sequence `ctrl-x ctrl-f` so Theia waits for other keys.

But you did that by mistake and you want to cancel the command you were typing.  You can then use `Ctrl-Q` for that.

My idea was that this could be reused to cancel a command like a git clone taking too long or somthing like that too. Or quit the application in the electron case.

**Comment by hexa00** [comment]
Not that not implementing the command but registering it has this side-effect. So removing it would remove the cancel keybinding feature.

**Comment by kittaakos** [comment]
Thanks for the clarification, @hexa00. I would recommend doing something that VSCode does. If there is no matching sequence, then it terminates. One can always press <kbd>Esc</kbd>, pragmatic but a feasible solution. I think that would solve both problems. Are there any thoughts on this?

**Comment by hexa00** [comment]
@kittaakos I tested vscode and it waits for ever for a key unless you press Ctrl-Q so Theia was meant to be the same way...

**Comment by hexa00** [comment]
Oops I just retested and it doesn't do that sorry.

Emacs does that (ctrl-g) however sorry for the confusion.

**Comment by epatpol** [comment]
Yea vscode just says that Ctrl-Q is not a command in the status bar I think

**Comment by belloyang** [comment]
Can someone please summarize what the solution is to solve that issue that cmd+q couldn't close electron app? I couldn't figure it out by looking through all the replies. Thanks a lot @kittaakos

**Comment by kittaakos** [comment]
@belloyang, these keybindings should close the electron app.

https://github.com/eclipse-theia/theia/blob/5fb75c73bea6fc54563c4b969551c3f3cd8c8d62/packages/core/src/electron-browser/menu/electron-menu-contribution.ts#L199

<kbd>⌘</kbd>+<kbd>Q</kbd> works on macOS only, natively.
