### ISSUE TITLE
[java] The Java LS does not report any diagnostics on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1332]
But with JS/TS it works. So there should be something with the Java LS on Windows.

**Comment by svenefftinge** [comment]
Do you have java installed? Anything in the logs?

**Comment by kittaakos** [comment]
> Do you have java installed?

Yes.

> Anything in the logs?

I have modified the js files inside the `node_modules` to see if there are any errors there. Nothing.

Please note, the CA works, for instance. And here is the interesting part: this does not report an error although I do not have the type `Strssaing` and the method `prinssat` does not exist on the `PrintStream`:
```java
class azxxzssasadaA {
    public static void main(Strssaing[] args) {
        System.out.prinssat("boo");
    }
}
```

And this reports an error. See the `d` after the closing curly brace:
```java
class azxxzssasadaA {
    public static void main(Strssaing[] args) {
        System.out.prinssat("boo");
    }d
}
```

**Comment by kittaakos** [comment]
I think it is not a Theia issue. If you agree, please close.
<img width="334" alt="screen shot 2018-02-23 at 10 51 37" src="https://user-images.githubusercontent.com/1405703/36588183-93cdf394-1887-11e8-8742-5cf04d9e124f.png">

**Comment by kittaakos** [comment]
Same on OS X.

**Comment by gorkem** [comment]
Some part of the missing diagnostics is due the the missing configuration support on Theia. jdt.ls depends on `didChangeConfiguration` notification to correctly initialize. I think jdt.ls needs to move the initialization logic as well https://github.com/eclipse/eclipse.jdt.ls/issues/601

**Comment by gorkem** [comment]
This is also affected from the fix made on https://github.com/TypeFox/vscode-languageserver-node/commit/e0c1f194dabede0409f0d8f4e4e2eeccc65e1535

**Comment by gorkem** [comment]
With the latest updates I no longer can reproduce this issue. Closing. Please reopen if it still exists
