### ISSUE TITLE
Drag and drop throws an error

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1336]
It happens when I drag a **folder**, change my mind and put it back where it was:
```
Uncaught (in promise) Error: Request move failed with message: EINVAL: invalid argument, rename '/Users/akos.kitta/Desktop/theia-ws/dugite-extra/.vscode' -> '/Users/akos.kitta/Desktop/theia-ws/dugite-extra/.vscode/.vscode'
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at main.js:242
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

**Comment by lmcbout** [comment]
Testing to Drag a folder and Drop it back over himself generated the same eror as reported. If you Drag a folder and then decide to Drop it not over itseft, but over the parent folder, then it ask you if you want to relace it or not.
We should trap this error.

**Comment by kittaakos** [comment]
Why do not we do nothing when the source URI equals with the target URI, wouldn't it be better than catching and ignoring an error.

There is another strange behavior; if I drag a file and change my mind (so that the drop destination would be the same as the drag source), it offers whether I would like to override the existing file one or not. Why do we ask that instead of doing nothing?

**Comment by epatpol** [comment]
I agree, no need to throw an error, just do nothing if source === target.
