### ISSUE TITLE
[Theia CLI] @theia/core/package.json not found error

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#1338]
So I tried doing a customized Docker image for Theia using ``theia build`` and I [stumbled upon this error](https://travis-ci.org/sr229/theia-openshift/builds/344590926#L1329).

The package exists but it seems to point to ``@theia/<package>/package.json``, not ``@theia/package``.

**Comment by akosyakov** [comment]
Hi, are we talking about this repo: https://github.com/sr229/theia-openshift? I don't see `latest.package.json` file where.

**Comment by sr229** [comment]
yep @akosyakov, I was pbserving how you do your building by copying it on my own repo before fabricatong a better one, but I kept encountering this error.

My plan was to use COPY and add it to /opt/app, then tell theia CLI to build there

**Comment by akosyakov** [comment]
You did not answer my question. There should be `latest.package.json` in this repo next to `Dockerfile`. How is it supposed to work without when it should be copied?

**Comment by sr229** [comment]
Closing issue as this seem to be an issue with how I `COPY` it on Docker
