### ISSUE TITLE
[electron] The electron application throws an error when refreshing the window

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1341]
Originally from [here](https://github.com/theia-ide/theia/pull/1319#issuecomment-367237716). It happens when one refreshes the browser window with Ctrl/Cmd+R.

**Comment by vince-fugnitto** [comment]
I've re-tested the bug on both macOS and Linux due to the recent updates to the Electron version, and removal of clustering and concluded that the bug is no longer present. 

If we confirm, we can close the issue :smiley:

**Comment by vince-fugnitto** [comment]
Closing as the issue seems to be resolved based on current testing.
