### ISSUE TITLE
DiffNavigation does not work anymore

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#1346]
monaco canNavigate() returns always false.

**Comment by AlexTugarev** [comment]
How to reproduce?

**Comment by AlexTugarev** [comment]
Looks like, there is an issue with monaco api.

**Comment by jbicker** [comment]
It is possible that it is related to https://github.com/theia-ide/theia/issues/1343.

**Comment by AlexTugarev** [comment]
Not sure, but after rebasing no master, I have same issue. OTOH I spotted an issue with incorrect typings.

**Comment by akosyakov** [comment]
@jbicker meant that it is possibly related to removing requirejs, but don't get distracted :)

**Comment by AlexTugarev** [comment]
I got it. But looking deeper into the issue, I see, that an method in typings is underscored, but not in js code :neutral_face:
