### ISSUE TITLE
Split application-package

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1356]
There are some very useful methods in the application-package to get informations about the current extensions, however pulling that also pulls a lot of overhead like the generator stuff. I'm not exactly sure how to do it yet but looking at #1084 I think this sort of menu contribution should be in core, as we want all theia applications to have a way to list the current version and extensions (kinda like eclipse). I do not however want to add application-package as a dependency to core, so there's an issue with that... 

I'm open to ideas on how to resolve this problem, maybe remove or duplicate the code that does the npm listing of extensions infos and whatnot inside core?

**Comment by akosyakov** [comment]
We should introduce another dev package, like `@theia/application-manager`. Move everything that is not needed for `ApplicationPackage` to this package. This package should be used by the Theia cli and the extension manager packages.

**Comment by epatpol** [comment]
This would be a good first step, although I'm still not sure how we would do #1084 if it's another dev-dependency that core can't use. Any ideas?

**Comment by akosyakov** [comment]
Why should core use it?

**Comment by akosyakov** [comment]
ok, I see because of menu contributions, I think you can it as a dependency to core

**Comment by epatpol** [comment]
I've started work on this on a branch under theia's repo [here](https://github.com/theia-ide/theia/commit/ea9c8c9ec541c12fc538193ddde6758564c3be5e) if you want to check @akosyakov. I'm not exactly sure what to split here, and the old packages depending on application-package now depends on application-manager too. If I follow that core would then depend on theia/application-package which contains the info needed to fetch versions and whatnot. Is that okay?
