### ISSUE TITLE
Git only works with first repo in workspace

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1359]
I have a workspace containing more than one git repo.  Theia only monitors the first repo found for changes, and ignores the others.

**Comment by marcdumais-work** [comment]
Hi John. You're right that only one git repo is selected/active at a time. Look on the status bar at the bottom, to the left - you'll see the active repo name (if there's more than one repo). If you click on it, you'll be able to change it to any detected repo in your workspace.
