### ISSUE TITLE
[search in file] Doing `Ctrl+a` in the 'search expression' text field selectes whole file

### ISSUE THREAD

**Issue by geropl** [theia-ide/theia#1363]
Instead, I'd expect the whole expression to be selected, just like in VSCode.

**Comment by kittaakos** [comment]
Related: #808?

**Comment by epatpol** [comment]
Yes I think it's the same bug, I'm pretty sure #808 would select the editor text if you happened to have an editor with text opened at the same time.

**Comment by akosyakov** [comment]
This one seems to be related as well: https://github.com/theia-ide/theia/issues/1394#issuecomment-369151333

**Comment by akosyakov** [comment]
Resolved in #1415
