### ISSUE TITLE
[editor] Drag and drop glitch when moving files with opened editor

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1366]
The DND works fine and after reopening the file the content is there but something is odd with the editor.

![dnd_deletes_file_content](https://user-images.githubusercontent.com/1405703/36604310-abe42f30-18bd-11e8-9d98-3cd551afca97.gif)

Related: https://github.com/theia-ide/theia/pull/950#issuecomment-352351340?

**Comment by akosyakov** [comment]
yes, we still don't react properly on deletion and renaming

**Comment by spoenemann** [comment]
Is this a duplicate of #1191?

**Comment by kittaakos** [comment]
Yes.

**Comment by kittaakos** [comment]
Duplicate of #1191.
