### ISSUE TITLE
Improve "Do you want to save ..." dialog

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1374]
<img width="408" alt="screen shot 2018-02-26 at 10 09 45" src="https://user-images.githubusercontent.com/914497/36662047-769f2c36-1add-11e8-9837-6a6502f6923d.png">

* ~`Cancel` button seems to be redundant~
* Should `Don't Save` button has full width?
* Why both main actions are emphasized?
* Typo in text.

**Comment by akosyakov** [comment]
`Cancel` is not redundant. It cancels closing the editor then other close the editor.

**Comment by svenefftinge** [comment]
Also if autosave is on, we should simply save and not bother the user.

**Comment by AlexTugarev** [comment]
Thanks! I forgot to mention, that I've seen this when autosave was on.

**Comment by jbicker** [comment]
One issue left: https://github.com/theia-ide/theia/pull/1429#issuecomment-370348247
