### ISSUE TITLE
[file-search][quick-open] Broken icons in the quick open widget when searching for a file in the workspace

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1376]
<img width="599" alt="screen shot 2018-02-26 at 13 08 10" src="https://user-images.githubusercontent.com/1405703/36669772-5ba1d42e-1af6-11e8-9e65-5eae378d4afc.png">

**Comment by svenefftinge** [comment]
@kittaakos I don't see this anymore in the master state, but I noticed that the icons in the editor tabs are aligned differently. Seems like it is caused by the css changes you did for the navigator. 
Could you verify if you see the same?

**Comment by svenefftinge** [comment]
<img width="424" alt="screen shot 2018-02-27 at 09 02 17" src="https://user-images.githubusercontent.com/372735/36717077-f302bc74-1b9c-11e8-8981-a3a6e5213708.png">

**Comment by kittaakos** [comment]
I will take care of this.

**Comment by kittaakos** [comment]
Will be fixed as part of #1391.
