### ISSUE TITLE
ts cannot fix broken imports after installing missing dependencies 

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1382]
To reproduce:
- open a ts file with imports to external packages
- imports should be broken
- download dependencies, i.e. run install
- imports should be fixed, they are not

**Comment by AlexTugarev** [comment]
@akosyakov could you provide an example to reproduce with?

I tried, but it works fine with this one:
![2018-02-27 10 59 14](https://user-images.githubusercontent.com/914497/36722337-8d16eeec-1bad-11e8-8483-3efbcd5bcf49.gif)

**Comment by AlexTugarev** [comment]
worked with running `yarn` in Theia ws after wiping out node_modules:
![2018-02-27 11 33 06](https://user-images.githubusercontent.com/914497/36724098-66ac800a-1bb2-11e8-920c-ccc050e27208.gif)

**Comment by AlexTugarev** [comment]
@akosyakov can you still reproduce this?

**Comment by akosyakov** [comment]
it was fixed in the meantime
