### ISSUE TITLE
Page up/Page down shifts the git view left and right slightly when in the git commit message view

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1384]
When focussing the git message text box, if you press Key.PAGE_UP and/or Key.PAGE_DOWN it messes up the view a bit. Following screencast explains it better:

![screencast_2018-02-26_04_15_10 pm](https://user-images.githubusercontent.com/2881761/36696006-f6788ea6-1b10-11e8-8d14-245f53391681.gif)

**Comment by vince-fugnitto** [comment]
closing since it does not occur anymore, probably after the `Git` widgets were refactored to use React
