### ISSUE TITLE
ITreeNode.isVisible works wrong with navigator nodes

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#1385]
In some cases `ITreeNode.isVisible(node)` says that navigator node is visible when it is actually hidden.

### Steps to reproduce
1. Unfold in the navigator a file from subdirectories of the workspace root.
2. Collapse a few nodes to hide target file
3. Get node from the navigator and check visibility.

Actually the problem is that `ITreeNode.visible` isn't mandatory field and node treated as visible if the field doesn't exist. Quick debugging showed, that the field is undefined and remains undefined for collapsed (and so invisible) node.

**Comment by akosyakov** [comment]
This flag does not reflect whether a node is hidden. You should check the expansion state for it. It reflects whether a node should be rendered at all.

**Comment by mmorhun** [comment]
Well, then I just didn't understand the model properly. But to me [this](https://github.com/theia-ide/theia/blob/d980c133b18300391062feec8cc4e2837b167c46/packages/core/src/browser/tree/tree.ts#L69-L73) comment is confusing. Maybe we should change the description of the property to avoid such pitfalls for newcomers? WDYT?

**Comment by akosyakov** [comment]
updating the docstring sounds good
