### ISSUE TITLE
[core] Connection Status not updated on restart

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1386]
Currently, the connection status is assumed to be online initially. Since then there is no status change, the listeners will not get an initial status event for being ONLINE. If the application was left in OFFLINE state and that information was saved to the store, the new application keeps hanging in that state.

**Comment by kittaakos** [comment]
This still happens on the master.

**Comment by kittaakos** [comment]
![screencast 2018-03-01 10-53-29](https://user-images.githubusercontent.com/1405703/36838230-f142d68c-1d3e-11e8-82c4-8a691b4aea75.gif)

**Comment by svenefftinge** [comment]
Do you know how to reproduce it?

**Comment by kittaakos** [comment]
No, unfortunately, I do not know. I'll try to reproduce it again.

**Comment by kittaakos** [comment]
No matter how hard I have tried to reproduce it, the defect did not occur again. I close this. One can reopen it again or open a follow-up with the exact steps.
