### ISSUE TITLE
[navigator] Click beyond tree collapses/expands root node

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1390]
![2018-02-27 10 35 52](https://user-images.githubusercontent.com/914497/36721110-48d89fee-1baa-11e8-838f-1e2497925902.gif)

Really annoying is, that the current selection is lost, after expanding the tree again.

**Comment by akosyakov** [comment]
The tree is flickering on the expansion. It is new. We should reverse the same width for the toggle.

**Comment by kittaakos** [comment]
This issue blocks my work for #1479. I'll take care of it.

**Comment by kittaakos** [comment]
Closed via #1479.
