### ISSUE TITLE
[editor] Keyboard shortcut is applied to editor without focus.

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1394]
While having focus on terminal widget and pressing `command+k`, a line is deleted in the editor, which has no focus:

![2018-02-27 10 59 42](https://user-images.githubusercontent.com/914497/36724167-9f18f7de-1bb2-11e8-972a-fe82e6cc60aa.gif)

**Comment by epatpol** [comment]
Can't reproduce on linux, I think it's mac specific? 

Is the issue about `command+k` not doing anything in the terminal or really that it does something in the editor while it shouldn't as the focus is in the terminal?

**Comment by epatpol** [comment]
Nevermind what I said above, it's not about doing nothing in the terminal, but more that keyboard shortcuts are applied to the editor even though the editor doesn't have focus. Kinda like how `ctrl+f` works everywhere (i.e it will open the file search even though you're in the file tree to the left).

**Comment by AlexTugarev** [comment]
@epatpol thanks for checking with linux. indeed, that issues seems to be related to `command` key. `command+k` is the same as `ctr+l`, but I used to use first one. 

the thing is, even if `command+k` is not to be supported for any reasons, I would not expect this shortcut to be applied in editor without having the focus.

**Comment by AlexTugarev** [comment]
Same happens even if the commit message field has focus.
