### ISSUE TITLE
[git] Error logged when repository switcher in statusbar is clicked

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1402]
> Uncaught (in promise) The command 'git.change.repository' cannot be executed. There are no active handlers available for the command.

Looks like the command handler is disabled if only one repository is available. Maybe in that case the handler should be active, but just do nothing.

**Comment by elaihau** [comment]
@AlexTugarev 
OK I tested the scenario where there is no git repo in the workspace ... looks like the button in the status bar does not even show up. So I guess my question above is not valid any more :)

**Comment by AlexTugarev** [comment]
Sounds good. I'll test your PR.
