### ISSUE TITLE
Nodes indentation is not aligned properly for all trees

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1403]
- [x] From https://github.com/theia-ide/theia/issues/1412#issue-301306120
 - [x] The outline view is messed up too.
 - [x] Check the call hierarchy tree too.
 - [x] Make sure the changes from above do not break the Problems view.

**Comment by kittaakos** [comment]
<img width="264" alt="screen shot 2018-03-01 at 10 57 15" src="https://user-images.githubusercontent.com/1405703/36838409-62a970ba-1d3f-11e8-887a-e68bda204cd4.png">
