### ISSUE TITLE
[git] Git history view has the focus which feels alien compared to other widgets

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1407]
Note the blue highlighting. See below:
![screencast 2018-02-28 13-56-33](https://user-images.githubusercontent.com/1405703/36788833-b108cb58-1c8f-11e8-8122-cad1e286400b.gif)

Also, can we make it closeable? It can be closed anyway:
![screencast 2018-02-28 14-02-02](https://user-images.githubusercontent.com/1405703/36788940-20bb1a46-1c90-11e8-9c09-b553c47f73ef.gif)

**Comment by rcjsuen** [comment]
I think the close button isn't rendered because the widget's `title`'s `closable` property hasn't been set to `true`. You also can't close it with the middle mouse button.

**Comment by kittaakos** [comment]
> I think the close button isn't rendered because the widget's title's closable property hasn't been set to true.

Yes, I can confirm that, thanks! My question was rather why did we decide to have a non-closeable widget, unlike the `Problems` view.

**Comment by svenefftinge** [comment]
> Yes, I can confirm that, thanks! My question was rather why did we decide to have a non-closeable widget, unlike the Problems view.

Because it opens in the left side-bar. It also doesn't have an icon.

**Comment by svenefftinge** [comment]
See also https://github.com/theia-ide/theia/issues/1408

Adding the close icon everywhere, makes the UI a bit busy. We should experiment with things like only showing it on hover or so.

**Comment by elaihau** [comment]
Hi @svenefftinge , to make sure that I am not misunderstanding you

> Adding the close icon everywhere, makes the UI a bit busy.

Could you please explain what you meant by "busy" ? Is it a visual issue (i.e., having too many close buttons is distracting / makes users feel uncomfortable), or a performance issue (i.e., it slows down the UI / backend) ?

Thanks !

**Comment by jbicker** [comment]
If this is still about the blue border on some focussed widgets (beside the close button): it shouldn't be there anymore. Has been solved with https://github.com/theia-ide/theia/pull/1728. 
So, maybe one should rename this issue?

**Comment by kittaakos** [comment]
> If this is still about the blue border on some focussed widgets

No. That was fixed.

> So, maybe one should rename this issue?

I would rather close this. Objections?

**Comment by kittaakos** [comment]
The original issue has been fixed, I am closing this. Someone wondering why the widget cannot be closed should reference [this comment](https://github.com/theia-ide/theia/issues/1407#issuecomment-372038382).
