### ISSUE TITLE
[tabbar][enhancement] Tab-bars without an icon should be aligned left if there are no icons

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1408]
Currently, the space for an icon is there even if there is no icon.

<img width="342" alt="screen shot 2018-02-28 at 14 05 28" src="https://user-images.githubusercontent.com/1405703/36789028-782e7e9e-1c90-11e8-86c4-3235f91c7bfc.png">

**Comment by spoenemann** [comment]
Alternative solution: Show a default icon if the widget's title has none.
