### ISSUE TITLE
[Navigator] Broken alignment of files vs. folders

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1412]
In below's tree the files seem to be siblings to the rrot, but they are children. They should align with the other folder children.

<img width="236" alt="screen shot 2018-03-01 at 08 39 52" src="https://user-images.githubusercontent.com/372735/36832550-347d21a4-1d2c-11e8-94cb-90b7646a1432.png">

**Comment by akosyakov** [comment]
It is a special case of https://github.com/theia-ide/theia/issues/1403

**Comment by kittaakos** [comment]
I merge this into #1403, it will be fixed together anyway.
