### ISSUE TITLE
[Windows] Change the address of the example application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#142]
It cannot open the example on `0.0.0.0:8080` (in Edge & Chrome). `127.0.0.1:8080` works fine.

I am using VirtualBox (Win10)

**Comment by svenefftinge** [comment]
ok, please change it then. `0.0.0.0`generally doesn't work on windows at it seems.

**Comment by kittaakos** [comment]
Thanks! The changes will be merged as part of #135.

**Comment by kittaakos** [comment]
149c7bd7ce932b7da475c319fa5b9eb202186ac9

**Comment by kittaakos** [comment]
Closed via #137
