### ISSUE TITLE
Add status bar button to change language settings for the current file 

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1420]
It would be helpful to have a button in the status bar which would allow to change the language settings for the current file. I think that the implementation in vscode works well, so we could do something similar.

**Comment by vince-fugnitto** [comment]
@simark I believe it has been added, tested on 021cfc5
The following statusbar item enables users the ability to change the language status for the current file.

https://github.com/theia-ide/theia/blob/021cfc52d15e806a510d59c47b4fe4baba9410ae/packages/editor/src/browser/editor-contribution.ts#L101-L114
