### ISSUE TITLE
Browserify-aes

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1428]
The [browserify-aes](https://www.npmjs.com/package/browserify-aes) package that gets pulled in by Theia is listed as being licensed under the MIT license, but this [issue](https://github.com/crypto-browserify/browserify-aes/issues/43) indicates that package may in violation of other licenses.

Does Theia actually use browserify-aes?  Could the dependency on it be removed?

**Comment by svenefftinge** [comment]
It comes through webpack, which is required by the application-package:
```
> yarn why browserify-aes
yarn why v1.3.2
[1/4] 🤔  Why do we have the module "browserify-aes"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Reasons this module exists
   - "workspace-aggregator-3a78d219-b5dd-42a0-88b7-0bb6370469db#@theia/application-package#webpack#node-libs-browser#crypto-browserify#browserify-cipher" depends on it
   - "workspace-aggregator-3a78d219-b5dd-42a0-88b7-0bb6370469db#@theia/application-package#webpack#node-libs-browser#crypto-browserify#browserify-sign#parse-asn1" depends on it
info Disk size without dependencies: "96kB"
info Disk size with unique dependencies: "300kB"
info Disk size with transitive dependencies: "464kB"
info Number of shared dependencies: 8
✨  Done in 0.92s.
```

**Comment by jopit** [comment]
Does Theia actually need (make use of) the function in browser-aes itself, or is just pulled in because it's part of a package containing other function that Theia needs?

**Comment by svenefftinge** [comment]
It is pulled in through the `extensions-extension`, which uses `application-package`, which uses `webpack`, which has a dependency `node-libs-browser->crypto-browserify->browserify-cipher`.
I know that webpack is used at runtime, to update a theia app ((un)installing extensions). I don't know if webpack actually really requires the dependencies above in our use case.

**Comment by svenefftinge** [comment]
For now, you could remove the `extension-manager` extension from your theia app, to get rid of the dependency.

**Comment by jopit** [comment]
Our package.json doesn't include the `extension-manager` extension, but `application-package` still gets built into our theia app.

```
{
    "private": true,
    "dependencies": {
        "@theia/typescript": "^0.3.7",
        "@theia/navigator": "^0.3.7",
        "@theia/terminal": "^0.3.7",
        "@theia/outline-view": "^0.3.7",
        "@theia/preferences": "^0.3.7",
        "@theia/git": "^0.3.7",
        "@theia/file-search": "^0.3.7",
        "@theia/markers": "^0.3.7",
	"@theia/java": "^0.3.7"
    },
    "devDependencies": {
        "@theia/cli": "^0.3.7"
    }
}
```
Is there some other extension that's also pulling it in?  The docker hub theiaide/theia image also contains `application-package` although it's package.json doesn't include `extension-manager`

**Comment by epatpol** [comment]
@svenefftinge I believe the `@theia/cli` pulls it even though `extension-manager` isn't there.

**Comment by jopit** [comment]
Forgive my node/yarn ignorance, but is it OK to remove devDependencies, will yarn still build our theia app?

**Comment by svenefftinge** [comment]
You can remove the devDependencies after you've successfully built the application.
Not that you need to start Theia through `node src-gen/backend/main.js` then.

**Comment by jopit** [comment]
Awesome, thanks

**Comment by kittaakos** [comment]
@jopit, is there anything else left we have to discuss here? If no, I would like to close this issue. Thanks!

**Comment by jopit** [comment]
We are good for now, so closing this.
