### ISSUE TITLE
Add user interface for settings

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#1433]
Now to change user or workspace settings we have to edit appropriate config file which is not comfortable for most of the users. It would be good to have some UI.

**Comment by mmorhun** [comment]
I see a few ways of implementing:
- add a window with left-side tree or list and panel with corresponding to selected in the tree item options as a main view (kind of classic desktop settings).
- add `Settings` tab into the left panel with tree or list of topics. Then open in editor-like tab selected options group. It could be json settings or more classic-like checkboxes, inputs, dropdows, etc.
- vscode-like settings: editor with json schema and autocomplete (not sure about vscode left part).

@akosyakov @svenefftinge what do think?

**Comment by svenefftinge** [comment]
I'd prefer to go with:
 - Command to open the settings file (create one if it doesn't exist)
 - JSON schema support

Once we have that we can look into further improving it, e.g. by doing the vscode approach or using a generic json rendered UI, such as http://jeremydorn.com/json-editor/

**Comment by svenefftinge** [comment]
I created #1434 for the JSON editing part.

**Comment by mmorhun** [comment]
@svenefftinge have you started work on that issue? If no, I could take it after current one.

**Comment by svenefftinge** [comment]
I have started working on the JSON Schema support, only (i.e. #1434)

**Comment by kittaakos** [comment]
Can this go to a separate extension?

**Comment by lanrat** [comment]
How does one find the list of setting/preferences options? It is not clear what variable names can be defined in the JSON.

**Comment by svenefftinge** [comment]
I consider this done. Any outstanding issues should be tracked in individual tickets.
We now also have json schema support in the text editor (#3078).
