### ISSUE TITLE
JSON Schema Support

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1434]
Make sure that the JSON support in Theia has automatically registered all common Schemas (https://github.com/SchemaStore/schemastore).
In addition, it shall be possible to programmatically create schemas (we need that for preferences).

**Comment by vinokurig** [comment]
If there any progress on it? If no I can start working on it.

**Comment by svenefftinge** [comment]
Yes, we are working on it. A PR is on its way.

**Comment by svenefftinge** [comment]
I created a new extension here : https://github.com/theia-ide/theia-json-extension
