### ISSUE TITLE
[shell] Editor's overlay widgets are hidden

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1439]
Editor overlay widgets, such as the suggestions pop up no longer overlay the other widgets.
Seems like this is since the recent shell refactorings. @spoenemann could have a look?

<img width="237" alt="screen shot 2018-03-05 at 22 22 14" src="https://user-images.githubusercontent.com/372735/37000445-b6b87df4-20c3-11e8-9524-0ff4dd72efe5.png">

**Comment by spoenemann** [comment]
See commit 7c11840f209a1e5b670d5dceaad4ba8633db5775
