### ISSUE TITLE
Implement a logger for debug logs 

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#144]
The goal of this issue is to document the implementation of a logger we can use for debug log or other kind of logs (info etc...) And thus replace all console.log calls.

My initial plan is to use [winston](https://github.com/winstonjs/winston)

For the frontend I would make a custom transport to that logs through JSON-RPC to the backend , that way this would only be called when the debug level actually triggers a log action)

The backend service logging service would relog through the backend logger what came in from the frontend

And the backend would directly log to a winston logger

**Comment by svenefftinge** [comment]
It doesn't seem to run in our frontends https://github.com/winstonjs/winston/issues/287

**Comment by svenefftinge** [comment]
Bunyan seems to work with webpack https://github.com/trentm/node-bunyan#webpack

**Comment by hexa00** [comment]
Indeed, I'll set it up with Bunyan then, it seems like a nice library too

I like the filtering support etc.. I will have to make Stream over JSON-RPC for this one, should be ok.

**Comment by hexa00** [comment]
See PR #167

**Comment by hexa00** [comment]
Closed in #167

**Comment by BeilyNaiman** [comment]
I want to use a logger to my project on create-react-app , which lib should I use?
