### ISSUE TITLE
[dialog] Consider doing `reject`on `close`

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1443]
`AbstractDialog.open()` returns a promise that gets resolved on `accept()`.
It should `reject` that promise on `close()`.

**Comment by vitaliy-guliy** [comment]
As it discussed in https://github.com/theia-ide/theia/pull/2401 the behavior has been a little bit changed.
Now when closing the dialog we call `resolve` and pass `undefined`  value.
This helps handle closing the dialog by checking the value and do not catch the promise.
