### ISSUE TITLE
Tree iterator ignores the first node

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1444]
Create an iterator with the tree root. When iterating on it, it does not visit the root node itself.

**Comment by kittaakos** [comment]
@akosyakov, could you please comment on this and #1443 whether these are real defects and we have to fix it, or that is the expected behavior. It would be strange if that is the expected, but anyway, I would need some help confirming it. Thanks!

**Comment by kittaakos** [comment]
Merged into #1450.

**Comment by akosyakov** [comment]
Yes, I think it is a bug.

**Comment by kittaakos** [comment]
Thanks for checking!
