### ISSUE TITLE
Handle inappropriate `theiaext` usage gracefully

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#1451]
`elaihau@elxa4wqvvz1:~/dev/theia/packages/core$ ./node_modules/.bin/theiaext 
(node:746) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: please specify the script that runs with theiaext command.
(node:746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The error message should be more informative and the error thrown by the script should be handled.

**Comment by kittaakos** [comment]
@elaihau, could you please add some context to this issue? For instance, what did you do, what OS are you using? Something that we could use to track down, reproduce and fix the problem. Thanks!

**Comment by elaihau** [comment]
yes @kittaakos , I was trying to use **theiaext** to build one of the packages, e.g., core. And the command should look like the following:
`elaihau@elxa4wqvvz1:~/dev/theia$ ./node_modules/.bin/theiaext build core`

As a newbie to this project, I wasn't aware of how **theiaext** should be used, and therefore I did the following command:
`elaihau@elxa4wqvvz1:~/dev/theia$ ./node_modules/.bin/theiaext`
hoping to get some useful information, like what we get from git:

`elaihau@elxa4wqvvz1:~/dev/theia$ git` 

`usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
`

however got the followings instead:

`elaihau@elxa4wqvvz1:~/dev/theia$ ./node_modules/.bin/theiaext` 

`(node:13121) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: the ext script does not exist: ext:undefined
(node:13121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`


After looking into the code, I was thinking, maybe there are 2 things we could do to improve:
1. Handle the error to hide the UnhandledPromiseRejectionWarning
2. Display more informative message(s) to help users to get a better understanding of how **theiaext** should be used.

**Comment by akosyakov** [comment]
Please read the documentation: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#build-extension-packages-individually

You should not user theiaext directly.
