### ISSUE TITLE
'Open Workspace Symbol' command throws errors if no file is opened

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1460]

**Comment by elaihau** [comment]
Hi @akosyakov , could you please provide a little more details on the context and steps to reproduce this bug? 

Also, is it programming language specific? I tried with the Typescript & Javascript files, and couldn't see errors from the logs or front-end.

Thanks.

**Comment by akosyakov** [comment]
You should not open any file.

**Comment by marcdumais-work** [comment]
@akosyakov trying to reproduce, I do not see any error with a workspace open and no file open. With no workspace open, I see: 

```
[2018-03-08T11:07:47.829Z]  INFO: Theia/31 on 4cc54fb6b67c: Error: not opened []
```
Is that the error ?

**Comment by akosyakov** [comment]
@marcdumais-work just tried again, it does not happen anymore, feel free to close, i will open a new issue if find steps to reproduce

**Comment by marcdumais-work** [comment]
ok, thanks.
