### ISSUE TITLE
Avoid `split` of document content

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1471]
Split lines is quite expensive as it's done in `merge-conflicts` and `git/dirty-diff`, cf. 

<img width="797" alt="screen shot 2018-03-09 at 12 31 27" src="https://user-images.githubusercontent.com/914497/37205699-042679fe-2396-11e8-8489-4c905c6d5de9.png">

cc. @akosyakov

**Comment by akosyakov** [comment]
@AlexTugarev please profile as well there were other hot spots

**Comment by AlexTugarev** [comment]
the `merge-conflicts` hot spot can be easily improved by using new iterator-based [`split`](https://github.com/theia-ide/theia/blob/536f38d3fd2d7491c87318f0765f1ba575b52d57/packages/core/src/common/strings.ts). 

<img width="763" alt="screen shot 2018-03-09 at 13 11 22" src="https://user-images.githubusercontent.com/914497/37207041-663aabb0-239b-11e8-860e-cce9ab1c8cfc.png">

**Comment by akosyakov** [comment]
Noticed that it happens even with `"git.editor.decorations.enabled": false`.
