### ISSUE TITLE
A collapse all action/command would be useful in the navigator

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1473]
Fortunately, as a workaround, one can refresh the browser window until we have [this](https://github.com/theia-ide/theia/issues/1316) bug.

Before starting to implement anything for this task, make sure it is clear how and where to put this action/command. For instance, do we need a toolbar for the widget and so on.

Edit: fixed the link to the other bug.

**Comment by epatpol** [comment]
I'm okay with adding a toolbar to the widget like vscode. I guess it could also accept contributions from other extensions also, kinda like the status bar?

**Comment by kittaakos** [comment]
> I'm okay with adding a toolbar to the widget like vscode. I guess it could also accept contributions from other extensions also, kinda like the status bar?

Thanks for pinging, @epatpol. As I wrote, the toolbar/whatever requirements have to be discussed before you start to implement anything. Maybe, we just simply drop the idea and add a keybinding for that.

CC: @akosyakov @svenefftinge

**Comment by epatpol** [comment]
>As I wrote, the toolbar/whatever requirements have to be discussed before you start to implement anything. 

I wasn't planning to work on this right away no worries :)

Indeed maybe a simple keybinding/command contribution could be good for now, and then once the ui requirements are set in stone there can be something that just calls the command that was there before.

**Comment by spoenemann** [comment]
We currently use the area in the top right corner for the search box. What if we use the same area for buttons that become visible on hover (like it's done in VS Code)?
