### ISSUE TITLE
[git][diff][question] Dirty diff manager throws an error

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1475]
when either `right` or `left` is not under version control.

It does not cause a problem, but can we handle it on the frontend? So do not execute `git show` when something is not under version control.

Alternatively, git backend can handle this and return either `undefined` or something else.

I have assigned to you, @AlexTugarev. If you believe, it should be handled on the git backend, just reassign it to me. Thanks!

**Comment by AlexTugarev** [comment]
@kittaakos I finally understand the underlying issue here! 

you are completely right, it should not produce any errors (in log). the implementation does not check for uri schemes, which is a bogus. 

e.g. in comparing a tree to some other branch let's open `gitrev` uris, which cannot be handled as `file` uris. I'll add a guard for uris to be handled.

**Comment by AlexTugarev** [comment]
@kittaakos please reopen, if there will be any other situations related to this issue.

**Comment by kittaakos** [comment]
I do not know why we are trying to call `git show` but it could be a diff manager problem. Steps to reproduce:
 - Create a file in the currently active repository (for the sake of simplicity, let's have one repository in the WS).
 - Write something to the editor.
 - Delete file from the navigator. (The file remains open in the editor but the content will be deleted, know issue). Make sure it already has the `U` untracked Git decorator.
 - See the error at the backend.

**Comment by AlexTugarev** [comment]
thoughts on this:

* there is no change emitted when an untracked file is deleted.
* `git show` is requested for unaffected models in diff manager.

Considered changes:

- [ ] untracked files should not be handled at all!
- [ ] create model on staging of untracked files 
- [ ] removes model when a file becomes untracked
- [ ] update model's previous revision content when `staged` state changes

**Comment by kittaakos** [comment]
> there is no change emitted when an untracked file is deleted.

Did you mean, you are not receiving a `GitStatusChangeEvent` when an untracked file has been deleted?

**Comment by AlexTugarev** [comment]
Correct. No change is reported for deletion of a file `U`.

**Comment by AlexTugarev** [comment]
I think it's git's (de)fault. I did not consider that, and it requires to be handled explicitly.

**Comment by kittaakos** [comment]
Smells like a bug. If that's the case, that would mean, if the user deletes an untracked file, the removal does not show up in the Git widget.

**Comment by kittaakos** [comment]
I receive the event in the [Git widget](https://github.com/theia-ide/theia/blob/18a24ac1f11bc45f56c64a9d058387af9a5a7ba2/packages/git/src/browser/git-widget.ts#L97) when I delete an untracked file.

<img width="512" alt="screen shot 2018-03-14 at 11 55 50" src="https://user-images.githubusercontent.com/1405703/37398401-b087ede0-277e-11e8-9f7f-d7a2225fd713.png">

I am not currently not on the `master` but the branch was up-to-date.

**Comment by AlexTugarev** [comment]
The git widget shows the projection of git status results, and it shows the content correctly.

https://github.com/theia-ide/theia/blob/master/packages/git/src/browser/git-widget.ts#L105-L145

**Comment by AlexTugarev** [comment]
@kittaakos I see, I can compute the deletion of file! `untracted -> not present` would mean it's deleted.

**Comment by kittaakos** [comment]
I will work on this. I will add a guard to the Git backend so that `git show` will not throw an error if the file is not under version control. Do you have any objections @AlexTugarev?

**Comment by AlexTugarev** [comment]
Go ahead @kittaakos! 👍

**Comment by AlexTugarev** [comment]
I already tackled one case of the browser part in #1526, cf. https://github.com/theia-ide/theia/pull/1526/files#diff-22b4c0c5283e2f27abbd130887b77fc6R217, which means handling of either `undefined` or any kind of error.

**Comment by kittaakos** [comment]
@AlexTugarev, is it still a valid issue after #1562? I do not see the error anymore.

**Comment by AlexTugarev** [comment]
@kittaakos, the initial issue is no longer present. I filed #1735 as follow-up to handle deletion separately.
