### ISSUE TITLE
[problems] styling issue in problems view

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1484]
The label is wrapped in the icon element and gets `fontawesome`font family.
<img width="176" alt="screen shot 2018-03-12 at 19 28 59" src="https://user-images.githubusercontent.com/372735/37302431-cc08028e-262b-11e8-82d2-7a1db3eea8ba.png">

**Comment by kittaakos** [comment]
@svenefftinge, could you share a link to your sandbox DSL, so that I can reproduce the issue?

**Comment by kittaakos** [comment]
Nevermind, I managed to mock this from code:
<img width="310" alt="screen shot 2018-03-19 at 09 53 47" src="https://user-images.githubusercontent.com/1405703/37586096-8fc29642-2b5b-11e8-9755-3a7ef2af71b4.png">
