### ISSUE TITLE
[ts] Theia is not responsive with a lot of ts errors and opened Problems view

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1489]
Try to copy and open this file https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts

It seems that we are trying to fetch about 10000 diagnostics and render all of them in the main thread.

**Comment by marcdumais-work** [comment]
I think this is a generic issue, not limited to TS - we have seen similar with a Java project

For more info see this comment: https://github.com/theia-ide/theia/issues/2060#issuecomment-397295251
