### ISSUE TITLE
On the activation, the first visible tree node should be selected if there is no selection.

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1510]
Right now it is a root and some trees don't show the root.

**Comment by kittaakos** [comment]
It only applies to the Navigator. As far as I know, call hierarchy, outline, and problems view has its logic to select the root node if there is one. Furthermore, this task contradicts with #1390 which I am currently working on. I would like to close this task unless you have a good reason to keep this open.

**Comment by kittaakos** [comment]
I think this should be among the `TreeProps`. And by default, the tree widget should take care of it.

**Comment by akosyakov** [comment]
At least we should improve API by allowing to pass a node in `selectNextNode`, `selectPrevNode` as a first argument.

**Comment by kittaakos** [comment]
OK, thanks! Then just ignore my comments from above.
