### ISSUE TITLE
Terminal content isn't visible after browser tab switching

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#1513]
### Steps to reproduce
1. Open terminal
2. Make some output (for example type `ls -la`)
3. Switch to another browser tab, click or type o few symbols.
4. Return back to Theia tab.

**Expected behaviour:** Terminal output is displayed as before tab switching
**Actual behaviour:** Almost always only the last line is visible. Other content appears after any scroll.

![theia-terminal-tab-switch-bug](https://user-images.githubusercontent.com/15607393/37471128-ba476362-2871-11e8-9f1a-4182fd83d2c4.gif)

### Additional info
**OS:** Fedora 27

**Comment by vince-fugnitto** [comment]
@mmorhun can you confirm if this is still an issue? It seems to work fine for me locally

**Comment by mmorhun** [comment]
Seems it is already fixed.
