### ISSUE TITLE
[git] Chronologically order the Git branches

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1519]
Chronologically order the Git branches, instead of alphabetically. At least give a preference that could be used to configure this. I do not know whether they have a preference for that or not, but VSCode orders them by the last access time too. Which is not a bad idea.

Theia:
<img width="541" alt="screen shot 2018-03-15 at 22 06 30" src="https://user-images.githubusercontent.com/1405703/37491172-3abea35e-289d-11e8-9b98-200f3e2d2e2a.png">

VSCode:
<img width="421" alt="screen shot 2018-03-15 at 22 05 55" src="https://user-images.githubusercontent.com/1405703/37491175-3f382bc6-289d-11e8-9025-55bae596d8d2.png">

**Comment by kittaakos** [comment]
That is another mystery, why comes `a` after `G`:
<img width="596" alt="screen shot 2018-03-15 at 22 09 50" src="https://user-images.githubusercontent.com/1405703/37491321-b7040134-289d-11e8-870d-d0a04a376b1e.png">

**Comment by elaihau** [comment]
maybe it is because ascii code of the lower cased `a` is greater than that of the upper cased `G` :)

**Comment by elaihau** [comment]
The command 
`elaihau@elxa4wqvvz1:~/dev/theia$ git branch --sort=-committerdate`
lists all branches by the last commit timestamp, sorted by desc order.

Correct me if i am wrong: In order to support listing by Chronologically order, we will need to make changes to the dugite-extra: 
https://github.com/theia-ide/dugite-extra/blob/master/src/command/branch.ts

**Comment by kittaakos** [comment]
Thank you, @elaihau! I have opened a followup and will take care of it.

https://github.com/theia-ide/dugite-extra/issues/14

> In order to support listing by Chronologically order, we will need to make changes to the dugite-extra:

We could make the ordering in Theia as well, but you are right, let's order it with Git.
