### ISSUE TITLE
Review `chokidar` watcher options in the FS implementation

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#152]
This is a follow-up of #125 and #150.

If we had problems with `chokidar` during the development, I would expect problems during runtime too. We need to check and verify. Having failing tests on `Linux` first would be awesome. I have mentioned the `Linux` because we had issues (#125) on that OS initially.

**Comment by akosyakov** [comment]
Let's use [glob-watcher](https://github.com/gulpjs/glob-watcher) that's a wrapper around chokidar that seems to handle chokidar issues, e.g. it works fine for [ldm](https://github.com/theia-ide/theia/blob/master/config/local-dependency-manager/src/package.ts#L259).

**Comment by akosyakov** [comment]
@epatpol Can you comment issues which you have with fs here? I will add tests for them.

**Comment by epatpol** [comment]
@akosyakov if I remember correctly, what I tried first when was I injected the first preference prototype (the one that was not over JSON-RPC yet), I never entered the function [here](https://github.com/theia-ide/theia/pull/140/commits/e8e333d3b7a03c6b45ee5eb0430f24394d059b1d#diff-a01042c6a739bfb371ab07a36dbde8ebR49) when modifying files on the workspace. However creating, deleting or moving files resulted in an event.

As for the other case, @lmcgupe had it when trying to make a test for it [here](https://github.com/theia-ide/theia/pull/140/commits/b7ab2a16eb2b9044e63be83c96205058cbd71568#diff-1ddeb30a4e86d0c395537d1e41a5f215R92). I think he tried many stuff in the test case and couldn't manage to enter the onFileChange callback. @lmcgupe maybe you can add more details on what you tried exactly?

**Comment by lmcgupe** [comment]
Using the below test class, when changing a file content, or actually creating a new file, the callback never gets called..

/*
 * Copyright (C) 2017 Ericsson and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 */

import { JsonPreferenceService, IPreferenceServer } from './preference-server';
import { FileSystem } from '../../filesystem/common/filesystem';
import { FileSystemWatcher } from '../../filesystem/common/filesystem-watcher'
import * as chai from 'chai';
import * as chaiAsPromised from 'chai-as-promised';
import * as fsXtra from 'fs-extra';
import * as os from 'os';
import URI from '../../application/common/uri';
import { FileUri } from '../../application/node/file-uri';
import { FileSystemNode } from "../../filesystem/node/node-filesystem"


const expect = chai.expect;
let prefService: IPreferenceServer;
let fileWatcher: FileSystemWatcher;
let fs: FileSystem;
const TEST_ROOT = FileUri.create(os.tmpdir()).appendPath("node-fs-root");
const uuidV1 = require('uuid/v1');
let root: URI;
let fileSystemNode: FileSystemNode;
let uri: URI;

before(() => {
    chai.config.showDiff = true;
    chai.config.includeStack = true;
    chai.should();
    chai.use(chaiAsPromised);

    root = TEST_ROOT.appendPath(uuidV1());
    fsXtra.mkdirsSync(FileUri.fsPath(root));

    uri = root.appendPath(".theia/prefs.json");
    fsXtra.createFileSync(FileUri.fsPath(uri));
    fsXtra.writeFileSync(FileUri.fsPath(uri), '{"lineNumbers": "on"}', { encoding: "utf8" });

    fs = new FileSystemNode(root);
    fileWatcher = new FileSystemWatcher();
    prefService = new JsonPreferenceService(fs, fileWatcher, ".theia/prefs.json");

});

after(() => {
    fsXtra.removeSync((FileUri.fsPath(uri)));
    fsXtra.removeSync(FileUri.fsPath(root));
});
describe('preference-service', () => {
    describe('01 #has preference', () => {
        it('should return true for the has preference', () => {
            return expect(prefService.has("lineNumbers")).to.eventually.equal(true);
        });

        it('should return false for the has preference', () => {
            return expect(prefService.has("nonExistingPref")).to.eventually.equal(false);
        });
    });

    describe('02 #get preference', () => {
        it('should get the value for the preference', () => {
            return expect(prefService.get("lineNumbers")).is.eventually.equal("on");
        });

        it('should get no value for unknown preference', () => {
            return expect(prefService.get("unknownPreference")).is.eventually.equal(undefined);
        });
    })

    describe('03 #onPreferenceChanged', () => {
        it('should get notified of changed pref', () => {
            fileSystemNode = new FileSystemNode(root);
            const stat = fileSystemNode.getFileStat(uri.toString());

            stat.then((fileStat) => {
                fileSystemNode.setContent(fileStat, '{"lineNumbers": "off"}');
            });

            // xtra test to try to trigger a change event - remove if not necessary
            // uri = root.appendPath(".theia/prefs2.json");
            // fsXtra.createFileSync(FileUri.fsPath(uri));
            // fsXtra.writeFileSync(FileUri.fsPath(uri), '{"lineNumbers": "on"}', { encoding: "utf8" });
        });
    });
});

**Comment by lmcgupe** [comment]
The callback being notifyDifferentPrefs in class preference-server.ts.

**Comment by epatpol** [comment]
Upon further testing with having the watcher in the backend, creating/deleting/moving files create events and onFileChanges callbacks are called (and this works everytime). However modifying the content of a file doesn't seem to call the callback.

**Comment by kittaakos** [comment]
> However modifying the content of a file doesn't seem to call the callback.

See: https://github.com/theia-ide/theia/pull/140#issuecomment-307353564
I hope that helps.

**Comment by kittaakos** [comment]
> Using the below test class, when changing a file content, or actually creating a new file, the callback never gets called..

In general, you need to attach the file system client from the watcher to the file system. That was one problem. The other one: you need to test that file system in your suites what you have initializes in the `before` phase. I would say, your problem is unrelated to this ticket.

**Comment by epatpol** [comment]
@kittaakos Yea I was also thinking that there was something missing in our setup for the file watcher, thanks a lot for investigating!

**Comment by kittaakos** [comment]
@akosyakov, @epatpol Can we close this ticket? It seems to be obsolete.

**Comment by akosyakov** [comment]
Tests were fixed long time ago :)
