### ISSUE TITLE
[dirty diff] `git show` error logged for git-ignored files

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1522]
try opening a git-ingored file (e.g. `yarn-error.log`) in the editor. `dirty diff` module tries to fetch previous revision from git, which fails.

**Comment by AlexTugarev** [comment]
@kittaakos any idea, how to detect ignored files either on frontend, or on backend?

**Comment by kittaakos** [comment]
I would handle that differently. Let's add an expected error code to the Git backend, and simply return with `undefined` if something is not under version control.

Yes, we could check it upfront, whether the resource is under version control or not, before running `git show`,  but that would be an additional Git command. I think it is "cheaper" to expect an error and handle that gracefully.

Let me know if we go with this, and I implement it.

**Comment by kittaakos** [comment]
Similar to #1475.
