### ISSUE TITLE
No notification if one commits without commit message. Last message will be used.

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#1532]
If I reload the theia page and commit something without a commit message, I get a notification.
But if I already committed something before, the last typed message will be committed again next time.
![nocommitmsg](https://user-images.githubusercontent.com/28291421/37523299-ce9dc7a6-2926-11e8-920a-309f00f7df57.gif)

**Comment by epatpol** [comment]
Shouldn't the button be disabled if no commit message is entered? Unless this is supposed to be an amend... In that case it still shouldn't do a second commit.

**Comment by kittaakos** [comment]
> last typed message will be committed again next time

Are you sure it is true and it is not a problem in the history? Just asking though. Could you please verify it in the terminal too?

**Comment by kittaakos** [comment]
Ohh, I think you are right. We store the state of the commit message in the widget.

https://github.com/theia-ide/theia/blob/ec2d98bcdf2c99209fa255029be9e09b23ed2ad3/packages/git/src/browser/git-widget.ts#L44

Is that OK?

**Comment by jbicker** [comment]
Yes. And we forgot to reset it here:https://github.com/theia-ide/theia/blob/ec2d98bcdf2c99209fa255029be9e09b23ed2ad3/packages/git/src/browser/git-widget.ts#L172

**Comment by elaihau** [comment]
Hi @jbicker  are you working on the fix ? If not I will reset the the message every time a commit is made, and populate an error message if the message is empty.
