### ISSUE TITLE
Suggestion: Use more specific Errors

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#1535]
Right now every single error thrown is of type `Error`, and tests try to filter the exception based on the exact message string...

Error messages are meant for humans.

TypeScript supports `Error` type subclassing, so wouldn't it be better to implement a default `CustomError` with the small boiler plate required to make it a proper object, and then inherit our errors from it ?

Most typed language (and not only, e.g. Python) compare exceptions based on the error type, because that's the actual object that should represent the error that happened.

TypeScript example:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#support-for-newtarget

Pros:
- Error catching becomes more specific
- Tests benefit from it (no more human message regex matching that breaks once we change a word)

Cons:
- We must declare the error before hand

In my opinion it is a good practice to throw something else rather than `Error` everytime.

**Comment by akosyakov** [comment]
Can we use `code` property for it and introduce standard error codes? We cannot pass arbitrary error types between frontend/backend without tweaking JSON-RPC code each time. This approach is used in Node.js: https://nodejs.org/api/errors.html#errors_node_js_error_codes.

Generally, I find a suggestion to distinguish errors not based on a message is useful. For example, `vscode-jsonrpc` cannot preserve stack traces and because of it, we have to log all request errors on the backend. It pollutes logs in cases when an error is expected and contains a message which should be displayed to the user. If we can distinguish programming from user errors when we can filter the latter out from logging.

**Comment by svenefftinge** [comment]
I agree. But let's not base it on subclassing `Error` due to the serializing issues, @akosyakov  mentioned.
So let's have a `type: string` property.

**Comment by marechal-p** [comment]
But wouldn't adding a property require subclassing ?

**Comment by marechal-p** [comment]
I may be missing some serialization tests, I don't really know where to look in order to test the errors with the rpc system used in theia, do you have any advice ?

**Comment by marechal-p** [comment]
I think it is still missing some serialization tests, am currently looking around `vscode-jsonrpc`

**Comment by marechal-p** [comment]
So now using stringify the error is serialized as:
```ts
{
    message: "the error message for the human",
    stack: "the stack trace for the developer",
    kind: "front or back end",
    code: "actual error code like nodejs would do"
}
```
I will wait for feedback on this model and its current implementation.

**Comment by svenefftinge** [comment]
We don’t need the ‚kind‘ property

**Comment by marechal-p** [comment]
Error structure:
```ts
{
    message: "the error message for the human",
    stack: "the stack trace for the developer",
    code: "actual error code like nodejs would do"
}
```

In order to be able to define the error type/code, I propose we use `XxxErrorCode` enumerations -or something similar- to regroup package specific errors, so that we can import it anywhere else and use the auto-completion to list the error codes and being able to process them.

Would this be easier ?

[Examples](https://github.com/marechal-p/theia/blob/937329fd275cd88ab29875cc45152e87b027923b/packages/core/src/common/error.spec.ts)
