### ISSUE TITLE
cli: Add option to build production bundle

### ISSUE THREAD

**Issue by ishitatsuyuki** [theia-ide/theia#1537]
Currently the bundle doesn't get minimized and is not suitable for deployment. We should add a production config.

Side tip: webpack 4 may make configuration production settings easier.

**Comment by akosyakov** [comment]
It is a dup of https://github.com/theia-ide/theia/issues/806.

I think it should be another way around, the production should be a default mode. For the development one will need to set `NODE_ENV` to `development`.

Switching to webpack 4 is a separate issue.

**Comment by kittaakos** [comment]
> I think it should be another way around, the production should be a default mode.

Could you give a good reason, why is it better?

**Comment by akosyakov** [comment]
It depends on use cases. If you want to deploy with `theia-cli` which we expect to be the most popular case then you prefer production mode. If you want to develop then you prefer development mode. It also a default in webpack 4.

Other way or another someone should add `--mode production` or `--mode development` to `theia build`. We can let users who deploy type less and for developers generate `--mode development` into `build` and `watch` npm scripts with the extension generator.

**Comment by kittaakos** [comment]
So ideally, I will not face any drawbacks during the development, did I get it right? I hope so. That means, I do not need to explicitly set environment variables in each shell when building, watching, and running tests, right?

**Comment by akosyakov** [comment]
Right, they will be set once in npm scripts.

**Comment by kittaakos** [comment]
Awesome, thanks!
