### ISSUE TITLE
Test against latest monaco and monaco-languageclient

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1539]
I've published next version `0.5.0-0` for the monaco-languageclient which support Monaco `0.11`. It would be good try to migrate and check that lang features are working properly for different servers while MS guys in the mood to have patch fixes. Last time it took 5 months.

**Comment by gorkem** [comment]
What are the instructions for testing this version? Updating the dependency to 0.5.0 did not work for me and caused the build to fail.

**Comment by akosyakov** [comment]
It should be `0.5.0-0` for monaco-languageclient.

> caused the build to fail.

What was the issue?

**Comment by AlexTugarev** [comment]
It's not published yet, right?

**Comment by akosyakov** [comment]
It is published as next, you can use `0.5.0-0`.

**Comment by AlexTugarev** [comment]
resolved in #1681
