### ISSUE TITLE
Generalize EditorManager and EditorRegistry to WidgetManager and WidgetRegistry

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#154]
They are turned out to be useful to create openers for other kinds of widgets.

**Comment by akosyakov** [comment]
Ther should be:
- events widgets changed, closed, opened
- read access methods for widgets (including an active and a current) by a URI, a type or both
- write access methods to add widgets for by a URI, a type or both
- shortcuts for promises on when a widget is closed/opened for by a URI, a type or both

Probably it should be a part of the shell.

**Comment by hexa00** [comment]
@svenefftinge could that be closed after #525 ?

**Comment by svenefftinge** [comment]
Yes.
