### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by santoshray02** [theia-ide/theia#1541]
Hi,
Is there any way to show welcome page on theia-ide startup. As Visual code is displaying the welcome page 

![screenshot from 2018-03-19 11-04-03](https://user-images.githubusercontent.com/12428112/37579622-4942e8f2-2b65-11e8-9b49-64668416c371.png)

**Comment by spoenemann** [comment]
Implement a widget with the desired content and add it to the main shell area on startup.

**Comment by vince-fugnitto** [comment]
closed due to #3149

**Comment by adamretter** [comment]
See also - https://github.com/theia-ide/theia/tree/master/packages/getting-started
