### ISSUE TITLE
Way to specify default view?

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1546]
The very first time a browser accesses Theia, views like _Files_ or _Git_ are available on the left side, but none are actually open.

![image](https://user-images.githubusercontent.com/29612372/37601127-a72fdab6-2b5f-11e8-8e50-0548658d7c6d.png)

Is there a way to specify that by default, the _Files_ view should be open in this situation?

**Comment by epatpol** [comment]
Similar to #830?

**Comment by spoenemann** [comment]
I'd like to generalize this: Currently extensions can contribute widgets and specify how these should be part of the initial layout by implementing FrontendApplicationContribution. How can one customize the initial layout?

The only way I can see at the moment is to create a subclass of ShellLayoutRestorer and override `initializeLayout`. We could support this approach by splitting the two parts of that method (restore the shell layout from the storage service / frontend application contributions initialize the layout) so they can be overridden individually. Any thoughts on this?

**Comment by spoenemann** [comment]
I created a proposal in #1605.

**Comment by akosyakov** [comment]
> Currently extensions can contribute widgets and specify how these should be part of the initial layout by implementing FrontendApplicationContribution.

An extension can also get access to other widgets and initialize them as required without overriding the frontend application.

**Comment by spoenemann** [comment]
> An extension can also get access to other widgets and initialize them as required

But you cannot remove the contribution of another widget if it already has some initialization code.

> overriding and rebinding the frontend application which is quite invasive for the extension to do.

Yes, you shouldn't do this in a normal extension, but when creating a custom application it's totally fine to override the FrontendApplication.
