### ISSUE TITLE
[git] git repo added from the command line is not available from the quick open menu

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#1549]
GIT repo added from the command line prompt does not show up in the quick open menu on clicking the  "switch git repo" button (from the status bar).

![peek 2018-03-19 11-10](https://user-images.githubusercontent.com/37082801/37604098-9582e1da-2b66-11e8-85f9-b7c477480cf9.gif)

**Comment by kittaakos** [comment]
If that is the case, it is another regression compared to the previous Git discovery behavior.

**Comment by kittaakos** [comment]
I believe this works as expected. One can refresh the state of the repository provider from the Git View.

![screencast 2018-03-19 17-18-36](https://user-images.githubusercontent.com/1405703/37608131-0f50b144-2b9a-11e8-89c7-fc4bfba554aa.gif)


@elaihau, could you please try the same I have done? If it works for you too, we can close this issue.

**Comment by elaihau** [comment]
You are right @kittaakos , the refresh button does the magic. I will close this one.
