### ISSUE TITLE
Specify credentials for git push?

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1550]
The Git view provides the ability to do a _Push_; is there a way to specify credentials like a github personal access token to be used with the push?

**Comment by kittaakos** [comment]
@jopit, currently, there is only one way to achieve it; you should be able to open a new terminal from Theia, there you can do the necessary authentication steps. Let me know if you have further questions on this topic.

Also: https://github.com/theia-ide/theia/issues/1037

**Comment by jopit** [comment]
OK, thanks.
