### ISSUE TITLE
Navigation in the diff view is broken

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1553]
Try to navigate with arrows, it puts the focus in the editor instead of preserving it.

**Comment by akosyakov** [comment]
I think it was addressed by https://github.com/theia-ide/theia/pull/1498.

**Comment by kittaakos** [comment]
From the `master`:
![gh-1553](https://user-images.githubusercontent.com/1405703/37658031-d4385ec8-2c4c-11e8-8670-d7d8ceacc77c.gif)

**Comment by svenefftinge** [comment]
Ok, great. I thought I was able to reproduce it over the weekend.
