### ISSUE TITLE
Support variable substitution inside strings

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#1561]
In this issue, I propose to add support of [variable substitution](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution) mechanism inside strings in Theia.
It can be used within different configurations (e.g. tasks.json, future launch.json) to reference some info based on the current state of Theia app e.g. file in the active editor, current line number, text selection or workspace root folder.
In addition, support [VSCode's predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) will allow one step closer to VSCode's configuration files since it allows to have:
- Theia tasks more compatible with VSCode tasks;
- future Theia debug configurations more compatible with VSCode launch.json.

Also, need to add a contribution point to provide a hook that allows any extensions to contribute its own variables. For example:
- Java extension may provide a variable to get current class' FQN;
- some Maven extension may provide a variable to get current Maven module name.

Contribution point is a **very important part for Eclipse Che** since we need to be able to reference Che workspace objects e.g. servers in conf files and in our [Preview URL](https://www.eclipse.org/che/docs/6/che/docs/servers.html#what-is-my-preview) feature.
I'll provide the details of a possible implementation later.
Thoughts?

**Comment by azatsarynnyy** [comment]
Possible design of Macro API

```typescript
/**
 * Macro is a special variable which can be used inside of strings using ${macroName} syntax.
 * Macro can be expanded to some string value.
 */
export interface Macro {
    /**
     * Macro name. Also serves as unique id of macro.
     */
    name: string;
    /**
     * A short description of macro.
     */
    description?: string;
    /**
     * Expand macro to some string value.
     * @returns promise resolved to the expanded string value
     * or to 'undefined' if macro cannot be expanded.
     * Never reject.
     */
    expand(): Promise<string | undefined>;
}
```

```typescript
export interface MacroRegistry {
    /**
     * Register the given macro.
     */
    registerMacro(macro: Macro): void;
     /**
      * Return all registered macros.
      */
    getMacros(): Macro[];
}
```

```typescript
export interface MacroService {
    /**
    * Expand all macros in the given string.
    * @returns promise resolved to the given text with already expanded macros.
    * Never reject.
    */
    expandMacros(text: string): Promise<string>;
}
```

```typescript
export interface MacroContribution {
    registerMacros(macros: MacroRegistry): void;
}
```

**Comment by azatsarynnyy** [comment]
For expanding macros in the different configuration files (tasks.json, launch.json) there may be `ConfigurationMacroService` that uses `MacroService`.
```typescript
export interface ConfigurationMacroService {
    /**
     * Expand all macros in the given configuration.
     */
    expandMacros<T>(configuration: T): Promise<T>;
}
```

**Comment by svenefftinge** [comment]
Important feature indeed. 
I like the term `variable` much better than `macro` because its more often used in that context (environment variables, Eclipse, vs code).

For the replace service, wouldn't it be `(string)=>string` ? Why `T`?

**Comment by svenefftinge** [comment]
> For the replace service, wouldn't it be (string)=>string ? Why T?

Sorry, I was referring to `ConfigurationMacroService` and overlooked `MacroService`.
So what is the purpose of `ConfigurationMacroService`?

**Comment by azatsarynnyy** [comment]
@svenefftinge 

> I like the term variable much better

I don't mind )

> So what is the purpose of ConfigurationMacroService?

It iterates through all the properties of the gives object and substitutes the known variables in all found strings.
Though, it can one of the methods of `MacroService`.

**Comment by azatsarynnyy** [comment]
```typescript
export class VariableService {
    substitute(text: string): Promise<string> {
        ...
    }
    substitute(arr: string[]): Promise<string[]> {
        ...
    }
    substitute<T>(obj: T): Promise<T> {
        ...
    }
}
```

**Comment by azatsarynnyy** [comment]
We can use the same names as VSCode: `variable` and `resolve variables`

**Comment by azatsarynnyy** [comment]
Should it be part of Theia core or separate built-in extension within Theia?

**Comment by akosyakov** [comment]
> Should it be part of Theia core or separate built-in extension within Theia?

I would prefer to go with a separate extension. The core is mostly the application framework. If it is needed later we can move the API part in the core.

**Comment by azatsarynnyy** [comment]
I've opened the PR #1581
