### ISSUE TITLE
Allow user to search .gitignored files easily

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1563]
When searching files with ctrl-p (searching by filename not file content), it ignores files specified in gitignore.  It's a good general default, but sometimes it's useful to search through them too.  It would be good to have a way to quickly allow searching through them as well.

We should have a preference that toggles what the default setting is, but also a way to change it just for one search.  It would be inconvenient for the user to have to change a preference back and forth just for one search.

@svenefftinge suggested that when typing ctrl-p twice, the file search could enter the "don't use .gitignore" mode.  When hitting ctrl-p twice, the placeholder text in the quick open box should be updated to reflect that.

**Comment by epatpol** [comment]
As @MarkZ3 mentionned on gitter, I think it would be nice if the user could ignore something other than what's from the .gitignore. I think we could have a default pref like `search.ignoreFiles` which could be 'Git' meaning you ignore the same files from git, or an array of patterns that could be excluded. We could then keep the idea of having ctrl-p once to use that ignore pattern (git or custom patterns), and ctrl-p twice to ignore that pref. WDYT?

**Comment by svenefftinge** [comment]
The double `ctrl+p` suggestion is similar to the quick outline in Eclipse, where you can press `ctrl+o`a second time, to see the inherited members.

**Comment by simark** [comment]
As a temporary fix, I changed the current default behavior to search gitignored files (#1569).  When this suggestion is implemented and we have a way to toggle searching gitignored files, the default behavior should go back to not search them.
