### ISSUE TITLE
[proposal] Change Resource#readContents API

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1565]
Currently, `readContents` resolves to a `string` and we take it for granted. Never get rejected, everything is fine.

For instance, when we try to load historical revisions from Git, we use `git show` to get the content of a file for a particular commitish. As the state of the master we just reject if the file is not in the Git repository, not under version control, incorrect commitsh and so on. #1522 is to silent the backend and handle such cases gracefully when `git show` fails and return `undefined`. Since the `git show` is called from the `GitResource`'s `readContent` there is no way to indicate, something bad has happened.

I would propose to the change the API and return:

```typescript
{
  readonly success: true;
  readonly content: string;
}
| {
  readonly success: false;
  readonly reason: string;
  readonly errorCode: string | number | undefined;
} 
```

or something like that.

This is just a proposal, I am open to anything. The only thing I would like to achieve is to have a better API than `Promise<string>`.

CC: @akosyakov, @AlexTugarev, @svenefftinge

**Comment by akosyakov** [comment]
I was wondering the same while changing the file resource. I am fine to let `readContents` to reject. We allow it for saving methods already. Clients have to deal with it if they want or it will be logged at the top level.

**Comment by kittaakos** [comment]
We leave the return value as is; Promise<string> and we might reject. 

In case of a Git resource; the rejection could be due to different reasons: you have messed up your `git show` command parameters, or the file is not under version control. Clients should handle these differently if they want to.

I am closing this.
