### ISSUE TITLE
Failed to start language server 'JavaScript'.

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1566]
We're seeing this message when we edit a JavaScript file in our Theia application.  Our package.json file does pull in `@theia/typescript`, which in turn pulls in `typescript-language-server`, which says it supports both JavaScript and TypeScript.
```
$ cat package.json 
{
    "private": true,
    "dependencies": {
        "@theia/typescript": "^0.3.7",
        "@theia/navigator": "^0.3.7",
        "@theia/terminal": "^0.3.7",
        "@theia/outline-view": "^0.3.7",
        "@theia/preferences": "^0.3.7",
        "@theia/messages": "^0.3.7",
        "@theia/git": "^0.3.7",
        "@theia/file-search": "^0.3.7",
        "@theia/markers": "^0.3.7",
	"@theia/java": "^0.3.7"
    },
    "devDependencies": {
        "@theia/cli": "^0.3.7"
    }
}
```
There are no related messages written to the console by the running Theia app. Is there some other dependency that we are missing?

**Comment by kittaakos** [comment]
You could try to install `typescript` to the global or make it available from the workspace root.
See: https://github.com/theia-ide/theia/issues/1392#issuecomment-369144196

**Comment by kittaakos** [comment]
For some reason, GH does not link the proper comment. I meant this one:

> Here is how the language server looks up the tsserver binary:
> https://github.com/theia-ide/typescript-language-server/blob/master/src/lsp-server.ts#L69
> 
> For sure, we need to send proper information to the user in case it cannot find it. (see theia-ide/typescript-language-server#28)

**Comment by jopit** [comment]
OK, installing `typescript` to the global scope worked, thanks.

Is there a mailing list or blog or someplace where changes like the removal of `typescript` from the dependencies of `typescript-language-server` are announced?

Btw, I also noticed that the theia docker image https://hub.docker.com/r/theiaide/theia/ doesn't have `typescript` installed and so has the same problem.

**Comment by marcdumais-work** [comment]
@jopit FYI, about the docker images having this issue: https://github.com/theia-ide/theia-apps/issues/29

**Comment by kittaakos** [comment]
> Is there a mailing list or blog or someplace where changes like the removal of typescript from the dependencies of typescript-language-server are announced?

I am not aware of such a channel, unfortunately.

**Comment by akosyakov** [comment]
> Btw, I also noticed that the theia docker image https://hub.docker.com/r/theiaide/theia/ doesn't have typescript installed and so has the same problem.

thanks for mentioning it, I will check it.

**Comment by kittaakos** [comment]
I am closing this now. @jopit, please reopen, or create a follow-up if you have further questions/problems with this.
