### ISSUE TITLE
Terminal (Shell) is overlapping after few characters

### ISSUE THREAD

**Issue by santoshray02** [theia-ide/theia#1567]
I am trying to type long syntax in shell but it is restarting from 0 after few characters .

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12428112/37755174-58de4a7e-2dca-11e8-99a8-abf16d2e2a4c.gif)

**Comment by marcdumais-work** [comment]
hi @santoshray02 ,

I just tried the terninal on master, but I do not see this problem. Can you give more details? Steps to reproduce?

**Comment by santoshray02** [comment]
Thanks @marcdumais-work 
Run the Project(theia-ide)  `yarn run start` 

Open [http://localhost:3000](http://localhost:3000) in new browser

**Comment by marcdumais-work** [comment]
@santoshray02 Where did you get the Theia you are using? Built yourself from latest source code? Built from published npm modules? From a docker image (if so which one)?

**Comment by santoshray02** [comment]
Build from source code

**Comment by marcdumais-work** [comment]
ok, thank you @santoshray02 for the feedback. I am unable to reproduce at this time. Maybe others can give this a try and report here?

**Comment by lmcbout** [comment]
@santoshray02  @marcdumais-work 
Hi, I just compile the latest Theia . I Opened a new Chrome and open Theia. I only open the terminal and started typing. I couldn't reproduce this issue either. I am running on Ubuntu 16.04.
Which operating system are you using?
Which browser are you using? (Chrome, Firefox, Opera,...)

**Comment by santoshray02** [comment]
Thanks @marcdumais-work  @lmcbout 
I am running it on Ubuntu 16.04 , Chrome

**Comment by lmcbout** [comment]
@santoshray02 
Can we try something, may be there is some cache in your browser
Close Chrome
Can you try on an incognito Chrome browser (When opening Chrome, select the option "New Incognito.."
Enter localhost:3000 (to connect to your workspace)
Open the terminal
Type some chars and see if it still occurs.

**Comment by elaihau** [comment]
I am not able to reproduce this problem either.

**Comment by epatpol** [comment]
> Its happening only for the first time .

First time what if I may ask? Opening the terminal in a new frontend session or the first time you start the backend etc.

We might need more details than that to be able to reproduce it on our end.

**Comment by santoshray02** [comment]
Thanks guys,

Issue Resolved .
