### ISSUE TITLE
Error when deleting a file which is opened in the editor.

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1574]
When deleting a file:
```
Uncaught (in promise) Error: Request getFileStat failed with message: Cannot find file under the given URI. URI: file:///Users/akos.kitta/Desktop/bar/Untitled.txt.
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at main.js:242
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

Steps to reproduce:
- Create a file.
- Delete it.

Since the stack trace is absolutely useless, [here is a hint](https://github.com/theia-ide/theia/blob/c145b1533c69fb2e560099b85bc5b12c18bd94b8/packages/filesystem/src/browser/file-resource.ts#L81) to the source of the problem.

**Comment by epatpol** [comment]
This only happens when you create a new file and keep the editor opened right? 

If no associated editor is opened there's no file-resource associated with that file I believe. I think the `FileResource` gets a change event from the fs (delete event) and then tries to check if it's in sync. The easy fix is to not do the sync when a delete event is received. But there is still the issue of an editor left open after that (although that might be a separate issue).

**Comment by lmcbout** [comment]
After a small investigaton, the error reported comes from node-filesystem.getFileStat()
If we don't return an error, but a FileStat 
ex : ( const statFake: FileStat = { uri: uri, lastModification: 0, isDirectory: false };
         return statFake; )
The error is gone.

Some comment to take into consideration: 
But we still have a file open in the editor whth no reference into the filesystem anymore.
- WE can just close the file and nothing happen.
- If user wants to enter new data, we can allow to create the file again with the new data or just throw the error:  " Error: Request setContent failed with message: Cannot find file under the given URI. URI: file:///...)
- if the file is clean, then nothing happen until the user modifies the file., again we allow to save the content by creating a file or we should just throw an error.
- If "auto-save = on" and file is dirty , then we should create a new file  with the new data or again throw an error.

**Comment by kittaakos** [comment]
> This only happens when you create a new file and keep the editor opened right?

👍

**Comment by lmcbout** [comment]
Yes. This happen when the file is open in the editor

**Comment by kittaakos** [comment]
This still happens with a different error:

```
Request resolveContent failed with message: Cannot find file under the given URI. URI: file:///Users/akos.kitta/Desktop/wss/A/a.sadl.
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at main.js:242
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```
