### ISSUE TITLE
[lsp] Support workspace configurations

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1575]
It also seems that we bogusly communicate that Theia supports configurations and `didChangeConfiguration` event. It could be that changes should be done in `vscode-base-languageclient` to fix a bug: https://github.com/TypeFox/vscode-languageserver-node/blob/e0c1f194dabede0409f0d8f4e4e2eeccc65e1535/client/src/base.ts#L965

**Comment by simark** [comment]
> It also seems that we bogusly communicate that Theia supports configurations and didChangeConfiguration event. It could be that changes should be done in vscode-base-languageclient to fix a bug: https://github.com/TypeFox/vscode-languageserver-node/blob/e0c1f194dabede0409f0d8f4e4e2eeccc65e1535/client/src/base.ts#L965

This is what is sent to clangd when Theia launches clangd: https://pastebin.com/raw/7GaDT0aD

As far as I know, we don't claim that we support the `workspace/configuration` request, and there is no such thing as communicating that we support `workspace/didChangeConfiguration`.  It's possible however, to communicate to the server that we support dynamic registration for `workspace/didChangeConfiguration`, but we don't do that either.  So I don't think the current behavior is bogus.  But of course, we could work to support more of those things if needed.
