### ISSUE TITLE
BaseLanguageClientContribution#onReady is always called with undefined arg

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#158]
This is because `BaseLanguageClient#onReady()` returns a `Promise<void>` while the code in `BaseLanguageClientContribution#onWillStart()` assumes a `Promise<ILanguageClient>`

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/commit/60cb9ec045f651a5ac35d7c3384000f8984a3eb8
