### ISSUE TITLE
[file-search] The file search looks different on Windows and OS X

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1591]
Depends on #1584.

Once the file search works on Windows and OS X, one has to check why the UI looks different on Windows than OS X. Originally from [here](https://github.com/theia-ide/theia/pull/1587#issuecomment-376598057)

AC:
 - [ ] The quick file search should look the same on all platforms.
 - [ ] It should not show encoded URI segments: `%40phosphor` instead of `@phosphor`.

Hint: one has to check whether we send URIs (as strings) back and forth between the frontend and the backend instead of FS paths.

OS X:
<img width="668" alt="screen shot 2018-03-27 at 18 42 59" src="https://user-images.githubusercontent.com/1405703/38012472-eaf93bd0-3261-11e8-9941-1c0052fe2086.png">

Windows:
<img width="602" alt="screen shot 2018-03-27 at 18 43 09" src="https://user-images.githubusercontent.com/1405703/38012479-efc12b78-3261-11e8-9353-818e0787c3fd.png">

**Comment by akosyakov** [comment]
Looks like results returned by the search are normalized via URI.

**Comment by kittaakos** [comment]
No, the picture is out-dated, the URI normalization is already fixed. The catch is; on Windows, it is a path, on OS X it is the file name and the relative path as a description.

**Comment by elaihau** [comment]
could we close this one as https://github.com/theia-ide/theia/pull/3749 was merged ?
