### ISSUE TITLE
Terminal Panel overlaps Monaco Editor

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#1594]
Seems that the Terminal panel has a higher order than the Editor, which causes the panel to overlap the Monaco completion dialogue

![image](https://user-images.githubusercontent.com/14976516/38015330-0739c350-329e-11e8-81f8-720102dbdf40.png)

**Comment by sr229** [comment]
Behavior in VS Code for comparison: The above Dialogue overlaps any panel.

**Comment by epatpol** [comment]
@sr229 Can you provide an easy way to reproduce it, it seems to work for me here

![screenshot from 2018-03-28 09-40-43](https://user-images.githubusercontent.com/2881761/38032703-4a49d536-326c-11e8-9da9-8b3c966989a6.png)

Although I'm not sure it's the same completion dialog. Can you reproduce it with a simple `.js` file and trying the same thing as me above?

Which OS/Browser combination are you using?

**Comment by sr229** [comment]
@epatpol This was done on Firefox 58 on Ubuntu 16.04.3, and yes I was able to reliably reproduce it

![image](https://user-images.githubusercontent.com/14976516/38074610-e15b3d20-3361-11e8-884f-f51d761dd561.png)

**Comment by epatpol** [comment]
Weird, I'm also on Ubuntu 16.04 and testing on Firefox (59.0.1 however) and it seems to work perfectly fine here. Can you test on another browser and see if it's reproducible? Are you on the latest theia master?

**Comment by sr229** [comment]
@epatpol tested on Theia@latest NPM packages via a custom-built Docker image based from `theiaide/theia:latest`

**Comment by epatpol** [comment]
@sr229 That's really weird I wish I could reproduce it...

**Comment by svenefftinge** [comment]
This was fixed with https://github.com/theia-ide/theia/pull/1447

**Comment by sr229** [comment]
@svenefftinge is this on the next packages right now?
