### ISSUE TITLE
Move the `file:open` command and its handle from `@theia/workspace` to `@theia/core`

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1609]
Why?
 - To be able to open any arbitrary file through the `CommandService` without depending the `@theia/workspace`.
 - The open command (implemented with the `OpenerService`) is workspace agnostic.
 - Yes, we could use the `OpenerService` directly, but that would imply duplicating the logic which is done by the command handler anyway.

Idea:
 - We could have a generic opener command with its handler in the `@theia/core`.
 - Reuse that in the `WorkspaceCommands` (in `@theia/workspace`).
 - For instance; one can call it from the quick open palette, paste some URI and it will open something. Even an HTTP URI.

**Comment by marechal-p** [comment]
Just tried to refactor along your suggestions, this is a first pass.

For the idea of opening any URI, isn't it already possible to register some handler that returns `true` when asked if it can handle the input ?

**Comment by kittaakos** [comment]
You do not have to do much with the opener part, it is already implemented:

```typescript
import { OpenerService, OpenerOptions, open } from '@theia/core/lib/browser/opener-service';

//...

await open(this.openerService, uri, options)
```

**Comment by marechal-p** [comment]
I don't really understand...

Right now I moved `file.open` command and its handler from `@theia/worspace` to `@theia/core`.
Also renamed the `file.open` to `core.open` (in the case we expand the opening process to take HTTP URI and everything/anything).
It felt better indeed.

But I don't see what you want to do regarding the `open(this.openerService, uri, options)`.

Right now it looks like this `open` functions could be a method of `OpenerService`:

```ts
// why not ?
this.openerService.open(uri, options)

// instead of the current:
import { open } from ...
open(this.openerService, uri, options)
```

But isn't this function just enough ? As long as we have access to an openerService, just call `open` on it and call it a day ? What are the use cases that you saw and that weren't covered ?

**Comment by kittaakos** [comment]
> Right now I moved file.open command and its handler from @theia/workspace to @theia/core.

Great!

> Also renamed the ID from file.open to core.open (in the case we expand the opening process to take HTTP URI and everything/anything).
> It felt better indeed.

OK.

> But I don't see what you want to do regarding the open(this.openerService, uri, options).

[Nothing](https://github.com/theia-ide/theia/issues/1609#issuecomment-378278964), it is already there.

**Comment by kittaakos** [comment]
Closed via https://github.com/theia-ide/theia/pull/1647.
