### ISSUE TITLE
@types/electron conflicts with types provided by electron natively

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#161]
Electron starting 1.6.9 ships with native types as electron.d.ts that conflict with the @types/electron we had.

This broke the build with errors like:
```node_modules/@types/electron/index.d.ts(11,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'preventDefault' must be of type '() => void', but here has type 'Function'.
node_modules/@types/electron/index.d.ts(12,3): error TS2403: Subsequent variable declarations must have the same type.  Variable 'sender' must be of type 'WebContents', but here has type 'EventEmitter'.
node_modules/@types/electron/index.d.ts(15,7): error TS2300: Duplicate identifier 'Point'.
```
We should switch to these native types but doing so yeilds errors at the moment like: ```src/application/electron-browser/menu/menu-plugin.ts(39,44): error TS2694: Namespace 'Electron' has no exported member 'MenuItemOptions'. src/application/electron-browser/menu/menu-plugin.ts(39,103): error TS2694: Namespace 'Electron' has no exported member 'MenuItemOptions'. src/application/electron-browser/menu/menu-plugin.ts(88,37): error TS2694: Namespace 'Electron' has no exported member 'MenuItemOptions'. src/filesystem/node/node-filesystem.spec.ts(839,12): error TS2345: Argument of type '"unhandledRejection"' is not assignable to parameter of type '"loaded"'```

This issue is about fixing those.

**Comment by lmcgupe** [comment]
https://github.com/lmcgupe/theia/commit/9bb572065c54d08b7b9031650fee6809e8864620
