### ISSUE TITLE
Is there a way to control theia from a parent frame?

### ISSUE THREAD

**Issue by travis1111** [theia-ide/theia#1613]
So we run theia in iframe.

We want to switch workspace root from outside of theia iframe, and after we do this action, we are hoping theia's files view is automatically switched to the new workspace root.

Is this possible?

I create an backend extension so that I can set theia's workspace root.  (Still has bug, see #1397), we also know that theia send an alive call to backend probably every second.  Is there a way to do something in the backend so that theia's front-end realize that the workspace root is changed then it automatically refreshes the view?

**Comment by epatpol** [comment]
Would it be possible to post to a restful endpoint of Theia where it would be `host/setWorkspace` with the appropriate information from outside of the iframe? Then Theia would reload with the new workspace. So instead of doing a GET like you did [here](https://github.com/theia-ide/theia/issues/1397) you could POST or something else to an endpoint where the callback would be to switch the server's workspace. WDYT?

**Comment by epatpol** [comment]
> I am confused, I don't think POST makes any different.... but can Theia switch instruct browser to reload the window?

> One thing I am thinking is, to build an frontend (javascript) extension, so somehow the parent window call the js inside theia iframe, and from the js function, I switch the workspace... but I don't think I can call js inside iframe especially parent and iframe are running on different port. Or maybe?

I understand a little better, I thought setting the root from the backend actually triggered the reload at the moment, so my bad. It's actually the workspace service that, once the root is set, opens/reloads the window. So yes in that case you could make an extension that has both a frontend/backend part, the backend would receive the information about the new workspace with a GET/POST/ETC, then sends that information to its frontend module, that would have the workspace-service injected, and then from there you could set the root and reload the iframe (I think?). 

> One thing I am thinking is, to build an frontend (javascript) extension, so somehow the parent window call the js inside theia iframe, and from the js function, I switch the workspace... but I don't think I can call js inside iframe especially parent and iframe are running on different port. Or maybe?

That's the issue, if they were on the same server/port I think it could be doable, but I actually have no clue. It would indeed be the easiest to just create a frontend module that can be called from outside the iframe. Otherwise the approach I explained above should be able to work.

**Comment by travis1111** [comment]
Thanks!

So backend extension to receive the new root, then the backend extension send the new root to frontend, then frontend extension call workspaces service to switch the root?

Any example on how to send information to front end? :-)

**Comment by travis1111** [comment]
Calling a js from a different port is not possible, by my colleague mentioned post message:

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

Now I need an example of building a front end extension that can receive the message and do the switch?

Go back to the REST -> backend -> frontend -> backend discussion, I think the original solution didn't work was because of this `Usually we set the root workspace from the frontends as technically you can have several different frontends with different workspace roots all connected to the same backend. `

**Comment by travis1111** [comment]
@epatpol thank you ! will take a look today!

**Comment by travis1111** [comment]
Thanks @epatpol 

I can receive the post message from parent window in the theia (in iframe).  But I received millions of setImmediate as well... this is the message" `setImmediate$0.04896350016180917$793`

this is my code

```
onStart(app: FrontendApplication): void {
        alert("start");
        window.addEventListener("message", function(event) {
            console.log(event.data);	    
        }, false);
        alert("registered");
    }
```

Why I am getting these ``setImmediate`` messages?

**Comment by epatpol** [comment]
@travis1111 I really have no idea, as I never really worked with cross-origin communication. But looking at https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage maybe you have to filter the messages you receive before doing anything with them? i.e Make sure they come from the containing page (although I don't know where the others could be coming from...)

**Comment by travis1111** [comment]
thanks, but the setImmediate message comes from http://localhost, same as theia ide...

**Comment by epatpol** [comment]
So maybe they're used in a lib we use so we already have messages from within theia (just a guess). I think it would be a good first step to investigate where exactly those are coming from. In the case it's normal to have them you probably would need to filter down the message even more to make sure it's really the one coming from outside.

**Comment by epatpol** [comment]
@travis1111 I don't see the rest of the code but I assume you inject the implementation of a `WorkspaceService` in the constructor of that class or as a property?

`constructor(@inject(WorkspaceService) protected readonly workspaceService: WorkspaceService, ...)`


 If so you should be able to access it with the `this` object like so `this.workspaceService.open(...)`

**Comment by travis1111** [comment]
@epatpol yes I did here is the code:

```
import { injectable, inject } from "inversify";
import { WorkspaceService } from '@theia/workspace/lib/browser/workspace-service';
import { CommandContribution, CommandRegistry, MenuContribution, MenuModelRegistry } from "@theia/core/lib/common";
import { CommonMenus } from "@theia/core/lib/browser";
import { FrontendApplicationContribution, FrontendApplication } from "@theia/core/lib/browser";
import URI from "@theia/core/lib/common/uri";
import { FileSystem } from '@theia/filesystem/lib/common';

export const DemoCommand = {
    id: 'Demo.command',
    label: "Shows a message"
};

@injectable()
export class DemoCommandContribution implements CommandContribution {

    constructor(
        @inject(FileSystem) protected readonly fileSystem: FileSystem,
        @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService,
    ) { }

    registerCommands(registry: CommandRegistry): void {
        registry.registerCommand(DemoCommand, {
            execute: () => this.openProject()
        });
    }
    
    protected openProject(): void {
        this.workspaceService.close();
        this.workspaceService.open(new URI("file:///home/" + "aaa"));
    }
}

@injectable()
export class DemoFrontendContribution implements FrontendApplicationContribution {
    constructor(
        @inject(FileSystem) protected readonly fileSystem: FileSystem,
        @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService,
    ) { }

    onStart(app: FrontendApplication): void {
        alert("start");
        window.addEventListener("message", function(event) {
          try {
            if ( event.data.startsWith('setImmediate') )
            {
                return;
            }
            alert("hhhhh");
            this.workspaceService.open("file:///home/" + event.data);
          } catch (e) {
            //console.error('Invalid json', event);
          }
        	    
        }, false);
        alert("registered");
    }
}
@injectable()
export class DemoMenuContribution implements MenuContribution {

    registerMenus(menus: MenuModelRegistry): void {
        menus.registerMenuAction(CommonMenus.EDIT_FIND, {
            commandId: DemoCommand.id,
            label: 'Say Hello'
        });
    }
}
```
But compile failed:

``
$ tsc
src/browser/demo-contribution.ts(50,18): error TS2339: Property 'workspaceService' does not exist on type 'Window'.
```

**Comment by epatpol** [comment]
@travis1111 What about doing something similar to the [frontend-application](https://github.com/theia-ide/theia/blob/e0222f81ddb35a2cdd862f8de81078bfe5b8ce4e/packages/core/src/browser/frontend-application.ts#L97).

I'm not sure what's different in your case, but the `this` seems to refer to window instead of the class.

**Comment by travis1111** [comment]
Almost there!

this is my code

```javascript
@injectable()
export class DemoFrontendContribution implements FrontendApplicationContribution {
    constructor(
        @inject(FileSystem) protected readonly fileSystem: FileSystem,
        @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService,
    ) { }

    protected async closeWorkspace(event: any): Promise<void> {
        const dialog = new ConfirmDialog({
            title: 'Close Workspace',
            msg: 'Do you really want to close the workspace and switch to a new one?'
        });
        if (await dialog.open()) {
            await this.workspaceService.close();
            await this.workspaceService.open(new URI("file:///home/microclimate-workspace/" + event.data));
        }
    }
    
    protected callback(event : any): void {
        try {
            if ( event.data.startsWith('setImmediate') )
            {
                return;
            }
            alert("hhhhh");
            this.closeWorkspace(event);
          } catch (e) {
            //console.error('Invalid json', event);
          }
        	  
    }
    
    onStart(app: FrontendApplication): void {
        alert("start");
        window.addEventListener("message", event => this.callback(event), false);
        alert("registered");
    }
}
```

Current issue is, I can see the confirmation dialog, after I click OK, the iframe refreshes itself but shows `` you have not yet opened a workspace``, if I send the postMessage again, then I can see the new workspace.

What could be the issue here?

**Comment by epatpol** [comment]
Looking at `WorkspaceService` it seems calling `this.workspaceService.close();` also reloads the window. So maybe this causes an issue where you reload the window and the `this.workspaceService.open(...` never gets called?

I'm not sure, maybe try debugging this code in the frontend? Or what exactly are the steps you would like here. This is what I understand:

* Send a new workspace from outside
* Confirm dialog from inside
   * Do nothing *or*
   * Open the new workspace

I'm not sure you even have to close the current one, but if you only call open I believe it wants to open in a new window/tab right?

**Comment by travis1111** [comment]
Yes it opens a new window

**Comment by travis1111** [comment]
it is working now, see https://github.com/theia-ide/theia/issues/1639
