### ISSUE TITLE
How can I make theia-ide (browser) portable

### ISSUE THREAD

**Issue by santoshray02** [theia-ide/theia#1633]
How can I make theia-ide (browser) portable?

**Comment by santoshray02** [comment]
I compiled and build it in one directory and try to run the build in another directory . (I have copied and pasted all the build to another directory ) 
![screenshot 1](https://user-images.githubusercontent.com/12428112/38289344-4fe8c89e-37f3-11e8-93dc-59ab0be02343.png)

**Comment by svenefftinge** [comment]
You can't. Theia uses yarn workspaces which hoists all npm packages to a common parent `node_modules` folder plus adds symbolic links to the developed npm packages there.
