### ISSUE TITLE
[tasks] output to terminal is broken

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1634]
When a task runs, that uses a terminal process, ```"processType": "terminal"``` in its configuration, a terminal used to be created, in which the output of the task was displayed. This no longer happens in master - must have broken at some point and went unnoticed.

**Comment by azatsarynnyy** [comment]
I guess it's because of widget factory was used to create a TerminalWidget and attach it to the app shell. But after the #1480, widget factory just creates a TerminalWidget w/o attaching it the shell.

**Comment by azatsarynnyy** [comment]
I've proposed a fix in #1635

**Comment by marcdumais-work** [comment]
Cool, I will try your PR.
