### ISSUE TITLE
Minor issue: text - selectbox overlapping in output widget

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#1637]
In the output widget, there is a minor issue regarding the text - selectBox overlapping when the browser resizes. 
The widget should be smart enough to wrap the last word in case that the widget does not have enough width.

Demo:
![peek 2018-04-03 10-23](https://user-images.githubusercontent.com/37082801/38255423-bf2c0722-3729-11e8-9f23-d0647257558e.gif)

**Comment by elaihau** [comment]
will be resolved by https://github.com/theia-ide/theia/issues/1637

**Comment by elaihau** [comment]
will be resolved by https://github.com/theia-ide/theia/pull/5134

**Comment by vince-fugnitto** [comment]
Fixed in #5134 :)
