### ISSUE TITLE
How to close and set new workspace root and NOT open a new window?

### ISSUE THREAD

**Issue by travis1111** [theia-ide/theia#1639]
What i would like to do is allow customers to open a new workspace root in one action.

I have this code:

```javascript
protected async closeWorkspace(event: any): Promise<void> {
        const dialog = new ConfirmDialog({
            title: 'Close Workspace',
            msg: 'Do you really want to close the workspace and switch to a new one?'
        });
        if (await dialog.open()) {
            await this.workspaceService.close();
            await this.workspaceService.open(new URI("file:///home/" + event.data)), ;
        }
    }
```

it is not working, theia editor refreshed itself once, then shows

```sh
you have not yet opened workspace
```

but if I call that method again, (since workspace is already closed), then I can see the new workspace.  So I guess the ``workspace.close()`` will cause a browser refresh, in that case, the ``open`` command never get called. 

So how to make the close the open in one action?

**Comment by epatpol** [comment]
Actually, looking at `WorkspaceService.open` : 

`    open(uri: URI, options?: WorkspaceInput): void {`

We see that there's some WorkspaceInput optional argument. Looking at it : 

```
export interface WorkspaceInput {

    /**
     * Tests whether the same window should be used or a new one has to be opened after setting the workspace root. By default it is `false`.
     */
    preserveWindow?: boolean;

}
```

Can you try calling `workspaceService.open(..., {preserveWindow: false});` ?

**Comment by travis1111** [comment]
Thanks @epatpol 
not I tried with ``true`` and ``false``, it always open a new window

this is the new code

```javascript
protected callback(event : any): void {
        try {
            if ( event.data.startsWith('setImmediate') )
            {
                return;
            }
            
            //this.closeWorkspace(event);
            this.workspaceService.open(new URI("file:///home/" + event.data), 
                {preserveWindow: true});
          } catch (e) {
            //console.error('Invalid json', event);
          }
        	  
    }
```

**Comment by travis1111** [comment]
Look at this line:

https://github.com/theia-ide/theia/blob/ceec46c93c316fe87903c2a1b2c454fc0e726dcb/packages/workspace/src/browser/workspace-service.ts#L93

I think that one set the preserveWindow to false
so no matter what I pass in, it is always false, thus always open a new window

**Comment by epatpol** [comment]
@travis1111 I was commenting exactly that just now from the debugging I did.

Indeed this is a bug and should be fixed I think.

**Comment by travis1111** [comment]
cool, so there is something open new window too see #1631

**Comment by epatpol** [comment]
#1644 was opened, if you can, it would be nice to try that patch with your application and see if it solves your issue.

**Comment by travis1111** [comment]
Thanks saw it... we build theia in a container... I will take a look of the build process and see how we build it :) but yes I want to test the change!! thanks for fixing it!

**Comment by epatpol** [comment]
You can try it again with the latest master and report back if it works for you.

**Comment by marcdumais-work** [comment]
@travis1111 you did not mention, but If you build Theia from npm modules (vs from source), you'll have to wait a few minutes for the new "next" version to be published. And of course use "next" instead of "latest".

**Comment by travis1111** [comment]
@marcdumais-work Tried with next build, no new window :-) but still old workspace :-(

https://github.com/theia-ide/theia/issues/1643

**Comment by marcdumais-work** [comment]
@travis1111 there is still a bug getting in the way: https://github.com/theia-ide/theia/pull/1656

**Comment by travis1111** [comment]
@marcdumais-work Thanks!!! I am ready to test it as soon as it is in npm! :-)

Thank you!!!! and @epatpol !!!! you guys are great!!!!

**Comment by travis1111** [comment]
Thanks!!! @epatpol  @marcdumais-work  it works now!!! I can switch the workspaces now!! :-) with #1656
