### ISSUE TITLE
Undo should remove the "dirty" state of the editor

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#1640]
If I start typing in an editor, the editor is marked as "dirty" with the small circle in the tab. If I undo the change, it is still dirty. Then if I try to close the tab, it pops-up to ask to save. This can be annoying because it happens very often that I start typing and change my mind, or I type accidentally.

Edit: this is with auto-save OFF

**Comment by kittaakos** [comment]
Are you sure it does not work? I know it is annoyingly slow, but could you please verify it again? I did it on OS X in Chrom. Thanks!

![gh-1640](https://user-images.githubusercontent.com/1405703/38317639-cfb048e2-382d-11e8-9fd4-ab41aaf9bad0.gif)

**Comment by MarkZ3** [comment]
It looks like you have auto-save on? Sorry my case was when using auto-save off, which means in the whole process there was no save and it should detect that it is back to the unmodified state. It looks like the dirty state is only cleared by saving right now, not undoing.

**Comment by kittaakos** [comment]
I see; it makes sense. Thanks for explaining.

**Comment by MarkZ3** [comment]
I think this is a show-stopper for C/C++. Change one 'core' header by mistake and you have to recompile your whole code base, which can take hours. @simark is this something that affects you too? Just making sure I'm not alone being clumsy here!

**Comment by simark** [comment]
> I think this is a show-stopper for C/C++. Change one 'core' header by mistake and you have to recompile your whole code base, which can take hours. @simark is this something that affects you too? Just making sure I'm not alone being clumsy here!

I completely agree with you.  @vince-fugnitto has been doing a ton of usability improvements.  Vince, do you think we can put this on your to-do list?

**Comment by vince-fugnitto** [comment]
The problem is even more visible now since we've set `auto-save` off by default #4777
I am constantly making new changes, undoing them, and the editor still has the dirty state (which is annoying as an end user).
