### ISSUE TITLE
Different electron issues when opening several workspaces

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1641]
Here's how I reproduce it:

* Launch the electron version and open a new workspace (or keep the current opened workspace if existing)
*  File -> Open -> Another workspace
* This opens a new electron window

Go to File -> Close Workspace in the *first* electron window

`Close Workspace` dialog is then opened in the *second* electron window.

Expected behaviour is to see the window opened in the first one.

Update: It seems that most (haven't tested all, but I assume it's all of them) are executed in the second electron window.

Also, it seems that if I close the *second* window. The first window becomes unresponsive (offline status bar kicks in) and trying to execute commands from it returns the following error in the back-end:

```
Attempting to call a function in a renderer window that has been closed or released.
```

**Comment by marechal-p** [comment]
There is still the problem of the web worker being shutdown for some reason when we close one window but not all, still looking into it.
