### ISSUE TITLE
preserveWindow option is ignored in the WorkspaceService.open API

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1643]
As seen in https://github.com/theia-ide/theia/issues/1639

**Comment by epatpol** [comment]
I'll ask somebody to review and hopefully approve it by today. I just want to make sure it's not breaking anything (even though the change is so small).

**Comment by travis1111** [comment]
Thank you so much!!!

**Comment by travis1111** [comment]
Thanks @epatpol 

With preserveWomdow set to true, it won't open a new window, this is goof :-) thanks!

But unfortunately, if the workspace is not closed, not matter what I do, the switch just doesn't work.  Still stays with the old workspace root.  Unless I close it...

now what to try now?

**Comment by travis1111** [comment]
@epatpol thanks for fixing it, I will give it a try as soon as it is in npm. :-) . thanks!
