### ISSUE TITLE
[terminal] intermitent line wrap issue for 1st terminal

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1646]
I have momentarily reproduced this on latest master, but can't anymore. It does seem to reproduce consistently in a docker image I have, based on master from a couple of days ago: (@theia/core 0.4.0-next.ceec46c9).

In that image, with a freshly restarted client, the first terminal I start, it wraps before reaching the full width of the widget and remains on the same line after, until I hit "enter":
![peek 2018-04-04 07-32](https://user-images.githubusercontent.com/25749063/38305301-6590c142-37da-11e8-89e3-8681a0317f92.gif)

**Comment by svenefftinge** [comment]
Couldn't reproduce this resizing issue. We've done a lot of fixes in this area since last year. 
Please reopen if this is still a thing.
