### ISSUE TITLE
Openshift

### ISSUE THREAD

**Issue by JamesDrummond** [theia-ide/theia#1655]
I would like to run Theia in Openshift. However, there are certain guidelines for docker images that can run in Openshift https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines . I would like to propose in creating an new Dockerfile for Openshift whos parent image is 'theiaide/theia'. Maybe call this image 'theiaide/theia-openshift'. Below is what I would propose.

https://github.com/devcomb/dockerfiles/blob/master/theia/Dockerfile
```
FROM theiaide/theia
COPY entrypoint /home/theia/
RUN chgrp -R 0 /home/theia && \
    chmod u+x /home/theia/entrypoint && \
    chmod -R g=u /home/theia && \
    chmod g=u /etc/passwd
USER 10001
ENTRYPOINT ["/home/theia/entrypoint"]
CMD yarn theia start /home/project --hostname 0.0.0.0
```

https://github.com/devcomb/dockerfiles/blob/master/theia/entrypoint
```
#!/bin/bash
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}$
  fi
fi
exec "$@"
```

If you have openshift.io account you can test with my image 'devcomb/theia-openshift'.

Also where do you keep your Dockerfile that dockerhub images are based on. Found out that the CMD is different in dockerhub latest image versus https://github.com/theia-ide/theia/blob/master/examples/browser/Dockerfile . 

Let me know your thoughts and if you want me to open PR.

**Comment by svenefftinge** [comment]
We maintain Docker files over in https://github.com/theia-ide/theia-apps.
There are discussions regarding this in https://github.com/theia-ide/theia-apps/pull/35 and https://github.com/theia-ide/theia-apps/pull/10. 
Having dedicated images for open-shift sounds good to me.

**Comment by JamesDrummond** [comment]
@svenefftinge Funny I was trying to find that post #10 I made when I started this ;) . I will create a pull request over there. You should update your dockerhub page https://hub.docker.com/r/theiaide/theia/ to include where the dockerfiles are located on github.

**Comment by JamesDrummond** [comment]
@svenefftinge How do you guys do your docs? I am planning writing an article only how to get Theia working on Openshift with a front end proxy(openshift/oauth-proxy:latest) that provides authentication through Openshift backend. I could write markdown for it. Not sure how gitbooks works that you use at http://www.theia-ide.org/doc/.

The proxy front end is nice for people using Openshift Origin like myself as it gives me a safe way to work on my on remote server when using Theia IDE. It should also be able to be used on openshift.io but I i haven't tested.

BTW Theia's interface is really quick :) . Do you know what the front end that Monaco uses for the user interface. Is it there own custom frontend. I am trying to decide between vuejs/angular/react right now on a user interface framework for my own project I am working on.

Looking forward to the Che's integration with Theia!

**Comment by epatpol** [comment]
@JamesDrummond Right now there's documentation for developing theia in [this repo](https://github.com/theia-ide/theia/tree/master/doc). But there's also some on the [website](http://www.theia-ide.org/doc/index.html) which is generated from the [website repo](https://github.com/theia-ide/theia-website). I don't know where I would put the documentation for running theia on openshift however. I think on the main website as an example to how to run it would be nice.

Also pretty cool for the proxy that would provide authentication. I'm interested to see how easy/difficult it is to setup :)

**Comment by JamesDrummond** [comment]
I'll leave this issue open till Travis CI integrates image into build and upload to docker hub. Feel free to close on my behalf when done.

**Comment by gorkem** [comment]
Closing

**Comment by marcdumais-work** [comment]
Issue to track adding the OpenShift image to CI / docker publish: https://github.com/theia-ide/theia-apps/issues/42
