### ISSUE TITLE
Client "offline" mode falsely reported

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1657]
I have recently noticed that my client reports being "offline" when it's actually not. It's not just kicking-in momentarily, but rather seems to stay in that mode indefinitely, once it triggers. 

Looking at the backend logs, it seems that the "alive request" is responded-to as expected: 
```
{"name":"Theia","logger":"root","hostname":"elxa610sxy1","pid":16374,"level":10,"msg":"Checking backend connection status. Scheduled an alive request with 1000 ms timeout. []","time":"2018-04-05T09:18:47.944Z","v":0}
{"name":"Theia","logger":"root","hostname":"elxa610sxy1","pid":16374,"level":10,"msg":"Connected to the backend. []","time":"2018-04-05T09:18:47.946Z","v":0}

```

**Comment by epatpol** [comment]
I have also noticed that sometimes, and the client still works perfectly even though it says offline mode.

**Comment by svenefftinge** [comment]
I also noticed the offline status is stored on unload and it seems that on load it is not updated with the actual state. So it stays offline.

**Comment by spoenemann** [comment]
It happens when the FrontendConnectionStatusService initializes the connection status before the shell has restored its state from the local storage.

StatusBarImpl.setBackgroundColor waits for the status bar to be attached, but that does not include completing the initial layout.
