### ISSUE TITLE
Where is Theia storing problems view items?

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1666]
Theia remembers the items in the problems view between sessions.  How are these being stored?  How can we clear them?

**Comment by kittaakos** [comment]
From here: https://github.com/theia-ide/theia/blob/942e03603b7c35d5650616329e0f68ad1d92acd3/packages/markers/src/browser/marker-manager.ts#L131

The browser implementation uses the `window.localStorage`.

Although I did not try it, one can delete the local storage in Chrome: https://superuser.com/questions/519628/clear-html5-local-storage-on-a-specific-page

Let me know how it works.

PS: from code, you should be able to call `window.localStorage.clear` or something like this.

**Comment by kittaakos** [comment]
Related: https://github.com/theia-ide/theia/issues/1352

**Comment by jopit** [comment]
Deleting the local storage in Chrome does work, thanks.
