### ISSUE TITLE
Disable the `Merge Conflicts` commands when nothing to merge.

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1667]
Otherwise, it throws an error if no editors nothing is opened:
```
merge-conflict-resolver.ts:51 Uncaught TypeError: Cannot read property 'uri' of undefined
    at MergeConflictResolver.../../packages/merge-conflicts/lib/browser/merge-conflict-resolver.js.MergeConflictResolver.doAccept (merge-conflict-resolver.ts:51)
    at MergeConflictResolver.../../packages/merge-conflicts/lib/browser/merge-conflict-resolver.js.MergeConflictResolver.doAcceptIncoming (merge-conflict-resolver.ts:38)
    at Object.execute (merge-conflict-resolver.ts:25)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (command.ts:166)
    at quick-command-service.ts:84
```

<img width="621" alt="screen shot 2018-04-06 at 16 27 14" src="https://user-images.githubusercontent.com/1405703/38426672-9517c5a8-39b7-11e8-9c55-719aca1f4e36.png">

**Comment by AlexTugarev** [comment]
They shouldn't appear here at all.

**Comment by kittaakos** [comment]
AFAIK, if a command has a label, it appears. But I am not sure about it, that was my experience. At least, when I did not specify a `labe`l for the command, it did not appear.

**Comment by kittaakos** [comment]
@akosyakov, do you know whether showing all the commands with the `label` property among the quick item is a bug (regression) or the desired behavior? Thanks!

**Comment by AlexTugarev** [comment]
@kittaakos I've checked quickly, it's not necessary to register command with labels for code lenses, only the id's are required. This can easily be fixed.

**Comment by AlexTugarev** [comment]
this lines needs to be changed, so that only label-less commands are registered:
https://github.com/theia-ide/theia/blob/6af80f4a096b80d6e803fa107b36fe69905bc6ab/packages/merge-conflicts/src/browser/merge-conflicts-frontend-contribution.ts#L48-L50

**Comment by kittaakos** [comment]
Cool, thanks for checking; still I would like to know whether this is the desired behavior or not. So that, it will not cause confusion next time.

**Comment by AlexTugarev** [comment]
I think this is indeed the desired behavior. I also ask that question once, and the looked it up:
https://github.com/theia-ide/theia/blob/5c23bd8c0b29e3b14f56ba7ccc1415cb3740bb93/packages/core/src/browser/quick-open/quick-command-service.ts#L28-L30
