### ISSUE TITLE
The Electron application should have a system icon

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1669]
The icon shown for the Electron application (for example when you alt-tab) is a generic one.  It should be the Theia logo.

**Comment by kittaakos** [comment]
It cannot be unless you brand and bundle your application. See here: https://github.com/theia-ide/theia-apps/compare/GH-3. If you have no objections, I would like to close this issue.

**Comment by kittaakos** [comment]
Also; https://github.com/theia-ide/yangster-electron/releases.

**Comment by simark** [comment]
Ah ok sorry for the noise.
