### ISSUE TITLE
LSP tracing configuration

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1674]
One already can see a language server output in the output view per a language. If tracing is enabled then the output contains JSON-RPC messages as well.

Right the only way to enable tracing is via changing a client language contribution. It would be nice to have other means, for example via the cli options, e.g. `--trace-java` option. What do you think?

cc @simark @svenefftinge 

Also should be fixed as the part of this task: https://github.com/theia-ide/theia/pull/1653#issuecomment-380138891

**Comment by simark** [comment]
I think it would be nice if it was configured the same way as other loggers, for consistency.

**Comment by akosyakov** [comment]
Yes, it sounds good.

**Comment by akosyakov** [comment]
After https://github.com/theia-ide/theia/pull/1771, it would be better to manage tracing per a JSON-RPC connection, not only per a language server.

**Comment by akosyakov** [comment]
It will be implemented generically via preferences for all language servers with `vscode-languageclient`.

With the following preferences, replace `typescript` with your language:
```
{
  'typescript.trace.server': 'off' | 'messages' | 'verbose' | {
    'verbosity': 'off' | 'messages' | 'verbose'
    'format': 'text' | 'json'
  }
}
```

After enablding tracing the user will be able to see tracing in the output view for the corresponing language server.

**Comment by akosyakov** [comment]
For example for json:
![tracing](https://user-images.githubusercontent.com/3082655/44788934-9dc4c880-ab9b-11e8-9698-cb396e7cae24.gif)
