### ISSUE TITLE
Consider updating `xterm.js` (3.3.0) to support multi-line links in terminal

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1679]
Milestone 3.3.0 is almost complete, see https://github.com/xtermjs/xterm.js/milestone/24?closed=1. 

Especially the [multi-line link matching](https://github.com/xtermjs/xterm.js/pull/1303) is worth looking into an upgrade once it's released. 

BTW the `vscode-xterm` package is basically the master state of xterm.

**Comment by svenefftinge** [comment]
@AlexTugarev you mentioned that you have tested the vscode version and that it worked nicely. 
If that is the case and it is more regularly updated we should use it, too.

**Comment by AlexTugarev** [comment]
As we depend on `^3.0.`, we've updated it automatically with recent `yarn.lock` update.
