### ISSUE TITLE
QuickOpen API enhancements

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#1680]
I'd like to propose to extend QuickOpen API to allow to use the `QuickOpenService` in two modes:
1. When it's opened with a list of custom elements like it currently works.
2. When it's opened with a list of the registered `QuickOpenHandler`s (see the screencast from VScode).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1636395/38560858-492756a6-3cdf-11e8-9a69-bd849751994d.gif)

`QuickOpenHandler` has an ID, description and can return QuickOpenModel. `QuickOpenHandler` represents actually a shorthand for a frequently used command. E.g.:
- `>` handler calls `CommandQuickOpen`;
- `...` handler calls `QuickFileOpen`;
- `task ` handler calls `TaskQuickOpen`;
- etc.

Some `QuickOpenHandler` can be registered as a default handler i.e. that handler will be called automatically upon opening QuickOpen with Ctrl+P (it should be `Go to File`).
Also, there should be a contribution point that will allow the extensions to contribute its own QuickOpenHandlers.

So user hits Ctrl+P to call QuickOpen in a second mode (with handlers) and `QuickFileOpen` is shown since `...` is a default handler. Once the entered text matches an ID of one of the registered `QuickOpenHandler`s, then list of the items provided by the related handler will be shown.
The behavior of the feature should be very similar to the VSCode.

**Comment by azatsarynnyy** [comment]
Also, there should be a contribution point that will allow the extensions to contribute its own `QuickOpenHandler`s.
And one `QuickOpenHandler` can be registered as a default handler i.e. that handler should be called automatically when no ID is specified in QuickOpen. Obviously, it should be a handler that calls Go to File QuickOpen.

**Comment by azatsarynnyy** [comment]
Would you be interested in such enhancement?

**Comment by azatsarynnyy** [comment]
I've updated the description.
@svenefftinge would you be interested in such feature?

**Comment by svenefftinge** [comment]
In VS Code I personally don't use it because it is more key strokes than just directly trigger the right command. It is nice for discoverability, though, but the command palette does that well, too.

I would say other things are more important atm. But I am not strictly against it in the hope it wouldn't affect the existing QuickOpenHandler API too much.

**Comment by azatsarynnyy** [comment]
As I see it won't affect the existing QuickOpen API clients.
Thanks.
