### ISSUE TITLE
Moving Java language server binary out of tree

### ISSUE THREAD

**Issue by ishitatsuyuki** [theia-ide/theia#1685]
The Java LS jar should be downloaded with a postinstall script, not by bundling inside the package.

The current approach has two downsides:

- Blob in git repository makes clone very slow.
- Blob in npm package bloats npm/yarn cache directory.

**Comment by gorkem** [comment]
I do not think having binaries on the repo is a good idea. I would also like to see a way to give a specific version of the jdt.ls rather than "latest"

**Comment by benoitf** [comment]
I had same issue cloning
I saw that two entries that is using the whole size where almost
```
100644 blob 9055419b154944b15c13dfe21d605ada9e7aca39 34858956    packages/java/download/jdt-language-server-latest.tar.gz
100644 blob f4b50cf19f5c0273023bad234530d92b4d14779d 31767672    packages/java/download/jdt-language-server-latest.tar.gz
```

at one time we used https://git-lfs.github.com/ (there is pro/cons as well) which allow to store binaries as part of git repository.

**Comment by ishitatsuyuki** [comment]
We don't have to. We can use the legacy scheme, which downloads the official artefact directly. If you're worried about availability, you can cache it in the CI and/or pin multiple mirror URLs instead.

The tagged releases are available at http://download.eclipse.org/jdtls/milestones/.

**Comment by akosyakov** [comment]
Please take local builds in the consideration as well. The issue was that developers were blocked, since local builds failed because eclipse was not reachable. It was annoying since the most of the work does not happen on the java extension.

BTW i am not saying that we should not do it. We should, but previous experience should be taken in the consideration.

**Comment by benoitf** [comment]
@ishitatsuyuki I agree with you, as it seems the main issue was that repository was down sometimes, as Eclipse has mirrors the script could check a various list of mirrors (or get the closest one)

for example even if main repo is down, you may still get from one mirror like
https://ftp.gnome.org/mirror/eclipse.org/jdtls/


@akosyakov I think that with mirrors, we should have always have at least one mirror working.

**Comment by akosyakov** [comment]
Although an archive is removed from git, unarchived artifacts are still in git. They should be removed as well. Plus download should happen only on `postinstall` npm script, not on `prepare` as now, otherwise it is executed during publishing.

**Comment by AlexTugarev** [comment]
@akosyakov we would need to rewrite the gulpfile, or add `gulp` to dependencies. which one is to prefer?

**Comment by akosyakov** [comment]
Whatever has less dependency overhead and simple.
