### ISSUE TITLE
[Workspace open] Cursor navigation broken

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1692]
In the open... dialog the cursor navigation no longer works.

**Comment by epatpol** [comment]
I looked at it a bit, it's weird, arrow up/down seems to not move the selected element, but doing it a few times and pressing open actually opens something that should be selected (but simply not shown).

i.e

```
Element1 -> Selected
Element2
Element3
Element4
```

Pressing Down two times should have `Element3` selected but it appears like it's still on `Element1`. Pressing Open then opens `Element3`.
