### ISSUE TITLE
Support for EditorConfig

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#1694]
Add an extension supporting [EditorConfig](http://editorconfig.org/) to define coding styles.

Working on extension is in branch
https://github.com/theia-ide/theia/tree/editorconfig

**Comment by akosyakov** [comment]
How is it going to be integrated with the current preferences?

[VS code extension](https://github.com/editorconfig/editorconfig-vscode) overrides configurations user/workspace editor settings. Would not it make sense in our case as well?

**Comment by vitaliy-guliy** [comment]
We also override editor configuration. Editorconfig has bigger priority than editor preferences.

**Comment by akosyakov** [comment]
I meant we should consider whether we want to make sure that the preferences API return the consistent result with what users see in editors. If so then we should hook it up in the preferences machinery.

cc @svenefftinge
