### ISSUE TITLE
Search within workspace files: Action / widget

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#17]
Users need to search the workspace. A "Find In Path" Action should open a search widget in which I can type in text and hit search. The list of matches should be shown below in a tree like fashion.
-  Top level - files
-  Second level - matches within files
Double click on an item should open and reveal the match.

The view should later allow to do replace as well and should offer some common options like regex, case-insensitivity, whole-word-match. But these additional things should be covered in extra tickets.

The feature will require a specific extension to the FileSystem API, as we obviously don't want to load the contents of the whole workspace into the frontend.

**Comment by svenefftinge** [comment]
The basic search functionality is there. But we still lack the UI, some configuration features and replace functionality.

**Comment by AlexTugarev** [comment]
They are switching from sidebar to panel.

<img width="1635" alt="screen shot 2018-04-03 at 09 12 13" src="https://user-images.githubusercontent.com/914497/38234851-61f9614e-371f-11e8-89ac-c59a8f974b53.png">

**Comment by jbicker** [comment]
Yes.
