### ISSUE TITLE
`Widget was activated, but did not accept focus` is flaky

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1707]
Got false positives during debugging and on slow connections. To reproduce open an editor, throttle your connection (not with Chrome - it cannot throttle web sockets), refresh the page.

**Comment by spoenemann** [comment]
See #1061 and #1604.

**Comment by spoenemann** [comment]
The current implementation waits for one animation frame and then checks focus. We should change it to wait further animation frames if focus is still not set, up to some maximum like 10 frames or so.
