### ISSUE TITLE
Make format-on-save work when editing Typescript (theia-in-theia)

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1710]
One drawback of switching to Theia to develop Theia is the lack of format on save like in vscode.  The manual alternative is invoke the command by hand (`ctrl+i`).

I looked into it a little bit, I started to implement the server side here:

https://github.com/simark/typescript-language-server/tree/will-save-wait-until-attempt

However, I can't get Theia to send those `willSaveWaitUntil` requests, where we could reply the edits to apply before saving.  I am not sure where they should originate from.  The monaco code, or our code?  I am not actively working on it, so feel free to pick it up.  Or if you have specific pointers that could help me, provide them here and I might look into it again.

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/blob/e349656d573f69623e301bfce0b589ecdc3e1de3/packages/monaco/src/browser/monaco-workspace.ts#L141 should fire a workspace event

https://github.com/TypeFox/vscode-languageserver-node/blob/39a33129955b7ad747cd1ad8fb44d06718421fca/client/src/base.ts#L474 should send an event to a language server

**Comment by vince-fugnitto** [comment]
I believe it's been addressed by https://github.com/theia-ide/theia/pull/4012
Please re-open the issue @simark if it's not the case :)
