### ISSUE TITLE
Fix bug when renaming opened files

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#1712]
After renaming the opened file its tab title still has old name.
Opened file does not update its path after renaming its parent folder.

![rename](https://user-images.githubusercontent.com/1655894/38858559-b3e28880-4234-11e8-8aad-bd285cdd50e1.gif)

**Comment by AlexTugarev** [comment]
I think it's a duplicate of https://github.com/theia-ide/theia/issues/230. Please reopen, or comment on the other issue, if you find more information on this.
