### ISSUE TITLE
[cluster] Enabling debug mode is failing

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#1715]
When in cluster mode, we are allowed to pass arguments to IPC services in order to enable the inspect mode, per server name. Problem is, there are multiple workers for the same server name, which means that they will all try to use the same debug port, and then crash them because of this.

**Comment by akosyakov** [comment]
For dynamic port allocation use `--nfsw-watcher-inspect=0`.

**Comment by marechal-p** [comment]
My bad indeed ! Now the worker enters in debug mode, but the vscode configuration thinks that the port used to connect to it is 0...

**Comment by marechal-p** [comment]
But in essence it works, closing.
