### ISSUE TITLE
(Question) When is the next version of Theia going to be released?

### ISSUE THREAD

**Issue by gindik** [theia-ide/theia#1718]
There have been fixes delivered that we are looking leverage. Would it be possible to get an estimate on when the next version will be released?

**Comment by akosyakov** [comment]
You can use `next` as a version to use the latest changes from master. After running `yarn` versions will be locked by yarn, so new changes in the master should not break. In order to catch up with changes `yarn.lock` file should be deleted and `yarn` should be run again.

**Comment by marcdumais-work** [comment]
@gindik as mentioned, you can get the benefits of the latest master version using "next", assuming all your dependent Theia extensions are up-to-date (may not always be the case for the ones hosted outside ```theia-ide/theia```). 

About the next release: it will tentatively be towards the end of the month, so probably late next week or early the following one. I added an agenda item to discuss this during next's week Dev meeting.

**Comment by gindik** [comment]
Thank you!
