### ISSUE TITLE
[Markers] No marker icon in the gutter next to the marker's line

### ISSUE THREAD

**Issue by BoykoAlex** [theia-ide/theia#1720]
Eclipse, VSCode, Atom all show markers in the view (that's there), squiggly lines in the editor highlighting the range and a marker icon in the gutter.

**Comment by svenefftinge** [comment]
Theia does show squiggly lines and icons for diagnostics.
Could you be more precise what is missing?
What did you do and what was the expectation?

**Comment by BoykoAlex** [comment]
I saw the squiggly line :-) Which package adds squiggly lines? @theia/markers?
However, the error icon in the gutters i didn't see. Was expecting to see the error icon in the left gutters around line numbers next to the line where squiggly line is shown, but the icon wasn't there...

**Comment by AlexTugarev** [comment]
@BoykoAlex the error markers are located at the scrollbar.

<img width="1338" alt="screen shot 2018-04-19 at 17 01 59" src="https://user-images.githubusercontent.com/914497/39000083-6f53d866-43f3-11e8-984f-1307d53f5531.png">

We can also check, if it makes sense (if it actually works) to enable lightbulbs with monaco 0.12.0, ref PR https://github.com/theia-ide/theia/pull/1681.

**Comment by svenefftinge** [comment]
Please reopen if we missed something.

**Comment by BoykoAlex** [comment]
The error marker icon (not just colour) shows up in the left gutter around line numbers, but thinks it's far from being something absolutely necessary :-) Squiggly lines are working for me and markers in the scrollbar help too. Thanks very much!-)
