### ISSUE TITLE
[Git History] Command Doesn't Toggle

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#1727]
When hitting any menu point below the View menu, a tab opens somewhere. When hitting the same menu again, it closes the same tab again. This works neatly with Call Hierarchy, Extensions, Files, Git, and so on. But it fails with Git History. Opening the Git History works well, but when hitting the same menu point again, results in no action and no error. The tab remains open. Looks like an inconsistent and unintended behaviour to me. Bug?

**Comment by jbicker** [comment]
Yes, it was on purpose.

**Comment by kittaakos** [comment]
@jeanlucburot, thanks for the feedback. We did it on purpose. I would say, the other views behave strangely. For example, if the Git view is opened and one clicks on `View` > `Git` why would it close it. If it does not have the focus, it should grab the focus. But when it has the focus, nothing should happen. What's your take on that?

**Comment by jeanlucburot** [comment]
@kittaakos Oh ok. I just coincidentally opened all the Views and found this behaviour inconsistency. All is good though, if this was done on purpose. I absolutely agree, when hitting View > Git twice, it should only grab its focus and not close it. It should only be closed with a close button or close context menu.

**Comment by kittaakos** [comment]
Could you please open a follow-up issue describing the current odd behavior?
(Or reopen this issue and adjust the title.)

**Comment by spoenemann** [comment]
The current behavior is very convenient when you use the shortcuts to toggle views. For example, press cmd+shift+m to show the Problems view, press that again to close it.

This behavior was implemented as part of #1028. @svenefftinge proposed it in https://github.com/theia-ide/theia/pull/1028#issuecomment-356642336.

**Comment by jbicker** [comment]
Or show a check mark left of the menu title if the widget is shown.

**Comment by svenefftinge** [comment]
> We should show a check mark left of the menu title if the widget is shown.

I don't think electron menus support that, but we could check.

**Comment by vince-fugnitto** [comment]
Closed thanks to #4997
