### ISSUE TITLE
Support a remote backend in the electron app

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#174]
At the moment the electron app starts a backend server when its window loads.

This ties the electron app to a local backend.

We would need to implement a way to specify a backend url for the electron app to connect to. 

Maybe start with a cmd line option.

**Comment by svenefftinge** [comment]
I would prefer to have a real case here. I don't think a user would want to provide a URL manually.
Maybe connecting to a workspace server (e.g. Eclipse Che) and provide the available workspaces would be nice, but it needs a real context. In theory I do not see any issues with connecting to a remote backend rather than starting one.

**Comment by hexa00** [comment]
Well the real case is a user wanting to use the electron app with a remove backend, I thought that was one major use case ?

But yes it should not be an issue, the issue is more about how to present that to the user...

**Comment by marcdumais-work** [comment]
During internal discussions, a new argument in favor of using Electron as a front-end to connect to a remote workspace: one potential concern using a normal web browser as front-end is that there could be malicious browser plugins installed that could capture or even modify information passing through Theia, such as source code, without the user knowing.

**Comment by marcdumais-work** [comment]
@Zate Maybe you have some input about the perceived security concern above, of using a web browser to access a Theia workspace vs using Electron as front-end (i.e. its built-in chromium) to access the same workspace? Let's say in the case where Theia is used as an IDE to develop access-controlled, proprietary code, that resides on a remote server. 

To me it sounds like a valid concern, that a malicious browser extension could, e.g. send a copy of opened source files to a 3rd party or even inject/nodify source code, but I am not sure how realistic of a  threat it actually represents, vs other potential threats. 

P.S. If you have other ideas of security-related items that we should consider, we could create a separate issue to collect / discuss them.

**Comment by Zate** [comment]
@marcdumais-work thanks for the ping.  Just now getting to look at this.  I'll do some more research on what it means to the threat model for Electron+Remote vs Browser+Remote but I would highly suggest starting with this : https://github.com/electron/electron/blob/master/docs/tutorial/security.md#only-load-secure-content

I'll see what else I can find out and write up or collect.

**Comment by marechal-p** [comment]
Watching #1672

**Comment by marechal-p** [comment]
closing in favor of #2056

**Comment by echo-ray** [comment]
This project is awesome! 
Thanks a lot!
