### ISSUE TITLE
Consider reusing the same jdt.ls workspace on restart (for a given opened folder)

### ISSUE THREAD

**Issue by fbricon** [theia-ide/theia#1745]
A new workspace is created every time Theia starts jdt.ls:
https://github.com/theia-ide/theia/blob/bfd88d37b5aa25ef945f15c299513603b205fcf6/packages/java/src/node/java-contribution.ts#L36 

Workspace initialization can be extremely slow, depending on the size of the projects being opened. Reusing the same workspace (for the same projects) would increase startup performance by an order of magnitude or two.

cc @gorkem @tsmaeder

**Comment by svenefftinge** [comment]
Is that the equivalent to what a workspace is in Eclipse? Sounds reasonable to reuse it, putting it into the tmp folder will make it hard for users to clean it in case they have to (do they?).

**Comment by fbricon** [comment]
Yes it is exactly an Eclipse workspace.

**Comment by AlexTugarev** [comment]
@svenefftinge, clean up [may be necessary](https://github.com/theia-ide/theia/pull/1583#issuecomment-379296310). 

maybe we can move them under `~/.theia/java/workspaces/<workspace-identifier>` where `workspace-identifier` is a sanitized path of the workspace root. I think, we cannot move it into Theia workspace, as it overlaps then.

**Comment by marcdumais-work** [comment]
I have noticed that the Java LS takes a while to respond, for example for completions, after a client restart. This is probably due, at least partly, to the jdt.ls workspace being recreated each time?

**Comment by AlexTugarev** [comment]
Closing as resolved in #2970
