### ISSUE TITLE
The location drop down is not updated anymore

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1751]

**Comment by akosyakov** [comment]
<img width="777" alt="screen shot 2018-04-20 at 10 02 20" src="https://user-images.githubusercontent.com/3082655/39037833-fd428a6c-4481-11e8-9ab0-e155e8983280.png">

The drop down supposes to show all segments for a currently revealed folder. On the screenshot, you can see that it is not the case.

**Comment by svenefftinge** [comment]
Not sure I understand but isn't that just because you are looking at `/workspace`, i.e. there are no other segments?

**Comment by akosyakov** [comment]
In this case, it should be: `examples`, `theia`, `workspaces`, `/`.
