### ISSUE TITLE
[git] Git history shows incorrect commit date

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1754]
<img width="493" alt="screen shot 2018-04-20 at 10 01 33" src="https://user-images.githubusercontent.com/1405703/39037831-fb956450-4481-11e8-96c6-acc3cd5455e3.png">

One has to call:
```typescript
date.setUTCSeconds(Number.parseInt(time));
```

on the date when converting the epoch time to date.

Here: https://github.com/theia-ide/theia/blob/25c91c41a93b9e4f51786f7d9b5fca6a7bd19525/packages/git/src/browser/history/git-history-widget.ts#L113

**Comment by kittaakos** [comment]
Absolutely. It's yours. Let me know if you need help.

**Comment by AlexErling** [comment]
Hi, I could use a little help. Any information to point me in the right direction would be appreciated.
What type is the commit.author.timestamp, a string or a number? I am confused where to call 
```date.setUTCSeconds(Number.parseInt(time));```
I was thinking something along the lines of 
``` date.setUTCSeconds(Number.parseInt(commit.author.timestamp) ```

Any guidance would be great.

**Comment by kittaakos** [comment]
> commit.author.timestamp

It is a `number`. See:
https://github.com/theia-ide/theia/blob/a62d8eaa8434947777de09d3e2b28be948744b2b/packages/git/src/common/git-model.ts#L316

Here is a small snippet depicting the problem:
```javascript
const t = 1512511924;
console.log(new Date(t)); // Sun Jan 18 1970 13:08:31 GMT+0100 (CET)
const d = new Date(t);
d.setUTCSeconds(t);
console.log(d); // Sat Dec 23 2017 11:20:04 GMT+0100 (CET)
```

You need to do something like this:
```diff
diff --git a/packages/git/src/browser/history/git-history-widget.ts b/packages/git/src/browser/history/git-history-widget.ts
index 64e74f9d..b6c76107 100644
--- a/packages/git/src/browser/history/git-history-widget.ts
+++ b/packages/git/src/browser/history/git-history-widget.ts
@@ -108,9 +108,11 @@ export class GitHistoryWidget extends GitNavigableListWidget<GitHistoryListNode>
                     for (const commit of changes) {
                         const fileChangeNodes: GitFileChangeNode[] = [];
                         const avatarUrl = await this.avartarService.getAvatar(commit.author.email);
+                        const authorDate = new Date(commit.author.timestamp);
+                        authorDate.setUTCSeconds(commit.author.timestamp);
                         commits.push({
                             authorName: commit.author.name,
-                            authorDate: new Date(commit.author.timestamp),
+                            authorDate,
                             authorEmail: commit.author.email,
                             authorDateRelative: commit.authorDateRelative,
                             authorAvatar: avatarUrl,
```

**Comment by kittaakos** [comment]
And if you are there, perhaps, you could fix the typo in `avartarService`. It should be `avatarService` instead.

**Comment by AlexErling** [comment]
Okay, here are the changes I made then: 

```
const avatarUrl = await this.avatarService.getAvatar(commit.author.email);
const authorDate = new Date(commit.author.timestamp);
authorDate.setUTCSeconds(commit.author.timestamp);
commits.push({
    authorName: commit.author.name,
    authorDate: authorDate,
```

**Comment by kittaakos** [comment]
Looks good. FYI, you can shorten the object literal with this:
```typescript
const avatarUrl = await this.avatarService.getAvatar(commit.author.email);
const authorDate = new Date(commit.author.timestamp);
authorDate.setUTCSeconds(commit.author.timestamp);
commits.push({
    authorName: commit.author.name,
    authorDate,
```

If you would like to contribute, you have to provide your changes with a pull request and sign it. You can find additional details about it [here](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md). If you need help, forking, creating a PR or anything; do not hesitate to ask. I am happy to help you with the onboarding.

**Comment by AlexErling** [comment]
Okay, I sent in the PR. Let me know if there is something else I need to do. Also, let me know if you know of anything else or any other projects I could help out with. I would love to help out and learn more if possible!

**Comment by svenefftinge** [comment]
@kittaakos Could you elaborate why and how `setUTCSeconds` fix this? Also in https://github.com/theia-ide/theia/blob/a62d8eaa8434947777de09d3e2b28be948744b2b/packages/git/src/common/git-model.ts#L316 it is unclear what to expect. Is it the number of milliseconds til 01-01-1970 ? What timezone? Would be better to have an ISO string there.

**Comment by kittaakos** [comment]
We use [`--date=unix`](https://github.com/theia-ide/theia/blob/f98eb08fadfca8bb1377a493583f34b940516b6d/packages/git/src/node/dugite-git.ts#L510) to get the back the author-date of the commit.

 > `--date=unix` shows the date as a Unix epoch timestamp (seconds since 1970). As with `--raw`, this is always in UTC and therefore `-local` has no effect.

 AFAIK, one can convert the epoch time to JS date either with `setUTCSeconds(epoch)` or by using the constructor of date `new Date(setUTCSeconds * 1000)`. I am OK with both approaches or any better one too.

 > Would be better to have an ISO string there.

 Let's do that; anything would be better than 1970.

**Comment by kittaakos** [comment]
Do you have any updates on this, @svenefftinge or can we update the Git API (changing the epoch number to the desired string) in a separate ticket? If the fix is right, I do the review. Thanks!
