### ISSUE TITLE
Keybindings do not support keyboard layouts

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1764]
The current keybinding implementation uses the `code` property of KeyboardEvent. Unfortunately, [as described on MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code), this does not support keyboard layouts:

> The KeyboardEvent.code property represents a physical key on the keyboard (as opposed to the character generated by pressing the key). In other words, this property returns a value which isn't altered by keyboard layout or the state of the modifier keys.

**Comment by spoenemann** [comment]
In contrast to `code`, the numeric `keyCode` property works correctly. However, MDN says [it has been removed from the web standards](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode).

**Comment by svenefftinge** [comment]
Did you check how other browser IDEs deal with it?

**Comment by spoenemann** [comment]
JupyterLab uses the PhosphorJS command registry, which uses the `@phosphor/keyboard` package for key bindings:

https://github.com/phosphorjs/phosphor/blob/master/packages/keyboard/src/index.ts

It uses the deprecated `keyCode` property and translates that to a string using a static mapping.

I implemented a similar approach in theia-ide/sprotty#212.
