### ISSUE TITLE
Consolidate development scripts

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#177]
A subset of the scripts start with `$` in the `Developing.md` which seems to be alien in the npm world. Get rid of them.

To be a bit more specific, clean up the scripts that were introduced via: https://github.com/theia-ide/theia/commit/5c8834c6c2f053f6c8eba2f2da890dfb0c55c321#diff-4b4665bbdb3a58548d1a99002d045088

**Comment by hexa00** [comment]
I'm not sure what you mean ?

Like build / watch should become what?

**Comment by kittaakos** [comment]
I hope [this] clarifies.

[this]: https://github.com/theia-ide/theia/commit/5c8834c6c2f053f6c8eba2f2da890dfb0c55c321#commitcomment-22412625

**Comment by hexa00** [comment]
Haa ok I missread as 'scripts that start with $,, '

I'm fine with that

**Comment by kittaakos** [comment]
Please review @hexa00. PR: https://github.com/theia-ide/theia/pull/197. Thanks!
