### ISSUE TITLE
[osx][git] alt + left/right doesn't work in comment input field

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1772]
When writing multiple words I would like to navigate using alt+cursor left / cursor right.

**Comment by kittaakos** [comment]
I wasn't able to reproduce it locally, but I am not on the `master` branch currently. I will look into this in short.

![gh-1772](https://user-images.githubusercontent.com/1405703/39175934-d403eb28-47ab-11e8-9a8b-fa67dbb19e95.gif)

**Comment by kittaakos** [comment]
It was fixed via https://github.com/theia-ide/theia/pull/1705.
