### ISSUE TITLE
Cannot open another workspace (Pop-up blocker)

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1774]
1. Optional: delete `recentworkspace.json` file, then start Theia and open a workspace
1. Try to open another workspace, menu `File > Open...` and select a different location
1. Current browser tab is just reloaded, no new tab is opened.

In backend logs I see the following error:

```
[2018-04-25T08:10:25.995Z] ERROR: Theia/88467 on MacTugarev3.local: Error: Cannot open a new window for URL: http://localhost:3000/ []
```

--- 

### Update

Just realized, that Chrome's settings were reset after updating to v66. 

It was the pop-up blocker, that's why the new tab was not opened.

### Question

In that case, if new tab/window cannot be opened, should instead load the new workspace in same window? 

[`WorkspaceService`](https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/workspace-service.ts#L67) will reset workspace root back to previous value on unload.

**Comment by spoenemann** [comment]
Probably a duplicate of #1631?

**Comment by AlexTugarev** [comment]
@spoenemann, you are right, it's same as #1631. But it's generally caused by Pop-up blockers.
