### ISSUE TITLE
Set up nightly builds

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#178]

**Comment by akosyakov** [comment]
`gulp` seems just to use a branch for next release: https://github.com/gulpjs/gulp/tree/4.0
One can do `npm install gulpjs/gulp#4.0` to install it.
We could have a job that builds the master branch and if the build is successful then merge it to `theia-ide/theia#1.0` branch.

**Comment by hexa00** [comment]
I sounds weird to me that we would like to auto merge master into 1.0...

Usually we would branch out, then cherry-pick bug fixes into the release branch.. ?

I don't see the direct link between master and a version

**Comment by akosyakov** [comment]
We can use another branch name. We usually use a `SNAPSHOT` suffix for next version with maven, in js world is more common to use `next`, so it could be `next` as a branch name.

Also, I see that typescript project actually publishes nightly builds to npm with `next` tag. We can do the same, it will mean more hassle with version incrementing, but easy to discover for other.

**Comment by hexa00** [comment]
Couldn't we just name the nightly build date-shortcommit ? And not create a branch ?

To me a branch is useful if we plan to have a development track on it, but it seems in this case it's just to create a build at a known point ?

And when we release a version then we would create a branch and update it as needed...

**Comment by akosyakov** [comment]
Done by https://github.com/theia-ide/theia/pull/336
