### ISSUE TITLE
[layout restoration][navigator] widget state restored, immediately reset

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#1781]
The file navigation widget only restores a maximum of 3 levels of directories, even if 3+ levels of directories are expanded before the reload:

![peek 2018-04-25 17-43 file tree](https://user-images.githubusercontent.com/37082801/39285651-b5956648-48e7-11e8-86de-2850fe89ee6c.gif)

Expected: the file navigator should restore 100% of its original state.

**Comment by marcdumais-work** [comment]
Like mentioned by @akosyakov on gitter, it seems that the navigator's expanded state is not restored at all, for me. 

However, as mentioned by @mmorhun on gitter, it can seem to be restored when an editor is open/selected, and, when restored, in turn "reveals" that file in the navigator. 

![peek 2018-04-26 07-04](https://user-images.githubusercontent.com/25749063/39302302-2f962468-4920-11e8-9214-95b6bce15268.gif)

**Comment by elaihau** [comment]
It is caused by the file tree being rendered twice on Theia starts.

The tree is rendered for 1st round by the layout restorer. At this point, the tree is 100% identical with the what it used to look like - all "expanded" states are restored.

After that, the tree is rendered for the 2nd time in `FileNavigatorWidget.initialize()`, where the root is reset to `workspaceService.root` that only has information regarding the root and its 1st-level children.

**Comment by kittaakos** [comment]
> Expected: the file navigator should restore 100% of its original state.

See: https://github.com/theia-ide/theia/issues/1316

**Comment by kittaakos** [comment]
> file navigation widget only restores a maximum of 3 levels of directories

It does not restore a single for me. See:
![restore-tree](https://user-images.githubusercontent.com/1405703/41144262-a28e0fc8-6afc-11e8-8f5d-2f7e1242df70.gif)


```
git rev-parse --short HEAD
33548c4b
```

**Comment by elaihau** [comment]
I tested in my local environment (ubuntu linux + chrome), and found this no longer happens on the latest master branch.

@kittaakos @marcdumais-work could you please confirm?

**Comment by kittaakos** [comment]
Partially, but the current state is better than it was. 👍
Unfortunately, neither the selection nor the scroll state is stored/restored.  (OS X + Chrome + 80f402c6)

**Comment by elaihau** [comment]
>neither the selection nor the scroll state is stored/restored. (OS X + Chrome + 80f402c)

Thank you Akos for pointing it out. I will see what I can do to fix the rest of the problem :)
