### ISSUE TITLE
`Unhandled promise rejections` in git tests seems to break OSx build

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1784]
It is not reproducible with `npx run test @theia/git`, but with `yarn test:theia` i get the following error:
```
(node:16921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c run test \"@theia/!(example-)*\" --parallel
Directory: /Users/kosyakov/oomph/theia-master/git/theia
Output:
".
```

See https://travis-ci.org/theia-ide/theia/jobs/371392558

**Comment by kittaakos** [comment]
I am not sure if that is the reason, but currently, we have an incorrect path in the main `tsconfig.json` for the Git extension. I have [fixed that with the Mini Browser PR](https://github.com/theia-ide/theia/pull/1752/files#diff-e5e546dd2eb0351f813d63d1b39dbc48R65). I will verify it.

**Comment by akosyakov** [comment]
It is not related to git. I can reproduce it with `npx run test @theia/task`.

**Comment by kittaakos** [comment]
OK, the issue title was misleading. Thanks for the correction!
