### ISSUE TITLE
Document npm4 requirement in the dev doc

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#179]
Actual: both backend and frontend have errors.
Expected: it works.

**Comment by hexa00** [comment]
I just ran:
```
git clone https://github.com/theia-ide/theia \
&& cd theia \
&& npm install \
&& cd config/local-dependency-manager \
&& npm install \
&& cd ../../examples/browser \
&& npm run bootstrap \
&& npm run start
```
And it worked ... could provide more info ? error log etc?

**Comment by kittaakos** [comment]
See attached [log](https://github.com/theia-ide/theia/files/1063217/GH-179_Theia.log.txt).

**Comment by kittaakos** [comment]
As I see; `npm i` is being executed five times. Is that correct or I am simply blind?

**Comment by akosyakov** [comment]
Looks OK:
1. first to download dependencies for theia
2. second for ldm
3. install ldm on the path of the browser example
4. install theia-core as a local dependency for the browser example
5. install non local dependencies for the browser example

**Comment by akosyakov** [comment]
which npm version do you use? build does not seem to be executed for you after install

**Comment by kittaakos** [comment]
I have tried with both `v6.10.3` and `v8.0.0`.

**Comment by kittaakos** [comment]
And I do __not__ have `tsc` in the global node modules. If that helps anything at all.

**Comment by akosyakov** [comment]
scripts are written to work with npm@4.x.x, npm@5.x.x has breaking changes, maybes also regarding scripts

**Comment by akosyakov** [comment]
Could you try with npm4?

**Comment by kittaakos** [comment]
> scripts are written to work with npm@4.x.x

Really? On travis, we have a build with Node6 (and npm3) that passes. So I think it is not true.

**Comment by akosyakov** [comment]
I've changed travis scripts to use npm4

**Comment by kittaakos** [comment]
Are you sure? https://travis-ci.org/theia-ide/theia/jobs/241057581#L283

**Comment by akosyakov** [comment]
yes: https://travis-ci.org/theia-ide/theia/jobs/241057581#L286

**Comment by kittaakos** [comment]
I see. That makes sense.

**Comment by kittaakos** [comment]
Why do we have a node6 build then? I just would like to understand its benefit.

**Comment by akosyakov** [comment]
i don't know, i am talking only about npm versions

**Comment by akosyakov** [comment]
i think once we discussed it and node 8 is not considered to be stable and it is recommended to use node 6.

**Comment by kittaakos** [comment]
But node6 comes with npm3, right?

**Comment by kittaakos** [comment]
Build worked fine with node7 and npm4. I am fine with locking ourselves to node7 and npm4 this point but then please clearly state it in the documentation.

**Comment by kittaakos** [comment]
One more thing on this thread; as I see node7 does not have a long term maintenance support.
See: https://github.com/nodejs/LTS#lts-schedule1

**Comment by akosyakov** [comment]
I am not sure why you need node7, my local set up is node v6.10.3 and npm v4.6.1

**Comment by akosyakov** [comment]
```
nvm install 6
npm install -g npm@4
```

**Comment by kittaakos** [comment]
I clearly do not want to install npm4 into the global.

**Comment by hexa00** [comment]
Could we close this once it's documented in developing.md ?

**Comment by hexa00** [comment]
I'll change the title to reflect that

**Comment by kittaakos** [comment]
Good point, but I would still consider npm4 as the main problem.

**Comment by hexa00** [comment]
You mean we should adapt the scripts or change npm version ?

**Comment by epatpol** [comment]
I added a section on that in Developing.md, but I'll try investigating and see why it doesn't work with node8/npm5.

**Comment by akosyakov** [comment]
It is not relevant anymore since we use yarn
