### ISSUE TITLE
Git list should be navigable

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#1791]
For consistency reasons the list of file changes in the git extension should behave the same way as the list in git diff view behaves. 

- [ ] Keyboard navigation

- [ ] Open diff view without loosing focus on git list

It would be more convenient to review the changes before staging them. 
Additionally it would be fine to stage/unstage by a keyboard shortcut (space).

**Comment by AlexTugarev** [comment]
@jbicker, to continue 
https://github.com/theia-ide/theia/pull/2630#issuecomment-414634578, I think we should align the selection behavior in git widget and SiW widget, where the results are revealed but the widget remains focused.

**Comment by jbicker** [comment]
Yes. I agree. As it is in git diff view as well.
