### ISSUE TITLE
[editor] Color pickers in css files would be awesome

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#1794]
![css_colorpicker](https://user-images.githubusercontent.com/28291421/39317959-23673026-497d-11e8-8060-466da0f801c3.gif)

**Comment by vince-fugnitto** [comment]
Currently implemented in Theia 😄 

<div align='center'>

<img width="556" alt="Screen Shot 2019-05-02 at 10 29 02 AM" src="https://user-images.githubusercontent.com/40359487/57082660-2ebce800-6cc5-11e9-99e6-cab28c39e16d.png">


</div>
