### ISSUE TITLE
[mini-browser] errors logged to js console when files are opened

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1796]
try to open any different files from file navigator, and see there are errors logged, e.g.

```
GET http://localhost:3000/mini-browser-check/Users/tugarev/Projects/lsp4j/releng/pom.xml 501 (Not Implemented)
```

I think we should catch those errors from `fetch` in `MiniBrowserOpenHandler`

<img width="1070" alt="screen shot 2018-04-27 at 08 53 31" src="https://user-images.githubusercontent.com/914497/39348740-af96575e-49f8-11e8-80dc-123984a18d95.png">

**Comment by kittaakos** [comment]
I am closing it as invalid. The `canHandle` logic has completely changed and we prefetch all the supported file types on `init` via JSON-RPC. Please reopen if the issue still occurs.
