### ISSUE TITLE
[navigator] When a folder contains only a folder, expand both automatically

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1800]
This would greatly improve the experience for Java projects, for example.

Ideally we would have a different representation of Java packages, but for that we might need a separate widget (e.g. "Package Explorer").

**Comment by pfgallagher** [comment]
@spoenemann — perhaps this feature should be toggleable? I understand why it's nice for Java projects, but I personally find it quite irksome. Thank you!

**Comment by costeaalex** [comment]
This would be useful for PHP projects as well and yes, it would be good to be toggle actioned.
