### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by reggi** [theia-ide/theia#1813]
Any recommendations on how to password protect the editor?

**Comment by AlexTugarev** [comment]
@reggi can you explain what is meant by protection in this case?
Do you want to restrict access to the application as whole?

**Comment by reggi** [comment]
Yes. The general thought is what is the recommended way to put theia on a
server and password protect the GUI so that o ly people with access can
visit.

**Comment by gorkem** [comment]
duplicate of #411
