### ISSUE TITLE
NullPointException ocurred when open a java file!

### ISSUE THREAD

**Issue by DustFinger001** [theia-ide/theia#1814]
cant load java language server,  some exception ocurred like this:
![image](https://user-images.githubusercontent.com/16345979/39393006-8184abc2-4af2-11e8-9e2b-378a7c820a7b.png)

**Comment by AlexTugarev** [comment]
@DustFinger001  do you have a reproducible example? I think think it happens when a maven project is imported. Maybe a clone url to reproduce. Could be, that this is an issue for JDT LS.

**Comment by DustFinger001** [comment]
@AlexTugarev  yes， It happens in maven project .  my example is in local environment , But i can reproduce this error.

**Comment by gorkem** [comment]
@fbricon any ideas what makes m2e upset?

**Comment by AlexTugarev** [comment]
@DustFinger001 could you please provide a reproducible example? 

@gorkem, I think this should be filed for jdt.ls including an example. Or do you see something theia specific here?

**Comment by fbricon** [comment]
seems like the pom.xml has no artifactId. @DustFinger001 it'd help if you could paste your pom.xml here (after anonymizing the content)

**Comment by DustFinger001** [comment]
@fbricon @AlexTugarev i can not reproduce this exception in my environment right now , the pom.xml could be fixed by my workmate.

**Comment by AlexTugarev** [comment]
@DustFinger001 please open new issue for [jdt.ls](https://github.com/eclipse/eclipse.jdt.ls), if this happens again.
