### ISSUE TITLE
Speeding up the build

### ISSUE THREAD

**Issue by dvc94ch** [theia-ide/theia#1827]
Why does it recompile all extensions every time and not only the changed ones + the ones that depend on that one?

I can use yarn watch, but that can make my laptop unresponsive (only 8GB RAM)

**Comment by kittaakos** [comment]
@dvc94ch, you could try this: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#watch-a-specific-package-and-its-local-upstream-dependencies

**Comment by dvc94ch** [comment]
Thanks
