### ISSUE TITLE
Navigator doesn't show new file added initially, doesn't automatically refresh after creating new files either

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1830]
2 Errors: 
     - Workspace folder do not show it's name
     - Files do not show in the navigator view

How to reproduce
1- Make sure there is no "localhost:3000" active (No pre-existing client running on that address:port )
2- Create a new workspace : mkdir ../workspace1
3- Start theia browser application
  -> cd examples/browser; yarn start ../../../workspace1
4- Initiate the web browser: localhost:3000
5- Select left sidebar "Files"
  -> wll show an empty folder (note the workspace folder name does not show) (ERROR 1)
6- In the navigator view, create a new file (Either from the "File" in the menubar or from the context menu
  -> The file gets created in the editor, but doen't show in the navigator (ERROR 2)
7- modify the empty file with anything
  -> the file data is updated even if we don't see the file in the navigator (If autosave is on)
8- In the navigator view, select the folder arrow to close and re-open
  -> Now we can see the file in the navigator view
9 Create a new file and the new file doesn't show in the navigator view until you close + re-open the folder

To solve the issue
10- Select in the menubar "File" -> "Open..." 
--> you will see the current workspace folder
11- Just select "Open" in the dialog 
  --> note now the navigator view will display the workspace folder on the first line in another web browser page
  --> We are showing the same folder as before but now the workspace folder shows
12- Create a new file in the navigator and it shows up right away
Note: The small video start at step 4 to show what happens:

![peek 2018-05-01 navigatornotrefresh](https://user-images.githubusercontent.com/419051/39478522-af587a5c-4d30-11e8-8061-8ec2f34041ab.gif)

**Comment by marcdumais-work** [comment]
@lmcbout I am not able to reproduce this - number 5 and 6 work for me. Did you increase your inotify limit? If you run out, it might look like what you're reporting.

**Comment by lmcbout** [comment]
My Inotify is set to 500K,

**Comment by svenefftinge** [comment]
Since this seem to happen on a regular basis, we maybe should tell the user.

**Comment by marcdumais-work** [comment]
@svenefftinge do you have a way in mind to "tell the user"? Through documentation? Notification from Theia at runtime? Inotify is linux-specific. Do you know if there is a corresponding host resource, for Mac/Windows computers, that might also need to be increased from default value? 

In this specific issue, it turns-out that insufficient inotify was not the cause. Rather I suspect @lmcbout found a case where the workspace somehow ends-up being not correctly set, maybe not having filesystem watching active.  More digging is required.

**Comment by lmcbout** [comment]
@marcdumais-work I modified the "How to repoduce" to say : 
  Make sure there is no "localhost:3000" active (No pre-existing client running on that address:port )

**Comment by lmcbout** [comment]
Another observation: When I see in the navigator view the workspace name is not showing, adding a new file and modifying it, the data is saved. (Auto-saved is on) Then, if I edit and save  the file outside Theia, (Using "vi <filename> "from a terminal while the file is still in the Theia editor, the file watcher kicks in and the file is updated  accordingly. So it doesn't seems  the file-watcher be the issue here! It seems more to be in the area of the navigator.

**Comment by kittaakos** [comment]
@lmcbout, please reference the task from the description of the PR and not from its title, if possible.

Also, you either have to close your task manually after merging your PR, or you can use some magic keywords and GH will do it for you. You can read about this feature here: https://help.github.com/articles/closing-issues-using-keywords/

Let me know if you have questions.

**Comment by lmcbout** [comment]
Thanks @kittaakos for the link about automatically close the issue
