### ISSUE TITLE
[electron] The server worker sometimes shutdown for no reason

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#1831]
When running theia in electron, doing things such as opening / closing a workspace seem to cause the server worker to unexpectedly shutdown.

My idea is that this would be caused by the BrowserWindow reload.

**Comment by vince-fugnitto** [comment]
Similar to #1341, Electron no longer throws errors or crashes unexpectedly when refreshing, reloading, closing a workspace, or opening a workspace.
