### ISSUE TITLE
Mini browser breaks ResourceProvider

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1832]
The mini browser's `canHandle` throws for non-file URI.

It breaks java's `jdt:`-URLs, i.e. opening non-source classes.

**Comment by gorkem** [comment]
Noticed too. Was trying to figure out the reason.

**Comment by azatsarynnyy** [comment]
There's the same issue when I'm trying to open an extension's readme by clicking on an item in the Extensions view
![screenshot from 2018-05-04 12-44-41](https://user-images.githubusercontent.com/1636395/39621907-10fb47b6-4f99-11e8-95c3-60f806e8e512.png)

**Comment by AlexTugarev** [comment]
FYI there is also #1796. I think we need to catch errors from `fetch` instead of just reading status code.

**Comment by akosyakov** [comment]
Was not it fixed by https://github.com/theia-ide/theia/pull/1833?

**Comment by marechal-p** [comment]
Can you tell me if this issue still happens since [this commit](https://github.com/theia-ide/theia/commit/8ab83bde790651b679dc212965b9eba871754214) is merged ?

**Comment by svenefftinge** [comment]
So it can be closed again?
