### ISSUE TITLE
Navigation from problems view 

### ISSUE THREAD

**Issue by gorkem** [theia-ide/theia#1835]
The items on the problems view are not clickable. Clicking on an entry should open the file on the problem location in an editor.

**Comment by kittaakos** [comment]
It works for JS/TS:

![gh-1835-js](https://user-images.githubusercontent.com/1405703/39509244-d27ad272-4de5-11e8-92da-7c4366ecdc3d.gif)

@gorkem, did you try Java files/markers?

The opening logic for the markers happens here: https://github.com/theia-ide/theia/blob/f98eb08fadfca8bb1377a493583f34b940516b6d/packages/markers/src/browser/marker-tree-model.ts#L17

**Comment by lmcbout** [comment]
Tested with git commit  (b9941f63df57fb2876b8d74dfe4f47fcfc674048) July 3, 2018
Double-click on an isssue reported in the problem view for a JAVA project and
it opens the file and highlighted the issue at the proper line
Can we close this  issue ?

**Comment by kittaakos** [comment]
Thanks for verifying, @lmcbout!

Please reopen if it still happens.
