### ISSUE TITLE
Launch/Run/Debug configurations

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#184]
As an IDE user
- I want to be able to launch the program that I am developing, with a certain launch configuration, that determines what the launch does
- I want to be able to create multiple launch configurations
- I want the launch errors  to be shown in the Problems View

As an extension developer
- I want to be able to create a run contribution, so that I can extend Theia to support other runtime environments (containers?)

**Comment by svenefftinge** [comment]
I would like to have a keybinding for `running most recently executed launch config`.

**Comment by akosyakov** [comment]
@marcdumais-work is it still relevant?
