### ISSUE TITLE
error: The ws channel does not exist

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1842]
Seems to loose connection between frontend and backend

How to reproduce
1- start backend
2- Start the Frontend
3- From frontend, open a second workspace
  -> a second tab open with the new workspace
4- Close the first workspace
  --> Look at the backend, the will be the following error:
[2018-05-03T13:19:33.713Z] ERROR: Theia/23102 on elxa36mbq32: The ws channel does not exist [ 0 ]

**Comment by marcdumais-work** [comment]
I simplified the title of this issue
