### ISSUE TITLE
Can not open Git Diff item

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#1843]
1. Open Git History
2. Expand changed files list of any commit
3. Try to open any diff item.
![screenshot from 2018-05-03 16-42-59](https://user-images.githubusercontent.com/7668752/39580374-b58cd5f4-4ef1-11e8-9df9-7b04dc86df87.png)

**Comment by marechal-p** [comment]
@vinokurig are you able to tell if the PR fixes this issue ?

**Comment by vinokurig** [comment]
@marechal-p I've cheeked, your PR fixes the issue!
