### ISSUE TITLE
[terminal] turn cursor blinking off

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1847]
The cursor blinking is very irritating as it is not constant depending on the connection. We should simply turn it off (it is turned off in vs code, too)

**Comment by mofux** [comment]
FWIW Cursor blinking should not be affected by the connection speed as it's only rendered by the client without any impulse from the connection itself

**Comment by AlexTugarev** [comment]
Can it be, that we stopped & continued after hitting a breakpoint when we see this issue?

It looks like the blink animation heavily rely on time diffs.
