### ISSUE TITLE
Is electron package needed for running browser IDE ?

### ISSUE THREAD

**Issue by imdurgadas** [theia-ide/theia#1853]
I was going through the theia documentation and it says that there are 2 modes to run theia IDE i.e via browser and via electron.
But in the packages/core/  , I see that electron is present which resembles like it's a core module.

Do we really need electron to run the browser ?

**Comment by marechal-p** [comment]
We don't necessarly need electron to run the browser.
Despite `@theia/core/src/electron-browser`, that Theia's sources.

Once you generate an application with `@theia/application-manager` by using `yarn` in `theia-folder/examples/browser`, only the browser specific source files should be used.

Just take a look at the following `require` statements, in the generated sources:

- `/examples/browser/src-gen/frontend/index.js`
```js
// [...]

module.exports = Promise.resolve()
    .then(function () { return Promise.resolve(require('@theia/core/lib/browser/menu/browser-menu-module')).then(load) })
    .then(function () { return Promise.resolve(require('@theia/core/lib/browser/window/browser-window-module')).then(load) })
    .then(function () { return Promise.resolve(require('@theia/output/lib/browser/output-frontend-module')).then(load) })
    // [...]
```

- `examples/electron/src-gen/frontend/index.js`
```js
// [...]

module.exports = Promise.resolve()
    .then(function () { return Promise.resolve(require('@theia/core/lib/electron-browser/menu/electron-menu-module')).then(load) })
    .then(function () { return Promise.resolve(require('@theia/core/lib/electron-browser/window/electron-window-module')).then(load) })
    .then(function () { return Promise.resolve(require('@theia/output/lib/browser/output-frontend-module')).then(load) })
    // [...]
```

**Comment by marechal-p** [comment]
Closing, unless you have any other questions / concerns.

**Comment by imdurgadas** [comment]
@marechal-p Thanks for your quick response. However, I have a following question. 
As you mentioned in the above reply, I executed `yarn` command in examples-browser and that failed with the following error:
```
Error: Failed to find Electron v1.8.2-beta.5 for linux-s390x at https://github.com/electron/electron/releases/download/v1.8.2-beta.5/electron-v1.8.2-beta.5-linux-s390x.zip
```

However, after the failure - if we issue `yarn run build` , the browser loads ? 

Is the above behaviour correct ?
