### ISSUE TITLE
Question: Is there a reason why Theia's npm package packs its `.ts` source files ?

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#1854]
Other packages I know of only provide `.js` and `.d.js` files. Is there a reason why we pack the `.ts` files with it on npm ?

**Comment by AlexTugarev** [comment]
source maps are also included, which allows us to see the typescript sources while debugging.

**Comment by akosyakov** [comment]
With next typescript extension developers also will be able to navigate to sources.

@marechal-p is there an issue with it?

**Comment by marechal-p** [comment]
I was just comparing at how we use other npm packages, like `vscode-languageserver-protocol` or `vscode-ripgrep` that only packs their `.js` and `.d.ts` files. I was wondering why we were packing the `.ts` files too, and if we were building the `.js` from it when it was a npm dependency ? Or if we just packed the pre-built `.js` files and `.d.ts` typings ?

**Comment by marechal-p** [comment]
Closing because the answer is `to see the TypeScript sources while debugging`.
