### ISSUE TITLE
[Question] Is electron mandatory package for browser ?

### ISSUE THREAD

**Issue by imdurgadas** [theia-ide/theia#1862]
As part of #1853 , it was mentioned that electron is not needed for browser dependency.

As mentioned in the comments in #1853, we executed `yarn` command in examples-browser and that failed with the following error:
```
Error: Failed to find Electron v1.8.2-beta.5 for linux-s390x at https://github.com/electron/electron/releases/download/v1.8.2-beta.5/electron-v1.8.2-beta.5-linux-s390x.zip
```
However, after the failure - if we issue `yarn run build` , the browser loads ?

Is the above behaviour correct ?

**Comment by marechal-p** [comment]
I am unable to reproduce your error, could you send the steps you used to arrive there ?
From the point where you fetch Theia ?

**Comment by marechal-p** [comment]
_(is [this](https://github.com/theia-ide/theia/issues/1699) related ?)_

**Comment by imdurgadas** [comment]
Not really. I am trying this on **linux s390x** platform.

Steps:
1.  Install NodeJS
2.  Install yarn :  `npm install -g yarn@1.6.0`
3.  Clone v0.3.8 theia  `git clone https://github.com/theia-ide/theia.git -b v0.3.8`
4.  `yarn`

Step 4 fails with : 
```
Error: Failed to find Electron v1.8.2-beta.5 for linux-s390x at https://github.com/electron/electron/releases/download/v1.8.2-beta.5/electron-v1.8.2-beta.5-linux-s390x.zip
```

**Comment by kittaakos** [comment]
https://github.com/electron/electron/issues/12789

**Comment by kittaakos** [comment]
> linux-s390x

It is a not supported HW platform. See: https://github.com/electron/electron/issues/12789#issuecomment-417927283
