### ISSUE TITLE
[monaco] Refactor keybinding is broken on Windows/Linux

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1866]
Trying to write a capital R in Theia (shift+r) in an editor does not work.  Instead, it invokes a command bound by the monaco editor:

    {command: "monaco.editor.action.refactor", keybinding: "shift+r", context: "editorTextFocus"}

**Comment by marechal-p** [comment]
In this case it comes from the bindings fetched from monaco and imported into Theia's keybindings.

But it raises the following question: What to do about keybindings that match `/shitf\+\w/` ?

Do we only avoid these if they are set in the `editorTextFocus` ?

**Comment by AlexTugarev** [comment]
@simark can you prove more information on your browser, please?

I just tested it on macOS with Chrome, and do not see this issue. 
Refactor command is bound to <kbd>shift</kbd> + <kbd>command</kbd> + <kbd>r</kbd>

<img width="621" alt="screen shot 2018-05-08 at 15 34 36" src="https://user-images.githubusercontent.com/914497/39760489-b6cffbde-52d5-11e8-805c-5ad5558671f1.png">

**Comment by simark** [comment]
Chrome on Linux.  "command" does not exist in the non-Mac world so it probably just gets ignored and it boils down to "shift+r".

**Comment by AlexTugarev** [comment]
could you try [`KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_R`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/codeAction/codeActionCommands.ts#L256) as keybinding of `My Action!!!` in [monaco playground](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance)?

Is this also broken on linux+chrome?

**Comment by simark** [comment]
> could you try KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_R as keybinding of My Action!!! in monaco playground?

- On Linux+Chrome: it works (displays the popup)
- On Linux+Firefox: you see the popup for a fraction of a second, but it refreshes right after (ctrl+shift+r is a shortcut for refreshing, ignoring cache content)

Note that in the `registerKeybinding` function, the shortcut gets registered as `"shift+r"`, so the problem must be before that.

**Comment by AlexTugarev** [comment]
I created https://github.com/Microsoft/monaco-editor/issues/865. 

Let's hope it will make it into 0.13.x of standalone monaco.

**Comment by simark** [comment]
Thanks.

The linked fix looks promising: https://github.com/Microsoft/vscode/commit/2a37e213cb054657b44d9e98ea1742a32f98184a

How hard/easy would it be for me to build Theia with the master branch of the monaco editor, see if this fixes the issue?  Or maybe build an older version of monaco (the one we use currently), but with this fix backported?

**Comment by AlexTugarev** [comment]
We depend on [monaco-editor-core](https://www.npmjs.com/package/monaco-editor-core) via [monaco-languageclient](https://www.npmjs.com/package/monaco-languageclient). It's quite a chain, and I'm not aware of nightly builds of monaco. You can try to [build it locally](https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#1-ship-a-new-monaco-editor-core-npm-module).

**Comment by marechal-p** [comment]
The command from monaco is like so:
![gh1866-keybinding-object](https://user-images.githubusercontent.com/14182238/39772078-30f5bbec-52c2-11e8-8651-d94005121192.png)

But it ends up as `shift+r` in Theia, this seems to come from `monaco-keybinding.ts`, the `metaKey` might not get correctly converted under non-OSX systems.

**Comment by marechal-p** [comment]
[This](https://github.com/marechal-p/theia/commit/14a16736b104259fb53772987b30211206663ae3) commit seems to fix the issue, but it feels too simple, does it fail on some corner cases ?

**Comment by simark** [comment]
After a few tries I couldn't get `monaco-languageclient` to build using a locally built `monaco-editor-core` (which is built from the vscode repo, IIUC).  If can do it, it would perhaps be good to put the procedure in the `monaco-languageclient` README.  It would also be good to make sure the instructions in this README are still up to date.

**Comment by AlexTugarev** [comment]
@marechal-p, that might work as a temporary workaround for that particular issue. But, I'm not sure about the impact on other parts.

I asked, if the fix of https://github.com/Microsoft/vscode/issues/49225 will make it into next monaco release.

OTOH, I'd prefer to add a temporary workaround to the `editor.action.refactor` monaco keybinding here: 

https://github.com/theia-ide/theia/blob/master/packages/monaco/src/browser/monaco-keybinding.ts#L37-L42

**Comment by AlexTugarev** [comment]
>  it would perhaps be good to put the procedure in the monaco-languageclient README. It would also be good to make sure the instructions in this README are still up to date.

@simark, please create an issue for monaco-languageclient, if you find something out of date in the readme file. 

As mentioned before, it depends on the monaco-editor-core package, it does not build it. I think, we can be really happy, that the standalone monaco-editor is supported at all.

**Comment by simark** [comment]
> @marechal-p, that might work as a temporary workaround for that particular issue. But, I'm not sure about the impact on other parts.
> 
> I asked, if the fix of Microsoft/vscode#49225 will make it into next monaco release.

I agree with Alex, this seems like the right fix.  A binding with the Mac ctrl key (called `WinCtrl` in Monaco and `MacCtrl` in Theia) should never be used when running a Windows/Linux client, as that key doesn't exist.

**Comment by marechal-p** [comment]
Does that means that when we import bindings from anywhere and that some `MacCmd` button is specified, we just drop the binding for non-OSX platforms and we don't even try to convert it ?

**Comment by simark** [comment]
> Does that means that when we import bindings from anywhere and that some MacCmd button is specified, we just drop the binding for non-OSX platforms and we don't even try to convert it ?

You mean `MacCtrl` I guess?

If we're on Linux/Windows and there's an attempt to register a binding that contains `MacCtrl`, I think it would be better/safer to ignore the binding completely and show a warning than to register the binding without that key.  Otherwise it leads to the situation in this issue.

**Comment by simark** [comment]
> Does that means that when we import bindings from anywhere and that some MacCmd button is specified, we just drop the binding for non-OSX platforms and we don't even try to convert it ?

That's what I think we should do, but maybe it's not the right or best option.

**Comment by simark** [comment]
I am seeing this again today on 1ea897b5d56858d6a20be85f8cc5a63461c2bc85.
