### ISSUE TITLE
Use che-ls-jdt in @theia/java

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#1869]
We (folks at Red Hat) have implemented a bunch of extensions (like adding library dependencies nodes to project explorer). We would like to implement these extension for Theia, as well. 
As discussed on the gitter channel, a first step would be to consume our extended version of jdt.ls living here: https://github.com/eclipse/che-ls-jdt/ instead of vanilla jdt.ls

**Comment by tsmaeder** [comment]
I am working on a PR that would consume che-ls-jdt from a mvn repo. Local development requires mvn, though.

**Comment by AlexTugarev** [comment]
@tsmaeder, please check the recent change to download jdt.ls on postinstall. the script is moved, you might need to rebase, if already started working on that.

**Comment by tsmaeder** [comment]
PR: https://github.com/theia-ide/theia/pull/2069

**Comment by AlexTugarev** [comment]
#2069 is merged. Thanks!
