### ISSUE TITLE
Theia Electron application menu fails on macOS

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#1875]
Theia Electron context menu fails on macOS. There should for instance be a View menu with entries such as Call hierarchy, Extensions, Files, Git, Git History, Outline, Output, ... But non of them are visible when run on macOS. Please see macOS screenshot.

Ran following command on macOS High Sierra 10.13.4 with node v8.11.1, npm 6.0.0, yarn 1.6.0:

```
git clone https://github.com/theia-ide/theia.git
cd theia
yarn
cd examples/electron
yarn run start
```

<img width="1440" alt="bildschirmfoto 2018-05-09 um 17 38 19" src="https://user-images.githubusercontent.com/38067850/39824568-f99f5c18-53af-11e8-9536-3b912e0a2fb8.png">

When trying to do the same on Ubuntu 16.04.4 LTS with node v8.11.1, npm 6.0.0, yarn 1.6.0 the script above fails when running yarn. So, yarn has to be run twice. But the end result works. The menu shows as expected. Please see Ubuntu screenshot.

```
git clone https://github.com/theia-ide/theia.git
cd theia
yarn
yarn
cd examples/electron
yarn run start
```

![bildschirmfoto vom 2018-05-09 17-45-49](https://user-images.githubusercontent.com/38067850/39825018-10b5a294-53b1-11e8-895a-ff90623cedf2.png)

**Comment by AlexTugarev** [comment]
I verified this; it's broken since updating to v1.8.x of electron. maybe there are some api changes, and we need to catch up.

BTW in the meantime electron v2 was released.

**Comment by kittaakos** [comment]
Quick question as I am doing the review of the [corresponding PR](https://github.com/theia-ide/theia/pull/2079); it is not the context menu but the application menu, right?

**Comment by jeanlucburot** [comment]
My understanding is:
- context menu: the right-click within the window somewhere, not outside of it.
- application menu: outside of the window, usually the top of the window frame. In the case of macOS the menu at the top of the screen. Same applies to Ubuntu with the Unity Desktop. Under Windows 10 this is a bit different; there it is the menu to the top of the window frame.

**Comment by kittaakos** [comment]
Closed via https://github.com/theia-ide/theia/pull/2469.
