### ISSUE TITLE
[monaco] New keybinding collision because of the context

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#1888]
Monaco seems to have added new keybindings that we load in Theia, but they use different contexts to avoid collisions, while we do not: our default context for any monaco's binding is `editorTextFocus`.

```log
[2018-05-11T12:58:34.238Z]  WARN: Theia/9773 on elxa8wlvvz1: (logger=root)
    Collided keybinding is ignored;  [ '{"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}',
      ' collided with ',
      '{"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}' ]

[2018-05-11T12:58:34.240Z]  WARN: Theia/9773 on elxa8wlvvz1: (logger=root)
    Collided keybinding is ignored;  [ '{"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}',
      ' collided with ',
      '{"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}' ]
```

Monaco's context for each (`command / keybinding / context`):
- `monaco.editor.action.diffReview.next / f7 / isInDiffEditor`
- `monaco.editor.action.wordHighlight.next / f7 / editorTextFocus && hasWordHighlights`
- `monaco.editor.action.diffReview.prev / shift+f7 / isInDiffEditor`
- `monaco.editor.action.wordHighlight.prev / shift+f7 / editorTextFocus && hasWordHighlights`

**Comment by MarkZ3** [comment]
Please note that for Electron, you have to use a different command now to see the logging, see https://github.com/theia-ide/theia/issues/2344

**Comment by marechal-p** [comment]
@vince-fugnitto cc
