### ISSUE TITLE
Arrow keys don't work in Terminal

### ISSUE THREAD

**Issue by filips123** [theia-ide/theia#1896]
Arrow keys don't work in Terminal. When I press these keys, it printed `^[[A`, `^[[B`, `^[[C` or `^[[D`, but it should handle them like in real Terminal.
Also, add support for Ctrl+C and Ctrl+V.

See https://asciinema.org/a/XufeQLTnx8OUJ9EzUxGsd2Twp for Asciinema Recording.

**Comment by filips123** [comment]
I test this with Firefox 60.0, Chrome 66.0 and Edge on Windows 10.
Theia is running on [Codenvy](http://codenvy.io/) **Debian 8.9** stack with **Node.js v8.11.1**, **NPM 5.6.0** and **Yarn 1.5.1** with [Ngrok](https://ngrok.com/) HTTP tunneling of port 3000.

**Comment by filips123** [comment]
Also, keys like `~`, `ˇ`, `^` and `°` (Alt Gr + 1, 2, 3...) don't work.

**Comment by svenefftinge** [comment]
I don't think it's an issue in Theia as it works with all deployments I use. It would be interesting to learn where the encoding gets broken, though. Has anyone else seen this?

**Comment by filips123** [comment]
I tested this few more times, and sometimes it works and sometimes not.

**Comment by marcdumais-work** [comment]
@filips123 We had a user ping us today on gitter, with a similar issue as you described here, also with a ```debian```-based image. Troubleshooting a bit, s/he noticed that ```sh``` was used as terminal, instead of the usual ```bash```. This can be because, in the image being used, environment variable ```$SHELL``` points to ```/bin/sh```. Can you check if perhaps it's the same in your case? 

If so, you can override Theia using ```sh```, as long as you have ```bash``` installed, by defining environment variable ```$THEIA_SHELL``` and pointing it to your locally installed ```bash```, and making sure that this variable is set before / at Theia startup.

**Comment by filips123** [comment]
I can't see  `$SHELL` variable with `printenv` and Theia run terminal in `sh` and arrow keys don't work.
But if I run `export  THEIA_SHELL="/bin/bash"` and then run Theia, Theia will run terminal in `bash` and arrow keys will work.

Maybe Theia could detect if `bash` is installed and then use it instead of variable `$SHELL`.

Keys like `~`, `ˇ`, `^` and `°` (Alt Gr + 1, 2, 3...) don't work even in `bash`. See https://asciinema.org/a/unRyKt5Em5N6ozQI32YCh0omO.

Also, add support for copying with `Ctrl+C`, cutting with `Ctrl+X` and pasting with `Ctrl+P`.

**Comment by marcdumais-work** [comment]
> I can't see $SHELL variable with printenv

So it looks like $SHELL is not set, in your image? Just to confirm, can you try this in a terminal: 
``` bash
echo $SHELL
```

> Keys like ~, ˇ, ^ and ° (Alt Gr + 1, 2, 3...) don't work even in bash

What kind of keyboard do you use? I do not need to use the ```alt``` key to type  ```~``` or  ```^```. The other characters, I think, are not standard on an American English keyboard?  Could the issue be one of locale or such, that would need to be set in the container, to correctly support your keyboard? 

>  add support for copying with Ctrl+C, cutting with Ctrl+X and pasting with Ctrl+P

These, I can confirm, do not work for me either. Normally in a terminal, ````Ctrl-C``` is used to kill the current command. Did you mean ```Shift-Ctrl-C``` / ```Shift-Ctrl-V```, as are used for native terminals on Ubuntu? No shortcut for cut, that I can see. Using Theia in Chrome, the former seems to open the developers tools, and the later works (if there is something to paste in the clipboard). So probably just a matter of the copy shortcut having a collision with the Chrome built-in shortcut.

**Comment by filips123** [comment]
> So it looks like $SHELL is not set, in your image? Just to confirm, can you try this in a terminal:
`echo $SHELL`

I am using Codenvy image with Debian `8.9` and Node `8.11`.
If I run `echo $SHELL` from Codenvy online terminal (`bash`), it printed `/bin/bash`, but if I run `printenv`, there is not `$SHELL` variable. Theia uses `sh` terminal.
If I run `export THEIA_SHELL='/bin/bash'` and then Theia, Theia will use `bash` terminal. `$THEIA_SHELL` variable will be in `printenv`.

> What kind of keyboard do you use? I do not need to use the `alt `key to type `~ `or `^`. The other characters, I think, are not standard on an American English keyboard? Could the issue be one of locale or such, that would need to be set in the container, to correctly support your keyboard?

I use QWERTZ Slovenian Keyboard. Characters like `~`, `ˇ`, `^`, `˘` and `°` are on `Alt Gr` + `1`, `2`, `3`, `4`...
![slovenian-keyboard](https://user-images.githubusercontent.com/16626308/40563581-917a5e36-6065-11e8-94f1-1db711a8bc3a.png)

> These, I can confirm, do not work for me either. Normally in a terminal, `Ctrl-C `is used to kill the current command. Did you mean `Shift-Ctrl-C` / `Shift-Ctrl-V`, as are used for native terminals on Ubuntu? Using Theia in Chrome, the former seems to open the developers tools, and the later works (if there is something to paste in the clipboard). So probably just a matter of the copy shortcut having a collision with the Chrome built-in shortcut.

When `Ctrl + C` is pressed, Theia Terminal might be able to detect if any text is selected and then copy it. If no text is selected, `Ctrl+C` should work like in classic Terminal. This is how `cmd `and `powershell `in Windows 10 work.

**Comment by marcdumais-work** [comment]
@filips123 Thanks for the info. It's good to have people trying Theia with different keyboards; AFAIK, my colleagues and myself all use standard American keyboards / layouts. 

> Keys like ~, ˇ, ^ and ° (Alt Gr + 1, 2, 3...) don't work even in bash

This looks like a bug. Can you open a separate issue for this? It could be useful to try this on another docker image and/or natively, to see if this problem might be specific to the debian image you're using. 

> Maybe Theia could detect if bash is installed and then use it instead of variable $SHELL.

I think that on ```Linux``` Theia should honor the ```$SHELL``` environment variable that is set. Some users might want to use ```sh``` or another shell, even if ```bash``` is available. If neither is set, it probably makes sense to chose ```sh```, as it is ubiquitous. 

> When Ctrl + C is pressed, Theia Terminal might be able to detect if any text is selected and then copy it. If no text is selected, Ctrl+C should work like in classic Terminal. This is how cmd and powershell in Windows 10 work.

It looks like VS Code have this: https://github.com/Microsoft/vscode/issues/8818

However I think it might be more pressing to have some working shortcuts, for ```copy``` and ```paste``` in the terminal, across supported browser.  Here is what I observe on my Linux laptop: 

```
copy: Ctrl-Shift-Insert: works on Chrome but not on Firefox
Shift-Insert: paste: works on Chrome and Firefox
```

```
Ctrl-Shift-C: copy: works on neither (Chrome: collision with built-in shortcut)
Ctrl-Shift-V: paste: works on Chrome
```

**Comment by filips123** [comment]
> This looks like a bug. Can you open a separate issue for this? It could be useful to try this on another docker image and/or natively, to see if this problem might be specific to the debian image you're using.

I created new issue: https://github.com/theia-ide/theia/issues/1989. I currently can't test in other docker images.

**Comment by svenefftinge** [comment]
Please reopen if this still happens.

**Comment by zerdos** [comment]
still happens.
