### ISSUE TITLE
Cannot type C, X or V

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#190]
Running Electron example on Linux. If I type C in the editor, it doesn't to anything. It actually does "copy" as if Ctrl was pressed. Similarly, X does cut and V does paste.

**Comment by MarkZ3** [comment]
Note: This bug is not present when running on macOS, it is only seen so far on Linux.

**Comment by kittaakos** [comment]
Closed via #223

**Comment by MarkZ3** [comment]
Thanks a lot!
