### ISSUE TITLE
Question: Theia license

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#1904]
Apologies if this has been covered elsewhere (a search returned no results), but we have a question about the license model of theia.

The source in this repository outlines that the license in use is Apache 2.0, however the [eclipse page](https://projects.eclipse.org/projects/ecd.theia) outlines it to be epl/gpl.

Please confirm the license this code is released under both now and any plans for the future as this will affect our ability to adopt and help support this product.

Thanks!

**Comment by svenefftinge** [comment]
It currently is Apache 2, but as the source code is moved to Eclipse we will relicense the code to EPL2.
So now it is Apache 2 only, in future it will be EPL2 only.

**Comment by thegecko** [comment]
If I read this right, EPL2 allows a secondary license to further affect usage and in this case GPL2 is outlined as being the secondary. This effectively makes the code GPL2 and makes usage of this project rather restrictive in a proprietary environment, please confirm this is the intention.

**Comment by svenefftinge** [comment]
The secondary license only applies when needed. I.e. you use it under GPL2 if you have to because run the code in a context that requires GPL compatibility. So it is 'or' rather than 'and'.

**Comment by svenefftinge** [comment]
Think of it as EPL2 with additional GPL compatibility.

**Comment by thegecko** [comment]
Perfect, thanks!

**Comment by marcdumais-work** [comment]
Closing for now. You may re-open if there are more license-related questions.
