### ISSUE TITLE
The hover is broken in Safari - The popup is empty

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#191]
The popup is empty when hovering over a symbol, a method, etc.
Works fine in Chrome and in FF.

**Comment by svenefftinge** [comment]
close as fixed (no longer reproducible)

**Comment by kittaakos** [comment]
There is still a glitch, but maybe it is related to the LS.

![screencast 2017-11-20 14-51-02](https://user-images.githubusercontent.com/1405703/33021754-3f70ae64-ce03-11e7-9fe3-ae8d97a1762b.gif)

**Comment by svenefftinge** [comment]
Yes, I think it is the LS. You could try to reproduce that in vscode.
