### ISSUE TITLE
[Question] Access Preferences on the backend application?

### ISSUE THREAD

**Issue by BoykoAlex** [theia-ide/theia#1910]
There are some settings/preferences in the language server extension: jvm heap max heap size and java home path. These are used to launch language server jar using a specific JVM with -Xmx arg value.
Found how preferences are initialized and used. Here is one example: https://github.com/theia-ide/theia/blob/master/packages/navigator/src/browser/navigator-preferences.ts

Looks like these are client side preferences... Is there a way to look at these preferences on the backend application side? Does it make sense for the backend application to access these preferences?

**Comment by BoykoAlex** [comment]
Most of the settings i can send to the backend language server process via `workspace/didChangeConfiguration`, but the JVM home and max heap size preferences are needed to correctly launch the language server process and therefore i need to send them over to the backend separately (outside of language server protocol). Is there a "theia" way to send something from the client to the server?

**Comment by BoykoAlex** [comment]
Thanks for you answers!-)

**Comment by dhuebner** [comment]
@BoykoAlex If you are still interesting in passing start parameter there is an additional start method now:

 ```
abstract start(clientConnection: IConnection, options: LanguageServerStartOptions): void;
```
