### ISSUE TITLE
Migrate to React

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1915]
Any usages of phosphor's virtual dom should be migrated to React.
See https://github.com/phosphorjs/phosphor/issues/302#issuecomment-333601384

**Comment by lukehutch** [comment]
(Copying comment from #302): 

Why not use Inferno instead? Its it is smaller and much faster than React, and in particular its virtual DOM diff implementation is much faster than React's. 

https://github.com/infernojs/inferno

**Comment by svenefftinge** [comment]
It is less mainstream so it would raise more questions and mean a steeper learning curve for people looking into adopting and contributing.
