### ISSUE TITLE
[git] Open File is missing

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1919]
It's very useful to open the editor for changes in git view. I'm not sure if this is a regression, but I miss the `Open File` action for the items in the list of changes:

<img width="431" alt="screen shot 2018-05-17 at 10 06 30" src="https://user-images.githubusercontent.com/914497/40164525-1739f71e-59ba-11e8-9a53-35a1fa61f37d.png">

I expected to see a such an open button:

<img width="117" alt="screen shot 2018-05-17 at 10 07 22" src="https://user-images.githubusercontent.com/914497/40164746-a6c6a260-59ba-11e8-9e3a-c6c0ab67ea7a.png">

BTW: the command `Git: Open File` works fine inside the diff editor. But it's inconvenient to open the diff editor first.

**Comment by kittaakos** [comment]
> if this is a regression

No, it is not.
