### ISSUE TITLE
`Close All` closes tabs on the wrong side bar

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1923]
It happens if a sidebar tab for which the context menu was triggered does not have focus.

**Comment by spoenemann** [comment]
How can that be reproduced?

**Comment by akosyakov** [comment]
I can reproduce it particularly with `Git` and `Outline` view:
- focus  `Outline` view
- right-click on `Git` view and select `Close All`
- observe that `Outline` view is closed

**Comment by spoenemann** [comment]
Could we extend the context menus so they pass the widget and/or DOM element that was right-clicked as an argument to the `execute` / `isEnabled` / `isVisible` methods of the command handlers?

**Comment by AlexTugarev** [comment]
@spoenemann not sure, if this is possible for electron.

**Comment by JanKoehnlein** [comment]
Also holds for editors. I wanted to close all editors, but closed all left panel views instead because the navigator had focus.

**Comment by kittaakos** [comment]
> I wanted to close all editors, but closed all left panel views instead because the navigator had focus.

Similar: https://github.com/theia-ide/theia/issues/1999
