### ISSUE TITLE
[navigator][context-menu] The contribution for the navigator context menu does not always available at start up

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1924]
See the attached screen-cast. As one can see, even the `Delete` and `Rename` (core items) are not available at startup. It did happen to me when I have opened a new workspace.

![theia_context_menu_issue](https://user-images.githubusercontent.com/1405703/40222656-86afb4c8-5a80-11e8-99aa-dbce0a50b64a.gif)

**Comment by kittaakos** [comment]
The `UriAwareCommandHandler` returns with `isEnabled` `false`, because the `selection` is `undefined` from the service:

https://github.com/theia-ide/theia/blob/448cbac3555d9d17afcd29befe0a27c95ec984cc/packages/core/src/common/uri-command-handler.ts#L74

**Comment by kittaakos** [comment]
The bug is here: https://github.com/theia-ide/theia/blob/448cbac3555d9d17afcd29befe0a27c95ec984cc/packages/core/src/browser/tree/tree-selection-impl.ts#L71-L73

We do not propagate (set) the selection from the `TreeSelectionService` to the `Selection` service when the internal state does not change.

**Comment by kittaakos** [comment]
The problem is: although we restore/set the selection of the tree at application startup here:

https://github.com/theia-ide/theia/blob/448cbac3555d9d17afcd29befe0a27c95ec984cc/packages/core/src/browser/tree/tree-widget.ts#L130-L131

We do not send this property to the `SelectionService` because the widget is not yet ready, hence there is no active widget in the shell:

https://github.com/theia-ide/theia/blob/448cbac3555d9d17afcd29befe0a27c95ec984cc/packages/navigator/src/browser/navigator-widget.ts#L77-L80

**Comment by kittaakos** [comment]
To sum up:
 - Happens only when you have an empty workspace with the single root node. Also, there are no editors.
 - There are no additional tabs (Git, History, and so on) but the `Files`.
 - On startup, we correctly set the state of the TreeSelectionService and we fire the onSelectionChanged but this time there are no active widgets, so we do not propagate the selection to the selection service.
 - Next time, when you click (right or left) the one and only single node the internal state of the tree selection service does not change, hence we do not fire a selection change event.

We agreed: removing the `this.shell.activeWidget === this` guard from the `naviagtor-widget` should fix the issue.

**Comment by akosyakov** [comment]
I meant [this guard](https://github.com/theia-ide/theia/blob/448cbac3555d9d17afcd29befe0a27c95ec984cc/packages/core/src/browser/tree/tree-selection-impl.ts#L71-L73), removing `this.shell.activeWidget === this` will break the global selection, for example: https://github.com/theia-ide/theia/pull/1663

**Comment by kittaakos** [comment]
Oh, OK. thanks for the update!

**Comment by kittaakos** [comment]
Here is the related change: https://github.com/theia-ide/theia/pull/1663/files
