### ISSUE TITLE
[question][language-client] The `ILanguageClient` from the `BaseLanguageClientContribution` is not available unless I open a file that belongs to my language

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1925]
This means I cannot extend and use the protocol unless I open the very first file for my language. After opening the first file, it works perfectly. Otherwise, `await this.languageClientContribution.languageClient` waits forever.

Is my assumption correct at all? At least, that was my experience so far. If it is correct, what could be a short (even dirty) solution? Is it possible to eagerly start 

CC: @akosyakov

**Comment by akosyakov** [comment]
Yes, it is correct default. One can override `BaseLanguageClientContribution.waitForActivation` to customize it.

**Comment by kittaakos** [comment]
Awesome!

**Comment by kittaakos** [comment]
Something like this does the trick:
```typescript
@injectable()
export class YourlLanguageClientContribution extends BaseLanguageClientContribution {

    readonly id = 'yourLanguage'
    readonly name = 'Your Language'

    constructor(
        @inject(Workspace) protected workspace: Workspace,
        @inject(Languages) protected languages: Languages,
        @inject(LanguageClientFactory) protected languageClientFactory: LanguageClientFactory) {
        super(workspace, languages, languageClientFactory)
    }
    // ... Your other methods

    // ts-lint:disable-next-line:
    waitForActivation(): Promise<any> {
        // To ensure eager activation. We do not wait until the first file open.
        return this.workspace.ready;
    }

}
```
