### ISSUE TITLE
[problems] view does not have a scroll bar

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1928]
The problems view does not seem to have a scroll bar. This is a limitation, specially when there are a lot of problem markers present. The corresponding VS Code view has it.

**Comment by jbicker** [comment]
For me it is not reproducible.
![problem-scrolling](https://user-images.githubusercontent.com/28291421/40371521-ede7c47c-5de2-11e8-8b66-c1a5f3814e91.gif)

**Comment by marcdumais-work** [comment]
Thanks for testing this, @jbicker . I also can't reproduce it ATM. Closing for now - will re-open if I can figure-out the steps to reproduce.
