### ISSUE TITLE
Investigate `ldm install -dev` on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#193]
It seems that the `devDependencies` are not installed into the downstream projects correctly on Windows.

See #188 
One needs to start the investigation [here](https://github.com/theia-ide/theia/blob/master/config/local-dependency-manager/src/package.ts#L209).

**Comment by kittaakos** [comment]
I have added error logging to the place mentioned above, nothing happened. But still, dev dependencies are missing from the example's `node_modules` folder. For instance; `concurrently`.

**Comment by akosyakov** [comment]
What if you do `npm install` after?

**Comment by kittaakos** [comment]
That works. See here: https://github.com/theia-ide/theia/issues/188#issuecomment-307763803
By the way, I think I have managed to figure out the problem. I am just running the verification builds.

**Comment by kittaakos** [comment]
Although I still have the feeling we unnecessarily run either build or install steps multiple times, the Windows-based example build works fine with my changes. See attached full [log](https://github.com/theia-ide/theia/files/1071234/gh_193_theia_example_full_console_output.txt) for more details.

**Comment by kittaakos** [comment]
PR: #198
