### ISSUE TITLE
[theia] Open workspace dialog scaling issue

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1935]
Depending of your display resolution and  size of Theia client when opening the dialog to select a new workspace, the "OK" and "CANCEL"  buttons are un-reachable. Also, the dialog exceed over the status bar.

![peek 2018-05-22 openworkspacenobuttons](https://user-images.githubusercontent.com/419051/40373483-0093b866-5db5-11e8-8056-39c85fc0b9ce.gif)

**Comment by elaihau** [comment]
I will add a few `min-height` to handle this scenario.
