### ISSUE TITLE
[theia] Usability to use Theia to develop Theia

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1937]
I want to use Theia as a development platform
 1- Create a stable Theia + compile: OK
 2- Start Theia from the browser -> It starts on port 3000 by default, let say I change it to port 3001 to let the port 3000 available when I test the application, otherwise I get an error saying "Address in use" OK for now, but not convenient to specify a port to start from !

 3- In ".theia/recentworkspace.json", it records my stable running Theia.Now, each time I create a new workspace, it erases my stable Theia running application --> issue here, I don't want to reset my Theia stable application when running a test environment, not very convenient

 4- In your developement Theia, open a terminal. Execute ANY COMMAND i.e. 'ls -alF'
  Now resize the browser to be smaller -> Note the delay it takes to resize the workspace, very slow before we see the "outline" bar to show. Try again to smaller size. still very slow. Also note in the terminal how long it takes to refresh and have the scrollbar available, when I select the scrollbar, it does not respond rapidly either.
Note: Using other tabs  in the same browser (Firefox)  and the performance are OK.

file:///home/lmcbout/Videos/Peek%202018-05-22%20TheiaInBrowser.gif

**Comment by marcdumais-work** [comment]
@lmcbout looks like you wanted to attach a video, but it didn't work.

**Comment by gorkem** [comment]
@mmorhun FYI

**Comment by lmcbout** [comment]
Here the missing small video .

![peek 2018-05-22 theiainbrowser](https://user-images.githubusercontent.com/419051/40422369-24d7ece4-5e5d-11e8-8251-4e4ec32767d0.gif)

**Comment by lmcbout** [comment]
Some extra observation:
1- The small video was perform with Firefox
2- If I do the same with Chrome, the performance are ok but the scroll for the terminal dissappear most of the times, it like the view area overlaps the vertical scrollbar. When enlarging the terminal window, we can see the scroll bar position but when resizing occurs, it goes away. When reducing the width , the vertical scroll bar never shows in the terminal window.

**Comment by marcdumais-work** [comment]
@lmcbout Thanks for bringing-up these usability concerns, that you observed. 

If we go one by one: 

a) Theia backend starting with default port number, collision if starting a second backend
I think this is a valid concern. Starting Theia without specifying a port number, it will  attempt to use port 3000, and fail if it's already used. Maybe we could try ports, starting at 3000, until we find one that's free, or request an ephemeral port that would end-up being a random, free one. But then the user would have to check the backend traces to find that port, and use it to connect, which is also not so user-friendly. 

In the stated context, where the user wants to launch a "test" instance of Theia, we can imagine that we would eventually have a launch configuration for that, where the user could configure how that Theia instance would be started, including on which port. We had similar in Eclipse CDT, for the GDB server launch configs. 


b) "recent workspace"
Having only the latest workspace being remembered is indeed limiting. We have  recently discussed enhancing that, to save a list of recent workspaces. We could then add an "Open Recent" menu entry in "File", that would permit selecting one workspace from that list.

That being said, this observation, I think, highlights that the current way that both a "development" instance and a "test" instance share a common "user storage" might not be ideal, even if we extend it to support multiple recent workspaces. Ideally, I think the "test" instance should have its own, separate user storage "sandbox", like in Eclipse where the test instance has its own workspace, so they do not interfere with each other. 


c) Resizing performance
I am not able to reproduce this one. On my machine, using the latest master, it's quite fast to resize. 

I have noticed that when you start your terminal, there is a trace saying: **"Starting Eclipse with GTK3"**. Is it possible you start an eclipse, in e.g. .bashrc? If so, the CPU and memory taken at that time might explain the slowness.


Comments on these items? We should register specific issues, for those we think should be addressed.

**Comment by marcdumais-work** [comment]
I have tried the resizing on Firefox, and it's also fast on my machine.

**Comment by mmorhun** [comment]
@lmcbout as about workspace try to use on second Theia start:
`yarn theia start <path-to workspace-root> --port=<custom-port>`

**Comment by mmorhun** [comment]
Probably @AndrienkoAleksandr could comment about terminal resize.

**Comment by lmcbout** [comment]
@marcdumais-work 
a- Collision on port 3000: A supposition would be that Theia starts on port 3000 by default. When running theia in development mode, we could use 3001 and after until one is free ! The question would remains, How the user knows which port is currently used for his debug environment? May be we can only allow 3001 for development testing then ! A "test instance" in a launch configuration should become available soon if we want people to contribute and test Theai with Theia.

b- The menu of recents workspace would probably be usefull. As you mentioned, we need to have a clear distinction between the test and development user storage. Define an alternate user-storage on the cli would work, but a GUI to define it like in Eclipse would make it easier to the end-user. Both can live together

C- there is a trace saying: "Starting Eclipse with GTK3". is to let me know that if I start eclipse, the GTK being use will be GTK3 an not using GTK2. It is just a variable initialisation.  This morning  I rebooted my PC and still on Firefox, it is slower than in Chrome to be easily noticeable.

@mmorhun 
the command  "yarn theia start <path-to workspace-root> --port=<custom-port> " is the only way right now to start , but not every user will be wiling to mentioned a starting cli all the times. Also, when you start the second Theia on the cli not to overwrite the recentworkspace, you will not be allow to change the workspace from Theia oepn new workspace since the times, it will overwrite the ".theia/recentworkspace.json"

**Comment by marcdumais-work** [comment]
@marechal-p @elaihau could you please try the terminal resizing case, as described above, and report if you see the performance issue? Maybe try in both Chrome and Firefox.

**Comment by elaihau** [comment]
@marcdumais-work I tried on my local and the performance is OK. Tested in both Chrome and FF.
I did see some lagging if I dragged the edge of the browser fast enough, however, it wasn't as bad as what @lmcbout 's GIF showed.

**Comment by marcdumais-work** [comment]
@lmcbout regarding the performance issue, I wanted to rule-out one potential cause: can you confirm that the test was done running the Theia backend in "normal" mode, i.e. not in a debug session?

**Comment by marcdumais-work** [comment]
update: we traced the "resizing" performance issue to a corrupted Firefox profile.

**Comment by marcdumais-work** [comment]
I think all that was reported in this issue is either addressed or has a specific issue created.
