### ISSUE TITLE
[Question] Test my extension in Theia

### ISSUE THREAD

**Issue by BoykoAlex** [theia-ide/theia#1938]
My goal is setup some kind of a build for my Theia extension that would produce an artifact that could be installed into Theia.

I was thinking of packing my Theia extension in a tarball, i.e. `npm pack` and then install it into Theia...

Is there a way to download Theia for Web Developers desktop app? I suppose if that was available the next step would be installing extension package tarball... Is that possible?

Does this sound like the right approach to achieve the goal stated at the top? Or is there a better way perhaps?

**Comment by akosyakov** [comment]
Theia applications and extensions are normal node packages. You can package your extension to a tar with `npm pack` and then add it as a tar dependency to your app package. 

> Is there a way to download Theia for Web Developers desktop app? 

There is no right now. But you can create a new package.json, add required extensions as dependencies, your extension as a tar dependency, set target to electron and run `theia build` + `theia start`. See https://github.com/theia-ide/theia/tree/master/dev-packages/cli to learn how to use theia cli.

**Comment by BoykoAlex** [comment]
Thanks very much!-)
