### ISSUE TITLE
Verify the vs `alias` in the webpack configuration.

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#194]
Currently, the alias resolves into a non-existing location. Do we need it at all?
The `alias` configuration can be found [here](https://github.com/theia-ide/theia/blob/master/config/webpack/webpack.config.js#L38).

**Comment by hexa00** [comment]
@kittaakos  Is this still try after #299 ? the link now is 404

**Comment by svenefftinge** [comment]
Not sure what was the issue here back then, but today the alias resolves fine. Please reopen if there is something we should take action on.
