### ISSUE TITLE
Clean up webpack configuration for the examples

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#195]
Clean up proxy configurations [here](https://github.com/theia-ide/theia/blob/master/examples/browser/webpack.config.js#L7).
And move the `empty` [webpack file](https://github.com/theia-ide/theia/blob/master/examples/browser/webpack.config.js#L40) next to the other configurations.

**Comment by hexa00** [comment]
I think this was addressed by #299 @kittaakos ? I'm closing please reopen if it's still revelant
