### ISSUE TITLE
[question] What shoudl we do with the terminal when restarting the server.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1950]
How should we handle the terminal data when restarting the server ?
Scenario:
1- Theia Web client is open , open a terminal, change directory and execute some commands
2- Stop the server, create a new version of the server and restart it --> Theia web server went from off-line to connected again.
3- While restarting the server, one line showed up on the console:
" 2018-05-24T11:32:21.657Z] ERROR: Theia/5216 on elxa36mbq32: Error attaching to terminal id 3, the terminal is most likely gone. Starting up a new terminal instead. [] (logger=terminal) "
4- I observed that the terminal shows the last command executed in the terminal, but now the terminal is not in the selected folder where I executed the command, but to the folder associated where I started the Theia server.

What should we do?
- Possibility that the server and the client will not connect anymore depending of the new server version.
- The terminal still shows the last commands, but the terminal is in a different folder.
- Should we keep or remove the data showed in the terminal and just restart a new empty terminal?
- Should we add an indication too attract the attention of the end-user that the terminal folder has changes?

Now I restart the Theia client

- the terminal is restarted empty now, no more traces of previous command execution, the terminal  is showing the folder we started the new server. In this case, I think it is ok since we started a new fresh teminal.

**Comment by marcdumais-work** [comment]
I do not think there is much to be done, to automatically recover in cases, the connection/state of FE <=> BE, when a backend is replaced by another one that is not version-compatible. In that case, it will probably be mandatory to restart/refresh the client too, which will then fetch a fresh, updated copy of the FE code, from the backend. 

So if we set that case aside, we are left with the case where backend is restarted, with one or more terminals opened in the frontend. 

A terminal runs in the backend, and sends its output to the frontend, populating the XTerm terminal widget with it. Like a regular native terminal, the exact state is not preserved between sessions. e.g. the current active directory, in a terminal, will not be restored if a terminal is closed and re-opened. That part is expected.

So what this boils-down to, is that, in cases where a terminal is lost by a backend restart, the frontend still shows the output from the previous terminal. We have a few potential options:

 - clear the terminal widget
 - keep the output in the widget, but add a message saying that the terminal has been restarted
 - (more generic but maybe not a good idea?): force a client restart when it's detected the BE has restarted, thus clearing such non-saved state
 - keep current behavior
 - ...

**Comment by svenefftinge** [comment]
+1 for
> clear the terminal widget

but 
> keep current behavior

is IMHO not too bad either.

**Comment by marcdumais-work** [comment]
@svenefftinge I am leaning on the side of leaving it as-is. 

If for some reason the backend I am using is restarted, I think I would prefer being able to see the previous terminal's output, to help remind me what I was doing in that terminal, see what last happened,...  Even if it's a new terminal effectively connected to the widget, at that point. 

Other opinions?

**Comment by marcdumais-work** [comment]
Closing this for now, re-open to continue discussion
