### ISSUE TITLE
Close "Git Blame annotation" without closing the editor does not exist

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1951]
Git: show Blame annotation  (ALT+B)  works fine
If I want to close the Blame annotation section without closing the file, there is no command for it. Should the command be a toggle , the first time it opens Git Blame and closes the Blame annotation if re-execute the command !

**Comment by lmcbout** [comment]
Thanks, should we document it somewhere !

**Comment by kittaakos** [comment]
> Thanks, should we document it somewhere !

@lmcbout feel free documenting it.

**Comment by AlexTugarev** [comment]
GitLens had `show` and `toggle` in the beginning, they dropped first in favor of `toggle`. 

Maybe we should change as well, WDYT? I'd take care of that, if wanted.

**Comment by marcdumais-work** [comment]
> GitLens had show and toggle in the beginning, they dropped first in favor of toggle.
Maybe we should change as well

+1
It also did not occur to me to try ```escape``` to close the git blame annotation, so I ended-up closing / re-opening the editor in the end, after unsuccessfully trying to toggle.

**Comment by marcdumais-work** [comment]
> should we document it somewhere

As a user I would be unlikely to seek this type of information from a manual, even if that manual was extensive. I think it's better to make it intuitive.

**Comment by AlexTugarev** [comment]
Fixed in #2392
