### ISSUE TITLE
Templates showing and allow modifying the preferences

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1952]
Is there a template showing all available preferences that we can apply in Theia, What are the default value for each preferences? How and where can I modify a preference?

Suggestion: Like git hooks, there are files like "commit-msg.sample". All information is already available in the file, we just need to uncomment the functionalite we re interested in  and rename the file to have it available. Easy to use.

**Comment by vince-fugnitto** [comment]
@lmcbout  Can we close this thanks to the `Preferences Widget`?

**Comment by lmcbout** [comment]
With the preference UI implemented, it fulfill this request.
Thamks
