### ISSUE TITLE
As a Theia extension developer I would like to avoid copy-pasting the boilerplate core modules setup code

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#196]
In the examples, one needs to load all the code modules (such as file system, messaging, logging, etc...) each time with the actual Theia extension.

It would be great if Theia would be shipped with a base class or a function that does that boilerplate part. So one can concentrate only the extension.

**Comment by akosyakov** [comment]
@kittaakos considered fixed with theia generator?

**Comment by kittaakos** [comment]
See https://github.com/theia-ide/theia/pull/299
