### ISSUE TITLE
[mini-browser] Add refresh button

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1972]
the mini browser chrome needs a refresh button.

**Comment by kittaakos** [comment]
We do not know and cannot access the current `location.href` if it is from a cross-domain.

**Comment by roberttilewick** [comment]
Sorry - can you refresh now? If so, how?

**Comment by msujew** [comment]
@roberttilewick The mini browser contains a toolbar that allows you to refresh the embedded iframe:

![image](https://user-images.githubusercontent.com/4377073/188468118-e362c669-ab36-477c-b9ff-20c79c5d2bbf.png)

**Comment by roberttilewick** [comment]
Thanks, but I don’t see that toolbar. What am I doing wrong?
