### ISSUE TITLE
Pushing Git Commit fails

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#1975]
After having cloned a remote Git Repository and placed a Commit, pushing the changes back to the remote server fails without errors. Within the context of what has been tested here the remote repository is on Bitbucket and requires username and password when pushing to it. Neither username nor password are asked at any time though.

![bildschirmfoto vom 2018-05-28 14-06-41](https://user-images.githubusercontent.com/38067850/40613946-ed0f4a96-6280-11e8-810e-9bbccf6190a3.png)

![bildschirmfoto vom 2018-05-28 14-07-12](https://user-images.githubusercontent.com/38067850/40613950-ef6d4a22-6280-11e8-86c0-c1ef598755df.png)

**Comment by kittaakos** [comment]
Perhaps you were facing the same problem as described here: https://github.com/theia-ide/theia/issues/1787

**Comment by jeanlucburot** [comment]
Looks similar indeed. I guess there will eventually be a difference in Theia's remote browser version and desktop electron version. Even though the terminal can be used as a workaround, it should IMO remain a workaround until there is a more user friendly option inside of Theia, hence, a dialog of some sort providing positive and negative feedback and also offering the next steps.

**Comment by kittaakos** [comment]
@jeanlucburot, if you do not have any objections, I would like to close this and merge your [last comment](https://github.com/theia-ide/theia/issues/1975#issuecomment-392547972) into #1787.

**Comment by jeanlucburot** [comment]
@kittaakos Please do.
