### ISSUE TITLE
[workspace] Register the last workspace the user works with, not necessary the last closed workspace.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1978]
When closing a workspace, it modifies the "<homedir>/.theia/recentworkspace.json".  I think the recentworkspace.json should be adjusted when we select the workspace tab on the browser. The end result will be that if a user stops and restarts the BE- FE, the proposed workspace to the user will be the last workspace he worked with.  Also, we need to remove the line updating the "recentworkspace.json" when closing a workspace. Closing register the workspace  closed last, not necessary the last workspace the user was working with.

**Comment by vince-fugnitto** [comment]
Closing, duplicate and newer issue #2998
