### ISSUE TITLE
[navigator] Support multi-selections

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#20]
To support commands that can deal with multiple files

**Comment by akosyakov** [comment]
Depends on https://github.com/theia-ide/theia/issues/447

**Comment by svenefftinge** [comment]
- [] 'Delete' should support multi selections.
 - [] Add 'Compare with Each Other' to open two files in diff editor.

**Comment by kittaakos** [comment]
From https://github.com/theia-ide/theia/issues/447#issue-254570264.

- [ ] the tree selection service should be improved to support additional selections https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-selection.ts#L68
- [ ] the tree widget should add additional selection on the click https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-widget.ts#L262

**Comment by kittaakos** [comment]
> the tree widget should add additional selection on the click https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-widget.ts#L262

Unfortunately, this item is outdated.
