### ISSUE TITLE
Display drives in `FileDialog` 

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#200]
in the case with one drive, the drives section could be omitted

**Comment by hexa00** [comment]
What is a driver in that context ? Like using custom web vs native ?

**Comment by akosyakov** [comment]
'C:', 'D:' on Windows, on Mac when you insert a USB stick you can see new devices

**Comment by hexa00** [comment]
Haaa OK :) typo there I guess

**Comment by lmcgupe** [comment]
Sorry, i don't have a MAC environment to reproduce this.

**Comment by akosyakov** [comment]
@lmcgupe it is not about MacOs, but was actually motivated mostly by Win support, since the user should be able to switch between different drives like `C:` and `D:`
