### ISSUE TITLE
Open files view by default?

### ISSUE THREAD

**Issue by travis1111** [theia-ide/theia#2005]
Hi, as mentioned in this post:

https://github.com/theia-ide/theia/issues/1546

We would like to display something one the user opens up the editor the very first time.  For example the Files Tree view at the left.  Currently both files and git views are closed.

We saw this commit:

https://github.com/theia-ide/theia/pull/1605/files

So I guess what I need to do is to extend this: ``frontend-application.ts``, and override method ``createDefaultLayout``, is that correct?

If yes, so in that method, open up the files view?  how?

thanks

**Comment by svenefftinge** [comment]
You can inject the `FileNavigatorContribution` and then call 
```
    navigator.openView({
        activate: true
    })
```

**Comment by JustinBobby007** [comment]
> You can inject the `FileNavigatorContribution` and then call
> 
> ```
>     navigator.openView({
>         activate: true
>     })
> ```
FileNavigatorContribution  can not be imported by other packages.  
This works: 
`app.shell.activateWidget(XXX_WIDGET_ID);`

**Comment by IPvSean** [comment]
@donalod did you ever figure out how to open a default directory view and keep the terminal open?

**Comment by donalod** [comment]
@IPvSean negative, I sank too much time and was not familiar enough with it, so I bailed unfortunately. Sorry I don't have better news.

**Comment by IPvSean** [comment]
hahaha that is where I am @donalod , exact same problem and I wasted too much time on this already

**Comment by akosyakov** [comment]
@donalod Could you post a question on the community page (https://spectrum.chat/theia?tab=posts) and provide a github repo with what you were able to achieve? Positing on a closed issue does not help, no one will see it.

**Comment by rubenanapu** [comment]
The solution implemented in the link below worked for me:

https://github.com/bayodesegun/theia/pull/1/files

If the link above goes down, the solution consists of basically modifying the `theia/packages/navigator/src/browser/navigator-contribution.ts` file,  more specifically `initializeLayout` method.

It was changed from this:
```
async initializeLayout(app: FrontendApplication): Promise<void> {
        await this.openView();
}
```

to this:

```
async initializeLayout(app: FrontendApplication): Promise<void> {
        // Reveal 'Files' view when opening a workspace for the first time
        // See:
        //  https://github.com/bayodesegun/theia/pull/1
        //  https://github.com/eclipse-theia/theia/issues/830
        await this.openView({ activate: true, reveal: true });
    }
```
