### ISSUE TITLE
[lsp][xtext] Disable the LSP features when opening historical revisions of a model resource (from the Git History view) in an editor

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2006]
It messes up the problem decorators in the `Files` navigator and also pollutes the `Problems` view with irrelevant diagnostics. I assume we need to filter the (`gitrev`) URIs and do not call `didOpen` and `didClose`. See the attached screencast:

![screencast 2018-05-31 15-03-05](https://user-images.githubusercontent.com/1405703/40783937-4ef8d582-64e4-11e8-8553-d9e22c411467.gif)

**Comment by svenefftinge** [comment]
I think it should be filtered by the language server. It might be able to deal with such URIs.

**Comment by kittaakos** [comment]
OK. I was not sure which part should do that.
