### ISSUE TITLE
Creating React components with JSX instead of plain javascript

### ISSUE THREAD

**Issue by AhmetTanakol** [theia-ide/theia#2008]
Hello,

I looked at some examples of creating an extension. Instead of using `React.createElement`, is it possible to use JSX syntax? I am planning to integrate a react application which was written in JSX format, so it is not feasible to convert everything. I am really new to Theia, at this point I can't know my limitations. 

```
export class App extends React.Component {
  render() {
    return React.createElement('div', {style: appStyle},
      React.createElement('header', {style: appHeaderStyle},
        React.createElement('h1', {style: appTitleStyle}, 'Welcome to React')
      ),
      React.createElement('p', {style: appIntroStyle}, 'React App')
    );
  }
}
```

Thank you

**Comment by svenefftinge** [comment]
Please see this PR which marks the first step towards migrating to React.
https://github.com/theia-ide/theia/pull/1914

See especially the addition in the tsconfig to allow tsx syntax.
