### ISSUE TITLE
Check why example build takes so long

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#201]
This task should also take care of the Travis-CI integration. One single build takes ~20 minutes.

**Comment by hexa00** [comment]
I tried to cache node_modules and examples/electron/node_modules and download and it did not help. I think this is going as fast as it can.

And it takes 10 minutes per node version so 20 minutes is version 7 + version 6

Closing this based on that.

**Comment by akosyakov** [comment]
BTW After restructuring, it is about 6 mins: https://travis-ci.org/theia-ide/theia/builds/254237999?utm_source=github_status&utm_medium=notification

**Comment by hexa00** [comment]
The examples are not there anymore so it does take less time for sure

Also btw I see many
```
@theia/languages: > @theia/languages@0.0.1-alpha.1 test /home/travis/build/theia-ide/theia/packages/languages
@theia/languages: > echo 'Error: no test specified'
@theia/languages: Error: no test specified
```
Looks weird

**Comment by akosyakov** [comment]
Examples are there: https://travis-ci.org/theia-ide/theia/jobs/254238000#L1538 only UI tests are switched off for now

**Comment by akosyakov** [comment]
`echo 'Error: no test specified'` - lerna invokes test script on all packages and it says that the package does not have tests right now
