### ISSUE TITLE
Enable macOS CI

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#202]
See https://docs.travis-ci.com/user/multi-os/

**Comment by kittaakos** [comment]
I doubt that we need it in the near future. Almost all of us uses OS X on daily basis.

**Comment by hexa00** [comment]
Well I don't , I'd rather have CI tell me that it breaks and one of you guys at some later point...
It's useful to easily identify where the issue was introduced too
It seems easy enough to do also...

**Comment by hexa00** [comment]
See: #421

**Comment by hexa00** [comment]
This is done.
