### ISSUE TITLE
[search] Minor Improvments

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2022]
We should register an additional command, for `Search in workspace`, that opens and focusses the search view no matter it is there or not.

Also when in the search field, I'd like to be able to use the cursor-down key to select the first match.

**Comment by svenefftinge** [comment]
And using cursor up on the first entry, should again select the search field.

**Comment by svenefftinge** [comment]
A menu action on items in the file navigator would be very useful, too.
`Find in Folder...`

**Comment by simark** [comment]
> We should register an additional command, for Search in workspace, that opens and focusses the search view no matter it is there or not.

+1, I was going to file an issue for this :)

**Comment by jbicker** [comment]
> A menu action on items in the file navigator would be very useful, too.
I have filed a new Issue for that: https://github.com/theia-ide/theia/issues/2049

The rest is solved here: https://github.com/theia-ide/theia/pull/2029
