### ISSUE TITLE
Open the new file in editor

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#203]
Open the file after its creation in an editor.

**Comment by hexa00** [comment]
I'm sorry I just don't understand what that means ? :)

Could you please elaborate ?

**Comment by kittaakos** [comment]
When creating a new file, the file should be opened in the editor.

**Comment by hexa00** [comment]
OK so when creating a file using theia the file should show up in the editor ? 

Does theia have a new file command already?

**Comment by kittaakos** [comment]
One can create a new file from the navigator via the context menu option.

**Comment by hexa00** [comment]
OK thx for the clarifications

**Comment by akosyakov** [comment]
Will be fixed by https://github.com/theia-ide/theia/pull/166
