### ISSUE TITLE
[Question][Enhancement] Overlay icon in the editor for the delete and dirty file.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2034]
When having a dirty file, we replace the icon to delete by a fill circle, should we have an overlay icon instead to show the file is dirty, but the user can select the icon to delete the file from the editor, means we should still show the  "X" 
Clean file: show the "X" icon to delete
Dirty File: show the "X" icon to delete , but we overlay with the "Circle"

**Comment by lmcbout** [comment]
@vince-fugnitto Yes the circle means dirty, but it does not say delete if you click on the circle !

**Comment by vince-fugnitto** [comment]
@lmcbout this is not confusing however, a regular user of Theia would understand what this means and if the user does decide to click the circle, he will be prompted stating that there are unsaved changes. The same can be found in vscode like I mentioned earlier.

**Comment by vince-fugnitto** [comment]
Remember, the **x** icon is to close the editor, not delete. We display the **circle** to indicate the file is dirty and has unsaved changes. Are you fine with closing the issue?
