### ISSUE TITLE
[question] Extend default view class?

### ISSUE THREAD

**Issue by travis1111** [theia-ide/theia#2035]
Hi we would like to have the file tree view open by default, so I think the correct way is to extend ``FrontendApplication``, but and override method ``createDefaultLayout``...

But it seems my code is not being called:

Module.ts
```sh
import { FrontendApplicationContribution } from '@theia/core/lib/browser';
import { DefaultViewFrontendContribution } from './defaultview-contribution';
import { ContainerModule } from "inversify";

export default new ContainerModule(bind => {
    bind(FrontendApplicationContribution).to(DefaultViewFrontendContribution);
});
```

Controbution.js

```sh
import { injectable } from "inversify";
import { FrontendApplication } from "@theia/core/lib/browser";


@injectable()
export class DefaultViewFrontendContribution extends FrontendApplication {

    /**
     * Let the frontend application contributions initialize the shell layout. Override this+     * method in order to create an application-specific custom layout.
     */
    protected async createDefaultLayout(): Promise<void> {
        
        console.log("called me");
    }
}
```
I ran it in debugger, console.log(''called me'') not called.

I guess there are problems with my code... but I don't which part is causing the issue... :p-)

**Comment by kittaakos** [comment]
@travis1111, do you have a public repository I can check out to see what is going on? Are you developing your own Theia extension?

Although I did not try it (not even compiled this), I would do something like this:
```typescript
import { inject, injectable } from 'inversify';
import { FileNavigatorContribution } from '@theia/navigator/lib/browser/navigator-contribution';
import { FrontendApplicationContribution } from '@theia/core/lib/browser/frontend-application';

@injectable()
export class OpenFileNavigatorContribution implements FrontendApplicationContribution {

    @inject(FileNavigatorContribution)
    protected readonly navigatorContribution: FileNavigatorContribution;

    async onStart(): Promise<void> {
        await this.navigatorContribution.openView({ reveal: true });
    }

}
```

And in your frontend module, add the following binding:
```typescript
bind(FrontendApplicationContribution).to(OpenFileNavigatorContribution).inSingletonScope();
```

So instead of subclass anything, you have a contribution that will run at application start-up: it opens and reveals the `Files` view.

Let me know if that does not work for you. If it is OK, please close the task. Thanks!

**Comment by travis1111** [comment]
Hi, @kittaakos We only want to show the file tree view when a new project is created.  After that we still want to restore the view from the last access.  So I am guessing subclass is the only option here.

I will add my code to a repo, but I have created one extension in the past, so this time I just copy and paste and modify...  so the setup shouldn't be an issue...

**Comment by travis1111** [comment]
@kittaakos thanks it is working now, I had to use ``inSingletonScope()``.  Thank you!~
