### ISSUE TITLE
Cannot set the selection in the monaco editor programmatically

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#205]
In the theia-sprotty example we use the following code to open an element in the the monaco editor

```
this.editorManager.open(uri).then(
   editorWidget => {
      const editor = editorWidget.editor
      editor.selection = location.range
      editor.cursor = location.range.start
      editor.revealRange(location.range
   }
)
```

While cursor is set and the range revealed properly, the selection is not applied. 
Is that  the wrong way of setting the selection, or is it a bug?

**Comment by svenefftinge** [comment]
Maybe this was fixed in the meantime? At least the outline extension uses `editor.selection` when selecting a node and it works.

**Comment by JanKoehnlein** [comment]
Confirmed. Yangster (theia-sprotty) already uses this successfully.
