### ISSUE TITLE
Improve warning styles

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2053]
They should be readable in the bright and dark theme.

Right now:
<img width="360" alt="screen shot 2018-06-06 at 14 57 27" src="https://user-images.githubusercontent.com/3082655/41039518-f5522776-6999-11e8-88f8-e00e9119dc7c.png">

**Comment by kittaakos** [comment]
Just like the `Offline` from the status bar.

**Comment by vince-fugnitto** [comment]
Fixed!
