### ISSUE TITLE
[preview] Does not show the images [jpg]

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2055]
Maybe I am not using the correct syntax, but it works on GitHub. It does not show up in Theia.

```md
![](./path/to/my/image.jpg)
```

**Comment by AlexTugarev** [comment]
This would require to serve those images from the file system.
It would be nice to extend it as described. Also it sounds familiar, there might be a similar issue. I’ll try to find.

**Comment by svenefftinge** [comment]
Let's just assume the mini-browser extension is installed and use its endpoint.

**Comment by eldos-dl** [comment]
Double-clicking on an image file is opening it as an editable file and not showing an image preview by default. However, double-clicking the second time is opening the image preview. Is this expected behavior? Any workaround for this?
