### ISSUE TITLE
[editor] Support complex coloring

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2058]
## Goal
Support complex coloring, such as semantinc coloring (end game) or just very good lexical coloring. Developers spend a lot of time in front of source code, so better make pretty and clear to read the information we are looking for !

## Approaches
1. Use the Language Server to gather relevant information on symbols and keywords
2. Use Textmate and its grammars and themes

While (1) would provide the best coloring possible because it could have access to the whole context of the project, it has also the biggest overhead. Source files can be really big, and asking the LS for anything comes at some cost. Hopefully the LSP should evolve and propose messages optimized for this use case, but this is currently not the case.

(2) requires `oniguruma` in order the use the Textmate grammars and parse source files, so the trick is to make this library run in the browser. The coloration is not as fine as other semantic coloring, but it is a fair tradeof between speed and quality. Textmate could be used as a first pass and then later apply more precise coloring.

## Tasks:
- [ ] Use the LS to tokenize the source files
- [ ] Optimize the usage of Textmate in the browser

**Comment by marechal-p** [comment]
#944 #1757

**Comment by svenefftinge** [comment]
This is done now.
