### ISSUE TITLE
[editor] Use Textmate to colorize the source files

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2059]
Relative to #2058 

The goal is to place most of Textmate's dependencies in the browser, so that the coloring is as fast as possible, while still allowing some modularity in order to easily expand the list of supported languages.

**Comment by marcdumais-work** [comment]
@marechal-p would this issue correspond to https://github.com/theia-ide/theia/pull/2118 ? If so can we close it?

**Comment by marechal-p** [comment]
https://github.com/theia-ide/theia/pull/2118 merged.
