### ISSUE TITLE
Rename Emitter Event() to Subscribe and Event<T> to Listener<T>

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#207]
When trying to understand how the events worked in Theia I was very confused about the wording used in the Emitter class.

Namely:
```typescript
/**
     * For the public to allow to subscribe
     * to events from this Emitter
     */
    get event(): Event<T> {
```

What this property actually does is registering listeners on the emitter.

It's confusing that it is called event and is a property since it leads to beleive that this is an actual Event Object ( what you were to pass as fire(event) )...

In fact this function does not relate to the concept of a event at all, it relates to listeners and their subscribtion.

So I propose we change the name to: 
```typescript
get subscribe()
```

Also the Event<T> type is not related to an event, it is actually the signature of a closure over a listener function.

So I propose we change the name to:
```typescript
export interface Listener<T>
```

So in the end we would have:
```typescript
get subscribe(): Listener<T>
```

WDYT?

**Comment by svenefftinge** [comment]
I agree that the current names are missleading

**Comment by hexa00** [comment]
OK I'll refactor this soon

**Comment by akosyakov** [comment]
It should be something like `EventSource` and `source` then.

**Comment by akosyakov** [comment]
It was taken from vscode: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameeventaspan-classcodeitem-id421eventlttgtspan. Also it used with vscode-jsonrpc, so we won't be able to get rid of it in implementations of language server contributions.

**Comment by hexa00** [comment]
I see, I did not know that, maybe it's better left as is then

**Comment by hexa00** [comment]
Let's leave it, the way the vscode doc explains it kinda make sense and I don't want to have 2 implementations of it, closing this.
