### ISSUE TITLE
Navigator scrolls back up when selecting a item

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2072]
Using a pretty recent build of Theia (a2df2fafd8c98070f4e991e4cf9b1cb6162e8363, June 1st), Electron example.

It doesn't happen every session but when I scroll down in the navigator and click on a file, it scrolls back up. This makes it difficult to open files. I have to resort to doing a single click then pressing enter.

![navigator-bug](https://user-images.githubusercontent.com/311730/41109161-52267614-6a44-11e8-966c-7cca5a70ea90.gif)

**Comment by JanKoehnlein** [comment]
Sounds like #1593 is back?

**Comment by kittaakos** [comment]
I was not able to reproduce it yet, but I found a difference in the navigator when running in browser and electron:
  - In the browser version: if you refresh the browser, the [tree state is not stored/restored](https://github.com/theia-ide/theia/issues/1316).
 - In the electron version; the tree state is restored.

**Comment by kittaakos** [comment]
Same as: https://github.com/theia-ide/theia/issues/3347
