### ISSUE TITLE
The "clangd is not installed" popup is not shown

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#2081]
If clangd can't be started because it is not found, Theia is supposed to show a popup with a link explaining how to install it.  It seems like this popup is not shown anymore.  However, when closing the backend (and thus breaking the single websocket connection), then the popup finally appears.  So there seems to be a problem communicating the failure to start clangd to the frontend.

**Comment by vince-fugnitto** [comment]
The `clangd is not installed` popup correctly displays as of  d874539.
I'll re-open the issue if the problem ever returns.
