### ISSUE TITLE
The "more information" button in the "classpath not defined" java language popup doesn't work

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#2082]
When loading a Java project with missing classpath information, the java language server reports that it will only give syntax errors.  Theia then shows a popup with a "more information" button.  This button does nothing, and I saw an error in the console (I don't have it right now unfortunately, I'm typing this from memory) about a missing handler for the corresponding command.

**Comment by gorkem** [comment]
Duplicate of https://github.com/theia-ide/theia/issues/1078 ?

**Comment by simark** [comment]
Ah indeed, sorry.
