### ISSUE TITLE
Additional Keybindings and Menu Items

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#210]
We should register keybindings and menu items for
- [ ] undo/redo 
Will be tested by opening an editor, applying a change, then undo the change and verify the document’s state. Afterwards ‘redo’ shall reapply the change.
- [ ] find/replace (in editor) 
Will be tested by searching a text phrase in a document.
- [ ] copy/paste (menu only in electron) 
The copy and paste menu actions, will be added to the Electron application’s main menu. It will copy the currently selected text of the focusses text editor into the clip board. ‘Paste’ will insert the text in the system’s clipboard at the cursor position of the currently opened and focussed text editor.
- [ ] selection commands 
The main menu contributions for the selection commands shall have the same effect than the corresponding keybindings.

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/437

**Comment by akosyakov** [comment]
Done with https://github.com/theia-ide/theia/pull/437
