### ISSUE TITLE
[Editor] Preferences

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#211]
Based on the preferences registry (#12), we should allow users to configure whether they want to
- [x] see line numbers 
If this is turned on (defaults to on), the rule on the left of an opened text editor will show line numbers. If it is turned off, no line numbers will be shown.
- [x] have word wrap activated 
If this is turned on (defaults to off), any text that exceeds the horizontal width of an editor will be soft wrapped. I.e. the contents will be shown on subsequent lines.
- [x] see visually rendered whitespace 
If this is turned on (defaults to off), whitespace characters are visually rendered using appropriate symbols. It can be tested with any text file, containing white spaces.

**Comment by epatpol** [comment]
As @simark pointed out on gitter, I think tabSize would be a nice improvement too.

**Comment by hexa00** [comment]
Just a comment on the line warp,, it would be nice to have some indicating that it does wrap at the end of the line, I found that very annoying in vscode that you have to use line numbers to know if it's wrapped

**Comment by epatpol** [comment]
#281 checks the first two options. They were pretty easy to add as monaco already had some options for those. As for the whitespaces, I think (unless I missed it somewhere in the api), we need to implement our own coloring function or something along those lines.

**Comment by akosyakov** [comment]
@epatpol you should use `renderWhitespace: 'all'` for Monaco

**Comment by epatpol** [comment]
I'll close this one for now, although the preferences system can still be improved, issues are going to be opened/discussed in other threads.
