### ISSUE TITLE
[Question]Should we clear markers when closing the corresponding editor?

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2110]
When closing the editor, we should remove the associated problem markers.
Do we need to maintain the list of markers for previously opened files? The markers get generated when opening a file

**Comment by svenefftinge** [comment]
It is the duty of a language server to decide on whether to remove them or not. Depends on their capabilities of keeping track of the full workspace (e.g. Java, Xtext) or only the opened buffers (e.g. TypeScript). Closing it, please open if I missed something.
