### ISSUE TITLE
Quick Access Widget

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#212]
We need a widget that allows users to quickly search for things like commands, files, symbols, etc.
It should be a pop-up, with a text field and a list of results below. The top element should be selected and chosen on enter, but cursor keys should allow to change it.

Also, the default search strategy should allow fuzzy search. Something like http://fusejs.io/ seems appropriate.

**Comment by akosyakov** [comment]
Covered by https://github.com/theia-ide/theia/commit/84e5434962a210d1500b8334a0eee93ca2a2d0ae
