### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#213]
Based on #212 a command palette shall be opened. The user shall be able to search through any of the registered and at that time enabled commands and execute one of them.

<img width="863" alt="screen shot 2017-06-15 at 08 43 12" src="https://user-images.githubusercontent.com/372735/27168607-b5c105ac-51a6-11e7-9964-f5da6b3d6e09.png">

For instance, to execute the ‘Open File’ command, the user can trigger the command palette command and start typing ‘Open’, which shall filter the list of available commands down, such that the ‘Open File’ entry is visible. The user shall be able to select that entry using the cursors or the mouse and execute it by either clicking on it or pressing enter.

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/pull/471
