### ISSUE TITLE
[Question] Theia IDE in Che server

### ISSUE THREAD

**Issue by BoykoAlex** [theia-ide/theia#2133]
Looks like the primary use case for having Theia IDE in the cloud is pairing it up with Che server workspace. Thus instead of Orion IDE UI Theia IDE would be used.
I saw Theia (Docker) stack and Theia (OpenShift) stack... 
Used Theia (Docker) stack to create a workspace - saw Theia IDE UI which is awesome!-)
If I to deploy Che server in K8s I suppose I'd need Theia (K8s) which isn't available... Is that correct?

Is there a way to install more Theia extensions while I'm running it next to a Che workspace (in a docker container?)? It seems to only show installed extensions but not the extensions i can install...

**Comment by gorkem** [comment]
This is probably more appropriate question for Che project but here it goes. You probably do not need a Theia(k8s) stack Theia(openshift) stack can be enough. I have not really tested it myself but it should be enough @ashumilova @benoitf have you tried? If it does not work please report it on the Che issues. 

There is an interim way from Dashboard to install Theia plugins. When you are editing a workspace you should notice a `Tools` tab which enables you to install Theia plugins. We are working on a better way to get plugins to a workspace, so stay tuned.

**Comment by kittaakos** [comment]
Please reopen if required.
