### ISSUE TITLE
[plug-in] Limit UI-contributions until they are ready

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2140]
Could we remove the empty plug-in view? 
At least until there is something a user could do, it gives a bad impression otherwise.

**Comment by svenefftinge** [comment]
I would like to remove the extensions UI from the initialized layout, too.  Objections?

**Comment by gorkem** [comment]
@benoitf can we quickly put a something that retrieves a list of plugins that we have lying around. I think we can just start with a list of plugins on a JSON file hosted on a GH repo. Now that we have the plugin APIs having the UI would encourage the adoption.

**Comment by benoitf** [comment]
@gorkem I think yes we can add actions from the widget. There is an action through command palette so we may add a button as well.
@svenefftinge and to the answer on having many UI initialized at startup, yes we can remove them. (I think plugin was inspired from extension on that part).
