### ISSUE TITLE
Incorrectly displaying active sidebar menu item

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2145]
There is an issue when selecting the active sidebar menu item. 
Most active menu items display correctly, except for **Git** and **Plugins** (and possibly more). 

![menu-problem](https://user-images.githubusercontent.com/40359487/41680298-097d69b2-749f-11e8-8054-d4765176bfad.gif)

**Comment by svenefftinge** [comment]
That happens when a widget doesn't set focus on any element when activated.
The git widget should focus the commit message field.

**Comment by jbicker** [comment]
At least for the git widget https://github.com/theia-ide/theia/pull/2129 should fix it.

**Comment by svenefftinge** [comment]
For plugins it can't, but I removed the default opening. Consider this closed.
