### ISSUE TITLE
[git] Queue git operations

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2146]
We should queue git operations so we don't run into `.lock`-file-exists situations.

Reproducible by staging many files one after the other quickly.

**Comment by kittaakos** [comment]
This should be related: https://github.com/theia-ide/theia/issues/1769.

After running any Git commands, we run an `ensureSync` on the repository that creates the `index.lock` file. We could try to fix that before getting into any sophisticated queueing. What do you think?

**Comment by svenefftinge** [comment]
I don't think it happens because of git status, but because of quickly doing several git operations one after the other.

**Comment by svenefftinge** [comment]
> Reproducible by staging many files one after the other quickly.

If I do that slowly I don't see the error.

**Comment by kittaakos** [comment]
We receive the `index.lock` change multiple times in the same message:
```json
{
  "content": "{"jsonrpc":"2.0","method":"onDidFilesChanged","params":{"changes":[{"uri":"file:///Users/akos.kitta/git/eclipse.jdt.ls/.git/index.lock","type":1},{"uri":"file:///Users/akos.kitta/git/eclipse.jdt.ls/.git/index.lock","type":2}]}}",
  "id": 2,
  "kind": "data"
}
```

![screen shot 2018-07-09 at 11 12 31](https://user-images.githubusercontent.com/1405703/42441845-696e8d50-8369-11e8-960f-b0caf50eb694.jpg)

**Comment by kittaakos** [comment]
Is this still valid? Can we close this issue, @svenefftinge?

With #1769, we use the `--no-optional-locks` Git option for each `git status` command. It is supported if the Git version is `2.15.0+`. With #2851, the embedded Git version is `2.17.1`, so it should be supported for everyone by default.

**Comment by svenefftinge** [comment]
We can reopen it if the change was not enough.
