### ISSUE TITLE
[quick command] Support `isToggled`

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2150]
A toggle feature has been introduced for commands. I needs to be reflected in the command palette, too.

One need to add method below to CommandQuickOpenItem.

    getIconClass() {
        const toggleHandler = this.commands.getToggledHandler(this.command.id);
        if (toggleHandler && toggleHandler.isToggled && toggleHandler.isToggled()) {
            return `fa fa-check`;
        }
        return super.getIconClass();
    }
Also, I stumbled over an odd css property that should be removed:
https://github.com/theia-ide/theia/blob/master/packages/monaco/src/browser/style/index.css#L36

**Comment by kittaakos** [comment]
Can we close this?

**Comment by svenefftinge** [comment]
yes
