### ISSUE TITLE
Use `cmd+shift+o` for `Go To Symbol in File...` instead of opening the outline

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2154]
Currently the outline gets opened and it is not very useful to look up symbols fast.

**Comment by Rijul5** [comment]
@akosyakov - Hope you are doing good! Is it possible to have symbol information for the selected tree node (model element) of outline-view?

I have highlighted this question in issue 1817 [https://github.com/theia-ide/theia/issues/1817](url) also. Please help me in understanding how we can associate a command in my frontend extension to carry the symbol information on the selected model element of outline view.

**Comment by Rijul5** [comment]
@akosyakov - Thank you for your reply. At this stage, I just want the symbol location of the selected model element. Therefore, can you please suggest how can I access the symbol location of the selected model element in Outline-View. 

![image](https://user-images.githubusercontent.com/32622151/42857798-7be0fa2a-8a19-11e8-849e-890b5eaa225a.png)
As shown in the above image, when I click on "Generate Diagram" command selecting one model element, i should get the symbol location of the selected model element.

Hence, please guide how can I achieve this in my command handler. Below is the structure of my command's handler.

@injectable()
export class DiagramCommandContribution implements CommandContribution {

    constructor(
        @inject(MessageService) private readonly messageService: MessageService,
        @inject(EditorManager) protected readonly editorManager: EditorManager,
        @inject(OpenerService) protected readonly openerService: OpenerService,
    ) { }

    registerCommands(registry: CommandRegistry): void {
        registry.registerCommand(DiagramCommand, new OpenInDiagramHandler(this.messageService, this.editorManager, this.openerService))
    }
}

export class OpenInDiagramHandler implements CommandHandler {

    constructor(@inject(MessageService) private readonly messageService: MessageService,
        protected readonly editorManager: EditorManager,
        protected readonly openerService: OpenerService) {
    }
    execute(...args: any[]) {
 .......................
.......................
}
