### ISSUE TITLE
React typings missing from v.Next

### ISSUE THREAD

**Issue by dunnry** [theia-ide/theia#2157]
There appears to be a problem with the latest version of Theia (next) and extensions. The issue is in theia/core with react dependency. You can repro this by doing a clean git pull from @svenefftinge 's example Xtext DSL extension (https://github.com/theia-ide/theia-xtext). Delete the yarn.lock file and do a 'yarn install'. The following errors will occur:

```
$ tsc && yarn run copy-ls
lerna ERR! ../node_modules/@theia/core/lib/browser/status-bar/status-bar.d.ts(1,23): error TS2688: Cannot find type definition file for 'react'.
lerna ERR! ../node_modules/@theia/core/lib/browser/status-bar/status-bar.d.ts(57,25): error TS2503: Cannot find namespace 'JSX'.
lerna ERR! ../node_modules/@theia/core/lib/browser/status-bar/status-bar.d.ts(60,53): error TS2503: Cannot find namespace 'JSX'.
lerna ERR! ../node_modules/@theia/core/lib/browser/widgets/react-widget.d.ts(1,23): error TS2688: Cannot find type definition file for 'react'.
lerna ERR! ../node_modules/@theia/core/lib/browser/widgets/react-widget.d.ts(2,24): error TS7016: Could not find a declaration file for module 'react'. 'C:/src/theia-xtext/node_modules/react/index.js' implicitly has an 'any' type.
lerna ERR! Try npm install @types/react if it exists or add a new declaration (.d.ts) file containing declare module 'react';
```

**Comment by AndrienkoAleksandr** [comment]
+1

**Comment by AndrienkoAleksandr** [comment]
Seems @types/react https://github.com/theia-ide/theia/blob/master/packages/core/package.json#L80 should be moved from "devDependencies" to the "dependencies"

**Comment by kittaakos** [comment]
> Seems https://github.com/theia-ide/theia/blob/master/packages/core/package.json#L80 should be moved from "devDependencies" to the "dependencies"

Yes. And `@types/react-dom` too.
