### ISSUE TITLE
[electron] wasm support issue

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2170]
It seems like the current Electron renderer is not supporting Web Assembly (following the textmate coloring patch using wasm).

Is it just a matter of updating Electron ?

**Comment by akosyakov** [comment]
Electron supports wasm since 1.7.x. We use 1.8.x. Maybe it should be configured somehow or API a bit different?

**Comment by marechal-p** [comment]
Yes indeed, my bad. The problem seems to come from a call to `fetch` on a `file:xxx` uri, not because of wasm non-support.
