### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by rafaelwand** [theia-ide/theia#2174]
When building, I get the following error:
error /home/theia/node_modules/nsfw: Command failed.

OS version: Ubuntu 18.04
yarn version: 1.7.0
nvm version: 0.33.11
node version: v8.11.3

The build log is attached.
[BuildError.txt](https://github.com/theia-ide/theia/files/2131719/BuildError.txt)

**Comment by AlexTugarev** [comment]
@rafaelwand you need some basic build tools installed on that machine. Could you try with `sudo apt-get install build-essential`?

**Comment by AlexTugarev** [comment]
@rafaelwand if that works, we should add it to docs: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#linux

**Comment by rafaelwand** [comment]
Yes. It works.
