### ISSUE TITLE
[plug-in] allow to create a Disposable object from disposable collections from plug-in API 

### ISSUE THREAD

**Issue by benoitf** [theia-ide/theia#2184]
User could call something like

```
const composedDisposable = Disposable.from(disposable1, disposable2, disposable3);
```
 and it will return a composed Disposable

**Comment by AlexTugarev** [comment]
Would the `DisposableCollection` work, too? From `@theia/core/lib/common/disposable`

**Comment by benoitf** [comment]
@AlexTugarev on implementation side, probably yes.
