### ISSUE TITLE
[plug-in] Introduce the plugin API for terminal

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [theia-ide/theia#2186]
The new plugin model should contain API for creating and accessing terminal in Theia. The task includes following items to be done:
- [x] define the API of the terminal operations
- [x]  document the API
- [x]  develop the defined API
- [x]  test it on the sample plugin

**Comment by dkuleshov** [comment]
@AndrienkoAleksandr Hi, I see that the description says that the API is documented, could you please point me where I can find the documentation, because I can not find it. I'm also wondering where I can find the sample plugin the API was tested upon. Thank you.

**Comment by AndrienkoAleksandr** [comment]
https://github.com/theia-ide/theia/blob/da1e383406ea77ddd9350e4d96dc145b8af7c546/packages/plugin/API.md Terminal section.

**Comment by AndrienkoAleksandr** [comment]
About samples:
https://github.com/theia-demo-plugins/theia-frontend-plugin/blob/master/src/terminal.ts

**Comment by AndrienkoAleksandr** [comment]
Terminal api is quite limited. It's the same like in the vscode. If you want to use terminal widget for some advanced feature, you should write extensions and use extension api, and maybe improve current api.

**Comment by dkuleshov** [comment]
Understood, thank you
