### ISSUE TITLE
Logo design for the application

### ISSUE THREAD

**Issue by richardbmx** [theia-ide/theia#2189]
@akosyakov  Hi, I see that you are requesting a [logo design for the application](https://opensourcedesign.net/jobs/jobs/2017-09-03-design-a-logo-for-theia-the-open-source-js-based-ide-framework).  I am a graphic designer and I would like to make a logo for you if you wish..

Here you can see part of my work (https://steemit.com/@richardbmx)

**Comment by akosyakov** [comment]
@richardbmx we already have a logo, thank you
