### ISSUE TITLE
Missing php autocomplete in theia-app

### ISSUE THREAD

**Issue by pwFoo** [theia-ide/theia#2191]
Hi,

I tested [theia-apps](https://github.com/theia-ide/theia-apps) in docker but it looks like php autocomplete is missing? Autocomplete just works for locale code (class names, variables, ...), but with an empty file no completition for key words (public, class, ...) and methods (file_get_contents, ...).

Am I missing some settings or needed extensions to get it work?

**Comment by akosyakov** [comment]
Monaco supports only basic coloring for php by default. One have to create an extension for php. @meysholdt i remember you created something. Is it published?

**Comment by marechal-p** [comment]
Like @akosyakov said, I think it would take an extension registering a Language Server (LS) for PHP, such as [this one](https://github.com/felixfbecker/php-language-server) maybe.

@pwFoo auto-completion features that require some understanding of a language, like builtin names require a LS for Theia to operate optimally when editing source files. The LS is also the one allowing you to navigate the code (find references of a function, "go to definition", etc...)

**Comment by meysholdt** [comment]
@akosyakov I just published and moved it here: https://github.com/theia-ide/theia-php-extension

@marechal-p yes, it's a Theia extension for the php language server from @felixfbecker.

**Comment by svenefftinge** [comment]
Closing it. Subsequent issues should be raised over at https://github.com/theia-ide/theia-php-extension
