### ISSUE TITLE
[plugin-ext][electron] `setImmediate` is undefined

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2201]
I have been running `master` in Electron, and it seems like there is a problem from `plugin-ext`'s sources:
```
rpc-protocol.ts:239 Uncaught (in promise) ReferenceError: setImmediate is not defined
    at RPCMultiplexer.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCMultiplexer.send (rpc-protocol.ts:239)
    at rpc-protocol.ts:140
    at <anonymous>
```
Not really sure what is the cause, it seems like this is code run inside webworkers ?

**Comment by marechal-p** [comment]
TIL: https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate#Browser_compatibility

**Comment by benoitf** [comment]
former issue as well https://github.com/eclipse/che/issues/9767
