### ISSUE TITLE
[Tree] Root node does not get selected when navigating up (resp. left)

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#2204]
![selectionbug](https://user-images.githubusercontent.com/28291421/41971863-2d0bff62-7a10-11e8-9360-2b984c543208.gif)

**Comment by akosyakov** [comment]
@jbicker could you try to reproduce? I believe it was fixed by recent changes from @kittaakos

**Comment by jbicker** [comment]
Looks good now. I'll close this.
