### ISSUE TITLE
[key bindings] Several "WARN: Collided keybinding is ignored"

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2209]
Theia master as of (603fe22), Electron example.

[2018-06-27T13:47:08.892Z]  WARN: Theia/28010 on elxajvlvvz1: (logger=root)
    Collided keybinding is ignored;  [ '{"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}',
      ' collided with ',
      '{"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}' ]

[2018-06-27T13:47:08.894Z]  WARN: Theia/28010 on elxajvlvvz1: (logger=root)
    Could not register keybinding:
      {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
    Error: "f7" is in collision with something else [scope:0] []

[2018-06-27T13:47:08.894Z]  WARN: Theia/28010 on elxajvlvvz1: (logger=root)
    Collided keybinding is ignored;  [ '{"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}',
      ' collided with ',
      '{"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}' ]

[2018-06-27T13:47:08.896Z]  WARN: Theia/28010 on elxajvlvvz1: (logger=root)
    Could not register keybinding:
      {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
    Error: "shift+f7" is in collision with something else [scope:0] []

**Comment by marechal-p** [comment]
Duplicate: https://github.com/theia-ide/theia/issues/1888
