### ISSUE TITLE
ERROR: Cannot find a service for the path: /services/plugin-ext [] (logger=root)

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2210]
Theia master as of (603fe22), Electron example.

[2018-06-27T13:47:08.567Z] ERROR: Theia/28010 on elxajvlvvz1: Cannot find a service for the path: /services/plugin-ext [] (logger=root)

**Comment by MarkZ3** [comment]
Please note that you have to use a different command now to see the logging, see https://github.com/theia-ide/theia/issues/2344

**Comment by lmcbout** [comment]
Close the PR, and re-assign to the issue #2344.

**Comment by MarkZ3** [comment]
Why? Is the issue not still there when logging is present?

**Comment by lmcbout** [comment]
I was only looking at the electron loggings, I made a mistake when I submitted my PR, I realized there was an issue just for the logging (issue #2344 ), so this issue is still there

**Comment by lmcbout** [comment]
@benoitf Question:
When starting electron, I see in the logging area the following: "root ERROR Cannot find a service for the path: /services/plugin-ext "
This comes from the plugin-ext/src/common/plugin-protocol.ts
Is it something forgotten or not implemented yet ? 
I see also the code for the hosted section handling the browser , node and node-electron , but in the main section, I see browser and node, but not node-electron section!!

**Comment by kittaakos** [comment]
It has another side-effect, the backend crashes when we set a new workspace root. See here: https://github.com/theia-ide/theia/pull/3202#issuecomment-431079431

I try to reproduce and fix the issue as it blocks #3202.

(I am CCing @marcdumais-work, just to make sure he is aware of this problem too.)

**Comment by kittaakos** [comment]
@benoitf, any updates on https://github.com/theia-ide/theia/issues/2210#issuecomment-406384664?

This still happens with a9cf7d8d19d3218a85373adbc2e0c1d1dbddef1c.

**Comment by benoitf** [comment]
@kittaakos I never saw this error or was able to reproduce it

**Comment by kittaakos** [comment]
@benoitf, thanks! To make sure we are on the same page; it happens with the electron example. Can you please confirm, that the entire plug-in system works in both the browser and electron?
