### ISSUE TITLE
[terminal] Copy/paste on keyboard doesn't work in terminal

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2216]
Theia master as of (603fe22), Electron, browser example. Ubuntu.

1. Open the terminal
2. Select some text and try to Ctrl+Shift+C and Ctrl+Shift+V.
Nothing happens.

There is also no context menu to do it.
In the browser, I also haven't been able to do it with the keyboard but there is the context menu. Also, Ctrl+shift+C opens the dev tools in Firefox...

**Comment by elaihau** [comment]
This one is related to https://github.com/theia-ide/theia/issues/2171

**Comment by kittaakos** [comment]
It should be possible with https://github.com/theia-ide/theia/pull/3469.

Please reopen if needed.
