### ISSUE TITLE
[Problems] Allow deleting markers

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2219]
The problems view should allow to delete individual, multiple markers using the context menu.

**Comment by jbicker** [comment]
Another possibility would be a hover button as in search result tree. 
@svenefftinge, what do you think?
![deletetreenodes](https://user-images.githubusercontent.com/28291421/42019138-9bc54e46-7ab4-11e8-9213-76ec81e829e5.gif)

**Comment by kittaakos** [comment]
Duplicates?
 - [[markers] add a way to prune stale markers](https://github.com/theia-ide/theia/issues/1031)
 - [Be able to clear error markers](https://github.com/theia-ide/theia/issues/1352)

If so, please make sure to close them when closing this.

**Comment by svenefftinge** [comment]
duplicate of #1352.
