### ISSUE TITLE
"rename" shows pointless warning

### ISSUE THREAD

**Issue by meysholdt** [theia-ide/theia#2241]
In the file view, after pressing F2, the rename-dialog shows the error "A file with this name already exists.".

While this is technically correct because the text filed is pre-populated with the former file name, it's pointless, because it's accusing the user of something the user isn't responsible for.

Expectation: The validation for name conflicts shouldn't run until after the first text modification the user has applied to the text field. 

Disabling the "ok" button, however, makes sense for all cases in which no rename could happen.

Also, it makes sense to label the button "rename" instead of "ok".

**Comment by jbicker** [comment]
Duplicates https://github.com/theia-ide/theia/issues/639
