### ISSUE TITLE
How to trigger close method of a widget on save

### ISSUE THREAD

**Issue by AhmetTanakol** [theia-ide/theia#2267]
Hello,

I have a React application that is rendered into a custom widget's node. Right now, I can save the data that resides in my component's store into the file when the user closes the JSON file. I want to trigger the same function that I call in `close()` method of `Widget` via save. The function that I am using in `close()` method is defined in my custom open handler. I pass this function as an argument when I create an instance of my widget. I checked the source code but I am not sure how to use save command to trigger this action. Could you please give some hints? Thank you

MyOpenHandler
```js
 open(uri: URI, options?: OpenerOptions): MaybePromise<object | undefined> {
 // Some code ...
 const customWidget = new CustomWidget(store, MyComponent, this.saveData(resource));
 // Some code ...
 }
 

  private saveData = (resource: Resource) => (data: Object): void => {
    if ( resource.saveContents !== undefined ) {
      resource.saveContents(JSON.stringify(data, null, 2), { encoding: 'UTF-8' });
    } else {
      console.warn('cannot save');
    }
  }
```

MyWidget
```js
  close() {
    this.saveData(getData(this.store.getState()));
    super.close();
  }
```

**Comment by akosyakov** [comment]
A widget should implement `Saveable` to support save-lifecycle: https://github.com/theia-ide/theia/blob/b9941f63df57fb2876b8d74dfe4f47fcfc674048/packages/core/src/browser/saveable.ts#L23-L28

For such widget, `close` method will be augmented to call `save` method as well: https://github.com/theia-ide/theia/blob/b9941f63df57fb2876b8d74dfe4f47fcfc674048/packages/core/src/browser/saveable.ts#L73-L91

**Comment by AhmetTanakol** [comment]
Thank you, the problem that I am having is I can't get the `saveable` object. Since I don't directly change the data of my JSON file,  `saveable` always stays undefined. Is there a way to set manually this saveable object?

https://github.com/theia-ide/theia/blob/b9941f63df57fb2876b8d74dfe4f47fcfc674048/packages/core/src/browser/saveable.ts#L61

**Comment by akosyakov** [comment]
> the problem that I am having is I can't get the saveable object

I am not sure that I get you right. Your widget should implement `Saveable` interface.

In your place, I won't use `Resource` to work with a file but `MonacoEditorModel` that implements `Saveable`. Then your widget should implement `SaveableSource` and return an instance of `MonacoEditorModel` as saveable. This model also will be shared with an editor so all changes will be immediately reflected. You can have look at https://github.com/TypeFox/ecf2018-theia-workshop/blob/0207163259ace9cc69202be18d94a9f8b27a5518/jsonschema-form-extension/src/browser/referenced-model-storage.ts#L8 and https://github.com/TypeFox/ecf2018-theia-workshop/blob/exercise-3/jsonschema-form-extension/src/browser/jsonschema-form-view.tsx to learn how to create one, modify and react to changes.

**Comment by AhmetTanakol** [comment]
Thank you, I will check the example
