### ISSUE TITLE
[navigator] add a toggle to sync the editor and navigator selections

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#227]

**Comment by akosyakov** [comment]
For the beginning, we could always reveal a file selected in the editor in the navigator as it is done in VS code. But personally, it is annoying me a lot. I like how it is done in Intellij more: the toggle is hidden under the navigator settings menu and the navigator tool panel has a button to select the source.

**Comment by mmorhun** [comment]
Done
