### ISSUE TITLE
[git] Commit message textArea does not resize correctly on browser refresh

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2278]
Steps to reproduce:
 - Add a commit message: `a\n\b\nc`.
 - Activate `Files`.
 - Set the focus on an editor.
 - Refresh the browser.

This does not happen when the `Git` is active and then the user refreshes the browser.

Also: we must not restore the validation error/warnings when the commit message `textArea` is empty. Otherwise, the following happens.

 - Active the `Git` widget.
 - Press `Commit`.
 - Got the error which is expected.
 - Refresh the browser.
 - The error is still there, it should not be.

**Comment by kittaakos** [comment]
When refreshing the browser, we do not hit the `storeState` in the `Git` widget when it is not the active one. This defect seems to be a generic issue with the `storeState`/`restoreState`. Related: https://github.com/theia-ide/theia/issues/1316

I can work around this, by storing the state each time there is a change in the `textArea`. What's your take on that @AlexTugarev?

**Comment by svenefftinge** [comment]
But isn't #1316 specific to the tree widget?

**Comment by kittaakos** [comment]
As I see it does not matter whether it is a tree or not; it applies to the stateful widgets in general. I will come up with a quick fix for the commit message (`textArea`) issue in short.
