### ISSUE TITLE
Should hide/disable menu items applicable to workspaces when no workspace is present

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2287]
General issue with Theia to hide/disable menu items which are in the context of a workspace when no workspace is currently present. 

Menu items such as:

- `File >  Open Workspace Preferences`
- `File > Save`
- `File > Save All`
- `Edit > Cut`
- `Edit > Copy`
- `Edit > Paste`
- `Edit > Search in Workspace`
- etc.

do not have meaning or value when no workspace is present, and thus should be hidden or disabled to avoid confusion.

**Comment by akosyakov** [comment]
a dup of https://github.com/theia-ide/theia/issues/446?
