### ISSUE TITLE
Save option should only be visible when the current editor file is dirty

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2288]
Ideally, we should toggle the `Save` menu option's visibility based on if the current editor file is dirty or not. In addition, the `Save All` menu option should only be visible if there is any dirty file in the workspace.

**Comment by akosyakov** [comment]
Hi, could you specify what is your target `browser` or  `electron`? For `electron` is a known issue, since there is no way to dynamically update menu items. For the browser, it will be a bug.

**Comment by vince-fugnitto** [comment]
`vscode` behaves the same way having `save` and `save all` selectable at all times.
closing unless there is a real issue in the future with end-users.
