### ISSUE TITLE
[plug-in] Implement inspect configuration

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [theia-ide/theia#2289]
Implement inspect configuration: 
```theia#WorkspaceConfiguration#inspect<T>(section: string)```:
https://github.com/theia-ide/theia/blob/v0.3.16/packages/plugin/src/theia.d.ts#L2838

https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/plugin/preference-registry.ts#L138

**Comment by AndrienkoAleksandr** [comment]
Seems related or depends on: https://github.com/theia-ide/theia/pull/2117

**Comment by evidolob** [comment]
Need for VS Code XML extension

**Comment by akurinnoy** [comment]
depends on https://github.com/theia-ide/theia/issues/3540

**Comment by akosyakov** [comment]
@benoitf @evidolob @akurinnoy Could we provide an implementation without support of multi roots for now?

**Comment by akurinnoy** [comment]
@akosyakov I believe, yes

**Comment by akosyakov** [comment]
@akurinnoy Could you look into it this week? If no, please ping me i may have time to look at it tomorrow.

**Comment by akurinnoy** [comment]
This issue is in our sprint plan and someone else could handle it.
@evidolob @AndrienkoAleksandr WDYT?

**Comment by evidolob** [comment]
Yes, I can handle it
