### ISSUE TITLE
Error thrown when attempting to search with no workspace present

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2297]
Theia throws an error from the `Search Widget` when a search is performed without a current workspace. Instead of throwing an error, Theia should instead catch the error and display it as a meaningful message to end users. (ex: **Please open a workspace or file(s) before searching**)

![no-workspace-root](https://user-images.githubusercontent.com/40359487/42380166-f3a25bf8-80fa-11e8-8174-2b7a456eace2.gif)

**Comment by marcdumais-work** [comment]
Another option would be not to permit using "search in workspace" when no workspace is open.
