### ISSUE TITLE
[editor] Renaming a file should rename a corresponding editor

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#230]
Consider also what to do with an underlying file resource and monaco model.

**Comment by hexa00** [comment]
Note if #899 works with nsfw and nsfw provies rename support this may be easier to do than before from the FS change.

**Comment by slemeur** [comment]
Just updating the issue, this issue is still present (as today).

**Comment by epatpol** [comment]
I'd like to tackle this one, so looking at #582 and the old comments I'm still not sure what we want here. Would how vscode do things be okay? i.e

* Rename is made from within Theia
    * If associated editor has unsaved content
        * Rename the editor but keep the unsaved content
    * Else 
        * Rename the editor 
* Rename is made from outside Theia (Filesystem)
    * If associated editor has unsaved content
        * Rename the editor (add *deleted from disk* suffix to the label)
    * Else 
        * Close the editor with the old name

**Comment by lmcbout** [comment]
Just an observation here, what would happen if the "auto-save is on" , and the file is moved to a new location from outside Theia,:
- would it update the file at the new location?
- would it create a new file at the old location even if the initial file is moved elsewhere? --> now we would have two different files at two locations.
Same apply to the rename, we would have old + new file under the same folder, but which one has the latest contents?

**Comment by epatpol** [comment]
@lmcbout I think the same thing would happen as defined in the workflow I wrote just above. In your case, if autosave kicks in before any rename, you would enter the `Else` branch above, where the editor is closed/renamed depending on if it was an external or internal event. However, if autosave kicks in *after* a rename, then you would enter the first `if` condition above, which means it would either autosave your unsaved content to the new file, or recreate the old file.

Last case where we auto-recreate the last file could be discussed further, maybe it wouldn't autosave in that case? Anyway, as a first step we could do above and deal with that corner case later imo.

**Comment by lmcbout** [comment]
@epatpol That was just some observation we should consider. One thing, when a user is editing "File1" and under the hood the file is rename "File B", I think the user would be surprise to see  editing in a file and the save occurs under another file !!!

**Comment by epatpol** [comment]
It only saves under another filename if he had unsaved content, and then the title of the editor would clearly say it's *deleted from disk*, otherwise it saves to the same file. VScode does it this way and I believe that should suit most users.
