### ISSUE TITLE
Some files has missing syntax highlighting

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#2306]
Usually some of this files in VSCode has Syntax Highlighting already:

- HTML
- Markdown
- Dockerfiles (unsure)

Theia does not have any syntax highlighting of sorts.

**Comment by marcdumais-work** [comment]
Hi,

What have you been testing-with? With the example application built from master, there should be highlighting for at least HTML, from the list above. 

This was added recently, along with coloring for a few other languages, in the new ```@theia/textmate-grammars``` extension. Markdown should be covered but maybe is not working correctly -  I see barely any color; except in the label part of links:
![image](https://user-images.githubusercontent.com/25749063/42413031-28b8a7fc-81e6-11e8-8290-9ba1d45f29af.png)

Dockerfile is not covered yet, I think. 

```@theia/textmate-grammars```  has not released in ```latest``` version on npm, but is available as ```next```. It has also not been added yet to the docker images in ```theia-ide/theia-apps```.

**Comment by marcdumais-work** [comment]
I see that ```.yml``` files have some coloring but not a lot - probably a bug. Also another important file type is not covered yet: JSON.

**Comment by sr229** [comment]
@marcdumais-work I'll try updating my image to reflect this, but #2307 seems to be recurrent

**Comment by svenefftinge** [comment]
> I see that .yml files have some coloring but not a lot - probably a bug.

This is fixed now. Closing, as the rest was theia-apps related.
