### ISSUE TITLE
Frontend App not working in Docker - Circular Dependency problem

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#2307]
Currently, I used the full `package.json` from theia-ide/theia-apps for my Theia image, and this happened both at latest and next

![image](https://user-images.githubusercontent.com/14976516/42413045-36788924-824b-11e8-9c9e-02d09840c8a5.png)

**Comment by sr229** [comment]
Taking a look at logs, this seems to be a problem with the extensions, preferrable something that refers about `electron.js`

**Comment by marcdumais-work** [comment]
Please re-open this issue in the ```theia-ide/theia-apps``` repo.

**Comment by marcdumais-work** [comment]
I think the issue is caused by this: https://github.com/theia-ide/theia/issues/2307#issuecomment-403230229
