### ISSUE TITLE
Does theia support debugging?

### ISSUE THREAD

**Issue by dclong** [theia-ide/theia#2308]
Is debugging support in the plan?

**Comment by akosyakov** [comment]
yes, it is WIP, @tolusha is on it: https://github.com/theia-ide/theia/commits/vscode-debug-protocol

**Comment by squarti** [comment]
WIP 

https://cloud.ibm.com/devops/pipelines/5d3bcd8d-a050-4493-b910-bbe880ae2619/db9e0649-d1ce-4eff-a8b9-f2ff30721aa9/d2ea3133-97de-47ce-97a6-ff1e5ce4b4f8?env_id=ibm:yp:us-south

https://cloud.ibm.com/devops/pipelines/5d3bcd8d-a050-4493-b910-bbe880ae2619/e78f45ba-049f-43de-ba6f-d7e019db23d0/705b3928-c1c5-448b-aa23-cbc22874d394?env_id=ibm:yp:us-south
