### ISSUE TITLE
[Java] Outline is one change behind

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2309]
Somehow for Java the outline reflects the previous state instead of the current one.

**Comment by kittaakos** [comment]
It is still present in 68ff5f84.

![screencast 2018-10-11 16-55-37](https://user-images.githubusercontent.com/1405703/46813209-9c7be380-cd76-11e8-8b16-9a4deb54e691.gif)

**Comment by kittaakos** [comment]
I have found a related fix in JDT LS: https://github.com/eclipse/eclipse.jdt.ls/pull/795

I built a Java LS locally and verified the outline behavior. It worked:

![screencast 2018-10-12 08-05-36](https://user-images.githubusercontent.com/1405703/46850930-08e9f780-cdf6-11e8-950c-aabf37b4af37.gif)

I will [publish a new JDT LS from the fork](https://github.com/kittaakos/eclipse.jdt.ls-gh-715).

**Comment by kittaakos** [comment]
Fixed with https://github.com/kittaakos/eclipse.jdt.ls-gh-715/commit/56e26304c44e68f45a65dcfd956b7ff3f73263ec.
