### ISSUE TITLE
[git] Multiple Git status received when changing a file a single time

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2311]
According to the Chrome debugging tools, the Git status is received three times by the client after performing a single character change in a file:

![screen shot 2018-07-09 at 11 09 09](https://user-images.githubusercontent.com/1405703/42441575-cadd65d0-8368-11e8-9282-325229f65a4e.jpg)

**Comment by akosyakov** [comment]
Do you know how to reproduce it? After to open one file and do a single change but I can see only one status update. What is the repo? Which widgets are opened?

**Comment by kittaakos** [comment]
I have a few Java sources opened in the editor, and I have changed one of them.
I have auto-save `false,` if that matters.

**Comment by kittaakos** [comment]
I cannot reproduce it anymore. Please reopen if still occurs.
