### ISSUE TITLE
[search] Issues with styles

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2317]
The replace toggle should have a fixed width, otherwise:

![2018-07-10 09 17 51](https://user-images.githubusercontent.com/914497/42495204-b9f2b508-8422-11e8-82ac-04ce9a6d8f92.gif)

Search input field should scale down, otherwise you might miss the option buttons:

![2018-07-10 09 18 20](https://user-images.githubusercontent.com/914497/42495248-d770c746-8422-11e8-8dfe-5c19d2787136.gif)

cc. @jbicker

**Comment by jbicker** [comment]
> The replace toggle should have a fixed width
Hm, actually it has a fixed width already. Works well in Chrome. For some reason Firefox doesn't care about it.

**Comment by jbicker** [comment]
> Search input field should scale down, otherwise you might miss the option buttons

I would suggest that we have to prevent at some point to scale down the widget if we want to keep the buttons in sight.
If not at some point the buttons will be hidden because it makes no sense to diminish the search input so far.

**Comment by AlexTugarev** [comment]
@jbicker, here is a repro with latest master in Chrome:

![2018-07-12 10 37 45](https://user-images.githubusercontent.com/914497/42622045-b06357ec-85bf-11e8-8257-0e7120dfd5ea.gif)

**Comment by jbicker** [comment]
Yeah, figured that just out. min-width will fix it.

**Comment by AlexTugarev** [comment]
> > Search input field should scale down, otherwise you might miss the option buttons
> I would suggest that we have to prevent at some point to scale down the widget if we want to keep the buttons in sight.
> If not at some point the buttons will be hidden because it makes no sense to diminish the search input so far.

Not sure, I got this, but can you just compare with vscode?

**Comment by jbicker** [comment]
I did. There it stops at some point.

**Comment by jbicker** [comment]
FYI: I will fix this after https://github.com/theia-ide/theia/pull/2301 is merged
