### ISSUE TITLE
Get rid of hardcoded 3000 port

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#233]
It is impossible to start apps on different ports right now.

**Comment by Nebiroth** [comment]
I can generate any port number that doesn't require root privilege every time the app is launched, but does that port number have to be passed to endpoint.ts to be able to stay connected with the backend?

**Comment by hexa00** [comment]
From endpoint.ts:
```typescript
    protected get host() {
        return location.host || "127.0.0.1:3000"
    }
````
So yes... I guess it also needs to be handled  by examples/browser/webpack.config.js  or it's prod equivalent...

**Comment by akosyakov** [comment]
`location.host` takes care about the browser, but in electron there is no location API
