### ISSUE TITLE
[keymaps] Extra notifications at editing keymaps.json

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#2336]
Notifications are displayed many times at editing keymaps.json
https://youtu.be/bvfU9q_hwxE

**Comment by AlexTugarev** [comment]
Maybe we should debounce the event handler here: https://github.com/theia-ide/theia/blame/1e3f8dbb0915cc8ee2f47ddffa1f7e597cb3f992/packages/keymaps/src/browser/keymaps-service.ts#L58
