### ISSUE TITLE
[electron] No log in the terminal anymore

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2344]
Using Theia master as of a5f7852. Electron example.
If I start it with "yarn run start", there is only a couple of lines outputted:
```
$ yarn run start
  yarn run v1.3.2
  $ theia start
```
However, this is not normal because a lot more things are usually logged. You can work around this by launching with the electron binary directly:
```
$ ../../node_modules/.bin/electron ./src-gen/frontend/electron-main.js
Starting server worker...
Server worker has been started. [ID: 1 | PID: 23519]
Server worker is ready to accept messages. [ID: 1 | PID: 23519]
root INFO Theia app listening on http://localhost:42139.
```
But this is not ideal and inconsistent with the browser example.

**Comment by kittaakos** [comment]
Can we close this, @MarkZ3? Thanks!

**Comment by vince-fugnitto** [comment]
I believe this issue can be closed, output is displayed in electron when testing 60dcb33.  
Please re-open the issue if it's not the case.
