### ISSUE TITLE
[textmate] some ts code is weirdly colored

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2358]
try with https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/editorWorkerServiceImpl.ts

**Comment by marechal-p** [comment]
It seems to come from the json casting.

Some illustrations:

![image](https://user-images.githubusercontent.com/14182238/42962990-020445e2-8b61-11e8-8f22-219c648a2491.png)
![image](https://user-images.githubusercontent.com/14182238/42963012-14ae841e-8b61-11e8-884e-8e29958f0951.png)
