### ISSUE TITLE
Extension build time/speed

### ISSUE THREAD

**Issue by jbremmer** [theia-ide/theia#2362]
The build time for extension with theia is very long:

```extension-folder/browser-app/yarn watch```

takes about that much
```
Version: webpack 4.15.1
Time: 63034ms
```

Not sure if I do everything correctly, I've used ```yo theia-extension``` to scaffold plugin.

Is this normal or is there way around this to speed up my build times?

**Comment by akosyakov** [comment]
A new version of generator-theia-extension is published.
