### ISSUE TITLE
[java] Need a preference to add command arguments to language server

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2363]
I tried to open a Java project with Theia. The project uses Lombok, which is a library that is normally added to the Eclipse JVM (config.ini) with "-javaagent:/path/to/lombok.jar", see https://projectlombok.org/. If I hardcode this in the Theia Java extension code, it works, but it would be nicer if the user could set a preference to add command-line arguments.

**Comment by gorkem** [comment]
The preference exists, can you try `java.jdt.ls.vmargs`. The full list of configuration parameters [supported for vscode]( https://github.com/redhat-developer/vscode-java#supported-vs-code-settings) should also work for theia.

**Comment by MarkZ3** [comment]
Thanks! I'll give that a try. Where are users (like me!) supposed to discover this? Perhaps it should be mentioned in the Java package Readme?

**Comment by MarkZ3** [comment]
I tried `java.jdt.ls.vmargs` but it doesn't seem to work. If I look at java-contribution.ts, I don't see any logic that would read that preference. Unless this is something that would be in the base language implementation?

**Comment by gorkem** [comment]
Forgot that this particular config is applied before the server is started. 
Yes, we need to add it to the java-contribution

**Comment by 502647092** [comment]
@MarkZ3 how to add lombok support
I need this, too.
Thanks

**Comment by MarkZ3** [comment]
@502647092 
I remember making it work locally by changing the Theia code but I don't quite remember what I did. I think I hardcoded "-javaagent:/path/to/lombok.jar" in java-contribution.ts or something like that.

**Comment by 502647092** [comment]
@MarkZ3 
https://github.com/theia-ide/theia/blob/2d090d3836753ad21252147dfc6a5bb173b46ab6/packages/java/src/node/java-contribution.ts#L128-L132
add `'-javaagent:/home/theia/lib/lombok.jar` in here ?

**Comment by akosyakov** [comment]
One can pass language server start parameters from the frontend (preferences). See how it is done for TS: https://github.com/theia-ide/theia/blob/84284959a3c579f874831b5450e5858670aeee07/packages/typescript/src/node/typescript-contribution.ts#L56

**Comment by BoykoAlex** [comment]
@akosyakov is there more detailed info about how get frontend preferences in LS start options `parameters` property? I took *cpp* package as example (the `args` parameter).
Here are all references in the code that I mirrored in my code:
Node side:
https://github.com/theia-ide/theia/blob/master/packages/cpp/src/node/cpp-contribution.ts#L22
https://github.com/theia-ide/theia/blob/master/packages/cpp/src/node/cpp-contribution.ts#L32
https://github.com/theia-ide/theia/blob/master/packages/cpp/src/node/cpp-contribution.ts#L39

Common side:
https://github.com/theia-ide/theia/blob/master/packages/cpp/src/common/index.ts#L29

Client side:
https://github.com/theia-ide/theia/blob/master/packages/cpp/src/browser/cpp-preferences.ts#L60 https://github.com/theia-ide/theia/blob/master/packages/cpp/src/browser/cpp-preferences.ts#L82

The preference prefix matches server id...

Is there anything else I missed? Any special conditions for preferences key names?

I see the options for me has the session but `properties` is always `null`

**Comment by akosyakov** [comment]
@BoykoAlex in the frontend side cpp preferences are converted into start parameters here: https://github.com/theia-ide/theia/blob/b1df8fc6df895b9a473911fe5d91320a8bc55d07/packages/cpp/src/browser/cpp-language-client-contribution.ts#L145-L152

**Comment by BoykoAlex** [comment]
@akosyakov thank you very much! Working now!-)
