### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by bevrard** [theia-ide/theia#2365]
Currently, I'm running Theia on a server.

Is it possible to "activate" a login page on theia?

Thanks in advance.

**Comment by akosyakov** [comment]
It is out of the scope of Theia and up to a concrete product to implement a login page, authentication/authorization and so on. On the backend, Theia runs Express.js (a web server) and allows to configure it via `BackendApplicationContribution` callbacks.

You can look at other threads:
- https://github.com/theia-ide/theia/issues/2126 
- https://github.com/theia-ide/theia/issues/411

**Comment by bevrard** [comment]
Thank you for your feedback.
