### ISSUE TITLE
[java][git-dff] The Git diff annotations work oddly with Java sources

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2373]
Steps to reproduce:
 - `git clone https://github.com/theia-ide/theia.git && cd theia && yarn && cd examples/browser && yarn run start`
 - Select [`eclipse.jdt.ls`](https://github.com/eclipse/eclipse.jdt.ls.git) as the WS root.
 - Open [`JavaBreakIterator.java`](https://github.com/eclipse/eclipse.jdt.ls/blob/96370034a34c02c3028672578d93b300f1400c12/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java) in the editor.
 - Comment out line 39: [`public Run() {`](https://github.com/eclipse/eclipse.jdt.ls/blob/0af5098c35e3532312354123906e94f709f1c038/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java#L39).
 - Check the diff decorations.

Happened with commit 2c9cbbe2 from the `master`.

![screencast 2018-07-17 13-15-57](https://user-images.githubusercontent.com/1405703/42814522-c36f9324-89c4-11e8-8533-24a73afc7bbf.gif)

```diff
git diff org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java
diff --git a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java
index 28f4cc5..f94a7fc 100644
--- a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java
+++ b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/JavaBreakIterator.java
@@ -36,7 +36,7 @@ public class JavaBreakIterator extends BreakIterator {
                /** The length of this run. */
                protected int length;

-               public Run() {
+               // public Run() {^M
                        init();
                }

```

**Comment by AlexTugarev** [comment]
it might be related to #2177

**Comment by kittaakos** [comment]
After reopening the editor, the Git diff decorations are not there. Not even for the modified line:
![screen shot 2018-07-17 at 13 29 54](https://user-images.githubusercontent.com/1405703/42814781-9bf8c710-89c5-11e8-9777-42888822c8fc.jpg)

**Comment by kittaakos** [comment]
Perhaps there is either a formatter (editorconfig) invovled or it is related to some `CRLF`/`LF` thingy.
