### ISSUE TITLE
[Search In Workspace] UI glitch at 90% zoom level

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#2377]
<img width="389" alt="screen shot 2018-07-18 at 09 14 52" src="https://user-images.githubusercontent.com/28291421/42865807-1eec1924-8a6b-11e8-875d-5b0e8536f6ed.png">

**Comment by svenefftinge** [comment]
@jbicker I think sometimes its hard to do something about it, with 1px line thickness. 
But please have a look, maybe there is an easy way to fix.
