### ISSUE TITLE
[Search In Workspace] scroll bar incorrectly displayed on Firefox

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2379]
**Search In Workspace** scrollbar is incorrectly displayed (styling) on Firefox.

**Firefox**
![selection_007](https://user-images.githubusercontent.com/40359487/42880300-cd8c2ece-8a61-11e8-890b-cf8d8db498ba.png)

vs.

**Chrome**
![selection_008](https://user-images.githubusercontent.com/40359487/42880307-d241be2a-8a61-11e8-8ce1-45a0b390cdd4.png)

**Comment by kittaakos** [comment]
This has to be verified after https://github.com/theia-ide/theia/pull/2724.

**Comment by vince-fugnitto** [comment]
backlog grooming, issue has been resolved
