### ISSUE TITLE
selected node(s) in file navigator change when right click the void area

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#2383]
As the GIF shows, theia does not keep the selected node(s) in file navigator when user right-clicks the void area. Instead of keeping the node selection, theia removes the selection, and selects the workspace root.

![peek 2018-07-18 11-40](https://user-images.githubusercontent.com/37082801/42893620-d9cc180e-8a82-11e8-8f63-b88a66d89a44.gif)

**Comment by akosyakov** [comment]
it is on purpose, the area where there is no tree node belongs to a root
