### ISSUE TITLE
Registered Textmate provider 'source.cpp' is being overriden

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#2388]
![image](https://user-images.githubusercontent.com/14976516/42920085-9ba44cca-8b47-11e8-90fd-29b262abcecd.png)

Tested with the same package.json from #2354.

**Comment by akosyakov** [comment]
@sr229 can you copy the whole stack trace?

**Comment by sr229** [comment]
@akosyakov I already killed the pod as soon as I caught this :fearful:

**Comment by svenefftinge** [comment]
The JSON extension was registering a grammar under `source.cpp`. Fixed it.
