### ISSUE TITLE
Many ENOSPC errors in large workspace

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#239]
I have a large workspace with the LLVM codebase and I get tons of this kind of exception:

```
Uncaught Exception:  Error: watch /home/emalape/git/theia/examples/electron/llvm/tools/clang/test/Driver/Inputs/mips_fsf_tree/mips-mti-linux-gnu/include/c++/4.9.0/mips-mti-linux-gnu/mips64/64/nan2008/bits/.keep ENOSPC
Error: watch /home/emalape/git/theia/examples/electron/llvm/tools/clang/test/Driver/Inputs/mips_fsf_tree/mips-mti-linux-gnu/include/c++/4.9.0/mips-mti-linux-gnu/mips64/64/nan2008/bits/.keep ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/emalape/git/theia/examples/electron/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/emalape/git/theia/examples/electron/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/emalape/git/theia/examples/electron/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/emalape/git/theia/examples/electron/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/emalape/git/theia/examples/electron/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

A few things that might have something to do with this bug:
- The llvm folder I have checked out (including built files) has 109937 files.
- The path /home/emalape/git/theia/examples/electron/llvm is actually a symlink to /home/emalape/git/llvm

I also checked that I have space left on the drive and it doesn't seem to be the problem.

```
Filesystem                   Size  Used Avail Use% Mounted on
udev                         7.8G     0  7.8G   0% /dev
tmpfs                        1.6G   11M  1.6G   1% /run
/dev/mapper/ubuntu--vg-root  219G  152G   56G  74% /
tmpfs                        7.8G  1.9M  7.8G   1% /dev/shm
tmpfs                        5.0M  4.0K  5.0M   1% /run/lock
tmpfs                        7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda1                    472M  212M  236M  48% /boot
tmpfs                        1.6G   56K  1.6G   1% /run/user/121963
```

**Comment by hexa00** [comment]
I have this problem the moment I launch theia see Troubleshooting Linux in https://github.com/theia-ide/theia/blob/master/doc/Developing.md

Maybe theia could detect it and propose to increase the inotify max ?

**Comment by hexa00** [comment]
See #90 as realated too

**Comment by MarkZ3** [comment]
How come other tools like VSCode don't have this problem though? Is it really necessary to watch all the files? I would think it's only necessary to watch the folders and also just the files that are open in editors. But I know nothing about inotify so that could be wrong :) I'd like to see if there's a way to have it work without changing the max, at least for most situations.

**Comment by hexa00** [comment]
Yes I'm wondering about that too.. ( why VSCode is working fine)

I think like you said we should watch less that's a better solution

**Comment by akosyakov** [comment]
VS code has the same issue and to avoid it they:
- allow a user to provide exclude patterns via settings, see `files.watcherExclude` setting
- run a watcher in the separate process and restart it if it fails

**Comment by hexa00** [comment]
@akosyakov I understand the exclude pattern but not the watcher in a separate process, if you get ENOSPC errors restarting won't help ? Unless you restart without what it was watching?

**Comment by akosyakov** [comment]
@MarkZ3 are you on Linux?

**Comment by akosyakov** [comment]
@hexa00 you are right, the separate process won't help with this issue

I guess they watch in the separate because it harms the performance of the main process, as well as another way around.

**Comment by MarkZ3** [comment]
@akosyakov Yes on Linux. In VSCode, I do not get the error and the refreshing works, without changing the inotify maximum. Perhaps the errors are just swallowed or perhaps they do watch less things which sounds like a very good thing to me. I think it's worth looking into in order to provide a better out-of-the-box experience when possible. I think it makes sense to only watch folders and files that are actually opened in the editor. Even better would be to only watch folders that are expanded in the Navigator. That would cut down the number drastically and decrease the chance of having to edit sysctl.conf, which is not very nice. I could rename this issue to something more improvement-sounding instead of a bug, like "Investigate possibility of watching less files" ?

**Comment by akosyakov** [comment]
> I think it makes sense to only watch folders and files that are actually opened in the editor. Even better would be to only watch folders that are expanded in the Navigator.
it won't work for all clients, e.g. language servers are expecting events about some files

**Comment by akosyakov** [comment]
@epatpol let's test the preference service with `files.watcherExclude`, look for default values in VS Code

**Comment by epatpol** [comment]
@akosyakov Ok I'll start looking into that

**Comment by MarkZ3** [comment]
> it won't work for all clients, e.g. language servers are expecting events about some files

Makes sense!

Come to think of it, it must be the excludes that makes it work for me in VS Code because I have a huge SVN repo with .svn which contains a lot of files. I bet they are excluded.

**Comment by simark** [comment]
I agree with @MarkZ3, watching only what we need would be nice, and much more resource-efficient. The default limit on the machine I use is 8192 and I can't change it (I don't have root).  We will work with projects that have > 8192 files, even when excluding .svn/.git/etc.

I'd really like if we could avoid the problem by being more efficient in what we watch, rather than by requiring the user to set an obscure preference to exclude some files...

**Comment by akosyakov** [comment]
@MarkZ3 @simark Could you try again? We've introduced `files.watcherExclude` option that ignores `node_modules` by default. You can change it in `.theia/settings.json` from your home dir or the workspace dir.

**Comment by hexa00** [comment]
I think we should watch what is visible in the navigator only. 
And the opened files from the editor.
Is there a reason to watch anything else?

**Comment by akosyakov** [comment]
The navigator is only one client, others, for example, are language servers.

**Comment by simark** [comment]
I can imagine situations where we need to watch files that are not displayed, for internal purposes.  For example, if you do a git checkout on the command line that changes a .h file that is included in your currently open file, but that is not shown in the navigator.  The language server should probably be informed of the change so it can update the errors/warnings, its index, etc.  Is it Theia's responsibility to tell the language server that a file was changed?

**Comment by svenefftinge** [comment]
Vscode have an FAQ for this : https://code.visualstudio.com/docs/setup/linux#_error-enospc

**Comment by simark** [comment]
So, I found out that the limit on inotify watches are per-user, no per-process as I thought.  So watching in a separate process won't help to circumvent that limit.

**Comment by akosyakov** [comment]
We don't use chokidar anymore, probably it is not relevant anymore. Could someone check and close if it is so?

**Comment by simark** [comment]
Resource-wise it seems more efficient than chokidar.  I don't know if it watches properly though, not sure how to test that currently.

**Comment by svenefftinge** [comment]
Ok, then let's do it the other way around...: 
Please reopen if this is still an issue :)
