### ISSUE TITLE
Emmet extention

### ISSUE THREAD

**Issue by LucaGabi** [theia-ide/theia#2390]
Hi,

   How can I create an emmet extension for HTML - I would be very happy to have that done, please give any clue or idea - it must be a separate extention that can work on .php files as well (or registred file type).

Thanks.

**Comment by pablodonayre** [comment]
I'm using [Theia Full Docker](https://github.com/theia-ide/theia-apps/tree/master/theia-full-docker). How can i enable or add EMMET extension (if any)?

**Comment by akosyakov** [comment]
You should put the emmet extension into some folder in your image and configure Theia to load extension from this directory, for example via env variable `THEIA_DEFAULT_PLUGINS=local-dir:path_to_plugin_dir`

**Comment by pablodonayre** [comment]
What EMMET Extension have you used ? I have found [vscode-emmet-helper](https://github.com/Microsoft/vscode-emmet-helper)

**Comment by akosyakov** [comment]
It's built-in vscode extension. You can get it from https://github.com/theia-ide/vscode-builtin-extensions. I should fine time to publish them to npm already 🙈

**Comment by akosyakov** [comment]
Emmet extension is published: https://www.npmjs.com/package/@theia/vscode-builtin-emmet

One can include it in Theia at build time as here: https://github.com/theia-ide/theia-apps/pull/146/files#diff-964302cf25c6f37acd4ebdf6d686a1d3
