### ISSUE TITLE
[theme] Make the default theme configurable

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2391]
Currently, the default is the `dark` theme. We [can not use dependency injection for the themes](
https://github.com/theia-ide/theia/pull/873#issue-154365384).

To make it configurable, I propose introducing the
```
"theiaApp": {
  "defaultTheme": "your-theme-id"
}
```
construct in the `package.json`. If that is there and known by the application, we use that. Otherwise, we fall back to the current default; `dark` theme.

Later we can support such customization in a separate (`json`, `yaml`, etc...) file. Similarly to the [`electron-builder`](https://www.electron.build/configuration/configuration) configuration.

**Update:** 
https://github.com/theia-ide/theia/issues/2391#issuecomment-406511729

**Comment by svenefftinge** [comment]
How does it behave if multiple extensions provide a default theme?

**Comment by kittaakos** [comment]
In the end, you will have one application. So that `package.json` matters, and not the defining extensions. Extensions can define themes, but the "application" pins which one is the default.

**Comment by svenefftinge** [comment]
Ah, you meant the `package.json` of the main application. Got it!

**Comment by kittaakos** [comment]
We made a few adjustments regarding the application configuration:
 - Everything should go under `"theia"`.
 - The frontend related things should go under `"frontend"`, and the backend under `"backend"`.
 - Configurations, that **will be** injected into the `index.html` must go under `"config"`. `"anotherproprty"` must not be available at runtime.
```
"theia": {
    "frontend": {
      "config": {
        "defaultTheme": "myTheme"
      },
      "anotherproprty": 1
    }
  }
```
