### ISSUE TITLE
BaseLanguageServerContribution should support list of ids and names

### ISSUE THREAD

**Issue by soerendomroes** [theia-ide/theia#2393]
I am currently working on a language server for a hierarchical Xtext grammar. So the resulting language server does support multiple languages. To use them in a Theia extension I have to start the same language server multiple times and register each id name pair indiviually to get support for each subgrammar, since the `BaseLanguageServerContribution` does only support one language per language server.

**Comment by akosyakov** [comment]
Please have a look how TS extension registers 4 different languages for the same LS: https://github.com/theia-ide/theia/blob/4ba93d63206df35505de6b55bafdb4d22528ed65/packages/typescript/src/browser/typescript-client-contribution.ts#L22

**Comment by soerendomroes** [comment]
Thank you, this solves my problem.
