### ISSUE TITLE
`Open File` command should match by path as well

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2395]
Currently, it only filters by a file name, it is not very useful when there are a lot of files with the same name, like `package.json`.

**Comment by vince-fugnitto** [comment]
`Open File` currently supports both searching by name, path or both

**Comment by elaihau** [comment]
search by path has bugs to fix

![peek 2018-12-31 17-38](https://user-images.githubusercontent.com/37082801/50568645-ef848780-0d22-11e9-8762-6a19e04534a2.gif)
