### ISSUE TITLE
Two scroll bars in OpenDialog

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#2397]
Open dialog has two scrollbars when files list is bigger than the window.
When there is no need for scrolling it still has one scroll bar which scrolls a few pixels.
![screenshot from 2018-07-19 16-32-43](https://user-images.githubusercontent.com/15607393/42945915-51c6c134-8b72-11e8-9703-64ddee4c7bde.png)

**Comment by kvbhat** [comment]
Hi All.. i created a PR https://github.com/theia-ide/theia/pull/3195 to fix the  'Open dialog has two scrollbars when files list is bigger than the window.' Request to review the same.

I'm not able to fix the 2nd part 'When there is no need for scrolling it still has one scroll bar which scrolls a few pixels.'.

I'm new to Theia can I get some inputs for fixing the 2nd part?

Thanks

**Comment by kittaakos** [comment]
> Should be fixed with #3195

👍
