### ISSUE TITLE
[navigator] Expanding an item without selecting it scrolls up to the highligthed/selected item

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#240]
I have a fairly large tree in the navigator. If I select the first item and I expand an item without selecting it further down, it scrolls up to the highlighted/selected item.

1. Item near the top is selected
![step1](https://user-images.githubusercontent.com/311730/27345498-e786b46e-55b7-11e7-9827-faba516ecb0d.png)
2. I scrolled down to an item lower in the tree
![step2](https://user-images.githubusercontent.com/311730/27345500-e78b26b6-55b7-11e7-9a03-0ad6b7c095d8.png)
3. When I expanded the item, it scrolled back up to the first item.
![step3](https://user-images.githubusercontent.com/311730/27345499-e789f5c0-55b7-11e7-8b60-1e76b2e05b68.png)

**Comment by jbicker** [comment]
Fixed in https://github.com/theia-ide/theia/pull/655
