### ISSUE TITLE
Improve callbacks of dialogs

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#2400]
Dialog should call `resolve` and pass `undefined` value when the dialog is closed without accepting.
Is needed for https://github.com/theia-ide/theia/issues/2153
Actually the problem is to handle somehow closing the dialog by clicking 'Cancel' button.
The proposed method needs to be checked for other cases.

**Comment by akosyakov** [comment]
Have you seen https://github.com/theia-ide/theia/issues/1443?

**Comment by vitaliy-guliy** [comment]
Have commented in https://github.com/theia-ide/theia/issues/1443
