### ISSUE TITLE
fs watcher should normalise buffered events

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2402]
For example, DELETE events should be removed if they are followed by ADD. Otherwise, clients bogusly react to events.

See for more cases: https://github.com/Microsoft/vscode/blob/dcd5ea858f2607186b772f0ce746de584e263bff/src/vs/workbench/services/files/node/watcher/common.ts#L52-L86

**Comment by kittaakos** [comment]
Related issues:
 - [ ] [Duplicates in workspace/didChangeWatchedFiles notifications ](https://github.com/theia-ide/theia/issues/2236)

Feel free to update.
