### ISSUE TITLE
where the business logic should stay in this project, FE or BE ?

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#2415]
I have been working on adding the multi-root support to theia (https://github.com/theia-ide/theia/issues/1660), and received lots of good feedback from the community https://github.com/theia-ide/theia/pull/2117

While I was refactoring the `workspace` service I had kept thinking what's the boundary between the FE and BE in this project.

What I wanted to do initially was letting FE call the BE when it needs something, and let the BE do that job. After the refactoring, the BE, however, has no knowledge of workspace folders being opened, or the roots added.

To be honest, I have no preference on one way of doing things than the other. But this makes me think: If we count on the `workspace-service` in FE to do the job, why do we need `default-workspace-server` or `workspace-protocol` (in BE) at all? Reading and writing content from / to `recentworkspaces.json` can be done in FE as well, by calling `FileSystem` from the FE.

In the larger scope, do we want to put as much business logic in the FE as possible, or do the oppposite (i.e., use BE)?

Could you please share your insights on this?

**Comment by svenefftinge** [comment]
Yes, we should keep the user's state on the FE. Otherwise we would need to invent session state, which would make things more complicated. I am not saying we should never do that, but it needs to carry its weight.

> If we count on the workspace-service in FE to do the job, why do we need default-workspace-server or workspace-protocol (in BE) at all? Reading and writing content from / to recentworkspaces.json can be done in FE as well, by calling FileSystem from the FE.

The BE service returns the most recently used root, which can be set through command line on start.

**Comment by elaihau** [comment]
> The BE service returns the most recently used root, which can be set through command line on start.

that part doesn't need to done in `workspaceService`.

the command line args can be read from something like a `CliService`, and the recently used root can be retrieved from the filesystem :)

**Comment by kittaakos** [comment]
@elaihau, can we close this?

**Comment by elaihau** [comment]
@kittaakos thank you for the remider :)  done.
