### ISSUE TITLE
[lsp][markers][xtext] Diagnostics are not available on the client after the LS initialization

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2422]
I am currently investigating the cause. Opening the problematic file in an editor makes sure the markers are visible. Without this hack, it does not show the errors/warnings after the LS init.

**Comment by kittaakos** [comment]
Similar to #2420.

The server sends the diagnostics eagerly, but the client connection is not initialized, so no one is listening to them.

https://github.com/TypeFox/vscode-languageserver-node/blob/dad191188b81c7f189e64ad15079f5deeaa04fa3/client/src/base.ts#L1056

Alternatively, this could be solved, by triggering a "full workspace build" (whatever does that mean) for your language after the language client initialization and receive the validations again after the build.

**Comment by akosyakov** [comment]
I think it is Xtext issue. The protocol says that initialization goes like that:
-`client` sends an initialize request to `server` to provide client capabilities
- `server` responses to an initialize request to provide `client` with server capabilities
- when `client` is ready it sends `initialized` notification to `server`, see https://microsoft.github.io/language-server-protocol/specification#initialized.

Xtext has to await `initialized` notification to start the initial build. cc @svenefftinge

**Comment by dhuebner** [comment]
@kittaakos Could this issue be closed as it doesn't seem to be theia a issue?

**Comment by kittaakos** [comment]
I prefer leaving this issue open, so we are aware of the problem. Do you think it generates noise in the Theia repo?

**Comment by dhuebner** [comment]
>  I prefer leaving this issue open, so we are aware of the problem.

 I'm okay with leaving it open if that is the way how you manage/document 3rd party issues. In addition, adding `lsp` label could help find it.

> Do you think it generates noise in the Theia repo?

With > 600 open issues this one will not generate additional noise, I think.

**Comment by svenefftinge** [comment]
> With > 600 open issues this one will not generate additional noise, I think.

Is there a message hidden in this? :-)

The issue has been fixed https://github.com/eclipse/xtext-core/pull/894

**Comment by dhuebner** [comment]
> > With > 600 open issues this one will not generate additional noise, I think.
> 
> Is there a message hidden in this? :-)
> 
> The issue has been fixed [eclipse/xtext-core#894](https://github.com/eclipse/xtext-core/pull/894)

@svenefftinge  A "Time to clean up" message :)
