### ISSUE TITLE
Plugin panel is always empty

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [theia-ide/theia#2428]
1. Clone back-end plugin sample: 
`git clone https://github.com/theia-demo-plugins/theia-frontend-plugin.git`
2. Go to the plugin folder and build it:
yarn && yarn run build.
3. Run theia with plugin:
`export HOSTED_PLUGIN=/path/to/the/cloned/plugin/theia-frontend-plugin &&  cd /path/to/theia/examples/browser && yarn theia start`
4. Open theia and open plugin panel.
Actual result: plugin panel is empty
Expected result: plugin panel should display added plugin.

**Comment by benoitf** [comment]
HOSTED_PLUGIN is an internal variable for hosted mode (it's quite hidden)

using `THEIA_PLUGINS` is the expected variable for end-users and then it should work with that parameter

**Comment by evidolob** [comment]
I confirm that with `THEIA_PLUGINS` it's work
