### ISSUE TITLE
Reveal in editor doesn't work for the first line in Markdown preview

### ISSUE THREAD

**Issue by orucky** [theia-ide/theia#2444]
Reveal in editor (focusing on the appropriate line in the editor after double-clicking on the corresponding content in the preview) doesn't work for the first line *of the preview* for Markdown.

Example: let `test.md` look like:
```
foo
bar

baz
```
It gets rendered as
```
foo bar

baz
```
Then double-clicking on `foo`/`bar` does nothing, while double-clicking on `baz` changes focus to the editor window / opens it if it doesn't exist (the expected behavior).

**Comment by marechal-p** [comment]
![preview-editor-double-click](https://user-images.githubusercontent.com/14182238/43330130-53eea57a-9190-11e8-8467-352038f70f9d.gif)
Am on Ubuntu running Electron, and it seems like I don't have the same problem. Did you make sure to run the most recent application ?

**Comment by orucky** [comment]
No, I haven't, sorry ... reported the behavior in the current backend version of gitpod. It works in the latest Theia, so closing the issue ...
