### ISSUE TITLE
Completion list not correct for Java.

### ISSUE THREAD

**Issue by hifall** [theia-ide/theia#2457]
Here is the screenshot I took when I tried to look up the methods inside Integer:

<img width="678" alt="screen shot 2018-07-27 at 3 05 15 pm" src="https://user-images.githubusercontent.com/5734293/43306742-bc825af0-91ae-11e8-89d5-e4ca73d01095.png">

I was expecting parseInt, among others, on the list, but it's not. Also, other candidates on the list are not Integer's members/methods.

The env was set up per the Play With Docker instructions.

**Comment by hifall** [comment]
I set the browser example up per:
https://github.com/theia-ide/theia/blob/master/examples/browser/Dockerfile

Since I did not see any error during the setup, maybe it's not supposed to have the LS up.

If so, could you please give me a pointer to a setup with LS up?

Thanks!

**Comment by kittaakos** [comment]
Do you have Java installed in the Docker image? You can try it by opening a new terminal <kbd>Ctrl</kbd>+<kbd>\`</kbd> and run `java -version`. By the way, [here](https://github.com/theia-ide/theia-apps/blob/master/theia-java-docker/Dockerfile) is a Docker file for Theia with Java installed on it.

**Comment by kittaakos** [comment]
https://github.com/theia-ide/theia/blob/1747b18d33fcc2e8d70646d352299ac3a4aa0efd/examples/browser/Dockerfile#L32-L33

**Comment by hifall** [comment]
I am so sorry, I did miss that. My bad.

Retrying that per your instructions.

Thanks!

**Comment by kittaakos** [comment]
I did not have a problem building it.

```
git clone https://github.com/theia-ide/theia-apps.git && cd theia-apps/theia-java-docker && docker build . -t next --no-cache
```

Please tell me what do you want to achieve? Cannot you do
```
docker pull theiaide/theia-java:next \
$$ docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia-java:next
```
as described in the [documentation](https://hub.docker.com/r/theiaide/theia-java/)?

**Comment by marcdumais-work** [comment]
@hifall 
>Trying to build an image out of the Java Docker file gives me this error:
Step 10/16 : ADD $version.package.json ./package.json
ADD failed: stat /var/lib/docker/tmp/docker-builder278842839/latest.package.json: no such file or directory

To build the image yourself, make sure that you clone this repo, not just the ```Dockerfile```, since it will need at least one of the two ```*.package.json``` files to build correctly.
