### ISSUE TITLE
Split JsonRpcProxyFactory

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#246]
Right now `JsonRpcProxyFactory` has 2 responsibilities:
- send requests/notifications through a proxy object
- handle received requests/notifications with a target object

It leads to complication of the usage-side since to get a proxy one should provide a target, but very often a target relies on a proxy, so one has to introduce a third concept to decouple them.

It would be nice to decouple on `JsonRpcProxyFactory` level by having a separate module to handle each responsibility instead of forcing clients to do it each time.

**Comment by hexa00** [comment]
I get the 2 responsibilities but I'm not sure I understand what you mean by " but very often a target relies on a proxy, so one has to introduce a third concept to decouple them."  ??

Do you mean that often a target relies on a proxy being there to be able to notify ?

But it seems like a good idea, it was a bit confusing to use the JsonRpcProxyFactory at first

**Comment by akosyakov** [comment]
If `Logger` implements `ILoggerClient` interface then there is a cycle because `Logger` needs `ILoggerServer` proxy, but to create a proxy one needs an instance of `Logger`, to overcome it we have `LoggerWatcher`.

**Comment by akosyakov** [comment]
I suggest that we don't need a target to create a proxy, then there is no need for `LoggerWatcher`, `PreferenceWatcher`, `WorkspaceWatcher` and so on.

**Comment by hexa00** [comment]
Right I actually started by having Logger implement ILoggerClient, it seemed natural, then hit that cycle and did the Watcher. 

So yes a big +1 to that :)

Thanks for explaining a bit more

**Comment by akosyakov** [comment]
For the preference service I am trying to do the following:
- allow setting a target on a proxy with `setClient` method: https://github.com/theia-ide/theia/pull/140/commits/fc5f3bac7e4c9b971f7eacc874bcef8083501a7b#diff-1374a64f486c980dead22d8e618ca36c
- after that the preference service can set a client on a proxy in the constructor: https://github.com/theia-ide/theia/pull/140/commits/a213d266f1eb68a5c2a1696f5f044019e4137f96#diff-f51552448cdd6841f22a2a7cd322391bR22

What do you think about such approach? @svenefftinge @hexa00

**Comment by akosyakov** [comment]
One can call `setClient` on a remote proxy to set a local target object instead of providing it via the constructor.
