### ISSUE TITLE
[git] Rename `Changed` to `Changes` in the Git view

### ISSUE THREAD

**Issue by orucky** [theia-ide/theia#2465]
Currently, the staged changes are listed in a section 'Staged Changes', the unstaged changes as 'Changed'. Imho it's not a good naming because:
  * why change*s* vs. change*d*?
  * *changed* evokes the idea of *all* changes, that is both staged and unstaged

I would simply call the unstaged changes section as 'Unstaged Changes', or if it's too long, the first section Staged, the second Unstaged. Or maybe 'Index' and 'Modified' etc.

**Comment by kittaakos** [comment]
We tried to stick to the VS Code behavior. Did we get out of sync? If no, I would recommend closing this.

**Comment by lexcorp16** [comment]
I would like to get on this @kittaakos how can I get started (first time contributor)

**Comment by lexcorp16** [comment]
Thanks a lot @kittaakos. PR is here: https://github.com/theia-ide/theia/pull/3073
