### ISSUE TITLE
Add an ability to add a custom new line to a tree node

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#2471]
It would be great to extend the `TreeDecorator.Data` with a field e.g. `header` that would describe new div above or under the tree node.
Is needed for https://github.com/theia-ide/theia/pull/1983 to place description above the preference node

**Comment by akosyakov** [comment]
You can also override `TreeWidget.renderNode` and customize a node rendering for a particular type. `TreeDecorator` in the first place was designed to decorate the node by external contributors relative the given tree.

**Comment by vinokurig** [comment]
Thank you for advice, closing it
