### ISSUE TITLE
Add search functionality to the tree widget 

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#2472]
File navigator widget has a search-box. It would be great to move this code to common  `TreeWidget` to apply the search-box for every widget that extends `TreeWidget`.
Is needed for https://github.com/theia-ide/theia/pull/1983

**Comment by akosyakov** [comment]
I would like to see it in the file dialog and outline as well. Although it should be configurable via `TreeProps` and disabled by default.
