### ISSUE TITLE
How to best create a Theia Electron app

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2483]
Is there a ready-to-use way to create an Electron app with theia? As a result I am searching for a solution to have one shell file that has to be run to start the Theia Electron app. The same step on Windows would be having one single EXE file with everything in it.

**Comment by kittaakos** [comment]
We have a bundled electron application for the YANG language: https://github.com/theia-ide/yangster-electron. Let me know if you need assistance with it.
