### ISSUE TITLE
Clarify usages of `Logger.child`

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#249]
Currently, it is not clear when and how to use `Logger.child`. On the server-side, it is backed up by bunyan expecting node js streams as options, because of it on the client-side it is useless.

Maybe we just should remove it from the logging protocol and configure bunyan on the server-side to use different loggers depending on parameters for example.

**Comment by hexa00** [comment]
It is meant to be used as this bunyan signature
```
 child(obj: Object, simple?: boolean): Logger;
```

and not :
```
child(options: Logger.LoggerOptions, simple?: boolean): Logger;
```

See the use here: https://github.com/trentm/node-bunyan#logchild

So there should be no node js streams there, it is useful in the client-side to add a name to the logger and to set a custom log level for it.

**Comment by akosyakov** [comment]
Thx, now it is clear to me. I thought for child loggers one can provide other streams, like for different components log to different files.

So an idea would be to override `BunyanLoggerServer.child` if one wants to write to another stream for some options?

```ts
child(obj: Object): Promise<number> {
    if ('component' in obj && obj['component'] === 'myComponent') {
        return super.child({..obj, stream: this.myStream});
    }
    return super.child(obj);
}
```

**Comment by hexa00** [comment]
If the extension dev really needs streams I guess he can do that yes. 

But if the main use case is to write to some other file then using ```logger.child ({ compotent='name',   path: '/var/tmp/myapp-error.log' }) ``` would be way easier and currently supported
