### ISSUE TITLE
Integrate Custom DSL with Sprotty

### ISSUE THREAD

**Issue by amirsaad2015** [theia-ide/theia#2490]
I am having trouble understanding the process of integrating Sprotty into my language server. I have created my own DSL, and have read Typefox's blog about Sprotty and examined the Theia-Sprotty repo (it is archived now), but it is still unclear on the steps necessary for integration (where to put the DSL, which files to change, etc). Any help would be appreciated.

**Comment by svenefftinge** [comment]
Please have a look at https://github.com/theia-ide/yang-lsp. It provides a complete example.

**Comment by amirsaad2015** [comment]
@svenefftinge Thank you for the response. I have examined the repository, but am still not sure as to how to integrate my dsl with Sprotty. Besides the repository, are there any other examples that will help point me in the right direction?

**Comment by svenefftinge** [comment]
@spoenemann Do you have any further advice?

**Comment by spoenemann** [comment]
> I have created my own DSL

...with Xtext?

> and examined the Theia-Sprotty repo (it is archived now)

It's not archived yet: https://github.com/theia-ide/theia-sprotty
But it will soon be moved to https://github.com/eclipse

> Besides the repository, are there any other examples that will help point me in the right direction?

As mentioned by @svenefftinge, Yangster is the best example:

 * https://github.com/theia-ide/yang-lsp contains the Xtext DSL and the server implementation of Sprotty.
 * https://github.com/theia-ide/yang-sprotty contains the client implementation of Sprotty.
 * https://github.com/theia-ide/yangster contains the integration into Theia using the theia-sprotty library.

**Comment by amirsaad2015** [comment]
@spoenemann Thank you for the quick response. Yes I have successfully created my LSP using Xtext and have integrated it with Theia. 

The directory structure of my project is almost the same as the one listed here: https://github.com/theia-ide/theia-xtext

I have also referred to a previous issue listed here: 
https://github.com/theia-ide/theia/issues/1817

But am still a bit confused on where to begin. 

First, should I add a .diagram project to my lsp, and if so, which specific files should I add? I understand that the yang-lsp repo contains some files that are specific to yang, but not sure which files are essential for integrating Sprotty.

**Comment by amirsaad2015** [comment]
Hello. I have examined the yangster repository and have made my best attempt to understand the overall architecture of the Sprotty api as it relates to the integration with an xtext lsp. 

Work I've done: I cloned the repository theia-xtext and added the .diagram project to it with the following files: DiagramLanguageServerExtension.xtend, LanguageDiagramGenerator.xtend, LanguageDiagramModule.xtend

I understand that this is the server implementation of the Sprotty API. Is this sufficient enough for the server implementation or am I missing key files?

Furthermore, what are the next steps/files to implement for the client portion? 

Any help would be appreciated! Thank you for your fast responses!

**Comment by spoenemann** [comment]
> I understand that this is the server implementation of the Sprotty API. Is this sufficient enough for the server implementation or am I missing key files?

That's hard to tell just by the file names, but sound good so far.

> Furthermore, what are the next steps/files to implement for the client portion?

Sprotty has some documentation in its [Wiki](https://github.com/theia-ide/sprotty/wiki). Other than that, have a look at [yang-sprotty](https://github.com/theia-ide/yang-sprotty) for the diagram implementation and at [yangster](https://github.com/theia-ide/yangster) for the integration in Theia.

**Comment by spoenemann** [comment]
I suggest to move this discussion to the [Sprotty community forum](https://www.eclipse.org/forums/index.php/f/443/) since it is not directly related to Theia.
