### ISSUE TITLE
Message doesn't pop up

### ISSUE THREAD

**Issue by AhmetTanakol** [theia-ide/theia#2494]
Hi,

I am trying to display a message by using `MessageService.info` however message is displayed only on console and it doesn't pop up. I use `0.3.13` version for all theia modules. I created `theia-hello-world-extension` and modified the versions of the dependencies in `package.json`. How can I display this message?

Thank you

**Comment by AlexTugarev** [comment]
Please make sure your application contains the `@theia/messages` extension. Without this extension messages are just logged.

**Comment by AhmetTanakol** [comment]
Thank you, I missed that

**Comment by AlexTugarev** [comment]
Does it work now for you? If true, can we close this?

**Comment by AhmetTanakol** [comment]
Yes, it worked thank you
