### ISSUE TITLE
Problems view not synchronized with editor when editing typescript

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#2499]
If you look at this video:

![peek 2018-08-02 11-05](https://user-images.githubusercontent.com/1758287/43592643-03131330-9644-11e8-8732-ab28863130cc.gif)

You'll see that the problems view seems to be one edit "late" when the error disappears.  It shows an error about "a" when removing "a" and it doesn't show it when "a" is present.

It looks fine when editing a cpp file with clangd as the language server.

**Comment by akosyakov** [comment]
I cannot reproduce it. Can you reproduce it if you start from clean clone? What are you doing it?

**Comment by akosyakov** [comment]
@AlexTugarev could you comment here, please? I can have a look later.

**Comment by akosyakov** [comment]
I was able to reproduce it with multiple editors, e.g by opening `keymaps-frontend-contribution` side by side with `keymaps-service`. One of the files has outdated or not markes in the problem view
