### ISSUE TITLE
Server worker failed to start without --no-cluster option

### ISSUE THREAD

**Issue by dunnry** [theia-ide/theia#2500]
The latest pull is failing to start (example/browser) with "yarn run start" when the --no-cluster option is missing in Windows.

$ theia start
Starting server worker...
Server worker has been started. [ID: 1 | PID: 9064]
Server worker failed to start.
Server worker is ready to accept messages. [ID: 1 | PID: 9064]
Server worker has been disconnected. [ID: 1 | PID: 9064]

**Comment by kittaakos** [comment]
I am verifying this on my Windows image right now...

**Comment by dunnry** [comment]
I pulled the latest commit (40640d5cca03c82536d4c371eb962e20a7f9097c) and you are correct - it seems to work now.  However, you can reproduce it by using an older commit:

`git reset --hard "4eb376041c202fbb85d4643eb720cb57f204e699"`

Now, do your "yarn install" and "yarn run".  It will error out for you.  I don't know the differences of course, but it might be something that would be worth investigating to see what broke it so it doesn't happen again.

BTW, it's not that particular commit that introduces the issue.  It was present a few commits earlier as well.  That's only the last commit I was on that demonstrated the issue.  I am not savvy enough with git bisect to figure this out easily.

**Comment by dunnry** [comment]
I can't reproduce it anymore.  It might be a race condition or timeout issue.  However, it is just intermittent.
