### ISSUE TITLE
[local storage][git] Git history view not loaded when the view is not visible (Hidden by another view)

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2502]
Git-history view not restored.
Scenario:
- Open a workspace
-Open the git-history view --> get populated
- Select the otehr view which will be hiding the git-history view i.e. File Navigator view
- Reload the browser
- Now select the Git History view, ==> the data doesn't shows
- Now keep the focus on the Git history view and reload the browser
--> The data in Git History view is now showing

Question: Should we maintain the data for the git history view in the local storage or we should re-generate that data when putting the focus or make the view visible?
Nte: If I have a git repository in this workspace, close the workspace, change the git repo for another branch, then re-open the workspace, the git history view has to re-generate the history anyway.

**Comment by svenefftinge** [comment]
> Question: Should we maintain the data for the git history view in the local storage or we should re-generate that data when putting the focus or make the view visible?

Regenerating is better so we don't run out of storage.

**Comment by jbicker** [comment]
Got solved with https://github.com/theia-ide/theia/pull/2627
