### ISSUE TITLE
Changing the color theme is slow

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2503]

**Comment by akosyakov** [comment]
Was able to reproduce it with an opened terminal

**Comment by marechal-p** [comment]
AFAIK the terminal has a tendency to slow everything down... The theme changing is mostly just adding/removing `style` html tags, so I wonder how much faster this could be made.

**Comment by kittaakos** [comment]
![screen shot 2018-08-07 at 16 07 49](https://user-images.githubusercontent.com/1405703/43780991-30b965de-9a5c-11e8-8149-317e2063fb90.jpg)

**Comment by kittaakos** [comment]
People say it is not recommended to call `context.fillStyle` too frequently, but it is
https://github.com/xtermjs/xterm.js/blob/dd7a9c3b7a7ef060e91b022845f6084d51f29437/src/shared/atlas/CharAtlasGenerator.ts#L75

https://github.com/xtermjs/xterm.js/blob/dd7a9c3b7a7ef060e91b022845f6084d51f29437/src/shared/atlas/CharAtlasGenerator.ts#L91

Although the inner loop variable is not used at all.

**Comment by kittaakos** [comment]
Are we still using an Xterm fork? How difficult would it be to try out a few modifications?

**Comment by kittaakos** [comment]
There is another minor glitch with this, when the user does <kbd>Ctrl/Cmd</kbd>+<kbd>P</kbd> > `Change Color Theme`

Then the currently used theme is set again. It is unnecessary.

Do nothing and close the Command Palette (<kbd>Esc</kbd>), then we set again the current theme. I think the logic should be a bit smarter and not set the value if the current theme is the same as we want to set. (Other solutions are good too.)

https://github.com/theia-ide/theia/blob/cda47a7f47533fd6e1d591ca0fc61f254f063473/packages/core/src/browser/theming.ts#L149-L153

**Comment by Tyriar** [comment]
You should switch to the dynamic char atlas, this should fix this problem for the most part as well as improve perf across the board. This was introduced in v3.4 https://github.com/xtermjs/xterm.js/releases/tag/3.4.0 and we're replace the static char atlas with it soon https://github.com/xtermjs/xterm.js/issues/1576

**Comment by akosyakov** [comment]
@Tyriar thanks for the heads up, we will try

**Comment by akosyakov** [comment]
I don't have time to try out https://github.com/theia-ide/theia/issues/2503#issuecomment-440364041, if someone can open a PR with changes it would be very welcomed!
