### ISSUE TITLE
[git] Limit elements in staging view

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2512]
We need to limit the number of elements rendered in the staging.
For instance, when `node_modules`is not excluded the amount of file changes freeze the browser.

**Comment by kittaakos** [comment]
[dugite-extra can limit](https://github.com/theia-ide/dugite-extra/blob/bf5c15f4496fd18e5b13291ae861f59f2cc061b3/src/command/status.ts#L44) the number of items per `git status` command execution.

See here: https://github.com/theia-ide/theia/issues/1101

**Comment by svenefftinge** [comment]
Ok, limiting on that level might be even better.
