### ISSUE TITLE
[navigator] right click on empty area does not context menu anymore

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2538]
It is a regression before the empty have belonged to the project.

In single root mode, it should belong to the project as before. In multi-root it should allow to add and remove roots.

**Comment by elaihau** [comment]
@akosyakov  I need your clarification: Which node does the `empty` belong to, if there are more than one folder added to the same workspace ? Thank you.

**Comment by akosyakov** [comment]
@elaihau i am working on handling deleted and renamed files and will fix this issue in the same PR, had to refactor a bit the file tree and navigator model anyway.
