### ISSUE TITLE
[browser] a sub-menu is empty if all its items are not visible

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2553]
it would be good not to render it.
<img width="422" alt="screen shot 2018-08-11 at 08 04 29" src="https://user-images.githubusercontent.com/3082655/43988787-32899bb6-9d3d-11e8-8bcf-6cb4a132ef46.png">

**Comment by kittaakos** [comment]
I am closing this in favor of: [[context-menu] Do not render `CompositeMenuNode`s with zero children](https://github.com/theia-ide/theia/issues/1996).
