### ISSUE TITLE
Backend should listen on localhost by default

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#256]
I noticed that the backend listens on all interfaces by default:

    tcp        0      0 :::3000                     :::*                        LISTEN      20184/node          

That would allow by default anybody on the network to access this backend, it's not a very safe default.  I suggest listening on 127.0.0.1 by default, but allow overriding this with a command line parameter.

**Comment by akosyakov** [comment]
@simark with #310 `localhost` is used by default, the host can be changed for the web with yo config

**Comment by akosyakov** [comment]
Should be fixed by #310
