### ISSUE TITLE
nsfw does not always report ADDED/DELETED events on linux

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2566]
To reproduce, try to create or delete a file in src folder for any Theia extension. You will see that the navigator does not get an event.

Strangely when a file is moved or its content is changed events are reported always. It would be interesting to investigate what is the cause of this difference in nsfw and our use of Node.js fs API.

**Comment by akosyakov** [comment]
@elaihau @marcdumais-work was not it address as well by recent changes in nsfw? It would be good to file an issue about it while the project is active.

**Comment by akosyakov** [comment]
You should first expand and then do changes. Otherwise changes are fetched on a node click. You should see that file changes in navigator without touching UI at all.

**Comment by elaihau** [comment]
You are right. 

![screenshot from 2019-01-16 11-49-32](https://user-images.githubusercontent.com/37082801/51613011-9dcdb800-1ef0-11e9-830d-03a8d912688e.png)

**Comment by elaihau** [comment]
You are right 
![peek 2019-01-23 09-23](https://user-images.githubusercontent.com/37082801/51613052-b2aa4b80-1ef0-11e9-9f17-0b6901ede62f.gif)

**Comment by elaihau** [comment]
I found nsfw did call our event callback on file added to `theia/packages/monaco`. 
We have this bug because the event from nsfw was associated with a different path `theia/node_modules/@theia/monaco` which is the symbolic link of `theia/packages/monaco`.

any changes made to `theia` or `theia/packages` were associated with the correct paths, because there was no links in for them in the workspace.

when file edits happened in `theia/packages/monaco`, however, nsfw emits two events, one associated with `theia/node_modules/@theia/monaco`, and the other `theia/packages/monaco`.

While this is something that needs to be fixed in nsfw, there is a way to work around this issue in theia:

```ts

(events: nsfw.ChangeEvent[]) => {
            for (const event of events) {
                if (event.action === CREATED || event.action === DELETED) {
                    getAffectedFiles(event.directory, event.file).forEach(file => {
                        if (event.action === nsfw.actions.CREATED) {
                            this.pushAdded(watcherId, paths.join(event.directory, event.file!));
                        }
                        if (event.action === nsfw.actions.DELETED) {
                            this.pushDeleted(watcherId, paths.join(event.directory, event.file!));
                        }                     
                    });
                }

                if (event.action === nsfw.actions.MODIFIED) {
                    this.pushUpdated(watcherId, paths.join(event.directory, event.file!));
                }
                if (event.action === nsfw.actions.RENAMED) {
                    this.pushDeleted(watcherId, paths.join(event.directory, event.oldFile!));
                    this.pushAdded(watcherId, paths.join(event.directory, event.newFile!));
                }
            }
        }
```

```ts
getAffectedFiles(directory, file): string[] {
    // find all affected files recursively. in each call, we could
    // use fs.lstat to check if it is a symlink
    // and use fs.readlink to get the target
    
}
```
What do you think? @akosyakov

**Comment by akosyakov** [comment]
@elaihau i would start by filing an issue for nsfw, maybe it would be resolved fast and then we don't need any work arounds. Could you open such and link to this issue?

**Comment by elaihau** [comment]
filed https://github.com/Axosoft/nsfw/issues/67

**Comment by akosyakov** [comment]
@elaihau just to confirm your suggestion is to resolve a symlink to a real path and if it is different then report an event for a real path as well?

**Comment by elaihau** [comment]
> just to confirm your suggestion is to resolve a symlink to a real path and if it is different then report an event for a real path as well?

yes exactly.

**Comment by akosyakov** [comment]
@elaihau i would give it a try, at least it should improve a situation for real paths, won't report events for all symlinks to this path though :(

**Comment by akosyakov** [comment]
> won't report events for all symlinks to this path though :(

discussed with @svenefftinge that it is fine for now, we will wait till one opens a real issue for it
