### ISSUE TITLE
Re-align items in file dialog

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#2568]
This is the current state of Open File dialog

![unaligned open dialog](https://user-images.githubusercontent.com/1655894/44050994-53d869f4-9f41-11e8-9870-635242b18438.png)

The proposal is to improve alignments of the elements to make them more readable and looking better.

This is how Open file dialog may look

![open dialog - 1](https://user-images.githubusercontent.com/1655894/44053943-d538aaa6-9f49-11e8-9c49-b780c1da7bb8.png)

And the next one is Save file dialog [theia/issues/2173](https://github.com/theia-ide/theia/issues/2173) working on which is in progress and which is based on the Open file dialog.
The Save dialog may look like the following

![save dialog-1](https://user-images.githubusercontent.com/1655894/44053834-82e092be-9f49-11e8-97f3-5cb1a9dc870b.png)

**Comment by akosyakov** [comment]
It looks better to me. I only wonder whether it will look nicer if navigation arrows are aligned to the left.

// cc @svenefftinge @jbicker

**Comment by vitaliy-guliy** [comment]
Navigation arrows aligned to the right.
 
![right alignment of navigation arrows](https://user-images.githubusercontent.com/1655894/44074095-eb779d9e-9f9f-11e8-9076-90e5b53a447c.png)

Background of navigation and filter fields has been changed to background in text field.

**Comment by jbicker** [comment]
Looks better to me too. Also the different background of the fields.
+1 for navigation aligned to the left.

**Comment by vitaliy-guliy** [comment]
Great! Let me continue with that.
I will push the refinements within my PR [theia/pull/2564](https://github.com/theia-ide/theia/pull/2564).
It looks the issue needs to change only file-dialog.css

**Comment by vitaliy-guliy** [comment]
My last screenshot may confuse somebody. It shows open dialog with file name field from the save dialog. Please don't pay attention on that.

**Comment by svenefftinge** [comment]
+1 from me, too. Only the labels on the left seem to need a little left-padding.

**Comment by vitaliy-guliy** [comment]
Done.
