### ISSUE TITLE
Typescript tokenisation does not work in .tsx files

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#2571]
For instance parentheses don't close automatically.

**Comment by svenefftinge** [comment]
Can you please provide an example?
Also please verify how it is in vs code.

**Comment by akosyakov** [comment]
Just checked, it is still reproducible on master

**Comment by akosyakov** [comment]
nope, sorry for the noise, everything is good, works nicely, was wrong instance of Theia :)
