### ISSUE TITLE
Refresh the file tree in the Files View

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2573]
How can I refresh the tree of the in the Files View?
The reason I need this is that I generate new code files within the working directory, but the Files View does not update itself automatically.
I already tried importing the FileNavigatorTree:
```
import { FileNavigatorTree } from "@theia/navigator/lib/browser/navigator-tree";
```

And then injecting `FileNavigatorTree` in the constructor:
```
    constructor(
        @inject(MessageService) protected readonly messageService: MessageService,
        @inject(FileNavigatorTree) protected readonly fileNavigatorTree: FileNavigatorTree
    ) { }
```

And then call:

```
this.fileNavigatorTree.refresh().then(resultFileNavigatorTree => {
    this.messageService.info("Refreshed the file navigator tree.");
});
```
But this did not do the trick. This raises the error:
```
Uncaught (in promise) Error: No matching bindings found for serviceIdentifier: FileNavigatorTree
```

**Comment by akosyakov** [comment]
It is not possible to inject widgets or its model. One should use corresponding contribution and open handler to access a widget first and then its model.

In the case with the navigator:
```ts
@inject(FileNavigatorContribution)
protected readonly navigatorContribution: FileNavigatorContribution;

const navigator = await navigatorContribution.widget;
await navigator.model.refresh();
```

Please study [AbstractViewContribution](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/shell/view-contribution.ts) to learn common access APIs for views and then `FileNavigatorContribution`.

**Comment by jeanlucburot** [comment]
Case solved, thank you.
Keep this issue open or close it?
