### ISSUE TITLE
How to open code file stored on the Node side

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2588]
What must done to open a code file stored on the file system on the Node side?

I believe it must be the `open()` method in `packages/core/src/browser/opener-service.ts`.  So I tried injecting `CommandService` in the constructor and then using `executeCommand()` to open the file:

```
import { injectable, inject } from "inversify";
import * as React from "react";
import { CommandService } from '@theia/core/lib/common';
import { CommonCommands } from '@theia/core/lib/browser/common-frontend-contribution';

@injectable()
export class MyWidget extends ReactWidget {

    constructor(
      @inject(CommandService) protected readonly commandService: CommandService
    ) {
      super();
    }

    public myMethod() {
        const filePath: string = "/path/to/my/file.java";

        this.commandService.executeCommand(CommonCommands.OPEN.id, new URI(filePath)).then(res => {
            console.log("Successfully opened file!");
        }).catch(err => {
            console.log("Error openning file!");
        });
    }
}
```

Doing this though I run into the error path and `err` is empty.

**Comment by akosyakov** [comment]
You should use `OpenerService`: 
```ts
open(this.openerService, new URI(filePath))
```

You should be aware that commands are not APIs, but functions which can be directly executed by a user. You will be safer to use a properly statically-typed APIs, like `OpenerService`.

**Comment by akosyakov** [comment]
> Doing this though I run into the error path and err is empty.

Do you have a full stack trace?

**Comment by jeanlucburot** [comment]
> You should be aware that commands are not APIs, but functions which can be directly executed by a user. You will be safer to use a properly statically-typed APIs, like OpenerService.

Do you mean by this, that I have the choice between calling the command directly or using the `OpenerService`? Or do you mean that I should use both together?

> Do you have a full stack trace? You can try to debug OpenerService to find where it fails or provide a reproducible example.

Sadly I have no stack trace. Have not had the chance to work myself into that yet.

So, I tried following your advice, but I'm not sure how exactly you mean to proceed. My steps are the following ones.

In the class constructor I inject the `OpenerService` that I imported like this:
```
import { OpenerService, open } from "@theia/core/lib/browser";
```
The injection looks like this:
```
constructor(
    @inject(OpenerService) protected readonly openerService: OpenerService
) { }
```
Then when trying to open the code file I access `open()` directly and give `this.openerService` and the path as parameters:
```
open(this.openerService, new URI("/path/to/my/file.java")).then(res => {
    console.log("open success - res: " + JSON.stringify(res));
}).catch(err => {
    console.log("open fail - err: " + JSON.stringify(err));
});
```
Doing this I run into the following error:
```
open fail - err: "A resource provider for '/path/to/my/file.java' is not registered."
```
The need to register some resource provider seems like the obvious missing step. So the question is, how do I register such a resource provider?

**Comment by akosyakov** [comment]
> Do you mean by this, that I have the choice between calling the command directly or using the OpenerService? Or do you mean that I should use both together?

I meant when it is possible i would use services with staticly-typed APIs like `OpenerService`, not commands.

> Doing this I run into the following error:

ah, I see, it is because you should provide a URI, not a path, i.e. `new URI('file:///path/to/my/file.java')`

**Comment by jeanlucburot** [comment]
Ok, that was the problem. The path has to be manually enhanced with `file://` in order to work. Also, `new Path("/path/to/my/file.java")` by itself does not enhance the scheme correctly. The resulting code that works, is the following:
```
// Append necessary uri scheme to path.
const path: string = "file://" + "/path/to/my/file.java";
// Convert uri scheme enhanced path to URI type.
const uri: URI = new URI(path);

// Request opener handler.
this.openerService.getOpener(uri).then(res => {
    const openHandler: OpenHandler = res;
    // Instruct to open file.
    openHandler.open(uri);
});
```
