### ISSUE TITLE
Allow changing tab character size

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#259]
It should be possible to change the tab size.  I suppose at one point we will want to be able to override that value per language, but to start, a single preference would be enough.

**Comment by MarkZ3** [comment]
At first when reading the title I though "Why per language?" but you mean the tab "character" not the widget/browser-style tab :)

**Comment by simark** [comment]
Haha, indeed.

**Comment by simark** [comment]
@epatpol, is this resolved now? I think you added a preference for that?

**Comment by epatpol** [comment]
@simark yes it's fixed now thanks for bumping this issue. You can check "editor.tabSize" in the code for the default value as of now.
