### ISSUE TITLE
Enter on the numpad can't be used to open files

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#260]
It is possible to open files in the file explorer by selecting them and pressing enter, but not the numpad enter.

**Comment by MarkZ3** [comment]
We can add a new Key for NumpadEnter and and add a key listener for it in the tree, but I think it's too cumbersome to have to add two listeners every time both Enter and NumpadEnter need to do the same thing (i.e. always??). Should key strokes be considered equal if their KeyboardEvent.code (number) is the same? Or would there be cases where we want to differentiate Enter vs NumpadEnter? I can push a quick fix just for the file browser but I don't think it's good for the long term. I can already see a handful of other places where we would need another listener for NumpadEnter.

**Comment by simark** [comment]
If they have the same keyCode, what makes them different?

I don't see a scenario where we'll want to have different behaviors for both, so I think a fix that treats them the same way at the core is good.

**Comment by simark** [comment]
This seems to work now, maybe thanks to the keybindings refactoring by @hexa00?  Anyway, it works :).
