### ISSUE TITLE
Multiuser support with login session

### ISSUE THREAD

**Issue by nebulade** [theia-ide/theia#2605]
Hi there,

just found out about theia and it looks really great, the default docker container works very well locally.
I was trying to find out if this is a pure single-user app, or if there are possible extensions or so to have multiple users, when deployed on the cloud. I don't mean collaboration here, but a simple login/logout ui with basic user management.

I hope I didn't overlook something obvious.

Thanks!

**Comment by svenefftinge** [comment]
Theia itself is single user, as it exposes full access to the remote container. 
To support multi-user you would have to manage deployments of workspaces and users, which is out of scope for the Theia project. If you don't want to build that yourself, you can have a look at either Eclipse Che or gitpod.io.
