### ISSUE TITLE
Improve Command Line Argument Handling

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#262]
We should look how different extensions can contribute to CLI arguments.

**Comment by svenefftinge** [comment]
Theia core should define a hook 'CommandLineContribution` that allows any extensions to contribute to the command line interface, by providing options, descriptions, and defaults.
The actual arguments should be provided through injection.

On startup we should obtain and call all contributions to configure the command line library (yargs), the resulting actual arguments object will be provided through injection to any clients.
