### ISSUE TITLE
How to inject properly

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2631]
Is there any recommended method for injecting Classes? I have created a class in which I want to run an external process on the Node side. For this I found the `RawProcessFactory` which I try to inject, but nothing is injected into the variable.

```
export class MyProcess {
    @inject(RawProcessFactory) protected readonly rawProcessFactory: RawProcessFactory;

    public run() {
        this.rawProcessFactory... // emtpy
    }
}
```

**Comment by AlexTugarev** [comment]
@jeanlucburot by "empty" you mean undefined?

`MyProcess` need to be decorated `@injectable` and bound in a module, backend module in that case.

**Comment by jeanlucburot** [comment]
Yes, it resulted in `undefined`.
