### ISSUE TITLE
Go to last editor location command

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#264]
One thing I use a lot in Eclipse is the "Last Edit Location" command. When I type code, sometimes I navigate through a few files to understand what I should use, then I want to go back where I was typing. It is bound to Ctrl+Q in Eclipse (same on mac)

**Comment by kittaakos** [comment]
I use this in VSCode too.

**Comment by svenefftinge** [comment]
Is that different to #73 in that it skips all locations where I didn't change something?

**Comment by kittaakos** [comment]
No, it is exactly what you have described. Still, I would keep this open to having a dedicated binding for that.

**Comment by svenefftinge** [comment]
add a comment about keybindings https://github.com/theia-ide/theia/issues/73#issuecomment-345457440
