### ISSUE TITLE
[preferences] remove comment from settings template

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2652]
when using the json extension, it doesn't automatically recognize JSONC and therefore shows errors for the comment in the automatically created settings.json. 

as long as JSONC is not automatically recognized, we should just remove the comment. also, I think the a preference UI should explain everything necessary to change settings.

**Comment by akosyakov** [comment]
An issue for json extension? it should be fine to use comments with Theia.

**Comment by AlexTugarev** [comment]
@akosyakov, jsonc grammar is associated with `*.jsons` files only in https://github.com/theia-ide/theia-json-extension/blob/master/json-extension/src/browser/json-grammar-contribution.ts#L93

**Comment by AlexTugarev** [comment]
Thanks to @akosyakov for discussing this. We can add an additional monaco language extension registration for `jsonc` to the preference extension, which should select `settings.json` by filename.
