### ISSUE TITLE
Problems running ldm

### ISSUE THREAD

**Issue by IcyDoor** [theia-ide/theia#266]
I am trying to run the theia browser example in a docker container but running ldm fails.

The Docker container has:
Ubuntu:17.04
git
nodejs 7.10
npm 4.2
typescript

1. I run the npm install in the theia folder
2. npm install and npm install -g . in the folder theia/config/local-dependency-manager
i can now run ldm globally. 
3. When i run ldm it requires a file from a relative path ../lib/ldm.js
That file does not exist so i change it to theia/config/local-dependency-manager/src where the source files are located.
4. The ldm.js does not exist, only the typescript versions of all of the scripts exist (.ts)
So i manually compile the files to js.
5. The compiled .js files contains import statements which cannot run natively so i manually transpiled the files to be able to run them from a shell, it then complains about not finding the sourceMaps property which is injected from another file, so i moved the code from the injected file right into the complaining manager.js file and it still wont run.

I figured that since i am the only one getting these hurdles that i was doing something wrong.

This is the error it gives me when i try to npm run bootstrap in the browser folder and its caused by not being able to run ldm successfully as described in previously mentioned numbered list:

npm ERR! Linux 4.4.66-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "localinstall"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browser-example@0.0.1-alpha.1 localinstall: `ldm install --dev --original-sources
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browser-example@0.0.1-alpha.1 localinstall script 'ldm install --de
v --original-sources'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the browser-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ldm install --dev --original-sources

Thanks in advance!

**Comment by kittaakos** [comment]
@IcyDoor, could you please share the full console log? We might need all the information, not just the exception, to be able to resolve the issue. For instance, [here](https://github.com/theia-ide/theia/files/1126063/theia_install_full_console_log.txt), you can reference my full console log.

Thanks in advance for your cooperation!

**Comment by kittaakos** [comment]
Also, please try the [tl;dr](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#tldr) script, and do *not* install `ldm` into the global if feasible. At least, I have never done that so far, and it worked before.

**Comment by svenefftinge** [comment]
I double checked executing the script that is listed under 'tl;dr' (https://github.com/theia-ide/theia/blob/master/doc/Developing.md#tldr) in a docker image. It worked without problems. 
I have:
```
jovyan@0051d8b0fd1c:/work/theia/examples/browser$ npm --version
4.2.0
jovyan@0051d8b0fd1c:/work/theia/examples/browser$ node --version
v7.10.0
```

**Comment by simark** [comment]
@svenefftinge, can you give either the exact commands you use, or even better, a Dockerfile to reproduce it?

**Comment by svenefftinge** [comment]
I figured the reason is user permissions. When running `npm install` for local-dependency-manager it silently fails to run the additional scripts and just reports a warning (`cannot run in wd`).

The solution is described here : https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd
We will create a docker image and publish it, to make it easier for people to try Theia. Also we should add the flags as described in the solution.

**Comment by simark** [comment]
Shouldn't we just say that you shouldn't run that as root?

**Comment by svenefftinge** [comment]
Yes, if that fixes the issue, too.

**Comment by IcyDoor** [comment]
Thanks everyone for the help!
@svenefftinge Thanks alot, that solved it :)
Ran this:
git clone https://github.com/theia-ide/theia \
&& cd theia \
&& npm install --unsafe-perm \
&& cd config/local-dependency-manager \
&& npm install --unsafe-perm \
&& cd ../../examples/browser \
&& npm run bootstrap \
&& npm run start

@simark I downloaded node 7.10.0 and npm 4.2.0 on Ubuntu 17:04 like this:
curl -sL https://deb.nodesource.com/setup_7.x | bash -
apt-get install -y nodejs
Here is a link: 
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by simark** [comment]
@IcyDoor: ok, well the 7.x setup isn't advertised anymore since 8.x is out, but it's good to know it still works. An alternative is to use [nvm](https://github.com/creationix/nvm).

**Comment by svenefftinge** [comment]
Here is the docker file that works for us
```
FROM node:7.10-wheezy

MAINTAINER "TypeFox"

LABEL name="theia"
LABEL version="0.1"

RUN mkdir /theia-git && git clone https://github.com/theia-ide/theia /theia-git

RUN cd /theia-git \
    && npm --silent --unsafe-perm install \
    && cd /theia-git/config/local-dependency-manager \
    && npm --silent --unsafe-perm install \
    && cd /theia-git/examples/browser \
    && npm run bootstrap \
    && npm run build:frontend

EXPOSE 3000

WORKDIR /theia-git/examples/browser

CMD npm run start:backend
```
