### ISSUE TITLE
Context menu has slight "wiggle"

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2665]
When I navigate the context menu, i.e. open a sub-menu, all entries of menu shift slightly.

![2018-06-08 09 33 07](https://user-images.githubusercontent.com/3210701/41145088-3d179aee-6aff-11e8-8838-a7c121c8b2eb.gif)

**Comment by kittaakos** [comment]
Also tracked here: https://github.com/theia-ide/theia/issues/1996
Original PR: https://github.com/theia-ide/theia/pull/2004
Another PR: https://github.com/theia-ide/theia/pull/2587
