### ISSUE TITLE
[preference-ui] not usable after re-open

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2666]
repro:

1. open and change settings
  ![screen shot 2018-08-27 at 01 59 12](https://user-images.githubusercontent.com/914497/44634662-e2cedc00-a99c-11e8-9888-10f4e71f6384.png)

2. close and re-open:
  - why is the tree expansion state preserved? I wasn't expecting this.
  - see, you cannot expand other sections.
  - see, you cannot change anything from tree editor.
  - ![2018-08-27 02 00 26](https://user-images.githubusercontent.com/914497/44634692-4c4eea80-a99d-11e8-81ce-1297fa84631d.gif)

3. js console show only this (maybe) related entry, which comes from `push.../../packages/preferences/lib/browser/preferences-tree-widget.js.PreferencesTreeWidget.handleClickEvent`

```
logger-protocol.ts:99 root ERROR Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `Grid`. See https://fb.me/react-warning-keys for more information.
    in div (created by Grid)
    in Grid (created by List)
    in List (created by View)
    in View
    in div
```

**Comment by svenefftinge** [comment]
@vinokurig would you be able to look into this the next days?

**Comment by vinokurig** [comment]
I'll take a look ASAP
