### ISSUE TITLE
[editorconfig] should not modify on open

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2667]
modifications like `insert_final_newline` as for the theia repo should not be applied on opening of an editor. 

instead it should be applied on first save of changes, cf. vscode extension for editorconfig:

![2018-08-27 02 28 18](https://user-images.githubusercontent.com/914497/44635025-08f67b00-a9a1-11e8-8258-2182d056ea5f.gif)

**Comment by vince-fugnitto** [comment]
@AlexTugarev I'm thinking of fixing the issue to only perform `editorconfig` modifications `onSave`, is this the correct solution?

**Comment by AlexTugarev** [comment]
sounds good. also have a look at what @akosyakov did to exclude auto save (https://github.com/theia-ide/theia/commit/0a24b07578b2746f946b5ecbe03d0c89d6bb18d2), would be good if that's would respect it too.

**Comment by svenefftinge** [comment]
I noticed that it even does adding an empty line if there is no editorconfig in the project.
I tried with https://github.com/spring-guides/gs-spring-boot

**Comment by akosyakov** [comment]
I think it is typescript LS. Maybe formatting on saving is enabled for it by default. Right now we don't provide any preferences to it.

**Comment by geropl** [comment]
@AlexTugarev and I dug a bit into it and it seems that changes caused by editorconfig are applied whenever they are updated (which includes on editor open) (cmp. [`editorconfig-document-manager L101`](https://github.com/theia-ide/theia/blob/master/packages/editorconfig/src/browser/editorconfig-document-manager.ts#L101)).

**Comment by svenefftinge** [comment]
According to [these guidelines](https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines) we should not apply `trim_trailing_whitespace` and `insert_final_newline` on open.
