### ISSUE TITLE
Open File defaults to search everywhere

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2671]
Since the recent changes in the quick command palette, the `open file` command searches everywhere initially. It should do that only after trigger CMD+P a second time.

**Comment by svenefftinge** [comment]
@azatsarynnyy this slipped during my review. Would you be able to take care of it immediately?

**Comment by azatsarynnyy** [comment]
@svenefftinge sure. I take care of it.

**Comment by azatsarynnyy** [comment]
@svenefftinge here's the fix https://github.com/theia-ide/theia/pull/2677
