### ISSUE TITLE
tree nodes cannot always be expanded from the preference editor

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#2676]
1) Open the preference editor from the top menu bar `File->Settings->Open Preferences`
2) Try to expand nodes from the pref tree. Nodes are not expandable.
3) If refresh browser, the nodes become expandable again.

![pref_tree_not_extend](https://user-images.githubusercontent.com/37082801/44667337-81ccf580-a9e8-11e8-8272-471f090708f9.gif)

**Comment by AlexTugarev** [comment]
dup of #2666?

**Comment by elaihau** [comment]
you are right @AlexTugarev . Let me close this one.
