### ISSUE TITLE
changes to workspace preferences don't always take effect

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#2679]
Changes made to workspace preferences take effect when users edit the `settings.json` manually in editor.

Changes don't take effect when they are made through the pref tree.

![peek 2018-08-27 12-55](https://user-images.githubusercontent.com/37082801/44673247-f445d180-a9f8-11e8-8ce5-fb8244ca6730.gif)

**Comment by svenefftinge** [comment]
@vinokurig Could you check this, too?
