### ISSUE TITLE
How does a language server communicates with the Theia backend

### ISSUE THREAD

**Issue by ankitmithu007** [theia-ide/theia#2685]
I was digging into the code and got a good understanding of the communication between Theia's frontend and  backend over WebSocket  JSON-RPC.
But I was a little confused how is the communication happening between language server(LSP) and the Theia's backend.
My guess is it not over WebSocket. Code links would be really helpful.

**Comment by svenefftinge** [comment]
It depends on the language server. We use stdio most of the time.
E.g. https://github.com/theia-ide/theia/blob/master/packages/python/src/node/python-contribution.ts#L37

**Comment by svenefftinge** [comment]
uest
