### ISSUE TITLE
[File -> Open... ] Bug

### ISSUE THREAD

**Issue by daxiansheng** [theia-ide/theia#269]
In windows 10, git bash
git clone theia to somewhere c:\xxx\xxx\xxx\xxx\theia
build theia.
And then cd to  c:/xxx/xxx/xxx/xxx/theia/examples/browser

$npm run start

open http://127.0.0.1:8080 in chrome
click File -> Open ...

Nothing happened, no dialog opened, but the chrome developer console report: no permission read hiberfil.sys

**Comment by akosyakov** [comment]
It should be in the scope of https://github.com/theia-ide/theia/issues/199

**Comment by akosyakov** [comment]
@daxiansheng Feel free to look into #199

**Comment by hexa00** [comment]
Fixed in #643 I think please re-open if it's still an issue
