### ISSUE TITLE
[Tasks] Terminal stays busy after finishing a shell task

### ISSUE THREAD

**Issue by lucas-koehler** [theia-ide/theia#2692]
I tried to executed a task with `TaskService.run`. This task executes a shell script that creates a JAR file. After this finishes, the console of the task stays busy. Therefore, it cannot be used and on the terminal it looks like something is still executed. Is this on purpose or a bug? If it is on purpose, how can I avoid this?

**Comment by akosyakov** [comment]
@marcdumais-work @simark Maybe you can help?

**Comment by simark** [comment]
It depends by what OP means by "the console of the task stays busy".  I think it's normal that the terminal stays open, but it should say "terminated" or something like that in the tab.  It's expected that once the task has finished running, it doesn't drop you to an interactive shell.

If what you see doesn't match this behavior, could you please provide a reproducer?

**Comment by lucas-koehler** [comment]
Unfortunately, I do not have a current reproducer anymore. However, back then I assumed that the shell should be interactive after the task finished. Because this is not the case on purpose, I believe this issue can be closed.

**Comment by simark** [comment]
> Unfortunately, I do not have a current reproducer anymore. However, back then I assumed that the shell should be interactive after the task finished. Because this is not the case on purpose, I believe this issue can be closed.

Ok.  Sorry about the delay, I had not seen this issue previously in the sea of issues.  Thanks @gorkem for doing some cleanup/sorting/labelling.
