### ISSUE TITLE
[preferences-ui] settings are inserted before template comment 

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2699]
It would be nice if the settings would be inserted after the comment:

![screen shot 2018-08-29 at 14 57 39](https://user-images.githubusercontent.com/914497/44789095-09a73100-ab9c-11e8-848d-4094ac80ded3.png)

/cc. @vinokurig

**Comment by svenefftinge** [comment]
Shouldn't we just get rid of the comment, now that we have tool support?

**Comment by AlexTugarev** [comment]
Let’s do that.

**Comment by AlexTugarev** [comment]
@vinokurig, cool I see, you started working on this. Looking forward to test your PR!
