### ISSUE TITLE
toml extension

### ISSUE THREAD

**Issue by colemickens** [theia-ide/theia#2704]
It would be nice if `toml` were supported. There's a VSCode extension with syntax support and a language server: https://github.com/bungcip/better-toml

**Comment by vince-fugnitto** [comment]
Sorry for the lack of response, unfortunately it happens occasionally when working in a large project. 

We have been working tirelessly at improving our compatibility with vscode so it is highly likely that the vscode extension for `toml` is already supported. If you however encounter with running the vscode extension in Theia, feel free to open issues describing the bugs :)
