### ISSUE TITLE
Backend fails to start possibly because of a timeout  

### ISSUE THREAD

**Issue by mathansen** [theia-ide/theia#2710]
The server worker startup fails for me from time to time with the following output:
```
time yarn start --hostname=0.0.0.0
yarn run v1.9.4
$ theia start --hostname=0.0.0.0
Starting server worker...
Server worker has been started. [ID: 1 | PID: 1558]
Server worker failed to start.
Server worker is ready to accept messages. [ID: 1 | PID: 1558]
Server worker has been disconnected. [ID: 1 | PID: 1558]
^CCommand terminated by signal 2
real 0m 16.72s
user 0m 3.26s
sys 0m 0.21s
```

I terminated the command immediately after the "...has been disconnected" message. The host machine is a Raspberry Pi. A timeout seems a probable cause.

**Comment by akosyakov** [comment]
We should allow to increase timeout or check whether we need it at all on the first startup in the case if the DI configuration is broken.

**Comment by JonasHelming** [comment]
Workaround until this is fixed: By appending --no-cluster to the yarn start command, everything will run in the same process rather than separate worker processes.

**Comment by akosyakov** [comment]
@JonasHelming just be aware that it can potentially run heavy file processing in the same process and block the UI, like locating git repositories and watching file system, if you git repo and workspace are small it should be fine

**Comment by JonasHelming** [comment]
@akosyakov : Thanks for the hint. In our current use case, we deal with a very small project, so we are fine for now...

**Comment by mathansen** [comment]
@akosyakov is there an update to when you guys will find the time to look into this? Alternatively, it would be great to know where this timeout is currently specified in Theia, so we can just increase it for the moment.
