### ISSUE TITLE
Errors trying to install Theia on Ubuntu

### ISSUE THREAD

**Issue by MarioFromBelgium** [theia-ide/theia#2714]
Hi, I have been trying to install Theia on a remote ubuntu (16) server.
After the 5th trial, each time from a freshly installed image, I decide to search help.

Attached the printout of the terminal window during the install process.
[Install_Theia.txt](https://github.com/theia-ide/theia/files/2336299/Install_Theia.txt)

What I'm I doing wrong?
What more info do you need?
The server is hosted at Vultr so I can have a fresh clean server up and running in minutes evenmore I don't need to stick with UBUNTU 16 (although my experience is at UBUNTU)

Thx on beforehand for your support!

Mario

**Comment by MarioFromBelgium** [comment]
Hi @marcdumais-work 

Thx for helping out!  
I'm afraid I have not enough experience with yarn etc..  
I don't have clue how to go foreward. I have tried to install the the packages with npm install nsfw etc..

That did seem to work but what than?   launching yarn? yarn build?  In any case that does not seem to do the job.

As said already I can have a clean ubuntu in minutes but even then I don't understand what my actions should be. In my understanding the yarn command should have installed all modules...no?

Grts,
Mario

**Comment by marcdumais-work** [comment]
@MarioFromBelgium From the provided log, it looks like you already have a good Node,js and yarn versions. I think all you need to do is to install a few Ubuntu / Debian packages, before you attempt to build Theia. Here's a starting point : 
```
sudo apt update && apt install -y g++-4.8 oracle-java8-set-default libsecret-1-dev python build-essential

```

You may eventually need to install more Ubuntu dependencies, depending on which Theia extension(s) you want to use. For example, for C/C++ development, you would need to install clangd, that is used as a language server. 

Something that might help is to look at what we install in our Docker images. Here is the Dockerfile for the ```theia-full``` image, that's also based on Ubuntu 16.04. In this image, we attempt to provide the environment where all (*) Theia features can be tried. There will be of course a lot more installed in that image than you need, to start-with: 

https://github.com/theia-ide/theia-apps/blob/master/theia-full-docker/Dockerfile

(*): may not be 100% up-to-date.

**Comment by MarioFromBelgium** [comment]
@marcdumais-work 
installing the different packages that you mentioned did the job!

Great work! Thx
Now I'm going to explore the IDE...ready to find the solution for the newt problem.

Regards,
Mario

**Comment by marcdumais-work** [comment]
have fun exploring Theia
