### ISSUE TITLE
Should provide tooltip in the extensions views

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2721]
Suggestion: We should have a tooltip for the Extensions view to show the package and the description. If the user has the Extensions view with minimal width, he doesn't see everything. 
I.e "@theia/task", see the package, but not the description
"@theia/textmate-grammars", the package name is shorten and need to put "..." for the name, the user has to expand to see the whole name.

**Comment by elaihau** [comment]
discussed with @lmcbout , this also applies to the file navigator
