### ISSUE TITLE
Opening Git History view generates errors

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2722]
Opening the Git History (From menu or "ALT+h) view generates many errors on the consoles like this:

root ERROR Warning: Encountered two children with the same key, `a999282c`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
    in div
    in div

**Comment by marcdumais-work** [comment]
@lmcbout Did you notice this on master? Were you using a multi-root workspace at that time?

**Comment by jbicker** [comment]
Hi, I assign that to me since I'm currently reworking the git history implementation. It grew to a mess.

**Comment by lmcbout** [comment]
I saw those errors while testing the multi-root environment, did not test it with the latest master

**Comment by marcdumais-work** [comment]
@jbicker It's possible that the error above happens when the same git repository is included more than once, in a given multi-root workspace. Just a theory...
