### ISSUE TITLE
Open workspace dialog should have a filter and show only the folder 

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2723]
When selecting File->Open Workspace,  the dialog should filter to show only the folder and the files containing the multi-root workspaces. All other files should not be shown in the dialog since we cannot use it.

**Comment by elaihau** [comment]
the workspace files can be identified by their extensions. vsCode uses `code-workspace`, and we could use something like `theia-workspace`. What do you think ?

**Comment by marcdumais-work** [comment]
@elaihau maybe we could automatically use the ```.theia-workspace``` extension when we create a workspace file, but still support opening a VSCode workspace file (for compatibility)? i.e. show files with both extensions, as candidate for being chosen, in the ```Open Workspace``` dialog

**Comment by elaihau** [comment]
yes i am on it right now. 

Also I would suggest we change the file dialog API to support `pre-set the filter`. Right now "All Files" is the option that always at the top and by default. 

![filter_](https://user-images.githubusercontent.com/37082801/44866734-0e2f2080-ac54-11e8-860e-c2850a7b8b12.png)

**Comment by elaihau** [comment]
related to https://github.com/theia-ide/theia/issues/2590

**Comment by akosyakov** [comment]
I'm not sure that we need it, we for sure need #2590 because vscode apis only allow to disable selection of files and folder, they don't allow to hide them. @elaihau will you work on #2590 first?

**Comment by vince-fugnitto** [comment]
closing thanks to #2803
