### ISSUE TITLE
[ts] Superfluous error logging when cannot find the `tsserver` executable

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2750]
I get the errors either periodically, or per file per WS. One would be enough. See attached screencast. Maybe the defect is not TS specific but a generic issue with the LS processes.

![screencast 2018-08-31 20-33-11](https://user-images.githubusercontent.com/1405703/44930321-3c008c00-ad5e-11e8-8874-12334f2db01f.gif)

**Comment by akosyakov** [comment]
It tries infinitely to restart a server because the process gets killed and the connection is lost. We need to distinguish truly broken connection from processes and tackle the latter differently.
