### ISSUE TITLE
Don't distribute electron

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2758]
It causes issues like https://github.com/theia-ide/theia/issues/1699 and https://github.com/theia-ide/theia/issues/2693. I suggest that we move `electron` to `devDependency` for `core` and `cli` that we still can use its api, but it will be up to the client to install it. For `cli` probably we can remove it altogether, also need to check whether `electron-builder` can cause similar issues.

We will need to fix https://github.com/theia-ide/theia/issues/775 first.

**Comment by marechal-p** [comment]
So, in a Theia application, would the dependencies look something like:
```js
{
    "dependencies": {
        "@theia/core": "latest",
        "@theia/thing": ...,
        "electron": "latest",
    }
}
```
?

**Comment by akosyakov** [comment]
yes, something like that, not sure about latest, we should recommend the same version which is used in `core` as a dev dependency

**Comment by marechal-p** [comment]
Could we define the dependency to electron as a peerDependency too? As well as a devDependency so that it is available while working on the sources? Would that work in your experience?

**Comment by akosyakov** [comment]
I was thinking about it, but it seems that `peerDependency` is mandatory, the install will fail if they are not provided by the client. We need something optional, there is also `optionalDependency`, but there is no a way to disable a single one.

**Comment by laosb** [comment]
Updates?

**Comment by tsmaeder** [comment]
Today I have bigger concern that @theia/core has a direct dependency to electron. 
https://github.com/theia-ide/theia/issues/2758
It also brings tons of unwanted files for host process.

**Comment by tsmaeder** [comment]
Moved discussion from #4620 :


Today I have bigger concern that @theia/core has a direct dependency to electron.
#2758
It also brings tons of unwanted files for host process.
@akosyakov
Member
akosyakov commented 17 hours ago

    Today I have bigger concern that @theia/core has a direct dependency to electron.
    #2758

Agreed that it should be optional.

    It also brings tons of unwanted files for host process.

I wonder how. It should be loaded at build or runtime only for electron target. We don't reference it outside of electron src folders.
@benoitf
Collaborator
benoitf commented 17 hours ago

        It also brings tons of unwanted files for host process.

    I wonder how. It should be loaded at build or runtime only for electron target. We don't reference it outside of electron src folders.

it's in node_modules folder
@benoitf
Collaborator
benoitf commented 17 hours ago

I should have said I was talking about filesystem space, not memory.

**Comment by marechal-p** [comment]
> Today I have bigger concern that @theia/core has a direct dependency to electron.

Ah indeed: https://github.com/theia-ide/theia/blob/master/packages/core/package.json#L23

> benoitf: it's in `node_modules` folder

IIRC we delete the electron files from `node_modules` in some of the Docker images:
https://github.com/theia-ide/theia-apps/blame/master/theia-docker/Dockerfile#L15

But then how are we supposed to split out this electron dependency?

Split each extension contributing electron code into something like `@theia/core-electron`?

**Comment by akosyakov** [comment]
> Split each extension contributing electron code into something like @theia/core-electron?

No, it would be too much.

I've propose to make a dev dependency, so we can still APIs. IDE developers will need to declare Electron as runtime dependency in their package.json.

cc @thegecko @JanKoehnlein @spoenemann and anyone else who is building Electron right now :)

**Comment by JanKoehnlein** [comment]
Making Electron a dev-dependency sounds good to me. 

Splitting packages also bears a high risk that both sides get out of sync. We already experience and fix a lot of bugs, especially when running Theia Electron on Windows. It seems like this already gets less love and testing than the browser version. 

Single sourcing for Electron and the browser is still one of the killer features for many Theia users, so please don't make that harder.

**Comment by spoenemann** [comment]
The actual problem is that we have separate source folders `browser`, `electron-browser`, `common` and `node`, but we build them all with the same settings.

Another possible approach could be to define different build settings for the source folders. For example, we could use the `import-blacklist` rule of tslint to ensure that electron and node APIs are not used in browser code.

**Comment by marechal-p** [comment]
@spoenemann I feel like this is a different issue, but I still like it! Didn't know about this option :)

**Comment by akosyakov** [comment]
We could also experiment with `postinstall` script of theia cli which will run `yarn install electron` if a target is `electron`. If it works nicely it would not break existing clients. If...

**Comment by akosyakov** [comment]
I will add `@theia/electron` package which should have all electron dependencies (electron, electron-store, native-keymaps). It will be used as a dev dependency for `@theia/core` and as a dependency for `@theia/cli`.
