### ISSUE TITLE
[plug-in] Add Tree View and Tree Data Provider APIs

### ISSUE THREAD

**Issue by ashumilova** [theia-ide/theia#2782]
The new plugin model should contain the tree view and tree data provider APIs. 
Tree View should have : 
- [x] tree view definition  
- [x] tree view item definition
- [x] tree view events (TreeViewExpansionEvent, TreeViewSelectionChangeEvent, TreeViewVisibilityChangeEvent)

For tree data provider:
- [x] provide ability to register provider for tree data

**Comment by vitaliy-guliy** [comment]
Everything is done except 'TreeViewVisibilityChangeEvent'. I cannot find it in the VSCode api.
