### ISSUE TITLE
[plug-in] Keyboard Shortcuts Plugin API 

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#2783]
Provide API for keybinding management something like [VS Code API ](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeskeybindings )

**Comment by RomanNikitenko** [comment]
Command API and ability to register keybindings from 'package.json' file of a plugin are used to contribute key bindings from plugin side.
[Command API](https://github.com/theia-ide/theia/blob/eb586cd2f7730b4d182f4c5e3a5a6bf9d1f522d6/packages/plugin/src/theia.d.ts#L1974-L2004) provides ability to register a command and handler for given command.
[This PR](https://github.com/theia-ide/theia/pull/3731) allows to provide keybindings for commands in ‘contributes' => ‘keybindings’ section of  package.json' file, read and register them.
So now we have ability to contribute key bindings from plugin side.
Please see example and video in description of [the PR](https://github.com/theia-ide/theia/pull/3731)
