### ISSUE TITLE
[plug-in] Menu Plugin API 

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#2785]
Provide API for contribute a menu item for a command to the Thia components
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by azatsarynnyy** [comment]
done by https://github.com/theia-ide/theia/pull/2955

**Comment by azatsarynnyy** [comment]
done
https://github.com/theia-ide/theia/pull/2955
