### ISSUE TITLE
[search-in-workspace] `deltaDecorations` called on diff editor

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2795]
repro:

- select two files in Files navigator
- compare both (via context menu)
- see JS log

WARNING: `deltaDecorations should be called on either the original, or the modified editor.`

call site: `search-in-workspace-result-tree-widget.js.SearchInWorkspaceResultTreeWidget.decorateEditor`

besides the missing check for diff URI, why is it trying to decorate editor in the first place? I haven't used the Search since starting Theia. 

/cc. @jbicker

**Comment by jbicker** [comment]
Duplicates https://github.com/theia-ide/theia/issues/2539

**Comment by AlexTugarev** [comment]
Thanks!
