### ISSUE TITLE
As a user I would like to `Open...`, `Open Workspace...`, and `Open Recent Workspace...` with a keybinding

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2808]
I propose using the VS Code keybindings if they do collide with existing ones.

**Comment by vince-fugnitto** [comment]
@kittaakos I may be mistaken but I noticed that only `Open` in vscode has a keybinding present. We will most likely be using our own keybinding for all others.

**Comment by kittaakos** [comment]
> We will most likely be using our own keybinding for all others.

Why is it a problem?

**Comment by vince-fugnitto** [comment]
@kittaakos Sorry it isn't a problem, just wanted to confirm that we will be using our own keybindings. When you proposed to use vscode's I thought perhaps you found keybidings for the`Open Workspace` and `Open Recent Workspace`.

**Comment by kittaakos** [comment]
> Sorry it isn't a problem, just wanted to confirm that we will be using our own keybindings.

👍 

> I thought perhaps you found keybidings for theOpen Workspace and Open Recent Workspace.

You're right, I was confused with `Open Folder` (Cmd+K/Cmd+O) I believe.
