### ISSUE TITLE
[SIW][question] Additional context for the SIW editor decorations

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2827]
As I see, VS Code only applies the SIW decorations to the editor when the SIW widget is active. Do we want to adjust our behavior to VS Code, or we are good with the current one; we always show the decorations when there are SIW search results.

From VS Code:
![screencast 2018-09-10 10-22-10](https://user-images.githubusercontent.com/1405703/45285494-91b60080-b4e3-11e8-945e-dbbf1d0e68b1.gif)

CC: @svenefftinge, @akosyakov

**Comment by svenefftinge** [comment]
So when I activate an editor, the decorations are removed, too?

**Comment by kittaakos** [comment]
Reopen (or create a new issue) if we want to support this in Theia.
