### ISSUE TITLE
Error when storing the layout state

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#2831]
It looks that there is a bug with storing the layout state when closing/refreshing the browser.

To test it I added a simple React widget that demonstrates the problem
```javascript
export class TestWidget extends ReactWidget {

    constructor() {
        super();

        this.id = 'test-view';
        this.title.closable = true;
        this.title.caption = this.title.label = 'Test View';
        this.title.iconClass = 'fa fa-child';

        this.update();
    }

    protected render(): React.ReactNode {
        return <React.Fragment>
                <div>Test View</div>
            </React.Fragment>;
    }

}
```
and show the widget by following
```javascript
        const testWidget = new TestWidget();
        this.applicationShell.addWidget(testWidget, {
            area: 'left'
        } as ApplicationShell.WidgetOptions);
```

Now widget is properly displayed in Theia. But when Theia tries to store its layout the following error is appeared in browser console
```
root ERROR Error during serialization of layout data TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ShellLayoutRestorer.../../packages/core/lib/browser/shell/shell-layout-restorer.js.ShellLayoutRestorer.deflate
    at ShellLayoutRestorer.../../packages/core/lib/browser/shell/shell-layout-restorer.js.ShellLayoutRestorer.storeLayout
```

**Comment by vitaliy-guliy** [comment]
![error when storing the layout state](https://user-images.githubusercontent.com/1655894/45299320-ea04f680-b513-11e8-8225-81f3542138b4.png)

**Comment by kittaakos** [comment]
Could you please create a branch with that new widget? That would simplify a lot.

**Comment by vitaliy-guliy** [comment]
Yep, sure

**Comment by vitaliy-guliy** [comment]
Done. See the description to the pull request.

**Comment by kittaakos** [comment]
> Done

Thanks! Did you try to _console log_ what could cause the cycle? You could try [`
util.inspect(object[, options])`](https://nodejs.org/api/util.html#util_util_inspect_object_options). Or a [browser equivalent](https://github.com/Automattic/util-inspect). I did not try it though.

**Comment by marechal-p** [comment]
I tried to identify the circular reference, but the only match I find is just a duplicate reference:
![image](https://user-images.githubusercontent.com/14182238/45328211-e9c32600-b528-11e8-9ff2-063d62cf874c.png)

When I try to check for a reference of an object in one of its children's children, I can't find anything.

Here's the branch with my naive tests: https://github.com/theia-ide/theia/blob/mp/issue-2831/packages/core/src/browser/shell/shell-layout-restorer.ts#L85-L89

**Comment by vitaliy-guliy** [comment]
It works. Thanks!
