### ISSUE TITLE
Missing 'View' keybindings

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2837]
There are missing keybindings for `View` commands. (Ex: `Outline`, `Plugins`, `Search`)

<img width="348" alt="screen shot 2018-09-10 at 7 38 53 pm" src="https://user-images.githubusercontent.com/40359487/45330249-863df600-b532-11e8-8591-4d83ea06e440.png">

**Comment by vince-fugnitto** [comment]
@kittaakos thanks for pointing it out, should we simply not have a keybinding to toggle the `Search` widget, or just not use `ctrlcmd+shift+f` ?

**Comment by kittaakos** [comment]
> should we simply not have a keybinding to toggle the `Search` widget

Yes, please.
