### ISSUE TITLE
iconColor in TreeDecorator.Data does not do anything

### ISSUE THREAD

**Issue by JPinkney** [theia-ide/theia#2839]
Hi, I am currently trying to colour the file icons blue in the file navigator for folders in a users java classpath. I have come across iconColor in [TreeDecorator.Data](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-decorator.ts#L481) but it does not seem to do anything, whereas I am able to set iconOverlay etc using the tree decorator.

**Comment by vince-fugnitto** [comment]
@JPinkney sorry I just came across this issue, you can follow the same idea as the `git.decorations.colors` preference which enables coloring in the explorer for different git states.

https://github.com/theia-ide/theia/blob/021cfc52d15e806a510d59c47b4fe4baba9410ae/packages/git/src/browser/git-decorator.ts#L116-L140

**Comment by JPinkney** [comment]
We don't need it anymore, it was needed back when we were working on https://github.com/eclipse/che-theia-java-plugin but it is cool to know this capability exists!

**Comment by vince-fugnitto** [comment]
Okay great! 
I'll close the issue then :)
