### ISSUE TITLE
Java: Consume che-ls-jdt as jdt.ls extension

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#2849]
Once we have merged Support RedHat JDT LS extensions #1878 , it would make sense to consume che-ls-jdt (as well as the microsoft java debug adapter) as extension to jdt.ls instead of using an augmented build.

**Comment by tsmaeder** [comment]
We'd have to include the bundles from che-ls-jdt into our theia-java plugin https://github.com/eclipse/che-theia-java-plugin and to go back to using the basic jdt.ls in Theia proper.

**Comment by kittaakos** [comment]
> go back to using the basic jdt.ls in Theia proper.

Related: https://github.com/eclipse/eclipse.jdt.ls/pull/746

**Comment by tsmaeder** [comment]
@kittaakos I don't see the connection to that jdt.ls issue.

**Comment by kittaakos** [comment]
OK then. Just keep in mind, Theia is shipped with a fork of the JDT LS:
https://github.com/theia-ide/theia/blob/fd9dfcaa30e77787d35fc63602baacd3fcf8ffda/packages/java/package.json#L61

**Comment by tsmaeder** [comment]
> OK then. Just keep in mind, Theia is shipped with a fork of the JDT LS:

I guess you wanted the feature before the gitpod.io launch? But frankly, shipping with forks because you can't get your PR's and/or CQ's approved is not a good practice, IMO.
