### ISSUE TITLE
[Electron] Open a workspace from an empty Electron close the Electron application

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2856]
Scenario:
- Open Electron when there is no workspace.
- Add a workspace  from "Open workspace" or "Open Recent Workspace"

Result: Electron will close

**Comment by vince-fugnitto** [comment]
@lmcbout 
Do you mind re-testing and closing if the issue is no longer valid?
On my side everything worked correctly :smiley:

**Comment by lmcbout** [comment]
Works fine, Thanks
