### ISSUE TITLE
[plug-in] API for register a filesystem provider

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#2861]
This is part of VS Code [Workspace API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace)

**Comment by azatsarynnyy** [comment]
`workspace.registerFileSystemProvider` API has been added by the PR https://github.com/theia-ide/theia/pull/4484.


For now, the contributed providers are taken into account when opening a document by URI with `workspace.openTextDocument` API. See the sample plugin https://github.com/eclipse/che-theia-samples/pull/31.


To complete support of `FileSystemProvider` API, a couple of follow-up issues has been opened:
- https://github.com/theia-ide/theia/issues/4511
- https://github.com/theia-ide/theia/issues/4510
