### ISSUE TITLE
[preferences] Add splitpanels on after drag

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2862]
When I drag the preferences widget around in the shell, there seems to be an additional split panel added for ever drag.
<img width="1023" alt="screen shot 2018-09-12 at 10 59 02" src="https://user-images.githubusercontent.com/372735/45414142-01aabf00-b67b-11e8-8735-d814ec1a9911.png">

**Comment by svenefftinge** [comment]
@vinokurig Would you be able to look into that?

**Comment by vinokurig** [comment]
I'll take a look ASAP
