### ISSUE TITLE
[git] should rely on or fallback to system git

### ISSUE THREAD

**Issue by colemickens** [theia-ide/theia#2863]
I took a peak and I realize this issue is probably in `dugite`, but it seems to be bundling it's own `git` binary. This doesn't work on my system, NixOS, as it doesn't work with random, unpatched ELFs.

I'm not sure if dugite exposes a way to tell it to use the system git. If so, and someone can point me in the right direction, I can try to send a PR. Or otherwise, I could open an issue on `dugite`, if that's the right thing to do.

**Comment by kittaakos** [comment]
If you want to use an external Git, you have to set the [`USE_LOCAL_GIT`](https://github.com/theia-ide/dugite-extra/blob/bf5c15f4496fd18e5b13291ae861f59f2cc061b3/src/core/git.ts#L162) environment variable to `true`.
