### ISSUE TITLE
[status-bar][styling] Adjust the font color in the status bar when Theia is offline

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2877]
Currently, it is the yellowish background with the white font. We should change it and use the [`--theia-warn-font-color0`](https://github.com/theia-ide/theia/blob/f93d2811e63555725ee999c7db1840d45352a434/packages/core/src/browser/style/variables-dark.useable.css#L127) so that we align the styles with Git and SIW.

![screen shot 2018-09-13 at 17 48 39](https://user-images.githubusercontent.com/1405703/45536736-a4da1080-b802-11e8-9275-78d1e5ea6669.jpg)

**Comment by lexcorp16** [comment]
I would like to get on this @kittaakos, mind pointing me in the right direction?

**Comment by kittaakos** [comment]
We change the status bar styling based on the connection status change events here:
https://github.com/theia-ide/theia/blob/4eda225bc683633b9a5528b0a327b0b7681cce6e/packages/core/src/browser/connection-status-service.ts#L188-L195

We set the warning color here:
https://github.com/theia-ide/theia/blob/4eda225bc683633b9a5528b0a327b0b7681cce6e/packages/core/src/browser/connection-status-service.ts#L207

Currently, only the background color can be modified: https://github.com/theia-ide/theia/blob/4eda225bc683633b9a5528b0a327b0b7681cce6e/packages/core/src/browser/status-bar/status-bar.tsx#L63-L67

You have to add a new method:
```js
setColor(color?: string): Promise<void>;
```

And implement it similarly we did for the background:
https://github.com/theia-ide/theia/blob/4eda225bc683633b9a5528b0a327b0b7681cce6e/packages/core/src/browser/status-bar/status-bar.tsx#L106-L110

**Comment by lexcorp16** [comment]
Thanks a lot @kittaakos. PR is here https://github.com/theia-ide/theia/pull/3075
