### ISSUE TITLE
New concept for Theia views

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#2879]
Currently I'm implementing [View plugin API](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) which gives the ability to the developer to embed his view to the UI. View can be displayed only inside view container. Theia does not support this kind of displaying the views, so I have implemented custom view container (displayed as view in Theia terms) which may display several views inside itself. This view container like Theia view has id, title and icon.

In VS Code plugin can embed his view container only to 'activitybar' which actually is left part of the layout. In Theia I did not set such restriction and plugin can show the view container in left, right and bottom parts.

See an example. Plugin describes 'Package Explorer' view container on the left, 'Comments' on the right and 'Remote' on the bottom. 'Package Explorer' contains 'Package Dependencies' and 'Package Outline' views, 'Comments' contains three automatically generated views (one per user, for example). 'Remote' view container at the bottom has only one view. Actually I'm not sure whether we need to describe view containers for the bottom parts. When I try to display several views inside of it, it become looking ugly.

![views](https://user-images.githubusercontent.com/1655894/45542612-145bfa00-b81b-11e8-87af-8fce4aed8a6c.png)

For an instance, in the current version of Theia plugin cannot embed 'Opened Editors' view to the 'Files'/'Explorer' part and the functionality like in VS Code that displays opened editors can not be implemented. 

That's why I want to propose new view concept for Theia.

![vs code views concept](https://user-images.githubusercontent.com/1655894/45541101-c7762480-b816-11e8-9a2e-cdc91f455ec7.png)

Considering this concept views are displayed inside parts.

I still don't know whether we need to describe part for all the views or maybe part can be automatically generated if some code wants to open the view without specifying the part. 

I still haven't seen how it's implemented in VS Code and for me it is still not clear.
Let's discuss this together and find a solution.

Pros:
- it would allow to embed custom view to any Theia part

Cons:
- may be some issues with dragging and dropping the views

**Comment by svenefftinge** [comment]
I would prefer to keep it optional, so that a `Widget` can be a `ViewContainer` accepting additional TreeViews or not. We should make sure that our VS Code equivalent widgets (e.g. navigator) do support it, so that contributions can be made. But not impose this on every widget.

**Comment by akosyakov** [comment]
@vitaliy-guliy Have you researched whether there are already good React components which can do it and also support both horizontal and vertical layouts? We could decouple trees from phosphor widgets and turn them into React components. We can reuse it for the debug extension as well then.
