### ISSUE TITLE
[doc] Update the required Node.js version in the Prerequisites section

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2880]

**Comment by akosyakov** [comment]
I wonder should we mention which Node.js version should be used to make sure that app works in Electron. I don't think we can use 9, 10 in this case.

**Comment by kittaakos** [comment]
I do not know much about 9. But for sure we cannot use 10.

**Comment by kittaakos** [comment]
But it is recommended to use a version that has the active LTS. Only the even version number has active LTS support: https://github.com/nodejs/Release.

**Comment by akosyakov** [comment]
I mean in Electron always bundled Node.js is used, as far as I know, Node.js 9 and 10 only supported by Electron 3. If someone uses apis from them its app won't work in Electron.
