### ISSUE TITLE
Missing libs for extension when using yarn

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2888]
To build up Theia after having cloned from Git I use `yarn` in the main directory to build all the libraries. Lerna takes care of every project within `/packages`. Now, I have an extension that makes use of Theia libraries such as `languages`, `editor`, `navigator`, `monaco`, ... The problem is that `yarn` breaks in the middle of its job mentioning that my extension is missing some libraries. I assume that my extension is checked and built before those mentioned libraries yet exist, which is why the error arises. This is the error:

```
lerna ERR! [compile] src/browser/services/events-language-server-service/events-service.ts(8,42): error TS2307: Cannot find module '@mycompany/events/lib/browser/events-client-contribution'.
lerna ERR! [compile] src/browser/services/events-language-server-service/text-document-completion.ts(7,48): error TS2307: Cannot find module '@theia/languages/lib/browser'.
lerna ERR! [compile] src/browser/services/events-language-server-service/text-document-completion.ts(54,61): error TS7006: Parameter 'languageClient' implicitly has an 'any' type.
lerna ERR! [compile] src/browser/services/events-language-server-service/text-document-completion.ts(55,13): error TS2347: Untyped function calls may not accept type arguments.
lerna ERR! [compile] src/browser/services/events-language-server-service/text-document-completion.ts(55,106): error TS7006: Parameter 'completionList' implicitly has an 'any' type.
lerna ERR! [compile] src/browser/services/events-language-server-service/text-document-did-open.ts(7,48): error TS2307: Cannot find module '@theia/languages/lib/browser'.
lerna ERR! [compile] src/browser/services/events-language-server-service/text-document-did-open.ts(49,61): error TS7006: Parameter 'languageClient' implicitly has an 'any' type.
lerna ERR! [compile] src/browser/widgets/event-handler-widget/event-handler-widget.tsx(12,40): error TS2307: Cannot find module '@theia/java/lib/browser/java-client-contribution'.
lerna ERR! [compile] src/browser/widgets/event-handler-widget/event-handler-widget.tsx(13,31): error TS2307: Cannot find module '@theia/editor/lib/browser'.
lerna ERR! [compile] src/browser/widgets/event-handler-widget/event-handler-widget.tsx(14,34): error TS2307: Cannot find module '@theia/workspace/lib/browser'.
````

I understand that those libraries do not yet exist, but how can I solve this problem? The name of my extension starts with an `a`, so assuming that `lerna` walks through the `/packages` folder alphabetically, my extension is built before other extensions are build that it depends on. My current workaround is not pretty, but does the job (the execution order is important):

````
cd theia && yarn
cd ..
cd theia/packages/languages && yarn && cd ../../..
cd theia/packages/editor && yarn && cd ../../..
cd theia/packages/navigator && yarn && cd ../../..
cd theia/packages/markers && yarn && cd ../../..
cd theia/packages/monaco && yarn && cd ../../..
cd theia/packages/java && yarn && cd ../../..
cd theia/packages/aaa-myextension && yarn && cd ../../..
cd theia && yarn
````

**Comment by marcdumais-work** [comment]
Hi @jeanlucburot ,

To build just one package, try: ```npx run build @theia/<package>```

Did you define all your Theia dependencies, in your extension's ```package.json```? From the above, you have at least a few.

**Comment by jeanlucburot** [comment]
Thanks @marcdumais-work ,
the problem was due to missing dependencies in the `package.json`. When previous compilation with `yarn` has already taken place, no problem arises. But when pulling from Git and not yet having the `node_modules`, then compilation failed. A trap that is very easy to get caught into. I personally would prefer if Lerna grumbles out errors always when there are missing dependencies in the `package.json` and not waits until they _really_ don't exist.
