### ISSUE TITLE
[outline] Use the `DocumentSymbol.detail` not just only the `DocumentSymbol.name`

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2894]
Currently, `detail` is ignored. It would be nice to decorate the Outline with the detail. Just like Eclipse does with the type information.
![screen shot 2018-09-17 at 15 21 03](https://user-images.githubusercontent.com/1405703/45625594-88053d80-ba8d-11e8-9cba-bcf1ff06e27a.jpg)

**Comment by kittaakos** [comment]
I have added the bare minimum support for the `detail` [here](https://github.com/theia-ide/theia/pull/2885/files#diff-b66e384594a59de0891e4a8e3b0bd1a4R295). No decorations, no fancy colors, just the concatenation of the `symbol.label` + `symbol.detail`.

**Comment by vrubezhny** [comment]
Here's how it's looking with what I have done in [PR](https://github.com/theia-ide/theia/pull/3314)

![t2894](https://user-images.githubusercontent.com/620781/47679144-cbda7f00-dbc3-11e8-8a0b-c8a2b92d6df2.png)
