### ISSUE TITLE
Authoring Plug-ins and "Hosted Plugin: xxxx" not being in command palette.

### ISSUE THREAD

**Issue by jdflemin** [theia-ide/theia#2896]
### Setup
Windows 10 Pro
nvm 1.1.7 (for windows)
node 8.12.0
yarn 1.9.4
python 2.7.15

### Description
[Authoring Plugins Tutorial](https://www.theia-ide.org/doc/Authoring_Plugins.html) 
I am following the above tutorial and whenever I get to the "Executing the Plug-in" section I am not able to find "Hosted Plugin: xxxxxx" in the command palette. 

I have had Theia up successfully multiple times with the following methods:
[Docker](https://github.com/theia-ide/theia-apps#theia-docker)
[Yangster Electron](https://github.com/theia-ide/yangster-electron)
[Building your own IDE](https://www.theia-ide.org/doc/composing_applications)

### Question
Is there something else I am missing while setting up Theia to be able to explore this feature or is there currently a bug preventing this feature from working properly? I saw someone else having a kind of similar issue also running Windows 10, the other issue though was showing "Hosted Plugin: xxxxx" where as I cannot even get that to populate. Maybe some bugs exist in Windows 10? If so what should I change my set up to, in efforts to start exploring the plugins and how to build them? Any recommendations?

**Comment by benoitf** [comment]
@jdflemin I will try on Windows10pro. I tested on macOS and Linux

**Comment by jdflemin** [comment]
@benoitf Thank you for looking into this. If I come up with anything I will let you know and I will also look into trying on Linux.

**Comment by jdflemin** [comment]
I might be missing something in setup that might not be mentioned in docs if this works on Linux too as I ran a Linux machine with the following setup and encountered the same thing:

Debian 9 Stretch
Node 8.12.0
Python 2.7.13
Yarn 1.9.4

**Comment by benoitf** [comment]
@jdflemin do you have plugin-ext package in the package.json of your theia assembly ?

it is required to use plug-in mechanism

**Comment by Mosho1** [comment]
@benoitf that fixed it for me. I suggest adding it to https://www.theia-ide.org/doc/Authoring_Plugins.html.

**Comment by gorkem** [comment]
I do not think there is anything else left to do on this one closing
