### ISSUE TITLE
python file has no highlight or prompt

### ISSUE THREAD

**Issue by fuzihaofzh** [theia-ide/theia#2914]
I wan to use Theia to edit a python file. However, I found it has no highlight nor prompt of input. Could anyone please help on this?

![image](https://user-images.githubusercontent.com/1419566/45755934-335eef80-bc52-11e8-8414-e3484ae20d39.png)

**Comment by AlexTugarev** [comment]
If the Python LS cannot be started you'd see related messages in the log of the backend. 

Could you check if you see something like this: https://github.com/theia-ide/theia/blob/master/packages/python/src/node/python-contribution.ts#L47-L48

**Comment by akosyakov** [comment]
@AlexTugarev don't we send a notification to a user with an explanation how to install?

**Comment by AlexTugarev** [comment]
@akosyakov that's a very good idea. Thinking a bit further, we could also provide configuration support, as part of the LS contributions on the BE. I think we discussed such features with @geropl or @32leaves. For example, we could move the download and extraction of the jdt, or the installation of pyls to tasks, which could be started on the initial LS start. 

But as a beginning we can introduce notifications.

**Comment by csytan** [comment]
I also get this problem using the stable Docker version. No mention of Python in the logs.

**Comment by kittaakos** [comment]
Related: #4189.
