### ISSUE TITLE
Make the compound preference server smarter

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#292]
The compound preference server should be aware of the different json preference servers priority (i.e if it receives a change from user settings for "lineNumbers" but there is already a setting in the workspace preference server for that, filter out the event?)

**Comment by epatpol** [comment]
I suggest we close this one as several things changed, i.e the removal of preference servers but the workspace preference providers now have priority and overrides user preferences

**Comment by akosyakov** [comment]
@epatpol sounds good, close it
