### ISSUE TITLE
[travis] Error: Cannot find module '../../build/Release/nsfw.node'

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2921]
https://travis-ci.org/theia-ide/theia/jobs/430283343#L1580

Builds seem highly unstable lately, I cannot find the reason yet.

**Comment by simark** [comment]
My be something wrong with the Travis caches, I deleted them and restarted my build.

**Comment by simark** [comment]
So, this issue seems to be gone after clearing the caches, but now there is an issue with a task test, which I also see locally.

https://travis-ci.org/theia-ide/theia/jobs/430668560

**Comment by akosyakov** [comment]
To avoid breaking travis caches: https://github.com/theia-ide/theia/pull/2927

**Comment by kittaakos** [comment]
@marechal-p, the [PR](
https://github.com/theia-ide/theia/pull/2927) was merged. Please verify and close this issue if the problem does not persist anymore. Thanks!

**Comment by marechal-p** [comment]
Yes, perfect!
