### ISSUE TITLE
[minor] Incorrect info message when selecting recent workspace

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2934]
- Open a workspace.
 - Open a recent workspace and select the current one.

Incorrect info message due to bugous code.

![screen shot 2018-09-20 at 16 59 33](https://user-images.githubusercontent.com/1405703/45827569-fd277b80-bcf6-11e8-9c73-bcaa5240eb29.jpg)

`tsc` says `never`:
![screen shot 2018-09-20 at 17 00 12](https://user-images.githubusercontent.com/1405703/45827674-39f37280-bcf7-11e8-8bd3-a13d00b59774.jpg)

https://github.com/theia-ide/theia/blob/0f97c9ad6432e7f9fe9549005c6dedf14fabafa0/packages/workspace/src/browser/quick-open-workspace.ts#L65

**Comment by vince-fugnitto** [comment]
closed since we no longer use `MessageService` to display info message
