### ISSUE TITLE
Terminal initial size is incorrect

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#294]
If I start the terminal in a large window, I will see something like this:
![terminal-resize](https://user-images.githubusercontent.com/698076/28173340-23b2f5a4-67bc-11e7-88a2-fa02485d4cee.png)

The terminal is starting up with a smaller size then the window allows and wrapping the lines based on that. So you see the weird wrapping.

Then it figures out the correct size and update the terminal so the line wrapping becomes ok. But this looks very weird. We should fix it to have the right size from the start if possible.

**Comment by hexa00** [comment]
We should be able to query the dom element for it's size and send that as the terminal initial size

**Comment by lmcbout** [comment]
@hexa00 , It looks like this issue has been fixed with the issue #463 merged on sept 12

**Comment by hexa00** [comment]
I don't think this original issue is fixed it still starts with 80 cols until resize is called
