### ISSUE TITLE
Add confirmation dialog on close

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#2942]
It is way too easy to accidentally close Theia. For instance, when going back in history (on mac even happens with swiping left) or pressing CTRL+W. 
We should add a confirmation dialog

**Comment by kittaakos** [comment]
Please make this configurable (via the preferences).

**Comment by vince-fugnitto** [comment]
@marechal-p can this be closed thanks to your PR #3641?

**Comment by marechal-p** [comment]
Yes, nice catch!
