### ISSUE TITLE
Debug panels - regressions?

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#2946]
With reference to PR #2891

We came across the multiple debug panel changes when picking up the latest master and have found it causes some issues.
Most users only have one debug session at a time, but by supporting multiple sessions, the following problems have been introduced:

- Launching, stopping and relaunching the same debug configuration opens a brand new panel. Develop/debug cycles are often quick and this ends up with many tabs open. This is especially annoying as new tabs default to the bottom area, so you need to keep moving them if this isn't your preferred layout.
- User's are unable to see the debug tab before launching a session. In this case user's cannot manage their breakpoints before starting debug.

I'd really like to see the Theia debug follow vscode where possible, but if multiple debug sessions are here to stay, can I request the following:

- By default only have a debug panel per debug configuration, not session
- Reintroduce the ability to display a debug panel prior to starting debug so breakpoints can be seen/managed

cc @tolusha @tsmaeder @svenefftinge

**Comment by tolusha** [comment]
@thegecko 
I am planning to fix that in subtasks (Debug Panel & List of all breakpoints.) of the epic https://github.com/theia-ide/theia/issues/2843

**Comment by thegecko** [comment]
Thanks for the information @tolusha Are there also plans to have debug panels per configuration rather than per session (as it is now)?

**Comment by tolusha** [comment]
@thegecko 
sure, debug panels will be per configuration.

**Comment by tsmaeder** [comment]
@tolusha I don't think that works: what if you start two debug sessions from the same configuration?

**Comment by tsmaeder** [comment]
Run two copies of jdt.ls? Remote debug with a fixed port is not the only possiblity.

**Comment by svenefftinge** [comment]
> I'd really like to see the Theia debug follow vscode where possible, but if multiple debug sessions are here to stay, can I request the following:

Me too. Also VS Code does support multiple debug sessions, quite nicely. 
I could see that switching between sessions in VS Code looses selection state, which we could do better. But other than that the UX is pretty decent.

**Comment by svenefftinge** [comment]
> Run two copies of jdt.ls? Remote debug with a fixed port is not the only possiblity.

Such rare cases can be done by duplicating the configuration instead of introducing another 1-n indirection.

**Comment by svenefftinge** [comment]
The only thing that I personally find od in the debug story of VS Code is the floating debug toolbar.
That should really be sticky on the top of the debug view.

**Comment by thegecko** [comment]
Another option for multiple sessions per configuration could be to use a flag in the configuration?
That way, the default would create a single panel per configuration, but the advanced user could set their configuration up to spawn a panel per session.

**Comment by akosyakov** [comment]
Should be fixed in master.
