### ISSUE TITLE
Why does the demo need write access to my public repositories?

### ISSUE THREAD

**Issue by Qix-** [theia-ide/theia#2947]
Hey there,

Why does the Theia demo require write access to public repositories? Is there a way to scope this to read only/allow me to choose which repositories? Otherwise it's way too dangerous to test.

Thanks!

**Comment by svenefftinge** [comment]
GitHub doesn't allow requesting write permissions on a per repository basis, unfortunately.
What we could do is, start out with read access (so only the e-mail would be requested) and then later when a user actually wants to do something with a GitHub repo, ask for more permissions. 
At least the e-mail is needed, as a user will get a full container in the cloud, so we need to know a bit who she is just in case.

**Comment by Qix-** [comment]
Yeah that sounds perfect :)
