### ISSUE TITLE
Blame annotation UI broken

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#2956]
Some lines are not shifted by the blame annotation view.
<img width="835" alt="screen shot 2018-09-24 at 15 26 30" src="https://user-images.githubusercontent.com/28291421/45954912-b2677580-c00e-11e8-9b5b-8489d2ff2c31.png">

**Comment by AlexTugarev** [comment]
@jbicker, do you have an example file from this repo?

we have some decorations related additions recently. there might be some interferences ;-)

**Comment by jbicker** [comment]
In that particular case I've noticed it in [problem-widget.tsx](https://github.com/theia-ide/theia/blob/master/packages/markers/src/browser/problem/problem-widget.tsx).

**Comment by AlexTugarev** [comment]
commit messages needs to be escaped. now, they might contain characters that break styles. I can be reproduced with any commit which message contains single quotes.
