### ISSUE TITLE
Tasks can't be run through the shell

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#2960]
If you try the following task in vscode:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "A task",
            "type": "shell",
            "command": "echo {Hello,world!}"
        }
    ]
}
```

it outputs `Hello world!`.  `{Hello,world!}` becoming `Hello world!` is the result of the command being run through bash (or another compatible shell).

With Theia, we don't run the task through the user's shell, which results in the following error:

    Error launching task 'A task': Error: Request run failed with message: Command not found: echo {Hello,world!}

Since we aim for vscode compatibility for tasks (and because shells are nice tools), we should support this.

**Comment by simark** [comment]
From what I understand reading [this](https://code.visualstudio.com/docs/editor/tasks-appendix), if the type of the task is "shell", the command should be the full command line, including arguments, to be interpreted by the shell.  The "args" property is ignored.  If type is "process", "command" should be only the executable name and the "args" property is used.  But in both cases, a terminal showing the output is opened by default.

**Comment by elaihau** [comment]
@marechal-p could this one be closed?

**Comment by marechal-p** [comment]
More details: https://github.com/theia-ide/theia/commit/2b950102fbd058459ebe227b9e128e3637bc8ad2
