### ISSUE TITLE
[plug-in][languages] Register a document link provider

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#2964]
Multiple providers can be registered for a language. In that case providers are asked in parallel and the results are merged. 

https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7369

**Comment by azatsarynnyy** [comment]
done https://github.com/theia-ide/theia/pull/3061
