### ISSUE TITLE
Using the preview widget to have a text replacement

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2965]
**Description**

It would be nice to be able to have a text replacement using some keyword.

One implementation I tried was to have all variables defined in a file, use the preview editor to see the modified text. If the user needs to adjust the text, he double-clicks in the preview  file. This opens the file editor. By having them side by side and have a file containing the word replacement, the end-user can see the modified text.

We just surfaced the idea at the synch meeting, but I did not look at any other consideration yet.

**How to test:** 
1. Create a filename `catalog.json` in the workspace root folder
2. Add some variables to test. example:
     
```json
{
  "Hi":  "How are you",
  "Google": "https://google.com"
}
```

3. Under any workspace folder, create a file with the extension ".md"  ex: "test.md"
4. Open the file "test.md" (Open in Preview editor)
5. Double-click on the file to open the editor portion
6. Set you layout to see the catalog.json, the editor and the preview
7. In the editor you neeed to use the `"{{ <variable name> }}"` 

Note: you need to use the {{ and }} around the variables to be executed and to see the result in the preview editor. 

![textreplacement](https://user-images.githubusercontent.com/419051/46013616-d40e3e80-c09a-11e8-8b53-69b0d9c3157f.gif)

**Comment by vince-fugnitto** [comment]
@lmcbout I believe this issue can be closed?

I believe the implementation would be best suited to an external extension using some of the `preview`'s functionality and would not be present in the main repository since it's quite niche?

**Comment by lmcbout** [comment]
Ok, let close it
