### ISSUE TITLE
[debug] "Add debug configuration" command bug

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2976]
From master, when doing "Add debug configuration" from the menu bar items, all it adds to my launch config is `[]`.

**Comment by thegecko** [comment]
Ack.
The issue seems to be around here:
https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-configuration.ts#L59

Where 'newDebugConfiguration' return an object, which is then 'concat' with an array.
