### ISSUE TITLE
Support coloring themes

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#298]
We have a Cloud IDE project that uses your framework and I was wondering if we can custom style the entirety of the Application because there's no docs for it

**Comment by akosyakov** [comment]
Right now only by changing them in theia-core.

**Comment by svenefftinge** [comment]
We use CSS variables for common things. Currently there are two different definitions
 - [bright theme](https://github.com/theia-ide/theia/blob/master/src/application/browser/style/variables-bright.css)
 - [dark theme](https://github.com/theia-ide/theia/blob/master/src/application/browser/style/variables-dark.css)

We currently include the dark one, but will for sure allow some sort of theming in future.
Anyway for your IDE you should be able to adjust that.

**Comment by svenefftinge** [comment]
@akosyakov we should think about the contributing css per theme name in the extension system.

**Comment by akosyakov** [comment]
@svenefftinge Can it be closed since we have [ThemeService](https://github.com/theia-ide/theia/blob/920f4e185ec64355bf92a0edc2879c70364615ee/packages/core/src/browser/theming.ts#L57)?

**Comment by svenefftinge** [comment]
Yes
