### ISSUE TITLE
Auto Save command seems unreliable

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#2982]
On occasion, when Theia starts (in browser or electron mode) I find the `Auto Save` menu item doesn't correctly toggle. It seems to make a difference whether an editor is open or not.

Has anyone else seen this issue?

**Comment by marcdumais-work** [comment]
@thegecko do you mean that you sometimes find that the state of the ```Auto Save``` menu item does not match the observed state of the auto-save feature? 

I have not noticed that, but also have not being paying attention to that menu item. Might you have had the auto-save preference also defined at the workspace level? 

Playing with this feature, I observe that it acts by directly set the ```editor.autoSave``` preference, at the  user storage level (<user's home>/.theia/settings.json. However it's also possible for the user to define that preference at the workspace level: <workspace path>/.theia/settings.json . 

When doing that, it will have precedence, for that workspace, over the same preference defined in user storage. When that happens, the menu item will not work correctly any more.

**Comment by thegecko** [comment]
My observation is that toggling the auto save menu item has no effect (e.g. if it's on, it stays on).

AFAIK preference files haven't been modified, so not sure if there is a clash as you describe.

I'm having trouble recreating it and it certainly doesn't break when I try to screen capture it!

I'll reopen this issue if I manage to record the issue.
