### ISSUE TITLE
Re-starting the server when two or more workspaces are in a browser generates errors.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2995]
Starting Theia in a browser generates errors on the server console
If you start Theia in a browser, it starts ok
If you add a second workspace in the browser, then select again Theia workspace 
Note: average loading time is also bad when there is more than one workspace available in a browser and re-starting the server . The secondd workspace could be very little, just a few files in it is enough.

Restart the server and press the refresh button of the browser for Theia workspace, then many errors appears on the server console.
1-
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2-
root ERROR TypeScript: (node:24318) UnhandledPromiseRejectionWarning: Error: geterr timeout

3- List of warnings:
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.

**Comment by kittaakos** [comment]
It is the same the [Reconnecting issues](https://github.com/theia-ide/theia/issues/3224).

**Comment by akosyakov** [comment]
We should make sure that language servers unregister all commands when disposed and register new on reconnection to get rid of warnings.
