### ISSUE TITLE
Switching to a fresh repository ends up in 'Bad revision' exception in git widget

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#3010]
If I have multiple repositories in a workspace and switch to a "fresh" one (one without any commits yet) an exception is thrown [in git widget](https://github.com/theia-ide/theia/blob/master/packages/git/src/browser/git-widget.tsx#L343). `Uncaught (in promise) Error: Request log failed with message: Bad revision.`
The repository was switched (one can see that in the statusbar) but because of the exception the git widget is not updated.
However, if I select this or another "fresh" repository again I don't get an exception and the git widget gets updated.

**Comment by kittaakos** [comment]
We also have to handle when there was a `git init` but there was no `git add . && git commit -m "blabla"` command yet? It ends up in a `fatal: your current branch 'master' does not have any commits yet`

**Comment by jbicker** [comment]
I've done that. Did a `git init` but no `add` resp. `commit`. What did you do to get `fatal: your current branch 'master' does not have any commits yet`?

**Comment by jbicker** [comment]
Where is that `fatal` exception thrown?

**Comment by kittaakos** [comment]
It is from the Git executable.
```bash
rm -rf delete-me--git-log \
&& mkdir delete-me--git-log \
&& cd delete-me--git-log \
&& git init \
&& git log
```
