### ISSUE TITLE
[ci] [appveyor] update git version used

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#3012]
I think we need a more recent native git installed for our Appveyor CI env, so that the git extension unit tests can pass. I do not see the git version being defined in our ```appveyor.yml``` however. 

https://ci.appveyor.com/project/kittaakos/theia/build/1.0.5589#L2271

**Comment by kittaakos** [comment]
Thanks for reporting, I will take care of it.

**Comment by kittaakos** [comment]
The external and the embedded (`dugite`) Git versions are the same: `2.17.1.windows.2`. The breaking change should be somewhere else.

**Comment by marcdumais-work** [comment]
Thanks for looking into this @kittaakos . I see that the last 4 commits have passed Appveyor CI, so it seems all is good.
