### ISSUE TITLE
error while loading shared libraries: libgconf-2.so.4

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#3026]
I followed the instructions here on Ubuntu 18.04:
https://github.com/theia-ide/theia/blob/master/doc/Developing.md

~/git/theia/examples/electron$ yarn run start ~/git/llvm/
yarn run v1.7.0
$ theia start /home/mark/git/llvm/
~/git/theia/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

I had to install this by hand:
  sudo apt-get install libgconf-2-4

**Comment by vince-fugnitto** [comment]
The [prerequisites](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites) for running the application on different operating systems has been 
updated thanks to @marechal-p. Please re-open the issue if it is still incomplete :)
