### ISSUE TITLE
Migrate to monaco 0.9 and monaco-languageclient 0.1

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#306]

**Comment by akosyakov** [comment]
See https://github.com/theia-ide/theia/pull/299/commits/7543ec244341c3bb8ad7814c5865fb5e97e431af

**Comment by hexa00** [comment]
This is kinda weird the title says update to 9 but the commit revers to 8 ? 
So I'm confused... was it 9 before and we wanted to make it work with 9 but decided to rollback instead?

**Comment by akosyakov** [comment]
I've tried to use 0.9 but it was not straightforward, so I've reverted it and put a link to the commit as a reminder.
