### ISSUE TITLE
Assert NPM version

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#309]
The [script](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#tldr) obviously contains an incorrect path for the examples.

If I start the script with the correct path, it complains about the missing `start` script:

```
git clone https://github.com/theia-ide/theia \
&& cd theia \
&& npm install --unsafe-perm\
&& cd examples/browser \
&& npm run start
```

**Comment by akosyakov** [comment]
@kittaakos could you try with #310?

**Comment by kittaakos** [comment]
Sure.

**Comment by kittaakos** [comment]
It is still broken. Please reference [attached log](https://github.com/theia-ide/theia/files/1158782/GH_309_full_console_log_01.txt).

**Comment by akosyakov** [comment]
Please try to use npm@4, it seems that you are using npm@3.

**Comment by kittaakos** [comment]
Although it is still running, it looks better. I keep you posted.

Can we assert the npm version: https://www.npmjs.com/package/assert-npm-version

**Comment by kittaakos** [comment]
Great, it works with your changes.

**Comment by akosyakov** [comment]
Yes, asserting would be great, `npm` suggests using `engines` for it: https://docs.npmjs.com/files/package.json#engines

**Comment by kittaakos** [comment]
I would be happy with any libraries if it works as expected.

**Comment by akosyakov** [comment]
it is obsolete with yarn

**Comment by kittaakos** [comment]
@akosyakov, what about #179?
