### ISSUE TITLE
In firefox the font in git comment field is wrong 

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#3090]
Firefox
<img width="285" alt="screen shot 2018-10-04 at 17 24 00" src="https://user-images.githubusercontent.com/28291421/46484843-ddb24780-c7fa-11e8-8ae7-10ecfa4bfc96.png">
should be like in Chrome
<img width="251" alt="screen shot 2018-10-04 at 17 24 26" src="https://user-images.githubusercontent.com/28291421/46484867-e99e0980-c7fa-11e8-8c77-c972a66ead44.png">

**Comment by boomanaiden154** [comment]
I was not able to duplicate this, getting the same font in both Firefox and Chrome. Chrome version 69.0.3497.100 and Firefox version 62.0.3. 
Chrome:
![chromecommitmessage](https://user-images.githubusercontent.com/39388941/46910808-14c1e080-cf00-11e8-8d78-7e068b1ee9ee.png)
Firefox:
![firefoxcommitmessage](https://user-images.githubusercontent.com/39388941/46910809-1be8ee80-cf00-11e8-8842-a4efcd5ef92a.png)

**Comment by vince-fugnitto** [comment]
closed thanks to #3460
