### ISSUE TITLE
Clipboard Service

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#31]
A common service to access the clipboard.
Related : https://github.com/electron/electron/blob/master/docs/api/clipboard.md

**Comment by akosyakov** [comment]
There won't be the central clipboard service but each widget can use the DOM clipboard API to listen `cut`, `copy` and `paste` events and read/write the system clipboard data.

It is handled by https://github.com/theia-ide/theia/pull/437.
https://github.com/theia-ide/theia/blob/e370525041f56f0abab2a2045a20c655be5cf4e7/packages/navigator/src/browser/navigator-widget.ts#L37-L62

**Comment by hexa00** [comment]
Could this work with the terminal too ?

**Comment by akosyakov** [comment]
One should check, the default browser editable elements automatically contribute to the clipboard data.  If not we need to add listeners.

**Comment by akosyakov** [comment]
Done with https://github.com/theia-ide/theia/pull/437
