### ISSUE TITLE
how to use it in react  ? 

### ISSUE THREAD

**Issue by hosseinmh** [theia-ide/theia#3104]
HI I'm new in theia ide 
I have  question that is how use theia ide in react as a component or use it in website as a page ?
thanks a lot :)

**Comment by akosyakov** [comment]
Currently, only via iframe, the shell assumes to be attached to the document body.

**Comment by hosseinmh** [comment]
that mean we cant use theia ide completly ?
and how can make api rest for use theai ide ?

**Comment by akosyakov** [comment]
> that mean we cant use theia ide completly ?

You can via iframe. Probably, there is already iframe react component. We don't have plans to make Theia a React component. It should be possible to develop with any JS frameworks.

> and how can make api rest for use theai ide ?

What API? Could you provide more context? Theia is using JSON-RPC over web sockets for communications, not REST.

**Comment by hosseinmh** [comment]
for example using django rest framwork to send and receive json 

but question is how to get json object from theia editor or how to make it

**Comment by akosyakov** [comment]
> for example using django rest framwork to send and receive json

Sorry, I am not familiar with it and how it is deployed. Generally, you should be able to access any URL from the frontend as for a usual web app.

> but question is how to get json object from theia editor or how to make it

Please look at `EditorManager`, it should allow you to access a current editor and its content.

**Comment by allahyar** [comment]
@akosyakov Is it possible to perform `FileSystem` related operations with REST? I mean is CRUD files.
I did not understand from the [documentation ](https://theia-ide.org/docs/json_rpc/)page how I should change the endpoint. You can provide more details.
