### ISSUE TITLE
add mini browser in theia ide 

### ISSUE THREAD

**Issue by hosseinmh** [theia-ide/theia#3107]
hi 
i have question that is can theia ide support browser preview inside of editor like below image 

<img width="621" alt="screen shot 2018-10-06 at 11 29 04 am" src="https://user-images.githubusercontent.com/12621753/46568993-2e40b680-c95b-11e8-89e9-7c8f33d605b5.png">

**Comment by akosyakov** [comment]
It is already supported via [@theia/mini-browser](https://github.com/theia-ide/theia/tree/master/packages/mini-browser) extension.

**Comment by hosseinmh** [comment]
this extension is installed but  not display mini browser 
can you explain how to use this extention ? 
thanks 
<img width="342" alt="screen shot 2018-10-06 at 1 29 09 pm" src="https://user-images.githubusercontent.com/12621753/46570107-e8d8b500-c96b-11e8-86d1-9b13dd2d4f2c.png">

**Comment by akosyakov** [comment]
For example, look at `Open With` content menu item for some HTML file. You can open it as well programmatically, e.g. to preview an app.

**Comment by hosseinmh** [comment]
oh thanks 
and is any way to show react project in mini browser ??
and how to change position of button ?
thanks a lot :)

**Comment by akosyakov** [comment]
> and is any way to show react project in mini browser ??

As far as I know, the mini-browser is a browser, so it should be able to display any HTML including react projects. @kittaakos correct me if I'm wrong.

> and how to change position of button ?

I guess you will need your custom extension where you can exchange an implementation.

**Comment by svenefftinge** [comment]
Please reopen if there is anything left to be done/discussed here.

**Comment by akhiljay** [comment]
is there an example implementation that opens up a mini-browser by default whenever you run theia in a browser?
