### ISSUE TITLE
[workspace] avoid revealing/activating editors on Workspace#applyEdit

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#3116]
Currently, when applying a workspace edit to a monaco workspace, the respective editors are opened, revealed and activated. For some applications that's a bit too much. E.g., when my graphical sprotty editor triggers a refactoring, I don't want the loaded editors to steel the focus. 

Could we consider just opening the editors (not reveal, not activate)? Or at least make that configurable that, i.e. by adding a `applyEdit(changes: WorkspaceEdit, options?: EditorOpenOptions)`?

Opinions?

**Comment by svenefftinge** [comment]
Yes, I think allowing additional options should be fine.
