### ISSUE TITLE
Add ability to configure debugger connection timeout

### ISSUE THREAD

**Issue by evidolob** [theia-ide/theia#3118]
Currently we have 10 second timeout, in some cases it's not enough, we need ability to configure it.

Proposal configuration:
```json
  {
    "type": "node",
    "request": "attach",
    "name": "Attach by PID",
    "connectionTimeout": 30
  }
```
`connectionTimeout` is not mandatory, default value is 10 seconds

**Comment by benoitf** [comment]
I found that option exists when analyzing the source code, it is called `timeout` for nodejs debugger
