### ISSUE TITLE
I am trying to install theia-ide on my machine locally. But, currently facing issue for vscode-ripgrep. I have tried installing with the latest version of yarn 1.10.1 but no luck. Stuck on it for a long any help would be highly appreciated..!

### ISSUE THREAD

**Issue by vsansare** [theia-ide/theia#3157]
yarn install v1.7.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-9fffde4f-fcdc-4bec-8181-f1b26a8b4afe > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[5/5] Building fresh packages...
[10/12] ⠐ find-git-repositories
[7/12] ⠈ oniguruma
[8/12] ⠈ vscode-ripgrep
[9/12] ⠈ dugite
error C:\Users\vsansare\Documents\Rockwell_IDE\theia_fresh\theia\node_modules\vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:

**Comment by kittaakos** [comment]
@vsansare, do you have a fork or a public GH repository with your changes?

Did you install [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools)? You will [need it](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#building-on-windows) if you do not have Python 2.x and Visual C++ Build Tools installed on your system.

```
npm --add-python-to-path install --global --production windows-build-tools
```

**Comment by vsansare** [comment]
> @vsansare, do you have a fork or a public GH repository with your changes?
> 
> Did you install [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools)? You will [need it](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#building-on-windows) if you do not have Python 2.x and Visual C++ Build Tools installed on your system.
> 
> ```
> npm --add-python-to-path install --global --production windows-build-tools
> ```

@kittaakos its a public GH repository and I have successfully installed window tools with  npm  --global --production windows-build-tools.

**Comment by kittaakos** [comment]
> its a public GH repository

Great! Where is it? I need a branch with your changes.

**Comment by kittaakos** [comment]
I see, you are hitting this problem: https://github.com/Microsoft/vscode/issues/28434#issuecomment-346199674

**Comment by vsansare** [comment]
I have [generated](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) and added github_token as env variable but still no luck!! :(

**Comment by kittaakos** [comment]
Please confirm:
 - If you type `set` in `CMD.EXE` you can see the `GITHUB_TOKEN` environment variable,
 - but when you type `yarn` (using the same `CMD.EXE` instance you used for `set`) it fails with the above-mentioned issue.

Is that correct?

**Comment by vsansare** [comment]
Yes

**Comment by kittaakos** [comment]
Does this work for you?
```
rm -rf vscode-ripgrep-test \
&& mkdir vscode-ripgrep-test \
&& cd vscode-ripgrep-test \
&& npm init -y \
&& npm i -S vscode-ripgrep
```

(It creates an NPM package and installs `vscode-ripgrep` into it.)

**Comment by vsansare** [comment]
@kittaakos resolved it was an internal proxy issues..Thanks for the help!! 👍

**Comment by trueman1990** [comment]
Still have this issue. proxy is set correctly.

**Comment by biaji** [comment]
Same here.  This issue is still there:

vscode-ripgrep's lib/postinstall.js can not download target url "https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2" if you behind a proxy.
