### ISSUE TITLE
[plug-in] create a file system watcher

### ISSUE THREAD

**Issue by akurinnoy** [theia-ide/theia#3163]
[Documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemWatcher)
Need for XML LS
Language servers may need to know changes on other files that are not only editor buffers: node_modules folder, yarn.lock, maven target folder ....

**Comment by mmorhun** [comment]
To avoid unneeded traffic between plugin and Theia it seems wise to filter file system events on Theia side and sent a message over network if a match found.
However, in out current model all messages from plugin are sent to Theia client side. In case of frontend plugin it is ok, but in case of backend plugin, when interaction with Theia server side only needed, we have traffic "loop". This is more general problem than this issue itself and is out of this issue scope.
