### ISSUE TITLE
[debug-cortex] External node process

### ISSUE THREAD

**Issue by arekzaluski** [theia-ide/theia#3176]
I've spotted today that `gdb.js` in debug cortex plugin is spawned as a separate node process (https://github.com/theia-ide/theia/blob/debug-cortex/packages/debug-cortex/src/node/debug-cortex.ts#L141). It works well when Theia is started in development environment. Unfortunately it fails when it is packaged inside electron and installed on the system.
In that case the node is not found and the process crashes. Any idea on how it can be fixed?

**Comment by marechal-p** [comment]
Isn't it just a matter of installing node on your system?
