### ISSUE TITLE
[lint] enable prefer const tslint rule

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#318]
https://palantir.github.io/tslint/rules/prefer-const/

And fix existing issues.

**Comment by marcdumais-work** [comment]
+1

**Comment by hexa00** [comment]
I wonder if there's a rule for enforcing ending a line with ';' too ? 
It's easy to forget

**Comment by akosyakov** [comment]
there is: https://palantir.github.io/tslint/rules/semicolon/
but I would use as `"semicolon": [true, "always", "ignore-bound-class-methods", "ignore-interfaces"]`, it is relative only for statements

**Comment by akosyakov** [comment]
@marcdumais-work I like an idea to enable it only for VS Code till we almost don't have this error in the repo instead of fixing 400 places at once.
