### ISSUE TITLE
PHP syntax highlighting support

### ISSUE THREAD

**Issue by digitalbaboon** [theia-ide/theia#3187]
GIven that it runs most of the internet, would make sense to have PHP's syntax highlighting support. Or maybe there's a way I can install it myself if there's no plans to add it in the default package?

**Comment by marcdumais-work** [comment]
We have a ```theia@php``` extension that's outside this repo, and so is not used in the example application, though you can easily add it yourself in e.g. ```example/browser/package.json``` and then rebuilt it.  I think you need composer installed before building.
