### ISSUE TITLE
Creating a file at a given path

### ISSUE THREAD

**Issue by ankitmithu007** [theia-ide/theia#3196]
Hi,

Presently in theia, we can create a file in the current directory using SingleTextInputDialog.
But I have a requirement where the user can give a path while creating a file.

![image](https://user-images.githubusercontent.com/14087747/47030828-2d462b00-d18c-11e8-8c7f-000c636f4fd8.png)

How is theia converting /c:/Users/ankkumar/Project(in my case it will be the destination path)  to file:///c%3A/Users/ankkumar/Project?
I want to use the same encoding so that it can be consitent.

**Comment by kittaakos** [comment]
> I want to use the same encoding so that it can be consitent.

I do not understand the encoding part, but you should use
 - `FileUri.create` to create a URI from an FS path =>`file:///c%3A/Users/ankkumar/Project`
 - `FileUri.fsPath` to convert the URI to ann FS path => `c:/Users/ankkumar/Project`

Note, I did not use `/c:/Users/ankkumar/Project` but `c:/Users/ankkumar/Project` becasue it was fixed: https://github.com/theia-ide/theia/pull/3419

I hope this helps.
