### ISSUE TITLE
'Git History' widget is broken

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3197]
The `Git History` widget does not seem to be working properly as of 72309f0. The widget continuously displays the loading screen, without the widget's content ever resolving, but also does not throw any errors to the console.

**Comment by AlexTugarev** [comment]
@jbicker, I think it this went broken in https://github.com/theia-ide/theia/commit/0a1302135fa89877e3108477a7c1a15cfe871649. before that change, we relied on the value of the `selectedRepository`, which was [stored](https://github.com/theia-ide/theia/commit/4f67b025090bbe34a7dd81d6eb8cd56094ad75bc#diff-dffe0f99410eb244c88700601ca91cabR73) in the local storage and [restored](https://github.com/theia-ide/theia/commit/4f67b025090bbe34a7dd81d6eb8cd56094ad75bc#diff-dffe0f99410eb244c88700601ca91cabR51) on next open, right?

The new mechanism tries to find a repo in the `allRepositories` array, which is updated asynchronously. So the time we open the the history widget after a cold start, the list of repositories might be empty.

Should `findRespositories` try to refresh if the list of all repos is empty?

![2018-10-19 12 46 39](https://user-images.githubusercontent.com/914497/47214871-95208f80-d39f-11e8-8bb4-fe621d277c26.gif)
