### ISSUE TITLE
[plug-in][languages] Register a document symbol provider

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#3200]
Register a document symbol provider.

Multiple providers can be registered for a language. In that case providers are asked in parallel and the results are merged. A failing provider (rejected promise or exception) will not cause a failure of the whole operation.

https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L2523

**Comment by azatsarynnyy** [comment]
It's partly implemented by the PR https://github.com/theia-ide/theia/pull/3258

**Comment by vparfonov** [comment]
As I understand it should be implemented in `workspace` namespace
