### ISSUE TITLE
[plug-in]  Add API for onDidSaveTextDocument in workspace namespace

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#3201]
An event that is emitted when a text document is saved to disk.

**Comment by RomanNikitenko** [comment]
The functionality was provided by  https://github.com/theia-ide/theia/commit/a94cec0bb618cfec5686a86692896c9aa9898a4e and https://github.com/theia-ide/theia/commit/6375debb66d28c3e5d6ec92863bfce99247e1ac7
