### ISSUE TITLE
It should be configurable at build time whether the minified or the dev monaco code is being by webpack

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#323]
Currently, it is always the minified one and it is hard to debug in the browser. Probably a `--production` flag should do the trick.

**Comment by akosyakov** [comment]
Handled by https://github.com/theia-ide/theia/pull/527

One should set `development` as `NODE_ENV` env variable to enable dev monaco code, by default minified is used.

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/pull/527
