### ISSUE TITLE
As an extension developer I would like to customize the default editor options for monaco

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#324]
A longer term solution could be via preferences; an extension can define additional monaco preferences that override the default ones. For instance in the preferences file for the extension:

```
"editor.monaco" : {
  // define customization...
}
```

A shorter term solution is in the [`monaco-editor-provider`](https://github.com/theia-ide/theia/blob/master/packages/monaco/src/browser/monaco-editor-provider.ts#L49). One should be able to subclass it and rebind the customized editor-provider for the extension.

**Comment by kittaakos** [comment]
@akosyakov What if my extension uses a third party extension that already customizes the editor provider? Do you have any comments on that? Thanks!

**Comment by akosyakov** [comment]
Subclass the editor provider of a third party extension? I don't know, it will depend on how third party extension works.
