### ISSUE TITLE
[java] Switch back to the original JDT LS 

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3250]
The semantic highlighting LS capability has been merged to the `master`, switch back to the original JDT LS download location.

**Comment by kittaakos** [comment]
We could also rebase the type-hierarchy fork from the jdt.ls master: https://github.com/kittaakos/eclipse.jdt.ls-gh-28

**Comment by tsmaeder** [comment]
@kittaakos I can download the latest jdt.ls in < 1 second (38mb) over my gigabit line. Maybe the problem is on your side?

**Comment by tsmaeder** [comment]
@kittaakos we now have the ability to extend jdt.ls with extra bundles. Let's stop doing forks!

**Comment by kittaakos** [comment]
Do you want to grab this task, @tsmaeder?
