### ISSUE TITLE
[tests] tests hanging

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#326]
running "npm test" in the theia root directory does not seem to work well with the latest master. The test suite seems to hang after having reported that the filesystem test pass. 

When I checkout the version from a day ago, the same thing happens. With the version from 2 days ago (commit: a54259c17c4c844bb6cd4e0b496085e8ddbeba6a), the test pass.

**Comment by akosyakov** [comment]
It includes UI tests for the browser. I've also noticed that if they fail then sometimes they are hanging.

**Comment by marcdumais-work** [comment]
Renamed issue for accuracy, since the problem might not be with the UI tests

**Comment by marcdumais-work** [comment]
I just retried with yarn (latest master) and it still hangs, but seem to give a better clue where it's happening. It does indeed seem to freeze in the browser UI tests : 
```javascript
$ yarn run rebuild:browser && lerna run test --scope "@theia/example-browser"
lerna info version 2.0.0
lerna info versioning independent
lerna info scope @theia/example-browser
[..................] - run: info scope @theia/example-browser

```

**Comment by marcdumais-work** [comment]
Update: the problem was apparently a weird proxy issue. I had a proxy setup through environment variables in my .bashrc . Once I remove these environment vars and kill the still running selenium server, the tests start to work again.
