### ISSUE TITLE
[Theia][Dialog] Open workspace dialog do not allow to scroll down and see the bottom items

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3278]
Open workspace dialog scroll not set to the right size, so unable to scroll to see the bottom items. We need to resize the window to see the bottom items.

![openworkspacedialogwrongscroll](https://user-images.githubusercontent.com/419051/47505042-570dea80-d83b-11e8-9454-556922eadd11.gif)

**Comment by vince-fugnitto** [comment]
closed thanks to #4278
