### ISSUE TITLE
Build Problem (yarn)

### ISSUE THREAD

**Issue by ainslec** [theia-ide/theia#328]
Related to issue #316 , raising this new issue for build problem with Yarn (version 0.27.5).

![image](https://user-images.githubusercontent.com/201870/28470238-0d00b03c-6e31-11e7-87ad-97b64fa6a87e.png)

I attach two logs, one is the command line log, the other is a log from an NPM process that seems to have been spawned by YARN (added .txt suffix otherwise github does not allow me to attach it).

[yarn output.txt](https://github.com/theia-ide/theia/files/1165962/yarn.output.txt)

[2017-07-21T15_16_08_028Z-debug.log.txt](https://github.com/theia-ide/theia/files/1165963/2017-07-21T15_16_08_028Z-debug.log.txt)

**Comment by ainslec** [comment]
NOTE : Also referenced this in (CLOSED) issue #316 

OK, so have pulled the most recent version, executing from git base, I cd into the theia folder (the folder containing "README.md" and ".travis.yml".

I enter the command "yarn", and it hangs. This is the console window after 7 hours:

![image](https://user-images.githubusercontent.com/201870/28619301-94fbd198-71ff-11e7-90ea-633f35511e39.png)

**Comment by IcyDoor** [comment]
I'm getting the same access errors aswell. I'm getting it on a linux system so i think that its not just a windows issue.
Attached logfile:
[logfile.txt](https://github.com/theia-ide/theia/files/1182992/logfile.txt)

**Comment by marcdumais-work** [comment]
Hi @IcyDoor ,

From the log, it seems that the build is trying to access things under the /root folder, which non-root users normally do not have permissions: 
```
Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
```
Looking on my machine , I do not have that file under /root, but instead under my own user. 

Is your nodejs installed globally for the system? i.e. through an OS package (rpm, .deb)? If so you might try nvm (https://github.com/creationix/nvm) instead, so that your node is installed under your home directory and you have all permissions to install global packages, etc...

**Comment by ainslec** [comment]
Perhaps someone could build an dev windows version? And if so, they could report the version of their tooling. I'm using git bash mintty 2.6.2, node v7.10.0, npm v4.2.0, yarm 0.27.5.

**Comment by IcyDoor** [comment]
@marcdumais-work Yeah, i thought so too. But the docker build is running as root. I even tried manually changing the permissions for the file acces and re-ran yarn manually as root. Still got the same access error for the same file :/
Will give nvm a shot though. Thanks for the response :)

**Comment by kittaakos** [comment]
See: https://github.com/theia-ide/theia/issues/316#issuecomment-319384017

**Comment by rcjsuen** [comment]
@IcyDoor I faced the same permission problem when trying to build with Docker. I ended up creating a new user and "starting from scratch" that way. Please see #376 if you are interested in my Dockerfile.

**Comment by IcyDoor** [comment]
@rcjsuen Fantastic! My re-build was successful when using your method. Thanks alot :)

**Comment by hexa00** [comment]
Closing, seems to be resolved. reopen if there's still a problem.
