### ISSUE TITLE
[proposal] [commands] add descriptions, owner to commands

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3287]
As a user sometimes I'd like to know a short description of what a `command` does, and potentially it's owner. A few things I've considered are:
 
**1.** Updating the `quick-open-command-palette` to add both short descriptions, and owners.
This can be handled through a preference to set the verbosity of the commands to tailor to all different types of users (ex: Only Label, Only Label and Owner, Only Label and Description, All 3)

<img width="1495" alt="screen shot 2018-10-26 at 9 17 57 am" src="https://user-images.githubusercontent.com/40359487/47568855-3196e480-d900-11e8-907f-c4ead37e1ace.png">

**2.** Update the `keyboard-shortcuts` widget to add a description of a command and any other details through a pop-over. Downside is that a user may not think to look in this widget to see command details.

**3.** Create a new widget called `commands-view` which shows all available commands and their details.

The main purpose is to have more transparently to end users of what commands do, where they come from, and how to use them.

**Comment by elaihau** [comment]
Looks nice. As a user I would know what commands I would lose if uninstall an extension.

**Comment by benoitf** [comment]
are you able to filter in command palette the commands per owner ?

**Comment by vince-fugnitto** [comment]
@benoitf I haven't done a full implementation as of yet, but I think we can definitely either include the `owner`/`description` field as part of our `fuzzy-searching`, and if we were really adventurous have regexp as part of our searching to search down to specific `owners`. What do you think? Do you think it'd be useful to filter by owner?

**Comment by benoitf** [comment]
my usecase was how to quickly see commands of a given owner (owner being for example a theia plug-in or an extension)

**Comment by vince-fugnitto** [comment]
@benoitf would you be fine with perhaps searching for `@theia/debug` or `@theia/plugin`, or would you rather we had a different construct?

**Comment by benoitf** [comment]
I was most wondering what could be done by user, like using a new hotkey (today we have empty to open files, > to open a command, wondering if with another key it can indicate on which owner we want to filter or if there are other ways)

either doing
```
in:"then here I have completion for all owners" and then I can type my command name
```
or if I type the owner name, it filters command by this owner name
```
> @theia/debug the name of the command
```
 or something else

**Comment by vince-fugnitto** [comment]
@benoitf I think it'd be a little overkill maybe to implement something so complex, almost to the point of a regexp search. I think the simplest solution would be that the `owner` field is searchable and if you'd like to search for `@theia/debug` then that's all that would be searched. We might run the chance of having some additional results due to `fuzzy-searching` but it'd be minor.

**Comment by vince-fugnitto** [comment]
I can prefix the commands in a similar way as vscode does @svenefftinge @akosyakov 
Are you fine with having command descriptions which can be handled through a preference?

**Comment by vince-fugnitto** [comment]
closing thanks to #3313
