### ISSUE TITLE
[test coverage] source files not tested not reflected in coverage report

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#330]
This is not ideal since it's equivalent to ignoring files that have zero test coverage, artificially making the coverage report seem better than it actually is. 

possible fix mentioned in this thread: 
https://github.com/gotwarlost/istanbul/issues/112

**Comment by marcdumais-work** [comment]
to reproduce: 
in theia home, run 
```bash
yarn test
```

check the reported coverage for the "core package":
```bash
firefox packages/core/coverage/index.html
```
in firefox, navigate to the coverage report for sub directory "browser"

compare the reported coverage to the files under theia/packages/core/src/browser : there's 11 .ts files in there, but only a single one has unit tests, "opener-service.ts". Only that file has coverage reported. The reported coverage for the "browser" directory is ~53%, but if the untested files were accounted-for, it would be much lower, reflecting reality.

**Comment by hexa00** [comment]
Why did you close it ?

**Comment by marcdumais-work** [comment]
oops, closed by mistake. Thanks Antoine

**Comment by akosyakov** [comment]
Because some extensions don't have the test script? I've removed it because without tests mocha always exists with 1 and it breaks the build. We can empty spec files to such extensions. Would it work?

**Comment by marcdumais-work** [comment]
@akosyakov I think that's one cause. Without the test script in the generated package.json, an extension will not attempt to run the tests, and we get no coverage info for that package (instead of 0% coverage). But adding back the test script does not seem to be enough; ATM individual source files under a package are not considered in the coverage report unless they are covered by some test, it seems.

**Comment by marcdumais-work** [comment]
addressed in https://github.com/theia-ide/theia/pull/338
