### ISSUE TITLE
[Debug] Adjust the "Open configuration" and "Add Configuration"  menu item

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3309]
"Debug -> Open  configuration" does nothing when the file "launch.json" is not available.
We have two choices:
  - We create a file ( "launch.json" ) with a template in it.
  - the button "Open Configuration" should be insensitive when the launch file is not available.

Same apply to "Add configuration"

![launchconfignotopening](https://user-images.githubusercontent.com/419051/47652032-386d6380-db5b-11e8-84d0-4566e6f891d2.gif)

**Comment by akosyakov** [comment]
a dup of https://github.com/theia-ide/theia/issues/3285
