### ISSUE TITLE
[plug-in] Support custom icons in the TreeView

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#3330]
For now only icons from [font-awesome](https://fontawesome.com/) are supported.
For that plugin provides class name as iconPath

```
{
    label: userName,
    iconPath: 'fa-user medium-yellow'
}
```

Tree View Item [API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TreeView) describes that we have also to support icons from a file and pass it using resource URI.

This feature is a path of https://github.com/theia-ide/theia/issues/2782

Demo plugin [tree-view-sample-plugin](https://github.com/eclipse/che-theia-samples/tree/master/tree-view-sample-plugin) should demonstrate the feature.

**Comment by azatsarynnyy** [comment]
should be fixed by https://github.com/theia-ide/theia/pull/5057
