### ISSUE TITLE
[editor] Format the text on saved.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3338]
When editing in any editors, on saved, the data inside the file should be formatted. The text should be aligned.

**Comment by paulmelnikow** [comment]
Prettier is designed to be integrated into editors to format on save. It has [many existing editor integrations](https://prettier.io/docs/en/editors.html).

Running it automatically on save would be a big help for Shields contributors (badges/shields#2783), and similarly for any other project using Prettier.

**Comment by jankeromnes** [comment]
Exciting! @paulmelnikow If I understand @lmcbout's pull request correctly, we "just" need to somehow hook the `monaco.editor.action.formatDocument` action up with Prettier for Shields, and set the `editor.formatOnSave` preference to `true`.

**Comment by jankeromnes** [comment]
See also https://github.com/gitpod-io/gitpod/issues/408

**Comment by sojohnnysaid** [comment]
is there a way to format with prettier on save now? Was trying:
```js
"[javascript]": {
    "editor.formatOnSave": true
}
```
but not working

**Comment by jankeromnes** [comment]
@sojohnnysaid I think you may also want to install https://github.com/prettier/prettier-vscode in Theia, e.g. by downloading a `.vsix` file, and by drag-and-dropping it into Theia's extension panel on the left.
