### ISSUE TITLE
[plug-in] Implement 'inspect' method WorkspaceConfiguration object

### ISSUE THREAD

**Issue by evidolob** [theia-ide/theia#3346]
Now we have [`throw new Error('Not implemented yet.');`](https://github.com/theia-ide/theia/blob/85e39052cefe0d28234610d5078cad0b86cefa05/packages/plugin-ext/src/plugin/preference-registry.ts#L146). We need implement that method to be more compatible with existing VS Code extensions.

**Comment by AndrienkoAleksandr** [comment]
Duplicated https://github.com/theia-ide/theia/issues/2289
