### ISSUE TITLE
[plug-in] Register a workspace symbol provider 

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#3353]
Implement the API for registering a workspace symbol provider.
[typescript doc](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7271)

**Comment by tsmaeder** [comment]
@JPinkney is working on this.

**Comment by evidolob** [comment]
@tsmaeder It seems that this issue is done, can you close it?
