### ISSUE TITLE
[menu] [terminal] align terminal menu with vscode

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3356]
**Proposal**
Create a new `Terminal` top-parent menu item used for both **terminal** and **task** commands.

**Reasons for Change**
- Align with `vscode`.
- Easier to quickly locate terminal and task commands which are grouped based on functionality.
- More extensible to add new terminal and task commands than placing them under other menu parents.

![selection_004](https://user-images.githubusercontent.com/40359487/47792117-b5324600-dcf1-11e8-924b-6c8ac2014167.png)

**Comment by l0rd** [comment]
What about "Terminal" in View menu (to be even more consistent with VS Code):

![image](https://user-images.githubusercontent.com/606959/47794932-c135fc00-dd21-11e8-89fe-e2037561af78.png)

**Comment by vince-fugnitto** [comment]
> What about "Terminal" in View menu (to be even more consistent with VS Code):

I'll add it there as well to view the terminal and align further with vscode thanks!

**Comment by marechal-p** [comment]
About the view menu, I'm not so sure it should go there:
In Theia, terminals are widgets. Views in Theia are some kind of singleton that usually can be toggled, unlike terminals now. With the way things are, I would feel like just having the `Terminal` menu should be enough?

**Comment by slemeur** [comment]
Just a small questions for my understanding, why terminals are "widgets" and not "views"? 

I think as a user of Theia I would not know if it's a view or a widget. I understand the concern, but I don't think we should worry too much about that. I'm more concern about the consistency. IMO the user should be able to see all the different IDE main components (debuggers, explorer, terminals, search) from the "View" menu.

**Comment by l0rd** [comment]
> Views in Theia are some kind of singleton that usually can be toggled, unlike terminals now.

I am mostly neutral about that but I am afraid a Theia user, with a VS Code background, won't appreciate the subtle difference between a singleton and a widget.

**Comment by marechal-p** [comment]
> I am mostly neutral about that but I am afraid a Theia user, with a VS Code background, won't appreciate the subtle difference between a singleton and a widget.

It actually was (is?) my case, but tools can be different. In the current case with the terminals, I wonder what would be better though, is it something that should be changed?
