### ISSUE TITLE
[preview] Specify how Preview should open when there are more than two dock panels

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3376]
### This is the expected behavior for one or two dock panels.
This task is to define how it should behave when there are more than two dock panels (, and they are aligned horizontally) and adjust the behavior if required.

----

I would expect the Preview to open in the left-hand side dock panel. Instead, it opens in the right-hand side.

![screencast 2018-11-02 13-25-31](https://user-images.githubusercontent.com/1405703/47915458-3a109180-dea3-11e8-98ca-595f02136714.gif)

Is it a bug or feature. If it is a feature, what is the expected behavior when there are more than two dock panels in the main part?

Edit: added upfront clarification.

**Comment by AlexTugarev** [comment]
it's the expected behavior, and it should be opened in the tab folder next to the source editor.

![2018-11-02 13 45 22](https://user-images.githubusercontent.com/914497/47916191-9c6a9180-dea5-11e8-8df5-5dbcbc0c78f3.gif)

on the position, left or right, well this could be indeed a configurable behavior. opening it to the right was done to align with vscode.

**Comment by AlexTugarev** [comment]
atom does it the same way, cf. https://github.com/atom/markdown-preview

**Comment by AlexTugarev** [comment]
@kittaakos, that I'd consider a bug ;-) it finds the editor for `lerna.json` as a `ref` widget to open in the same tab folder. I think it should follow the simple rule (from user's pov) and split to the right.

**Comment by kittaakos** [comment]
It is a generic issue in our shell and Phosphor. When opening the Preview next to the Code Editor, it [finds another TabBar in the main panel](https://github.com/theia-ide/theia/blob/e8dd128c25294b23741cc345067952ef7cd85864/packages/core/src/browser/shell/application-shell.ts#L636).

**Comment by AlexTugarev** [comment]
I thought it's because [only a single tab bar](https://github.com/theia-ide/theia/blob/master/packages/preview/src/browser/preview-contribution.ts#L190) is consider by mistake.

**Comment by kittaakos** [comment]
Please ignore my comment. The bug was here: https://github.com/theia-ide/theia/blob/e8dd128c25294b23741cc345067952ef7cd85864/packages/preview/src/browser/preview-contribution.ts#L195
