### ISSUE TITLE
Lost panels in debug view

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#3377]
It seems that recent changes led to the loss of the individual panels (variables, call stack, threads). This means we cannot scroll the panel individually. This poses a problem as soon as we have deep stacks or complicated object structures: when we are looking at some object structure and we want to go one stack frame up and then look at those variables, we need to scroll up and down all the time.
Individual panels should be resizeable and have their own scrolling

**Comment by svenefftinge** [comment]
The previous state was super rough and therefore had lots of UX problems. We decided to go with how chrome developer tools do it, as it works well for us and is much simpler.
Would be ok to change it as you suggest. I.e. to be like in VS code, with sizing and individual scrolling per panel, though.

**Comment by svenefftinge** [comment]
> We're glad to fix any crap you find, but please involve us.

Cool. You can of course create a PR so the panels are resizable and scrollable similarly to VS Code.
