### ISSUE TITLE
Open workspace and closing tab race condition

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#3378]
[Illustration](https://giant.gfycat.com/CapitalDistinctBunting.webm)

Somehow, if you open a new workspace that spawns in a new tab and happen to close the old one before Theia's loaded the new tab, you will end up on the workspace you just closed.

1. Open a workspace (tab1)
2. Open new workspace from tab1 (tab2 should open)
3. Close tab1 before tab2 finished loading

Result:
- tab2 displays workspace that was on tab1 (which you closed).

**Comment by marechal-p** [comment]
VS Code now always reuse the window you currently have when you open a new workspace, and only when you do `File > New Window` will you have a new window, without any workspace set.

**Comment by marechal-p** [comment]
https://github.com/theia-ide/theia/pull/3135 would be one way to fix it!

**Comment by elaihau** [comment]
Could we close this one since #3135 has been merged ?
