### ISSUE TITLE
[plug-in] SymbolInformation from plugins is not consistent with VSCode (Plugin API)

### ISSUE THREAD

**Issue by JPinkney** [theia-ide/theia#3387]
Hi, I still haven't completely figured out whether this is a bug or not but while testing https://github.com/theia-ide/theia/issues/3353 I have found an inconsistency between creating a symbol information in VSCode vs Theia.

Currently, if you want to create a symbol from an extension inside VSCode you can do: 

```typescript
new SymbolInformation('test', 0, 'test23', undefined)
```

which creates a symbol information object with name as 'test', kind as 0, container name as 'test23' and location as undefined.

However, in Theia the line above throws an error saying: "Argument of type '"test23"' is not assignable to parameter of type 'Range'. I tried looking into it but i'm not sure if its an issue with constructor overloading or something else.

For more info:

I am able to create symbol informations in theia using this line:
```typescript
new theia.SymbolInformation('test', 0, 'test23', new theia.Location(theia.Uri.parse("some uri"), new theia.Range(new theia.Position(1, 1), new theia.Position(1, 1))))
```

and that works fine. 

This particular issues comes up when you have a workspace provider

```typescript
    export interface WorkspaceSymbolProvider {
        provideWorkspaceSymbols(query: string, token: CancellationToken | undefined): ProviderResult<SymbolInformation[]>;
        resolveWorkspaceSymbol?(symbol: SymbolInformation, token: CancellationToken | undefined): ProviderResult<SymbolInformation>;
    }
```

and you want to resolve the symbols location inside of resolveWorkspaceSymbol. You shouldn't need to provide the location In order to do this you (and in VSCode you don't need to) but in Theia currently you do.

**Comment by benoitf** [comment]
@JPinkney I suppose it's linked to strict checking (where in one case `undefined` or `null` is accepted while in another case it's a different value)

https://github.com/theia-ide/theia/blame/345dc6060be0003ad91b5434b17b19fbaf66a262/packages/plugin-ext/src/plugin/types-impl.ts#L1010-L1012 should have also `| undefined` for location

a new unit should be provided to be sure it will always be like that. (spec.ts file like https://github.com/theia-ide/theia/blob/345dc6060be0003ad91b5434b17b19fbaf66a262/packages/plugin-ext/src/plugin/type-converters.spec.ts)

@JPinkney do you plan to work on it ?

**Comment by JPinkney** [comment]
I can work on it since its needed for https://github.com/theia-ide/theia/issues/3353

**Comment by tsmaeder** [comment]
> https://github.com/theia-ide/theia/blame/345dc6060be0003ad91b5434b17b19fbaf66a262/packages/plugin-ext/src/plugin/types-impl.ts#L1010-L1012 should have also `| undefined` for location
> 

Do we _really_ need a constructor like this:

```
constructor(name: string, kind: SymbolKind, rangeOrContainer: string | Range, locationOrUri?: Location | URI, containerName?: string) {
```

IMO, the use of varying parameter lists was one of the worst aspects of Javascript "style" and I don't think we should use it in our code.
