### ISSUE TITLE
Build problem with Yarn (Windows 10)

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#339]
I used the yarn build tool in a GIT bash under Windows 10 with Node version 8.2.1 (yes I know I should use the older version 7.x.x). 

Yarn built everything fine. But I cannot run "yarn run start" because the goal "start" is missing in my configuration.  I can see "rebuild:browser" etc. but no "start".

Here are my commands:

Project commands
   - bootstrap
      node scripts/generate.js && lerna bootstrap --hoist -- --no-optional
   - build
      lerna run build --stream
   - clean
      lerna run clean --parallel
   - clean:rebuild
      rimraf .browser_modules
   - preinstall
      cd generator-theia && yarn
   - prepare
      yarn run bootstrap && yarn run clean && yarn run clean:rebuild && yarn run build
   - prepublishOnly
      yarn run test
   - rebuild:browser
      node scripts/rebuild.js --target=browser
   - rebuild:electron
      node scripts/rebuild.js --target=electron
   - rebuild: electron:debug
      DEBUG=electron-rebuild && yarn run rebuild:electron
   - refresh
      lerna clean --yes && yarn run bootstrap
   - test
      yarn run test:theia && yarn run test:electron && yarn run test:browser
   - test:browser
      yarn run rebuild:browser && lerna run test --scope "@theia/example-browser"
   - test:electron
      yarn run rebuild:electron && lerna run test --scope "@theia/example-electron"
   - test:theia
      lerna run test --scope "@theia/!(example-)*" --parallel
   - watch
      lerna run watch --scope "@theia/!(example-)*" --parallel

**Comment by akosyakov** [comment]
The doc says you should do `cd examples/electron` first or `cd examples/browser`.

**Comment by UdoW** [comment]
Ohh, I missed that part. You are right. I changed to the browser directory and it works now. Thanks. You can close this issue as "Works as expected".
