### ISSUE TITLE
Writing a plugin that is both backend and frontend

### ISSUE THREAD

**Issue by Mosho1** [theia-ide/theia#3391]
Hi, I would like to write a plugin that has features on both BE/FE. From the code I see they are mutually exclusive. Is this desirable to have in the project? I'm willing to work on a PR!

**Comment by kittaakos** [comment]
> From the code I see they are mutually exclusive

It should be possible. See, for instance, the Git extension. There are multiple frontend and backend modules in one single extension.

https://github.com/theia-ide/theia/blob/0ce38188ed3010662b90feacd3097d1b7eeb36c1/packages/git/package.json#L28-L45

**Comment by marcdumais-work** [comment]
Hi! Just to confirm: it seems that the question was about plugins, not extensions? I know it can be confusing having those two mean distinct things for Theia, but that are also often considered synonyms. 

@Mosho1 ?

**Comment by Mosho1** [comment]
While I worked it out in another way, yes I was asking about plugins rather than extensions.
