### ISSUE TITLE
Configuring language server behavior. Cannot mute the warnings

### ISSUE THREAD

**Issue by vivasahari** [theia-ide/theia#3394]
Hi! I use Theia for my gradle project. I constantly see the warning that says 'Failed to start Java language server: The scopes are already registered for language: java.". I need Java/Groovy syntax highlighting but I do not necessarily need Theia to analyse my project and throw these kind of warnings. Can anyone point me to documentation that specifies where this can be turned off so that I do not get these warnings?

**Comment by akosyakov** [comment]
@vivasahari please try the latest master, it should have been addressed: https://github.com/theia-ide/theia/commit/68d8faca310db5c1f333189d69149e3b8cb0fa65#diff-1760f3be482ff09286dd69d81895df0dL49

**Comment by vivasahari** [comment]
Hi @akosyakov. Yes, the issue seems to have gone with the latest master code. Thank you

**Comment by kittaakos** [comment]
Please reopen if required.
