### ISSUE TITLE
[Question] Is it possible to use Java for the backend ?

### ISSUE THREAD

**Issue by Zarfoux** [theia-ide/theia#3396]
Hi,
I made some RCP Eclipse application, write in JAVA with SWT for the UI.
I want to switch these RCP application in RCP Theia application, but i want to know if is possible to re-use some code to do it  ? 
In this picture , there is backend Java, how can i do that ?
![image](https://user-images.githubusercontent.com/16539745/47992076-3885da00-e0ec-11e8-88b4-7eda054b616b.png)

**Comment by akosyakov** [comment]
It is not really possible right now. The main backend process is Node.js process. But you can spawn a child java process from it and forward JSON-RPC messages between the frontend and java process. For example, language servers and debug adapters are implemented in this way.

**Comment by hihijain** [comment]
> It is not really possible right now. The main backend process is Node.js process. But you can spawn a child java process from it and forward JSON-RPC messages between the frontend and java process. For example, language servers and debug adapters are implemented in this way.

Hello,
I am also looking similar kind of implementation. I want to have theia backend in Java. is it possible to share some examples on this? That would be really helpful.

Thanks
