### ISSUE TITLE
'Open Recent Workspace' menu item no longer displays

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3421]
As of 9b08af17c5dde9464e17af68ee6b71bcf8552c44, the menu item for `Open Recent Workspace` no longer displays.

**Comment by akosyakov** [comment]
@vince-fugnitto will you care about it? the check should be inverted

**Comment by vince-fugnitto** [comment]
@akosyakov I can take care of it if you'd like :)

**Comment by vince-fugnitto** [comment]
@akosyakov 
The problem that I notice is that we are waiting for the promise of `this.workspaceService.rencentWorkspaces` to resolve before the command can be registered. 

This however is too late for the `menu` item as he will never get rendered if the command is not yet registered. This means that the `Open Recent Workspace` menu item will never be rendered. I have my doubts also on whether this would work on Electron as well.

**Comment by vince-fugnitto** [comment]
just for my information, why did we need to perform the check before registering the command ?

**Comment by akosyakov** [comment]
My initial motivation was to remove `onStart` callback, since it was fetching recent workspaces from the backend and delaying showing the shell to a user. I'm fine with any fix if it does not reintroduce `onStart` with remote calls.

**Comment by vince-fugnitto** [comment]
@elaihau what I'll do is remove the async calls, and not rely on `hasHistory` as before and instead display `No Recent Workspaces` if a user attempts to use the command without any recents. This will fix the menu issue, as well as your onStart problem

**Comment by vince-fugnitto** [comment]
> Is this related: #3429?
> 
> It breaks electron.

yes #3427 should fix it :)
