### ISSUE TITLE
Support source control other than Git

### ISSUE THREAD

**Issue by westbury** [theia-ide/theia#3423]
We have a need to support Mercurial repositories in our Theia-based product.  We currently do this by writing a shim that implements the Git interface over Mercurial.  We also need to rebind Git to a Git implementation that determines the repository type on every function call and delegate accordingly.  This works well for presenting the commit and history data.  For committing changes, it is usable, though as Mercurial has no concept of the index all changes are marked as 'staged'.  However we would like to improve the support for Mercurial by showing UI in the Git and Git History views that is appropriate for Mercurial.

To support multiple repository types in a clean way, we need the following refactorings:
1.  The Git and Git History views should be containers that determine the type of the selected repository and render the appropriate content widget.  If a single SCM is supported then the Git and Git History views will take their titles etc. from the content widget, otherwise they will get the title should be more generic, eg. SCM and SCM History.
2. The Git Widget itself needs some refactoring to split UI rendering likely to be common to many SCMs is separated from Git specific stuff.  This needs to extend to GitHistory and GitDiffWidget, and to the GitItem and GitChangesListContainer elements.

A start to this work is at https://github.com/westbury/theia/tree/git-refactor

**Comment by svenefftinge** [comment]
We should rewrite the git extension and bind the git commands to the vscode plugin API, so we can reuse the respective extensions: https://github.com/theia-ide/theia/issues/4103
Will be quite some work and restructuring but more sustainable way.

**Comment by westbury** [comment]
Closing this issue because the work has been done by @vinokurig
