### ISSUE TITLE
Disabled secondary button looks like main button in dark theme

### ISSUE THREAD

**Issue by micellius** [theia-ide/theia#3430]
There are two flavours of buttons: "main" and "secondary". Currently, disabled "secondary" button have a styling of disabled "main" button in the dark theme. In my opinion this UX is confusing users, since it changes semantic meaning of the button. My proposal is to have a separate style for disabled "secondary" buttons.

__Current__

![screen shot 2018-11-07 at 19 27 04](https://user-images.githubusercontent.com/410200/48149628-417dd380-e2c5-11e8-98e3-9e446c92fce2.png)

__Proposed (Option 1)__

![screen shot 2018-11-07 at 19 20 58](https://user-images.githubusercontent.com/410200/48149641-4e022c00-e2c5-11e8-96cf-e26d8151a1ba.png)

__Proposed (Option 2)__

![screen shot 2018-11-07 at 19 48 03](https://user-images.githubusercontent.com/410200/48149949-15af1d80-e2c6-11e8-977a-d9cdacfd72fa.png)

The first option IMHO looks better and makes less disruption for current look and feel, but the second is more aligned with bright theme, where "main" button gets styles of "secondary" when disabled.

__Bright Theme (Current)__

![screen shot 2018-11-07 at 19 25 49](https://user-images.githubusercontent.com/410200/48150070-5ad34f80-e2c6-11e8-9e4e-791007715da9.png)

Please, let me know, which option is preferable, and I'll send a PR.

**Comment by vince-fugnitto** [comment]
I think option 1 looks great! It means we can keep two different colours of buttons, each having their own disabled state. We can adjust to having the same behaviour for white theme with a blue disabled for main

**Comment by micellius** [comment]
@vince-fugnitto Thanks for feedback!

If we take the option 1 and apply same pattern to bright theme, the result will look like this:

![screen shot 2018-11-08 at 8 38 04](https://user-images.githubusercontent.com/410200/48181909-06fe5000-e332-11e8-9a0f-fcd5b13bd97d.png)

In this case both dark and bright theme use `--theia-accent-color3` for disabled "main" button.

**Comment by micellius** [comment]
PR #3433 was merged, I'm closing the issue.
