### ISSUE TITLE
Split Plugin API on front-end and back-end parts

### ISSUE THREAD

**Issue by tolusha** [theia-ide/theia#3449]
To support Plugin API for debug I have to implement method that starts debugging:
https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L8358

It basically implies starting Debug Adapter process which isn't possible to achieve due to the fact that code might be run in Web Worker.

@benoitf @evidolob @tsmaeder

**Comment by tsmaeder** [comment]
Theia back-end plugins are not run in the browser (that would never work). So you can implement the API in the back-end and everyone is happy, no?

**Comment by tolusha** [comment]
Back-end plugin tells me to start debugging and my code (which implements debug API) is located at front-end.

**Comment by akosyakov** [comment]
@tolusha communications between frontend-backend are bidirectional, it should be possible to send a request to the frontend to start a debug session.

**Comment by tolusha** [comment]
@akosyakov 
Starting debug session implies launching debug adapter which can be done only at back-end.

**Comment by akosyakov** [comment]
I meant to expose `DebugSessionManager.start` from the frontend to the plugin backend:
- the plugin backend requests the debug frontend to start a new session
- the debug frontend requests the debug backend to create a new session adapter, as it's now
