### ISSUE TITLE
[ux] Tab-bar toolbar layout issues

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3453]
It is ugly when there are multiple contribution items and the space is quite small.

![screen shot 2018-11-09 at 15 51 42](https://user-images.githubusercontent.com/1405703/48269280-7ad65080-e437-11e8-9f0f-78f7a0a212c8.jpg)

![screen shot 2018-11-09 at 16 17 11](https://user-images.githubusercontent.com/1405703/48270691-ed94fb00-e43a-11e8-9fa1-e8e0400577cb.jpg)

**Comment by vitaliy-guliy** [comment]
Could you make a screenshot of the whole window with Theia?
