### ISSUE TITLE
Problems installing hello-world-extension

### ISSUE THREAD

**Issue by s3dse** [theia-ide/theia#3461]
Hello,

probably a newbie question: I followed the "Authoring an extension" example in the Theia gitbook and ran the yeoman generator. Further, I did the "Build your own IDE" steps in a separate project. Combining the two, as plugging the hello-world-extension into the custom IDE fails for me. I chose electron as target and while the shell does start up, it hangs displaying the busy-indicator.

Custom Theia package.json:

```Json
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next",
    "@theia/java": "next",
    "@theia/keymaps": "next",
    "hello-world-extension": "../theia-hello-world/hello-world-extension"
  },
  "devDependencies": {
    "@theia/cli": "next"
  },
  "theia" : {
    "target":"electron"
  }
}
```

`yarn`
`yarn theia build`
Apart from some keybinding collisions no further errors are shown.
`yarn theia rebuild:electron`
`yarn theia start`
 When I issue the `--inspect` flag, with custom or default port, the application stops as the given port is already in use (this seems to be a node issue).

[Edit] I also tried to install the extension from a local registry ([Verdaccio](https://verdaccio.org)) with no success. 

Am I missing something? 
Thanks in advance.

**Comment by s3dse** [comment]
I'm trying to reproduce the issue but when I run `yo theia-extension hello-world-extension` I get the following error:

```
hello-world-extension: $ tsc
hello-world-extension: ../node_modules/@theia/core/lib/browser/keys.d.ts(139,19): error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
hello-world-extension: ../node_modules/@theia/core/lib/browser/keys.d.ts(139,19): error TS2552: Cannot find name 'Shift'. Did you mean 'SHIFT'?
hello-world-extension: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
hello-world-extension: error Command failed with exit code 2.
hello-world-extension: npm ERR! code ELIFECYCLE
hello-world-extension: npm ERR! errno 1
hello-world-extension: npm ERR! hello-world-extension@0.0.0 prepare: 'yarn run clean && yarn run build'
hello-world-extension: npm ERR! Exit status 1
hello-world-extension: npm ERR! 
hello-world-extension: npm ERR! Failed at the hello-world-extension@0.0.0 prepare script.
hello-world-extension: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by akosyakov** [comment]
we need to add it flag in tsconfig generated by the extension generator

**Comment by vince-fugnitto** [comment]
> we need to add this flag (skipLibCheck) in tsconfig generated by the extension generator

I don't seem to have push access to the generator to make the change, is it something you want to take care of?

**Comment by benoitf** [comment]
@akosyakov @vince-fugnitto but IMHO generated `d.ts` files should still have valid definition as well (if some people don't want to disable the library check) (provided by PR https://github.com/theia-ide/theia/pull/3711)
`skipLibCheck` is kind of workaround, so probably some tests in theia are missing to detect that `d.ts` can be compiled ?

**Comment by vince-fugnitto** [comment]
> @akosyakov @vince-fugnitto but IMHO generated `d.ts` files should still have valid definition as well (if some people don't want to disable the library check) (provided by PR #3711)
> `skipLibCheck` is kind of workaround, so probably some tests in theia are missing to detect that `d.ts` can be compiled ?

I agree it's a workaround, that's why I originally wrote #3711 to fix the issue in `keys.d.ts`. 
I'm all for having additional tests to make sure the definition files are valid if its possible.

**Comment by akosyakov** [comment]
@benoitf agree. Not sure, what can be done generally. tsc should not generate broken typings for valid code. It's started with switching to tsc 3.1, maybe with 3.2 they fixed it.

**Comment by s3dse** [comment]
Thanks @vince-fugnitto! 
I was able to reproduce the issue. Unfortunately the problem remains. To be safe, I started from scratch with the following steps
- https://www.theia-ide.org/doc/Composing_Applications.html
- https://www.theia-ide.org/doc/Authoring_Extensions.html
- added the extension to the dependencies of the custom Theia application
- ran `yarn`, `yarn theia build`, `yarn theia start`

The application log says
```
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 12579]
Server worker is ready to accept messages. [ID: 1 | PID: 12579]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
```
The browser only shows the busy indicator.

**Comment by vince-fugnitto** [comment]
@vince-fugnitto when the browser was displaying the busy indicator, did you notice any error logs within the `dev-tools` ? I'll try on my end to see if I have similar issues.

**Comment by vince-fugnitto** [comment]
That usually happens when there is a mismatch with pulling mutliple different versions of the same dependency, is your repository public? I can take a look for you 😊

**Comment by s3dse** [comment]
Sure, https://github.com/s3dse/custom-theia
Thanks!

**Comment by vince-fugnitto** [comment]
> Sure, https://github.com/s3dse/custom-theia
> Thanks!

I was able to find the [issue](https://github.com/s3dse/custom-theia/blob/6b27cd1dd4cbcb30570382fb320cac4538bdcbd7/theia-hello-world-extension/hello-world-extension/package.json#L12) :) your custom extension that you are referencing has `@theia/core: latest` while the theia version you are building is using `next` everywhere.

 If you upgrade your extension `@theia/core` to next, you won't be pulling in two different versions of the same dependency which causes the error. I was able to make the change, and it worked for me afterwards.

Just to be sure when rebuilding, you can delete your `yarn.lock` file just to be safe and truly pull the updated dependencies. Remember when building your extension again with next, to also update the dependencies in both the [browser](https://github.com/s3dse/custom-theia/blob/6b27cd1dd4cbcb30570382fb320cac4538bdcbd7/theia-hello-world-extension/browser-app/package.json#L1-L32) and [electron](https://github.com/s3dse/custom-theia/blob/6b27cd1dd4cbcb30570382fb320cac4538bdcbd7/theia-hello-world-extension/electron-app/package.json#L1-L32)

Let me know if you have additional issues :)

**Comment by s3dse** [comment]
I missed that 😊  It works. Many thanks!
