### ISSUE TITLE
How to change servername and port?

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#347]
How can I change the servername and port of the Theia examples?

At the moment everything is started from localhost and port 8080. 

I need to change the server side to a dedicated server name and port.

**Comment by akosyakov** [comment]
For the webpack dev server or for the express server?

**Comment by akosyakov** [comment]
For the former you should change environment variables, look at `webpack.conf`. For the latter you should update the yo config and rerun `yo theia:browser --force`.

**Comment by UdoW** [comment]
How to call yo?

**Comment by akosyakov** [comment]
from the cli: https://www.npmjs.com/package/generator-theia#getting-started

**Comment by UdoW** [comment]
yo still does not work.

**Comment by akosyakov** [comment]
`npm install -g yo`

**Comment by UdoW** [comment]
I did this under Debain 8 and my user has no sudo rights so I had to install it with my admin user. But my normal user cannot see the yo command. 

I will try it under my Windows machine.

**Comment by UdoW** [comment]
Under Windows the yo installation worked and I could change the host name.

But from another machine in the same network their is still no access to my local theia instance. The browser on the other machine tells me:

ERR_CONNECTION_REFUSED
