### ISSUE TITLE
[terminal] Strange border in terminal with Firefox

### ISSUE THREAD

**Issue by geropl** [theia-ide/theia#3472]
Screenshot:
<img width="937" alt="screen shot 2018-11-13 at 12 22 09" src="https://user-images.githubusercontent.com/32448529/48413596-7c11c100-e748-11e8-8b5b-d043b368f550.png">

**Comment by vince-fugnitto** [comment]
I unfortunately could not reproduce it in Theia, can you verify? Perhaps it is a problem from Gitpod?

**Comment by geropl** [comment]
I was able to reproduce similar border issues with pure Theia (this time the left-bottom corner) but was not fast enough for a screenshot. Since then I struggle to reproduce it in either Theia or Gitpod.

Firefox version: 63.0

**Comment by vince-fugnitto** [comment]
thanks! I'll keep an eye out for it and see if I can find the reason

**Comment by svenefftinge** [comment]
closing in favor of #4665
