### ISSUE TITLE
How to set the root-dir option?

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#349]
I try to start the browser example in another root dir.

I saw the "missing" option --root-dir an tried to set a new one with:

yarn run start -- --root-dir="absolute path"

But it does not recognize my option. How do I add the option --root-dir to the yarn call?

**Comment by kittaakos** [comment]
Thanks for asking @UdoW, it seems to be broken.

When I start the application with `yarn run start -- --root-dir=/Users/something`, then the `arg` variable in the `default-workspace-server` is `undefined` so it falls back to the `cwd`.

If I log the `process.argv` to the console I can see the following:
```
[ '/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node', '/Users/akos.kitta/git/theia/examples/browser/src-gen/backend/main.js' ]
```

None of them is my path for sure. I think it is not even passed into the node process.

**Comment by akosyakov** [comment]
It would be possible to pass args with https://github.com/theia-ide/theia/pull/527, e.g.: `npx theia browser --root-dir=/Users/something`

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/pull/527
