### ISSUE TITLE
[plug-in][tasks] Add tasks.onDidStartTask API

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#3505]
Add [`tasks.onDidStartTask`](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L5079) API to allow a plugin be notified when a task is started.
There're several useful links - https://github.com/eclipse/che/issues/11458#issuecomment-438950509

**Comment by RomanNikitenko** [comment]
[PR](https://github.com/theia-ide/theia/pull/3826) for the issue
