### ISSUE TITLE
"Upload/Copy Files into Workspace" Command

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#351]
Users should be able to copy local files and folders into the development workspace.

**Comment by marcdumais-work** [comment]
I did a quick search and found the following tutorial that might be interesting: 
https://www.thepolyglotdeveloper.com/2016/02/upload-files-to-node-js-using-angular-2/
https://scotch.io/tutorials/express-file-uploads-with-multer

**Comment by hexa00** [comment]
Seems to me it would be better to have a dedicated service for that outside of theia... like ssh, samba, ssh-fs ... whatever...
And maybe an easy way to have the user use these services ?

**Comment by svenefftinge** [comment]
Which security concerns?
Please note that we should find a way that works locally (electron) and remotely. 
I'd prefer a drag 'n drop feature, so I could drag local files onto the navigator, like I can do in google drive.

**Comment by hexa00** [comment]
It may look bogus as security but some would like to avoid having a direct http link to the files for example to download the workspace outside of theia.
I thought maybe the interface for upload would allow that too...

And the feature may be more complex then it looks, how to handle big files, incomplete transfers, progress...

I mean maybe all of that doesn't have to be baked-in to theia directly...?

**Comment by svenefftinge** [comment]
What do you mean with baked-in? Of course is it should not be in `core`or mandatory at all, but I'm pretty sure it is an important feature to get your local files into a workspace.

**Comment by hexa00** [comment]
Yes it is important.

I just mean we should use http or whatever under the hood, and not go through a theia api for file upload. I guess that went without saying..

And if we do use http make sure we get permissions/max file size stuff right...

**Comment by marcdumais-work** [comment]
Ericsson just open-sourced this - the description is not too clear about the content, but maybe worth it to investigate if we could re-use?

https://github.com/Ericsson/c3-drop

**Comment by lmcbout** [comment]
A new version for the Drag & Drop is available for review using the FileSystem

**Comment by akosyakov** [comment]
Could you update the PR?

**Comment by marcdumais-work** [comment]
fixed in PR #868
