### ISSUE TITLE
External extension not working after some updates to the master branch

### ISSUE THREAD

**Issue by uniibu** [theia-ide/theia#3516]
I was using my own theia vue extension https://www.npmjs.com/package/@devpodio/theia-vue-extension and it was working perfectly until i decided to rebuild my theia to get the latest updates on `next`. 

Theia now throws an error about `decorate` twice on `Widget.ts` at theia/core. It also now throws a warning during build about Reflect.ts not being found.

I did some digging and it might be related to https://github.com/inversify/InversifyJS/issues/737 since first, theia uses v0.1.10 of reflect-metadata and a quick github search reveals that reflect-metadata is invoked 2-3x. 

So I think we can update reflect-metadata as suggested on the link given.

**Comment by marcdumais-work** [comment]
Hi @uniibu 

I'd like to try to reproduce your issue. I tried to build and run the `browser-app` from your extension's repository, but it worked without apparent issue. 

> theia uses v0.1.10 of reflect-metadata

I think theia itself uses `v0.1.12`. From theia's `yarn.lock`: 

```
reflect-metadata@^0.1.10:
  version "0.1.12"
  resolved "https://registry.yarnpkg.com/reflect-metadata/-/reflect-metadata-0.1.12.tgz#311bf0c6b63cd782f228a81abe146a2bfa9c56f2"
```

>  a quick github search reveals that reflect-metadata is invoked 2-3x.

From what I understand of the linked issue, it's ok for it to be invoked any number of times, as long as a single copy of the library ends-up being loaded in the F-E application.

**Comment by uniibu** [comment]
@marcdumais-work Thanks for testing it. I'd like to do more tests, pls keep this open. Cheers

**Comment by akosyakov** [comment]
@uniibu make sure that you don't have duplicate theia extension packages in your node_modules

If you use `next` everywhere, when to update remove all theia extensions from yarn.lock

**Comment by uniibu** [comment]
@akosyakov Thanks, I will do that. I probably was using an old lock file. 
@marcdumais-work Could you please try running the browser-app example with `search-in-workspace@next` extension. Let me know if it works. Thanks!

**Comment by marcdumais-work** [comment]
>  try running the browser-app example with search-in-workspace@next extension. Let me know if it works. 

I am now able to reproduce the issue!

Investigating for what the cause might be.

**Comment by marcdumais-work** [comment]
I notice that, with @theia/search-in-workspace added, yarn pulls 2 versions (many?) of the Theia packages:
- (expected): the latest `next`:  `0.4.0-next.316c760b`
- (un-expected): a `next` published ~1 week ago: `0.4.0-next.cea62337`

```
~/dev/theia-vue-extension$ yarn why @theia/process
yarn why v1.10.1
[1/4] Why do we have the module "@theia/process"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@theia/process@0.4.0-next.cea62337"
info Has been hoisted to "@theia/process"
info Reasons this module exists
   - "workspace-aggregator-8ef38480-5c1d-4f20-b45c-4706f4e25c3e" depends on it
   - Hoisted from "_project_#@theia#languages#@theia#process"
   - Hoisted from "_project_#browser-app#@theia#process"
   - Hoisted from "_project_#electron-app#@theia#process"
   - Hoisted from "_project_#browser-app#@theia#terminal#@theia#process"
info Disk size without dependencies: "396KB"
info Disk size with unique dependencies: "8.78MB"
info Disk size with transitive dependencies: "178.5MB"
info Number of shared dependencies: 165
=> Found "@theia/search-in-workspace#@theia/process@0.4.0-next.316c760b"
info Reasons this module exists
   - "_project_#browser-app#@theia#search-in-workspace" depends on it
   - Hoisted from "_project_#browser-app#@theia#search-in-workspace#@theia#editor#@theia#languages#@theia#process"
info Disk size without dependencies: "396KB"
info Disk size with unique dependencies: "8.78MB"
info Disk size with transitive dependencies: "178.5MB"
info Number of shared dependencies: 165
Done in 1.14s.
```

I tried to remove yarn.lock, clean the repo (`git clean -fdx`) and rebuilt. Afterward, only the expected `next` is pulled, and the application works again.

```
~/dev/theia-vue-extension$ yarn why @theia/process
yarn why v1.10.1
[1/4] Why do we have the module "@theia/process"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@theia/process@0.4.0-next.316c760b"
info Reasons this module exists
   - "_project_#browser-app" depends on it
   - Hoisted from "_project_#browser-app#@theia#process"
   - Hoisted from "_project_#electron-app#@theia#process"
   - Hoisted from "_project_#browser-app#@theia#search-in-workspace#@theia#process"
   - Hoisted from "_project_#browser-app#@theia#terminal#@theia#process"
   - Hoisted from "_project_#@devpodio#theia-vue-extension#@theia#languages#@theia#process"
info Disk size without dependencies: "396KB"
info Disk size with unique dependencies: "8.8MB"
info Disk size with transitive dependencies: "178.57MB"
info Number of shared dependencies: 134
Done in 2.41s.
```

@uniibu Try this and if it works for you, you can simply commit the updated `yarn.lock`

**Comment by uniibu** [comment]
@marcdumais-work Great! thanks! This probably solved the current issue, however, for regular users like for example, a user is v0.3.16 and Theia updated to v0.3.17, would this problem occur and have users delete their yarn.lock during updates? Or does it occur only because of how npm resolves the `next` tag?

**Comment by marcdumais-work** [comment]
@uniibu I am not sure what was the root cause in this precise case, but I think that usually `yarn.lock` will be able to update itself without having to be deleted like this. You might have encountered a corner-case, here, I hope.

**Comment by uniibu** [comment]
Closing. Deleting the yarn.lock and reinstalling then rebuilding solved this issue
