### ISSUE TITLE
Ability to specify path to Clangd in preferences

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#3517]
I know it's possible to add clangd to PATH before launching Theia but I find it clunky. I don't want it on my PATH all the time as I have multiple. Also, it would make it easier to support having per workspace path to Clangd. Imagine projects shipping their own proper version of clangd along with the compiler (clang) to build the project and setting these paths in the project's workspace.

**Comment by simark** [comment]
PR #2970 will define a way to pass parameters from the frontend to the backend when starting a language server.  The plan is to use that (once it is merged) to optionally pass a clang path and some command-line arguments.

**Comment by simark** [comment]
@marechal-p, would you like to pick this one up?

**Comment by vince-fugnitto** [comment]
fixed thanks to #3877
