### ISSUE TITLE
Alt+o shortcut (Toggle header/source) is not good on macOS

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#3519]
On many keyboard layouts on macOS, Option key (alt) combine with other keys are for printing special characters. For example, on my Canadian French, Alt+o yield ø (Empty Set). I propose instead that for macOS this keyboard shortcut could be Option+Command+O. This would depend on #3518

**Comment by simark** [comment]
@marechal-p, can we assign this to you?

**Comment by marechal-p** [comment]
https://github.com/theia-ide/theia/pull/3565
