### ISSUE TITLE
Align empty outline styles with other views

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3520]
In the problems view it has different color and aligned to the left.
<img width="775" alt="screen shot 2018-11-16 at 08 53 00" src="https://user-images.githubusercontent.com/3082655/48605462-25d99380-e97d-11e8-8340-c830edf82988.png">
<img width="401" alt="screen shot 2018-11-16 at 08 53 02" src="https://user-images.githubusercontent.com/3082655/48605468-28d48400-e97d-11e8-92a7-824522e7e5b7.png">

**Comment by vince-fugnitto** [comment]
sorry about that @akosyakov, at the time I thought it looked better but I'll align
