### ISSUE TITLE
hosted plugin leaking json rpc proxy factories

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3523]
<img width="1524" alt="screen shot 2018-11-16 at 12 18 51" src="https://user-images.githubusercontent.com/3082655/48618504-e0778f00-e999-11e8-99a0-07c9b04ec53a.png">

To reproduce:
- start Theia with several pages
- close all pages
- take the memory snapshot of the backend
- look for `JsonRpcProxyFactory` which is retained by the hosted plugin process even though clients are gone

**Comment by vitaliy-guliy** [comment]
@akosyakov  It looks we don't have the leakage anymore.Having spent some time on debugging and profiling the backend, I haven't found it.
Let you see at following snapshots.
The first one I got before opening browser tabs, second displays state with 4 tabs and the last one I take after closing the browser.

![snapshot 1](https://user-images.githubusercontent.com/1655894/54539259-7b12c980-499e-11e9-985d-3c3b58f38e95.png)

![snapshot 2](https://user-images.githubusercontent.com/1655894/54539278-8239d780-499e-11e9-8b05-915db3a29acf.png)

![snapshot 3](https://user-images.githubusercontent.com/1655894/54539294-87972200-499e-11e9-9276-95293c6c0f69.png)

**Comment by akosyakov** [comment]
sounds good, thanks for checking!

probably resolved by https://github.com/theia-ide/theia/pull/4521, since a hosted plugin process should be garbage collected now when a connection is closed
