### ISSUE TITLE
How do we change look and feel of Default theia editor 

### ISSUE THREAD

**Issue by deepakagra** [theia-ide/theia#3537]
I understand that we can build any added functionality using Extensions. But, how do I change look & feel of default implementation ? Like change default black color; or remove some Menu Items or change default editor to support Graphics ( current editor only support text )  ? Do I have to go and change inside theia core ? Or there are any configuration files ?

If I modify theia core files; then how do I upgrade my codebase as theia keeps upgrading ! That will result in conflicts.

**Comment by kittaakos** [comment]
There are different ways to customize Theia.

> change default black color

You can change it in the application's `package.json` by adding the [`defaultTheme`](
https://github.com/theia-ide/theia/pull/2442#issue-204080457) entry. Or you can change the default application name; minor branding related things are already supported.

Default application preferences can be defined and shared via the [`setting.json `](https://github.com/theia-ide/theia/blob/master/packages/preferences/README.md) preferences file.

> or remove some Menu Items or change default editor to support Graphic

Such a customization requires a new extension. You have to redefine the default Theia behavior by implementing custom logic in TypeScript. For example, you can subclass the default `EditorWidget` class or you can redefine an existing keybinding in an overridden method. Then you can use dependency injection ([InversifyJS](https://github.com/inversify/InversifyJS)) to rebind the default behavior.

> Do I have to go and change inside theia core

No. We might need to adjust `@theia/core` APIs, but ideally, an extension developer can modify menus, change the default editor behaviors, add new UI and backend features without core modifications.

**Comment by sr229** [comment]
I think this merits a closure since this is already a answered question.
