### ISSUE TITLE
[plug-in] Implement 'configurationDefault' contribution point

### ISSUE THREAD

**Issue by akurinnoy** [theia-ide/theia#3540]
[contributes.configurationDefaults](https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults)

Configuration example:
```
"contributes": {
    "configurationDefaults": {
        "[markdown]": {
            "editor.wordWrap": "on",
            "editor.quickSuggestions": false
        }
    }
}
```

**Comment by akosyakov** [comment]
@akurinnoy Are you working on it?

**Comment by akurinnoy** [comment]
@akosyakov unfortunately, we cannot take it in following sprint, but, we could do it in next sprint in 3 weeks, I think

**Comment by akosyakov** [comment]
@akurinnoy Would it be alright if i look at it now?

**Comment by akurinnoy** [comment]
@akosyakov Sure! Should I re-assign the issue?
