### ISSUE TITLE
improve navigation in the debug console

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3546]
The debug console should auto-scroll if it is located at the bottom. 

It is worth to test with `Launch Backend` configuration and log level debug. This configuration produces a lot of output and makes navigation and performance issues apparent.

**Comment by shenxs** [comment]
Hi ，I just wandering how is that going or how could I implement it ,if I want that feature

**Comment by akosyakov** [comment]
@shenxs feel free to grab it

**Comment by akosyakov** [comment]
It also jumps up on new output, super annoying :( Something like that happens with the scroll in navigator sometimes... could be the general issue with the tree model.

**Comment by a1994846931931** [comment]
I am working on this issue. Here is a short demo, and I'll make a PR if it looks fine to you:

![debug-console](https://user-images.githubusercontent.com/17487291/57440821-496dfe80-727b-11e9-8281-7536c64b2281.gif)
