### ISSUE TITLE
deploying plugins

### ISSUE THREAD

**Issue by Mosho1** [theia-ide/theia#3549]
The plugin docs don't explain how to deploy plugins, and I see that the build outputs a `.theia` file. How do I use it/deploy the plugin?

**Comment by micellius** [comment]
You can use `THEIA_PLUGINS` environment variable to point to directories containing plugins (comma-separated list). For example, you can start Theia with: 
```bash
export THEIA_PLUGINS=local-dir:/path/to/plugin1,local-dir:/path/to/plugin2 && yarn start
```

**Comment by Mosho1** [comment]
Thanks, that works!
