### ISSUE TITLE
Add preview mode for editor

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#3550]
Add an ability to open editor in preview mode. In this mode the editor will be replaced by opening another editor. Single mouse click on file in the navigator should open editor in preview mode, double click should open editor with disabled preview mode. Editor's tab should have an action that disables preview mode.
Vscode example:
![ezgif-1-c4c8a46fac26](https://user-images.githubusercontent.com/7668752/48773347-cdcdc480-eccf-11e8-8c3e-e063615c65e6.gif)
Is needed for https://github.com/theia-ide/theia/issues/2801

**Comment by vince-fugnitto** [comment]
@vinokurig I believe this will be achieved by #3373

**Comment by vinokurig** [comment]
@vince-fugnitto Thank you, closing it as a duplicate.
