### ISSUE TITLE
Add an ability to open editor in the specified column

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#3553]
Add an enum `[Active, One, two, Three]` to `EditorOpenerOptions` parameters and open the editor in the specified column when `EditorManager.openEditor(params: EditorOpenerOptions)` is called:
![screenshot-localhost-3000-2018 11 21-10-32-38](https://user-images.githubusercontent.com/7668752/48832772-9e2bc480-ed82-11e8-9bea-fbd70b6af82e.png)

is needed for #2801

**Comment by akosyakov** [comment]
What do you mean by a separate area?

**Comment by vinokurig** [comment]
If you click on file in the navigator, it will be opened in a new tab:
![screenshot-localhost-3000-2018 11 20-17-05-49](https://user-images.githubusercontent.com/7668752/48782408-ce258a00-ece6-11e8-9eb4-ecfef6545f22.png)
But I would like to have an ability to open the next editor in a separate tab:
![screenshot-localhost-3000-2018 11 20-17-07-02](https://user-images.githubusercontent.com/7668752/48782457-e85f6800-ece6-11e8-80b1-20b024e8ac09.png)

**Comment by akosyakov** [comment]
Try `widgetOptions: { mode: 'split-right' }` or `widgetOptions: { mode: 'split-bottom' }` to open a new tab bar area to right or to bottom relative to last focused widget.

**Comment by vinokurig** [comment]
Ok, thanks

**Comment by svenefftinge** [comment]
can we close this?

**Comment by vinokurig** [comment]
Let me try the proposed solution. I'll close it if it would work for me.

**Comment by vinokurig** [comment]
@akosyakov Thank you for your advice but it didn't solves my issue. I've studied the vscode plugin system and found that current solution doesn't fit it. This can only open the editor in a new column, but I need to open the editor in the specified column as well.
P.S. Rephrased the issue

**Comment by akosyakov** [comment]
Our areas don't have the notion of columns. I think first you will need to simulate it is somehow on the top of existing APIs in the plugin extension. Later if it is turned out to be useful for extension developers we can introduce such modes in the core.

**Comment by vinokurig** [comment]
> Our areas don't have the notion of columns

`Column` may be a wrong word but, anyway it is possible to open several editors in the same area (see the screen-shot in the description), so this issue is actual.

**Comment by svenefftinge** [comment]
You can align the terminology with the one from the vs code API.

**Comment by svenefftinge** [comment]
Yan you link to the respective part in vscode.d.ts?

**Comment by svenefftinge** [comment]
Found it 'ViewColumn'. I think that can be modelled within the plug-in extensions without modfiying the application shell too much.

**Comment by vinokurig** [comment]
This is already implemented by `widgetOptions: { ref: widget }` in `OpenerOptions`. I'll open a PR for plugin side.
