### ISSUE TITLE
Open one new browser application from theia application

### ISSUE THREAD

**Issue by RimShao** [theia-ide/theia#3554]
Hi JanKoehnlein/Sven,

We have one json-editor application server running. which can be accessed http://localhost:5000 via browser.

One Use case we have is to edit json-schema data in theia-ide window, Click one designed menu/button, using json-schema as input and open new json-editor application window. 

Now question is how to implement openning browser application (localhost:5000) from current theia-ide browser ?

One small example will be very helpful.

Please let me know if more explanation needed.

**Comment by svenefftinge** [comment]
I have two answers to your question:

1) Theia directly supports editing JSON files associated with JSON schema. You can reference the schema directly in the editor, like in the following [example](https://gitpod.io#snapshot/b32a4f52-381f-4590-92e7-5551678816b2) or add it the preferences.

2) If you still want to open a preview, you can open mini-browser with the given URL. For that you should use the `OpenHandler` and pass the http URL.

**Comment by RimShao** [comment]
Hi Sven,

Thanks a lot for the information.

1. I have a glance with your recommended JSON schema editor, basically what we want is this demo: https://json-editor.github.io/json-editor/.

2. Mini-browser is useful to us. I will try to coding further more with this approach.

**Comment by RimShao** [comment]
Thanks Sven, Now I figure out how Json-editor opened in mini-browser.

The question can be closed now.
