### ISSUE TITLE
[quality] consider adding more rules to dev.tslint.json

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#356]
In PR https://github.com/theia-ide/theia/pull/353, we introduced a second tslint config file, that extends the one we use for compilation. The new config is used by vscode to highlight broken rules in the editor, encouraging contributors to respect the contained rules, going forward.

Now might be a good opportunity to go crazy and try all the dev rules we think are, on balance, more useful than they are annoying :) 

I'll submit a PR with additional rules for dev-tslint.json. I think a good way to go forward is, for as many Theia developers as possible, to temporarily adopt those rules in they daily work, and provide feedback on which rules they dislike, are buggy or are more annoying than useful.

**Comment by marcdumais-work** [comment]
After discussions in the PR #356, there are valid concerns that we are introducing too many rules, generating too many linter warnings, that would distract from feature development. 

An alternate approach is to introduce a third tslint config file that contains all potentially useful rules. That new config file would not be used by vscode by default, but could be for users who want-to. This way it gives the opportunity for contributors to try a wider array of rules and eventually promote the most useful ones to "dev.tslint.json".

**Comment by marcdumais-work** [comment]
Here's a short list of TSLint rules that I propse we add to dev.tslint.json. 
 
**The following rules enforce items defined in Theia's [coding guidelines](https://github.com/theia-ide/theia/wiki/Coding-Guidelines) :**

enforce having parenthesis around arguments of arrow functions, except if we have a single argument 
https://palantir.github.io/tslint/rules/arrow-parens/
"arrow-parens": [
      true,
      "ban-single-arg-parens"
    ]

ban use of null keyword literal
https://palantir.github.io/tslint/rules/no-null-keyword/
"no-null-keyword": true

enforce that indentation is exactly 4 spaces
https://palantir.github.io/tslint/rules/indent/
"indent": [true, "spaces", 4]

enforce the proper formatting of JSDoc comments
https://palantir.github.io/tslint/rules/jsdoc-format/
"jsdoc-format": true

enforce using braces for if/for/do/while statements, except for one-liners
https://palantir.github.io/tslint/rules/curly/
"curly": [true, "ignore-same-line"]

only permit declaring a single variable per declaration
https://palantir.github.io/tslint/rules/one-variable-per-declaration/
"one-variable-per-declaration": true

**Misc rules:**

enforce POSIX standard of ending file with newline char
https://palantir.github.io/tslint/rules/eofline/
"eofline": true

make sure we do not use magic numbers
https://palantir.github.io/tslint/rules/no-magic-numbers/
"no-magic-numbers": true

Since we have a logger, we should probably discourage use of console.log() ,etc...
https://palantir.github.io/tslint/rules/no-console/
"no-console": true

**Comment by akosyakov** [comment]
Sounds good, let's give it a try.

**Comment by marcdumais-work** [comment]
https://github.com/theia-ide/theia/pull/366

**Comment by akosyakov** [comment]
It would be interesting to play with https://palantir.github.io/tslint/rules/no-inferrable-types/ and https://palantir.github.io/tslint/rules/typedef/. In such way that inferred types are recommended for variables inside method bodies, explicit types are advised for method signatures and for properties anything can be used.

**Comment by marcdumais-work** [comment]
The following rules we added at the suggesstion of @akosyakov : 
Prefer an interface declaration over a type literal (type T = { ... })
https://palantir.github.io/tslint/rules/interface-over-type-literal/
"interface-over-type-literal": true

Suggests to convert () => { return x; } to () => x.
https://palantir.github.io/tslint/rules/arrow-return-shorthand/
"arrow-return-shorthand": [true, "multiline"]

Disallows shadowing variable declarations.
https://palantir.github.io/tslint/rules/no-shadowed-variable/
"no-shadowed-variable": true

Disallows access to the constructors of String, Number, and Boolean.
https://palantir.github.io/tslint/rules/no-construct/
"no-construct": true

Disallows usages of any as a type declaration.
https://palantir.github.io/tslint/rules/no-any/
"no-any": true

**Comment by marcdumais-work** [comment]
See below for an interesting discussion about the use of  "typedef" and "no-inferrable-types" rules together. It seems that no conclusion has been reached yet. One suggestion that looks promising is to deprecate "no-inferrable-types" and add the equivalent as an option of "typedef". 

https://github.com/palantir/tslint/issues/711

**Comment by marcdumais-work** [comment]
Seems like GH doesn't understand the "partially fixes" keyword :)  Re-opening this issue so that we can continue discussing about rules we want to add/tweak.

**Comment by akosyakov** [comment]
@marcdumais-work https://help.github.com/articles/closing-issues-using-keywords/

**Comment by marcdumais-work** [comment]
@akosyakov thanks. What if I want to reference an issue but not close it upon merging the PR? Would a reference without one of the "closing" keyword work. i.e. "see #356" in the commit message?

**Comment by akosyakov** [comment]
yes, should work

**Comment by akosyakov** [comment]
`https://palantir.github.io/tslint/rules/no-magic-numbers/` is annoying for testing and well known http codes

**Comment by marcdumais-work** [comment]
@akosyakov We could remote that rule. There is also a possible compromise, for rules that are generally good but that we want to have the liberty to break in some specific cases, we have the option disabling that rule selectively, using comments in the code. It's very easy to do so in vscode, using a "fixit".  

e.g. in this case add something like "// tslint:disable-xext-line:no-magic-numbers" on the previous line. I think we can also disable for a whole file.

Do you think disabling the rule selectively makes sense, in this case?

**Comment by akosyakov** [comment]
whenever you compare with a number in tests you will need to add this line

**Comment by akosyakov** [comment]
well there is a way to disable some rules for the whole file: https://palantir.github.io/tslint/usage/rule-flags/

**Comment by kittaakos** [comment]
Can someone please explain to me why I have tons of warnings in the `node-filesystem.spec.ts`? For instance: ```[tslint] unused expression, expected an assignment or function call (no-unused-expression)```. Cheers!

**Comment by marcdumais-work** [comment]
Looks like this case: https://github.com/palantir/tslint/issues/2614

**Comment by kittaakos** [comment]
> Looks like this case: palantir/tslint#2614

I can add the [`tslint-no-unused-expression-chai`](https://www.npmjs.com/package/tslint-no-unused-expression-chai) rule. Objections?

**Comment by kittaakos** [comment]
I will add the rule as mentioned above. Is there anything that should be done within this task?

**Comment by marcdumais-work** [comment]
It seems that we have converged to an acceptable tslint configuration. Closing this issue.
