### ISSUE TITLE
[TS] TS LS does not start after installing `typescript` into the workspace's `node_modules` folder

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3568]
Preconditions:
 - I do not have `typescript` installed globally.

Steps to reproduce:
 - Open a JS/TS project as a workspace in Theia.
 - Open a TS/JS file. You get an error `tsserver` was not found. This is correct. 👍 
 - Run `yarn` in your workspace so that `tsserver` will be under `$WS_ROOT/node_modules/.bin/tsserver`.
 - Since the LS did not start, I do not have the `TypeScript: Restart Language Server`.

Workaround:
 -  Reload the (electron) application.

**Comment by akosyakov** [comment]
please check, there should be `TypeScript: Start Language Server` command

**Comment by kittaakos** [comment]
👍 Awesome.
