### ISSUE TITLE
[git][electron] Cannot push to a public repository from the bundled electron application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3571]
I go the following error when I tried to push from the UI.
```
Request push failed with message: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured
```

I can push from the terminal. Also, the `credential.helper` looks good:
```
$ git config --global credential.helper
osxkeychain
```

**Comment by svenefftinge** [comment]
This error means that the executable could not be found. maybe it should be an absolute path?

**Comment by kittaakos** [comment]
> This error means that the executable could not be found

I have to disagree. Although I did not check it thoroughly, it seems the git path was OK, but the command was `credential-osxkeychain`.

> maybe it should be an absolute path?

Absolute path of what?

**Comment by svenefftinge** [comment]
I suggested that because I had the same error message with just another executable a couple of days ago. But I see now that in this context the problem seems to be the embedded git.
I never really understood why that is used when there is a git on the system. Shouldn't we change dugite so that if there is a git on the PATH it uses it?

**Comment by kittaakos** [comment]
> Shouldn't we change dugite so that if there is a git on the PATH it uses it?

Yes. I wanted to suggest the same. And if there is no git on the PATH, we can start Theia with an info message (once) and use the embedded Git.

If we could use the system Git, we could also avoid future confusion in the terminal.
