### ISSUE TITLE
[debug] New thread detection removes stopped state

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#3601]
If a [new thread is detected](https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-session.tsx#L100), the [known threads are updated](https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-session.tsx#L364).

As this new thread information no longer contains any `stoppedDetails`, if the debug is in a stopped state, this state is no longer reflected in the UI and instead looks like it is running.

This is because the `stopped` state is entirely dependent on the existence of `stoppedDetails` being added by the last thread update.

This issue is especially apparent during the startup stages in a slow debug adapter which has a breakpoint at it's point of entry. This is primarily due to the delay introduced by [debouncing](https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-session.tsx#L359) the thread calls.

Removing the debouncing fixes this issue in the case of the `debug-cortex` plugin, but this wouldn't fix a scenario when a new thread is started during debug.

I'm happy to open a PR to remove the `debouncing`, but would like opinions or other suggestions.

Thoughts @akosyakov @simark @marcdumais-work ?

**Comment by akosyakov** [comment]
`stoppedDetails` should be updated only by `stop` event, never by other clients
