### ISSUE TITLE
Build not working with win32 or win64 platform (Git Bash)

### ISSUE THREAD

**Issue by ainslec** [theia-ide/theia#363]
Following instructions from the README.md:

![h5](https://user-images.githubusercontent.com/201870/28778898-2805b006-75f9-11e7-8918-21524ec6bcda.png)

The following occurs:

![h6](https://user-images.githubusercontent.com/201870/28778905-2e558b16-75f9-11e7-864e-05cccf8f5342.png)

This remains separate to yarn hanging via the "yarn" command in the same folder in issue #328 which remains unresolved.

Can anyone confirm if they have a build working on the Windows platform?

**Comment by MarkZ3** [comment]
I only see warnings, no errors? Or I am reading this wrong?

**Comment by kittaakos** [comment]
These are just warnings. `fsevents` is an optional native module only for OS X. Closing issue.

> Can anyone confirm if they have a build working on the Windows platform?

I can. Please see: https://github.com/theia-ide/theia/issues/316#issuecomment-319384017.
