### ISSUE TITLE
Show the progress for Git clone operation

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#3631]
When user is cloning a Git repo with the `Git: Clone...` command he/she may expect some notification should report the progress of cloning a repo. But nothing happens from the user's perspective. One need to check the Navigator tree to ensure that repo has been already clonned.

So, it'd be useful to have some notification reporting the progress of cloning a Git repo when it's invoked with the `Git: Clone...` command.

**Comment by AlexTugarev** [comment]
I'd ❤️ to see https://github.com/theia-ide/theia/pull/2461 in action for this!

**Comment by benoitf** [comment]
it requires https://github.com/theia-ide/theia/pull/2979

**Comment by kittaakos** [comment]
> it'd be useful to have some notification reporting the progress of cloning a Git repo when it's invoked with the `Git: Clone...`

Why just the clone command and not [all the Git operations](https://github.com/theia-ide/theia/issues/759)?

**Comment by azatsarynnyy** [comment]
Thank you @kittaakos for pointing this out!
Closed as a duplicate of https://github.com/theia-ide/theia/issues/759
