### ISSUE TITLE
[debug] managing configurations relies on @theia/json

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#3657]
As part of #3384 the debug configuration management (e.g. `add configuration`) has been moved to an inline suggestion in the editor rather than a dropdown:

![screen shot 2018-11-28 at 13 06 09](https://user-images.githubusercontent.com/61341/49154524-7901fd80-f310-11e8-902a-b242a5187936.png)

This has introduced an implicit dependency on `@theia/json` to be included in end applications, otherwise the `add configuration` functionality fails to work:

![screen shot 2018-11-28 at 13 00 28](https://user-images.githubusercontent.com/61341/49154576-a2228e00-f310-11e8-8e7e-d581a9c67009.png)

Should this be added to the debug dependency list even though it's not required to compile or be documented somewhere?

CC: @akosyakov @tolusha @simark @marechal-p

**Comment by marechal-p** [comment]
+1

**Comment by simark** [comment]
With Debian packages, on top of the concept of "Dependency" package, there is the concept of "Recommended" and "Suggested" packages for a given package.  If we had the same concepts, I think it would fall in one of those categories, where it's not strictly needed, but it adds extra functionality or improves the user experience.

**Comment by akosyakov** [comment]
Sounds good
