### ISSUE TITLE
hosted mode missing after building theia

### ISSUE THREAD

**Issue by TheZoker** [theia-ide/theia#3659]
Hi guys,

I followed the instructions to build theia:
https://www.theia-ide.org/doc/Composing_Applications.html

Worked well and I can access the theia editor via http://localhost:3000

Now I tried to create a plugin with this article:
https://www.theia-ide.org/doc/Authoring_Plugins.html

But when I press F1, there is no `hosted mode`. It's just completely missing:
![screenshot_2018 11 28_15h34m09s_001_](https://user-images.githubusercontent.com/1368405/49158726-1f56fe80-f323-11e8-9fba-b0b4f0f9f6ff.png)

But according to the docs, it should be there:
https://www.theia-ide.org/doc/Authoring_Plugins.html#executing-the-plug-in

Why is it missing? Do I need to do something else? 
I did not do anything else or changed any configuration...

I also tried it on a different machine, but still the same issue

**Comment by benoitf** [comment]
@TheZoker might be related to https://github.com/theia-ide/theia/issues/2896#issuecomment-427278248

**Comment by akosyakov** [comment]
@TheZoker You should add `@theia/plugin-ext` to your app package.json.

**Comment by TheZoker** [comment]
Yes that was the issue, the doc has to be updated here. Thank you!

Since this is a duplicate anyway, I'll close it

**Comment by yiliang114** [comment]
In the fact, you should not directily use the brower-app generated by generator-theia-extension,  add @theia/plugin-ext to devDependencies and restart

**Comment by yiliang114** [comment]
actually, you should also install `@theia/plugin-dev` to dependencies too
