### ISSUE TITLE
[preferences] Theia creates an empty `settings.json` file in my workspace when I change the user preferences

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3673]
- Open a workspace. Neither the `${WS_ROOT}/.theia` nor the `${WS_ROOT}/.theia/settings.json`  existed in my case..
 - `File` > `Settings` > `Open Preferenecs` > `Editor` > `enablePreview` > `false`.
 - I have an empty `settings.json` file as an outgoing change in Git.

**Comment by vince-fugnitto** [comment]
Our current implementation is a bit odd as in we create the `setting.json` under the `${WS_ROOT}/.theia/settings.json` once we open the **Preferences Widget**. 

We should instead open the **Preferences Widget** without creating the `${WS_ROOT}/.theia/settings.json` and only if the 'Workspace Settings' tab is selected in the widget by end-users do we trigger the creation of the file.

**Comment by elaihau** [comment]
atm one editor is associated with one file when opened. maybe what we could do is associating a temporary file from the `/tmp` folder with the "workspace pref" editor, and move that temporary file to `${WS_ROOT}/.theia` once the user activates the "workspace pref" editor or starts editing. 

what do you think @kittaakos  ?

**Comment by kittaakos** [comment]
That can work. Or delete the file if it was missing before opening the preferences editor and it is empty when closing the editor. Or wait until we have the in-memory model support. I do not know whether we're planning to implement it or have it already.

**Comment by vince-fugnitto** [comment]
@kittaakos has the problem been fixed? I don't see the `settings.json` being created anymore, that's the reason I proposed the idea of #5477

**Comment by kittaakos** [comment]
> has the problem been fixed

I do not know, but it is not an issue anymore. I cannot see the `Workspace` tab if open an empty workspace and select `File` > `Settings` > `Open Preferences`.

![Screen Shot 2019-06-14 at 16 02 40](https://user-images.githubusercontent.com/1405703/59514768-d9781700-8ebd-11e9-9787-6b0a717afc8e.jpg)
