### ISSUE TITLE
[electron] Missing content in debug view 

### ISSUE THREAD

**Issue by mark-edgeworth** [theia-ide/theia#3679]
When I run the UI in electron and attempt to debug some JS the Variables and Breakpoints sections of the debug pane are empty. 

However, when I run the backend (using Launch Backend) and connect using a browser the variables and breakpoints sections of the debug view are filled-in correctly.

Run with master as of this morning.

**Comment by mark-edgeworth** [comment]
To be clear, I did add a single breakpoint and theia was correctly stopped at it.

**Comment by akosyakov** [comment]
@mark-edgeworth Hi :wave: 

Can you check please your backend logs? Do you see something like here: https://github.com/theia-ide/theia/issues/3408#issuecomment-443146496

**Comment by akosyakov** [comment]
I was able to reproduce it, it does not seem to be related to https://github.com/theia-ide/theia/issues/3408

**Comment by akosyakov** [comment]
The fundamental issue that we use runtime features from es5 which are not supported in Node.js version bundled with Electron 1.8.2. I would prefer that we move to the latest stable Electron.

@mark-edgeworth Could someone from ARM to have a look at https://github.com/theia-ide/theia/issues/3693?

**Comment by thegecko** [comment]
@akosyakov We are keen to "bum" up the electron version. Let me investigate the work needed.

**Comment by akosyakov** [comment]
@thegecko there can be a bit more work, in addition, to bumping up the electron version :) related to nsfw package @kittaakos should know better

**Comment by thegecko** [comment]
This should be fixed when the `Array.values()` usages are removed as part of #3730 .
