### ISSUE TITLE
[security] event-stream dependency issue risk

### ISSUE THREAD

**Issue by legenddcr** [theia-ide/theia#3683]
According to a security issue reported by NPM security team:

https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

A malicious issue is found in flatmap-stream package and event-stream 3.3.6. NPM team has removed event-stream 3.3.6 and holding flatmap-stream (https://www.npmjs.com/package/flatmap-stream) now.

In Theia IDE, `@theia/plugin-ext` package depends on ps-tree 1.1.0, while ps-tree 1.1.0 depends on event-stream: `"event-stream": "~3.3.0"`. However, it might lead `theia-full` docker image or other custom builds depend on `@theia/plugin-ext` pulling `event-stream@3.3.6` in the past. Its likely that older builds of theia has pulled 3.3.6 version of event-stream, around nov 24-26 builds. 

Open this issue to track this security risk.

**Comment by marcdumais-work** [comment]
It think this doesn't affect Theia (latest, next) currently. But we should check in our images published on Dockerhub if some of them, within the given date range, might be affected.

**Comment by marcdumais-work** [comment]
I have confirmed that only `theiaide/theia-full` contains `@theia/plugin-ext` and so is potentially subject to the vulnerability. We had no published `theia-full` images for the critical dates above (CI was not passing, so the nightly builds were not published. As a sanity check, I had a look at images we have published the closest to these dates, and found a range that have `"event-stream": "~3.3.6"`:

I found 13 `theia-full` images that were affected, published on dockerhub between mid-October to mid-November
most recent: `theiaide/theia-full:0.4.0-next.7f311500`
oldest: `theiaide/theia-full:0.4.0-next.19d2d6c5`

e.g.:

```
marc@gimli:~$ docker run -it --entrypoint /bin/bash -p 3003:3000 -v "$(pwd):/home/project:cached" theiaide/theia-full:0.4.0-next.a129cafe
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

theia@dd601cd818f5:~$ yarn list | grep event-stream
├─ event-stream@3.3.6
```

**Comment by marcdumais-work** [comment]
I have purged the affected `theiaide/theia-full` images from our dockerhub account. 

As well as this one I had missed above: `theiaide/theia-full:next`, for a total of 14.
