### ISSUE TITLE
Delays on first access from the browser

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#3694]
We are using Theia 0.3.16.  We are seeing delays of 10 to 15 second or more when accessing web based Theia (in a docker container) for the first time from the browser, or when we refresh the page.

It seems to be based on the size of the workspace, bigger workspaces are worse.  A smaller workspace of 200MB takes a few seconds, a 700MB one takes about 15 seconds, bigger ones take longer. 

The logs show the delay is here:
```
2018-11-30T14:06:26.286707400Z root INFO [nsfw-watcher: 218] Started watching: /root/.theia
2018-11-30T14:06:40.372102400Z root INFO [nsfw-watcher: 218] Started watching: /workspace
```
Is there a way to turn on additional logging/tracing to see what's happening in greater detail?

**Comment by akosyakov** [comment]
Do you use `--no-cluster` mode?

**Comment by jopit** [comment]
No, we don't use `--no-cluster`.

**Comment by jopit** [comment]
I tried setting `--log-level=trace`, but nothing is output during the delay (there is output afterward).

**Comment by akosyakov** [comment]
@jopit try `--inspect=9228`, after that open the chrome dev tools, there should be a button to connect to a running Node.js process (server worker process). When you connect, please measure what is happening during opening the page. You can analyze the snapshot yourself or attach here that we can have a look as well.

**Comment by jopit** [comment]
I tried using 0.3.17 instead of 0.3.16 and I get an extra message in the logs
```
2018-12-03T20:54:23.452480600Z root INFO [nsfw-watcher: 95] Started watching: /root/.theia
2018-12-03T20:54:35.540770100Z root INFO [nsfw-watcher: 95] Started watching: /microclimate-workspace
2018-12-03T20:54:35.557667600Z root WARN e.onStart is slow, took: 12800.000000046566 ms
```
Does that mean anything useful?

**Comment by akosyakov** [comment]
probably, will be addressed by https://github.com/theia-ide/theia/pull/3699

**Comment by akosyakov** [comment]
> Using --inspect is going to attach to the main process right? If the server worker process is a separate process, how do I attach to it instead?

with `--inspect=9228` the server worker process will be run on 9229, the default port which is used by the chorme dev tools to attach

**Comment by jopit** [comment]
@akosyakov I started the profiler and reloaded the page.  There was a 10 second delay:
```
2018-12-04T18:40:22.096261900Z root INFO [nsfw-watcher: 442] Started watching: /root/.theia
2018-12-04T18:40:31.535387600Z root INFO [nsfw-watcher: 442] Started watching: /microclimate-workspace
2018-12-04T18:40:31.555616500Z root WARN e.onStart is slow, took: 10194.399999978486 ms
```
Looking at the captured data, nothing really jumps out at me, but then I don't really know what I'm looking for.

[profile.zip](https://github.com/theia-ide/theia/files/2645649/profile.zip)

**Comment by jopit** [comment]
@akosyakov I patched the version of Theia we are using with the changes for #3699 and the startup time in our scenario dropped from 10+ seconds to under a second, so it looks to be the same problem.

**Comment by akosyakov** [comment]
@jopit #3699 was merged, can we close this issue?

**Comment by jopit** [comment]
Closing.
