### ISSUE TITLE
[editor-preview] propose changing the 'list' category preference 

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3702]
the new `editor-preview` widget contributes a new preference under `list` which does not make sense to end-users and makes the preference hard to find. I propose we instead find a more meaningful name as a category. Perhaps the same can be true about the `description`.

<img width="798" alt="screen shot 2018-12-02 at 6 54 44 pm" src="https://user-images.githubusercontent.com/40359487/49346669-c3aead00-f663-11e8-92e8-67c65ab8414f.png">

**Comment by akosyakov** [comment]
It is not about editor preview, but to control when any widget which has a list (not only navigator) should open something. We are going to support it for the git, history and so on. The name is aligned with VS Code preference on the purpose.

If you want to disable editor preview, you should look for `editor.enablePreview` preference.

**Comment by vince-fugnitto** [comment]
thanks for clarifying @akosyakov !
