### ISSUE TITLE
[keybinding] Broken keybinding: `Toggle Bottom Panel`

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3703]
OS X, electron example. <kbd>Cmd</kbd>+<kbd>J</kbd> should toggle the bottom panel. It deletes the current line from the editor instead.

<img width="256" alt="screen shot 2018-12-03 at 08 35 45" src="https://user-images.githubusercontent.com/1405703/49359489-b252b880-f6d6-11e8-9668-a9033309b315.png">

![screencast 2018-12-03 08-34-30](https://user-images.githubusercontent.com/1405703/49359497-b5e63f80-f6d6-11e8-969c-5f93b3ba799e.gif)

**Comment by vince-fugnitto** [comment]
@kittaakos I've tested on my end for both the browser and electron version on OSX and it seems to currently work, can you confirm?

**Comment by kittaakos** [comment]
> can you confirm?

It works.
