### ISSUE TITLE
Open in Terminal

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#3710]
It would be great to have `Open in Terminal` command which opens a terminal and switches to the selected folder.

The command should be in context menu when right click at the folder in the navigator and will look like below.

![open in terminal](https://user-images.githubusercontent.com/1655894/49369476-28b4e200-f6fa-11e8-9969-7e187f736f0b.png)

**Comment by vince-fugnitto** [comment]
@vitaliy-guliy I believe the command already exists in master, see below:

![terminal](https://user-images.githubusercontent.com/40359487/49372524-f3dc6700-f6c8-11e8-9a9c-2d28dd4b7b8d.png)

Maybe the only thing to change would be its location :)

**Comment by vitaliy-guliy** [comment]
@vince-fugnitto Really? It seems we use old version of Theia in our Eclipse CHE. And we are missing this feature. Thanks.
