### ISSUE TITLE
editor preview should not be opened on single click if modifier keys are pressed

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3712]

**Comment by AlexTugarev** [comment]
Just verified, this is still the case.

**Comment by yeweiasia** [comment]
@AlexTugarev https://github.com/theia-ide/theia/pull/4806 Can this PR solve you problem?

**Comment by akosyakov** [comment]
@AlexTugarev could you remind me what was the issue? I've filed it but cannot recall now. I guess it is indeed the same as https://github.com/theia-ide/theia/issues/4807.

**Comment by AlexTugarev** [comment]
Try to select multiple file in the explorer holding `command` key down. Currently it will preview-open those file, which is not the expected behavior.

**Comment by yeweiasia** [comment]
press ctrl key to select multiple file cause the problem as well.

**Comment by akosyakov** [comment]
@yeweiasia Could you have a look into it?

**Comment by yeweiasia** [comment]
@akosyakov I'v create a new PR

**Comment by akosyakov** [comment]
should be fixed in https://github.com/theia-ide/theia/pull/4846
