### ISSUE TITLE
Unable to theia browser app with external extension

### ISSUE THREAD

**Issue by nehashri** [theia-ide/theia#372]
I am try to write an language extension with theia. I have created a extension package with extension.package.json. 
And a example browser module with theia.package.json. The browser module uses the new extension as a local dependency and all other theia modules use npm package (0.1.1 version). The app is building fine but when I start off the example, I am getting an exception in the UI, `Missing required @injectable annotation in: FrontendApplication.`. The same extension seems to work when I tried add it with theia built from source. Is there some annotations missing in Theia which is causing this problem? I tried externalizing the python package too. Found the same error.

**Comment by akosyakov** [comment]
It could be related to how we import `reflect-metadata` for `frontend` but I would need to check.

In `src-gen/frontend/index.js`, you can try to move `const { Container } = require('inversify');` down under `const { FrontendApplication } = require('@theia/core/lib/browser');` that `reflect-metadata` is imported before `inversify`.

**Comment by nehashri** [comment]
@akosyakov I tried pulling down `const { Container } = require('inversify');`.  I am still getting the same error.

**Comment by kittaakos** [comment]
@nehashri, you can reference a full-blown Theia extension [here]. We have created it for the YANG language. I hope it helps to resolve your issue.

[here]: https://github.com/yang-tools/yangster

**Comment by akosyakov** [comment]
@nehashri ok, we will need to try out to build an app mixing published extensions with local to reproduce an issue.

**Comment by nehashri** [comment]
@kittaakos in the yang extension, theia is built as a submodule. That will is not what I am looking for, as I will not be able to use the theia's published extensions. We would like to use theia's published extensions instead of building it from source every time. 
@akosyakov that's good. Hope this is resolved soon.

**Comment by nehashri** [comment]
Any updates on this issue?

**Comment by akosyakov** [comment]
@nehashri no chance to look at it so far, there is an issue to migrate the example project to the latest Theia with the setup similar you want to have: https://github.com/TypeFox/theia-xtext/issues/4

Feel free to open a PR there. Such PR will help to investigate this issue.

**Comment by akosyakov** [comment]
@nehashri it should be fixed, you can see such example here: https://github.com/theia-ide/theia-extension-example
