### ISSUE TITLE
[electron] Temporary disable the plug-in extensions in the electron example

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3723]
https://github.com/theia-ide/theia/issues/3651
https://github.com/theia-ide/theia/issues/2210

**Comment by benoitf** [comment]
yes, for now it looks the better path

**Comment by kittaakos** [comment]
> yes, for now it looks the better path

👍 Sure, I will take care of it and we will re-enable it later once it is fully functional.
