### ISSUE TITLE
[electron] Upgrade electron to version 3.x.x

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#3729]
In order to take advantage of updates and security fixes in electron, we should upgrade to the latest version of 3.x.x (currently [3.0.10](https://electronjs.org/releases#3.0.10)).

This would target the following sub-product versions:

- Node > `10.2.0`
- Chrome > `66`
- V8 > `6.6`

We should also update the minimum node version used by Theia to match the above (`>=10.2.0`).

According to [node.green](https://node.green/) this update would then allow support of all `ES2015` language features.

_Note:_ This should be done inline with [VS Code's support for electron](https://github.com/Microsoft/vscode/pull/56149).

**Comment by thegecko** [comment]
VS Code are planning on moving to electron 3.x in Q1 2019:

https://github.com/Microsoft/vscode/issues/52629#issuecomment-440149856

**Comment by thegecko** [comment]
Upgrading to node 10 would also fix #2009

**Comment by thegecko** [comment]
This now works on the [electron-3](https://github.com/theia-ide/theia/tree/electron-3) branch.

Tests are yet to pass, however.

**Comment by debovema** [comment]
Hi

This would also fix https://github.com/electron/electron/issues/15194 which was [merged](https://github.com/electron/electron/pull/15878) in Electron but backported only to 3.x and 4.x versions.

@thegecko : do you have an ETA for this issue ?

**Comment by thegecko** [comment]
@debovema what timescales are you working to? I'm happy to update the branch to get it working again and open a PR for discussion with the rest of the team.

My issue was getting the tests passing, would you be able to help with that?

**Comment by debovema** [comment]
I am mainly targeting a browser app but having an Electron app would be good on the long-term.

I will try to run the tests and see what's wrong.

**Comment by thegecko** [comment]
Fixed
