### ISSUE TITLE
Add a link to the gitter channel directly in the readme.md

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#373]
I could do it myself directly but I wasn't sure if everybody agreed to have that there. It might be easier then for developers looking into theia to find easy information without having to open an issue. Something like 

# Discussion
"For any questions related to theia (development, architecture, bugs), there is a  [gitter](https://gitter.im/theia-ide/theia) channel. Feel free to also open issues on Github for improvements,bugs etc."

At the end of the readme would be nice I think.

**Comment by svenefftinge** [comment]
We have the gitter badge already on top of the readme.

**Comment by epatpol** [comment]
You're right, wow I guess I really should check those badges more often. Thanks!
