### ISSUE TITLE
[preview-editor] breaks when start typing in preview

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#3734]
## Repro

open a file in the preview editor, then start typing. you gonna be asked to save the file immediately after the first key stroke.

also, if you cancel, two tabs will stay for the same file opened.

![2018-12-05 08 57 15](https://user-images.githubusercontent.com/914497/49506100-7f96f480-f87d-11e8-8b66-9862b0014513.gif)

**Comment by kittaakos** [comment]
Related https://github.com/theia-ide/theia/issues/3700?

**Comment by AlexTugarev** [comment]
Thanks! Closing as dupe.
