### ISSUE TITLE
[git] System/Global level `credential.helper` is not available from the electron application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3736]
This is a follow-up of #3397. Even if one [configures the `credential.helper`](https://help.github.com/articles/caching-your-github-password-in-git/) for Git, Theia does not use the system Git by default, so it has no effect.

Related #3571.

**Comment by svenefftinge** [comment]
It could be set on the repo, but still that doesn't seem to be a good solution for the desktop world.
Is there a way to pass the credential.helper config with every command?

**Comment by kittaakos** [comment]
> credential.helper config

It is possible to pass in custom configs with the `-c` flag. Do you have an idea to tackle this?

I wanted to add a command: `Use the global Git `credential.helper` in Theia`.
This command will try to locate the system git, run `git config --global credential.helper` and if that is defined, we will set this value in the embedded Git. Do you have a better approach?
