### ISSUE TITLE
[electron] There is no way to open the Dev Tools if the electron application is in a broken state

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3739]
I am not sure if this is related or not, but with [this](https://github.com/theia-ide/theia/commit/316c760b68231257da77b55ba217f43b14c9bc51#diff-e6697ec7c0f7ddbbfd9e8365baacf132R153) change, we set the application menu only when the [electron menu contribution has loaded](https://github.com/theia-ide/theia/blob/14078b4e3c1e783ea938c641fb5694ca6c60ec11/packages/core/src/electron-browser/menu/electron-menu-contribution.ts#L83).

The problem with this approach, there is no way to open the `Dev Tools` and access the console for the error stack trace.

See the attached image:

<img width="310" alt="bildschirmfoto 2018-12-05 um 13 54 34" src="https://user-images.githubusercontent.com/1405703/49515129-4cad2a80-f896-11e8-809a-e9b6b8b3740e.png">

@marechal-p, do you have any idea how can we tackle this problem. I like the changes you had made regarding the application menu, but clearly, we need a way to access the console.

**Comment by marechal-p** [comment]
Indeed, I thought that the shortcut would still be hooked. Turns out that if there isn't a menu for it, there isn't a shortcut for it :/

I am trying to see what would be the best way to bring this back, without adding menus if possible.

**Comment by kittaakos** [comment]
As a workaround, you can open `examples/electron/src-gen/frontend/electron-main.js` and uncomment `Menu.setApplicationMenu(Menu.buildFromTemplate([]));`.

I am more than happy with this solution.
