### ISSUE TITLE
Provide a Dockerfile for testing theia

### ISSUE THREAD

**Issue by rcjsuen** [theia-ide/theia#376]
Is the Theia team planning to provide a Dockerfile for testing Theia?

I hit some bumps while testing on [PWD](http://labs.play-with-docker.com/) but eventually got a Dockerfile that seems to get things up and running for me. You can use Vim to create the Dockerfile in your PWD node.

```Dockerfile
FROM node:7.10
RUN useradd --create-home theia
USER theia
WORKDIR /home/theia
RUN git clone --depth 1 https://github.com/theia-ide/theia && \
  cd theia && \
  yarn
EXPOSE 3000
WORKDIR /home/theia/theia/examples/browser
CMD yarn run start
```
```
$ docker build -t theia .
$ docker run -d -p 0.0.0.0:3000:3000 theia
```
Once the application has started, you can use the `3000` link at the top of PWD to open up Theia in a new browser tab.

**Comment by epatpol** [comment]
I don't know if it was planned or not, but I definitely think it's a good idea to have one working so thanks for that! I think it could be really useful to have a clean environment for the multiple tests theia has.

**Comment by marcdumais-work** [comment]
@rcjsuen awesome. I tried it and it worked nicely. 

I think the way forward is for you to submit this as a pull request. If not already done, please read file CONTRIBUTING.md in Theia's root.

**Comment by rcjsuen** [comment]
@marcdumais-work I'm not sure that it makes sense for this particular file to exist in the repository because the code has already been cloned and then you're cloning it again when Docker actually builds the image. However, I suppose there's no way around cloning the code since it's just testing the browser example and whatever bits you end up publishing to npm is probably not going to include the example, correct? So you either clone the code on your local machine then use the `COPY` instruction to copy stuff for Docker to use or you perform the full clone and build within Docker itself (which is what the above Dockerfile does).

**Comment by epatpol** [comment]
I agree, it's usually in another repo for that reason :)

**Comment by marcdumais-work** [comment]
@rcjsuen It's possible to use wget to download a file from GitHub, without cloning the whole repo. e.g. : 
```bash
wget https://raw.githubusercontent.com/theia-ide/theia/master/doc/Developing.md
```
We can keep the door open to future refactorings and re-organizations (like moving Docker files to a separate repo). But as a first step I think we need to have your work officially submitted to the project in a traceable way.

**Comment by svenefftinge** [comment]
+1 for having it within this repo.

**Comment by rcjsuen** [comment]
Where should this Dockerfile live? In `/` or `/examples/browser/`?

**Comment by epatpol** [comment]
I guess it makes sense, as it's basically wrapping the browser example.

**Comment by marcdumais-work** [comment]
Adding it under examples/browser sounds good to me. I think it would be nice to also add the build/run instructions, from the original post above, to help users use the dockerFile. I am not sure if it's customary to add such instructions in the dockerFile itself (as comments) or to have a separate file for that. 

Thanks @rcjsuen !

**Comment by rcjsuen** [comment]
I opened #406 to add the Dockerfile to the `/examples/browser/` folder.
