### ISSUE TITLE
Nodejs Debug Adapter Plugin

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#3766]
Provide NodeJS Debugger extension as a plugin

Depends on https://github.com/theia-ide/theia/issues/2990

@svenefftinge I believe the thinking is to keep Typescript/Theia support in the main repo, but it would still make sense to convert to a plugin-based version (in packages/debug-nodejs)

### Remain tasks to have fully-fledged node debug plugins 
- [x] Merge https://github.com/theia-ide/theia/pull/3902 (fix about debug contribution registration)
- [ ] ~~Introduce fix for Theia to handle duplication command registration when browser is refreshed (plugins run as sidecar) https://github.com/theia-ide/theia/issues/3970~~ Postponed

### Demo
[VS Code debug extension as remote plugins in Eclipse Che](https://www.youtube.com/watch?v=MhOjOwou--o&feature=youtu.be)

**Comment by svenefftinge** [comment]
We should directly use the vscode-extensions that are currently downloaded and wired.

**Comment by tolusha** [comment]
@svenefftinge 
As I understand I have
