### ISSUE TITLE
Typescript Language Plugin

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#3767]
Provide Typescript Language extension as a plugin

Depends on https://github.com/eclipse/che/issues/11468

@svenefftinge I believe the thinking is to keep Typescript/Theia support in the main repo, but it would still make sense to convert to a plugin-based version (in packages/typescript and packages/tslint)

**Comment by svenefftinge** [comment]
I think we should just reuse the typescript extension from VS Code?

**Comment by benoitf** [comment]
@svenefftinge AFAIK TypeScript is integrated in the VS Code product, it's not a `pure` extension that can be grabbed from VS Code marketplace

(for tslint there is one https://marketplace.visualstudio.com/items?itemName=eg2.tslint )

**Comment by tsmaeder** [comment]
> Before removing any extension, the plugin system should be complete and tested, and all clients (docker images, products) should move to use the plugin system.

So we need to go through a deprecation process, same as for API. For stuff that we move out of the main repo anyway (for example Java support), this can happen naturally (start new repo as a plugin), for typescript, we would have to have parallel code in the repo, for the time being.

**Comment by svenefftinge** [comment]
> For stuff that we move out of the main repo anyway (for example Java support), this can happen naturally (start new repo as a plugin)

I think we should aim at directly reusing vscode-java without any Theia-specific modifications. 
Maybe a good strategy would be try supporting that particular extension by doing so maturing the plug-in system. Once it is ready, we deprecate the @theia/java.

**Comment by svenefftinge** [comment]
Also many extensions seems to expect the standard vscode extensions (e.g. the python one expects the python language and configuration to be present). So maybe we should extract those extensions from VS Code and have them installed always.

**Comment by tsmaeder** [comment]
>  So maybe we should extract those extensions from VS Code and have them installed always.

Could you file an issue for that?

**Comment by tsmaeder** [comment]
One of the problems I'm trying to clear up is how vscode plugins are going to work when they are run in separate containers in Che 7. In particular, where to launch debuggees and how to use persistent volumes for plugin state have questions that need answering.

**Comment by svenefftinge** [comment]
I filed https://github.com/theia-ide/theia/issues/3815

**Comment by svenefftinge** [comment]
> VSCode plugins are written with the assumption that everything runs on a shared machine, which can cause problems.

It doesn't seem to cause many problems for the VS Code users.

**Comment by tsmaeder** [comment]
> It doesn't seem to cause many problems for the VS Code users.

Yes, but when running Theia in Che, things are different.

**Comment by tsmaeder** [comment]
For example, when a debug adapter tries to start a process to be debugged, it would typically be start it in the same container where the plugin is running, not the target (runtime) container.

**Comment by tolusha** [comment]
Since PR is merged it is possible to use VS Code extension [2] as a plugin in Theia. Currently it is available by direct url [3]. To build archive I use a docker file here [4]

[1] https://github.com/theia-ide/theia/pull/4170
[2] https://github.com/Microsoft/vscode/tree/master/extensions/typescript-language-features
[3] https://github.com/tolusha/ms-code.typescript/releases/download/1.0.0/che-typescript-language.vsix
[4] https://github.com/eclipse/che-theia/tree/ab/plugins/plugins/ms-vscode.typescript
