### ISSUE TITLE
Register a new menu action in order

### ISSUE THREAD

**Issue by nehashri** [theia-ide/theia#377]
I would like a feature where I can register a new menu action. Also for the menu action to take precedence over all other menu actions specified in the group. 
For example, currently in the 'New File Menu' group we have 
```
New File
New Folder
```
I would like to add a new menu action `My Menu Action`. At present, when added this will appear in the following order in 'New File Menu' group
```
New File
New Folder
My Menu Action
```
But I would like this appear in the following order
```
My Menu Action
New File
New Folder
```
Can this be done?

**Comment by akosyakov** [comment]
Menu items are sorted in the alphabetical order using the following properties `order`, `label`, `command.label` or `command.id`. If `order` is undefined then `label` used and so on.

You should provide a label or an order attribute which is greater in the alphabetical order than `New File`, something like:
```ts
@injectable()
export class MyMenuContribution implements MenuContribution {

    registerMenus(registry: MenuModelRegistry) {
        registry.registerMenuAction(FileMenus.NEW_GROUP, {
            commandId: 'myCommand',
            label: 'My Menu Action',
            order: '0_my_menu_action'
        });
    }
}
```

**Comment by nehashri** [comment]
@akosyakov, that works. Thanks a lot :)
