### ISSUE TITLE
Python VS Code extension

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3771]
I've tried to run [VS Code extension for Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python). It was installed sucessfully, but it does not seem to work.

Contributions are not localized:
<img width="630" alt="screen shot 2018-12-06 at 16 55 26" src="https://user-images.githubusercontent.com/3082655/49595226-d1bc4080-f977-11e8-8883-524e310b1dc9.png">

No language highlighting and support:
<img width="555" alt="screen shot 2018-12-06 at 16 55 32" src="https://user-images.githubusercontent.com/3082655/49595228-d1bc4080-f977-11e8-830b-902f313cc80f.png">

Errors from the backend:
<img width="1520" alt="screen shot 2018-12-06 at 16 55 41" src="https://user-images.githubusercontent.com/3082655/49595231-d254d700-f977-11e8-8de4-36a86dfc6126.png">

- [x] https://github.com/theia-ide/theia/pull/4458
- [x] https://github.com/theia-ide/theia/pull/4493
- [x] https://github.com/theia-ide/theia/pull/4480

**Comment by benoitf** [comment]
yes some LSP extensions are also providing debug stuff but debug stuff is not yet there (not even mocked)
but @tolusha is working on it

**Comment by akosyakov** [comment]
@benoitf ok

Also turned out that this extension does not include python language definition but relies on build VS Code extension (which is not on marketplace): https://github.com/Microsoft/vscode/tree/master/extensions/python

I will try to run them together when VS Code debug APIs are implemented.

**Comment by mannau** [comment]
@akosyakov Any updates on this after the merge?

**Comment by akosyakov** [comment]
@mannau i would try to give it a spin again

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/issues/3815 is needed for it

**Comment by tsmaeder** [comment]
It seems there already is a python grammar registered in the current python extension for theia. We could just migrate that to the "textmate-grammars" package.

**Comment by akosyakov** [comment]
@tsmaeder sounds good for now, eventually we don't want to support our textmate-grammars but consume them from source (VS Code)

**Comment by tolusha** [comment]
Now it is possible to use VS Code python extension [1]

![screenshot from 2019-03-04 10-59-59](https://user-images.githubusercontent.com/1640675/53721813-cf7d5b80-3e6c-11e9-965f-ff9830abace7.png)
![screenshot from 2019-03-04 10-59-26](https://user-images.githubusercontent.com/1640675/53721814-cf7d5b80-3e6c-11e9-812a-60ff77e9f97b.png)


[1] https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by tolusha** [comment]
Still have some errors in console

```
root ERROR Warning: Encountered two children with the same key, `$(refresh~spin) Refreshing Python Interpretersnull1null`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
```

**Comment by tolusha** [comment]
https://github.com/theia-ide/theia/pull/4493

**Comment by tolusha** [comment]
Related PRs merged. 
VS Code extension works. [1] 

[1] https://github.com/theia-ide/theia/issues/3771#issuecomment-469171523

- [x] https://github.com/theia-ide/theia/pull/4458
- [x] https://github.com/theia-ide/theia/pull/4493
- [x] https://github.com/theia-ide/theia/pull/4480

**Comment by Leletir** [comment]
@tolusha How did you manage to install the python debugger ?

**Comment by tolusha** [comment]
@Leletir 
yes, have you tried? https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by Leletir** [comment]
I'm using it on VS Code, so you've build Theia from source and added the `plugins` folder with this extension on it, isn't it ?
