### ISSUE TITLE
file name and paths are broken in search-in-workspace on windows

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#3773]
![siws_win](https://user-images.githubusercontent.com/37082801/49607625-678da680-f94b-11e8-8d6a-50b6ebf68e6e.PNG)

Ideally, the file paths should be relative to the workspace / folder path. Also, separators should not be rendered as "%5C"

**Comment by elaihau** [comment]
This is closely related to #3749

**Comment by westbury** [comment]
This is not only closely related to PR https://github.com/theia-ide/theia/pull/3749.  It is fixed by that PR.

**Comment by elaihau** [comment]
> This is not only closely related to PR #3749. It is fixed by that PR.

great :) I am closing this one as the PR has been merged.
