### ISSUE TITLE
Java Language Plugin

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#3778]
Provide Java language support as a plugin. We should get started with this plugin outside of the main theia repo (probably theia-ide/theia-java-plugin, but check with community). This task involves the following challenges: 
* Package jdt.ls as a theia plugin and hook it up to the language server plugin API.
* Java support uses some extensions to LSP: we need to come up with a way to support calling this additional protocol from within the java plugin
* We need a way that other plugins can hook up to extended protocol: in particular call custom commands and react to custom notifications.  We currently have some extensions sitting in github/che/che-theia-java-plugin. We will want to package that extension as a theia plugin eventually and need a way to call protocol on the connection to jdt.ls. My thinking is to expose the message connection as an API to other plugins.
* Identify places where we are missing plugin API. File issues for implementing the API. File issues to implement missing features once we have the API.

**Comment by svenefftinge** [comment]
Commented already [here](https://github.com/theia-ide/theia/issues/3767#issuecomment-445250224).
Instead of writing our own plug-in we should reuse the vscode-java extension. Also this should be a good way to sort out any rough edges in the plug-in system.

**Comment by tsmaeder** [comment]
After some deliberation, we've decided to try and run vscode-java inside Theia. There are at least 3 VSCode langauges APIs that are not implemented currently:
1. Rename
2. textDocument/documentColor
3. textDocument/foldingRange

jdt.lso does not provide documentColor. For the other two, we can ignore rename, and will have to stub foldingRange for the time being. They will be implemented by the IDE team in the next sprint (> dec 26.)

For other missing API's we encounter, we need to track them in tasks and implement them in separate PR's if they block progress on this task.

**Comment by tsmaeder** [comment]
@svor is going to work on this.

**Comment by svor** [comment]
Related issues:

Workspace folders are not initialized - https://github.com/theia-ide/theia/issues/3930
Code lens - https://github.com/theia-ide/theia/issues/3946
onWillSaveTextDocument event does not exist in API  https://github.com/theia-ide/theia/issues/4009
