### ISSUE TITLE
[widget tabs] Name doesn't fit

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#378]
We need to deal with long widget names, that don't fit the default size of a tab.
Also when opening many widgets in the same dock panel, the tab's size is evenly shared, making it hard to tell what widgets you have.

<img width="804" alt="screen shot 2017-08-07 at 11 38 22" src="https://user-images.githubusercontent.com/372735/29021206-04ea4764-7b65-11e7-9245-9a05a0d1b611.png">

**Comment by svenefftinge** [comment]
We should enable hovers.

**Comment by akosyakov** [comment]
It should be possible to provide the caption for the widget title: https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-manager.ts#L121

**Comment by svenefftinge** [comment]
Hi @mmorhun,  could you outline what you intend to do here?
I think this will be solved with #1177 which is what @spoenemann is currently working on.

**Comment by mmorhun** [comment]
@svenefftinge I wanted to enable hovers as you commented above, but it is done already (just checked).
So, nothing to do. (That label `help wanted` confusing a bit).

**Comment by svenefftinge** [comment]
Sorry for the consfusion, you are right. I will close this as a duplicate of #1177.
