### ISSUE TITLE
Error: Cannot apply @injectable decorator multiple times.

### ISSUE THREAD

**Issue by felipeweb** [theia-ide/theia#3780]
I don't know if i am doing something wrong, but i receive this error on browser console

![image](https://user-images.githubusercontent.com/4874009/49647359-602cd280-fa09-11e8-82bf-fa23cf52f064.png)

 *package.json*

```json
{
    "private": true,
    "dependencies": {
        "typescript": "latest",
        "@theia/callhierarchy": "^0.3.17",
        "@theia/core": "^0.3.17",
        "@theia/docker": "latest",
        "@theia/editor": "^0.3.17",
        "@theia/editorconfig": "^0.3.17",
        "@theia/extension-manager": "^0.3.17",
        "@theia/file-search": "^0.3.17",
        "@theia/filesystem": "^0.3.17",
        "@theia/git": "^0.3.17",
        "@theia/json": "^0.3.17",
        "@theia/keymaps": "^0.3.17",
        "@theia/languages": "^0.3.17",
        "@theia/markers": "^0.3.17",
        "@theia/merge-conflicts": "^0.3.17",
        "@theia/messages": "^0.3.17",
        "@theia/mini-browser": "^0.3.17",
        "@theia/monaco": "^0.3.17",
        "@theia/navigator": "^0.3.17",
        "@theia/outline-view": "^0.3.17",
        "@theia/output": "^0.3.17",
        "@theia/plugin": "^0.3.17",
        "@theia/plugin-ext": "^0.3.17",
        "@theia/plugin-ext-vscode": "^0.3.17",
        "@theia/preferences": "^0.3.17",
        "@theia/preview": "^0.3.17",
        "@theia/process": "^0.3.17",
        "@theia/search-in-workspace": "^0.3.17",
        "@theia/task": "^0.3.17",
        "@theia/terminal": "^0.3.17",
        "@theia/textmate-grammars": "^0.3.17",
        "@theia/tslint": "^0.3.17",
        "@theia/typescript": "^0.3.17",
        "@theia/userstorage": "^0.3.17",
        "@theia/variable-resolver": "^0.3.17",
        "@theia/workspace": "^0.3.17",
        "@coloradoide/authenticator": "0.0.22"
    },
    "devDependencies": {
        "@theia/cli": "^0.3.17"
    },
    "theia": {
        "target": "browser"
    }
}

```

**Comment by akosyakov** [comment]
`@theia/docker` seems to be published against next version, not latest.

**Comment by felipeweb** [comment]
@akosyakov unfortunately, I change to @theia/docker: next and still receive the same error

**Comment by svenefftinge** [comment]
This kind of errors happen if you have pulled different versions of the same theia extension (probably core?). You can check by looking for nested `node_modules/@theia/<someextension>/node_modules/@theia`. If you see them your config is not good. You need to make sure there is only one version.

**Comment by marcdumais-work** [comment]
Hi @felipeweb . I think the problem is that we do not have a released `latest` version for `@theia/docker`, only a few `next`, so you end-up pulling `latest` and `next` together. If you do not absolutely need this extension, removing it from package.json should fix your issue.

**Comment by felipeweb** [comment]
I found the problem guys thank all. It was two versions of theia core

**Comment by Akumzy** [comment]
@felipeweb how did you solve your own problem,  just installed everything based on documentation but am still getting the same error
![screenshot from 2019-01-14 19-47-04](https://user-images.githubusercontent.com/25849232/51133520-7bbfa000-1835-11e9-9924-d8507ba04aa2.png)

**Comment by marcdumais-work** [comment]
Hi @Akumzy 

Can you share the `package.json` for your application and point to the instructions you have been following?

**Comment by Akumzy** [comment]
```json
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}


```

**Comment by Akumzy** [comment]
> Hi @Akumzy
> 
> Can you share the `package.json` for your application and point to the instructions you have been following?

[The official DOC](https://www.theia-ide.org/doc/composing_applications)

**Comment by marcdumais-work** [comment]
@Akumzy  I think the latest commit on master has not released correctly, as `next` version on npm: some packages are not found. This happens once in a while. I have restarted the CI for that commit. Normally it works correctly the second time, whenever we see this issue. Please wait ~30 minutes and try again.

**Comment by Akumzy** [comment]
ok thanks

**Comment by seethroughtrees** [comment]
seeing same result as others with fresh install.  used same package.json from docs.

looks like in `yarn.lock`, doubling lots of versions with `0.4.0-next.73d23a46` and `0.4.0-next.b0c99c12`

not sure the best way to resolve, but hope it helps towards clearing this up.

**Comment by adrienrenaud** [comment]
For me it was `"@theia/typehierarchy": "^0.4.0"` causing the problem. Removing this line from `package.json` fixed it.

**Comment by rhildred** [comment]
This probably sounds like superstition. I deleted my yarn.lock and added it to my .gitignore. I also deleted my node_modules and did `yarn cache clean`

**Comment by dhananjayharel** [comment]
I am getting this error when I try to build docker image 
here is my package.json file
{
    "private": true,
    "dependencies": {
        "typescript": "next",
        "@theia/typescript": "next",
        "@theia/navigator": "next",
        "@theia/terminal": "next",
        "@theia/outline-view": "next",
        "@theia/preferences": "next",
        "@theia/messages": "next",
        "@theia/git": "next",
        "@theia/file-search": "next",
        "@theia/markers": "next",
        "@theia/preview": "next",
        "@theia/callhierarchy": "next",
        "@theia/merge-conflicts": "next",
        "@theia/search-in-workspace": "next",
        "@theia/json": "next",
        "@theia/textmate-grammars": "next",
        "@theia/mini-browser": "next"
		
    },

    "devDependencies": {
        "@theia/cli": "next"
    }
}

**Comment by ReinforceZwei** [comment]
I got the same error when I added `@theia/java` as a dependence to the `package.json` file.
Remove `@theia/java` from `package.json` and rebuild theia, then everything fine.

This is the `package.json` file that is NOT working
```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next",
    "@theia/java": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```
Any solution?

**Comment by marcdumais-work** [comment]
@ReinforceZwei Let me try

**Comment by marcdumais-work** [comment]
@ReinforceZwei It worked for me, using your `package.json` above. Most likely there was a temporary npm glitch or `@theia/java` did not published correctly for one `next` and was fixed soon after.

**Comment by marcdumais-work** [comment]
@ReinforceZwei It worked for me, using your `package.json` above. Most likely there was a temporary npm glitch or `@theia/java` did not published correctly for one `next` and was fixed soon after.

**Comment by ReinforceZwei** [comment]
@marcdumais-work It seems to be my problem.
My last try was based on a built theia. I modified the `package.json` and ran the build command again.
Now I built a brand new theia with `@theia/java` in a new directory and it worked perfectly.
Anyway thanks for your help!
