### ISSUE TITLE
Return mini browser result to node server

### ISSUE THREAD

**Issue by RimShao** [theia-ide/theia#3783]
Hi JanKoehnlein/Sven,

Now our Json Editor can be open with Mini Browser via Open Hander, then one more question is:

How can we upload the mini browser html result to the node server side within theia-Ide framework, I attache our Json Editor in the mini browser, the question is how to return the Json Output to the node server.
![minibrowser](https://user-images.githubusercontent.com/36630897/49649560-c9244280-fa29-11e8-8315-21e757692472.png)

 Just like the two links below: 

https://scotch.io/tutorials/express-file-uploads-with-multer

https://www.thepolyglotdeveloper.com/2016/02/upload-files-to-node-js-using-angular-2/

**Comment by svenefftinge** [comment]
Looks like you are creating a form-based JSON editor? 
You should implement an actual editor for that. In Theia you can read and write contents of files through the FileSystem.

**Comment by RimShao** [comment]
Thanks Sven.

Yes, it is form-based Json Editor, Now we setup http server in backed to receive the Json Output.
