### ISSUE TITLE
[git] there has no refresh button in git view in some case

### ISSUE THREAD

**Issue by zixuemeng** [theia-ide/theia#3801]
1.open a workspace which has no git repo
2.open git view,  it shows "Version control is not available at this time"
3.git clone a repo
There has no refresh button in git view in this case,  so I can only refresh the browser to update git view.

**Comment by westbury** [comment]
Sorry, disregard my comment about isEqualOrParent being used backwards.  It is correct there, but would need to be reversed if used is isAffected to look for changes to child objects inside the workspace.

**Comment by zixuemeng** [comment]
This issue has been fixed in 0.4.0 version
