### ISSUE TITLE
file search does not retrieve files from hidden folders

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#3809]
@vince-fugnitto found that files in hidden folders didn't show up in the file search results, while vsCode users don't have this problem.

![peek 2018-12-11 10-10](https://user-images.githubusercontent.com/37082801/49809523-1d326e00-fd2d-11e8-90f3-76c0c0ed4697.gif)

**Comment by lmcbout** [comment]
Can use CTRL+P to "Show/Hide" searching folders.

**Comment by Leletir** [comment]
Is it possible to desactivate the display of hidden files by default ?

**Comment by vince-fugnitto** [comment]
@Leletir the flag to show / hide ignored files is found here https://github.com/theia-ide/theia/blob/45f8993d5843d01b534518d390814c1083c044c4/packages/file-search/src/browser/quick-file-open.ts#L64

Perhaps if you'd like more control you can add a new preference where user's can decide for themselves the default behaviour of either showing / hiding ignored files when using the quick-open.

From my personal experience however, showing all files (ex: everything under node_modules) would just be unnecessary noise. If a user truly wants to see all files, it's simply an extra command <kbd>ctrl</kbd>+<kbd>p</kbd> once the quick-open has opened but it's up to you :)

**Comment by Leletir** [comment]
@vince-fugnitto thank you for the answer !

That's weird because by default theia show all the hidden files.
Is there a configuration file where I can set the value of `hideIgnoredFiles` ?

Complety agree with you 

> From my personal experience however, showing all files (ex: everything under node_modules) would just be unnecessary noise. If a user truly wants to see all files, it's simply an extra command ctrl+p once the quick-open has opened but it's up to you :)

**Comment by elaihau** [comment]
Patterns defined in .gitignore should not show up, however it is broken (reported in https://github.com/theia-ide/theia/issues/1588).

**Comment by Leletir** [comment]
If I understand when theia open a workspace, it looks for a .gitignore file and it should not dispay the files ignored in the .gitignore, is it right ?

**Comment by elaihau** [comment]
you are absolutely right. 

i looked into this issue a couple of months ago, but i forgot what stopped me. If interested, you are welcomed to open a pull request to make it better. Thank you !

**Comment by Leletir** [comment]
@elaihau Thank you very much.

I was thinking about, by default not displaying the files starting by .*

**Comment by elaihau** [comment]
> @elaihau Thank you very much.
> 
> I was thinking about, by default not displaying the files starting by .*

sorry i don't get it - why "not displaying files starting by .*" helps in case? not all files under `node_modules` have names that start with a dot. and potentially you could have any patterns (not just patterns starting with a dot) in .gitignore.

**Comment by Leletir** [comment]
Yes, I was thinking to my use case, but yes `node_modules` and a lot of patterns could be added
