### ISSUE TITLE
[quality][question] The `SymbolKind` enum is defined three times in the repo

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3810]
This is super minor. I found it accidentally in the source.

@benoitf, can we use the `SymbolKind` from the `@theia/languages` instead of redefining it twice in the plug-in extensions? `@theia/plugin` does not directly depend on `@theia/languages` but it is available through `@theia/monaco`. Thanks!

**Comment by benoitf** [comment]
hello @kittaakos 
I had the same remark (about the twice, not the third ! :-)
https://github.com/theia-ide/theia/pull/3483/files#r233357173

**Comment by benoitf** [comment]
@azatsarynnyy @evidolob ?

**Comment by azatsarynnyy** [comment]
I've removed the one from the `@theia/plugin` https://github.com/theia-ide/theia/pull/3814

**Comment by azatsarynnyy** [comment]
`SymbolKind` enum from the `@theia/languages` is different for some reason

**Comment by kittaakos** [comment]
Closed via https://github.com/theia-ide/theia/pull/3814.
