### ISSUE TITLE
Authentication Page

### ISSUE THREAD

**Issue by Pragmatik225** [theia-ide/theia#3824]
I just installed theia on my VPS server and I want to secure access to my code on it. I read through over issues but I still don't know how to set it up. Someone can help me? I just want a page which ask for credentials before give access to the IDE.

**Comment by svenefftinge** [comment]
It is out of scope for Theia. You can use anything from basic auth to having a proxy in between.
Hosting solutions like gitpod.io or eclipse che have full support for auth and user management.
