### ISSUE TITLE
Add an alias for `hostname`.

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3829]
~`h`~ ~or~ `host` can be an alias.

Originally from here: https://github.com/gitpod-io/gitpod/issues/181

One has to perform the changes here: https://github.com/theia-ide/theia/blob/9310c318fb9a7ee3b8241290f5c2c72c4442476c/packages/core/src/node/backend-application.ts#L59

**Comment by akosyakov** [comment]
I thought that `-` stands for single-character options, i.e. it cannot be `-host` but `-h`. Although it would be happy to have both `-h` and `--host`.

**Comment by jgbradley1** [comment]
This issue should be closed since the work is complete.
