### ISSUE TITLE
EditorManager: currentEditorChangedEvt is not emitted when an editor is closed

### ISSUE THREAD

**Issue by kaviththiranga** [theia-ide/theia#3846]
Open two files and close the last one. The editor for first one gets visible (it is not still the active one or has focus).

as per [this](https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-manager.ts#L78) I am expecting listeners registered via onCurrentEditorChanged to be invoked for this scenario.

Am I missing something?

**Comment by kaviththiranga** [comment]
same happens with the open scenario, if opened editors does not get focus or gets activated (opening by a single click on explorer), currentEditorChangeEvt is not emitted. But can overcome that by registering a listener to EditorManager:onCreated.

May be I am looking at wrong place and should focus on event emitters at generic Widget level to capture these.

**Comment by akosyakov** [comment]
Could you elaborate on what you want to achieve? If the widget does not get focus, `onCurrentEditorChanged` won't be triggered for it. It is expected.

**Comment by akosyakov** [comment]
If there are multiple visible editors and none of them has focus how do you define `currently visible editor`? first visible?

Maybe you can try to pick the first editor which is visible if there is no a current editor. Listening to `EditorManager.onCreated` sounds like a good idea for the initial opening without focus then, something like:
```ts
manager.onCurrentChanged(() => updateVisible());
manager.onCreated(() => updateVisible());
function updateVisible(): void {
    const currentVisible = manager.currentEditor || manager.editors.all.find(e => e.isVisible);
}
```

**Comment by kaviththiranga** [comment]
@akosyakov, I have created a screen capture to better explain my requirement.

https://drive.google.com/file/d/1Gaonwzvx74jdV-qGn2XvmxIuRv7FePWh/view?usp=sharing

We have a singleton react widget that renders a diagram depending on currently active editor.  It uses ``` manager.currentEditor  ``` to access target document for which it has to render the diagram.
As you can see in the video shared above, when we are opening a new editor or closing an existing one,  ``` manager.currentEditor  ``` becomes undefined unless we click and put focus on now visible text editor.  For opening scenario, we can overcome this by listening to ``` EditorManager.onCreated ```, but in the closing scenario, we don't have a way.

**Comment by kaviththiranga** [comment]
BTW I am unable to see field editors in EditorManager as shown in your example snippet above ``` manager.editors.all.find(e => e.isVisible); ```

**Comment by akosyakov** [comment]
it should be `manager.all`

**Comment by kaviththiranga** [comment]
@akosyakov thanks, I was able to resolve this with it.
