### ISSUE TITLE
Minimize a view container inside a split panel

### ISSUE THREAD

**Issue by tolusha** [theia-ide/theia#3860]
View container widget can't be minimized when size of the widget is controlled by a split panel.

![screencast-localhost-3000-2018 12 19-11-41-57](https://user-images.githubusercontent.com/1640675/50212243-39fd2000-0383-11e9-8675-188dc17acbe0.gif)

**Comment by akosyakov** [comment]
@tolusha can you check whether it is still a case? view container was refactored recently

**Comment by tolusha** [comment]
I can't reproduce this anymore.
