### ISSUE TITLE
File download should check read privilege instead of write privilege

### ISSUE THREAD

**Issue by legenddcr** [theia-ide/theia#3870]
https://github.com/theia-ide/theia/blob/248775060d/packages/filesystem/src/node/download/file-download-handler.ts#L58

I just found that Theia file download check whether calling process has write privilege or not before doing actual download. It seems check R_OK privilege is enough. 

Have confirmed with @kittaakos and I will try to submit a patch for this issue. Thanks.

**Comment by kittaakos** [comment]
@legenddcr, I have assigned you to the task. Let us know if you need assistance.
