### ISSUE TITLE
[preferences] unable to define group preference which contains another group in its name

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3875]
There is an bug when defining a preference's `group` which contains another `group` in its name
(ex: `cpp` and `cpp-debug`).

This will result in an odd rendering of the tree which duplicates a preference for both groups and only permits one group in the `preferences-tree` to be active at a given time.

**Comment by kittaakos** [comment]
> when defining a preference's `group` which contains another `group` in its name

@vince-fugnitto, how can I do that? I want to verify your PR. Thanks!

**Comment by vince-fugnitto** [comment]
> > when defining a preference's `group` which contains another `group` in its name
> 
> @vince-fugnitto, how can I do that? I want to verify your PR. Thanks!

For instance I updated the `cpp-preferences` to add a custom preference for test purposes called `cpp-test.test` with mock description, type and default values. On master you'll notice an odd behaviour when building which results in both the `cpp` and `cpp-test` groups containing the same preference from the preference tree widget. At the same time, only one of these groups can be open at the same time.

In my PR this issue will be fixed, only `cpp-test` will contain the preference, and there is no longer an odd behaviour with only one of the tree groups being opened at a given time.

Let me know if that was still unclear when testing !

**Comment by kittaakos** [comment]
> For instance I updated the `cpp-preferences` to add a custom preference for test purposes called `cpp-test.test` with mock description, type and default values. On master you'll notice an odd behaviour when building which results in both the `cpp` and `cpp-test` groups containing the same preference from the preference tree widget. At the same time, only one of these groups can be open at the same time.

Does this mean I cannot verify without changing the code?

**Comment by vince-fugnitto** [comment]
> > For instance I updated the `cpp-preferences` to add a custom preference for test purposes called `cpp-test.test` with mock description, type and default values. On master you'll notice an odd behaviour when building which results in both the `cpp` and `cpp-test` groups containing the same preference from the preference tree widget. At the same time, only one of these groups can be open at the same time.
> 
> Does this mean I cannot verify without changing the code?

Yes unfortunately, I noticed the issue when creating an extension that had in its name a substring of another group. In order to not have issues in the future, and only get a full match and not simply `startsWith` I made the update. Do you believe since we do not have an issue today with any of our preferences that we should not fix it ?
