### ISSUE TITLE
[views] pass the selected tree item to a command's argument

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#3882]
Theia should pass the selected tree item as an argument to the command executed from the context menu. See the attachments for details.
It's related only to the views contributed by the plugins.

#### Examples
VSCode 
The selected tree item is passed to the executed command's argument and the plugin just calls the command.

![vscode](https://user-images.githubusercontent.com/1636395/50335368-b9b9f480-0513-11e9-8f73-b35a3bfc8aeb.gif)

Theia
The selected tree item isn't provided to the executed command and the plugin asks user to specify it manually.

![theia](https://user-images.githubusercontent.com/1636395/50335382-c3435c80-0513-11e9-8261-37fe6282b30d.gif)

**Comment by akosyakov** [comment]
fyi: you should be able to retrieve the currently selected item from the global selection service

**Comment by tsmaeder** [comment]
Ok this is about the contribution point https://code.visualstudio.com/api/references/contribution-points#contributes.menus
There is a "note" section saying that the uri of the "current" resource should be passed to the command.

**Comment by akosyakov** [comment]
@tsmaeder it was implemented in https://github.com/theia-ide/theia/pull/4173/commits/e5c8ff9e60ae1c4df11cda5962a9a5d3a6aa9c57

@azatsarynnyy Could you verify?

**Comment by azatsarynnyy** [comment]
@akosyakov I've just checked it vscode k8s extension and it works the same way as it's described in the issue. So nothing is changed in the behavior.
There's the error in the console:
```
root ERROR [hosted-plugin: 24614] (node:24614) UnhandledPromiseRejectionWarning: Error: The command 'null' cannot be executed. There are no active handlers available for the command. (args: [{"kind":{"displayName":"Namespace","pluralDisplayName":"Namespaces","manifestKind":"Namespace","abbreviation":"namespace"},"id":"default","metadata":{"name":"default","active":false},"resourceId":"namespace/default"}])
    at CommandRegistry.<anonymous> (http://localhost:3000/bundle.js:96000:31)
    at step (http://localhost:3000/bundle.js:95807:23)
    at Object.next (http://localhost:3000/bundle.js:95788:53)
    at http://localhost:3000/bundle.js:95782:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (http://localhost:3000/bundle.js:95778:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (http://localhost:3000/bundle.js:95987:16)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (http://localhost:3000/79.bundle.js:4626:72)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/79.bundle.js:827:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/79.bundle.js:812:41)

root ERROR [hosted-plugin: 24614] (node:24614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
```

**Comment by akosyakov** [comment]
ok, so it is unrelated to https://code.visualstudio.com/api/references/contribution-points#contributes.menus

> It's related only to the views contributed by the plugins.

only to it :+1, i update the desc

**Comment by tsmaeder** [comment]
@akosyakov sorry, but shouldn't that be "Pass the selected tree item as an argument to a command"? At least that was the impression I got after speaking to Artem yesterday. Anyway...from the description now, I don't understand what the problem should be.

**Comment by akosyakov** [comment]
The note says only about currently selected resource (`URI`), which already the case.

In the case with `View` widget, no an URI, but the tree item should be passed. It would require special handling.

**Comment by tsmaeder** [comment]
Ok, but I don't see that in the VS Code documentation.

**Comment by vzhukovskii** [comment]
For this moment in progress implementing two actions:

* Kubernetes: Add File
* Kubernetes: Delete File

Found dependent issue, which temporary blocks the development: https://github.com/theia-ide/theia/issues/4752
