### ISSUE TITLE
[generator] theia widget generator

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#3890]
I've created a `yeoman` generator to easily build the scaffold of a widget contribution in Theia.
This allows users to easily setup the base of what's needed to easily create a widget in Theia, 
and enhance the base `hello-world` example to also display how easy it is to create a widget.

https://github.com/vince-fugnitto/theia-widget-generator

If people find it useful, perhaps we can include it under the main `theia-ide` organization so other developers can easily discover. Any thoughts?

**Comment by vince-fugnitto** [comment]
> Cool idea. I wonder would it make sense to merge it into https://github.com/theia-ide/generator-theia-extension? The generator could ask which kind of extension should be generated, i.e. `HelloWorld`, `View`, `Language` and so on.

yes I think that's a great idea!

**Comment by vince-fugnitto** [comment]
Thanks @akosyakov, I don't believe I have the necessary rights to the `theia-extension` widget, so for the moment I can fork it and make my updates there.

**Comment by akosyakov** [comment]
@vince-fugnitto I've sent an invitation that you can create a branch there as well

**Comment by vince-fugnitto** [comment]
closing thanks to https://github.com/theia-ide/generator-theia-extension/pull/26
