### ISSUE TITLE
Add the needed methods for Webview API

### ISSUE THREAD

**Issue by olexii4** [theia-ide/theia#3896]
Implement the next methods and add calling for needed events for Webview API:
- [x] registerSerializer
- [x] unregisterSerializer
- [x] reveal
- [x] viewColumn
- [x] onDidChangeWebviewPanelViewState

**Comment by olexii4** [comment]
https://code.visualstudio.com/docs/extensions/webview

**Comment by akosyakov** [comment]
@olexii4 are you looking into it?

**Comment by olexii4** [comment]
@akosyakov 
No. I have a lot of other high priority tasks in the current sprint

**Comment by olexii4** [comment]
Maybe in the next one

**Comment by akosyakov** [comment]
Please close the issue next time when it is really done. `registerSerializer` and `unregisterSerializer` were not properly implemented, see https://github.com/theia-ide/theia/issues/5647
