### ISSUE TITLE
Uncaught exception when Open folder on file tree

### ISSUE THREAD

**Issue by legenddcr** [theia-ide/theia#3898]
When click "open" context menu on a file tree folder, nothing happens. And there is Uncaught exception happens:

```
Uncaught (in promise) A resource provider for 'file:///workspace/theia/examples' is not registered.
```

GitPod has the same issue. In VSCode, there is no open context menu on folder node.

**Comment by legenddcr** [comment]
I used Theia 0.3.18 release
![image](https://user-images.githubusercontent.com/1400573/50468922-34d44c80-09e5-11e9-91c1-530042f5b589.png)

**Comment by akosyakov** [comment]
a dup of: https://github.com/theia-ide/theia/issues/1308?

**Comment by svenefftinge** [comment]
dupe see https://github.com/theia-ide/theia/issues/3898#issuecomment-450808822
