### ISSUE TITLE
[plug-in] TreeView should be created on registering a TreeDataProvider

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#3907]
Currently, Theia adds a TreeView for each registered TreeDataProvider only once - as soon as the frontend app is reached [a `ready` state](https://github.com/theia-ide/theia/blob/d24fbec78f2b49efef65035374532e94216ae00c/packages/plugin-ext/src/main/browser/view/view-registry.ts#L48-L51). It's not correct behavior for two reasons:
- a plugin can register a `TreeDataProvider` at any time but not only from `start` entrypoint
- on slow infrastructure a plugin registers `TreeDataProvider` later than the frontend app goes into a `ready` state

In any of the cases, plugin's tree isn't shown in a contributed view.

It works perfectly in standalone Theia but the problem is stable reproducible on some slow environment. For example, try the following steps:
- run Eclipse Che with Theia editor on minikube or use https://che.openshift.io
- clone the https://github.com/eclipse/che-theia-samples into workspace
- run the `tree-view-sample-plugin` on development host
- the `comments` view is empty

When I add some delay before the front app goes into a `ready` state then tree is shown in the view. To add such delay open several files and reload the browser's page.

**Comment by vitaliy-guliy** [comment]
One thing. I suppose TreeView must be created immediately only when `ready` state of Theia is reached.
Anyway we need to check.
