### ISSUE TITLE
Include Task commands to the main command palette

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#3935]
* Include all tasks from `tasks.json` file to main command palette (F1).
* Add preference item (disabled by default) to control viewing task items in the main command palette.
related issue: https://github.com/eclipse/che/issues/12239

**Comment by akosyakov** [comment]
In VS Code they have a special prefix for it `task`. `Quick Open` (F1) and then type `task`. We can do exactly the same. It would be also aligned with what we already have for commands and symbols, there prefixes are `>` and `#`.

**Comment by vince-fugnitto** [comment]
> In VS Code they have a special prefix for it `task`. `Quick Open` (F1) and then type `task`. We can do exactly the same. It would be also aligned with what we already have for commands and symbols, there prefixes are `>` and `#`.

It looks like Theia already has it unless I'm mistaken:

<img width="631" alt="screen shot 2019-01-03 at 11 33 13 am" src="https://user-images.githubusercontent.com/40359487/50649304-8469c980-0f4b-11e9-826c-c96c8477c86a.png">

**Comment by vinokurig** [comment]
@vince-fugnitto 
> It looks like Theia already has it unless I'm mistaken:

`> task` just shows the `Run Task` action witch will open a new palette with all tasks. The idea is to show tasks without executing an action.

@akosyakov @svenefftinge
I agree with you that adding a new prefix for Tasks make sense.

**Comment by vinokurig** [comment]
@akosyakov 
> you should remove >, just task then it seems to work already

You are right !
> F1 - actually is quick command, maybe we can introduce a new keybinding for the general quick open which opens without > prefix and one can type taskthen, or refactor existing Ctrl + P keybinding for it to align with VS Code

As far as I understood `Ctrl + P` keybinding already opens general quick open which opens without > prefix.

**Comment by vinokurig** [comment]
Already implemented
