### ISSUE TITLE
[plug-in] Code lens feature doesn't work correctly

### ISSUE THREAD

**Issue by svor** [theia-ide/theia#3946]
Code lenses are not displayed when trying to run vscode-jsva extension as a plugin in Theia.
Looks like `command-registry:CommandsConverter` works incorrectly.

**Comment by tsmaeder** [comment]
@svor do you have any more info on what is wrong with the CommandConverter?

**Comment by svor** [comment]
@tsmaeder 
`CommandsConverter` wants to convert the command from `CodeLens` to internal command `model:Command` but the structure of `CodeLens.Command` is not the same as  `theia:Command`
