### ISSUE TITLE
Git view show 'Version control is not available at this time' after git clone form command

### ISSUE THREAD

**Issue by evidolob** [theia-ide/theia#3948]
Git view has enabled control only after Theia reload, see gif:
![ezgif com-optimize](https://user-images.githubusercontent.com/929743/50689466-822e6a80-1032-11e9-8374-02726e08f803.gif)

**Comment by vince-fugnitto** [comment]
@evidolob 
Do you mind re-testing? I believe it's been addressed with #3831

**Comment by evidolob** [comment]
@vince-fugnitto I re-test and issue are fixed, thx.
