### ISSUE TITLE
[Java] Extension doesn't support `workspace/executeClientCommand`

### ISSUE THREAD

**Issue by BoykoAlex** [theia-ide/theia#3951]
JDT LS extends the LS protocol with `workspace/executeClientCommand`.
The Theia client side doesn't have support to handle this request message.
See VSCode extension for Java for references:
https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L183
https://github.com/redhat-developer/vscode-java/blob/master/src/protocol.ts#L99

**Comment by marechal-p** [comment]
Does https://github.com/theia-ide/theia/pull/3962 fix your issue?

**Comment by BoykoAlex** [comment]
@marechal-p yes, it's the same PR as mine. I had exactly the same PR, but doesn't look like TS compiler options in the theia java package like `any` type... Had to modify it a bit to get the build to pass. I also forgot to link my PR to the the issue....

**Comment by marechal-p** [comment]
Ah, my bad.
