### ISSUE TITLE
[Git] Unable to return to the initial commit after pressing the "Amend" button

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3959]
In the Git view, Click on the "Amend" (bottom portion of the view) and the commit change to the previous commit like doing the command : git reset --soft HEAD^
After the end-user selected the "Amend" button, there is no "Cancel" or "Undo" button to return to the original commit, you just been switched to a previous commit.
Also, the "Amend" button is also available to select another previous commit. If the end-user selects it again, it brings the files for that previous commit with the files from a different commit. If the user select the "Commit" at that time, it will create a new commit with all the files from any users and different commits.

**Comment by westbury** [comment]
This is a duplicate of https://github.com/theia-ide/theia/issues/3851

**Comment by lmcbout** [comment]
Agreed, Changing the name of the "Amend" button would help, but I think it is not enough, we would need an option to revert or cancel the action.

**Comment by kpge** [comment]
@lmcbout @vinokurig  I find the same problem. And the name of the 'Amend' button is still not changed,  it will confuses  a new user. Usually，amend is `git commit --amend `.
