### ISSUE TITLE
Failed to build related to @theia/outline-view

### ISSUE THREAD

**Issue by weikai** [theia-ide/theia#3964]
Theia is failed to build related to missing @theia/outline-view version.  I was able to build it yesterday with the same package.json file but not now.

warning @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning @theia/outline-view > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/cpp > @theia/filesystem > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
error Couldn't find any versions for "@theia/outline-view" that matches "0.4.0-next.fb39727e"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.12.3
error Command "theia" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c cd /opt/theia&&sudo -Hu $user yarn --cache-folder ./ycache && rm -rf ./ycache;sudo -Hu $user yarn theia build' returned a non-zero code: 1

**Comment by akosyakov** [comment]
Sometimes yarn fails to publish all packages :( It seems to happen again. Let's wait for a new build and see whether it helps.

**Comment by akosyakov** [comment]
Please follow this issue https://github.com/theia-ide/theia/issues/4083 instead. Closing as a dup.
