### ISSUE TITLE
yarn.lock is ignored 

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#398]
Because of https://github.com/lerna/lerna/issues/852 yarn.lock is ignored and thus the dependencys are not managed properly

**Comment by hexa00** [comment]
Actually I'm not so sure about that now... 

I don't know what triggers a yarn.lock update, but it doesn't seem to trigger all the time.

Also maybe we should use  --npm-client=yarn

**Comment by hexa00** [comment]
@akosyakov  do you have any hints about this one ?

**Comment by akosyakov** [comment]
Could you elaborate what is broken?

One rule with hoisting that we should use the dependency with the same version in all packages, otherwise it won't be hoisted and will be installed with npm.

**Comment by hexa00** [comment]
Yes so what happens is that some of the time, there seem to be a race condition that causes yarn.lock to be updated without any changes to package.json.

So doing yarn on master with no changes and then checking git status you will see yarn.lock as modified.

I usually notice that when I want to update a patch at some point I'll get a modified yarn.lock for no apparent reason.

We also got the issue with travis some UI test would start failing because a underlying webdriver io update was breaking it.

The thing is I don't understand enough all the moving parts here to pinpoint where the race could be... maybe you have a idea ? or could explain a bit more all the parts that modify package.json etc during a yarn install... ?

**Comment by hexa00** [comment]
But why would it update like once every 3 days and then not update for 3 days.... ?

If it updated consistently I would get it but as it is.. it seems like sometimes it does and sometimes it doesn't

**Comment by hexa00** [comment]
Also if I understand this properly this makes yarn.lock useless ?

**Comment by akosyakov** [comment]
probably depends on node_modules state, e.g. if there is already such package when preserves it, if not adds the latest matching, not sure

**Comment by hexa00** [comment]
OK I'll leave that open until we find a solution for lerna in general.

**Comment by akosyakov** [comment]
The solution will be to use yarn workspaces. It is possible to use with https://github.com/theia-ide/theia/pull/527. But I did some experiments and lerna + yarn workspaces is very slow with our setup.

**Comment by hexa00** [comment]
Do we still need lerna with this ?
I sure would like to get back the yarn.lock even if it's slower... unless you're talking hours...

**Comment by akosyakov** [comment]
Turned out that I run `lerna bootrap` which should not be run with yarn workspaces. It is quite fast and enabled with https://github.com/theia-ide/theia/pull/527

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/pull/527
