### ISSUE TITLE
The Git features are not available after cloning a project from GitHub

### ISSUE THREAD

**Issue by musienko-maxim** [theia-ide/theia#3987]
**Steps to reproduce:**
* Go to the Theia IDE. Press F1 and type command `git clone`.
* Select `Git: Clone...` and enter any GitHub url.

**Expected result:** After cloning the git features should be available for the just cloned repo
**Actual result:** The features are available after setting the project as root
**Env.:** Upstream Theia, run from  `examples/browser`, Chrome browser v. 71, OS.: Fedora 28

**Comment by vince-fugnitto** [comment]
@musienko-maxim I've tested on `latest` and did not notice an issue. I initially started with an empty workspace, performed <kbd>F1</kbd> then `Git: Clone...` and entered my given repo. I was able to see the git-widget updated with my new repo and features available. Can you perhaps elaborate on the issue?

**Comment by musienko-maxim** [comment]
On latest version all work. Thank you for your feedback.
