### ISSUE TITLE
[Git] Git view shows data from another frontend workspace

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3988]
Seems the data in the Git view is not workspace dependent.  I have two workspace open in separate tab and when I look at the changes in the GIT view from one workspace or the other, I see all changes from both workspaces.  One workspace, I have Theia and in the second workspace, I have "org.eclipse.egerrit", but in the GIT view, from any of two workspaces, I see the modified files from "org.eclipse.egerrit".

Note: running one backend with two frontends workspace on separate tabs.

![gitdataoverlapsworkspace](https://user-images.githubusercontent.com/419051/50906325-d8b0f580-13f2-11e9-9962-05f3937b893c.gif)

**Comment by akosyakov** [comment]
@elaihau @lmcbout Could you try to reproduce it on master? And if it's reproducible, reopen it and assign @vinokurig 

The code was completely rewritten.

**Comment by elaihau** [comment]
@akosyakov i tried having 2 theia browser instances and 1 backend, it worked properly. did you see this issue happen recently?

**Comment by akosyakov** [comment]
@elaihau thanks for checking, no i have not seen just checking that we did not break it with SCM extension
