### ISSUE TITLE
[settings] annoying notifications on typing

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3990]
It is fine to have a broken file on typing, we don't need to notify a user about it on each saving:
<img width="2032" alt="screen shot 2019-01-09 at 15 58 09" src="https://user-images.githubusercontent.com/3082655/50907344-6a3a5a80-1427-11e9-81cd-3eb6c62fbcbf.png">

**Comment by akosyakov** [comment]
@elaihau could someone have a look at it from Ericsson team?

**Comment by elaihau** [comment]
@akosyakov I talked with Marc and Vincent. 

I will revert what i did, and start another PR where we could discuss and find the best (hopefully) solution.

**Comment by elaihau** [comment]
PR https://github.com/theia-ide/theia/pull/4006

**Comment by elaihau** [comment]
https://github.com/theia-ide/theia/pull/4006 merged
