### ISSUE TITLE
[debug] Debug on Windows opens source files in new tabs

### ISSUE THREAD

**Issue by arekzaluski** [theia-ide/theia#4026]
## Description

Debugging in Windows opens new tabs for already opened files and sets a full path. Original breakpoints are ignored.

## Steps to reproduce:
Platform: Windows
Version: Electron

1. Run Theia (tested on current master - https://github.com/theia-ide/theia/commit/98edc40630b09171ecd76097b69fd08e3777340d)
2. Create simple node example
3. Set few breakpoints
4. Run node debugger

Current behaviour:

5. New tab is opened in editor with full uri to the file. Breakpoints in original file are ignored.

Expected behaviour:

5. Theia should not open another tab for the same file. Breakpoints in original tab should be respected.

## Notes
- Issue exists only on Windows. Debug works correctly on Mac OSX.
- Issue is not new. I'm able to reproduce it also on older versions of Theia.
- Issue exists also for different adapters, not only for node.
- Quick investigation showed that issue may be connected with wrong URIs received from monaco
- Issue is not reproducible in vscode

## Gif example
![theia-debug-windows](https://user-images.githubusercontent.com/13417215/51030857-8d602980-154f-11e9-9078-3edd083db605.gif)
 
@akosyakov @thegecko @tolusha

**Comment by akosyakov** [comment]
@arekzaluski thanks for reporting, could you investigate?

**Comment by arekzaluski** [comment]
@akosyakov No problem. I think that someone with better understanding of debugger and paths it Theia will be needed. I spent few last days on it any couldn't fix all corner cases with setting breakpoints correctly. I believe that main source of issue is connected with extra slash `/` in Windows paths and incorrect URI returned by model: `https://github.com/ARMmbed/theia/blob/master/packages/debug/src/browser/editor/debug-editor-model.ts#L82`

**Comment by thegecko** [comment]
Looking at the debug traffic, when it works on Mac the paths passed to/from the debug adapter take the same form;

`/Users/robmor01/theia-workspace/test.js` in

```json
{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"test.js","path":"/Users/robmor01/theia-workspace/test.js"},"sourceModified":false,"breakpoints":[{"line":2,"column":1}]}}
```
```json
{"seq":67,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"test.js","path":"/Users/robmor01/theia-workspace/test.js","origin":"read-only core module"}}}
```
```json
{"seq":80,"type":"response","request_seq":7,"command":"stackTrace","success":true,"body":{"stackFrames":[{"id":1000,"name":"(anonymous function)","source":{"name":"test.js","path":"/Users/robmor01/theia-workspace/test.js"},"line":1,"column":11}],"totalFrames":9}}
```

However on windows, they differ;
`/c:/Users/Rob/Projects/theia-workspace/test.js` and `c:\\Users\\Rob\\Projects\\theia-workspace\\test.js`
```json
root INFO {"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"test.js","path":"/c:/Users/Rob/Projects/theia-workspace/test.js"},"sourceModified":false,"breakpoints":[{"line":2,"column":1}]}}
```
```json
{"seq":66,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"test.js","path":"c:\\Users\\Rob\\Projects\\theia-workspace\\test.js","origin":"read-only content from Node.js"}}}
```
```json
{"seq":78,"type":"response","request_seq":7,"command":"stackTrace","success":true,"body":{"stackFrames":[{"id":1000,"name":"(anonymous function)","source":{"name":"test.js","path":"c:\\Users\\Rob\\Projects\\theia-workspace\\test.js"},"line":1,"column":11}],"totalFrames":9}}
```

**Comment by akosyakov** [comment]
We probably should use `FileUri.fsPath` to create a source path, otherwise they are in normalized form, not platform specific. It is not allowed to use `FileUri.fsPath` on the frontend, since frontend OS can be different from the backend. But one can use `FileSystem` API to convert URI to FS path: https://github.com/theia-ide/theia/blob/4572886d362f65c2e1857b37945a325d3bf09d8f/packages/filesystem/src/common/filesystem.ts#L140

I don't have time to look into myself, so PRs are welcomed.

**Comment by thegecko** [comment]
Now tested on Mac using Electron.

On reflection I'm considering just exposing the raw `fsPath` on the `URI` class to completely avoid having to call the backend filesystem. It would make this change so much simpler and remove the need to call the backend every time a path is calculated. The only drawback is we wouldn't use the central `getFSPath()` method, however this only includes extra functionality for Windows which isn't relevant for debug at the moment IMO.

**Comment by akosyakov** [comment]
> On reflection I'm considering just exposing the raw fsPath on the URI class to completely avoid having to call the backend filesystem.

It will be bogus. Your backend is Linux, but frontend is Windows, so you will send windows URIs to Linux backend. `URI` on purpose does not have APs for working for files, the backend is source of the truth and files URIs should be provided by it via `FileUri`.

**Comment by thegecko** [comment]
Thanks @akosyakov 
Could you help me understand how calling the [getFsPath() function](https://github.com/theia-ide/theia/blob/master/packages/filesystem/src/node/node-filesystem.ts#L385) on the backend is any different from simply pulling out the `fsPath` from a URI object in the frontend? That is all the function does:

https://github.com/theia-ide/theia/blob/master/packages/core/src/node/file-uri.ts#L50

**Comment by thegecko** [comment]
Nevermind, I can see `vscode-uri` itself is [OS aware](https://github.com/Microsoft/vscode-uri/blob/master/src/index.ts#L972)!

**Comment by akosyakov** [comment]
but it is the same problem with vscode-uri, it checks against your browser os version, not backend

**Comment by thegecko** [comment]
Only when run in the frontend.
[This code](https://github.com/Microsoft/vscode-uri/blob/master/src/index.ts#L15) looks to me like it will do the right thing when run in the backend.
