### ISSUE TITLE
[terminal] corruption in restored terminal's content

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#4029]
I thought there might already be an old issue about this but could not find it.

To reproduce:

1) In a Theia terminal, start vi and then exit the editor. 
2) reload Theia browser tab
3) Terminal is restored with old content, but also with some garbage (control characters?) underneath: 

![peek 2019-01-11 08-09](https://user-images.githubusercontent.com/25749063/51035540-4dfa0300-1578-11e9-987c-5e5d233ad70c.gif)

**Comment by vince-fugnitto** [comment]
Closed by #5364
