### ISSUE TITLE
[java-debug] Random error in CI (ENOENT)

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#4035]
Error: https://travis-ci.org/theia-ide/theia/jobs/478518512#L6279
> Error: ENOENT: no such file or directory, open '/home/travis/build/theia-ide/theia/packages/java-debug/download/java-debug/extension/package.json'

Cause? https://github.com/theia-ide/theia/blob/master/packages/debug/src/node/vscode/vscode-debug-adapter-contribution.ts#L101

**Comment by thegecko** [comment]
I've seen this error when the debug adapter hasn't successfully downloaded.
If the adapter is hosted on GitHub, it can fall victim to their rate limit throttling applied for too many anonymous downloads.

However in this case, it's possible the URL wasn't available from travis for some reason?

**Comment by tolusha** [comment]
I've faced this issue couple of times. 
I will try to figure out the reason.

**Comment by akosyakov** [comment]
I would like to package vsix files together with Theia extensions, that on postinstall nothing is downloaded only unarchived. It would be optional in the case if an archive is missing it would download as now.

@tolusha Are you looking into it? Can I?
