### ISSUE TITLE
[electron] Can't do New File or New Folder

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#404]
In the electron example New file and New folder from the main menu are grayed out.

However I can right click in the directory and do New file/folder.
In the browser example is is fine too.

**Comment by rcjsuen** [comment]
I see this in the browser example when running in Docker. It goes away after I click the 'Files' side pane because then a folder gets selected and the menu items have presumably responded to that selection.

**Comment by hexa00** [comment]
Yes, that's true.

However in electron even clicking the folder doesn't help.

**Comment by rcjsuen** [comment]
> In the browser example is is fine too.

Oh, I thought you meant it was fine in the browser example. I guess I misunderstood something here.

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/pull/437
