### ISSUE TITLE
[plug-in] Ability to get current selection in the explorer view

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#4043]
The use case where I want to use it for Task plugin is resolving the variables for Che tasks.
For example, we have command `mvn clean install -f ${current.project.path}` and we need to resolve it before running. So we need to replace `current.project.path` to execute the task for current project.

**Comment by tsmaeder** [comment]
@RomanNikitenko is this about implementing some vscode API call?

**Comment by RomanNikitenko** [comment]
@tsmaeder I'm sorry - I missed your message.
As far as I know vscode doesn't contain corresponding API.
So we need to find some way to get current selection in the explorer view on plugin side.

**Comment by vzhukovskii** [comment]
As I understand, we need macros mechanism in general and macro for current project path is particular type of macro as an example.

**Comment by RomanNikitenko** [comment]
@vzhukovskii we have ability to [register variable](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts#L51) from plugin side. But I don't know the way how to get current selection in the explorer view on plugin side. We could resolve the variables for Che tasks replacing `current.project.path` by path of current selection

**Comment by vzhukovskii** [comment]
For resolving actual variable `${current.project.path}` we need to implement interface [variable.ts#L24](https://github.com/theia-ide/theia/blob/master/packages/variable-resolver/src/browser/variable.ts#L24) on the plugin side and add additional method to obtain current selected paths (in [theia.d.ts](https://github.com/theia-ide/theia/blob/master/packages/plugin/src/theia.d.ts)) which can be retrieved from [selection-service.ts#L27](https://github.com/theia-ide/theia/blob/master/packages/core/src/common/selection-service.ts#L27)

**Comment by RomanNikitenko** [comment]
@vzhukovskii we have not problem with [registering variable](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts#L51), so we don't need to implement interface [variable.ts#L24](https://github.com/theia-ide/theia/blob/master/packages/variable-resolver/src/browser/variable.ts#L24), we can just [register variable].
The problem is - we can not obtain current selected path on plugin side
