### ISSUE TITLE
[keybinding] keybinding with 'alt' modifier broken when shadowed

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4060]
Keybindings with <kbd>alt</kbd> modifier are broken in the following cases:

| Command 1 | Command 2 | Keybinding 1 | Keybinding 2 |
|:---|:---|:---|:---|
|Find | Replace | <kbd>ctrlcmd</kbd>+<kbd>f</kbd> |<kbd>ctrlcmd</kbd>+<kbd>alt</kbd>+<kbd>f</kbd>|
|Open Preferences | Open Keyboard Shortcuts | <kbd>ctrlcmd</kbd>+<kbd>,</kbd> |<kbd>ctrlcmd</kbd>+<kbd>alt</kbd>+<kbd>,</kbd> |

**Comment by akosyakov** [comment]
Could you identify what broke it?

**Comment by vince-fugnitto** [comment]
closed thanks to #4072
