### ISSUE TITLE
In Firefox' Ubuntu 18 version,  The loading isn't finished.

### ISSUE THREAD

**Issue by minsoo5403** [theia-ide/theia#4067]
Loading doesn't end when I build theia and start it.

https://www.theia-ide.org/doc/composing_applications

Please Help I'm Newbie.

**Comment by akosyakov** [comment]
@minsoo5403 Hi, thanks for raising the issue. Could you provide logs from the firefox console and cli?

**Comment by minsoo5403** [comment]
Firefox console Message is like this and cli is no reaction

Failed to start the frontend application.
      e.exports< index.js:66

Error: "Could not unbind serviceIdentifier: e"
     unbind   http://localhost:3000/bundle.js:52.13636
     rebind    http://localhost:3000/bundle.js:52.13523
     n            http://localhost:3000/bundle.js:52.15698
     default   http://localhost:3000/bundle.js:52.1399974
     load       http://localhost:3000/bundle.js:52.12552
     d            http://localhost:3000/bundle.js:52.905602

**Comment by akosyakov** [comment]
Could you build in dev mode, that is `yarn theia build --mode development`,  try again and post new output here?

**Comment by minsoo5403** [comment]
Here is output When i start theia

Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 3495]
Error: No matching bindings found for serviceIdentifier: ProcessManager
    at _validateActiveBindingCount (/home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:91:26)
    at /home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
    at /home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:94:20)
    at Object.plan (/home/minsoo/my-app/node_modules/inversify/lib/planning/planner.js:136:9)
    at /home/minsoo/my-app/node_modules/inversify/lib/container/container.js:317:37
Server worker is ready to accept messages. [ID: 1 | PID: 3495]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"

**Comment by akosyakov** [comment]
@minsoo5403 Can you run `yarn why @theia/process` and post output, it seems that `@theia/process` either is not installed or installed multiple times

**Comment by minsoo5403** [comment]
Result like this  ... 

yarn why @theia/process
yarn why v1.13.0
[1/4] Why do we have the module "@theia/process"...?
[2/4] Initialising dependency graph...
warning Lockfile has incorrect entry for "@theia/callhierarchy@0.4.0-next.29795f26". Ignoring it.
Couldn't find any versions for "@theia/callhierarchy" that matches "0.4.0-next.29795f26"
? Please choose a version of "@theia/callhierarchy" from this list:
  0.4.0-next.ffbb7dcf 
  0.4.0-next.ff386514 
  0.4.0-next.fee81ec4 
  0.4.0-next.fed4e73b 
  0.4.0-next.fec64c30 
  0.4.0-next.fde3bdd3 
  0.4.0-next.fdbb533a 
  0.4.0-next.fd9dfcaa 
  0.4.0-next.fce07f87 
  0.4.0-next.fccb6114 
  0.4.0-next.fc7080f2 
  0.4.0-next.fc6e8217 
  0.4.0-next.fb435527 
  0.4.0-next.fb39727e 
  0.4.0-next.fb14b1a2 
  0.4.0-next.f9db5dde 
❯ 0.4.0-next.f9ae69d1 
  0.4.0-next.f98eb08f 
  0.4.0-next.f93d2811 
  0.4.0-next.f9048f12 
  0.4.0-next.f8e66b12 
  0.4.0-next.f8a21d90 
  0.4.0-next.f846d8bd 
  0.4.0-next.f81fe013 
  0.4.0-next.f7649017 
  0.4.0-next.f74f495b 
  0.4.0-next.f73263b9 
  0.4.0-next.f6ee123d 
  0.4.0-next.f6e320d8 
  0.4.0-next.f69caeba 
  0.4.0-next.f59f590b 
  0.4.0-next.f517558f 
  0.4.0-next.f5021b96 
(Move up and down to reveal more choices)


then, choice any version

[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@theia/process@0.4.0-next.5da05ede"
info Has been hoisted to "@theia/process"
info Reasons this module exists
   - Hoisted from "@theia#file-search#@theia#process"
   - Hoisted from "@theia#search-in-workspace#@theia#process"
   - Hoisted from "@theia#callhierarchy#@theia#languages#@theia#process"
   - Hoisted from "@theia#file-search#@theia#editor#@theia#languages#@theia#process"
   - Hoisted from "@theia#search-in-workspace#@theia#editor#@theia#languages#@theia#process"
info Disk size without dependencies: "7.24MB"
info Disk size with unique dependencies: "15.92MB"
info Disk size with transitive dependencies: "183.15MB"
info Number of shared dependencies: 163
=> Found "@theia/languages#@theia/process@0.4.0-next.29795f26"
info This module exists because "@theia#languages" depends on it.
info Disk size without dependencies: "416KB"
info Disk size with unique dependencies: "9.09MB"
info Disk size with transitive dependencies: "176.32MB"
info Number of shared dependencies: 163
=> Found "@theia/terminal#@theia/process@0.4.0-next.29795f26"
info This module exists because "@theia#terminal" depends on it.
info Disk size without dependencies: "416KB"
info Disk size with unique dependencies: "9.09MB"
info Disk size with transitive dependencies: "176.32MB"
info Number of shared dependencies: 163
=> Found "@theia/typescript#@theia/process@0.4.0-next.fed4e73b"
info Reasons this module exists
   - "@theia#typescript#@theia#callhierarchy#@theia#languages" depends on it
   - Hoisted from "@theia#typescript#@theia#callhierarchy#@theia#languages#@theia#process"
info Disk size without dependencies: "6.32MB"
info Disk size with unique dependencies: "15MB"
info Disk size with transitive dependencies: "182.23MB"
info Number of shared dependencies: 163
Done in 33.73s.

**Comment by akosyakov** [comment]
> warning Lockfile has incorrect entry for "@theia/callhierarchy@0.4.0-next.29795f26". Ignoring it.
Couldn't find any versions for "@theia/callhierarchy" that matches "0.4.0-next.29795f26"
? Please choose a version of "@theia/callhierarchy" from this list:

It does not look good. Our yarn sometimes fails to publish all next packages properly: https://github.com/theia-ide/theia/issues/3964#issuecomment-452276246 It seems to be that `@theia/callhierarchy` was not published for `5da05ede` commit.

Could you try to delete `yarn.lock`, `node_modules` and run `yarn` again to install latest next versions? Hopefully everything was published by the latest commit on master.

**Comment by minsoo5403** [comment]
it doesn't work .. delete and reinstall

yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
warning @theia/typescript > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/typescript > @theia/filesystem > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
warning @theia/messages > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning @theia/cli > @theia/application-manager > less > request > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.6: The platform "linux" is incompatible with this module.
info "fsevents@1.2.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@theia/cli > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 138.91s.

**Comment by marcdumais-work** [comment]
@minsoo5403 the log you provided does not reflect that there is a problem. I just tried building and running the "composing_application" example app, and it worked as expected. It pulled the following "next": `0.4.0-next.49db4e46`. Can you clean-up and give it another try?

**Comment by akosyakov** [comment]
You can also use `latest` instead of `next`, to try out the last release.

**Comment by akosyakov** [comment]
Please follow this issue https://github.com/theia-ide/theia/issues/4083 instead. Closing as a dup.
