### ISSUE TITLE
discussion: [keybinding] Properly manage keybindings and layouts

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#4079]
Following a bunch of issues regarding keybindings, and trying to understand what VS Code does, it is clear that this is not an easy topic.

## What Theia does

From what I understand, at the implementation level, we check properties in the following order:
1. [`KeyboardEvent.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) (number) *(deprecated)*
2. [`KeyboardEvent.keyIdentifier`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyIdentifier) (string) *(deprecated)*
3. [`KeyboardEvent.which`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) (number) *(deprecated)*
4. and finally [`KeyboardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) (string) which is the sole non-deprecated property that we check, but we only do it as last resort :thinking:.

From that lookup, we check against a big map of `KEY_CODE_TO_KEY` (number to Key) and `CODE_TO_KEY` (string to Key) in order to get our own `Key` abstraction, defining the right `code` and `keyCode` for said key (see this as a the bridge between some `event.code` and its `US` representation as a `event.keyCode`).

## Proposal

Wouldn't be too bad, except that maybe we should forget about `keyCode`, and instead start using [`KeyboardEvent.key`](https://developer.mozilla.org/fr/docs/Web/API/KeyboardEvent/key).

We can see how this works by playing on the following website:
https://w3c.github.io/uievents/tools/key-event-viewer.html

From my tests, doing the following key presses:

![keyboard-us-de](https://user-images.githubusercontent.com/14182238/51216300-ec2bf700-18f1-11e9-85f2-a664a92a7ea4.png)

- (#&#x2060;1 to #&#x2060;5) `ctrl+/` (US)
- (#&#x2060;6 to #&#x2060;10) `ctrl+-` (DE) physical equivalent of `ctrl+/` (US)
- (#&#x2060;11 to #&#x2060;17) `ctrl+shift+7` (DE) same localized representation as `ctrl+/` (US)
  (on a german keyboard, one must do `shift+7` to output a `/`)

What we can see is that the `event.key` field always match the originally defined binding, when trying to get a localized `ctrl+/`.

## `code` and `key` against `keyCode`

`code` has the advantage of being *locale independent*, while `key` is *locale dependent*.

The inconvenient of having a `key` that is local dependent is that we can precompute a `CODE_TO_KEY`, but *cannot* do it for a `LOCALIZED_KEY_TO_KEY` map because the localized `key` field will vary from one layout to the other.

Other difference between `KeyboardEvent.key` and `KeyboardEvent.keyCode` is that the value of `key` will be affected by the modifiers:

- press `7` (US): `event.key === '7'`
- press `shift+7` (US): `event.key === '&'`

Using a German keyboard:

- press `7` (DE): `event.key === '7'`
- press `shift+7` (DE): `event.key === '/'`

This means that it makes us dependent on the way we refer to keys: Do we want to say that you need to type on a key where `7` is drawn (somehow) and hold `shift`, no matter what `shift+7` resolves to???
(`/` on a German layout or `&` on an US layout)

In our case, **we don't actually refer to keys this way**: when we define `ctrl+/` on a US layout to comment a line in the editor, the representational keybinding **stays the same** on the German keyboard, it is just that if we were to represent the physical keys that would be involved back on a US keyboard, it would **look like** we did `ctrl+shift+7` (when actually it would be `ctrl+&` once we simplify the binding).

All in all, if we kept looking at `event.key`, we wouldn't have had any problem between US and DE.

## Keyboard layouts

This brings us to the management of keyboard layouts: there is currently no API in browsers to query some user's keyboard layout.

So what I propose is to have the user explicitly choose its keyboard layout from Theia's UI, with a dropdown or anything, and have keyboard layouts contributed somehow (via `ContributionProvider`s and/or plugins). This means that these contributions will need to be explicitly written down somehow.

We can store the chosen layout in the browser's local storage in some global field, and ask the user for it on the very first launch of Theia if it is undefined (because first run). Or we can default to US, but still display a notification to guide the user on how to change it.

This might allow us then to display the correct information when displaying bindings, based on what layout was chosen.

## Contributing/Writing keyboard layouts

Contributing layouts and creating them would be like creating TextMate themes (but simplier). Just do it once, and everyone is happy. Even if it doesn't map 100% to the real deal, 75% would be better than nothing at all.

**[Our current implementation](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/keys.ts#L555-L883) already defines something similar to a US layout map**. Although a bit sketchy in my opinion. It did the work until now, but maybe since we are having problems today it would be a good idea to clean that up?

From the top of my head, a keyboard layout map would look like the following, taking into account `event.code` and `event.key`:

```ts
const US_LOCALIZED_KEY_TO_PHYSICAL_KEYS_RAW = {
    'a': { code: 'KeyA' },
    'A': { code: 'KeyA', shift: true },
    '/': { code: 'Slash' },
    '?' { code: 'Slash', shift: true },
    ...
};
```

From there we could use this data structure to compute forward and reverse maps for any lookup.

To be fair, having to map each localized character to the corresponding physical key + modifiers pains me, but that's the only way to be able to correctly encode and decode from one layout to the other.

Also again: we are already partially doing this.

(_Worst case scenario_ we only do it for the US keyboard, to hell the rest?)

The design could be improved, this is just an idea that I throw out there.

# More testing

Maybe there's even too much information, let's take a look at different keyboards, for the same keybinding: `ctrl+/` to toggle line comment.

- `ctrl+/` (US) base for comparison
- `ctrl+/` (DE) maps to `ctrl+&` (US) or `ctrl+shift+7` (US)
- `ctrl+/` (FR) maps to `ctrl+>` (US) or `ctrl+shift+.` (US)

**Please note that these are exactly the keys I need to press on my US keyboard when I use the foreign layouts on VS Code. Remember that you need to close and reopen the whole VS Code window between layout switches for it to have an effect.**

We actually might not care what the localized keybinding maps to on an US keyboard. The issue might be that we currently do the translation, when we shouldn't even do it (maybe).

So what do we get from mapping localized bindings to their complete physical sequence? If we were to map some bindings to physical keys (instead of localized keys) then it would matter, in order to actually display the right information on screen when changing layout (if the feature gets added).

On the other hand, it would also allow us to understand alternative notations, such as `ctrl+&` could be written `ctrl+shift+7`. Not sure if it is something we want to support, but it is out there.

Example:

- `shift+alt(right)+4` (US) that maps to `£` (US, International with dead keys - IWDK).

In this case, the lookup of the `event.key = £` would fail when using US (IWDK), because we only have the standard US layout defined (default). But on failure, we could still try a lookup based on the physical keys, in that case `{ code: 'Digit4', shift: true, altRight: true }`.

![image](https://user-images.githubusercontent.com/14182238/51223821-6b7cf300-1911-11e9-9033-059fbaac2543.png)

- (#&#x2060;1 to #&#x2060;14) US layout
- (#&#x2060;15 to #&#x2060;29) US (IWDK) layout

This case is super weird, because it seems that we should use the function `getModifierState(code)` in order to have a better range on the available modifiers, as on my keyboard I do have something called `AltGraph` which is mapped to the physical `AltRight` key. And there seems to be a difference between `AltLeft` and `AltRight`, but not on US standard.

I wouldn't know what to do in that case, but this is why I write it down, maybe you have a better idea :)

We should definitely take a look at https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values for the available values for `event.code` and `event.getModifierState(code)`.

## What VS Code does

VS Code -by running on the same host the frontend/backend- have access to node APIs, and they use their own [`native-keymap`](https://www.npmjs.com/package/native-keymap) native npm module.

Although their internals are filled with different big data maps/enums ([1](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/keyCodes.ts#L8-L199), [2](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/keyCodes.ts#L229-L359), [3](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/keyCodes.ts#L8-L199), [4](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/keyCodes.ts#L229-L359), [5](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/scanCode.ts#L11-L208), [6](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/scanCode.ts#L268-L467)) and their relations are not quite easy to follow... I wouldn't know if we should go through the pain of inspiring ourselves from their implementation, seeing how intricate it is.

Something that I noticed with their design though, is that in VS Code the layout seems to be fetched on window opening, and even if you change the layout at runtime it will not dynamically update.

It is even worse than that, because even if you change the layout while running, the keybindings stay bound to the old physical layout that was set (doing `ctrl+/` (US) after starting with a DE layout still trigger the `decrease zoom` as if we pressed `ctrl+-` (DE) which involves the same physical keys... this looks like a bug to me).

## Foot notes

This doesn't account for cross OS layout, as I don't know if there is a difference between a Linux US layout and a Mac US layout...

I wrote this document in order to share what I think I could understand about this keybinding issues, the current system drove me crazy, and I don't think it has to be this complex. I also believe it came at this point because people kept trying to "fix" it without having the big picture.

I do not claim to have understood it all, if anything this *must* be seen as a resource for anyone wanting to fix the keybindings in Theia. Please add comments and any insight you could have on the matter. I really rely on you all there to review this and eventually come with better fixes, as I won't be able to focus on this task more than just thinking about it at high level like I just did, sorry :(

I think keybindings are important as I use them around 8 hours a day 7/7. So I would expect Theia to be good in that area, yet it is not really the case.

## Interesting references:

- Documentation about `KeyboardEvent.code`: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
- Keyboard event tester: https://w3c.github.io/uievents/tools/key-event-viewer.html
- List of deprecated and valid properties for `KeyboardEvent`: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

**Comment by marechal-p** [comment]
Please just throw anything you have on your mind regarding this issue, that's just my point of view, and I hope we will get around the issues we are having with keybindings.

I want to state again that I have other priorities at the moment, hence why I simply wrote down thoughts and didn't take act on this. Hopefully this thread will help someone.

**Comment by akosyakov** [comment]
// cc @svenefftinge @spoenemann 

@marechal-p I don't think `KeyboardEvent.code` is the official API already and supported by all browsers. I don't think we can rely on it.

**Comment by spoenemann** [comment]
> Wouldn't be too bad, except that maybe we should forget about keyCode, and instead start using KeyboardEvent.key.

That doesn't work because the `alt` modifier also has an influence on what the `key` property will give you. Therefore it would not be possible to realize a keybinding such as `alt + /` using that property, since the reported property value would be very different depending on the keyboard layout.

**Comment by spoenemann** [comment]
Currently I see only two approaches that would work reliably:

 1. Query the keyboard layout on startup as proposed by @marechal-p.
 2. Deviate from the VS Code keybinding style and define keybindings based on physical key locations instead of character values.

**Comment by svenefftinge** [comment]
> Deviate from the VS Code keybinding style and define keybindings based on physical key locations instead of character values.

I think from a UX point of view this is not acceptable.

**Comment by svenefftinge** [comment]
> Query the keyboard layout on startup as proposed by @marechal-p.

Querying on startup would be a huge friction in the UX.

**Comment by svenefftinge** [comment]
See also https://github.com/theia-ide/theia/pull/3833

**Comment by marechal-p** [comment]
> I don't think `KeyboardEvent.code` is the official API already and supported by all browsers. I don't think we can rely on it.

Looking at MDN and the W3C spec, `KeyboardEvent.code` is the official API (that should be implemented by other browsers that would lag behind today).

From https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode:

> You should avoid using this if possible; it's been deprecated for some time. Instead, you should use `KeyboardEvent.code`, if it's implemented.

Most major browsers do implement it (Chrome, Firefox, Safari, Opera, iOS Safari).
https://caniuse.com/#feat=keyboardevent-code

It has even been supported for a bit longer than the `wasm` support on these browsers:
https://caniuse.com/#feat=wasm

I think part of the trouble with this spec is that there wasn't a widespread of applications relying that deeply on keybindings, hence most other browsers not making that a priority for them yet, I guess.

**Comment by marechal-p** [comment]
> That doesn't work because the alt modifier also has an influence on what the key property will give you. Therefore it would not be possible to realize a keybinding such as alt + / using that property, since the reported property value would be very different depending on the keyboard layout.

This is true if you press the `alt-right` physical key, applying the `AltGraph` modifier.

On my keyboard layout (US, International with dead keys), the `Slash` physical key hosts the following characters:

```
? ̉
/ ¿
```

From what you said, you would expect `alt+/` to not be possible, yet:

![image](https://user-images.githubusercontent.com/14182238/51256062-8469c080-1972-11e9-9829-c69ad68517f5.png)

_Note that the `alt` modifier is correctly marked._

By pressing the `AltLeft` and `Slash` physical keys, the keybinding works. It is only if I press the `AltRight` key that the modification would happen.

On a French keyboard, the right `alt` key even has `AltGr` printed onto the keyboard. Until today I never understood why my `AltLeft` would be labeled `alt` while the one on the right was labeled `AltGr`, turns out it is to accomodate for this `AltGraph` modifier.

Using `AltRight`:

![image](https://user-images.githubusercontent.com/14182238/51256258-fd691800-1972-11e9-8845-2930d665172c.png)

So far I don't see a problem using `KeyboardEvent.key`.

**Comment by marechal-p** [comment]
@svenefftinge 

> Querying on startup would be a huge friction in the UX.

Indeed, but to have some dropdown available, or something that the user can quickly access would do the trick too.

Using a layout as stated in my proposal wouldn't change keybindings, in fact we might not need to handle layouts at all, and just keep the representational keybindings: as long as you can print a `/` on your keyboard, then doing `ctrl+/` will work whatever you do.

For users with keyboards that don't have this symbol at all will need to rebind it, for sure.

But even thinking about a corner case, say a Japanese keyboard: if they program in about any regular language, they would still need to use roman letters, as JS, TS, C#, C, C++, Python, etc... are all written in English. So I would expect them to be able to use some kind of US layout or something similar. In short, even on exotic keyboards, they might have access to regular keys used in an IDE by default.

Would love some insight from someone with such a different layout from the US one.

**Comment by marechal-p** [comment]
@svenefftinge 

> I think this is the key culprit, there is no reliable way of getting the actual character in that case.

I am sorry, I didn't understand what you were trying to do.

**Comment by svenefftinge** [comment]
When I press CMD+Shift+7 (on my german mac layout) I should see `/`as `key` but I get `7`.

**Comment by svenefftinge** [comment]
> Indeed, but to have some dropdown available, or something that the user can quickly access would do the trick too.

That is what I consider too much friction

**Comment by spoenemann** [comment]
We should change [the web standard](https://w3c.github.io/uievents/#interface-keyboardevent) for KeyboardEvent to make it more useful for IDEs...

**Comment by marechal-p** [comment]
@svenefftinge 

> When I press CMD+Shift+7 (on my german mac layout) I should see `/`as `key` but I get `7`.

Can you ask on [this tracker](https://github.com/w3c/uievents/issues/) about your issue with the German layout on Mac, see if it is part of the specification or a bug from the browser you are using?

@spoenemann 

> We should change [the web standard](https://w3c.github.io/uievents/#interface-keyboardevent) for KeyboardEvent to make it more useful for IDEs...

What would you like to see changed, and how?

**Comment by svenefftinge** [comment]
It is well known. I couldn't find a reference, though.

**Comment by svenefftinge** [comment]
related https://github.com/Microsoft/vscode/issues/713

**Comment by marechal-p** [comment]
> It is well known. I couldn't find a reference, though.

I tried some key combinations on my Ubuntu laptop, using a German layout, and couldn't get the same issue as you (might be missing the Mac `cmd` key).

![image](https://user-images.githubusercontent.com/14182238/51265351-9c4b3f80-1986-11e9-8b31-b9d219bcc445.png)

So I really wonder if this isn't some kind of corner case for Mac and their keys: When you do such a combination in the input box, does it outputs anything? Again, I'll have to try that tomorrow under different context, as I find it weird that it would misbehave in that case for no apparent reason.

**Comment by marechal-p** [comment]
This means that `macCmd+/` cannot be detected using the recommended `KeyboardEvent` API, which sounds like a bug to me, unless this is an intended behavior under some rules.

**Comment by svenefftinge** [comment]
Yes, it is a corner case for macs.

This is also worth reading https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/

**Comment by svenefftinge** [comment]
For detecting layouts https://github.com/ahtcx/layoutline

**Comment by svenefftinge** [comment]
https://github.com/w3c/uievents/issues/156

**Comment by svenefftinge** [comment]
This https://wicg.github.io/keyboard-map/

**Comment by marechal-p** [comment]
From https://wicg.github.io/keyboard-map/:

> Because most users have a physical keyboard that matches their locale and layout, we can reasonably assume that the key value is a good stand-in for the glyph printed on the keycap. While this does not hold true when the user has selected a different layout, in that case the user is well-aware of the mismatch between the glyph on the keycap and the character generated by a key press.

In our case, we might actually not be affected by keyboard layout: if the keybinding is `ctrl+/`, then the user must find a way to output the character `/` while pressing `ctrl` on its layout.

This is the behavior on VS Code, and the one we would like too.

- `ctrl+/` (FR) uses `[CtrlLeft]+[ShiftLeft]+[Period]` and looks like `ctrl+>` (US)
- `ctrl+/` (DE) uses `[CtrlLeft]+[ShiftLeft]+[Digit7]` and looks like `ctrl+shift+7` (US)
- `ctrl+/` (US) uses `[CtrlLeft]+[Slash]`

The physical keys involved each have nothing to do with each other, but a user would be pressing exactly the keys he expect to have to press. 

My issue currently is that when `KeyboardEvent.key` works correctly, we do not have to care about the localization of `ctrl+/`. User should find a way on their keyboard to output it, and for us it works out of the box. What do we display? `ctrl+/`.

I feel like the issue on Mac with `macCmd+shift+7` is a bug somehow, or just part of how this works, where `macCmd` just has some weird effect. I cannot wrap my head around the issues that this `key` field seems to solve, and this misalignment on Mac...

**Comment by marechal-p** [comment]
Just thought about something else @svenefftinge: Do we want to support `ctrl+/` on an US layout, and be something like `[CtrlLeft] + [ShiftLeft] + [Digit7]` on the german keyboard?

**Comment by marechal-p** [comment]
> When I press CMD+Shift+7 (on my german mac layout) I should see `/`as `key` but I get `7`.

Ok, so about this, it is a direct conflict with MacOS itself: https://superuser.com/questions/579209/non-us-keyboard-and-cmd-shift-7

I tried on a Mac and got the same behavior, except that some help menu popped out on my side.

Because we are running in the browser, I guess this is just part of some unlucky keybindings that will cause us troubles (just like we cannot use `ctrl+tab`).

And also it would seem that onlz on Mac, the German keyboard does indeed change the outputted character when pressing any `Alt` key :(

I am in pain, sorry to be that stubborn, I finally see the problems on Mac with that...

**Comment by marechal-p** [comment]
> Just thought about something else @svenefftinge: Do we want to support `ctrl+/` on an US layout, and be something like `[CtrlLeft] + [ShiftLeft] + [Digit7]` on the german keyboard?

I was asking this question because I can see a problem with the way we want to localize the keybindings:

If we want a keybinding on a US layout to be `ctrl+/`, then this will map to `[Control] + [Slash]`, modifiers: `Control`.

However, on a German keyboard, it will map to `[Control] + [Shift] + [Digit7]`, modifiers: `Control, Shift`.

So how do we then map something like `ctrl+shift+/` on a German keyboard? We are already using `shift` on that layout to do the regular `ctrl+/`.

Localizing seems to come with its own problems.

Meanwhile, the solution from @spoenemann to use physical keys seems to have advantages.

When we define keybindings, we often try to make them so it is physically easy to access, or rather ergonomic to use: video games for example, might use WASD (US) to move the avatar. But having played games with a french keyboard, WASD becomes ZQSD (because French keyboards have AZERTY layout, not QWERTY). Long story short, I know which physical keys they meant players to use, but localizing these bindings is useless, because it just breaks the ergonomic purpose of the original one.

wdyt?

**Comment by spoenemann** [comment]
@marechal-p we could handle such cases with a warning: #3836

**Comment by marechal-p** [comment]
@spoenemann how programmatically would we detect such a case, as of now?

**Comment by spoenemann** [comment]
I don't know yet. I'm planning to spend some work on the keybindings problems to sketch possible solutions, hopefully in the first half of February.

**Comment by spoenemann** [comment]
A very useful explanation on how keyboard handling has evolved in VS Code:

https://github.com/Microsoft/vscode/issues/17521

**Comment by spoenemann** [comment]
I submitted an issue to the keyboard-map API draft to discuss what we need in Theia:

https://github.com/WICG/keyboard-map/issues/26

We should work on a solution that we can use now, but it would be great if the web APIs could better support our scenario in the future, even if it takes years to get there.

**Comment by spoenemann** [comment]
I created a Google document to collect links and insights:

https://docs.google.com/document/d/1p17IBbYGsZivLIMhKZOaCJFAJFokbPfKrkB37fOPXSM/edit?usp=sharing

**Comment by spoenemann** [comment]
I'll work on a draft to handle this topic this week.
