### ISSUE TITLE
Add support for restructured text

### ISSUE THREAD

**Issue by almet** [theia-ide/theia#4082]
Hi, and thanks for the project. It's working pretty well for me so far. I'm missing support for [restructured text](https://en.wikipedia.org/wiki/ReStructuredText), which is quite common in python projects.

Not sure how this can be added, but that would be very welcome!

**Comment by marcdumais-work** [comment]
Hi @almet . Would having a preview rendering for `restructured text` be enough or at least a good step forward? Similar to what we have for `Markdown`, where you can have side-by-side the source editor and the "live" rendering of that source? 

If so we have an example how the `preview` extension can be extended (from a new, separate Theia extension) to provide an extra rendering: https://github.com/theia-ide/theia-plantuml-extension.

**Comment by svenefftinge** [comment]
We should check if https://github.com/vscode-restructuredtext/vscode-restructuredtext works.

**Comment by almet** [comment]
> Would having a preview rendering for `restructured text` be enough or at least a good step forward? 

Ah, I don't think so. That would answer another use case though. I personally almost never use these preview rendering because the simplicity of the markdown / restructuredtext languages does not make it a necessity to have a preview.

**Comment by akosyakov** [comment]
@svenefftinge I will mark such requests as `vscode` that we have a look at them after built-in VS Code extensions.

**Comment by akosyakov** [comment]
I've looked at source code at https://github.com/vscode-restructuredtext/vscode-restructuredtext and could not found any metadata or APIs which we don't cover already. @almet Could you give it a try? See https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

**Comment by almet** [comment]
That looks good to me!

**Comment by akosyakov** [comment]
@almet thanks for checking, closing it, please reopen if something wrong with the extenison
