### ISSUE TITLE
[plug-in]Delegate showReferences command to textEditor.commands.showReferences

### ISSUE THREAD

**Issue by svor** [theia-ide/theia#4084]
The command to show references is already registered by id `textEditor.commands.showReferences`. But plugins know nothing about `textEditor.commands.showReferences` id, they use `editor.action.showReferences` to show references.

To make it possible to execute `editor.action.showReferences` from the plugin and don't break existing clients we need to delegate `editor.action.showReferences` to existing `textEditor.commands.showReferences` command in plugin-ext-vscode.

**Comment by tsmaeder** [comment]
Actually, there seems to be a metric boatload of commands that are predefined in VS Code: https://code.visualstudio.com/api/references/commands

**Comment by benoitf** [comment]
linking to https://github.com/theia-ide/theia/issues/4050
