### ISSUE TITLE
Add a File menu entry to upload files

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia#4088]
When you want to upload a file into your Theia IDE, there is no visible option to do that.

Most people will first upload files to somewhere, and then `wget` or `curl` or `git pull` (!) desired files from the Terminal. This is terrible.

Adding a File menu entry that says `Upload file...` and opens a file picker would be awesome for UX.

**Comment by jankeromnes** [comment]
> you can drag and drop as a work around.

Thanks, that's true (dropping into the file tree, not the editor) but this feature is almost impossible to discover without someone telling you about it first.

A menu option would make that feature more discoverable.

**Comment by jankeromnes** [comment]
I see two potential places where this `Upload Files...` feature could be exposed:

1. In the `File` top-menu (right under `New File` and `New Folder`, maybe with an extra separator)
2. In the file tree context menu (right under `New File`, `New Folder` and `Open in Terminal`)

Notes:
- For 1. `MenuPath === CommonMenus.FILE_NEW === ['menubar', '1_file', '1_new']`
- For 2. `MenuPath === NavigatorContextMenu.NEW === ['navigator-context-menu', '4_new']`

**Comment by jankeromnes** [comment]
I'll go ahead and implement both (we can always change our minds during code review).

**Comment by jankeromnes** [comment]
Interesting find: The current file upload implementation uses `DataTransferItem.webkitGetAsEntry()`, which only works in [Firefox, Chrome and Edge](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry#Browser_compatibility). So you can't upload files in IE, Opera or Safari.

https://github.com/theia-ide/theia/blob/5156023a4b0c590b40485f82d5c798c6ef6f8dec/packages/filesystem/src/browser/file-tree/file-tree-model.ts#L191-L196

**Comment by akosyakov** [comment]
@jankeromnes If you know official stable API which cover all browsers, it would be good to rewrite it. I could not such find or figure out how to upload directories with that.

**Comment by akosyakov** [comment]
You should be aware that adding new dependencies is troublesome right now 😢 We need get CQs for them: https://github.com/theia-ide/theia/wiki/Registering-CQs I hope it would be resolved soon that we can develop fast again. //cc @marcdumais-work

**Comment by jgbradley1** [comment]
Was a decision ever made on what module should be used for this functionality? The PR seems almost complete if the licensing issue can be resolved.

**Comment by jankeromnes** [comment]
If there exist a way to transform a `input.files` (a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) from a `<input type="file" multiple>`), into a [DataTransferItemList](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList) to pass to `FileTreeModel.upload()`, then the pull request is almost finished in adding the menu entries.

However, just like the current drag-an-drop upload, it would still only work in [Firefox, Chrome and Edge](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry#Browser_compatibility), see https://github.com/theia-ide/theia/issues/4088#issuecomment-457505577.

The better solution would be to replace the existing `FileTreeModel.upload()` code with a library like https://github.com/felixge/node-formidable, because it would make file uploads work across all browsers, but importing a new library into Theia requires extra process.

**Comment by akosyakov** [comment]
`FileTreeModel.upload()` cannot handle big fils: https://github.com/theia-ide/theia/issues/969 It's a limitation of how we using web sockets. Need to fix it as well, but we can use `node-formidable` instead if it is better.

**Comment by jgbradley1** [comment]
Since this issue has been open for two months, using `FileTreeModel.upload()` seems like the path of least resistance in order for this feature to move forward.

Regarding the browser compatibility issue, a browser check could be performed in the code with a warning dialog box notifying the user if they're using an incompatible browser. 

In the file upload window, the 60 MB cap should be mentioned somewhere so users are aware. At least if they know about the issue, they can split files up outside of Theia as a workaround for now.

**Comment by jgbradley1** [comment]
If I understand the codebase correctly, it looks like the [backend server](https://github.com/theia-ide/theia/blob/8d151a6db3e74d573efff565f547a8581ed14eb0/packages/core/src/node/backend-application.ts) in an express server. If so, [express-formidable](https://www.npmjs.com/package/express-formidable) might be a better option to use.

**Comment by akosyakov** [comment]
They are limitations to implementation.

With stable APIs:
- only files can be uploaded
- only with simple name (not a relative path)

With webkit: one can also uploads directories, but exclusively, i.e one cannot select files then.

Would it be alright to have two commands `Upload Files...` (based on stable) and `Upload Folders...` (available only for webkit)?

cc @jankeromnes @jgbradley1

**Comment by jankeromnes** [comment]
> Would it be alright to have two commands `Upload Files...` (based on stable) and `Upload Folders...` (available only for webkit)?

That would work for me, thanks!

Or what about just implementing a `Upload Files...` menu entry and not `Upload Folders...`? The underlying feature is non-standard, I don't think I've ever needed it such a thing, and all the use cases I can think of can be worked around (e.g. selecting all files in a directory, or uploading an archive instead).

**Comment by jgbradley1** [comment]
In VS Code, there is a single `Open...` command that allows the user to select either a file or folder. Maybe that behavior should be imitated with the `Upload Files...` command. Allow a user to select files or folders, perform a check to determine what was chosen, which would determine which upload method is used (stable browser API vs webkit).

**Comment by jgbradley1** [comment]
Useing @jankeromnes changes, I have a very crude implementation [here](https://github.com/jgbradley1/theia) using formidable. You can try it it out with gitpod. It doesn't parse out the uploaded file correctly just yet.

I think the file upload option should use the native file picker dialog box. It feels more intuitive than trying to create and maintain a custom dialog box.

**Comment by akosyakov** [comment]
> Or what about just implementing the Upload Files... menu entry, and skipping Upload Folders... altogether? The underlying browser feature is non-standard, I don't think I've ever needed it such a thing, and all the use cases I can think of can be worked around easily (e.g. by selecting all files in a directory, or by uploading an archive).

I will start with that, but folder hierarchy won't be preserved, i.e. all files will be uploaded with simple names, if there are duplicates the last one wins. One can workaround it by drag & drop in the navigator.

> In VS Code, there is a single Open... command that allows the user to select either a file or folder. Maybe that behavior should be imitated with the Upload Files... command. Allow a user to select files or folders, perform a check to determine what was chosen, which would determine which upload method is used (stable browser API vs webkit).

As I explained, It is not feasible in browser context because standard limitations: there is not allow to select files OR folders. VS Code uses native Electron APIs for it.

**Comment by jgbradley1** [comment]
Okay @akosyakov I understand what you are saying now.

> Or what about just implementing the Upload Files... menu entry, and skipping Upload Folders... altogether? The underlying browser feature is non-standard, I don't think I've ever needed it such a thing, and all the use cases I can think of can be worked around easily (e.g. by selecting all files in a directory, or by uploading an archive).

I agree.

**Comment by jankeromnes** [comment]
🎉 🎉 🎉 Many thanks @akosyakov!

**Comment by davide-sergi** [comment]
From this discussion, I understood that is not possible to select programmatically (e.g. via command invocation) a file or folder, right? I ask because I'm trying to do so from my plugin
