### ISSUE TITLE
Much advanced and complete filetree widget

### ISSUE THREAD

**Issue by NeekSandhu** [theia-ide/theia#4094]
After carefully observing how filetrees are implemented in common apps, including VSCode (`monaco-tree`) and Theia, I'm happy to introduce a tree component that fills all the observed shortcomings and flaws in current implementaions, and adds bunch of extra improvements.

___

[`react-aspen`](https://github.com/NeekSandhu/react-aspen) is a standalone component with async-first API for rendering virtualized nested trees

<img src="https://i.imgur.com/94wkW8q.gif" width="300" />

As of yet, no other implementation outperforms `react-aspen` as far as performance numbers are concerned (from Chrome Profiling tools)

All the features are highlighted on `react-aspen` [repo page](https://github.com/NeekSandhu/react-aspen), but the secret sauce here is the fact that Aspen, unlike most implementations, does not use recursion to flatten the tree at once. Instead, it uses `Uint32Arrays` under the hood that are initialized empty and updated using diff/patch technique as the user expands or collapses directories.

___

Current issues in this repo relating to filetree were considered as well and should cover most of them, like scrolling jumps etc.

___

The reason I'm advocating this is because if more people focus on one source-of-truth, instead of reinventing the wheel, I think that'll help all of us. As that'll collectively make a thing more resilient.

**Comment by akosyakov** [comment]
@NeekSandhu It looks really cool what you did and that you had looked deeply at our and Monaco implementations.

If someone will be able to integrate it in `TreeWidget` without breaking APIs i would be glad to give it a try. We have products running on Theia and external extensions, because of it it is hard to change APIs already.

**Comment by vince-fugnitto** [comment]
As previously mentioned we are currently happy with our tree implementation and we have many products and external extensions currently using our API. Updating our `TreeWidget` throughout the framework would require significant effort (implementation, testing, adoption, etc) which we are not in the position at the moment to prioritize. If you happen to create a pull request proposing the idea we'd be happy to try it out but at the moment it is not one of our main priorities.
