### ISSUE TITLE
Shows spinning progress wheel forever

### ISSUE THREAD

**Issue by alainbernard** [theia-ide/theia#4095]
Hello,

I'm trying to deploy our own customized Theia in our corporate environment. Everything goes well when the required multiple proxy are sorted out, but when starting Theia with the command: 
`yarn theia start /workspace --hostname 0.0.0.0 --port 80`
we can access to the server hosting Theia, being welcomed by the spinning wheel, but then it never stops. 
The /workspace folder is read-write for everyone and there is no other output in the console of the server than the standard Theia starting outputs. 

Any clue of what can cause this behavior?

**Comment by marcdumais-work** [comment]
Hi @alainbernard 

There might be relevant error traces in your browser's devtools console. The symptoms you describe often are related to an application having one or more extension that's not compatible with the rest, resulting in two versions of some extensions to be included. 

Can you run the following command where you build Theia? i.e. the folder where your app's node_modules resides:
`yarn list | grep \@theia` and see if all Theia extensions have the same version?

**Comment by alainbernard** [comment]
Hi @marcdumais-work 

By looking at the browser stack, I just noticed this error message:
`WebSocket connection to 'ws://xx.xx.xx.xx/services' failed: WebSocket is closed before the connection is established.`

I ran the command you proposed, and it seems that all modules are in version `0.4.0-next.49db4e46`

**Comment by marcdumais-work** [comment]
Interesting - this is not the usual issue, we see often with this symptom. Is your Theia backend running in a container? 

Can you try accessing theia using a different browser, to rule-out that the workbench state restoration could be involved (it's saved in browser local storage)? I think using a private browser window could also be an option.

**Comment by alainbernard** [comment]
So, I did experiment a few things, and it appears that is somehow related to my company firewall... 
Indeed, this message appears when trying to connect from my computer, and does also appear when connecting on a working Theia instance on a public server from my computer. I'll have to investigate with them but at least it seems not related to Theia so I close this issue.
