### ISSUE TITLE
[plug-in][languages] Diagnostics are not represented in Problem view

### ISSUE THREAD

**Issue by svor** [theia-ide/theia#4097]
While using java VS Code extension I found that diagnostics are not represented in Problem view, so we can't see errors and warnings from the language server which was run by the plug-in.

**Comment by tsmaeder** [comment]
Can you see the diagnostic in the editor? How did you test this?

**Comment by svor** [comment]
In the editor I can see diagnostics with Error kind:
![screenshot from 2019-01-18 11-00-50](https://user-images.githubusercontent.com/1271546/51376302-adc05300-1b10-11e9-998f-1e31e5508fb9.png)
But no information in Problem view and no special decoration in Project tree

**Comment by tsmaeder** [comment]
This works fine for me: 
![screenshot from 2019-01-18 10-30-37](https://user-images.githubusercontent.com/13163770/51377865-35f02980-1b0c-11e9-872c-8d6a82b8b27c.png)

**Comment by akosyakov** [comment]
Editor, problems view and navigator use problems marker. If you convert plugin diagnostics to problem markers (not to Monaco diagnostics) they would appear everythere.

**Comment by tsmaeder** [comment]
Correct, Diagnostics from the API do not go through the ProblemManager.

**Comment by akosyakov** [comment]
fixed by https://github.com/theia-ide/theia/pull/4178
