### ISSUE TITLE
Support storing frontend state

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#41]
We should provide a storage mechanism that allows any components to load and save their state UI.
HTML5 Local Storage seems appropriate.

**Comment by MarkZ3** [comment]
Would it be good to start by saving the opened editors (Issue #265) ? It seems like a must-have feature from my perspective.

**Comment by svenefftinge** [comment]
Agreed. Generally, I would like to have a hook for extensions to participate in serializing and unserializing any local state. That state can be stored in local browser database but could also be used in e.g a URI (using JWT tokens) to create shareable links.

**Comment by hexa00** [comment]
@svenefftinge if it's a sharable URI it means we need to store this in the backend right ? vs using the browser local db ?

Guess we need to have a mix between some things that would be saved in the backend and some in the frontend ?

Like keep the layout in the frontend but the opened files / location in the backend?

**Comment by svenefftinge** [comment]
I actually was thinking of storing all state in the link. But with that we might quickly run into a situation where that is just too much data to fit into a URL. So let's solve this later when we have an actual use case.
Let's go with client site storage only for now and add backend storage when we've learned why we want it and when to use it.

**Comment by svenefftinge** [comment]
See https://github.com/theia-ide/theia/pull/525

**Comment by hexa00** [comment]
Note about #525 missing would be to store the cursor location in the editor ?
