### ISSUE TITLE
Have `sendText` return promise when the terminal have finished executing the command

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4100]
Is it possible to have `sendText()` resolve the promise when it has finished executing the command?
This will allow me to continue the executing of other things like opening a URL or files that are not related to the terminal.

One possible use case is deploying an app and opening an URL to that app after the deployment has completed.

**Comment by akosyakov** [comment]
I don't think it can be done with terminals. They are stream based, no notion of commands.Maybe something like that can be achieved with tasks. @marcdumais-work @simark ?

**Comment by simark** [comment]
Exactly, with a terminal you send bytes, but you don't know what happens on the other side.

It sounds like you want to use the [Process](https://github.com/theia-ide/theia/tree/master/packages/process) API, and wait for the process exit event?

**Comment by duemaster** [comment]
@simark 
So to clarify, you are saying to have a background extension that will create and run the process using the process API and update the client(frontend extension) when the command has finished executing?

Will that work if I would like to display the command and its output on the terminal widget?

**Comment by simark** [comment]
If you are running code in the frontend, you can use the Process API to start processes on the backend.  You can wait for it to exit using the `exit` event.  I don't know if you can make the output appear in a terminal though.

For that, implementing a task provider and starting a task is probably the way to go then.

**Comment by duemaster** [comment]
> If you are running code in the frontend, you can use the Process API to start processes on the backend. You can wait for it to exit using the `exit` event. I don't know if you can make the output appear in a terminal though.
> 
> For that, implementing a task provider and starting a task is probably the way to go then.

Ok, I give it a try.
Thanks!
