### ISSUE TITLE
support vscode scm api

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4103]
APIs: https://code.visualstudio.com/api/references/vscode-api#scm

There is VS Code extension for Git: https://github.com/Microsoft/vscode/tree/master/extensions/git

Our SCM UI is bound to Git right now. We need to extract Git-agnostic UI to a new extension. This extension should provide APIs similar to VS Code. Git extension has to be updated to use this API. The plugin extension then should use new API to implement VS Code SCM API.

**Comment by vinokurig** [comment]
If not we can take it, @akosyakov @svenefftinge WDYT?

**Comment by vinokurig** [comment]
The deadline for our related task (https://github.com/eclipse/che/issues/11867) is 5-th February

**Comment by svenefftinge** [comment]
Nice, please go ahead if you can start working on it now. :)

**Comment by vinokurig** [comment]
Before starting the work I need to find out:
Does this issue require to replace Theia Git package to VsCode Git Extension?

**Comment by vinokurig** [comment]
As I understood https://github.com/theia-ide/theia/issues/3815 is about replacing Theia extensions to VsCode extensions. This issue is mentioned in the list, so is it about deprecating Git extension in Theia?

**Comment by sunix** [comment]
Hi I am wondering if it is possible / good strategy to reuse vscode git extension and completely replace the current theia git implementation. WDYT ?

**Comment by vinokurig** [comment]
@sunix As far as I understood this issue is about supporting scm Plugin-Api. I think it is better to discuss such questions in https://github.com/theia-ide/theia/issues/3815 or https://github.com/theia-ide/theia/issues/3956

**Comment by akosyakov** [comment]
> Hi I am wondering if it is possible / good strategy to reuse vscode git extension and completely replace the current theia git implementation. WDYT ?

Eventually, maybe, if there won't be any clients. Before it the current git extension and git VS Code extension should share the same UI and contribution points.

**Comment by akosyakov** [comment]
@vinokurig It is another way around.

**Comment by vinokurig** [comment]
May be I missed something but as far as I understood this issue is about implementing [vscode scm api](https://code.visualstudio.com/api/references/vscode-api#scm) but Theia doesn't have Source Code Management. Am I right?

**Comment by vinokurig** [comment]
>Git extension has to be updated to use this API. The plugin extension then should use new API to implement VS Code SCM API.
@akosyakov Do you mean that Vscode scm api should use existed Git extension?

**Comment by vinokurig** [comment]
@akosyakov Could you please explain how this issue is related to VSCode Git extension?

**Comment by vinokurig** [comment]
Vscode uses Scm Service for this Api: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/scm/common/scmService.ts#L128, 
Do we need such service?

**Comment by vinokurig** [comment]
Moved the discussion to https://spectrum.chat/?t=951554dc-9fbf-4ad5-b5f2-2a6c07c058f0
