### ISSUE TITLE
change dependency vscode-nsfw to Axosoft/nsfw

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#4105]
vscode-nsfw (https://github.com/Tyriar/vscode-nsfw/commits/master) is more than one year old.
And if we compare it with its origin Axosoft/nsfw (https://github.com/Axosoft/nsfw/commits/master), vscode-nsfw does not have extra enhancements / bug fixes while it is 20 commits behind as of today.

Maybe we should use Axosoft/nsfw instead.

**Comment by akosyakov** [comment]
Cool, it seems that @implausible active again :) Would be interesting to test and see whether it fixes the memory leak issue: https://github.com/theia-ide/theia/issues/1284

**Comment by elaihau** [comment]
#1284 is not very likely fixed, as https://github.com/Axosoft/nsfw/issues/48 is still open.

**Comment by svenefftinge** [comment]
It is now fixed and released.

**Comment by elaihau** [comment]
> It is now fixed and released.

yes, the PR was also updated to use the new release. Thank you for the info !
