### ISSUE TITLE
[Feature] Support Go

### ISSUE THREAD

**Issue by sh7dm** [theia-ide/theia#4116]
Add golang support

**Comment by markkuit** [comment]
There already is a [Go extension](https://github.com/theia-ide/theia-go-extension). I'm personally still evaluating if and what features it's missing.

**Comment by akosyakov** [comment]
You also can follow https://github.com/theia-ide/theia/pull/4070 that should allow running VS Code extension for Go in Theia.

**Comment by vince-fugnitto** [comment]
Closing thanks to #4070, it is possible to run the VSCode Go extension in Theia
