### ISSUE TITLE
[plug-in] Tree View widget is sometimes unexpectedly empty

### ISSUE THREAD

**Issue by olexii4** [theia-ide/theia#4122]
It can be reproduce with that sample plugin:
https://github.com/eclipse/che-theia-samples/tree/master/samples/tree-view-sample-plugin
It happens randomly without any error message.
It is very frequently with a che-theia + kube:
- Sometimes unexpectedly empty:
    ![screenshot from 2019-01-21 14-53-47](https://user-images.githubusercontent.com/6310786/51476208-78746900-1d8d-11e9-8676-e19d144e1c4c.png)
- sometimes not empty
    ![screenshot from 2019-01-21 14-52-39](https://user-images.githubusercontent.com/6310786/51476210-7a3e2c80-1d8d-11e9-955f-dec167bb4a06.png)

**Comment by olexii4** [comment]
@vitaliy-guliy  No, I don't.
![screenshot from 2019-01-22 10-07-57](https://user-images.githubusercontent.com/6310786/51521188-7b736600-1e2e-11e9-9f77-b598644d32ca.png)

**Comment by vitaliy-guliy** [comment]
Tree works fine with Theia from master.
In che-theia image we use tagged version of Theia.
We don't need to change anything, just wait until 0.3.19 has been released.

**Comment by azatsarynnyy** [comment]
It looks like the same problem as I've described here https://github.com/theia-ide/theia/issues/3907 with more technical details after deeper investigation.
It works stable in standalone Theia but the problem is reproducible on the slower environments, e.g. Eclipse Che on k8s locally or on https://che.openshift.io

**Comment by vitaliy-guliy** [comment]
@azatsarynnyy yep, exactly. But I would say that TreeView should be created on registering a TreeDataProvider only when `ready` state is reached.

**Comment by olexii4** [comment]
duplicated  https://github.com/theia-ide/theia/issues/3907
