### ISSUE TITLE
[plugin] bump VS Code API version?

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#4124]
When I write a new VSCode extension, I will likely write it against the latest available version of the API, because it is pretty annoying to find out the right set of version numbers of individual npm packages for a certain prior VS Code release. 

In Theia, we currently strictly check that a plug-in does not refer to a higher VS Code API version than [1.27.2](https://github.com/theia-ide/theia/blob/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L89). A plug-in with a dep on a newer version will be rejected.

Does that version number make any difference at the moment? Shouldn't we bump it to a newer version, e.g. 1.30.2?

**Comment by benoitf** [comment]
@JanKoehnlein do you have the rejected message ? AFAIK version was just to avoid an undefined value, I don't think we're checking it inside Theia

**Comment by benoitf** [comment]
And for now I would say we're more close of 1.29 (many new APIs were introduced in 1.30)

**Comment by benoitf** [comment]
so i would say for now it's better to use 1.29 in version field (and compliant vscode language server library)

because, bumping to 1.30 may cause late failures as well (if vscode language server library is using for example DeclarationProvider (or other language API introduced in 1.30)

**Comment by tsmaeder** [comment]
I am pretty sure we never will "fully support" any given API version: VSCode will continue to run ahead of us. @JanKoehnlein about the npm versions: I don't quite understand the problem with the npm versions: is this strictly a problem when you want to create a new vscode plugin against a version of VS Code API with "yo code"?

**Comment by JanKoehnlein** [comment]
- `yo code` will setup a project with dependency on the latest VS Code extension API.
- If you are implementing a language, you likely will need a `LanguageClient`so you define a dependency to `vscode-languageclient`. VS Code will complete the latest release version for you.
- Newer versions of `vscode-languageclient` run a version check on the VS Code API, which is fixed to [`^1.30`](https://github.com/Microsoft/vscode-languageserver-node/blob/16317538e877d286cd67fc8577b10fe5efef936c/client/src/main.ts#L41)
- Theia sets exactly this version to [`1.27.2`](https://github.com/Microsoft/vscode-languageserver-node/blob/16317538e877d286cd67fc8577b10fe5efef936c/client/src/main.ts#L41).
- As a result the runtime check in the `LanguageClient` will fail tearing the entire plug-in down. Without notice, which is another issue.

To overcome this, one must know the exact version numbers of VS Code APIs packages like `vscode-languageclient` that matches the VS Code version `1.27.2` and use them as an upper version bound in their extension's `package.json`. AFAIK, this can only be determined by finding out the release date for VS Code `1.27.2`, browsing to the history of the respective VS Code API plug-in comparing dates, then looking for the version in the `package.json`. I hope you share my view that this is far from easy.

**Comment by akosyakov** [comment]
Stumble on the same with eslint and prettier extensions. They need 1.31.0, upgrading showed that nothing breaks since APIs which they used are covered. Why don't we bump it? There is no good reason to use version of eslint and prettier extensions for 1.27.2, if they work nicely with 1.31.0. cc @svenefftinge

**Comment by svenefftinge** [comment]
I agree we should support the latest released version. Ideally we'd go with a release schedule similar to vs code.

**Comment by benoitf** [comment]
hello, I wanted to update it this week before cutting down the release (was on my TODO list)

**Comment by tsmaeder** [comment]
> Ideally we'd go with a release schedule similar to vs code.

Yes, I think we'll need to track VS Code API. Currently, we're quite a bit behind in what we implement. We'd need to allocate some resources to catch up now and keep current in the future.

**Comment by akosyakov** [comment]
@benoitf Would be fine if we bump it to 1.32.3 today or you see that something else should be done except changing a version?

**Comment by benoitf** [comment]
@akosyakov it may be a bit scary as I didn't provide yet the PR but I'm taking it care of it today (before the cut of the release)

**Comment by akosyakov** [comment]
It's just we want to use it in our products which depend on next and now there is no way to change it. Maybe we could make it an env variable that products who like to live on the edge can bump up a version early.
