### ISSUE TITLE
How to pass data from backend to frontend via Events?

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4126]
I am trying to pass data from the backend to the frontend via events. (Backend fires events which is received by the frontend).

I am wondering if it possible as I tried following this [example](https://www.theia-ide.org/doc/Events.html), which doesn't seem to work.

Hence, I am wondering if I am using events correctly or it isn't meant to be used in such a manner.

**Comment by duemaster** [comment]
My bad, it was a timing issue. The backend did send an event detectable from the frontend. The issue is that the frontend did not initialise in time to pick up that event.

**Comment by akosyakov** [comment]
Generally we use [Event](https://github.com/theia-ide/theia/blob/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c/packages/core/src/common/event.ts#L25) for notifications, but it does not work for frontend-backend communications.

In this case, your backend service can have a frontend client. For instance, `FileSystem` has `FileSystemClient`: https://github.com/theia-ide/theia/blob/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c/packages/filesystem/src/common/filesystem.ts#L24

You can provide such client on the frontend and await then the backend calls it.

**Comment by duemaster** [comment]
> Generally we use [Event](https://github.com/theia-ide/theia/blob/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c/packages/core/src/common/event.ts#L25) for notifications, but it does not work for frontend-backend communications.
> 
> In this case, your backend service can have a frontend client. For instance, `FileSystem` has `FileSystemClient`:
> 
> [theia/packages/filesystem/src/common/filesystem.ts](https://github.com/theia-ide/theia/blob/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c/packages/filesystem/src/common/filesystem.ts#L24)
> 
> Line 24 in [73d23a4](/theia-ide/theia/commit/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c)
> 
>  export interface FileSystem extends JsonRpcServer<FileSystemClient> { 
> You can provide such client on the frontend and await then the backend calls it.

Oh, I think I might have used the client to send the event on the frontend side. Maybe that's why the events worked in my case.
