### ISSUE TITLE
How to bundle template files into an extension?

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4129]
I am currently writing an extension that creates some files from mustache.js. However, I realised that when I try to compile and build theia (run `yarn` and cd to `browser-app` to start theia), the templates files (.mustache files) aren't bundled into the lib folder, resulting in file not found exception.

I would like to know if this is to due to the configuration of the yeoman starter template and where can I change this setting?

**Comment by akosyakov** [comment]
You should make sure that all necessary files are packaged. Please have a look at `files` property of `package.json`: https://docs.npmjs.com/files/package.json#files

**Comment by duemaster** [comment]
@akosyakov 
Does the `lib` folder generated contain only compiled`.js` files? It seems that from the theia widget generator, `.css` files are imported and work but are not found in the `lib` folder.

I tried passing the absolute path of the template files when generating the files, and it works.

**Comment by akosyakov** [comment]
We put css files in `src` folder usually, which is packaged as well. These files are loaded from the frontend modules with relative imports from `lib` to `src` folder, for example:
https://github.com/theia-ide/theia/blob/cea62337848477b12b61ed7acf30634e12acc52d/packages/git/src/browser/history/git-history-frontend-module.ts#L24
