### ISSUE TITLE
Build fail because of node-gyp

### ISSUE THREAD

**Issue by alainbernard** [theia-ide/theia#4144]
When building Theia inside a corporate environment, even with npm and yarn proxy settings well configured, the build fail when building some OS-related packages, when using the `yarn install` command:

>
[4/4] Building fresh packages...
[1/9] ⠂ electron
[2/9] ⠂ vscode-nsfw
[3/9] ⠄ node-pty
[4/9] ⠄ drivelist
error /theiaide/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /theiaide/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.15.0/node-v8.15.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onread (net.js:622:25)
gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /theiaide/node_modules/oniguruma
gyp ERR! node -v v8.15.0

(this time it fails when building "oniguruma", sometimes it is when building "drivelist", I suspect the order of the build to be random).
Even if we download by another mean the required "node-v8.15.0-headers.tar.gz" package, build fails. 

The issue can be solved by manually running `node-gyp rebuild --proxy XXX` on the specific Theia package that failed to be built, but you can not include that step in an automated way in the Theia build process, which is annoying.

**Comment by akosyakov** [comment]
Are you sure that there is no env variables to configure proxy settings for node-gyp? What happens if you do something like `yarn install --http-proxy XXX`? Does not it pass settings down to `node-gyp`?

**Comment by alainbernard** [comment]
I dig a bit deeper into various issues on Github, and I found this one yarnpkg/yarn#2001. 

The command `npm_config_tarball=/path/to/node-v8.15.0-headers.tar.gz yarn install` worked and allows to run properly. Could be nice to have this "workaround" added to the documentation at some point.

**Comment by akosyakov** [comment]
> Could be nice to have this "workaround" added to the documentation at some point.

@alainbernard You are welcomed to add them :)
