### ISSUE TITLE
[cpp] CPP_CLANGD_COMMAND env variable no longer works

### ISSUE THREAD

**Issue by arekzaluski** [theia-ide/theia#4163]
## Issue

Since Theia version 0.3.19 it is impossible to use `CPP_CLANGD_COMMAND` env variable to override clangd location. Issue exists because following line will always return `true` and will never check other possibilities: https://github.com/theia-ide/theia/blob/845ca476051f86c0d26876812b8da226b22aa471/packages/cpp/src/node/cpp-contribution.ts#L35

Default `parameters.clangdExecutable` is always set to this value: https://github.com/theia-ide/theia/blob/845ca476051f86c0d26876812b8da226b22aa471/packages/cpp/src/common/index.ts#L25

## Possible solution
- Reverse check order and check first for `CPP_CLANGD_COMMAND` env variable

@marechal-p @akosyakov @thegecko

**Comment by arekzaluski** [comment]
Other possible solution is not to set a default value here: https://github.com/theia-ide/theia/blob/845ca476051f86c0d26876812b8da226b22aa471/packages/cpp/src/browser/cpp-preferences.ts#L62. I think that similar problem may exists also for `CPP_CLANGD_ARGS `

**Comment by marechal-p** [comment]
Ah indeed, when writing the conditional I assumed that if you didn't specify the preference for clangd, it would be undefined and move to check the environment variables. Turns out that thanks to the preference default, it always finds something in the LS start parameters.

Maybe we can just make the default for the preference to be `undefined`, that's what I expected to happen. Would that make sense?

**Comment by marechal-p** [comment]
Ah or to inverse the check order... Then again, I assumed that the environment variable would be part of the ambient context, while preferences are explicitly user defined, hence why I liked to have it first. But now I'm not so sure.

**Comment by arekzaluski** [comment]
Thank you for a quick answer. I think that both solutions will work and it should just be a matter of answering a question which of the two variables are more important:
- CPP_CLANGD_COMMAND env
- Profiles
Personally I think that a reversed check order may be a slightly better option because in general if user sets the env variable then he/she expects it to be used no matter what value is set in profiles.

**Comment by arekzaluski** [comment]
Also it will be a good idea to add a public method to be able to set a cpp settings. At the moment it is not easy to set it programatically and it is always loaded from profiles.

**Comment by marechal-p** [comment]
> Also it will be a good idea to add a public method to be able to set a cpp settings. At the moment it is not easy to set it programatically and it is always loaded from profiles.

What do you mean by "cpp setting"?
Can you explain a bit more what you'd like to be able to do programmatically?
Is it for an extension or a plugin?

**Comment by marcdumais-work** [comment]
@arekzaluski can we close this issue now or are there aspects still to address, now that #4164 is merged?

**Comment by arekzaluski** [comment]
Yes, problem was resolved in https://github.com/theia-ide/theia/pull/4164. I'm closing this issue.
