### ISSUE TITLE
support scm menu contributions

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4171]
See https://code.visualstudio.com/api/references/contribution-points#contributes.menus

- [x] The SCM title menu - `scm/title`
- [x] SCM resource groups menus - `scm/resourceGroup/context`
- [x] SCM resources menus - `scm/resource/context`
- [ ] ~SCM change title menus - `scm/change/title`~ - see https://github.com/theia-ide/theia/issues/4544

It depends on #4103

**Comment by vinokurig** [comment]
`scm/change/title` needs to have editor change details: (https://github.com/theia-ide/theia/issues/4544)
