### ISSUE TITLE
support view title menu contributions

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4174]
VS Code extension can contribute menu items to a view:
<img width="528" alt="screen shot 2019-01-28 at 11 31 37" src="https://user-images.githubusercontent.com/3082655/51830501-4cf30080-22f0-11e9-88da-0abe6ee3dee8.png">

See `view/title` contribution point [here](https://code.visualstudio.com/api/references/contribution-points#contributes.menus).

**Comment by ariel-bentu** [comment]
Is there a plan to support this?
thanks

**Comment by akosyakov** [comment]
It depends on https://github.com/theia-ide/theia/issues/5058

**Comment by akosyakov** [comment]
@ariel-bentu do you have sample vscode extension?

**Comment by ariel-bentu** [comment]
I will test it tonight and report back. No sample code to demo the issue
for now, bur real code :)

בתאריך יום ב׳, 17 ביוני 2019, 18:16, מאת Anton Kosyakov ‏<
notifications@github.com>:

**Comment by akosyakov** [comment]
it was fixed in https://github.com/theia-ide/theia/pull/5665
