### ISSUE TITLE
More Simple Xtext Extension Examples..

### ISSUE THREAD

**Issue by Filterk** [theia-ide/theia#418]
Hello.

I try to integrate Xtext extensions to Theia-IDE.

Now, I reference codes below git.
https://github.com/TypeFox/theia-xtext

However, this example is not working now because Theia-IDE's version is updated.
And I have reviewed YANG IDE, but because of addition 2 modules(xtext-jflex and yang-lsp), analysis is not easy...

In TypeFox, have any plan to release simple Xtext extension examples(without Sprotty and with Sprotty) which is compatible current Theia-IDE version(above 0.1.1)?

Thanks.

**Comment by akosyakov** [comment]
@Filterk  As you mentioned there is already an example without Sprotty: https://github.com/TypeFox/theia-xtext. If it does now work, please open an issue there.

**Comment by akosyakov** [comment]
@Filterk see https://github.com/TypeFox/theia-xtext/issues/4
