### ISSUE TITLE
Please shall we show more example case ?

### ISSUE THREAD

**Issue by frankLife** [theia-ide/theia#4187]
Doing this to let more developer get more information about project and let the theia community grow more fast !

**Comment by vince-fugnitto** [comment]
Can you clarify what you mean by showing more example cases?
Do you mean increasing documentation, and/or describing potential theia-based example applications?

**Comment by frankLife** [comment]
Yes, I mean the case maybe the theia-based example applications.

**Comment by akosyakov** [comment]
@frankLife Have you seen already https://github.com/theia-ide/theia-apps?

What particularly are you looking for? How to create a custom app with multiple custom extensions?

**Comment by frankLife** [comment]
@akosyakov yes, I had seen the [theia-app](https://github.com/theia-ide/theia-apps) , but I found the repository is more related to specific language such as java and go. I just want to learn more about custom extension or plugin built with theia like you say to help us to fit our business case. 😄

**Comment by akosyakov** [comment]
And you seen already docs on plugin/extensions development:
- Theia extension - https://www.theia-ide.org/doc/Authoring_Extensions.html
- Theia plugin - https://www.theia-ide.org/doc/Authoring_Plugins.html
- VS Code extension - https://code.visualstudio.com/api/get-started/your-first-extension + https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

**Comment by frankLife** [comment]
@akosyakov thanks a lot ! Is there also any more custom apps we can learn ?

**Comment by svenefftinge** [comment]
Here's another: https://github.com/theia-ide/yangster

**Comment by frankLife** [comment]
@svenefftinge excellent!
