### ISSUE TITLE
[git] embedded git fails for push/pull/sync commands

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#4192]
With reference to this PR: https://github.com/theia-ide/theia/pull/3747 we have seen the embedded git solution working well in most cases.

However, when executing some commands in the git pane, errors occur. Specifically when undertaking a pull or push, you get:

> Request push failed with message: LOCAL_GIT_PATH must be specified when using an exec function.

Could this be due to env variables not being passed to spawned processes?

@kittaakos

**Comment by thegecko** [comment]
Please clarify `Git customization`. I'm not aware of any customizations in this area.

**Comment by kittaakos** [comment]
> Git customization

Do you use the Git extension as is or do you have any special bindings or UI customization for it?

**Comment by thegecko** [comment]
OK, so I have proved this works with latest Theia master in development mode. It must be something to do with the way we run or package it. Closing for now.

**Comment by kittaakos** [comment]
Does it happen with https://github.com/theia-ide/theia-apps/tree/master/theia-electron?

**Comment by thegecko** [comment]
I'll try

**Comment by thegecko** [comment]
Works fine with https://github.com/theia-ide/theia-apps/tree/master/theia-electron :)
