### ISSUE TITLE
support vscode task contribution points

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4211]
See:
- https://code.visualstudio.com/api/references/contribution-points#contributes.taskDefinitions
- https://code.visualstudio.com/api/references/contribution-points#contributes.problemMatchers
- https://code.visualstudio.com/api/references/contribution-points#contributes.problemPatterns

@marcdumais-work it is required to ship built-in VS Code extensions like `grunt` and `gulp`

**Comment by tolusha** [comment]
@akosyakov 
Do you mind If I handle this?

**Comment by tolusha** [comment]
I will start from taskDefinistions [1]
[1] https://code.visualstudio.com/api/references/contribution-points#contributes.taskDefinitions

**Comment by akosyakov** [comment]
@tolusha yes, it is fine with me

I've mentioned @marcdumais-work because I believe there is not support of `problemMatchers` and `problemPatters` yet. Since Ericsson team was working on the task extension before, maybe they want to implement support of it as well.

**Comment by tolusha** [comment]
I postponed this task for a while.

**Comment by marcdumais-work** [comment]
Hi @tolusha 

> I postponed this task for a while.

Sorry, I missed this exchange. I hope you did not postpone because of it. I am fine with you working on this, else we will come around to it eventually.

**Comment by marcdumais-work** [comment]
@tolusha Unless you plan to work on this issue in the very near future, we would like to take-it over and @elaihau would start working on it. Please let us know if you have objections.

**Comment by tolusha** [comment]
@marcdumais-work I don't have any objections

**Comment by elaihau** [comment]
opened a pr https://github.com/theia-ide/theia/pull/5024 for this one
