### ISSUE TITLE
tasks contributed by VS Code extensions don't work

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4216]
They look bogus:
<img width="670" alt="screen shot 2019-02-01 at 09 16 36" src="https://user-images.githubusercontent.com/3082655/52110874-4c18e200-2602-11e9-8e4b-3d7d5d2ac95f.png">

And cannot be executed:
<img width="1556" alt="screen shot 2019-02-01 at 09 16 59" src="https://user-images.githubusercontent.com/3082655/52110872-491df180-2602-11e9-9071-5eb892dc0fbe.png">

You can reproduce it with `grunt` & `gulp` VS Code built-in extensions.

**Comment by akosyakov** [comment]
@elaihau What I do for now to try built-in VS Code extensions, for example for `grunt`:
- clone and install this extension https://github.com/theia-ide/vscode-builtin-extensions somewhere
- after that copy `vscode-builtin-extensions/vscode/extensions/grunt`  to `theia/plugins`
- then start Theia, `grunt` VS Code extension should be installed, check `plugins` View
- you can debug source code of this extension with `Hosted Plugin: Debug Instance` command

Particularly for `grunt` you will need to study how to work with it, I've created an example project with from [grunt-init-node](https://github.com/gruntjs/grunt-init-node). After you have it, you should compare experience in Theia and VS Code. VS Code users should not be lost. You can also find some articles for working with `grunt` in VS Code and try to follow along them with Theia.

**Comment by elaihau** [comment]
Thank you @akosyakov !

I followed the instructions to have the `grunt` extension built, copied to `theia/plugins`, and shown up in the plugins view.

With a project, where the grunt tasks are defined, opened in theia, I was able to see similar items from 'Run Tasks'.

**Comment by elaihau** [comment]
> * you can debug source code of this extension with `Hosted Plugin: Debug Instance` command

and from this github issue we can find more details on how to debug the theia plugins & vscode extensions: https://github.com/theia-ide/theia/issues/3251

**Comment by akosyakov** [comment]
I've just tried grunt extension with grunt init example and it does not detect tasks at all.

**Comment by elaihau** [comment]
tasks contributed by npm, grunt, gulp, jake, typescript-language-features now work in theia. 

could we close this issue if i am not missing anything ? 
@akosyakov

**Comment by akosyakov** [comment]
@elaihau thank you!
