### ISSUE TITLE
[plug-in] window.onDidChangeActiveTextEditor is not fired

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#4218]
Sometimes when restoring the Theia layout after restoring opened files the theia.window.onDidChangeActiveTextEditor occasionally is not sent.
Plugin cannot handle active text editor properly.

**Comment by mmorhun** [comment]
Cannot reproduce the described problem.
But during testing found that there is some focus related differences with VSCode: Theia triggers a new `onDidChangeActiveTextEditor` event when focus was taken and then returned back.

**Comment by mmorhun** [comment]
Also VSCode fires the `onDidChangeActiveTextEditor` with undefined after an editor tab closing.

**Comment by mmorhun** [comment]
Mentioned above incompatibilities are fixed in the PR above.
