### ISSUE TITLE
complete implementation of workspace APIs

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4240]
- [x] `workspace.rootPath` missing

**Comment by timkpaine** [comment]
This also doesnt work: `vscode.commands.executeCommand('workbench.files.action.refreshFilesExplorer');`

**Comment by akosyakov** [comment]
Linking: https://github.com/theia-ide/theia/issues/4565

`updateWorkspaceFolders` as well needed for vscode-go extension
