### ISSUE TITLE
Download menu entry doesn't work on Firefox

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia#4248]
Steps to reproduce:

1. Open [Theia in Theia (Gitpod.io)](https://gitpod.io/#github.com/theia-ide/theia)
2. Right-click on any file in the file tree, then click the `Download` menu entry

Expected behavior:

- The file gets downloaded

Actual behavior:

- Nothing happens (reproduced in both Firefox and Chrome, and on both Linux and Mac)

**Comment by jankeromnes** [comment]
Thanks @sylvestre for reporting this!

It's also worth nothing that no error is logged in the console, unfortunately.

**Comment by svenefftinge** [comment]
Just tried it and it worked.

**Comment by jankeromnes** [comment]
Interesting. It didn't seem to do anything for me on Chrome at first (using `localhost:3000` from Theia-in-Docker), but then suddenly it started working again (also it downloaded a `project.tar` first, instead of the file I requested, but that might have been my mistake).

Now it seems to work fine in Chrome, but I still can't get it to work in Firefox.

**Comment by geropl** [comment]
With bad internet I see quite a delay in Chrome between "Click Download" and the actual download starting (in Chrome UI).

Also, Download does not work in Firefox (no log output in either frontend nor backend).
