### ISSUE TITLE
[plugin][webviews] Fix `vscode-resource:` resources

### ISSUE THREAD

**Issue by kaviththiranga** [theia-ide/theia#4251]
As mentioned at https://code.visualstudio.com/api/extension-guides/webview#loading-local-content, we have used several local resources in webviews. When this plugin is hosted in theia and when we open the webviews which uses those local resources, I get below error on browser console.

<img width="464" alt="screen shot 2019-02-05 at 9 35 33 am" src="https://user-images.githubusercontent.com/1505855/52252631-71229300-2929-11e9-92e0-9e8c82586631.png">

**Comment by benoitf** [comment]
thanks for the report @kaviththiranga 
I did a fix for theia-resource and I forgot to apply it for vscode-resource
https://github.com/theia-ide/theia/pull/4014

issue is that only the first resource is replaced

will fix for net release

**Comment by kaviththiranga** [comment]
@benoitf thanks for the update, will tryout fixing locally to test this for the moment.

**Comment by kaviththiranga** [comment]
@benoitf replace the line with

``` var newHtml = html.replace(new RegExp('vscode-resource:/', 'g'), '/webview/'); ```

fixed the issue locally.

**Comment by kaviththiranga** [comment]
Sent a PR with the fix https://github.com/theia-ide/theia/pull/4255/files
