### ISSUE TITLE
How do I unregister subMenu?

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4252]
I would like to hide certain Menu Options such as Files, Selection in Theia. I found out that there is currently an API(#2951) that allows unregistering some of the menuActions but not subMenu. This leaves the subMenu to be rendered but no existing options are shown.

Is there a way to remove the subMenu altogether?

**Comment by kittaakos** [comment]
@duemaster, you can subclass the `CommonFrontendContribution` class, override the `registerMenus` method, then register the menus you need and finally rebid the contribution.

You may want to customize `WorkspaceFrontendContribution` class too. See [here](https://github.com/theia-ide/theia/blob/e7a5cf1c49fff96bb90b4e5e1554f5b3268309f0/packages/workspace/src/browser/workspace-frontend-contribution.ts#L92).

**Comment by bezidejni** [comment]
Can you please give some more details here @kittaakos ?

If I subclass `CommonFrontendContribution`, change the `registerMenus` method to add the default menus, they get added twice since the method in both my class and default `CommonFrontendContribution` gets executed. If I unbind `CommonFrontendContribution` in my extension, then I don't get a workable editor at all.

**Comment by duemaster** [comment]
@bezidejni. Could you try unbind and bind the CommonFrontEndContribution to your custom exension?

**Comment by bezidejni** [comment]
@duemaster That actually seems to work, thanks!

But I still don't know how to remove the subMenu. In this case I could stop some default menus generated in `CommonFrontendContribution` from getting created, but for example the "Go" menu gets created in [menu.ts](https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-menu.ts#L75). Does that mean I'd have to extend `EditorMenuContribution` as well to stop those menus from getting created or is there an easier way?

**Comment by akosyakov** [comment]
@duemaster to unregister submenu: 
```ts
MenuModelRegistry.unregisterMenuAction(submenuId, menuPath)
```
for instance: 
```ts
MenuModelRegistry.unregisterMenuAction(CommonMenus.HELP[CommonMenus.HELP.length - 1], CommonMenus.MAIN_MENU_BAR)
```

**Comment by ghewadesumit** [comment]
> ```ts
> MenuModelRegistry.unregisterMenuAction(CommonMenus.HELP[CommonMenus.HELP.length - 1], CommonMenus.MAIN_MENU_BAR)
> ```

In which file should I write the above code to disable or hide the sub menu.

**Comment by akosyakov** [comment]
You should implement https://github.com/eclipse-theia/theia/blob/a6d565ef1e83aa4fb85bbd1ca3ac7d355fe978a8/packages/core/src/common/command.ts#L114

**Comment by squidwarddab1111** [comment]
@akosyakov do you mean implementing this through an extension?

 Override the CommandContribution in the contribution.ts and bind it in the frontend-module.ts?

**Comment by akosyakov** [comment]
@squidwarddab1111 yes, your extension should provide a class implementing this interface and bind it in the extension frontend module
