### ISSUE TITLE
Drag & Drop  a file to the root folder does not work

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#4260]
When Dragging a file to a sub-folder, it Drags &Drops the file to the folder, but if you try to Drag the same file to the original location (Root folder), it doesn't work. Unable to drop a file to the root folder.
We need to have another file in the root folder, then drop the selected file over that file to allow Drop in a file. Still, we need to refresh the workspace. If the last item in the root folder is a folder, then it is impossible to drop a file into the root folder.

![drag droptorootfolder](https://user-images.githubusercontent.com/419051/52286255-e300d980-2935-11e9-9181-01bfd9077b8b.gif)

**Comment by benoitf** [comment]
@lmcbout drag the file to the `iot` folder ?

**Comment by vince-fugnitto** [comment]
@lmcbout dragging to the first root works, to the empty area it does not.

**Comment by lmcbout** [comment]
Thanks @benoitf  @vince-fugnitto .  I will close it then.
