### ISSUE TITLE
How do icons work in Theia?

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4262]
I am trying to figure out how icons are rendered in Theia.
I think they are somehow related to font-awesome but not sure where are they defined as when I try changing to another icon, it doesn't get rendered.

I am referring to something like [this](https://github.com/theia-ide/theia/blob/master/packages/mini-browser/src/browser/mini-browser-open-handler.ts#L187).

**Comment by akosyakov** [comment]
Particularly for `TabBarToolbarRegistry`, you either can use font-awesome icons in `text` property as described [here](https://github.com/theia-ide/theia/blob/5956e48a3e9bffccc6f8fc8379ebe23957f43735/packages/core/src/browser/shell/tab-bar-toolbar.tsx#L137-L155). Or provide an [icon class](https://github.com/theia-ide/theia/blob/5956e48a3e9bffccc6f8fc8379ebe23957f43735/packages/core/src/common/command.ts#L38) for a tab bar item command.
