### ISSUE TITLE
[plugin][webview][intermittant] window.postMessageExt is not a function 

### ISSUE THREAD

**Issue by kaviththiranga** [theia-ide/theia#4267]
In some of our webviews, we use webview.postMessage() at very early stage to get some data before rendering happens. We get above error intermittently when we open those webviews - mostly first render breaks and others are successful.

Going through the source code, I found the place where postMessageExt is injected to window object of iframe at https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/main/browser/webview/webview.ts#L99

My initial guess is that it has something to do with timeouts used below there before calling onLoad.

**Comment by akosyakov** [comment]
@kaviththiranga Do you think it would be possible to come up with a simple VS Code extension reproducing it? Or you track it down and fix for your webview :)

**Comment by kaviththiranga** [comment]
@akosyakov I will try to track it down with my webview. In worst case, I will create a sample to reproduce.

**Comment by kaviththiranga** [comment]
Seems my guess is correct. Reducing the timeout to 50ms at https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/main/browser/webview/webview.ts#L128 fixed the issue for all my webviews.

I am trying to understand a proper fix for this. I can add a timeout for webviews from our side, but then it will be another hack.
