### ISSUE TITLE
Error: /usr/lib64/libstdc++.so version GLIBCXX_3.4.18... coming from vscode-nsfw

### ISSUE THREAD

**Issue by timkpaine** [theia-ide/theia#4269]
I'm compiling with a compiler in a non-standard directory, and a much older one in /usr/lib, and setting up my LD_LIBRARY_PATH correctly. If I `ldd` on `node_modules/vscode-nsfw/build/Release/nsfw.node`, I see it pointing to the correct libstdc++ so in my non-standard directory, but at run time it looks like it tries to pickup /usr/lib64. 

Is the environment being passed to whatever bit of code runs the file system watcher? I've rebuilt nsfw separately and npm linked it in, and still the issues persist, so i'm thinking its a theia issue rather than a vscode-nsfw issue.

**Comment by kittaakos** [comment]
> so i'm thinking its a theia issue

@timkpaine, what did you do?

**Comment by timkpaine** [comment]
Just followed the getting started after setting my path and ld library path to point to my custom compiled. Is it possible there is a process being spawned that doesn't grab env from its parent?

**Comment by timkpaine** [comment]
A few updates:
- I can get it to load by calling node directly with the `node_modules/.bin/theia` script and `LD_PRELOAD`. 
- This flag needs to be propagated to [subprocesses](https://github.com/theia-ide/theia/blob/master/packages/process/src/node/raw-process.ts#L97) as well

**Comment by timkpaine** [comment]
I've "solved" it by modifying the above script, as well as any subprocesses (e.g. [here](https://github.com/theia-ide/theia/blob/cc51575a2c8660f13794ed9099ee14daaca982b9/packages/process/src/node/raw-process.ts#L102)) to include the `LD_PRELOAD`.
