### ISSUE TITLE
Remove the dev server configuration from webpack configs

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#427]
We don't use the dev server anymore after https://github.com/theia-ide/theia/pull/397#issuecomment-325287560, but the webpack configs still contain configuration for them.
- [x] the existing config for the browser example should be adjusted: https://github.com/theia-ide/theia/blob/master/examples/browser/webpack.config.js#L109
- [x] the same changes should applied to the browser generator: https://github.com/theia-ide/theia/blob/master/generator-theia/src/common/app-package-generator.ts#L173
- [x] the browser generator should not add the dev dependency to the dev server

**Comment by akosyakov** [comment]
PRs are welcomed.

**Comment by hexa00** [comment]
IMO this is more like #397 had missing parts and we need to fix it...

I mean I don't care how fixes it but I don't see it as a low priority let's way for an external party to fix...

**Comment by akosyakov** [comment]
Will be fixed witg https://github.com/theia-ide/theia/pull/527

**Comment by akosyakov** [comment]
Fixed with https://github.com/theia-ide/theia/pull/527
