### ISSUE TITLE
Menu contribution doesn't work on windows and Docker

### ISSUE THREAD

**Issue by DoroNahari** [theia-ide/theia#4270]
I have this pluginin trying to add menu items to Theia: https://github.com/DoroNahari/my-theia-plugin

When running Theia on Ubuntu with the plugin, i can see my plugin's command and the new "explorer/context" menu item that the plugin added.
When doing the same on Windows or Docker I can see the command but not the menu item.

**Comment by akosyakov** [comment]
Could you check on Windows/Docker that a plugin actually deployed? In `View` -> `Plugins`.  It seems that a command is not registered.

Please also check the browser and backend logs for errors.

**Comment by DoroNahari** [comment]
The plugin is deployed and the command is registered. Attached screenshot and logs
![2019-02-07_11-35-30](https://user-images.githubusercontent.com/24614792/52402375-c5b24380-2acc-11e9-957c-9cdb7e3acd80.png)
[backend_log.txt](https://github.com/theia-ide/theia/files/2840144/backend_log.txt)
[chrome_log.txt](https://github.com/theia-ide/theia/files/2840145/chrome_log.txt)



.

**Comment by amiramw** [comment]
@DoroNahari after changing your package.json to call the packager with [this windows opened PR](https://github.com/eclipse/theia-plugin-packager/pull/7) the flow seems to work for me.
