### ISSUE TITLE
FileUri gets loaded in browser

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4272]
`git` and `plugin` extensions causing it.

It is bogus to use `FileUri.fsPath` on the frontend, one should retrieve `fsPath` from the backend with `FileSystem.getFsPath`.

**Comment by kittaakos** [comment]
> `git`

https://github.com/theia-ide/theia/pull/4302

**Comment by kittaakos** [comment]
The Git part was fixed via https://github.com/theia-ide/theia/commit/1955032819a2ae754265a259f8a569809116ad20.

**Comment by mmorhun** [comment]
`plugin-ext` fixed in https://github.com/theia-ide/theia/pull/5314
