### ISSUE TITLE
[cpp] Switch between source/header file should be enabled only for cpp files

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#428]
Right now this command is always enabled for all editors and even if cpp file is not selected or an editor is opened for it.

**Comment by akosyakov** [comment]
PRs are welcomed. `isEnabled` should be implemented here: https://github.com/theia-ide/theia/blob/master/packages/cpp/src/browser/cpp-commands.ts#L45

**Comment by svenefftinge** [comment]
Shouldn't it be `isVisible`? I don't want to see that C++ specific command in other editors.

**Comment by epatpol** [comment]
How does that work currently, the isEnabled() is for when a command is executed, but is the isVisible option the one used to show it in a menu? i.e if a command is disabled but visible will it be greyed out?

**Comment by akosyakov** [comment]
`isVisible` only used for menus and does not take into the account  `isEnabled`, e.g. one can have a visible menu item but disabled.

In this case `isVisible` and `isEnabled` should do the same, e.g `isViisble` can delegate to `isEnabled`.

**Comment by akosyakov** [comment]
@Nebiroth What about `isVisible`?
