### ISSUE TITLE
How to install and display at a given URL

### ISSUE THREAD

**Issue by NevilleBulmer** [theia-ide/theia#4298]
Hi, I hope this isn't a stupid question, I am trying to install theia and have it display at, for example, www.example.com.

Also is there any way to modify the main page of the IDE, my plan is to implement a floating chat icon so that group may chat about the current project, I know this would be out of the scope for theia so I am planning on implementing this myself.

I am trying to get the above working so i can implement user accounts around the IDE.

Any help would be greatly appreciated.

**Comment by svenefftinge** [comment]
Theia itself runs on an express web server, it doesn't have any requirements to the domain name you use for accessing the application. For the other question: Multi-user management is something that is handled outside of Theia. E.g. Gitpod.io integrates with GitHub OAuth and provides a service to a dedicated Theia extension that obtains information about the active user and the collaborators.
