### ISSUE TITLE
EventListener causes memory leak

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4309]
I am using [Events](https://www.theia-ide.org/doc/Events.html) to receive notifications to update a ReactWidget. However, I am encountering some errors about a possible memory leak in the browser.
![screenshot from 2019-02-12 15-00-54](https://user-images.githubusercontent.com/8973687/52617526-1f54ac80-2ed7-11e9-9b78-a61f55644bb6.png)

Is there a way to "unsubscribe" from the event listener? I tried changing it to null in the onBeforeDetach() but it does not seem to  resolve the issue.

**Comment by kittaakos** [comment]
@duemaster, if you are using the `ReactWidget` which is a subclass of the `BaseWidget`, then you have access to the `toDispose` (`DisposableCollection`). Whenever you attach a listener you will get back a `Disposable` object that you can push into the `toDispose` collection, and it will be automatically disposed when your widget is disposed.

```js
this.toDispose.push(this.model.onSomethingChanged(event => console.log(`Do something with the ${event}.`)));
```

If you are not using the `BaseWidget` or any of its subclasses, you have to make sure you dispose the disposable manually.
