### ISSUE TITLE
Is it possible to have a button to add text at where the cursor is at?

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4316]
For example, the user could press a button in one of the widgets and text would be added/deleted/replaced in the editor at a predefined position or where the cursor is.

**Comment by kittaakos** [comment]
Although I did not try it, it should be feasible.

 - You inject the `EditorManager`.
 - You get the `currentEditor`. (Not the `activeEditor`. Read the JSDoc if you are curious what is the difference, if you cannot understand the difference from the JSDoc, let us know.)
 - Get the `TextEditor` from the `EditorWidget`.
 - Get the `cursor` position from the `TextEditor` and call `replaceText`.

You can also look into the search widget, we have the search and replace functionality [here](https://github.com/theia-ide/theia/blob/1955032819a2ae754265a259f8a569809116ad20/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L458-L490).

I hope this helps.

**Comment by kittaakos** [comment]
Please reopen if required.
