### ISSUE TITLE
Update to Xterm.js 3.11

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#4319]
We should update to https://github.com/xtermjs/xterm.js/releases/tag/3.11.0
And enable the new awesome reflow @tyriar implemented.

**Comment by svenefftinge** [comment]
See https://github.com/xtermjs/xterm.js/issues/1941

**Comment by svenefftinge** [comment]
We need to debounce the resize calls a bit more.

**Comment by Tyriar** [comment]
Should release 3.12.0 soon which will have an important fix for https://github.com/xtermjs/xterm.js/issues/1926 in it.

**Comment by vince-fugnitto** [comment]
Closed by #4680
