### ISSUE TITLE
multi column layout support for editors (similar to VSCode)

### ISSUE THREAD

**Issue by kaviththiranga** [theia-ide/theia#4322]
Please refer to https://code.visualstudio.com/api/references/vscode-api#ViewColumn.

As shown below, in our VSCode extension, we have a webview which is shown in second column - it provides a side by side view with source code.

Is there a plan to support this in Theia too? ATM, this view is rendered in a new editor tab when hosted in Theia - which doesn't serve the original intension of it for us.

<img width="1679" alt="screen shot 2019-02-13 at 9 02 24 am" src="https://user-images.githubusercontent.com/1505855/52685052-52964a80-2f6e-11e9-9a8f-2f7c7e4059d1.png">

**Comment by svenefftinge** [comment]
Theia layouting is even more flexible than VS Code. Opening any widget to the side of an existing widget can be done through the application shell.

**Comment by kaviththiranga** [comment]
I guess then what's missing here is the support for showOptions arg in showOptions

**Comment by kaviththiranga** [comment]
and some kind of a translation from VSCode terminology to Theia shell. When we create the webview, we have set the viewColumn as Two. But when the plugin is hosted in Theia, this is ignored.

**Comment by marechal-p** [comment]
Maybe it is a bit extreme, but with the current layout options that Theia offers, I don't see a way of mapping the column based layout from VS Code to Theia.

See the following screenshot, where I have 6 editors in the main panel:

![image](https://user-images.githubusercontent.com/14182238/52871969-48647f80-3119-11e9-97f8-d24933a72017.png)

Disclaimer: I don't think I would ever have such a workspace layout...

But the point stays the same: I don't see how to do it considering the example I provided.

On the other hand the ApplicationShell is able to open widgets on the side of something else, but it is always relative, never an absolute `col: 2`.

**Comment by akosyakov** [comment]
It won't be supported in Theia core, but plug-in extension should analyze the structure of current layout and translate VS Code `ViewColumn` to proper Theia position.

**Comment by akosyakov** [comment]
It should have been fixed by https://github.com/theia-ide/theia/pull/4892

@kaviththiranga please check again and open if not
