### ISSUE TITLE
[Plug-in] workspace.findFiles not working as expected

### ISSUE THREAD

**Issue by invincibleJai** [theia-ide/theia#4323]
Find files across all workspace folders in the workspace. https://code.visualstudio.com/api/references/vscode-api#workspace.findFiles

`vscode.workspace.findFiles(include: GlobPattern, exclude?: GlobPattern | null, maxResults?: number, token?: CancellationToken): Thenable<Uri[]>
`

sample -` findFiles('package.json', '**/node_modules/**', 10)`

It's listing all occurrences of `package.json` even one inside `node_modules` which should be excluded and even this parameter count has no effect.

Currently, even relative pattern is not working  as expected i.e 

```
const relativePattern = new vscode.RelativePattern(
            workspaceFolder,
            '{pom.xml,**/package.json,requirements.txt}'
          );
vscode.workspace.findFiles(relativePattern, '**/node_modules')
```

it returns empty `[]`

**Comment by slemeur** [comment]
@evidolob : Is that something your team can take care off?

**Comment by invincibleJai** [comment]
Thanks @slemeur . I see it's been already implemented https://github.com/theia-ide/theia/pull/3128 by @vparfonov but am experiencing above.

**Comment by invincibleJai** [comment]
Guys, any update on this thread. Thanks!!

**Comment by vparfonov** [comment]
@invincibleJai I will take a look

**Comment by invincibleJai** [comment]
@vparfonov thanks and for testing 
am using image `theiaide/theia-full:next`

https://github.com/redhat-developer/vscode-openshift-tools/wiki/Testing

Will the changes be available there?

**Comment by vparfonov** [comment]
@invincibleJai Yes, if you run in with next it should be available

**Comment by invincibleJai** [comment]
thanks @vparfonov, I tried on `next` and still i get same experience as in issue.

**Comment by vparfonov** [comment]
@invincibleJai Can, you, please build it from source and check again. Also can you share plugin what you try? Thanks

**Comment by invincibleJai** [comment]
@vparfonov am trying on https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics 

Can you pls help with some doc to build from src, i tried some time back but couldn't

PS: it's using `preview-html` so am making changes to files in `/tmp/vscode-unpacked/vscode_extension_redhat_fabric8_analytics.vsix/extension/` for debugging testing extension

**Comment by invincibleJai** [comment]
@vparfonov need your help, have tried with latest `theia-full:next` and earlier when I filed the issue basic search without glob used to work as in 

`vscode.workspace.findFiles('target/npmlist.json')`

but now even for this am getting an empty list. It'll be really nice if you can verify once.

**Comment by invincibleJai** [comment]
@vparfonov it's working even with `vscode.RelativePattern`, one thing why i got confused initially is if we pass `vscode.workspace.findFiles('target/npmlist.json')` it returns empty list and we change `vscode.workspace.findFiles('**/target/npmlist.json')` it's able to search.
