### ISSUE TITLE
[mini-browser] Let's use the `resetBackground` property instead of hard coding it in the CSS

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4324]
See https://github.com/theia-ide/theia/commit/73d23a46f9715aa5b9a04c2b5158c4fe39876d8c#r32301569

**Comment by kittaakos** [comment]
It should happen here https://github.com/theia-ide/theia/blob/60206635557685f049e1334362d491966f519171/packages/mini-browser/src/browser/mini-browser-content.ts#L608

Perhaps we broke it in https://github.com/theia-ide/theia/pull/3451.

**Comment by svenefftinge** [comment]
@kittaakos oh, yes. can you look into it?
