### ISSUE TITLE
[commands] The command handler has to be implicitly enabled when the `isEnabled` function is not defined

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4326]
If a command handler does not have the `isEnabled` function, it cannot be executed. I propose to make the handler implicitly enabled if `isEnabled` is not defined. Otherwise, the handler does not make any sense and clients have to add `isEnabled : () => true;`

https://github.com/theia-ide/theia/blob/60206635557685f049e1334362d491966f519171/packages/core/src/common/command.ts#L272

**Comment by svenefftinge** [comment]
Sounds like a bug.

**Comment by kittaakos** [comment]
I will look into this, something was odd.

**Comment by kittaakos** [comment]
> Sounds like a bug.

It must have been in my code. It works as expected.
