### ISSUE TITLE
[preferences] Allow overriding preference defaults for an application in package.json

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#4334]
In our use case we have the need to override the default values of workspace preferences without causing the system to save a config file.
Specifically we want the `workspace.preserveWindow` to default to `true` instead of `false` as declared in the workspace preferences schema.

A nice way this could work would be if the defaults could be read from the application `package.json` file, e.g. something like:

```json
{
  "theia": {
    "target": "browser",
    "frontend": {
      ...
    },
    "preferences": {
      "config": {
        "workspace": {
          "preserveWindow": true
        }
      }
    }
  }
}
```

Perhaps related to https://github.com/theia-ide/theia/pull/4296

Thoughts/other approaches?

cc @akosyakov

**Comment by akosyakov** [comment]
I would start with providing API for it that it could be done programmatically. There can be a default client for such API which reads default preferences from application `package.json`.

cc @svenefftinge

**Comment by thegecko** [comment]
Ack

**Comment by akosyakov** [comment]
@thegecko are you working on it? I would like to implement it. It goes well together with https://github.com/theia-ide/theia/issues/4524

**Comment by thegecko** [comment]
Not at the moment, please feel free to pick this up.
