### ISSUE TITLE
plugin with menu contribution doesn't build on windows cli

### ISSUE THREAD

**Issue by DoroNahari** [theia-ide/theia#4337]
I have a plugin with menu contribution. when i yarn it with windows cli it fails. (see log)
If i do yarn on linux/mac yarn success.
If i remove the contribution from package.json, yarn success on windows

Log:
Packaging of plugin
🔍 Validating...✔️
🗂  Getting dependencies...❌️
SyntaxError: Unexpected token o in JSON at position 76
    at JSON.parse (<anonymous>)
    at Yarn.<anonymous> (C:\Users\i348307\git\run-plugin\node_modules\@theia\plu
gin-packager\dist\yarn.js:61:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\i348307\git\run-plugin\node_modules\@theia\plugin-pac
kager\dist\yarn.js:13:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

https://github.com/DoroNahari/theia-run-plugin/tree/master/run-plugin
full log:
[yarn error.txt](https://github.com/theia-ide/theia/files/2864388/yarn.error.txt)

**Comment by kittaakos** [comment]
It seems to be a [@theia/plugin-packager](https://github.com/eclipse/theia-plugin-packager) issue. Can you please ask there?

**Comment by DoroNahari** [comment]
Issue solved with latest plugin packager version. Thanks
