### ISSUE TITLE
[plug-in] Implement 'WebviewPanel.reveal()'

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#4339]
[webviewPanel.reveal()](https://github.com/theia-ide/theia/blob/v0.3.19/packages/plugin-ext/src/main/browser/webviews-main.ts#L98) is not implemented at the moment. 
It would be very useful to have implemented this method and be better able to manage WebviewPanel.

**Comment by benoitf** [comment]
linking https://github.com/theia-ide/theia/issues/3896
