### ISSUE TITLE
[plug-in]  Ability to check whether the webview panel is active and visible

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#4342]
At the moment webview panel always returns 'true' for [properties](https://github.com/theia-ide/theia/blob/v0.3.19/packages/plugin/src/theia.d.ts#L2572-L2580).
I tested it for welcome-plugin, please see attachment:
![webview](https://user-images.githubusercontent.com/5676062/52795371-51eada80-307a-11e9-8243-dd128a2dc309.gif)

**Comment by RomanNikitenko** [comment]
linking #3896

**Comment by vparfonov** [comment]
will be fixed by https://github.com/theia-ide/theia/issues/3896

**Comment by akosyakov** [comment]
@RomanNikitenko @vparfonov can be closed by https://github.com/theia-ide/theia/pull/4892?

**Comment by RomanNikitenko** [comment]
I tested again and now it works fine for me!
@vparfonov I'm closing the issue.
