### ISSUE TITLE
[electron] Reloading the window or opening a new workspace crashes the app

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#4349]
When running the example electron application after a clean build, reloading the window kills the application.
The same is observed if a workspace is open while preserving the window (preferences - `workspace.preserveWindow`: true).

Tested on latest master (14th Feb 2019) with MacOS.

**Comment by thegecko** [comment]
Typically this doesn't break during debugging, only when started with `yarn start`

**Comment by thegecko** [comment]
Confirmed this only happens when opening or reloading a workspace with a space in the path.

It's due to the url encode/decode which happens when [storing the workspace URI in window.location.hash](https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/workspace-service.ts#L110)

**Comment by marechal-p** [comment]
Glad to know that I am not the only one having issues with that.

> Typically this doesn't break during debugging, only when started with `yarn start`

Yes, because when debugging, Theia is started in single process mode (`--no-cluster`). My guess was that it had to do with the way we managed the processes and windows somehow, but I never could debug this issue.

If you are in the same situation as me, the crash doesn't even output any errors, it just shutdowns for not apparent reason.

Hopefully you did find the root cause.

**Comment by thegecko** [comment]
Exactly what I see. This is quite a concerning issue for us as we keep the window while switching workspace.
I have a fix for reloading workspaces with a space in the path, but it didn't fix this.

I agree it's to do with clustering. It seems all workers stop during the reload so the app exits. 

Having to debug using console.log :)

**Comment by thegecko** [comment]
I've spent most of today trying to get to the bottom of this issue with no joy.

I've managed to debug the cluster fork, but can't see why the worker just decides to disconnect randomly during a reload. Some help would be appreciated.

**Comment by kittaakos** [comment]
Possible related: https://github.com/theia-ide/theia/issues/3242

**Comment by thegecko** [comment]
Yes, that's the same issue, but it also happens during a reload. Should we close this one?

My latest avenue of investigation for this was finding that closing the IPC connection will disconnect the worker process, which in turn stops the worker and the cluster;

https://nodejs.org/api/process.html#process_event_disconnect

https://github.com/nodejs/node/blob/62942e9ad7a59b76e9255ea2560bad2245709efc/lib/internal/cluster/child.js#L29

Can't prove that's what happens yet, though!

**Comment by thegecko** [comment]
cc @svenefftinge 

In the dev call today we discussed removal of cluster mode from Theia. If this is going to be the case, are you happy for me to create a PR now to turn off cluster mode by default?
