### ISSUE TITLE
[editor] enable `Code Editor` context menu item only for files

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#436]
`testEnabled` closure should be provided based on `opener.canHandle` for `WorkspaceCommands.FILE_OPEN_WITH` here:
https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/workspace-commands.ts#L95

After https://github.com/theia-ide/theia/issues/435 is fixed and `testEnabled` can handle `Promise`.

**Comment by akosyakov** [comment]
PRs are welcomed.

**Comment by kittaakos** [comment]
Closing in favor of https://github.com/theia-ide/theia/issues/1308.
