### ISSUE TITLE
Hosted Theia environment variables are not passed from host

### ISSUE THREAD

**Issue by idoprz** [theia-ide/theia#4362]
Running a host with the env THEIA_PLUGINS runs my plugin.
Running another plugin in hosted mode, has an empty THEIA_PLUGINS env.

**Comment by akosyakov** [comment]
@benoitf @evidolob could you help?

**Comment by amiramw** [comment]
This cleanup seems intentional:
https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/hosted/node/hosted-instance-manager.ts#L135-L136
However the THEIA_DEFAULT_PLUGINS env variable is preserved on host run.

**Comment by benoitf** [comment]
yes THEIA_PLUGINS are only for the instance , THEIA_DEFAULT_PLUGINS being for all instances
