### ISSUE TITLE
Incorrect hosted Theia URL

### ISSUE THREAD

**Issue by idoprz** [theia-ide/theia#4363]
The hosted Theia URL is taken from the --hostname paramter. Using --hostname 0.0.0.0 will open the hosted Theia tab in http://0.0.0.0:3000 which will not work.
This is also problem in a dockerized environment in which the host or port is mapped.

**Comment by akosyakov** [comment]
Right now the plug-in system read the address from the process which is internal thing. The real address on which Theia is exposed only available on the frontend via `Endpoint`.

**Comment by idoprz** [comment]
The suggested solution here and on #4011 will not work for us, as we are using path based routing. For example Theia will run under {myhost}/theia and the hosted Theia will be under {myhost}/port3030
So I think maybe there is a need for some configuration here.
@akosyakov  what do you think is the right way to handle this?

**Comment by akosyakov** [comment]
You need a proxy server for such configurations. It is not in the scope of Theia.

**Comment by benoitf** [comment]
hello @idoprz in Che we're overriding this exposed route so it's using the correct external endpoint. No need to have proxy server (but need to provide custom extension)

**Comment by idoprz** [comment]
> hello @idoprz in Che we're overriding this exposed route so it's using the correct external endpoint. No need to have proxy server (but need to provide custom extension)

I have a router component which route to it, so the route to the hosted Theia works. But it is path based. The only problem is that the opened tab in the browser is incorrect.
Do you suggest i will create a custom extension for opening the hosted Theia? shouldn't it be just a configuration to the existing extension?

**Comment by benoitf** [comment]
@idoprz 
maybe https://github.com/eclipse/che-theia-hosted-plugin-manager-extension/blob/master/src/node/che-workspace-hosted-plugin-uri-post-processor.ts#L38 is more helpful as answer.

**Comment by DoroNahari** [comment]
I Implement an extension like @benoitf referenced.
When running Hosted Plugin, Theia validate connectivity to the new tab's url
( https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/hosted/node/hosted-instance-manager.ts#L210 ).

In our landscape, user need to be authenticated and since the "ping" is in theia backend the authentication token is missing so the ping returns false and the tab isn't opening.

Maybe there should be a way to pass authentication token or cancel the ping execution?

**Comment by benoitf** [comment]
some hooks can be added in theia to add some headers (auth) to the request

**Comment by DoroNahari** [comment]
On second check, probably the authentication is not our problem. It is because we have a url redirect and the ping doesn't follow it.
@benoitf I think the ping should support redirecting, such that it will return true to a status code 302 or even to a range from 200 to 400.
Do you agree?

**Comment by benoitf** [comment]
@DoroNahari if there is a redirect it should probably follow the redirect and return true if redirect link is 200 not return true from 200 to 400.
Let say it's redirected to a URL that is not yet ready, returning true would lead to inconsistent state as well

**Comment by jgbradley1** [comment]
This is an issue outside of Theia's scope. An nginx configuration running outside of the docker container is one solution I would suggest looking into.

**Comment by DoroNahari** [comment]
After further investigation, the situation is that we have an external endpoint which is protected so either of the following 2 options could help:

1. Ability to ping local host and open the external url in a new tab.
1. Ability to pass auth header for the ping request.

Is it possible to contribute one these customization points to hosted-plugin flow.

**Comment by DoroNahari** [comment]
@benoitf Any thoughts?

**Comment by benoitf** [comment]
@DoroNahari I was on PTO last week

I would be in favor of option 2. In fact, before we had option 1 but we had an issue because for example in some K8S environment it is taking some time to make a route available (the external URL). So for example the local ping is immediate, then the user is redirected to a page saying that the route is not yet available so the UX is not good.

**Comment by DoroNahari** [comment]
@benoitf I created a PR as per your suggestion. It would be great if this could be reviewed quickly enough so it can get to the next version 🙏
