### ISSUE TITLE
how to add custom config in java language server

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4364]
i need add lombok
https://github.com/theia-ide/theia/blob/2d090d3836753ad21252147dfc6a5bb173b46ab6/packages/java/src/node/java-contribution.ts#L118-L122
`-javaagent:/home/theia/lib/lombok.jar`

**Comment by dneary** [comment]
Thanks for your question. @tsmaeder do you have any ideas?

**Comment by kittaakos** [comment]
Currently, it is not possible to achieve it without modifying the code. You can do at least two things:
 - You can subclass the `JavaContribution`, and more or less copy-paste the `start` method, adjust the JDT LS parameters in your code, and `rebind` the `JavaContribution` to your customized class.
 - You can make this configurable in Theia with a PR.

**Comment by tsmaeder** [comment]
the redhat.java extension already supports setting vm arguments in the preferences.

**Comment by akosyakov** [comment]
@502647092 a dup of https://github.com/theia-ide/theia/issues/2363 @502647092 Could you have a look into it?

**Comment by kittaakos** [comment]
I am closing this. It is tracked under #2363.
