### ISSUE TITLE
[git] Typo when pulling from/pushing to remote

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4365]
https://github.com/theia-ide/theia/blob/2d090d3836753ad21252147dfc6a5bb173b46ab6/packages/git/src/browser/git-quick-open-service.ts#L135

https://github.com/theia-ide/theia/blob/2d090d3836753ad21252147dfc6a5bb173b46ab6/packages/git/src/browser/git-quick-open-service.ts#L138

Should be `Successfully`.

**Comment by vinayb21** [comment]
PR for fix
https://github.com/theia-ide/theia/pull/4432

**Comment by kittaakos** [comment]
Closed via https://github.com/theia-ide/theia/commit/84284959a3c579f874831b5450e5858670aeee07
