### ISSUE TITLE
Research and discuss default keybindings for theia

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#438]
Some starting considerations:

  - We can't conflict with the browser's keybindings
  - Navigation should be consistent with readline
  - We don't have to copy anyone (vscode,atom,eclipse,emacs...)

**Comment by epatpol** [comment]
Do we try to keep the same combination of keybindings for both electron/browser versions? Or we go for two sets of keybindings. Althought maintaining one set is easier, I think sometimes you kinda expect shortcuts not to be the same when you're in a web application (i.e you know the browser already has some registered). In the case of a full desktop app (electron app), I don't really feel this way usually i.e I expect shortcuts to switch between tabs to be the same across *most* programs.

**Comment by hexa00** [comment]
I think we would have only 1 set otherwise it will be very confusing!

I guess a solution for the browser would be to have an escape mode a bit like vim mode where you could opt-in and out of having theia taking control of the browser keybindings ?

So like pressing Esc would give back control to the browser keybindings and clicking back in Theia or pressing Insert would give control back to Theia...

**Comment by svenefftinge** [comment]
Good idea, maybe a user preference would be sufficient to start with.

**Comment by svenefftinge** [comment]
We should use common shortcuts where they exist.

**Comment by hexa00** [comment]
@svenefftinge don't they always exist ? How would they not exist?

**Comment by svenefftinge** [comment]
I mean common shortcuts like [CTRL]+S for save should not be bound to something else even if it conflicts with a browser shortcut.

**Comment by hexa00** [comment]
OK so you mean 'common' as in usual shortcuts... not common to browser/electron.

So yes basically we should override the browser shortcuts and provide a way to get out of those kinda like being in a VM and using an escape sequence to get out.

**Comment by hexa00** [comment]
I'm closing this and we can discuss more specific issues as they appear
