### ISSUE TITLE
how to get the example run with customized pathname ?

### ISSUE THREAD

**Issue by frankLife** [theia-ide/theia#4384]
I found the front of example app only can be visited with root `/` pathname. when use pathname like `/theia` , it would spin all the time without any error.

![image](https://user-images.githubusercontent.com/5081884/53065108-462d6700-3505-11e9-9214-9fdb011937c5.png)

may I need more config ?

@akosyakov

**Comment by kittaakos** [comment]
> I found the front of example app only can be visited with root `/` pathname. when use pathname like `/theia` ,

@frankLife, what did you do? Did you build it from the source? Are you developing your own extension? Did it happen with Docker? Some additional input might help to solve your problem.

> it would spin all the time without any error.

Can you please check again both the backend logs and the browser's console.

**Comment by frankLife** [comment]
@kittaakos I just build own theia version without docker.  I  debug and found the 

```
this.initialized = this.workspaceService.roots.then(function (roots) {
            _this.prefix = _this.getPrefix(roots[0]);
        });
```

the `then` will not reach when use customized pathname

@kittaakos can you give us some more information about this

**Comment by frankLife** [comment]
my fault , sorry
