### ISSUE TITLE
Fix child loggers leaking 

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#439]
Currently the child loggers (started with logger.child{Options} are leaking.

Because:
  - ` loggerWatcher.onLogLevelChanged(event => {` sets a reference to the logger that is never cleaned-up
 - There's nothing to clean up the client logger on the loggerserver

So we need to make the child loggers disposable and add proper methods in the loggerserver to clean them up there also.

**Comment by akosyakov** [comment]
btw I don't see that Bunyan has API to dispose loggers.

**Comment by hexa00** [comment]
Not sure it needs one but yes something to validate...

**Comment by hexa00** [comment]
Close these one are now singletons See #519
