### ISSUE TITLE
[git] no matching bindings found for serviceIdentifier: Symbol(GitInit)

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4391]
After #4210, the following error is thrown:
`No matching bindings found for serviceIdentifier: Symbol(GitInit)`

It is most likely a cleanup issue.

**Comment by kittaakos** [comment]
@vince-fugnitto, where is the fix? I am trying to figure out what is causing #4395?

**Comment by vince-fugnitto** [comment]
@kittaakos I got this issue because I hadn't cleaned my repo when I pulled your changes, after performing a git clean and pull the problem went away so I closed my issue, it was a mistake on my part initially.

**Comment by kittaakos** [comment]
Thanks for your prompt reply!
