### ISSUE TITLE
Three little doubts

### ISSUE THREAD

**Issue by Rolige** [theia-ide/theia#4393]
Hi,

1. In the own IDE, how I can change the default command of `yarn theia start`?, and being a little more specific, I'm interested in use the custom command of `yarn theia start /my-workspace --hostname 0.0.0.0 --port 8080`, eg. if I execute `yarn theia start` I want to get the result of the command `yarn theia start /my-workspace --hostname 0.0.0.0 --port 8080`, I can't find the source code to change it.
2. Is there a way to stop an execution with a `yarn` or `bash` command?, I know we can't stop it with `CTRL+C` but I need stop it from another instance, is there a way?
3. Is there a way to stopping automatically an execution when the browser is closed?

Thanks in advance and great job, let me tell you that we have been testing a lot of similar apps, but this is amazing!

Regards!

**Comment by marechal-p** [comment]
>     1. In the own IDE, how I can change the default command of `yarn theia start`?, and being a little more specific, I'm interested in use the custom command of `yarn theia start /my-workspace --hostname 0.0.0.0 --port 8080`, eg. if I execute `yarn theia start` I want to get the result of the command `yarn theia start /my-workspace --hostname 0.0.0.0 --port 8080`, I can't find the source code to change it.

https://github.com/theia-ide/theia/blob/master/packages/core/src/node/backend-application.ts#L41-L42

Basically defaults in case you don't specify the command line arguments.

On the other hand, `yarn theia start` is a bit magical, as it comes from `yarn`, trying to find a script named `theia` in `package.json`, but fails, then looks into `node_modules/.bin` and finds it and executes it.

I usually use `yarn start`, which finds the `start` script defined in `examples/browser/package.json` in the main repo, but maybe this script is not defined in your application `package.json`.

Either way, you could add a script in your `package.json` like I mentioned that would do exactly what you want: `"your_start": "yarn theia start /my-workspace --hostname 0.0.0.0 --port 8080"`.

>     2. Is there a way to stop an execution with a `yarn` or `bash` command?, I know we can't stop it with `CTRL+C` but I need stop it from another instance, is there a way?

Well, given the focus is set to the Theia backend process when you run it, `Ctrl+C` is about the only way to stop the program. But in a nutshell you can fetch the PID of Theia's backend ([on start](https://unix.stackexchange.com/a/257012) or by looking up using `htop` or anything similar).

Then `kill -SIGINT <pid>`, which is basically the equivalent of doing `Ctrl+C`.

I think some teams are running Theia in a container and simply shut it down when required, one backend per container, so no issue with programmatically finding the right pid.

>     3. Is there a way to stopping automatically an execution when the browser is closed?

Not that I know of, directly, but I guess one could look around in the sources and find a way to list opened websocket connections, and try to react based on client inactivity time. Don't just shutdown right when you see 0 clients, as the client will not be connected when you will first boot the backend :)

**Comment by Rolige** [comment]
@marechal-p thanks a lot, I have now some ideas.

Regards!
