### ISSUE TITLE
[proposal][git] Remove the `dugite` dependency

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4401]
- We do not ship the executables anyway.

   - Yes, one can argue that the Git executable download script could be useful. I would recommend setting up Git once correctly on the environment, instead of downloading it per Theia backends. We should disable the Git UI is Git is not on the `PATH`.

 - No i18n support for the Git error parsing.

   - We cannot pars the `liegt außerhalb des Repositories` error message with the  [`fatal: .+: '(.+)' is outside repository`](https://github.com/desktop/dugite/blob/89a31870593bfb37673b003788f25093d136f9d6/lib/errors.ts#L104) regular expression. It means, we do not handle the expected errors correctly. We would be complete if each git command would be prefixed with `LC_ALL=C`. (cc: @AlexTugarev)

 - No wildcard expansion support: https://github.com/theia-ide/theia/issues/1564.

   - We cannot do `git check-ignore *` because the wildcards are not expanded by `dugite`.

- We could get rid of the env variables for
  - `--no-optional-locks`, and
  - the external Git path.

Thoughts?

----
Related: https://github.com/theia-ide/theia/pull/4400

**Comment by gorkem** [comment]
What exactly is the proposal here?

**Comment by svenefftinge** [comment]
> What exactly is the proposal here?

to remove the dugite library completely.

**Comment by sunix** [comment]
> > What exactly is the proposal here?
> 
> to remove the dugite library completely.

Just dugite or the entire the Theia git extension ? (to be replaced with the VSCode extension)

**Comment by svenefftinge** [comment]
This issue is just about removing the dugite library

**Comment by sunix** [comment]
We would need to replace it with something else right ?

**Comment by gorkem** [comment]
@svenefftinge Is there a second proposal to add something else that I am missing?

**Comment by kittaakos** [comment]
It seems we can live with `dugite`. I am closing this, please reopen if required.
