### ISSUE TITLE
[siw] Search in workspace is not deterministic when the results exceed the threshold

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4416]
I got back different hit counts for the same query term. See attached screencast.
I set the inclusion pattern, after hitting `Esc` I got back different result numbers. It is clear, we limit the search to 2k result items by default, but as a user, I expect to have the same result for the same search.

![screencast 2019-02-25 08-55-31](https://user-images.githubusercontent.com/1405703/53322458-c1af5f80-38db-11e9-8d36-b3fcfc61f2e1.gif)

**Comment by kittaakos** [comment]
[minor] Also, I would like to see the inclusion pattern even if the warning is there. Currently, the validation message overlays it.

**Comment by vince-fugnitto** [comment]
> [minor] Also, I would like to see the inclusion pattern even if the warning is there. Currently, the validation message overlays it.

The message behaviour is also present in `vscode` when the search input has focus, the message will overlay but disappears when focus is lost.

**Comment by vince-fugnitto** [comment]
Also is it a dup of https://github.com/theia-ide/theia/issues/4113?

**Comment by kittaakos** [comment]
Duplicate of #4113.
