### ISSUE TITLE
[Plug-in] Dynamic commands getting undefined

### ISSUE THREAD

**Issue by invincibleJai** [theia-ide/theia#4424]
I was trying to test https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics in theia and I observed one of the commands being defined in LS [1] and works fine in VSCode for applying QuickFixes gets undefined here. As in below screenshots.

<img width="829" alt="screenshot 2019-02-26 at 2 27 23 pm" src="https://user-images.githubusercontent.com/5129024/53400302-8f812900-39d3-11e9-80bc-0256cad63a14.png">

[1] https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/blob/master/src/consumers.ts#L154

Am not sure what could be the reason for failure here.

**Comment by benoitf** [comment]
hello @invincibleJai could you specify on which version of theia you've this issue as well ?

**Comment by invincibleJai** [comment]
@benoitf am using image `theiaide/theia-full:next` 

https://github.com/redhat-developer/vscode-openshift-tools/wiki/Testing

**Comment by invincibleJai** [comment]
@akosyakov i think it's working fine, thanks for help.
