### ISSUE TITLE
terminal exit problem

### ISSUE THREAD

**Issue by bj-white** [theia-ide/theia#4431]
Hello,
I edited a text in terminal, but I couldn't exit through ":wq".
How do I save it?
Thanks.

**Comment by svenefftinge** [comment]
You mean you used vim? It usually works like that when you are not in editing mode.
Could you be more specific?

**Comment by bj-white** [comment]
no, not vim, "vim: command not found".
Only "vi" can be used.
But,When I use vi, I can't save and quit.
How do you edit a file with vi?

**Comment by AndrienkoAleksandr** [comment]
> How do you edit a file with vi?

@bj-white When vim is opened, I can click on `Insert` to activate edit mode. When I applied changes in the editor, I press `Shift + :`, then type vim command `wq` - it's mean write(save) and quite(exit).

**Comment by bj-white** [comment]
@AndrienkoAleksandr Yes, it's in the shell. However, in theia-ide, it is not possible. You can try "theia-ide".

**Comment by AndrienkoAleksandr** [comment]
@bj-white , OK in the `insert mode` of the vi  ->  click `Esc` key on the keyboard(to exit from insert mode), and then 'Shift + :' => should appear command input in the bottom of the editor, type `wq + Enter`.

**Comment by bj-white** [comment]
@AndrienkoAleksandr I'm an Operations and Maintenance Personnel, and I'm very familiar with these commands, but they don't work in theia-ide.

**Comment by bj-white** [comment]
@AndrienkoAleksandr Oh, I see. Not good for Google, but good for Firefox.

It's a browser compatibility problem.

Can you try it on Google? Tell me the result?
Thanks.

**Comment by akosyakov** [comment]
@bj-white Do you mean Chrome? I cannot reproduce it with latest Chrome which version do you use?

**Comment by bj-white** [comment]
@akosyakov Yes, you can't use Google either?
My Google version is 68.0.3440.106

**Comment by akosyakov** [comment]
My is Version 72.0.3626.119 (Official Build) (64-bit). Could you update to latest and try again?

**Comment by AndrienkoAleksandr** [comment]
I have Chrome Version 72.0.3626.119 (Official Build) (64-bit) too. And vi works fine

**Comment by marcdumais-work** [comment]
@bj-white Which language and keyboard layout are you using? Do I guess correctly that you are running one of our Docker images from [here](https://hub.docker.com/u/theiaide), rather than building from the sources of this repo here? If so which one?

**Comment by bj-white** [comment]
@akosyakov @AndrienkoAleksandr @marcdumais Updated, it can be used. Thank you.
