### ISSUE TITLE
yarn run rebuild:electron && rebuild:browser do not work consistently

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#445]
See #79

>The rebuild does not seem to work, I can see something is happening when either invoking yarn run >rebuild:browser or yarn run rebuild:electron but I have the same error in both cases.

**Comment by MarkZ3** [comment]
Happened to me too a couple of days ago.

**Comment by vince-fugnitto** [comment]
Closing for the moment, the `rebuild:browser` and `rebuild:electron` scripts work fine.
We can re-open if the issue ever returns.

**Comment by gbodeen** [comment]
The issue has returned in Theia 0.13.0.

**Comment by vince-fugnitto** [comment]
> The issue has returned in Theia 0.13.0.

Can you please describe your issue and steps to reproduce?
