### ISSUE TITLE
[tree] Provide support for multi-selections

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#447]
- [ ] the tree selection service should be improved to support additional selections https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-selection.ts#L68
- [ ] the tree widget should add additional selection on the click https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-widget.ts#L262

**Comment by kittaakos** [comment]
I am merging this to #20.
