### ISSUE TITLE
Go to definition and outline doesn't work in cpp code

### ISSUE THREAD

**Issue by yeonggyulim** [theia-ide/theia#4470]
### Description

Go to definition and outline work in java, but they don't in cpp code even if I installed cpp and textmate packages. Anyone knows why?

### Reproduction Steps

![image](https://user-images.githubusercontent.com/36085009/53706200-6ac20100-3e6c-11e9-80c5-c2da6a2fbd82.png)
![image](https://user-images.githubusercontent.com/36085009/53706235-87f6cf80-3e6c-11e9-9d44-28c95f725c6a.png)

**OS and Theia version:**
Windows 10
@theia/java : ^0.3.19
@theia/cpp: ^0.3.19
@theia/textmate-grammars: ^0.3.19

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
Do you have the cpp language server installed ? You can find information in the `@theia/cpp` readme. 
Theia uses `clangd` to enable LSP features for cpp.

**Comment by yeonggyulim** [comment]
> Do you have the cpp language server installed ? You can find information in the `@theia/cpp` readme.
> Theia uses `clangd` to enable LSP features for cpp.

I installed `clangd`  through LLVM and make the path in `C:\Program Fiels\LLVM\bin`.
However, I still see this error and LSP features don't work. Do you know why?

![image](https://user-images.githubusercontent.com/36085009/53713525-86d69a00-3e8e-11e9-8ccc-957ed3f5cec1.png)

**Comment by vince-fugnitto** [comment]
You can try specifying the location of your `clangd` using the following preference:
https://github.com/theia-ide/theia/blob/e1b5a60f0841f8edf1d8d60d99012e996fc145bc/packages/cpp/src/browser/cpp-preferences.ts#L56

**Comment by yeonggyulim** [comment]
> You can try specifying the location of your `clangd` using the following preference:
> [theia/packages/cpp/src/browser/cpp-preferences.ts](https://github.com/theia-ide/theia/blob/e1b5a60f0841f8edf1d8d60d99012e996fc145bc/packages/cpp/src/browser/cpp-preferences.ts#L56)
> 
> Line 56 in [e1b5a60](/theia-ide/theia/commit/e1b5a60f0841f8edf1d8d60d99012e996fc145bc)
> 
>  description: 'Specify the executable name/path to run in order to start clangd.',

Is this what you mean?
![image](https://user-images.githubusercontent.com/36085009/53782896-c9fa4100-3f52-11e9-84d6-f1b88bce52bc.png)

but, how can I compile this to bundle?
there's no tsconfig.json file and it goes away whenever I build with yarn.

![image](https://user-images.githubusercontent.com/36085009/53783163-ddf27280-3f53-11e9-845d-433e2ad7b6b0.png)
I installed @thiea/cpp package and clangd, but I can't figure out what to do next.

**Comment by vince-fugnitto** [comment]
@yeonggyulim with clangd installed and the path referenced through the preference, were you able to benefit from cpp language support? (go to definition, hover...)

> but, how can I compile this to bundle?
> there's no tsconfig.json file and it goes away whenever I build with yarn.

I'm not quite sure what you mean, can you clarify what are you looking to accomplish?

**Comment by yeonggyulim** [comment]
> @yeonggyulim with clangd installed and the path referenced through the preference, were you able to benefit from cpp language support? (go to definition, hover...)

No, I edited preference like this, but still see the same error.
![image](https://user-images.githubusercontent.com/36085009/53851362-d2f61b80-4001-11e9-82af-ea79beaf929b.png)

> 
> > but, how can I compile this to bundle?
> > there's no tsconfig.json file and it goes away whenever I build with yarn.
> 
> I'm not quite sure what you mean, can you clarify what are you looking to accomplish?

I was confused. never mind with this question.

How should I handle this process Error?
![image](https://user-images.githubusercontent.com/36085009/53851426-020c8d00-4002-11e9-8df1-068c72bd0109.png)

Do you have any idea?

**Comment by yeonggyulim** [comment]
I found the problem.

It works after downloading `clangd`.
The problem I was suffering is it works on windows command prompt, but it doesn't with terminal on visual studio code.

Thank you for your help.
