### ISSUE TITLE
API to capture file modifications for plugins/extensions?

### ISSUE THREAD

**Issue by bdeleonardis1** [theia-ide/theia#4471]
### Description
I am trying to build a plugin or an extension for Theia that needs to get file modifications. Is there a way to write an event listener so that for every update to the document I can run a function? For example, if the user inserts the letter 'a' at the beginning of the document, my function:

`documentUpdate(operation='insert', character='a', position=0)` will get called.

**Comment by akosyakov** [comment]
You can subscribe to any document change with https://github.com/theia-ide/theia/blob/30298afd51ca8e61075c5879d9b2c1c57669d583/packages/monaco/src/browser/monaco-workspace.ts#L65

You will to derive semantic of operation (insert, remove) though from range and text changes.

**Comment by akosyakov** [comment]
The previous comment is for Theia extensions, for plugins: https://github.com/Microsoft/vscode/blob/e96ab81392ec49effa0369f4f086be8c128e5e2f/src/vs/vscode.d.ts#L7614

**Comment by bdeleonardis1** [comment]
Thanks for the help, I figured out how to get it working.

**Comment by deepakdahal** [comment]
@bdeleonardis1 just started looking into theia and came across this page. I am looking for a similar functionality. Basically be able to capture file modification/buttons clicked etc. Is there a plugin/extension out there that already does this? Any help would be much appreciated, thank you.
