### ISSUE TITLE
Add keymapsjson to WorkSpace Config

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4473]
### Description
Add keymapsjson to WorkSpace Config

**Comment by vince-fugnitto** [comment]
@502647092 can you clarify what you mean by this issue?

**Comment by akosyakov** [comment]
Thought it is related to https://github.com/theia-ide/theia/issues/4475, but i don't see that VS code exposes it via workspace configs.

**Comment by 502647092** [comment]
i deploy theia on docker when i update app the keymap need relpace
maybe i should mount volume /home/theia/.theia on host machine?

**Comment by akosyakov** [comment]
yes, if you want to share user settings you need to mount them into user home directory of your docker container.

**Comment by 502647092** [comment]
Thanks
