### ISSUE TITLE
Communication via JSON-RPC doesn't work in my extension

### ISSUE THREAD

**Issue by jonghuyn** [theia-ide/theia#4479]
### Description
I tried to make server side extension to do communicate via JSON-RPC between server and client 
But It doesn't work let me know why It doesn't work 

### Reproduction Steps
Backand Container Module
![image](https://user-images.githubusercontent.com/14925542/53783391-bb148e00-3f54-11e9-99a1-e08f7ada053d.png)
FrontEnd Container Module
![image](https://user-images.githubusercontent.com/14925542/53783507-2cecd780-3f55-11e9-89d6-36e3d2c01028.png)

And I made protocal interface like logger
![image](https://user-images.githubusercontent.com/14925542/53783521-455cf200-3f55-11e9-9a5b-85860166ba89.png)

![image](https://user-images.githubusercontent.com/14925542/53783536-54dc3b00-3f55-11e9-93d9-f9fcb129b9da.png)

**OS and Theia version:**
Windows 10
Theia version : latest (I'am using all of latest extension version in theia app)
**Diagnostics:**

**Comment by akosyakov** [comment]
It's unrelated to JSON-RPC. You never bind `TopBuildCommandHandler` symbol, but reference it in [toService](https://github.com/inversify/InversifyJS/blob/master/wiki/transitive_bindings.md)

**Comment by jonghuyn** [comment]
thank you
