### ISSUE TITLE
[tree] create tests for ITreeModel

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#448]
All methods of [ITreeModel](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-model.ts#L21) should be tested with pure Node.js tests according to https://github.com/theia-ide/theia/blob/master/doc/Testing.md.

**Comment by akosyakov** [comment]
PRs are welcomed. There is no need to test all at once, the first PR can provide coverage only for [ITree](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree.ts#L16).

**Comment by theBadT** [comment]
I'm currently working on implementing the tests. Since I'm coming from Java, .NET I'm rather new to typescript. Is it possible to check whether or not a particular call has been executed by a mock?

**Comment by akosyakov** [comment]
>  Is it possible to check whether or not a particular call has been executed by a mock?

Such tests should be written against  [TreeModel](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/tree/tree-model.ts) API, not checking implementation, i.e. mutate something and then use getter to check state.

**Comment by vince-fugnitto** [comment]
closed thanks to #4628 :+1:
