### ISSUE TITLE
How to run excutable jar file in theia extension???

### ISSUE THREAD

**Issue by jonghuyn** [theia-ide/theia#4481]
### Description

I tried to run excutable jar file in theia extension like on node.js server but I couldn't do Anyone know how???

### Reproduction Steps

**OS and Theia version:**
Windows 10
all of theia extension's version is latest
**Diagnostics:**

**Comment by akosyakov** [comment]
You should use [child_process](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) node.js module. Google for how run java from node.js.
