### ISSUE TITLE
Remove sourcing the .profile when starting a term

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#449]
When starting a terminal we always do:

```
term.write(`cd ${uri.path} && `);
term.write("source ~/.profile\n");
```

This makes no sense on linux and even less on windows. So we need to remove it for those for sure.

And it seems like an ugly hack for macOS, it's even worse that the user sees that displayed when starting a term.

@kittaakos  @akosyakov do you object to remove that entirely ? 
I remember discussing that with @svenefftinge for macOS but forgot what the issue was exactly on osx... but it seems like it should be fixed another way.

**Comment by svenefftinge** [comment]
It would be good though to figure out how to initialize the shell properly on the different systems.

**Comment by hexa00** [comment]
@svenefftinge maybe it's just my linux experience talking but why would the shell need external help to initialize ?
Isn't it responsible for it's own init ?

On linux running bash or zsh or whatever is a self-contained operation... is it not on mac ?

**Comment by hexa00** [comment]
Does it work with vscode for you ?
Feels like your init is not in the right file..

**Comment by svenefftinge** [comment]
Yes, it works nicely there.

**Comment by hexa00** [comment]
@svenefftinge ok good to know.

Here's what I plan to do:

- I'll see if I can use an env var for the root dir
 - And I will remove the .profile sourcing for now 

And we need to figure out a better way for macOS, I don't see anything obvious from vscode code but we should investigate more, I don't have a mac to test however :( 

WDYT?

**Comment by svenefftinge** [comment]
Yes, please remove it. I will check and if it still is bad for me, we can look what vscode does differently.
