### ISSUE TITLE
Speed up CI by dropping some configs on PRs (Node 6 / 7)

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#451]
Since macOS increased our CI build time it takes a long time to build all configurations with the max 4 builds we get on travis.

I would like to drop node 6 to remove 2 jobs and keep macOS

I think we could make it so that we ship node in our packging too so for the end users that would not be an issue, and for the devs it's easy to upgrade usually

**Comment by hexa00** [comment]
We could have a cron for it too just in case like once a day or something

**Comment by hexa00** [comment]
Basically to speed this up we have to choose what to run on all PRs and what to run nightly.

I suggest we run on all PRs:

Node 8 on Linux, Mac, Windows

Nightly:
Node 7 and Node 6 on all platforms.

Sounds OK ?

**Comment by akosyakov** [comment]
I think node 6 is most popular version right now, node 7 was never released.

**Comment by hexa00** [comment]
From gitter:
```

Antoine Tremblay @hexa00 09:01
how about we use node 8 linux/mac and keep node 6 once per day in a cron just in case ?
so we'll spot it if we have a problem
but won't be slowed down
￼
Anton Kosyakov @akosyakov 09:02
ok, let’s try it
```

**Comment by hexa00** [comment]
See https://www.infoq.com/news/2017/06/node-8-released-lts

Node 8 should be our baseline maybe for a 1.0 in Q1/Q2 2018?
