### ISSUE TITLE
Idea: Vue support

### ISSUE THREAD

**Issue by sh7dm** [theia-ide/theia#4513]
### Description
Support Vue.

### Reproduction Steps
1. Open any `.vue` file
2. ![default](https://user-images.githubusercontent.com/19504461/54037672-c2939b80-41cf-11e9-976e-2ee26ef58aa1.png)

**OS and Theia version:**
Theia v0.4.0, Ubuntu 18.04

**Diagnostics:** 
None

**Comment by vince-fugnitto** [comment]
@sh7dm you can perhaps try the following extension and raise any issues you may find :)
https://github.com/Devpodio/theia-vue-extension

**Comment by vince-fugnitto** [comment]
@sh7dm just wondering, were you able to get the `Vue` support you were looking for ? :)

**Comment by sh7dm** [comment]
@vince-fugnitto will try!

**Comment by sh7dm** [comment]
@vince-fugnitto Yes! Now I've got nice syntax highlight! Thanks
![изображение](https://user-images.githubusercontent.com/19504461/54124502-a08a5b00-4413-11e9-8027-1c2222718429.png)

**Comment by vince-fugnitto** [comment]
@sh7dm great! I'm glad to hear, is it fine if I close the issue? :)
