### ISSUE TITLE
Task widget should has Task title, not terminal.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [theia-ide/theia#4523]
### Description
Task widget should has Task title, not terminal.

### Reproduction Steps
1. Create new task
2. Launch this task: Terminal => Run Task => Select created task from the list and type enter
3. Take a look on the widget title.

Screen-cast:
![TaskTitle](https://user-images.githubusercontent.com/6873095/54123119-906c7e80-4407-11e9-8598-93674cfe86cb.gif)

**OS and Theia version:**
0.4.0.

**Comment by vince-fugnitto** [comment]
Closed by #5270
