### ISSUE TITLE
supporting on vscode plugin in menus setting is not stable

### ISSUE THREAD

**Issue by ouyangxizi** [theia-ide/theia#4529]
### Description
I write a vscode plugin to support a function that could add two commands when right click different  types files. It works very well in vscode, but not work in theia extension. The question is in vscode I set different "when" labels to add the different types of buttons, but the "when" labels work disorderly,it confused. By the way, the event I set is to click the button I add to open a url, it totally doesn't work in theia extension.

### Reproduction Steps
1.add some codes in package.json (add some labels i.e "menus" "when")
2. pack up as a .vsix
3.add the .vsix in plugins directory
4.run 

**OS and Theia version:**
1.The newest theia master branch codes
2.Docker version 1.12.6

**Diagnostics:** 
I wonder whether the support in vscode plugins could work better in theia extension.

**Comment by akosyakov** [comment]
@ouyangxizi Could you provide a VS Code extension to reproduce?

**Comment by ouyangxizi** [comment]
> @ouyangxizi Could you provide a VS Code extension to reproduce?
The main codes I add in package.json are below:
`"menus":{
    "explorer/context":[
    {
        "when":"resourceExtname == .bpm",
        "command":"extension.bpm"
    },
   {
        "when":"resourceExtname == .yaml",
        "command":"extension.yaml"
   }
]
}
`
I'd like to right click bpm file and there will be added a button, and right click yaml file and there will be added a button different with the previous button. But in theia extension the two buttons appear disorderly. I wonder the "when" label is not stable in theia?

**Comment by akosyakov** [comment]
@ouyangxizi it should be stable, maybe a bug. Which version of Theia do you use?

**Comment by ouyangxizi** [comment]
> @ouyangxizi it should be stable, maybe a bug. Which version of Theia do you use?

@akosyakov 
I use the newest master branch theia, compile the source code and make a image in docker.

**Comment by akosyakov** [comment]
> It means I write codes to implement a function that click a button then there will open a website in default browser. But it doesn't work in theia when work perfectly in vscode.

Could you provide an implementation please?

**Comment by ouyangxizi** [comment]
@akosyakov 
The codes below is the main function I write to open a uri in default browser. 
`export const openDefault = (path: any): void =>{
    let uri = "http://xx.xxxx.com/xxx/xxx.html";
    const browser = standardizedBrowserName(defaultBrowser());
    open(uri, browser);
};`
Thanks for your quick response~

**Comment by akosyakov** [comment]
And you running Theia in electron right? For browser I doubt it can work, extensions are running on the backend.

**Comment by ouyangxizi** [comment]
> And you running Theia in electron right? For browser I doubt it can work, extensions are running on the backend.
@akosyakov 
Do you mean that the way to add .vsix in plugins directory  only could run in the backend? If it is, I will consider another way to implement the OpenInDefaultBrowser function.

**Comment by benoitf** [comment]
@ouyangxizi 
You can open url by doing
```typescript
vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://theia-ide.org'))
```

with new ongoing API it should be possible to do
```typescript
vscode.env.openExternal(vscode.Uri.parse('https://theia-ide.org''));
```

**Comment by akosyakov** [comment]
VS Code extensions needs access to backend tools like nodejs. You can try to use vscode.open command instread and pass http url.

**Comment by ouyangxizi** [comment]
> @ouyangxizi
> You can open url by doing
> 
> ```ts
> vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://theia-ide.org'))
> ```
> 
> with new ongoing API it should be possible to do
> 
> ```ts
> vscode.env.openExternal(vscode.Uri.parse('https://theia-ide.org'))
> ```

Appreciate for your advice,it's worked for me.

**Comment by ouyangxizi** [comment]
> @ouyangxizi
> You can open url by doing
> 
> ```ts
> vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://theia-ide.org'))
> ```
> 
> with new ongoing API it should be possible to do
> 
> ```ts
> vscode.env.openExternal(vscode.Uri.parse('https://theia-ide.org'))
> ```

@benoitf 
I test it in vscode, it's worked for me. But back up as a .vsix in theia, The function jumping to the url doesn't happen in theia. I wonder where should I put these codes? 
How can I add a event that could click a button and jump to another tab in theia?
Thanks for your help!

**Comment by ouyangxizi** [comment]
> VS Code extensions needs access to backend tools like nodejs. You can try to use vscode.open command instread and pass http url.

@akosyakov 
Hi~One more question waiting for your help!
I found mini-browser in theia, that's exactly what I want in theia to open a url. How can I call the mini-browser API in vscode extension? I have read a lot of documents and discusses in Spectrum, still cannot solve this problem.
Using the codes below, cannot open url in theia:
```vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://theia-ide.org'));```
Looking forward for your help!
