### ISSUE TITLE
[open file][find command] Unexpected search results

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#4537]
If the search string is matched, I'd expect there would be no substring search results included.

![2019-03-12 17 07 28](https://user-images.githubusercontent.com/914497/54216260-a05c8f00-44e9-11e9-8a93-724d678004e7.gif)

![2019-03-12 17 06 40](https://user-images.githubusercontent.com/914497/54216296-ad797e00-44e9-11e9-9e41-5449a713e421.gif)

/cc. @akosyakov

**Comment by akosyakov** [comment]
Maybe related https://github.com/theia-ide/theia/issues/4508

**Comment by akosyakov** [comment]
We enable separate substring matching by default. Looking at clients it is not really good default. I would like to make it configurable and disable by default. Objections?

**Comment by akosyakov** [comment]
And there is apparently a race in quick file, looking into it as well.

**Comment by akosyakov** [comment]
The file search also returns unrelated results:
<img width="652" alt="Screen Shot 2019-03-13 at 09 08 17" src="https://user-images.githubusercontent.com/3082655/54262839-97ae9c00-456f-11e9-84a8-7596dbf5ecf5.png">
