### ISSUE TITLE
[workspace] add support for VersionedTextDocumentIdentifier 

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#4538]
`MonacoWorkspace#applyEdit()` should take versioned text documents into account, and not apply them when they differ in version.

This is especially valuable for non-monaco editors, e.g. diagrams, that are modified using LSP. Currently, we can have all kinds of races between the calculation of a change (e.g. rename or code action) and other user input. When applying the changes, the document may have a completely different state.

**Comment by akosyakov** [comment]
fixed by https://github.com/theia-ide/theia/pull/4553
