### ISSUE TITLE
Theia explorer context menu missing resource context for vscode extension

### ISSUE THREAD

**Issue by dehru** [theia-ide/theia#4539]
### Description
I've got a vscode extension that generates menu items from a "right-click" on the file explorer.  And depending on the context of the right click ( if it's a specifically named folder or a file ), it behaves differently.  In theia, the context items that it keys off of are always undefined.

I have a vsix that shows this behavior, linked below.

### Reproduction Steps
1. Download and run the vsix ( committed to this repo ) [https://github.com/dehru/vscode-explorer-context-extension](https://github.com/dehru/vscode-explorer-context-extension)
2. Download and use theia ide on this simple workspace [https://github.com/dehru/right-click-test-project](https://github.com/dehru/right-click-test-project)
3. Right Click ( Context Menu ) in the file explorer on the hello.js, world.js, and helloworld directory of the test project above
4. The context menu ( right click or option click ) does not show the expected menu items as expressed in the contributions property of the package.json

**OS and Theia version:**
MacOS 10.13.6, vscode@1.1.26, theia 0.4.0 ( and 0.3.19 ) 
 
**Diagnostics:** 
Vscode plugin contributions from package.json 
[https://github.com/dehru/vscode-explorer-context-extension/blob/master/package.json](https://github.com/dehru/vscode-explorer-context-extension/blob/master/package.json)

**Excerpt from package.json**:
```
"explorer/context": [
	{
		"command": "extension.hello",
		"when": "resourceFilename == hello.js"
	},
	{
		"command": "extension.world",
		"when": "resourceFilename == world.js"
	},
	{
		"command": "extension.helloWorld",
		"when": "explorerResourceIsFolder && resourceFilename == helloworld"
	}
],
```

When the menu is built in theia, the context is missing the resourceFilename ( undefined ), which is present in vscode as the item clicked on in the explorer.  I believe here is where the when statements are compared to the keyContext.  [ Link to monaco-context-key-service.ts](https://github.com/theia-ide/theia/blob/763ca8b4e1c3d1ce477efe79cea238c693b586dc/packages/monaco/src/browser/monaco-context-key-service.ts#L39)

**Vscode context in explorer when context-menu is folder:**
```
"explorerResourceIsFolder":true,
"resourceScheme":"file",
"resourceFilename":"helloworld",
"resourceLangId":null,
"resourceExtname":"",
```

**Theia context in explorer when context-menu is folder:**
```
"explorerResourceIsFolder":true,
"resourceScheme":undefined,
"resourceFilename":undefined,
"resourceExtname":undefined,
"resourceLangId":undefined
```

The vscode documentation on resource contexts:
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

### Sample Projects Used to Discover This Issue ###

Sample vscode extension:
[https://github.com/dehru/vscode-explorer-context-extension](https://github.com/dehru/vscode-explorer-context-extension)

Sample workspace:
[https://github.com/dehru/right-click-test-project](https://github.com/dehru/right-click-test-project)

**Comment by akosyakov** [comment]
@dehru thanks for the reporting 👍
