### ISSUE TITLE
Design a Theia logo

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#454]
I think we do not have a logo yet.

**Comment by JanKoehnlein** [comment]
If you consider a greek letter, please take a theta not a tau.

Von meinem iPhone gesendet

**Comment by myckyc** [comment]
Hey guys!

Here is some of my quick sketches and thoughts behind them. 
Let me know what you think about it. 

![theia-sketch-01](https://user-images.githubusercontent.com/13270017/30372195-bf537d22-9885-11e7-9cb1-ae376fcbf0de.jpg)

![theia-sketch-02](https://user-images.githubusercontent.com/13270017/30372194-bf5230fc-9885-11e7-8b76-df7f6d073bce.jpg)

---

![theia-explanation](https://user-images.githubusercontent.com/13270017/30372220-cae00cb4-9885-11e7-8501-7cee96bdf30d.png)

![theia-logo-work-01](https://user-images.githubusercontent.com/13270017/30372441-7716ea16-9886-11e7-91cb-378e029d10f7.png)

![theia-logo-work-02](https://user-images.githubusercontent.com/13270017/30372442-7718e492-9886-11e7-9e69-f32f8a437e6d.png)

**Comment by myckyc** [comment]
If you want to play with that, source file can be found here:
https://drive.google.com/open?id=0B8_5BZdVxA1ca21kVGx1VnRNZEE

**Comment by lmcbout** [comment]
Looking at the logo, the asteroid followed by some code, the third from the top in the list of 
https://drive.google.com/open?id=0B8_5BZdVxA1ca21kVGx1VnRNZEE
- My suggestion: we should be able to find the letter "T" in the trailing part of the asteroid. I would ease to think of the name "Theia"
Second, we should put some degrading colour in front of the asteroid, from orange to yellow, something like that.

**Comment by svenefftinge** [comment]
Awesome! I really like your proposals.
I like this one the most:
<img width="791" alt="screen shot 2017-09-13 at 13 28 10" src="https://user-images.githubusercontent.com/372735/30375060-7b2a0204-9887-11e7-90d6-ec83c0f4f905.png">

The icon is a good middle ground of the others. I also like the font being a bit software with the rounded edges.

**Comment by Nebiroth** [comment]
Looks good. Personally I think it might be better if there were a bit less spacing between the letters.

**Comment by myckyc** [comment]
Hey! Thanks for the feedback. 

@svenefftinge @Nebiroth The fonts are just for test reasons. That's why they wasn't included into my first post. I like how symbol works with the PF BeauSans Pro (it's on the pic posted by @svenefftinge ) but we can't use it because of it's commercial nature.

@lmcbout Not sure about including T into the asteroid's trail. But I will give it a try little bit later.

**Comment by MarkZ3** [comment]
> Awesome! I really like your proposals.
> I like this one the most:

I like it too! It might be a challenge to make some smaller icons out of it though. I think native apps need 16x16 (all the way to 512x512@2x).

**Comment by myckyc** [comment]
Hey @MarkZ3!
I believe we shouldn't worry too much about the small icons like 16x16 because they aren't really popular nowadays (only used for favicons in some cases). And we also can make a special version for this case.

Also current version of the symbol can be converted to 16px size with pretty good legibility. Here is my quick test with our "work in progress" version:
![theia-icon-test](https://user-images.githubusercontent.com/13270017/30430726-cf1b5830-9964-11e7-91d8-d8db44e22aab.png)

It's not antialiased at all in pure pixel art fashion.

**Comment by hexa00** [comment]
+1 for the color version :)

**Comment by MarkZ3** [comment]
> It's not antialiased at all in pure pixel art fashion.

Looks pretty good!

**Comment by svenefftinge** [comment]
Hey @myckyc, we really like your proposal and would like to use it. 
Are you ok with the apache license and could you provide a vector version of it?

**Comment by svenefftinge** [comment]
Would be awesome if you could provide it in both color and black/white

**Comment by myckyc** [comment]
@svenefftinge Hey! I'm sorry for this long pause. I've got buried under my day job tasks and deadlines. I will fix some technical and geometrical nuances and will upload new version in couple next days. Including vector files, color/bw versions and other stuff that you may need.

And I'm ok with Apache license.

**Comment by akosyakov** [comment]
@myckycI just wanted to clarify you are going to the same document on gdrive?

**Comment by marcdumais-work** [comment]
Hi @myckyc . Would it be possible to get an svg version of the logo above? (https://github.com/theia-ide/theia/issues/454#issuecomment-329139350)? Even if you are not done with a more final version, that would still help us. 

Also, could you submit it as a pull request on this repo?

**Comment by JanKoehnlein** [comment]
I've converted the ai file and cleaned it up a bit. 

[theia-logo.pdf](https://github.com/theia-ide/theia/files/1730772/theia-logo.pdf)
