### ISSUE TITLE
[Type Hierarchy] Support servers that want to compute the type hierarchy eagerly

### ISSUE THREAD

**Issue by HighCommander4** [theia-ide/theia#4540]
The current implementation of Type Hierarchy appears to always ask for one level of the hierarchy at a time, and ignore additional levels even if the server chooses to send them.

I think it would be good to support language servers that want to compute the type hierarchy eagerly. Specifically, if the server sends more levels than requested, Theia should make use of the levels that were actually sent.

(For some context, I'm working on an [implementation for the C++ language server](https://reviews.llvm.org/D56370). There, at least for parents, the marginal cost of computing the entire parent hierarchy compared to just one level is negligible, while the cost of computing each level in a separate request is a lot higher. Therefore, we return the entire parent hierarchy in response to `textDocument/typeHierarchy`, and do not support `typeHierarchy/resolve` for parents. However, with the current Theia implementation, Theia will only display one level of the hierarchy.)

@kittaakos @marcdumais-work

**Comment by kittaakos** [comment]
Nice to see other LSs implementing the `textDocument/typeHierarchy` feature👍.

@HighCommander4, please note, the current implementation in Theia, complies the LSP proposal specified here: https://github.com/Microsoft/vscode-languageserver-node/pull/426
And the lazy resolution was a requirement, see [here](
https://github.com/Microsoft/vscode-languageserver-node/pull/346#issuecomment-440283344). Long story short, I am not planning to change the Theia implementation unless we have some feedback on the proposal. However, I am happy to extract

https://github.com/theia-ide/theia/blob/c12f14ecca696ec91ccd29d5870602dfd282c3e6/packages/typehierarchy/src/browser/tree/typehierarchy-tree-model.ts#L50

into a method, and you can rebind the tree for your C++ implementation, where you can use `Number.MAX_SAFE_INTEGER` if you want.

If do you want to not customize the Theia implementation in the long run, you should raise your concerns on the specification and not here.

**Comment by kadircet** [comment]
Similar concerns are actually raised in spec, see:
https://github.com/Microsoft/vscode-languageserver-node/pull/426#discussion_r255414744
https://github.com/Microsoft/vscode-languageserver-node/pull/426#discussion_r255416980

**Comment by HighCommander4** [comment]
What is the downside of accepting extra levels, if the server has already sent them? The client is literally throwing away work that's already done.

**Comment by HighCommander4** [comment]
To be clear, the extent of the changes I'm proposing is this: https://github.com/theia-ide/theia/pull/4574

**Comment by kittaakos** [comment]
> To be clear, the extent of the changes I'm proposing is this: #4574

I won't hold your proposal back, it is in proposal state anyway.

> What is the downside of accepting extra levels, if the server has already sent them? The client is literally throwing away work that's already done.

Why do not you cache it on the server?

**Comment by HighCommander4** [comment]
> > To be clear, the extent of the changes I'm proposing is this: #4574
> 
> I won't hold your proposal back, it is in proposal state anyway.

Thank you :)

> > What is the downside of accepting extra levels, if the server has already sent them? The client is literally throwing away work that's already done.
> 
> Why do not you cache it on the server?

A couple of reasons:

 * It's not immediately clear what an appropriate key would be for the cache lookup.
    * The location (file/line/column) can change between requests due to editing.
    * The type name may not be unique across the workspace, even if it's fully-qualified. For example, you may have two different projects in the workspace, each building a separate executable, and each defining a type of the same name in the global namespace (or another common namespace).
 * Caching introduces additional complexity on the server side, as we now need logic to trigger clearing the cache from time to time (we can't have it grow indefinitely).

**Comment by kadircet** [comment]
In addition to the reasons @HighCommander4 provided, one thing that comes to my mind is:
Caching implies you'll have stale data, and to get rid of that staleness you will need to introduce additional logic.
