### ISSUE TITLE
Swift Language Support using Sourcekit-LSP

### ISSUE THREAD

**Issue by funcsatish** [theia-ide/theia#4543]
### Description
Sourcekit-LSP : [https://github.com/apple/sourcekit-lsp](https://github.com/apple/sourcekit-lsp)

How do i convert Sourcekit-LSP VSCode Extension to **Theia Swift Extension** 

Example code extension
```ts
import * as vscode from 'vscode';
import * as langclient from 'vscode-languageclient';

export function activate(context: vscode.ExtensionContext) {

    const config = vscode.workspace.getConfiguration('sourcekit-lsp');

    const sourcekit: langclient.Executable = {
        command: config.get<string>('serverPath', 'sourcekit-lsp'),
        args: []
    };

    const toolchain = config.get<string>('toolchainPath', '');
    if (toolchain) {
        sourcekit.options = { env: { ...process.env, SOURCEKIT_TOOLCHAIN_PATH: toolchain } };
    }

    const serverOptions: langclient.ServerOptions = sourcekit;

    let clientOptions: langclient.LanguageClientOptions = {
        documentSelector: [
            'swift',
            'cpp',
            'c',
            'objective-c',
            'objective-cpp'
        ],
        synchronize: undefined
    };

    const client = new langclient.LanguageClient('sourcekit-lsp', 'SourceKit Language Server', serverOptions, clientOptions);

    context.subscriptions.push(client.start());

    console.log('SourceKit-LSP is now active!');
}
```

**Comment by akosyakov** [comment]
You don't do it, but just deploy VS Code extension: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions and let us know if something does not work

**Comment by satishbabariya** [comment]
Yeah, you can found it here [https://github.com/apple/sourcekit-lsp/tree/master/Editors/vscode](https://github.com/apple/sourcekit-lsp/tree/master/Editors/vscode)
Though the extension is not available in VS Code Marketplace currently.

**Comment by akosyakov** [comment]
Loading from source supported as well, just put VS Cod extension under `plugins`. If does not work let me know.

**Comment by satishbabariya** [comment]
okay sure.

**Comment by funcsatish** [comment]
![Screen Shot 2019-03-14 at 3 12 45 PM](https://user-images.githubusercontent.com/39147630/54346791-b5f9c200-466b-11e9-84be-950012354e1d.png)
Is it possible to configure Plugins like this, or I need to edit extension which doesn't use any user-defined configs?
![Screen Shot 2019-03-14 at 3 14 37 PM](https://user-images.githubusercontent.com/39147630/54346919-eb9eab00-466b-11e9-8e75-a79dc62b492c.png)

**Comment by akosyakov** [comment]
Do you mean there Theia support user/workspace settings? Sorry, i did not really get the question.

**Comment by funcsatish** [comment]
In Sourcekit-LSP VSCode Extension currently, two configurations required,
![Screen Shot 2019-03-14 at 5 05 34 PM](https://user-images.githubusercontent.com/39147630/54354175-ff520d80-467b-11e9-81f1-7954e446a16f.png)

1. Server Path
2. Swift Toolchain Path

Can we configure Plugins in theia?

for testing purpose, i did set up both parameters static values and tested vscode extension with theia, using plugin folder and it works.

**Comment by akosyakov** [comment]
<img width="552" alt="Screen Shot 2019-03-14 at 13 58 25" src="https://user-images.githubusercontent.com/3082655/54358726-572f4b00-4661-11e9-8edb-a601108273c8.png">
Did you check preferences? They should be there.

**Comment by akosyakov** [comment]
@funcsatish do you have swift open-source project which you expect to work with this extension? that we can test as well

**Comment by funcsatish** [comment]
okay thanks, I'll check.

**Comment by funcsatish** [comment]
https://github.com/theia-ide/theia/issues/4543#issuecomment-472862566 currently sourcekit-lsp is in developement mode , and not use in production. so after release of sourcekit you can use any  open-source project avaiable on github.

**Comment by funcsatish** [comment]
also you have any example of dockerfile having plugins ?

**Comment by akosyakov** [comment]
Copy vsix files in some image folder and then use `THEIA_DEFAULT_PLUGINS=local-dir:path` ENV variable to point to it like here: https://github.com/theia-ide/theia-apps/pull/146/files#diff-ffce79e1eb9166eb9dfd79628eb80ca0R72

**Comment by akosyakov** [comment]
> #4543 (comment) currently sourcekit-lsp is in developement mode , and not use in production. so after release of sourcekit you can use any open-source project avaiable on github.

yeah, i am just not an expert, thought maybe you have some good demo example

**Comment by funcsatish** [comment]
you can use any of the one example here https://github.com/raywenderlich/swift-algorithm-club
also i'm currently working on implementing theia-swift-docker, when it's complete and tested, i'll do pr on it.
