### ISSUE TITLE
[typehierarchy][keybinding] Fix the keybinding collision

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4558]
```
logger-protocol.ts:112 root WARN Collided keybinding is ignored;  {"command":"typehierarchy:toggle","keybinding":"ctrlcmd+alt+a"}  collided with  {"command":"core.previousTab","keybinding":"ctrlcmd+alt+a"}
```

Pick any other reasonable, unused keybinding for the view.

**Comment by vince-fugnitto** [comment]
For new contributors, this occurs when we have two `keybinding` which collide with each-other (attempt to use the same keybinding for different actions)

An example implementation would be to check the codebase for any unused keyboard shortcuts, and/or use the `keyboard shortcuts` widget directly in Theia to search. What's important to note is also we should not add shortcut which may be reserved by the operating system or even browser.

If any help is required, feel free to always ask :)

**Comment by theBadT** [comment]
ctrlcmd+shift+h, where h stands for hierarchy, does the trick?

**Comment by kittaakos** [comment]
Closed via https://github.com/theia-ide/theia/pull/4682
