### ISSUE TITLE
[quality] The default resource resolver should reject with an error instead of a string

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4560]
https://github.com/theia-ide/theia/blob/01a983076976a3c18f54ad507abaf2df174ccd43/packages/core/src/common/resource.ts#L115

**Comment by kittaakos** [comment]
There are other flawed rejects in the code. Therefore, the acceptance criteria of this issue is:
 - search for:
   - `.reject('`
   - `.reject("`
   - <code>.reject(`</code>
 - and replacec the strings with an `Error`.

**Comment by theBadT** [comment]
Within this particular file, I could find only a single flawed reject. Throughout the whole code base however, there were several. The scope of this is issue is limited to https://github.com/theia-ide/theia/blob/01a983076976a3c18f54ad507abaf2df174ccd43/packages/core/src/common/resource.ts#L115 or shall the rejects on a global scale be adapted?
