### ISSUE TITLE
The intelephense PHP extension requires VS Code support to be at least of v.1.31.0

### ISSUE THREAD

**Issue by vrubezhny** [theia-ide/theia#4578]
### Description
It is impossible to install `intelephense` extension as Theia extension plugin because it requires VS Code v. >= `1.31.0`, while we declare it to be `1.27.2` in `plugin-ext-vscode. (I'm not sure on all the consequences, but the `intelephense` extension was satisfied when I applied the following simple fix that just changes the declared VS Code version to be `1.31.0`:
```
$ git diff packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts
diff --git a/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts b/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts
index 1e017b9f..55381bf9 100644
--- a/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts
+++ b/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts
@@ -72,7 +72,7 @@ export const doInitialization: BackendInitializationFn = (apiFactory: PluginAPIF
     };
 
     // override the version for vscode to be a VSCode version
-    (<any>vscode).version = '1.27.2';
+    (<any>vscode).version = '1.31.0';
```

Reference issues:
https://github.com/eclipse/che/issues/12796
https://github.com/eclipse/che/issues/12797

**Comment by tsmaeder** [comment]
See also https://github.com/theia-ide/theia/issues/4124

**Comment by tsmaeder** [comment]
@vrubezhny is there an older version of the plugin that would work with 1.27.2?

**Comment by vrubezhny** [comment]
Closing the issue as vscode supported version is updated by resolving https://github.com/theia-ide/theia/issues/4124
