### ISSUE TITLE
[key] Rename modifiers

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#458]
Rename:
- [ ] `Modifier` -> `KeyModifier`
- [ ] `M1` -> `CtrlCmd`
- [ ] `M2` -> `Shift`
- [ ] `M3` -> `Alt`
- [ ] `M4` -> `MacCtrl`

**Comment by svenefftinge** [comment]
Could be solved by using a library like mousetrap. See #472

**Comment by hexa00** [comment]
Like said in #472 I think it's a bad idea to use mousetrap for that, I don't think we want to externalise key event handling to external code.

We can look for inspiration from it however...
