### ISSUE TITLE
[plugin] Add PHP grammar contributions

### ISSUE THREAD

**Issue by vrubezhny** [theia-ide/theia#4582]
PHP grammar contributions are must be added to Theia for PHP Language
    
The CQ [1], [2] needs to be resolved before merging a fix for this issue
Need to remove the similar contribution from PHP extension [3]
    
[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19282
[2] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19509
[3] https://github.com/theia-ide/theia-php-extension

Reference issues:
https://github.com/eclipse/che/issues/12796
https://github.com/eclipse/che/issues/12797

**Comment by akosyakov** [comment]
I would really recommend to consider using builtin vscode extensions instead of textmate-grammars extension. They contain snippets, some default language specific editor settings and so on.

**Comment by vrubezhny** [comment]
> I would really recommend to consider using builtin vscode extensions instead of textmate-grammars extension. They contain snippets, some default language specific editor settings and so on.

@akosyakov The grammars & snippets referenced in CQ (and those I'm going to propose for inclusion to Theia) are taken directly from  VS Code: https://github.com/Microsoft/vscode/tree/master/extensions/php - are they what do you mean?

**Comment by akosyakov** [comment]
textmate-grammars Theia extension does not have anything except textmate grammars as far as i know. VS Code built-in extensions are more than that.

**Comment by vrubezhny** [comment]
Yet another CQ is opened for the issue: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19509
