### ISSUE TITLE
Terminal: copy & paste inconsistent

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#460]
It seems that one can copy from an external source and paste in Theia's terminal, with the expected result. 

However, in the other direction, there are issues.  When selecting text in the terminal and attempting to copy it using the browser's context menu, it doesn't work as well. At times, some text is copied, but it's not exactly what's selected in the terminal, at other times, even if some text is selected, the copy action is not enabled. 

Might be related to: https://github.com/theia-ide/theia/issues/31

**Comment by akosyakov** [comment]
Could be a bug in xterm?

**Comment by akosyakov** [comment]
There is already the copy listener in xterm, it seems to misbehave:
https://github.com/sourcelair/xterm.js/blob/7645bdd418b37a8bd176a69179c06178c8cb1130/src/handlers/Clipboard.ts#L34-L39

One should investigate and file a bug there, don't think anything can be done about it in Theia.

> at other times, even if some text is selected, the copy action is not enabled.

It should be fixed in the master, the copy command is always enabled.

**Comment by marcdumais-work** [comment]
thanks for the hint @akosyakov, I'll look into this

**Comment by marcdumais-work** [comment]
Hummm.  Debugging the xterm.js code, I see that our selections always seem to be offset by a constant factor of [+2, +1] (i.e. the selection starts and ends 2 columns right, one line down, compared to what it should be). This seems to match the fact that we (PhosphorJS?) add a margin of one char at the top and two on the left side of the terminal. 

When I try the xterm.js example, there is no such offset, and the selection works as expected.

**Comment by marcdumais-work** [comment]
If I remove the padding in terminal.css, the selection works correctly:

.terminal .xterm-rows {
    padding-top: 0 !important;
    padding-left: 0 !important;
}

**Comment by marcdumais-work** [comment]
playing around with the CSS, I think I found a way to keep that padding that doesn't interfere with the selection. See updated patch

**Comment by marcdumais-work** [comment]
So, to recap: it seems that when we try to copy from the terminal, what gets copied is not exactly what is selected. Instead the start and end points of the selection are shifted one line down and 2 columns right, which results in the copy feature not copying what is selected and expected. 
![peek 2017-09-07 13-06](https://user-images.githubusercontent.com/25749063/30175666-6ea6a910-93cd-11e7-8fc3-7bb19a4fee30.gif)

The "offset" between what's selected and copied corresponds to the padding that is added to the "xterm-rows" elements, in terminal.css. This padding adds a bit of space between the terminal and it's containing widget, such that the terminal's text is not directly at the window boundary. I first noticed that when the padding is removed, the copy copies exactly what is selected. 

By experimenting, I have discovered that adding the padding on the container element , "terminal-container" instead of element "xterm-rows", results in the same layout visually, but does not seem cause the issue described above. 
![peek 2017-09-07 13-12](https://user-images.githubusercontent.com/25749063/30175874-522b1cc0-93ce-11e7-8666-bfe178091b9e.gif)

**Comment by marcdumais-work** [comment]
My guess is that xterm.js does not take padding added to individual terminal rows into account, when mapping between the mouse position to the terminal text's, resulting in the wrong text being selected. However it does seems to take padding into account when it's added to the container.
