### ISSUE TITLE
[views] Provide into Application Shell correct active widget in complex views

### ISSUE THREAD

**Issue by vzhukovskii** [theia-ide/theia#4623]
### Description
There is a problem, when we have a complex contribution view with several widgets, for example with trees. There are situations, when we need to check current active widget in Application Shell to setup correct selection in Selection Service. So there is a need to place into Application Shell not a `ViewsContainerWidget` but active tree widget.

<img width="1149" alt="theia — Theia Browser Example 2019-03-20 15-57-49" src="https://user-images.githubusercontent.com/1968177/54690584-65320f80-4b2a-11e9-9158-df0e4f6dc240.png">

**Comment by akosyakov** [comment]
@vzhukovskii For now, you can also try to use `document.activeElement` to check focus, i.e. `this.node.contains(document.activeElement)`.

**Comment by vzhukovskii** [comment]
Wow! Didn't know about this approach. Big thanks!

**Comment by vzhukovskii** [comment]
Issue become not actual at this moment. Going to close it.
