### ISSUE TITLE
[terminal] wrapping problem

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#463]
When the terminal window is wide enough, there still seems to be a ~80 chars limit, when typing, before the wrap-around kicks-in, but without echoing a carriage return, so it starts to overwrite the beginning of the line. 

Once the enter key is pressed, the "proper" line is outputted, using the full width of the terminal, containing the whole command, as typed.

**Comment by marcdumais-work** [comment]
![peek 2017-09-06 14-22](https://user-images.githubusercontent.com/25749063/30127946-f2b13c4e-930e-11e7-8142-0f6eb79e2f45.gif)

**Comment by rahulgupta-acquia** [comment]
we are facing same issue , when trying to open new terminal programatically.

**Comment by marcdumais-work** [comment]
@rahulgupta-acquia This issue is pretty old - I will suggest you open a fresh one and add the relevant information, like the version of Theia you use and how exactly you attempt to open the terminal.
