### ISSUE TITLE
debug console does not have a title icon

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4638]
The `debug console` widget does not have a title **icon**.

<div align='center'>

![Screenshot from 2019-03-21 07-03-53](https://user-images.githubusercontent.com/40359487/54748308-a1578580-4ba7-11e9-8588-ea7f4362f55a.png)

</div>

**Comment by akosyakov** [comment]
Which icon would you use?

**Comment by vince-fugnitto** [comment]
> Which icon would you use?

I'm not quite sure, I can look into an appropriate icon, the only one I can think of at the moment is the same as the terminal

**Comment by vince-fugnitto** [comment]
@akosyakov something similar to this if I can create or find an appropriate version.

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/54754827-dde0ac80-4bba-11e9-8704-0d8f07018eff.png)


</div>

**Comment by akosyakov** [comment]
@vince-fugnitto right, we can just adjust existing VS Code icon:

<img width="35" alt="Screen Shot 2019-03-21 at 15 00 04" src="https://user-images.githubusercontent.com/3082655/54757218-0fbd3780-4bea-11e9-80c4-d957aef46e8b.png">

good idea Could you do it?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto right, we can just adjust existing VS Code icon:
> 
> <img alt="Screen Shot 2019-03-21 at 15 00 04" width="35" src="https://user-images.githubusercontent.com/3082655/54757218-0fbd3780-4bea-11e9-80c4-d957aef46e8b.png">
> 
> good idea Could you do it?

do you have any idea where that icon is located? :see_no_evil:

**Comment by vince-fugnitto** [comment]
@akosyakov nevermind I found it ! https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/media/repl.svg
