### ISSUE TITLE
Add eclipse eca validation check

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4641]
I propose we add the [Eclipse ECA Validation](https://github.com/apps/eclipse-eca-validation) check to our main repo for pull requests. This will save a lot of manual time where we need to check if the author's ECA is completed and up to date. With Theia's growing popularity it will become more manageable to have the automated check :smile: 

I added it to my Theia fork and tested the results:
- Correct ECA (valid email): https://github.com/vince-fugnitto/theia/pull/9
- Incorrect ECA (invalid email): https://github.com/vince-fugnitto/theia/pull/10

We already use the ECA validation check in other repos such as `sprotty` and `theia-cpp-extension` to name a few.

@marcdumais-work @svenefftinge @akosyakov @benoitf

**Comment by marcdumais-work** [comment]
This would be nice. @vince-fugnitto it looks like we could remove the `DCO` check too, since the `ECA` one also checks that commits are signed?

**Comment by marcdumais-work** [comment]
BTW this change would be done by changing the GH repo config, not through a PR. (since not all repos in the `theia-ide` org are "eclipse" repos, we probably do not want this done at that level?)

**Comment by vince-fugnitto** [comment]
> This would be nice. @vince-fugnitto it looks like we could remove the `DCO` check too, since the `ECA` one also checks that commits are signed?

The tool specifies that it includes `validation of “Signed-off-by” footers in commit messages for non-committers`. Would that be enough for committers for example to verify they have "Signed Off by"? Else, I don't it think it does any harm to also include the `DCO`.

> BTW this change would be done by changing the GH repo config, not through a PR. (since not all repos in the `theia-ide` org are "eclipse" repos, we probably do not want this done at that level?)

Yes exactly, its achieved by enabling the tool in the repository not through a PR. Perhaps solely including the check for the main repository would be enough at the moment?

**Comment by marcdumais-work** [comment]
@vince-fugnitto ok, so let's add the `ECA` check, for this repo only.  But we'll leave the `DCO` check in place too, for now.

**Comment by marcdumais-work** [comment]
Done. I posted on `spectrum` about it.
