### ISSUE TITLE
[Java] Clicking on Code Lense `▶ Run` doesn't open the Debug Console

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia#4648]
### Description

Clicking on the Code Lense `▶ Run` link doesn't automatically open the Debug Console.

### Reproduction Steps

1. Open [this Java file](https://github.com/Snailclimb/JavaGuide/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/source%20code/securityAlgorithm/src/main/java/com/snailclimb/ks/securityAlgorithm/RSADemo.java) in Theia (e.g. [via Gitpod](https://gitpod.io/#https://github.com/Snailclimb/JavaGuide/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/source%20code/securityAlgorithm/src/main/java/com/snailclimb/ks/securityAlgorithm/RSADemo.java))
2. Click on `▶ Run` above `public static void main(String[] args)`
3. A new `Debug` side panel appears (but doesn't open automatically)
4. No Debug Console appears, so you're left wondering whether Theia is doing anything after you clicked

If you open that file in VS Code (and wait for the LS to download the world) and click on `Run`, it automatically opens a Debug Console.

In Theia, I can click on the `Debug` side panel, and then on the small Terminal icon to open the Debug Console (which has the output I was interested in, but it's hidden behind too many steps).

It would be nice to automatically open the Debug Console when you click on `▶ Run`.

**OS and Theia version:** Mac OS, latest Theia in gitpod.io

**Diagnostics:**

**Comment by jankeromnes** [comment]
A few helpful pointers from @akosyakov to debug this issue (thanks Anton!):

> yes, sounds like a bug in Theia extension for java
it should add a property to open debug console to a debug configuration

https://github.com/theia-ide/theia/blob/7552e80b5dfb14d0fc4c6d14d771e7e1f6cdd31b/packages/java-debug/src/browser/java-debug-frontend-contribution.ts#L196-L207

> debug config is constructed here
you can check how it is different from vscode java extension
i think there should be some propery

> try `internalConsoleOptions`: `openOnSessionStart`
https://code.visualstudio.com/updates/May_2016#_control-opening-the-debug-console

**Comment by jankeromnes** [comment]
So, it seems that if not specified by the project, Theia sets `internalConsoleOptions` to `neverOpen` by default:

https://github.com/theia-ide/theia/blob/7e8b91090338ae7a71cd30f5dbc0a25774cc72bd/packages/debug/src/common/debug-configuration.ts#L63-L64

However, VS Code uses `openOnFirstSessionStart` by default:

https://github.com/Microsoft/vscode/blob/eeaf5d876e20884b05932988be04a8089297d07e/src/vs/workbench/contrib/debug/common/debug.ts#L60-L64

I believe we should align the default value.

**Comment by akosyakov** [comment]
@jankeromnes sounds good

**Comment by jankeromnes** [comment]
Erm, so Theia does have the correct default value in _two_ places:

https://github.com/theia-ide/theia/blob/7e8b91090338ae7a71cd30f5dbc0a25774cc72bd/packages/debug/src/node/vscode/vscode-debug-adapter-contribution.ts#L31-L35

https://github.com/theia-ide/theia/blob/7e8b91090338ae7a71cd30f5dbc0a25774cc72bd/packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts#L66-L70

But neither seems to be honored.

**Comment by jankeromnes** [comment]
After doing some more digging, it seems that default configurations are provided by debug adapters, and the `java-debug-adapter-contribution`:

https://github.com/theia-ide/theia/blob/002093674328d4a1647dc262199244c6627a693d/packages/java-debug/src/node/java-debug-adapter-contribution.ts#L93-L120

doesn't seem to care about the default values in the schema attributes for debug type `java`:

https://github.com/theia-ide/theia/blob/7e8b91090338ae7a71cd30f5dbc0a25774cc72bd/packages/debug/src/browser/debug-schema-updater.ts#L37-L61

Maybe it should?

**Comment by jankeromnes** [comment]
So, anyone can start a Theia debug session by calling:

https://github.com/theia-ide/theia/blob/002093674328d4a1647dc262199244c6627a693d/packages/debug/src/browser/debug-session-manager.ts#L127-L131

You can currently call this with an incomplete `options.configuration` (as Java Code Lense does).

Then, I think `this.resolveConfiguration(options)` will call `PluginDebugService.resolveDebugConfiguration(options)` and/or `DebugAdapterContributionRegistry.resolveDebugConfiguration(options)`:

https://github.com/theia-ide/theia/blob/002093674328d4a1647dc262199244c6627a693d/packages/plugin-ext/src/main/browser/debug/plugin-debug-service.ts#L104-L113

https://github.com/theia-ide/theia/blob/002093674328d4a1647dc262199244c6627a693d/packages/debug/src/node/debug-adapter-contribution-registry.ts#L99-L116

Neither plugin debug contributions nor debug adapter contributions seem to care about the default values in:

https://github.com/theia-ide/theia/blob/002093674328d4a1647dc262199244c6627a693d/packages/debug/src/browser/debug-schema-updater.ts#L40-L56

My question is: Who should care about these default values, and add them to the debug configurations?

I think plugins should be allowed to omit some configuration values, so default values should be enforced with low priority by some common debug contribution (or directly by the `start` function before `this.resolveConfiguration(options)`).
