### ISSUE TITLE
https://github.com/theia-ide/theia/pull/4600 has broken icon of webview 

### ISSUE THREAD

**Issue by benoitf** [theia-ide/theia#4664]
### Description
There is now a white background behing the webview's icon tab after https://github.com/theia-ide/theia/pull/4600 changes

### Reproduction Steps
Use a webview with icon

**OS and Theia version:**

**Diagnostics:**

**Comment by jbicker** [comment]
Sorry, I don't know how to get a webview tab.
Could you please give a more detailed explanation how to reproduce it?

**Comment by benoitf** [comment]
sure, np

**Comment by benoitf** [comment]
@jbicker I modified the cat coding webview example of vscode https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample

I made a binary there
https://github.com/benoitf/webview-demo/releases/tag/0.0.1

let say `$THEIA_HOME` is where you cloned theia:

copy the vsix file to `THEIA_HOME/plugins' and then yarn run start from THEIA_HOME/examples/browser

Bring command palette and search for 'start cat coding session'

you'll see a square white icon while the real icon is just behind.

**Comment by benoitf** [comment]
![cat](https://user-images.githubusercontent.com/436777/54829535-e8806c00-4cb6-11e9-8ed1-e3a844b012a3.gif)
