### ISSUE TITLE
double click on widget title to bring it in full window mode

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4668]
I would like to do it sometimes, i.e. to see full terminal output. Probably in this case double clicking again should restore the original layout.

**Comment by simark** [comment]
Eclipse does that, it's super useful.

**Comment by akosyakov** [comment]
tried to implement it with just adjusting css styles and asking the area to fit its children:
![fullscreen](https://user-images.githubusercontent.com/3082655/55090135-dcc5e880-50ae-11e9-9c2e-f2acd3f8cffd.gif)

It needs some styling but could work like that. The drawbacks: (1) you don't see menu and status bars and (2) it does not work for side-bars nicely. But maybe it is not a big issue.

**Comment by akosyakov** [comment]
You can play with that in this PR: https://github.com/theia-ide/theia/pull/4744
