### ISSUE TITLE
[ui/ux] better tab alignment

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4669]
The tabbars alignment looks a little off in my opinion. 
I noticed that:
1. there isn't uniform top and bottom padding so the tabs look off (more bottom padding).
2. there isn't adequate space between the tab icons and tab labels.
3. the tab icons are not aligned with the center of the tabs.
4. the styling overall can be greatly approved like vscode, since at the moment it is a little eyesore. 

**theia** 

<div align='center'>

<img width="751" alt="Screen Shot 2019-03-22 at 9 06 11 AM" src="https://user-images.githubusercontent.com/40359487/54824817-62e2c900-4c82-11e9-8b82-9827c84aad62.png">

</div>

**vscode**

<div align='center'>

<img width="722" alt="Screen Shot 2019-03-22 at 9 12 32 AM" src="https://user-images.githubusercontent.com/40359487/54824905-a5a4a100-4c82-11e9-8514-244a21da1d40.png">

</div>

**Comment by svenefftinge** [comment]
I adjusted the tabs in https://github.com/theia-ide/theia/pull/4670 please have a look

**Comment by vince-fugnitto** [comment]
closed thanks to #4670
