### ISSUE TITLE
golang def error

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4687]
### Description
![image](https://user-images.githubusercontent.com/10203793/54895920-d6900a80-4efc-11e9-9e10-6b45cc0c78b6.png)

### Reproduction Steps
```go
package main

import (
	"context"
	"fmt"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
)

func main() {
	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	services, err := cli.ServiceList(context.Background(), types.ServiceListOptions{})
	for _, service := range services {
		fmt.Printf("%s %s %t\n", service.ID[:10], service.Spec.Name, service.Spec.Mode.Global != nil)
	}
}
```

Press down Ctrl and Click `NewEnvClient`

**OS and Theia version:**
latest next docker version
theiaide/theia-go:next

**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 I cannot reproduce it on master step.

Could you explain how do you create a project? I've added `main.go` file in $GOPATH and then did `go get` to pull `api/types` and `client` dependencies. After that navigation works. Could it be that you are missing dependencies? Or you project is not in $GOPATH?

**Comment by 502647092** [comment]
not in gopath
use gomodules
