### ISSUE TITLE
tab icons not shown correctly

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4691]
### Description
![image](https://user-images.githubusercontent.com/10203793/54913760-70bc7680-4f2e-11e9-9757-e0ce8cb521fd.png)
![image](https://user-images.githubusercontent.com/10203793/54913789-8762cd80-4f2e-11e9-953c-37332d31e5a1.png)

### Reproduction Steps

**OS and Theia version:**
latest next docker version
theiaide/theia-full:next

**Diagnostics:** 
maybe need remove margin-bottom on `.p-TabBar[data-orientation='horizontal'] .fa.p-TabBar-tabIcon`
![image](https://user-images.githubusercontent.com/10203793/54913850-a6615f80-4f2e-11e9-8efe-213587915f75.png)
![image](https://user-images.githubusercontent.com/10203793/54913858-aa8d7d00-4f2e-11e9-9d0a-3fc62c8af105.png)

**Comment by vince-fugnitto** [comment]
the same also occurs for files without any extension.
![Screenshot from 2019-03-25 07-00-13](https://user-images.githubusercontent.com/40359487/54914666-d7f50f00-4ecb-11e9-99e0-cd4f8c3b8200.png)

**Comment by vince-fugnitto** [comment]
other errors occur when moving widgets into the `main-panel`.
there is no icon, and the spacing is off.

![Screenshot from 2019-03-25 07-03-47](https://user-images.githubusercontent.com/40359487/54914839-4e920c80-4ecc-11e9-86d1-46c994c96110.png)

@svenefftinge they are a result of the changes introduced from #4670

**Comment by vince-fugnitto** [comment]
solved with the following changes introduced in #4690
