### ISSUE TITLE
[tree] Scrolling in any tree widget causes error

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4695]
Tons of this in the browser console:
```
browser.ts:137 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
```

From here:
https://github.com/theia-ide/theia/blob/74d71420197d3baf9db99c7f50c380643fd01c47/packages/core/src/browser/browser.ts#L137

I am using 74d71420 on OS X in Chrome.

**Comment by kittaakos** [comment]
Steps to reproduce: scroll in a tree widget.

**Comment by akosyakov** [comment]
It's polluting logs. It would be good to have a look in it.
