### ISSUE TITLE
Support Key Sequences

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#472]
Current only simple is allowed

**Comment by hexa00** [comment]
So humm what is a composite keybinding exactly ?

**Comment by kittaakos** [comment]
For instance, in VSCode if you hit Cmd/Ctrl+K and after that Cmd/Ctrl+W, it closes all editors. I hope, this clarifies.

**Comment by kittaakos** [comment]
If no, please reference KeyChrod [here](https://www.emacswiki.org/emacs/KeyChord).

**Comment by svenefftinge** [comment]
We could use something like https://github.com/ccampbell/mousetrap.
It also provides a readable string syntax for key bindings, which we can use in code and user preferences.

**Comment by hexa00** [comment]
A key chord means keys pressed at the same time or very quickly like Cmd/Ctrl+K is a keychord... 

But using Cmd/Ctrl+K and after that Cmd/Ctrl+W would be called a key sequence.
See: https://www.emacswiki.org/emacs/KeySequence

A big +1 to that :) 

First thing I"m going to do when setting keybindings for myself in theia is make a emacs keymap so it will use that for sure.

**Comment by hexa00** [comment]
And I think we should have our own key/mouse event handler. 

Looking at the code mousetrap it is not that much and we would export a core aspect of theia to external code.

**Comment by svenefftinge** [comment]
I'd consider it good thing that it is not so much. I haven't looked too closely, but it seems to do exactly what we need. I don't see why we should not use it internally in the keybindings module.

**Comment by hexa00** [comment]
I don't mean that mousetrap is not good. I mean it may not be much code to write ourselves and we avoid having to contribute patches and wait for a release of an external project to fix core Theia functionality.

**Comment by svenefftinge** [comment]
It seems pretty mature (8000 stars, 700 forks and lots of releases). I'd rather use something small and stable then implement and maintain it ourselves if it fits our requirements.

**Comment by hexa00** [comment]
I'm not sure it fits all our requirements, I do not see anything to configure for example the delay between the keys in a keysequence. It seems to be hardcoded to 1 sec.

Also I think in general for an IDE like our own key sequences are just too important to delegate.  We want to be able to support any scenario with these and be able to fix problems quickly.

**Comment by epatpol** [comment]
It seems to me that for mousetrap to be usable it would need to fill all the requirements we have (i.e I'm not even sure about there right now). It's true that making it ourselves would mean we have more control/power over fixing/adding stuff.

The good thing I could see about using it is that it could save us some time as a basic implementation for  keysequences. Maybe we could have an implementation of a KeybindingHandler that uses mousetrap that could be replaced later on with one of our own. Although I'm not sure that would really save us work in the end.

**Comment by svenefftinge** [comment]
Yes, we could start using it and wait with our own until we learned why we would want to do that.
Also, it could help us to get a better understanding of we need. So for sure we should not expose its API to extension developers, but rather use it internally only to map the readable shortcuts to the callbacks.
That said we would use and expose the syntax of mousetrap's keybindings, so in case we so it without it later we would need to support that syntax.

**Comment by hexa00** [comment]
I don't think it's a good idea to use this as a temporary solution. I'm afraid what will happen is that we use mousetrap then find a problem or in or find that we need to do something that it can't do and then be faced with either writing our own key event handler or find a workaround or modify mousetrap.

And I think we will most likely choose the option that takes the less effort like the workaround or mousetrap modification.

We should write our own now while we're building the base of theia.

Also we already have some handling done, I don't think it's that much effort to add key sequences.

**Comment by hexa00** [comment]
For reference as discussed in a meeting let's use mousetrap for now and make sure it's abstracted properly to be possibly replaced later.

**Comment by hexa00** [comment]
Note we now decided not to use mousetrap
