### ISSUE TITLE
Terminal Chinese Language Not Support

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4730]
### Description
![image](https://user-images.githubusercontent.com/10203793/55047284-2b5b8e80-507f-11e9-99dd-2dab8b651beb.png)

### Reproduction Steps
**OS and Theia version:**
latest next version

**Diagnostics:**

**Comment by akosyakov** [comment]
Could you try to reproduce with pure xtermjs? I am not sure that we can do anything about it in Theia. You can also try with  https://github.com/theia-ide/theia/pull/4680 PR, it brings latest xterm js.

**Comment by 502647092** [comment]
@akosyakov 
use alpine image Chinese is Correct maybe is fonts problem
![image](https://user-images.githubusercontent.com/10203793/56093777-290e8680-5eff-11e9-9822-c7fa3b00f0b4.png)
