### ISSUE TITLE
 What unicode unit does theia use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [theia-ide/theia#4739]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

If this project uses a unit other than UTF-16 could/would you ever conform to the protocol 3.0 and use UTF-16?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by akosyakov** [comment]
We rely on VS Code LSP client and editor, so it is UTF-16 for position encoding.

**Comment by Avi-D-coder** [comment]
@akosyakov thanks
