### ISSUE TITLE
RPC calls don't properly transfer arrays

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#4757]
### Description
It might be a long standing bug, just hit me again today: Sending arrays through our RPC infrastructure will transform arrays of values into the first value.

send([1, 2, 3, 4])
recv() == 1

### Reproduction Steps
Not really sure how to reproduce, anytime I had to write a backend service using a protocol expecting an array as argument, it would fail.

**Comment by kittaakos** [comment]
Same as #4310 and #4343.
