### ISSUE TITLE
[terminal] IDE freezes with bad preference setting

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#4767]
A setting of `"terminal.integrated.lineHeight": 0` causes the IDE to freeze on load.

**Comment by akosyakov** [comment]
@svenefftinge How critical is it? Should i have a look?

**Comment by svenefftinge** [comment]
Not super critical as it only happens in a very rare case. But when it happens its a show stopper. So we should look at it soon.

**Comment by uniibu** [comment]
I stupidly set this to test on my gitpod workspace and now I can't open any repo from github or any previous workspace on gitpod. So basically, i can't use gitpod anywhere lol. @svenefftinge or @akosyakov have any idea?

**Comment by akosyakov** [comment]
@uniibu i will ask @svenefftinge to clean your user settings when he is around

**Comment by uniibu** [comment]
Ok, I was able to put back the `terminal.integrated.lineHeight` to 1 by manually editing the `settings.json` for a workspace/repo and opening that on gitpod, so it overrides the user settings.

**Comment by toonvd** [comment]
It also crashed when I accidentally set my font size to 1. So I think it is a general issue.

**Comment by uniibu** [comment]
I think its best to set a minimum hard limit for these settings to avoid crashing.

**Comment by akosyakov** [comment]
@uniibu Could you take care about it? something like `Math.max(lineHeight, 1)` should do?

**Comment by uniibu** [comment]
> @uniibu Could you take care about it? something like `Math.max(lineHeight, 1)` should do?

We actually have `minimum` property for preferences, so setting this would suffice. Created PR #4801
