### ISSUE TITLE
Plugin User Preferences are ignored

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#4773]
I tried to change the startup parameters for jdt.ls in the vscode-java plugin (installed via "deploy plugin by id") by setting the preference key ```java.jdt.ls.vmargs```. However, the java process would always use the default value for that preference.
Debugging in Chrome showed that the preference value from the user preferences is rejected, because the key ```java.jdt.ls.vmargs``` is not present in the combined preferences schema in the ```PreferenceSchemaProvider```.  In fact, no preference prefixed "java" was present in the schema when the user preferences were validated and thus all java preferences would be rejected as invalid.
The problem seems to be that the user preferences are read before the contributions from ```PluginContributionHandler```. 
Note that this problem seems to be timing dependent: sometimes the schema update happens before the reading of the user prefs and everything works fine.

**Comment by tsmaeder** [comment]
I noticed that "setSchema()" generates a preferences changed event, but the "newValue" that is propagated with this even is not the value from the user preferences, but the default value. The correct thing to do would be to report the value from the user preferences.

**Comment by tsmaeder** [comment]
The fact that the reported value is wrong would not really matter (the prefs in the plugin container are reinitialized with all prefs from the client side), except that parsing the user preferences throws away any keys that are not in the preference schema, and that the preferences are not invalidated and re-read when the schema changes.

**Comment by akurinnoy** [comment]
@tsmaeder this issue should be fixed by https://github.com/theia-ide/theia/pull/4743

**Comment by akosyakov** [comment]
should be fixed by https://github.com/theia-ide/theia/pull/4947

@tsmaeder please reopen if not
