### ISSUE TITLE
Turn autosave off by default

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#4776]
We should align the default behavior of autosave being off with VS Code.

**Comment by slemeur** [comment]
why?

**Comment by slemeur** [comment]
VSCode is not running in the same environment than Theia. 
As such, the behaviors and the experience provided to Theia must be adapted to the environment where it runs. 
Defaulting the behaviors of Theia to replicate VSCode could lead in a non-optimal experience.

**Comment by svenefftinge** [comment]
It confuses people switching between Vs Code and Theia back and forth.

**Comment by svenefftinge** [comment]
Why is Theia not running in the same environment as VS Code? I think it can run anywhere where VS Code is used and even runs all its extensions which are built with the VS Code behavior in mind. Some extension don't work so nicely with autosave turned on.

**Comment by akosyakov** [comment]
You can override default settings for your app after this PR is merged: https://github.com/theia-ide/theia/pull/4766/files#diff-163ff56fd2fd53d36d314074510353c0

**Comment by slemeur** [comment]
> Why is Theia not running in the same environment as VS Code? 

> I don't think VSCode is running in the browser, but I might have missed something ;) ! 

Theia is running in the browser and when you are coding from your browser, the experience is different than when you are coding on an electron application. 
Theia can be used as an editor in a cloud environment - meaning it is used remotely, there can also be connectivity or network issues. 

I'm not saying you should not change the default behavior, but I wanted to pointed out that we should not copy VSCode for the sake of replicating VSCode. It runs in different environment with different use cases, as such we should be cautious about that. 

Now, if editing in the cloud was better without autosave, I think I would not use GDoc ;)

**Comment by akosyakov** [comment]
Theia is running in Electron on Desktop.

**Comment by svenefftinge** [comment]
As Anton pointed out, Theia is not browser, only. 
But even if it were I don't understand why applications running in browsers should use auto-save and others don't (or vice versa). If I am offline, saving doesn't work no matter it's triggered automatically or not. And there is no problem with keeping dirty editor state in you browser until you can reconnect again.

For Theia, the general approach is to take the widely adopted and validated UX and tech from VS Code and rearchitect it so it runs fine in browsers. With the support for VS Code extensions it becomes even more important to align with the UX and expectation that extensions developer assume.

That said, PR #4766 allows applications to override the defaults to fit your needs. I can understand that you want to make the transition for Che users smooth, so it might be a good idea to change that default in your case.

**Comment by nils-mosbach** [comment]
I find the autosaving feature quite handy, but while playing around at some projects, this also leads to compile errors. e.g. if maven automatically hot deploys code changes while typing. I guess the same goes for running node in debugging mode.
