### ISSUE TITLE
[dev-meeting] scheduled 1h later during "daylight saving" time

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#4786]
ATM our dev meeting is [scheduled](https://github.com/theia-ide/theia/wiki/Dev-Meetings#purpose) "every Tuesday at 3 PM UTC". Now that both Europe and America have switched to DST, the meeting is 1h later vs before, local time. 

I am personally ok with this time, but I think it may be a little late for some of our European contributors. 

WDYT?

**Comment by akosyakov** [comment]
Today it is too late for me and @svenefftinge . Would 2 PM UTC work next week or it is too early for you?

**Comment by marcdumais-work** [comment]
Yes, the usual time seems fine with most, so we can switch to 2PM UTC starting next week.

**Comment by marcdumais-work** [comment]
Since no one is objecting, I will modify the time on the dev-meeting wiki to 2PM UTC. We can switch back to 3PM in the fall.
