### ISSUE TITLE
[electron] unable to quit electron instance due to preference

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4800]
**Description**

Due to the `application.confirmExit` preference, Electron cannot be closed in the following scenarios:
1. If the preference has the value of `always`.
2. If the preference has the value of `ifRequired` with a dirty editor (unsaved changes).
3. If the preference has the value of `ifRequired` and an extension wishes to prevent exit.

**Reproduction Steps** (Simple Scenario)
1. Start an Electron Theia instance.
2. Confirm that closing the Electron window works.
3. Start another Electron Theia instance.
4. Update the preferences by setting `application.confirmExit` to `always`.
5. Conform that closing the Electron window no longer works.

**Comment by marechal-p** [comment]
See https://github.com/electron/electron/issues/2301#issuecomment-123736541

On electron, when `onbeforeunload` stops the unloading, it seems like it doesn't display dialog.
We have to implement that on our side.

**Comment by kittaakos** [comment]
I made some changes locally, and it seems the `e.preventDefault();` works only if the `window.on('close'` is in the main electron module. Otherwise, it does not.

Depends on https://github.com/theia-ide/theia/pull/4869.
