### ISSUE TITLE
vscode-plugin: debug.registerDebugAdapterDescriptorFactory and debug.registerDebugAdapterTrackerFactory are not implemented.

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#4804]
### Description

When I tried to install this [plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), I got this error:

```text
root ERROR [hosted-plugin: 101973] (node:101973) UnhandledPromiseRejectionWarning: TypeError: vscode.debug.registerDebugAdapterDescriptorFactory is not a function
```

So I look into the source code, and found out that neither `debug.registerDebugAdapterDescriptorFactory` nor `debug.registerDebugAdapterTrackerFactory` is implemented by theia. 

### Reproduction Steps

- Download cpptools-linux.vsix from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
- Start a new instance of theia that comes with the extension
- Check theia's log

**OS and Theia version:**

OS: ubuntu 16.04
Theia: 0.5.0

**Diagnostics:** 

The two methods are not found in source code `packages/plugin-ext/src/plugin/plugin-context.ts`.

**Comment by benoitf** [comment]
Thanks for the report. These methods are not yet implemented in Theia https://che-incubator.github.io/vscode-theia-comparator/status.html
