### ISSUE TITLE
[COPY/PASTE] does not work in context menus

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#481]
If one uses the copy command in a context menu it does not work. 
After right click the focus on the clicked element gets lost.

**Comment by MarkZ3** [comment]
Was that the browser or electron version? I don't see the Copy command anymore in the context menu in the browser version. And I can't run the electron version :-p #497

**Comment by jbicker** [comment]
It was in the browser version. The copy command is still in the context menu of the file navigator. It loses its focus too. And we have the same effect on edit menu.
