### ISSUE TITLE
Emergency! Python Extension active failed in eclipse/che-theia:0.5.0 version,but in 0.4.0 master is ok

### ISSUE THREAD

**Issue by 113xiaoji** [theia-ide/theia#4817]
### Description
1.the theia images is eclipse/che-theia:0.5.0, i put the python extension ms-python.python-2019.3.6352.vsix at /default-theia-plugins/ folder and build new theia image.
2. I create a new che workspace based on eclipse/che-theia:0.5.0 with python extension
3. it shows 
![image](https://user-images.githubusercontent.com/31875988/55601564-10320280-5794-11e9-867a-4040065a0c5a.png)
![image](https://user-images.githubusercontent.com/31875988/55601575-1922d400-5794-11e9-9cba-acea6bc4b9ac.png)
![image](https://user-images.githubusercontent.com/31875988/55601605-42436480-5794-11e9-9b8b-6713ae485cbc.png)

The python extension is not working. 
I tried build  che-theia image with dockerfile.But i faced the same issue.
I tried to build theia with source code. And the python extension is worked.
I install python extension with plugin id, and it is worked. i cannot explain why
I add a issue , it fixed at a master version last than 0.4.0, but it not work at 0.5.0,It is kind of emergency, please responded me.
@akosyakov @kittaakos @svenefftinge @tolusha

**OS and Theia version:**
theia 0.5.0 

**Diagnostics:**

**Comment by akosyakov** [comment]
@113xiaoji che images supported by Che team, i don't think we can help here. I could try to transfer an image Che repo for visibility.

**Comment by akosyakov** [comment]
@113xiaoji https://github.com/eclipse/che/issues/13072

**Comment by 113xiaoji** [comment]
thank you
