### ISSUE TITLE
Errors/Warnings not shown when hovering after the context menu is opened once

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#482]
Using Theia/electron master as of today
A somewhat old Clangd (Jul 28, 2017)
macOS

1. Create a cpp file with an error:
`inttt main() {}`

2. Hover on the error: message is shown in a popup
3. Move the cursor somewhere else so that popup disappears.
4. Open editor context menu (right-click). Close it.
5. Try to hover on the error again: popup is not shown.

It might happen for other languages and OS, I'm not sure.

**Comment by svenefftinge** [comment]
Seems to be a problem in monaco, as it happens with other languages, too.

**Comment by MarkZ3** [comment]
In
vscode/src/vs/editor/contrib/contextmenu/browser/contextmenu.ts
It looks like onHide is never being called, and from what I can see this is what restores the hover:
```
this._editor.updateOptions({
hover:oldHoverSettings
});
```
Maybe something is not hooked up between phosphor and this context menu handling?

**Comment by svenefftinge** [comment]
I added a callback to properly call onHide.
