### ISSUE TITLE
Impossible to start/debug Hosted Instance

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#4821]
### Description
There is no way to select plug-in folder via select folder dialog. The only way is to cancel the dialog.

### Reproduction Steps
1. Execute `Hosted Plugin: Start Instance` command
2. Try to select a folder

**Expected:** When press `Open` the dialog should return selected folder
**Actual:** When `Open` button is pressed it just switches directory to the select. No way to complete dialog, close/cancel only.

**Comment by vzhukovskii** [comment]
See the last comment: https://github.com/theia-ide/theia/pull/4763

As a workaround, you can add property `canSelectFolders: true` into dialog options, when `Hosted Plugin: Start Instance` command executes.
