### ISSUE TITLE
[Plug-in]Does theia support OutputCahnnel VSCode API

### ISSUE THREAD

**Issue by invincibleJai** [theia-ide/theia#4822]
### Description
I was exploring VSCode extension support in theia and was unable to figure out if VSCode output channel API it supports?

https://code.visualstudio.com/api/references/vscode-api#OutputChannel

```
vscode.window.createOutputChannel(channelName);
```

**Comment by akosyakov** [comment]
It does: https://che-incubator.github.io/vscode-theia-comparator/status.html

You can analyze your extensions for missing APIs with https://github.com/theia-ide/theia-vscodecov

**Comment by invincibleJai** [comment]
@akosyakov thanks for pointing, it's helpful.
