### ISSUE TITLE
Project configuration is not up-to-date with pom.xml, requires an update.

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4829]
### Description
![image](https://user-images.githubusercontent.com/10203793/55679636-84f66f80-5941-11e9-8dac-251e7a6ce0b5.png)

### Reproduction Steps

**OS and Theia version:**

latest theia docker version

**Diagnostics:**

**Comment by akosyakov** [comment]
It seems that vscode-java extension provides a command to retrigger update of project configurations. Theia extension should do the same.

@502647092 Have you tried to use vscode-java extension instead?

**Comment by 502647092** [comment]
@akosyakov 
i use vscode-java extension find this action thank you 
![image](https://user-images.githubusercontent.com/10203793/56093506-3e35e600-5efc-11e9-9a72-b03f11deb301.png)
