### ISSUE TITLE
[gitpod] enable Electron support 

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4832]

**Comment by kittaakos** [comment]
What do you mean, @akosyakov?

**Comment by akosyakov** [comment]
https://medium.com/gitpod/developing-native-ui-applications-in-gitpod-15af2967c24e to test Electron version in Gitpod as well

**Comment by akosyakov** [comment]
Good enough for testing 😄 

<img width="1725" alt="Screen Shot 2019-04-09 at 13 48 34" src="https://user-images.githubusercontent.com/3082655/55798052-480bb380-5ace-11e9-9638-1e96a7f0cf8c.png">
