### ISSUE TITLE
[c/c++] Quick fix (Code action) does not seem to work

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#484]
Using Theia/electron master as of today
A somewhat old Clangd (Jul 28, 2017)
macOS

1. Create a source file:
test.cpp:

```
struct Foo {
    int x;
    int y;
};

int main() {
    Foo a = {x: 1, y: 2};
}
```
2. Place cursor on "x", in the initializer. There doesn't seem to be a way to trigger the quick fix/code acton (command palette, context menu).

In the log, I see this:
```
C/C++: <-- {"jsonrpc":"2.0","id":2,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/mark/git/theia/examples/electron/test/test.cpp"},"range":{"start":{"line":6,"character":14},"end":{"line":6,"character":14}},"context":{"diagnostics":[{"range":{"start":{"line":6,"character":14},"end":{"line":6,"character":14}},"message":"use of GNU old-style field designator extension","severity":2,"code":null}]}}}
Failed to decode CodeActionParams!
```

It could be either Theia is sending bad things or Clangd is not decoding CodeActionParams properly. I have seen in the past Clangd being too strict and early returning when an optional field was not set. If that's the case, we can move the issue to llvm/clangd Bugzilla.

**Comment by svenefftinge** [comment]
I can confirm that code actions work with the YANG-LSP.
<img width="298" alt="screen shot 2017-09-11 at 08 16 13" src="https://user-images.githubusercontent.com/372735/30260744-7d9ca0ec-96c9-11e7-857a-7c42a004005b.png">

**Comment by akosyakov** [comment]
@svenefftinge with the latest Theia? i.e. monaco 0.10.0

**Comment by svenefftinge** [comment]
No, with the current master state.

**Comment by svenefftinge** [comment]
I now tested also with the PR and it still works.

**Comment by akosyakov** [comment]
interesting that it does not seem to work with pure Monaco: https://github.com/Microsoft/monaco-editor/issues/574

**Comment by MarkZ3** [comment]
There is indeed a decoding problem on the Clangd side 
https://bugs.llvm.org/show_bug.cgi?id=34559

With that fixed (locally for now), I can see the quick fix, but it doesn't get applied when selected:

```
C/C++: <-- {"jsonrpc":"2.0","id":55,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///home/emalape/git/theia/examples/browser/test/test.cpp"},"range":{"start":{"line":6,"character":13},"end":{"line":6,"character":14}},"context":{"diagnostics":[{"range":{"start":{"line":6,"character":14},"end":{"line":6,"character":14}},"message":"use of GNU old-style field designator extension","severity":2,"code":null}]}}}
--> {"jsonrpc":"2.0","id":55, "result": [{"title":"Apply FixIt 'use of GNU old-style field designator extension'", "command": "clangd.applyFix", "arguments": ["file:///home/emalape/git/theia/examples/browser/test/test.cpp", [{"range": {"start": {"line": 6, "character": 13}, "end": {"line": 6, "character": 15}}, "newText": ".x = "}]]}]}

C/C++: Content-Length: 333

{"jsonrpc":"2.0","id":55, "result": [{"title":"Apply FixIt 'use of GNU old-style field designator extension'", "command": "clangd.applyFix", "arguments": ["file:///home/emalape/git/theia/examples/browser/test/test.cpp", [{"range": {"start": {"line": 6, "character": 13}, "end": {"line": 6, "character": 15}}, "newText": ".x = "}]]}]}

```

I will investigate some more.

**Comment by MarkZ3** [comment]
Clangd was changed to handle the command server-side, see https://reviews.llvm.org/D39276
Thanks for the suggestions!
