### ISSUE TITLE
[ui][git] `Discard All` action has layout issues when the Git widget is too narrow

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4851]
Same for `Unstage All` and `Stage All` commands:
![Screen Shot 2019-04-10 at 11 55 03](https://user-images.githubusercontent.com/1405703/55869936-cf692d80-5b87-11e9-991b-a49a6f4ed673.jpg)

**Comment by akosyakov** [comment]
@vinokurig it is broken after merging SCM PR

Before everything was nicely rendered with ellipsis:
<img width="152" alt="Screen Shot 2019-05-27 at 14 10 08" src="https://user-images.githubusercontent.com/3082655/58418908-7b5bcf00-8089-11e9-8779-2a8a11d6206a.png">
<img width="289" alt="Screen Shot 2019-05-27 at 14 04 26" src="https://user-images.githubusercontent.com/3082655/58418910-7b5bcf00-8089-11e9-9b2d-94568f2baab3.png">

How it is now:
<img width="179" alt="Screen Shot 2019-05-27 at 14 10 18" src="https://user-images.githubusercontent.com/3082655/58418906-7ac33880-8089-11e9-8d75-74f018b7c638.png">
<img width="318" alt="Screen Shot 2019-05-27 at 14 04 18" src="https://user-images.githubusercontent.com/3082655/58418911-7b5bcf00-8089-11e9-9788-175af5286f38.png">

**Comment by akosyakov** [comment]
Also the placeholder in input used to be 'Commit **m**essage', not 'Commit **M**essage'
