### ISSUE TITLE
Theia docker does not stop on SIGTERM

### ISSUE THREAD

**Issue by amiramw** [theia-ide/theia#4852]
### Description
Theia does not stop on SIGTERM / kill command which is problematic on K8S environment as a pod containing theia takes long time to stop.

It seems that packages/core/src/node/backend-application.ts listens on SIGTERM but it is only one of several child processes.

### Reproduction Steps

1. `docker run -p 3000:3000 theiaide/theia:next`
2. `docker exec -it <id> bash`
3. `kill 1` does nothing

The same behavior will apply if you try to stop with `docker stop -t 200 <id>`. After 200 seconds if will force stop.

OS and Theia version: Docker

**Comment by akosyakov** [comment]
We've got rid of cluster module yesterday. Now backend-application.ts runs in the main process, so it should. There are issues with next images right now, after they get sorted out, it would be nice if you try again.

Thanks for the reporting btw.

**Comment by amiramw** [comment]
Seems to be fixed now. Thanks!
