### ISSUE TITLE
Unsupported notification method: $/setTraceNotification message when installing Camel language VS Code extension

### ISSUE THREAD

**Issue by apupier** [theia-ide/theia#4855]
### Description

there is several times this message Info in log:

```
Apr 10, 2019 11:58:55 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTraceNotification
```

### Reproduction Steps

docker run -it -p 3000:3000 -v "C:/Users/Aurelien Pupier/theiatmp:/home/project:cached" theiaide/theia-full:latest

use deploy plugin by id command:
vscode:extension/camel-tooling.vscode-apache-camel
vscode:extension/redhat.vscode-xml

create an xml file with content:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd        http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
    <camelContext id="cbr-example-context" xmlns="http://camel.apache.org/schema/spring">
        <route id="cbr-route">
            <from id="_from1" uri="timer:timerName?delay=1000"/>
            <log id="_log1" message="Receiving order ${file:name}"/>
            <choice id="_choice1">
                <when id="_when1">
                    <xpath id="_xpath1">/order/customer/country = 'UK'</xpath>
                    <log id="_log2" message="Sending order ${file:name} to the UK"/>
                    <to id="_to1" uri="file:work/cbr/output/uk"/>
                </when>
                <when id="_when2">
                    <xpath id="_xpath2">/order/customer/country = 'US'</xpath>
                    <log id="_log3" message="Sending order ${file:name} to the US"/>
                    <to id="_to2" uri="file:work/cbr/output/us"/>
                </when>
                <otherwise id="_otherwise1">
                    <log id="_log4" message="Sending order ${file:name} to another country"/>
                    <to id="_to3" uri="file:work/cbr/output/others"/>
                </otherwise>
            </choice>
            <log id="_log5" message="Done processing ${file:name}"/>
        </route>
    </camelContext>
</beans>
```

play with it... not noticed when this error is logged exactly.

**OS and Theia version:**

Windows

**Diagnostics:**

**Comment by akosyakov** [comment]
It seems to be the issue with Camel LS. It should ignore undocumented messages: https://github.com/Microsoft/vscode-languageserver-node/issues/170

**Comment by apupier** [comment]
ok it needs to be handled in vscode-languageclient, lsp4j or maybe easier to negociate for me inside the Camel Language Server.

Thanks for the explanation and the pointers.

I created  https://github.com/camel-tooling/camel-language-server/issues/226

**Comment by apupier** [comment]
to ignore it, seems need to add an @JsonNotifcation with empty implementation:
https://github.com/eclipse/lsp4j/issues/22#issuecomment-266440509

**Comment by apupier** [comment]
I do not reproduce the $/setTraceNotification when trying to test VS Code extension with setting the .vsix in plugins folder as indicated here https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

Should I configure something specific to have "trace notification" sent?
After reproducing, I would like to test that I fixed it correctly in Camel Language Server side before publishing a new VS Code extension version.
