### ISSUE TITLE
[electron][TS] The TS Theia extensions picks up and uses incorrect TS version

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4865]
For instance, open `preference-proxy.ts` and see the errors.
![Screen Shot 2019-04-10 at 16 57 18](https://user-images.githubusercontent.com/1405703/55889676-b70e0880-5bb1-11e9-82d0-4a879003349a.jpg)

It happened with the bundled Theia electron application, I do have TS in my workspace's `node_modules` folder, but I do not have it globally installed.

Note, my workspace root is `/Users/akos.kitta/git/theia` and the application is under `/Applications/Theia.app`.

**Comment by akosyakov** [comment]
We don't distribute typescript as runtime dependency, since each app can bundle its own version. There should be a way to bundle one version during packaging then. I don't think there can be anything done in theia repo.

It would be also fixed as soon as we used typescript vscode extension.

**Comment by kittaakos** [comment]
> We don't distribute typescript as runtime dependency, since each app can bundle its own version. There should be a way to bundle one version during packaging then. I don't think there can be anything done in theia repo.

Then why do we have the [discovery logic](https://github.com/theia-ide/typescript-language-server/blob/6faea64ba5b0c748601197fa4db309e83b838fb0/server/src/lsp-server.ts#L88) in TS server?

I thought the problem is that the TS server is under `/Application/Theia.app/somewhere/nested/deep and the workspace with the `node_modules` is under a different roo foldert. Instead or `__dirname` we should start the discovery in the TS workspace root.

**Comment by akosyakov** [comment]
> Then why do we have the discovery logic in TS server?

only for local dev

**Comment by kittaakos** [comment]
> only for local dev

OK, it's completely broken. I am sure it used to work, and now you are telling me we cannot do anything in the Theia repo just wait for VS Code extensions.

For the record, the `typescript` dependency is among my dependencies, still, it does not work.

```json
{
    "private": true,
    "name": "theia-electron",
    "version": "0.3.17",
    "description": "Theia",
    "main": "src-gen/frontend/electron-main.js",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/theia-ide/theia.git"
    },
    "theia": {
        "target": "electron"
    },
    "scripts": {
        "prepare": "yarn run build",
        "build": "theia build",
        "package": "electron-builder",
        "package:preview": "electron-builder --dir"
    },
    "keywords": [],
    "author": "typefox <npm@typefox.io>",
    "license": "Apache-2.0",
    "bugs": {
        "url": "https://github.com/theia-ide/theia/issues"
    },
    "homepage": "https://github.com/theia-ide/theia#readme",
    "dependencies": {
        "@theia/callhierarchy": "next",
        "@theia/core": "next",
        "@theia/editor": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/git": "next",
        "@theia/java": "next",
        "@theia/json": "next",
        "@theia/keymaps": "next",
        "@theia/languages": "next",
        "@theia/markers": "next",
        "@theia/merge-conflicts": "next",
        "@theia/messages": "next",
        "@theia/mini-browser": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/outline-view": "next",
        "@theia/output": "next",
        "@theia/preferences": "next",
        "@theia/preview": "next",
        "@theia/process": "next",
        "@theia/search-in-workspace": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/textmate-grammars": "next",
        "@theia/typescript": "next",
        "@theia/userstorage": "next",
        "@theia/workspace": "next",
        "typescript": "latest"
    },
    "devDependencies": {
        "@theia/cli": "next",
        "electron-builder": "^20.36.2"
    }
}
```

```
$ pwd
/Applications/Theia.app/Contents/Resources/app/node_modules/typescript
```

**Comment by akosyakov** [comment]
Theia does not rely on ts ls discovery logic, but has own: https://github.com/theia-ide/theia/blob/36eba77252634a6227ec5e98eaf3e08f67e08dd8/packages/typescript/src/node/typescript-version-service-impl.ts#L52

It was not changed though for long time. It uses require to find bundled typescript, so if `@theia/typescript` and `typescript` are in the same node_modules it should work.

**Comment by akosyakov** [comment]
> and now you are telling me we cannot do anything in the Theia repo just wait for VS Code extensions.

I did not say that you have to wait for VS Code extensions. I said that it likely an issue in how dependencies are bundled for you app, not in Theia code.

**Comment by kittaakos** [comment]
To sum up, it works, but it picks up the bundled TS (`3.4.3`) as opposed to the one from the `node_modules`: `3.1.3`.

The temporary workaround is to set the correct TS version manually:
![Screen Shot 2019-04-11 at 09 12 47](https://user-images.githubusercontent.com/1405703/55937742-0d268e80-5c3a-11e9-9bde-5629807f2b5b.jpg)

![Screen Shot 2019-04-11 at 09 12 55](https://user-images.githubusercontent.com/1405703/55937756-11eb4280-5c3a-11e9-9d80-5076da76d7ab.jpg)
