### ISSUE TITLE
Some keybindings are not shown in the command palette?

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#487]
![command-palette](https://user-images.githubusercontent.com/698076/30272277-b7d4ce86-96c1-11e7-8ee1-fbd5e385874f.png)

Paste is not showing ?
Open should have a keybinding too ?
New file / new directory ... maybe not yet..

Also Copy is Ctrl-F9 is that right ? Seems strange to me.

**Comment by hexa00** [comment]
Could this be related to #490 ?

**Comment by svenefftinge** [comment]
There are just no keybindings registered for those commands.

**Comment by hexa00** [comment]
Maybe we should still show one for like Paste ?

**Comment by hexa00** [comment]
Fixed as #490
