### ISSUE TITLE
Filter out Quick Command from the command palette

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#491]
What should this do ?

**Comment by akosyakov** [comment]
It should open the quick command palette. We probably should filter out from the command palette.

**Comment by hexa00** [comment]
Ha k hehe :) I'll change the title

**Comment by svenefftinge** [comment]
Once we have a menu item that opens the quick command palette, having 'Quick Command' included could teach users the shortcut.

**Comment by hexa00** [comment]
Won't you see the shortcut in the menu already?

**Comment by svenefftinge** [comment]
good point :)
