### ISSUE TITLE
Gaps in vscode-ext support: views, launchConfig

### ISSUE THREAD

**Issue by ariel-bentu** [theia-ide/theia#4912]
### Description

Following are three topics in which Theia is not compatibale/ not fully working comparing to vscode in regards to vscode extensions:

#### Adding a View to Theia does not behave as in vscode, and some things don't work:
* Trying to add the view to one of the existing viewContainers (debug, explorer) do not work and the view does not show at all
* When adding a new viewContainer, and a view to it, the view shows but:
  * The icons for the tree elements do not show
  * Setting a menu as 'view/item/context' to be in the "inline" group, which means it should show up as an icon next to the tree-item text, is ignored and shows up only as right-click menu on the tree-item

#### Accessing Launch configuration by API does not work
* Trying to read existing launch configuration is not working
* Trying to write a new launch configuration writes the content to the .theia/settings.json as:
```
"launch.configurations": [ { <the configuration>}]
```

### Reproduction Steps
* git clone https://github.com/ariel-bentu/theia-vscode-gaps
* run it in vscode and in theia - to see the differences

#### Views gaps:
* To activate the extension, run command 'Bugs: Start'
* To try and add the view to debug or explorer, change line: 31 in package.json to "debug" or "explorer" - see that in vscode it places the view in either of them, and in theia it does not show anywhere
* See the missing icons
* See that "Bug1" menu is part of the right-click menu and not as a button in the tree-item as in vscode

#### launch config gaps
* Open in the hosted theia the Bugs project (so you'll have the predefined launch.json with Test1 config - or create on yourself in whatever project)

* Run the command `BUG: Find Launch Config named test1` - in vscode it works in theia - not
* Run the command `BUG: Create Launch Config named test2` - in vscode it works in theia - not

**OS and Theia version:**
Latest (15-April)

**Diagnostics:** 
explained in reproduction steps.

**Comment by akosyakov** [comment]
Thanks for the detailed reporting!

**Comment by tetchel** [comment]
I would also like to see support for the `views` contribution point without requiring the plugin to also contribute a `viewContainer`.

**Comment by ariel-bentu** [comment]
One addition, I plan to (try) fixing it and provide a pull request. If there's any other plan in this regards, please let me know.


I see in the code, that currently in theia, Icons are assumed to be from Font Awesome. In vs-code ext you can bring your own. I hope to be able to support that as well.

**Comment by benoitf** [comment]
thx @ariel-bentu 
I would say it would be better to do small PR that fixes a specific issue than trying to solve everything in one PR.

**Comment by akosyakov** [comment]
> launch config gaps

Should be addressed by https://github.com/theia-ide/theia/pull/4947 eventually

**Comment by akosyakov** [comment]
Launch part was addressed by https://github.com/theia-ide/theia/pull/4947
View gaps should be addressed by https://github.com/theia-ide/theia/pull/5057
Shell refactoring to support view container as first-class components is tracked here: https://github.com/theia-ide/theia/issues/5058

**Comment by akosyakov** [comment]
@ariel-bentu i'm closing it, please follow #5058 for view containers, i hope we get them in 0.9.0
the initial PR is here already: https://github.com/theia-ide/theia/pull/5392
