### ISSUE TITLE
Building Theia IDE Docker-Image within AWS EC2 instance: RUN yarn theia build Error

### ISSUE THREAD

**Issue by okrits** [theia-ide/theia#4913]
Hello, I'm using the free tier t2.micro instance with 1 CPU and 1 GiB of memory and amount of volume storage in Elastic Block Store is 8 GiB.

```
Step 16/19 : RUN yarn theia build
 ---> Running in fb133ccf4c62
yarn run v1.13.0
$ /home/theia/node_modules/.bin/theia build
Error: webpack exited with an unexpected signal: SIGKILL.
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/application-manager/lib/application-process.js:59:28)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn theia build' returned a non-zero code: 1
```

Many thanks in advance!

**Comment by benoitf** [comment]
hello, probably not enough memory as process is killed ?

**Comment by okrits** [comment]
Hello, I'm using the free tier t2.micro instance with 1 CPU and 1 GiB of memory. Amount of volume storage in Elastic Block Store is 8 GiB. That should be enough. Locally the docker image is round about 2 GB.

**Comment by marcdumais-work** [comment]
Hi @okrits ,

Which image are you trying to build? Is it one from our [theiaide/theia-apps](https://github.com/theia-ide/theia-apps) repo?

I think @benoitf is right. While it may be possible to run a small Theia application in 1GB of RAM, this amount of memory may not be enough to build the same application. 

You could try building it on a machine or instance that has more RAM and then run it on AWS EC2.

**Comment by okrits** [comment]
> Hi @okrits ,
> 
> Which image are you trying to build? Is it one from our [theiaide/theia-apps](https://github.com/theia-ide/theia-apps) repo?
> 
> I think @benoitf is right. While it may be possible to run a small Theia application in 1GB of RAM, this amount of memory may not be enough to build the same application.
> 
> You could try building it on a machine or instance that has more RAM and then run it on AWS EC2.

Yes it is theia-java-docker image from [theiaide/theia-apps](https://github.com/theia-ide/theia-apps) repository. Locally I have no problems to build the image. I'll try instance with more RAM.

Thank you @benoitf @marcdumais-work.
