### ISSUE TITLE
Switch to next tab or previous tab keybinding does not work in the browser example

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#492]
Doing Ctrl-Esc or Ctrl-Shift-Esc doesn't do anything... 

Using Chrome.

Also I think this keybinding is not practical at all ? Where does it come from ?

**Comment by hexa00** [comment]
The keybindings were wrong because of #493 

But even with this now fixed, The keybinding Ctrl-Tab and Ctrl-Shift-Tab doesn't work in the browser Example on Chrome.

Selecting the action in the palette works however.

**Comment by hexa00** [comment]
This is conflicting with the browser's keybindings and so the browsers tabs switch rather than Theia's

**Comment by spoenemann** [comment]
On Mac OS the current keybinding is Cmd-Tab / Cmd-Shift-Tab. That is even worse because it conflicts with the OS keybinding for switching apps. We should change those keybindings.

VS Code uses `ctrlcmd+alt+arrowleft` and `ctrlcmd+alt+arrowright`.
