### ISSUE TITLE
[quality] Move the upload service and its functionality to its own module

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4923]
`packages/filesystem/src/browser/download/file-download-service.ts` should be responsible for the download only, as its name suggests.

Move the upload functionality to its own module.

**Comment by akosyakov** [comment]
I would rather have files-service which represents `files` HTTP resources and provides HTTP operations on them, i.e. download, upload and so on.

**Comment by kittaakos** [comment]
I am OK with both; I would like to be able to locate the classes based on the container module name, if possible.
