### ISSUE TITLE
MDK vscode extension is not deployed properly

### ISSUE THREAD

**Issue by DoroNahari** [theia-ide/theia#4924]
### Description
MDK vscode extension is not deployed properly on theia.

### Reproduction Steps
I try to use MDK vscode extension on theia (latest\next) 
https://marketplace.visualstudio.com/items?itemName=SAPSE.vsc-extension-mdk

On theia: run command: Deploy plugin by ID -> Insert the plugin id: vscode:extension/SAPSE.vsc-extension-mdk

I can see that the plugin is deployed but the plugin features are not available. 
Issues for example: 

- There should be MDK commands added to the commands (not found with F1).
- There should be a new MDK terminal.
- There should be MDK preferences.
- The MDK language is loaded but no auto-completion, validation, navigation, etc.

**OS and Theia version:**
Windows/Mac, theia (latest\next)

**Diagnostics:** 
[mdk-logs-server.txt](https://github.com/theia-ide/theia/files/3084273/mdk-logs-server.txt)
[mdk-logs-client.txt](https://github.com/theia-ide/theia/files/3084283/mdk-logs-client.txt)

**Comment by akosyakov** [comment]
If you can provide a link to source code for this extension it would be nice. I could not find it on marketplace page. It would help with detailed analysis.

**Comment by benoitf** [comment]
@DoroNahari 
deploying the vsix I have the menu entries
![image](https://user-images.githubusercontent.com/436777/56297170-247ce480-6130-11e9-8b22-60a94d3c8a30.png)
or preferences
![image](https://user-images.githubusercontent.com/436777/56297289-60b04500-6130-11e9-8535-a1e82340abb7.png)

I see in your log a trace about some modules not found that I haven't
```
oot ERROR [hosted-plugin: 247] { Error: Cannot find module 'vscode-json-languageservice/lib/umd/services/JSONSchemaService.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.module._load (/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:83:33)
```
I might suspect it is linked to a Windows issue

**Comment by benoitf** [comment]
ok so from what I've found is that your extension is loading 'vscode-json-languageservice/lib/umd/services/JSONSchemaService.js'

    at Object.<anonymous> (/tmp/vscode-unpacked/SAPSE.vsc-extension-mdk-1.6.1.vsix/extension/node_modules/mdk-languageservice/lib/service/schema/SchemaService.js:10:25

```
let JSONSchemaService = require('vscode-json-languageservice/lib/umd/services/JSONSchemaService.js').JSONSchemaService;
class MDKSchemaService extends JSONSchemaService {
```

but looking at the files: 

```
$ ls -la node_modules/vscode-json-languageservice/lib/umd/services/
total 140
drwxr-xr-x 2 theia theia  4096 Apr 17 00:39 .
drwxr-xr-x 5 theia theia  4096 Apr 17 00:39 ..
-rw-r--r-- 1 theia theia 25365 Apr 17 00:39 configuration.js
-rw-r--r-- 1 theia theia 43989 Apr 17 00:39 jsonCompletion.js
-rw-r--r-- 1 theia theia 11584 Apr 17 00:39 jsonDocumentSymbols.js
-rw-r--r-- 1 theia theia  6319 Apr 17 00:39 jsonFolding.js
-rw-r--r-- 1 theia theia  6185 Apr 17 00:39 jsonHover.js
-rw-r--r-- 1 theia theia 21932 Apr 17 00:39 jsonSchemaService.js
-rw-r--r-- 1 theia theia  6501 Apr 17 00:39 jsonValidation.js
```

the files don't have the same lowercase/uppercase so I would say it's only working on non case-sensitive filesystems (like myself with macOS)

you should fix your code

**Comment by DoroNahari** [comment]
Thanks, the case-sensitive fix solves the deployment problem.
