### ISSUE TITLE
Diagnostic from a language server is overriding diagnostic from other Language servers contributing to the same file

### ISSUE THREAD

**Issue by apupier** [theia-ide/theia#4929]
### Description

Diagnostic from a language server is overriding diagnostic from other Language servers contributing to the same file

### Reproduction Steps

docker run -it -p 3000:3000 -v "${pwd}:/home/project:cached" theiaide/theia-full:next

use command "deploy plugin by id" for xml and Camel:
vscode:extension/camel-tooling.vscode-apache-camel
vscode:extension/redhat.vscode-xml

create file camel.xml with content:

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd        http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
    <camelContext id="cbr-example-context" xmlns="http://camel.apache.org/schema/spring">
        <route id="cbr-route">
            <from id="_from1" uri="timer:timerName?delay=1000ff"/>
            <log id="_log1" message="Receiving order ${file:name}"/>
            <plop>
        </route>
    </camelContext>
</beans>
```

--> error is on plop tag
remove the plop tag, you will see the timer:timerName?delay=1000ff error
readd the plop tag, the timer:timerName?delay=1000ff error will vanish

**OS and Theia version:**

**Diagnostics:**

**Comment by apupier** [comment]
using another way to deploy, it is working:

` docker run -it --rm -p 3000:3000 -p 3030:3030  -v C:/git/theia/plugins:/plugins -e THEIA_PLUGINS=local-dir:///plugins theiaide/theia-full:next`

![image](https://user-images.githubusercontent.com/1105127/56369697-214e2b00-61fa-11e9-857c-7ca332e53a6d.png)

**Comment by akosyakov** [comment]
Could it be that there are several extensions using the same diagnostic collection id?

**Comment by tsmaeder** [comment]
I think I understand what's happening here: if you look at /packages/plugin-ext/src/plugin/languages/diagnostics.ts#createDiagnosticsCollection, if no name is given, it is generated like so:
```
name = Diagnostics.GENERATED_DIAGNOSTIC_COLLECTION_NAME_PREFIX + this.getNextId();
```
However, if you look at ```this.getNextId()```, it just increments the instance variable "nextId". But since plugins run in a separate process (or even in a separate container in the case of Che), differentent plugins will get the same "nextId" and thus use the same name for the diagnostics collection. We need to generate a globally unique collection id.

**Comment by tolusha** [comment]
It seems everything works fine.
Both extensions send their diagnostics. 
If there an opned tag then Camle plugin doesn't send its.

![Screenshot from 2019-04-24 16-06-19](https://user-images.githubusercontent.com/1640675/56661818-353ad680-66ab-11e9-82c0-22451102eefe.png)
![Screenshot from 2019-04-24 16-06-33](https://user-images.githubusercontent.com/1640675/56661827-3a982100-66ab-11e9-91c9-25e9f4cc05a8.png)

**Comment by apupier** [comment]
> If there an opened tag then Camle plugin doesn't send its.

this is another use case.

I reported when the xml is valid but "just" not respecting xsd.
In this case, with the example that i provided, you should have:
- Camel LS reporting an error on the Camel URI
- XML LS reporting an xsd error

it is working fine in VS Code

please reopen.

**Comment by tolusha** [comment]
It is two different cases. In first case you have an opened `<plop>` tag. Camel plugin doesn't sent its diagnostics in this case (the same behavior in VS Code)

In another case the tag is closed and both plugins send its diagnostics as expected. 
Could you check if I miss something?

**Comment by apupier** [comment]
I checked!

and I'm very sorry :'(
In Theia, it is working perfectly fine.

The case in which we don't have the 2 errors reported is "normal" as the Camel Language Server is not supporting malformed xml.

I'm very sorry for the lost time, thank you having a look and spotted my mistake.

**Comment by tsmaeder** [comment]
Sorry folks, but reading the code, this _should not work_. If we have two diagnostics collections with the same name, the code says that we would only ever see one set of diagnostics. That seems to be the case when we use the default diagnostics name. @apupier have you started using an explicit name for the diagnostics collection, for example?

**Comment by tolusha** [comment]
@tsmaeder 
any ideas?

**Comment by apupier** [comment]
> @apupier have you started using an explicit name for the diagnostics collection, for example?

how can I provide an explicit name for diagnostic collections? it seems to be something very internal to Theia. Or it is part of the Language Server protocol? but i have not found anything about that.

**Comment by tsmaeder** [comment]
You can provide a name when you initialize the language client. A conversation with @benoitf has confirmed that this is broken when we run plugins in separate containers. When running locally, all plugins run in the same process, thus generating a different default collection id for each diagnostics collection. When we run as che 7 plugins, we get the same id. So we need to find a way to generate a globally unique id.

**Comment by benoitf** [comment]
we may use v4/ uuid library

**Comment by tolusha** [comment]
Something like `UUID.uuid4()` instead of `nextId++`

**Comment by tsmaeder** [comment]
Yes. In order to test this, we would have to run both extensions in different sidecars. It would be a good idea to first try and reliably reproduce the error to verify that any fix does indeed fix the problem.

**Comment by tolusha** [comment]
tested
https://github.com/theia-ide/theia/pull/5011
