### ISSUE TITLE
Fix Theia language extensions

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4930]
A lot of Theia language extension were broken by this commit: https://github.com/theia-ide/theia/commit/b8633c3fd5f08994c5d97b0e1d00e590b38c62d8

They should be fixed asap cc @simark @marcdumais-work 

It's too late to revert a change it was landed as part of 0.5.0 ~or we need to make bug fix release 0.5.1~ (we cannot some extensions already adjusted).

Look for all usages https://github.com/search?p=2&q=org%3Atheia-ide+%22onDidFailSpawnProcess%22&type=Code
- racket
- haskell
- json
- yaml
- rust
- xml
- xtext

Please don't break language contributions!

**Comment by marcdumais-work** [comment]
I think the breakage happened in this commit: [b174794752](https://github.com/theia-ide/theia/pull/3843/commits/b174794752bace9ce354b8995f59356dccc299aa).

@akosyakov IIUC the way forward is to propagate the new Process API to the broken extensions listed above? 

@marechal-p Can you take care of this?

**Comment by akosyakov** [comment]
@marcdumais-work yes, i don't see other way, reverting will break extensions who already migrated
