### ISSUE TITLE
[json] Auto-closing quotes does not work in JSON files

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4942]
Theia TS/JS:
![screencast 2019-04-18 09-30-03](https://user-images.githubusercontent.com/1405703/56344253-41abc480-61bd-11e9-959f-01a2c34df69f.gif)

Theia JSON:
![screencast 2019-04-18 09-30-58](https://user-images.githubusercontent.com/1405703/56344247-3b1d4d00-61bd-11e9-97e7-fd057829c5ff.gif)

VS Code JSON:
![screencast 2019-04-18 09-31-57](https://user-images.githubusercontent.com/1405703/56344239-35c00280-61bd-11e9-9fdb-bb06dc72ab8a.gif)

Related https://code.visualstudio.com/updates/v1_27#_auto-closing-surrounding-characters?

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/blob/master/packages/json/src/browser/json-grammar-contribution.ts#L33 should be aligned with https://github.com/Microsoft/vscode/blob/master/extensions/json/language-configuration.json
