### ISSUE TITLE
[Plugin-API] Redundant 'CancellationToken' argument is present in each rpc-request

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#4957]
### Description
 
On each rpc-request a new argument 'CancellationToken' is added to the arguments array: 
https://github.com/theia-ide/theia/blob/2a2a6010329850e79b508b2133a62749d2d39e05/packages/plugin-ext/src/api/rpc-protocol.ts#L179-L181

It causes a wrong behavior of `VsCode Git Extention`. On executing some commands, the extension handles received arguments and 'CancellationToken' object influences on the commands result:
https://github.com/Microsoft/vscode/blob/7d39e805fb66a6eac22f19af8bb90f48da863fd5/extensions/git/src/commands.ts#L649-L677

The command handles `resourceStates: SourceControlResourceState[]` It converts the argument to `undefined` and adds to `uri` array. While iterating the array `workspace.openTextDocument(uri)` with `undefined` is applied: https://github.com/Microsoft/vscode/blob/7d39e805fb66a6eac22f19af8bb90f48da863fd5/extensions/git/src/commands.ts#L692

Related Commit: https://github.com/theia-ide/theia/commit/4286ebd7a63f32951ac5a8df85ac788f23a54e0f
Is needed for #4103

@akosyakov  WDYT? 

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
Possible the same as https://github.com/theia-ide/theia/issues/4310

**Comment by akosyakov** [comment]
ok, then we need to pass a boolean flag to indicate whether the cancellation token should be appended
