### ISSUE TITLE
How to debug server of vscode extension

### ISSUE THREAD

**Issue by AlbertXiao1994** [theia-ide/theia#4962]
### Description
I can debug client of vscode extension according to [#3251](https://github.com/theia-ide/theia/issues/3251). Howerver, it seems to not working for server of vscode extension.  My breakpoint cannot be entered.

**OS and Theia version:**
OS 10.14.2 @theia/example-browser 0.5.0

**Comment by AlbertXiao1994** [comment]
The function supported by server of vscode extension seems to not working, such as the completion of vscode extension Vetur

**Comment by marechal-p** [comment]
What is and where is the file you are trying to debug precisely?

**Comment by AlbertXiao1994** [comment]
> What is and where is the file you are trying to debug precisely?

I import vscode ext which has client and server as theia plugin, and I want to debug it. It seems that only client of vscode ext can run.

**Comment by marechal-p** [comment]
> My breakpoint cannot be entered.

What is the path of the file? This might help us understand inside which process it is supposed to run, because for your breakpoints to work you have to be attached to the right process.

Also, what is this extension client/server?

**Comment by AlbertXiao1994** [comment]
> What is the path of the file? This might help us understand inside which process it is supposed to run, because for your breakpoints to work you have to be attached to the right process.

I debug my program according to [#4224 (comment)]{https://github.com/theia-ide/theia/issues/3251}, I get following diagnosis:Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9339).

The path is theia/plugins/**.

![image](https://user-images.githubusercontent.com/23646755/56504406-00b00900-654b-11e9-9c28-eca2dbffa965.png)

**Comment by marechal-p** [comment]
Ok, so it might be because the plugin host process is spawned per client, so I had more luck by tweaking the configuration a bit, notably:

- `"--hosted-plugin-inspect=9339",` becomes `"--hosted-plugin-inspect-brk=9339",`
- add a `timeout` property with at least 1 minute, to give you time to connect with a browser.

By doing this I was able to debug the activation script for the golang extension.

**Comment by akosyakov** [comment]
@AlbertXiao1994 make sure as well that source maps are generated for your VS Code extension

**Comment by AlbertXiao1994** [comment]
It seems that server of VSCode extension should run as Theia extension like typescript language server. By doing it I can migrate the most function of my VSCode extension.
