### ISSUE TITLE
Does theia support to use ssh to git pull code,If not there is an security problem

### ISSUE THREAD

**Issue by 113xiaoji** [theia-ide/theia#4964]
### Description
There is an security  problem. Whether subsequent versions will support?

### Reproduction Steps
git clone ssh url 
![image](https://user-images.githubusercontent.com/31875988/56480666-afbdf780-64ed-11e9-99cc-4fb25f54d3ae.png)

**OS and Theia version:**
theia 0.5.0

**Comment by svenefftinge** [comment]
Theia just runs standard git, so it does support it. But you need to install ssh on your system.
