### ISSUE TITLE
PHP files are not grammatically highlighted

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4966]
### Description
PHP files are not grammatically highlighted

![image](https://user-images.githubusercontent.com/10203793/56491457-232a2e00-651b-11e9-8c63-6c18ee9de53a.png)

### Reproduction Steps
docker image miaowoo/theia:next
open php file

**OS and Theia version:**

**Diagnostics:** 
package.json
```json
{
    "private": true,
    "dependencies": {
        "typescript": "latest",
        "@theia/callhierarchy": "next",
        "@theia/core": "next",
        "@theia/cpp": "next",
        "@theia/docker": "next",
        "@theia/editor": "next",
        "@theia/editorconfig": "next",
        "@theia/editor-preview": "next",
        "@theia/extension-manager": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/git": "next",
        "@theia/go": "next",
        "@theia/getting-started": "next",
        "@theia/java": "next",
        "@theia/java-debug": "next",
        "@theia/json": "next",
        "@theia/yaml": "next",
        "@theia/keymaps": "next",
        "@theia/languages": "next",
        "@theia/markers": "next",
        "@theia/merge-conflicts": "next",
        "@theia/messages": "next",
        "@theia/metrics": "next",
        "@theia/mini-browser": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/debug-nodejs": "next",
        "@theia/outline-view": "next",
        "@theia/php": "next",
        "@theia/output": "next",
        "@theia/plantuml": "next",
        "@theia/plugin": "next",
        "@theia/plugin-ext": "next",
        "@theia/plugin-ext-vscode": "next",
        "@theia/preferences": "next",
        "@theia/preview": "next",
        "@theia/process": "next",
        "@theia/python": "next",
        "@theia/ruby": "next",
        "@theia/rust": "next",
        "@theia/search-in-workspace": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/textmate-grammars": "next",
        "@theia/tslint": "next",
        "@theia/typescript": "next",
        "@theia/userstorage": "next",
        "@theia/variable-resolver": "next",
        "@theia/workspace": "next",
        "@devpodio/theia-vue-extension": "0.2.1"
    },
    "devDependencies": {
        "@theia/cli": "next"
    }
}
```

**Comment by akosyakov** [comment]
It is indeed bogusly highlighted on master compare to VS Code. It's a regression.

VS Code:
<img width="603" alt="Screen Shot 2019-04-23 at 06 23 08" src="https://user-images.githubusercontent.com/3082655/56553967-7094b280-6590-11e9-9cf9-c4566f9b9bec.png">

Theia:
<img width="671" alt="Screen Shot 2019-04-23 at 06 23 03" src="https://user-images.githubusercontent.com/3082655/56553968-7094b280-6590-11e9-85c0-df2786334f90.png">

**Comment by akosyakov** [comment]
@502647092 You don't get syntax highlighting at all? 

I get some, although not like in VS Code. textmate grammars are identical, don't have an idea yet what causing the difference. @svenefftinge maybe you know?

**Comment by 502647092** [comment]
@akosyakov this image not use vscode plugin
it use `@theia/php`
you can look package.json
only php not have syntax highlighting

**Comment by designerbase** [comment]
@akosyakov  Yes boss i am facing the same issue, PHP syntax are not highlighting yet. you have the the dockerFile which works the php perfectly ?

**Comment by akosyakov** [comment]
@designerbase i would be glad to look into it, but i cannot reproduce it with master state:
<img width="1938" alt="Screen Shot 2019-05-29 at 07 36 09" src="https://user-images.githubusercontent.com/3082655/58531990-7e1f0700-81e4-11e9-8655-ba0ea301aaf9.png">

**Comment by designerbase** [comment]
@akosyakov seems your project working perfect.. 

here i am sharing my Dockerfile and package.json file, please have a looking into it boss,

Dockerfile

FROM node:8-jessie-slim

ENV TZ=india/kolkata
ENV UID=10000
ENV GID=1002

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update && apt-get -y --no-install-recommends install sudo curl xz-utils wget git python build-essential \
    && apt install -y --no-install-recommends ca-certificates apt-transport-https \
    && wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add - \
    && echo "deb https://packages.sury.org/php/ jessie main" | tee /etc/apt/sources.list.d/php.list \
    && apt update \
    && apt install -y --no-install-recommends php7.2 \
    && apt install -y --no-install-recommends php7.2-cli php7.2-curl php7.2-json php7.2-mbstring \
    && curl -s -o composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --gid $GID theia \
    && adduser --disabled-password --gecos '' --uid $UID --gid $GID theia \
    && adduser theia sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && chmod g+rw /home \
    && mkdir -p /home/project \
    && chown -R theia:theia /home/theia \
    && chown -R theia:theia /home/project

USER theia

WORKDIR /home/theia
ADD package.json ./package.json

RUN yarn --cache-folder ./ycache \
    && rm -rf ./ycache \
    && NODE_OPTIONS="--max_old_space_size=4096" yarn theia build

EXPOSE 3000
ENV SHELL /bin/bash

ENTRYPOINT [ "yarn", "theia", "start", "/home/project", "--hostname=0.0.0.0" ]




package.json

{
    "private": true,
    "dependencies": {
        "typescript": "latest",
        "@theia/core": "next",
        "@theia/editor": "next",
        "@theia/editorconfig": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/git": "next",
        "@theia/json": "next",
        "@theia/keymaps": "next",
        "@theia/languages": "next",
        "@theia/markers": "next",
        "@theia/merge-conflicts": "next",
        "@theia/plugin-ext": "next",
        "@theia/plugin-ext-vscode": "next",
        "@theia/messages": "next",
        "@theia/mini-browser": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/outline-view": "next",
        "@theia/php": "next",
        "@theia/output": "next",
        "@theia/preferences": "next",
        "@theia/textmate-grammars": "next",
        "@theia/process": "next",
        "@theia/search-in-workspace": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/tslint": "next",
        "@theia/typescript": "next",
        "@theia/userstorage": "next",
        "@theia/workspace": "next"
    },
    "devDependencies": {
        "@theia/cli": "next",
        "lerna": "2.4.0",
        "rimraf": "latest",
        "typescript": "latest"
    }
}

**Comment by akosyakov** [comment]
I was able to reproduce with your package.json.

onigasm reporting the following error in browser console:
```
Uncaught Error: 105,110,118,97,108,105,100,32,99,111,100,101,32,112,111,105,110,116,32,118,97,108,117,101

Error: 105,110,118,97,108,105,100,32,99,111,100,101,32,112,111,105,110,116,32,118,97,108,117,101
    at OnigScanner.findNextMatchSync (/21.bundle.js:1958)
    at matchRule (/21.bundle.js:5994)
    at matchRuleOrInjections (/21.bundle.js:6012)
    at scanNext (/21.bundle.js:6102)
    at _tokenizeString (/21.bundle.js:6095)
    at Grammar._tokenize (/21.bundle.js:5851)
    at Grammar.tokenizeLine2 (/21.bundle.js:5821)
    at Object.tokenizeEncoded (/21.bundle.js:834)
    at EncodedTokenizationSupport2Adapter.tokenize2 (/vs/editor/editor.main.js:111928)
    at ModelLinesTokens._updateTokensUntilLine (/vs/editor/editor.main.js:56792)
    at /vs/editor/editor.main.js:12536
```

i am having hard time to understand what's going wrong. cc @svenefftinge @NeekSandhu maybe you know what is the cause

**Comment by designerbase** [comment]
@akosyakov  Yes i am facing the same issue in the console. when we type something in the editor, the error throws, but when i removed the "@theia/textmate-grammars": "next"  from the package.json , the error will go, but not highlight the syntax. 

thanks for helping....

**Comment by akosyakov** [comment]
Minimal package.json to reproduce:
```
{
    "private": true,
    "dependencies": {
        "@theia/preferences": "next",
        "@theia/messages": "next",
        "@theia/textmate-grammars": "next"
    },
    "devDependencies": {
        "@theia/cli": "next"
    }
}
```
and then
```
yarn && yarn theia build --mode=development && yarn theia start .
```

**Comment by akosyakov** [comment]
I've tracked it down to pinning onigasm to 2.2.1 resolves the issue. It's only broken in 2.2.2 cc @NeekSandhu

**Comment by akosyakov** [comment]
As a workaround you can use [yarn resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions) to pin onigasm to 2.2.1.

**Comment by designerbase** [comment]
@akosyakov is there any solution for now?

**Comment by akosyakov** [comment]
@designerbase see https://github.com/theia-ide/theia/issues/4966#issuecomment-496851320

**Comment by designerbase** [comment]
@akosyakov  thanks  its worked!!!
