### ISSUE TITLE
Electron app shows empty window (Starting express on port 'undefined')

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#497]
Using master as of today.
Node v7.10.0
npm@4.5.0
Ubuntu 16.04
yarn && yarn run rebuild:electron && cd examples/electron && yarn run start

In the console I see:
"Starting express on port 'undefined'."

![electron](https://user-images.githubusercontent.com/311730/30282366-19a5e0b6-96e3-11e7-8b69-66b120c255bf.png)

**Comment by hexa00** [comment]
Confirmed here too.

**Comment by hexa00** [comment]
Very strange even connecting a browser to the port shows an empty window even if the proper html is sent.

**Comment by hexa00** [comment]
@akosyakov I was not aware this was important could you explain what makes it important ?
How you figured this was the issue ?

Thanks,

**Comment by akosyakov** [comment]
When https://github.com/theia-ide/theia/issues/369 is done, it won't be important but until then the generator relies on the order of dependencies to generate the startup scripts.

**Comment by hexa00** [comment]
Haa ok :) thx!
