### ISSUE TITLE
TreeView fails if TreeItem object contains circular references

### ISSUE THREAD

**Issue by tetchel** [theia-ide/theia#4975]
### Description
 
Theia's TreeView API fails to display an extension's tree if an object to be converted to a TreeItem contains circular references. 
Running [my VS Code extension](https://github.com/microclimate-dev2ops/microclimate-vscode-tools) in Theia fails to show the TreeView in all but the simplest case. In the Theia logs, I see this message interspersed with the output from my tree-building code:
```
root ERROR [hosted-plugin: 40579] [ERRO: 13:12:22.031 extension.js.on():32]: Unhandled promise rejection: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.replyOK (/Users/tim/programs/clones/theia/packages/plugin-ext/lib/api/rpc-protocol.js:274:103)
    at /Users/tim/programs/clones/theia/packages/plugin-ext/lib/api/rpc-protocol.js:152:51
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The error is generated by that file trying to `JSON.stringify` my complex tree objects, which do contain circular references.

### Reproduction Steps

You need [Microclimate installed](https://microclimate-dev2ops.github.io/mdt-vsc-getting-started#doc) to use the extension, so hopefully the description above is enough.
1. Clone https://github.com/microclimate-dev2ops/microclimate-vscode-tools
2. Checkout the `theia` branch
3. Run `cd dev && vsce package` to build the vsix.
4. Copy the vsix into `$theia_clone/plugins`
5. Run the browser example. You will see that error message in the console output when the TreeView is rendered.

**OS and Theia version:**
macOS
Latest theia (built from master)

To fix this, we should use [`flatted.stringify`](https://www.npmjs.com/package/flatted) instead, which will flatten circular references. I have this working, and I'm putting together a PR with the fix. 
However, this means all JSON-to-string conversions on both the client and server ends will have to be done with `flatted` (you can't JSON.parse something that was stringified with `flatted`, or vice-versa), so this might not be so straightforward.

**Comment by tetchel** [comment]
I see now that Theia uses `vscode-jsonrpc`, so replacing `JSON.(stringify|parse)` with `flatted` won't be sufficient. We will have to dive into how VS Code solves this problem. 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/common/rpcProtocol.ts

**Comment by akosyakov** [comment]
> To fix this, we should use flatted.stringify instead, which will flatten circular references. I have this working, and I'm putting together a PR with the fix.
However, this means all JSON-to-string conversions on both the client and server ends will have to be done with flatted (you can't JSON.parse something that was stringified with flatted, or vice-versa), so this might not be so straightforward.

I don't like it. We should look at concrete data structure and see how to get rid of a cycle at serialization time and restore at deserialization.

**Comment by tetchel** [comment]
I think that using flatted (or its predecessor circular-json) is a pretty well-established solution to this problem. Custom replacers would work great, but they need to be written ad-hoc and we can't predict every extensions' potential needs.

I'm all ears for alternative solutions :P

**Comment by akosyakov** [comment]
Going VS Code way should be all right, i.e. https://github.com/Microsoft/vscode/blob/0fde6619172c9f04c41f2e816479e432cc974b8b/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L22-L28

cc @benoitf good with you?

**Comment by tetchel** [comment]
I created a sample for reproducing this, see https://github.com/tetchel/theia-tree-bug

**Comment by akosyakov** [comment]
VS Code extension are better that we can try against VS Code and Theia.

**Comment by tetchel** [comment]
Good point. I updated the example to target vs code instead. The original is now the theia branch.

**Comment by tetchel** [comment]
Hey @akosyakov @benoitf -

Sorry to ping you guys, but we're wondering about the status of this issue. Is there interest from your team in working on this anytime soon (say, in the next month), or are we on our own?

In general, we are definitely interested in contributing to this project, as we are looking to invest in and make use of Theia. However, this seems like a very core part of Theia that needs to be overhauled to fix this bug, and I'm not sure I'm the best fit to tackle this as my first issue!

Let me know.

**Comment by akosyakov** [comment]
@tetchel go ahead and open a PR, i have it on my list but not as a first priority, sorry
