### ISSUE TITLE
Commands invoked from TreeView context menu do not pass the object to the command handler

### ISSUE THREAD

**Issue by tetchel** [theia-ide/theia#4978]
### Description
 
In VS Code, if a command is run from right-clicking an item in a TreeView, the object that provided that TreeItem is passed to the command handler. [vs code doc](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)
[My extension](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/) uses this feature in almost every command, such as [this command](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/blob/theia/dev/src/command/OpenInBrowserCmd.ts#L25).
The handlers are registered [in this file](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/blob/theia/dev/src/command/CommandUtil.ts#L42).
From the `OpenInBrowserCmd` (first link), you see that I expect the resource passed to be `Project | Connection`, as these are the two types of objects that are displayed in my TreeView. This works great in VS Code.

But in Theia, the resource passed is instead a string roughly outlining the item's position and indices in the tree. This will cause extensions' commands like mine to fail to work in Theia because they rely on that context. 

I plan to refactor my extension to use the TreeView selection events to infer the currently selected project/connection. But I expect mine is not the only extension to use this behaviour from VS Code, so Theia should implement this feature to allow more extensions to work with minimal friction.

### Reproduction Steps

You need [Microclimate installed](https://microclimate-dev2ops.github.io/mdt-vsc-getting-started#doc) to use the extension, so hopefully the description above is enough.
1. Clone https://github.com/microclimate-dev2ops/microclimate-vscode-tools
2. `cd microclimate-vscode-tools/dev && vsce package`
3. Copy the vsix into $theia_clone/plugins
4. Run the browser example
5. Open the Microclimate tree and right-click run Open in Browser
6. Observe that the command doesn't work, and the output prints the unexpected object.

**OS and Theia version:**
macOS 
Latest theia (built from master)

**Comment by akosyakov** [comment]
@tetchel you can also look into fixing it in Theia then you don't have to adjust your extension. PRs are welcomed

**Comment by tetchel** [comment]
I took a look into fixing this, I think it is a symptom of #4975

**Comment by akosyakov** [comment]
Function are not capable to survive serialization/deserialization: instead of sending tree elements back as args. we should send its id, retrieve the original object and pass it as an argument.

It is not related to circular references.
