### ISSUE TITLE
Syntax highlighting not working in extension mode

### ISSUE THREAD

**Issue by lancemao** [theia-ide/theia#4979]
when using these steps to build theia IDE
https://www.theia-ide.org/doc/Composing_Applications.html
everything works fine

however, when build a hello-world extension described here:
https://www.theia-ide.org/doc/Authoring_Extensions.html
the syntax highlighting is not working, at least for Java, Javascript. Seems like JSON is working fine

OS: Mac
@theia/core version: 0.5.0

**Comment by akosyakov** [comment]
You should add [@theia/textmate-grammars](https://www.npmjs.com/package/@theia/textmate-grammars) to your app.

**Comment by vince-fugnitto** [comment]
Closing thanks to https://github.com/theia-ide/generator-theia-extension/pull/31

**Comment by quirinpa** [comment]
I get a node-gyp error trying to build @theia/node-pty when trying to install @theia/textmate-grammars so I can't check that this solution fixes syntax highlighting in my case. I've used https://www.theia-ide.org/doc/Composing_Applications.html and I still got no syntax highlighting (javascript).

**Comment by vince-fugnitto** [comment]
> I get a node-gyp error trying to build @theia/node-pty when trying to install @theia/textmate-grammars so I can't check that this solution fixes syntax highlighting in my case. I've used https://www.theia-ide.org/doc/Composing_Applications.html and I still got no syntax highlighting (javascript). I find it strange that in the theia repository itself, examples/browser/package.json doesn't reference @theia/textmate-grammars.

@quirinpa `@theia/textmate-grammars` has been deprecated for some time now (since `v0.16.0`):

> [textmate-grammars] removed the @theia/textmate-grammars extension #6933
>   - The extension will no longer be maintained by the project and remains in the Git history for anyone who would like to reference it or maintain it.

Syntax-highlighting is now contributed by vscode plugins.

**Comment by quirinpa** [comment]
Thanks for the information @vince-fugnitto. In that case shouldn't the "vscode-builtin-javascript" give me js syntax highlighting? It is listed in my package.json theiaPlugins..

**Comment by vince-fugnitto** [comment]
> Thanks for the information @vince-fugnitto. In that case shouldn't the "vscode-builtin-javascript" give me js syntax highlighting? It is listed in my package.json theiaPlugins..

Given you have plugin support (through the appropriate extensions), the `vscode-builtin-javascript` plugin should provide you with javascript syntax highlighting:

https://github.com/eclipse-theia/theia/blob/43a6b62ef8cbb57413ca75a783bbcd69f57578f9/package.json#L112

**Comment by quirinpa** [comment]
Thanks. I have copied and pasted the second example package.json file in https://www.theia-ide.org/doc/Composing_Applications.html. So i got the "@theia/plugin-ext-vscode" extension.. Shouldn't this be enough?

**Comment by vince-fugnitto** [comment]
> Thanks. I have copied and pasted the second example package.json file in https://www.theia-ide.org/doc/Composing_Applications.html. So i got the "@theia/plugin-ext-vscode" extension.. Shouldn't this be enough?

It should be, you can confirm you actually have the plugin present under the `plugins` folder (which should be downloaded by the script). When starting the application, and opening a js file you should have syntax highlighting.

**Comment by quirinpa** [comment]
It is present. But I have no syntax highlighting. Weird. Maybe I messed up somehow, but I simply followed the tutorial. Thank you very much for your quick replies. Should I open a new issue?

**Comment by vince-fugnitto** [comment]
> It is present. But I have no syntax highlighting. Weird. Maybe I messed up somehow, but I simply followed the tutorial. Thank you very much for your quick replies. Should I open a new issue?

@quirinpa I was able to confirm the example works on my end:

- `yarn`
- `yarn start`

In the `plugins` view I see the plugins present (`view` > `plugins`):

![image](https://user-images.githubusercontent.com/40359487/132528188-faca5c7a-4927-4c00-b51d-3f6f43b94534.png)

and I have syntax highlighting present:

![image](https://user-images.githubusercontent.com/40359487/132528437-07c45db6-4bc4-47c3-ad38-0040fa29b98b.png)

**Comment by quirinpa** [comment]
Theia wasn't seeing any plugins. I was doing "yarn theia start" without arguments so that's why. I'm sorry for the rookie mistake.  Running "yarn start" fixes this. Thanks.
