### ISSUE TITLE
keybinding for last edit location is broken

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4982]
cc @spoenemann could be related to recent keybindings changes?

**Comment by spoenemann** [comment]
It works for me. Which keyboard layout, browser, language setting do you use?

**Comment by spoenemann** [comment]
Chrome disables the `navigator.keyboard` API if the connection is not secure. In that case we fall back to detecting the keyboard layout based on the language, which in your case is English, which is a mismatch with the German keyboard (same for me).

The situation will improve once we have #4879.
