### ISSUE TITLE
[not an issue] [do not delete] Images

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#4990]
This is an issue used as a work-around for the lack of file upload for the GH wiki. We can add images in this issue and then reference them from the wiki, instead of adding them to the repo or hosting them somewhere else.

the idea came from here: https://ardalis.com/add-images-easily-to-github

**Comment by marcdumais-work** [comment]
![obtain-package-lock-json](https://user-images.githubusercontent.com/25749063/56670013-107d3980-6680-11e9-94e1-112e7e02dba8.gif)

**Comment by akosyakov** [comment]
@marcdumais-work links are permanent, you don't need to create an issue, just wait for upload to GitHub and then you can copy a link from a comment and use it.

**Comment by marcdumais-work** [comment]
@akosyakov are you sure they do not perform "garbage collection" once in a while? Or maybe they'll keep anything that's referenced from somewhere?

**Comment by akosyakov** [comment]
@marcdumais-work then so many of my images would be broken 🤣

**Comment by marcdumais-work** [comment]
@akosyakov You're probably correct that closing the issue would not affect anything - I was more scared if it was deleted altogether. Closing.
