### ISSUE TITLE
As an extension developer I want to add any custom React widget to the tab-bar toolbar

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4991]
Regarding the UI, I had something like this in mind.
![Screen Shot 2019-04-24 at 17 12 57](https://user-images.githubusercontent.com/1405703/56671059-36243600-66b4-11e9-996c-f35fb7cdbba8.jpg)

**Comment by vince-fugnitto** [comment]
I believe it also addresses https://github.com/theia-ide/theia/issues/4701 :)
