### ISSUE TITLE
error TS2307: Cannot find module 'native-keymap'. with Theia@next 

### ISSUE THREAD

**Issue by vazexqi** [theia-ide/theia#4994]
### Description

```
my-extension: $ tsc
my-extension: ../node_modules/@theia/core/lib/common/keyboard/keyboard-layout-provider.d.ts(16,55): error TS2307: Cannot find module 'native-keymap'.
```

### Reproduction Steps

I am almost certain that this is because of https://github.com/theia-ide/theia/pull/4873/files. This removed the native-keymap as dependency from core. 

1. mkdir my-extension && cd my-extension
1. yo theia-extension --theia-version=next 

```
my-extension: > my-extension@0.0.0 prepare /Users/nchen/Development/webide/my-extension/my-extension
my-extension: > yarn run clean && yarn run build
my-extension: yarn run v1.13.0
my-extension: warning package.json: No license field
my-extension: $ rimraf lib
my-extension: Done in 0.84s.
my-extension: yarn run v1.13.0
my-extension: warning package.json: No license field
my-extension: $ tsc
my-extension: ../node_modules/@theia/core/lib/common/keyboard/keyboard-layout-provider.d.ts(16,55): error TS2307: Cannot find module 'native-keymap'.
my-extension: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
my-extension: error Command failed with exit code 2.
my-extension: npm ERR! code ELIFECYCLE
my-extension: npm ERR! errno 1
my-extension: npm ERR! my-extension@0.0.0 prepare: `yarn run clean && yarn run build`
my-extension: npm ERR! Exit status 1
my-extension: npm ERR! 
my-extension: npm ERR! Failed at the my-extension@0.0.0 prepare script.
my-extension: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
my-extension: npm ERR! A complete log of this run can be found in:
my-extension: npm ERR!     /Users/nchen/.npm/_logs/2019-04-24T23_56_43_845Z-debug.log
```

**OS and Theia version:** Mac OS X on Theia@next

Note: Doing the same steps with `yo theia-extension` (using latest instead of next) works.

**Comment by akosyakov** [comment]
native-keymap dep makes sense only for electron target, so it was removed. You should install `@theia/electron` for your electron app as a dependency explicitly.

**Comment by vazexqi** [comment]
Sorry let me be clearer. I’m not building an electron app. I’m only interested in a browser-based IDE. 

If you repeat the steps above and generate only a browser-based app you will also see the issue. 

It seems that adding @theia/core as a dependency, which is required for browser-based IDE, will cause that issue. 

It seems that based on what you said, if I am only interested in building a browser-based IDE this shouldn’t be an issue. However it is right now. 

Does the generator itself need updating? Maybe it is listing a dependency that is no longer needed with Theia@next.

**Comment by akosyakov** [comment]
Wonder why we don't get this issue in our products and in theia-apps. They are already running on next without electron deps perfectly fine.

> Does the generator itself need updating? Maybe it is listing a dependency that is no longer needed with Theia@next.

maybe

**Comment by akosyakov** [comment]
I've created an issue there to investigate: https://github.com/theia-ide/generator-theia-extension/issues/29

**Comment by akosyakov** [comment]
@vazexqi Could you try to add `skipLibCheck: true` to your tsconfig? it could be that tsc tries to compile d.ts files from theia extensions and cannot compile electron files (even though you don't need them).

**Comment by vazexqi** [comment]
Yes, that fixes it. Thanks!

I was basing my own tsconfig.json off the one from generator-theia-extension. 

I took a closer look at https://github.com/theia-ide/theia/blob/master/configs/base.tsconfig.json and opened https://github.com/theia-ide/generator-theia-extension/pull/30 to update the tsconfig.json.
