### ISSUE TITLE
[git history]When git-history tab is current tab, click View-Git History can't close git-history tab

### ISSUE THREAD

**Issue by zixuemeng** [theia-ide/theia#4996]
### Description
When git-history tab is current tab, click View-Git History can't close git-history tab, while Git，Search and other tab can close.

**Diagnostics:** 

![git-history](https://user-images.githubusercontent.com/7857086/56706232-cca13780-6746-11e9-9167-f9c24c9c83f9.gif)

**Comment by vince-fugnitto** [comment]
I wonder why it was designed that way based on the following [comment](https://github.com/theia-ide/theia/issues/1727#issuecomment-382306601). 

Also, potential duplication of https://github.com/theia-ide/theia/issues/1727,

**Comment by akosyakov** [comment]
@vince-fugnitto Have you seen my comment on the PR: https://github.com/theia-ide/theia/pull/4997#issuecomment-486520599

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Have you seen my comment on the PR: [#4997 (comment)](https://github.com/theia-ide/theia/pull/4997#issuecomment-486520599)

Yes I saw, I'm not quite sure what the best solution might be at the moment.
