### ISSUE TITLE
Could firefox 42.0 be supported? 

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#500]
At the moment, trying to start Theia in Firefox 42 (~2 years old) results in a blank page. In the developers tools, looking at the console, I see the following error: "SyntaxError: let is a reserved identifier bundle.js:8102:8"

It looks like this old FF does not support  the "let" keyword. 
https://stackoverflow.com/questions/33198379/syntaxerror-let-is-a-reserved-identifier-on-firefox

Is there anything we could do? Would we need to transpile to an older ES version? And if so, I guess other things could break?

**Comment by MarkZ3** [comment]
I was curious about whether or not this version was still supported by Mozilla and I only found this picture 
https://www.mozilla.org/media/img/firefox/organizations/release-overview-high-res.78cf477dd915.png

Probably Theia shouldn't officially aim to support it but it would be good to have a work around

**Comment by marcdumais-work** [comment]
Maybe someone can correct me if I'm wrong, but my understanding is that we are aiming for the "sweet spot" of having the TS/JS features that we use being natively supported by our targeted, "modern" web browsers. 

It's of course theoretically possible to have [polyfills](https://en.wikipedia.org/wiki/Polyfill) or such in place to support features even if the browser doesn't, but this adds friction (bugs, work-arounds, increased support requests) that we probably do not have the resources to handle ATM.

**Comment by marcdumais-work** [comment]
There probably is not much appetite to have Theia running on older version of browsers. Closing.
