### ISSUE TITLE
[languages] TS import quick fix does not work anymore

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#5002]
#### Description
I am unable to get quick fix (code actions) to work in TypeScript.

#### Reproduction Steps
> Illustration: [Workspace setup on Gitpod](https://gitpod.io#snapshot/9ac47d22-e3b5-4a35-a777-153ba65d7974).

I removed the `injectable` import in [core/src/browser/about-dialog.ts](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/about-dialog.ts)

You should not be able to add it back using quick fix.

#### OS and Theia version
Ubuntu/Firefox - master as of https://github.com/theia-ide/theia/commit/09559a995efd4414cfc21bc9518d24bee4ddaa33

**Comment by vince-fugnitto** [comment]
I can confirm it is also broken for:
- Ubuntu/Chrome -  master as of 09559a9
- macOS -  master as of 09559a9

**Comment by akosyakov** [comment]
Which TS version?

**Comment by marechal-p** [comment]
`2.9.2` and `3.1.3` according to the linked Gitpod workspace.

**Comment by akosyakov** [comment]
@marechal-p it is caused by recent changes in workspace apply edit:
<img width="1843" alt="Screen Shot 2019-04-26 at 17 48 29" src="https://user-images.githubusercontent.com/3082655/56820198-8da8da00-684b-11e9-8a62-bc4946857998.png">

One need to investigate how it happens that editor version is different without any changes.

**Comment by vince-fugnitto** [comment]
Do you know why the editor version is different without any changes @JanKoehnlein?
When checking if the versions are equal the following is `false`.

https://github.com/theia-ide/theia/blob/61cf13d28e5d96da71bd5b606896fe0f99efd3c7/packages/monaco/src/browser/monaco-workspace.ts#L317

It seems to be introduced from https://github.com/theia-ide/theia/pull/4553.

**Comment by JanKoehnlein** [comment]
@vince-fugnitto no idea. Looks like a bug in typescript-language-server. Needs debugging to find out where it changes the document version without any file changes happening.

**Comment by svenefftinge** [comment]
I have fixed it in typescript-language server. Now publishing and updating here.
