### ISSUE TITLE
[bug]there is something wrong of snippets 

### ISSUE THREAD

**Issue by AlbertXiao1994** [theia-ide/theia#5004]
### Description
when I input prefix of ts snippets, the priority of result is too low and prefix cannot replaced as expected.

![2](https://user-images.githubusercontent.com/23646755/56786324-3b57c100-682b-11e9-924a-6ac3b8734310.gif)

**OS and Theia version:**
OS v10.14.2 Theia v0.5.0

**Comment by akosyakov** [comment]
a dup of https://github.com/theia-ide/theia/issues/4208
