### ISSUE TITLE
[alert-message] remove unnecessary alert-message container padding

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5018]
**Description**
The `alert-message` container has unnecessary padding which results in inconsistent alignment in widgets.

The following container padding, can be viewed when opening a workspace not under source control for example.

https://github.com/theia-ide/theia/blob/3ddca955fe7f9b371c94086871838c0c99d1a870/packages/core/src/browser/style/alert-messages.css#L23-L25

<div align='center'>

![Screenshot from 2019-04-26 09-50-15](https://user-images.githubusercontent.com/40359487/56814235-bbbaf980-680c-11e9-86f8-e59d6167529a.png)

</div>

**Comment by sauny** [comment]
I take it no-one has picked this up... mind if I give it a go?

**Comment by vince-fugnitto** [comment]
> I take it no-one has picked this up... mind if I give it a go?

Sure !! 😊

**Comment by sauny** [comment]
@vince-fugnitto I think I did that right.... there should be a PR for it now
