### ISSUE TITLE
Default indentation for 'Makefile' files is not <tab>

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#5026]
### Description

Makefile should use \<tab\> for indentation, like how viscode behaves.

### Reproduction Steps

- Create a new file named Makefile;
- Input \<tab\>;
- Check indentation.

**OS and Theia version:**

All platform, with Theia version 0.5.0

**Diagnostics:** 

- None

**Comment by a1994846931931** [comment]
And I've tried the following configuration, but it doesn't work:

```json
  "[makefile]": {
    "editor.insertSpaces": false
  },
```

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/issues/5026#issuecomment-487334500 is a bug: https://github.com/theia-ide/theia/issues/5031

**Comment by akosyakov** [comment]
@a1994846931931 see https://github.com/theia-ide/theia/issues/5031#issuecomment-487451363

**Comment by a1994846931931** [comment]
@akosyakov Yes, it works.
