### ISSUE TITLE
add select for compare function like vscode

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5028]
### Description
![image](https://user-images.githubusercontent.com/10203793/56857769-06bb4500-69a4-11e9-8884-82e2fad63d35.png)

**Comment by sauny** [comment]
Was having a look into this and (whilst I am still learning) I think I can probably give it a good stab.

I have looked around the navigator package, but don't feel that this sits well within it... happy to be corrected on that though.

So I thought I would start a new package for it, but can't work out how to load a new package from packages/ into theia when running it locally.  As I said, I am still learning so this may be the wrong way to go about this!

@akosyakov : any chance you can help?
