### ISSUE TITLE
No "run build task" on Theia

### ISSUE THREAD

**Issue by DoroNahari** [theia-ide/theia#5029]
### Description
In vscode there is a command Tasks: Run Build Task (https://code.visualstudio.com/docs/editor/tasks)
I can't find it or an equivalent in Theia.
Is that command should be on Theia?

**Comment by akosyakov** [comment]
cc @elaihau in scope of https://github.com/theia-ide/theia/issues/4212

**Comment by DoroNahari** [comment]
Ok, I will follow #4212
