### ISSUE TITLE
Diff Editor Support

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#503]
An open handler for diff editors should be registered from within the monaco package.
For the uri, we should use something simple like `diff:/caption` and the options need to contain the two uris, as well as other options that the monaco diff editor exposes.

**Comment by akosyakov** [comment]
> other options that the monaco diff editor exposes.

I am not sure about this, e.g. whether editors are read-only or not should be decided internally based on resources.

**Comment by svenefftinge** [comment]
I was thinking of options like `renderSideBySide` as declared here https://github.com/Microsoft/monaco-editor/blob/4930b6a/monaco.d.ts#L3100

**Comment by svenefftinge** [comment]
Fixed with #392
