### ISSUE TITLE
[editor-preview] preview editor does not have focus or selection when opening

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5035]
**Description**

When opening a `preview-editor`, the editor is not activated, focused and does not have selection (cursor within the editor). This results in issues such as #5027 and is overall annoying for end users.

**Steps to reproduce**
1. Ensure that the preference `editor.enablePreview` is enabled.
2. Open a preview-editor (single click a file from the explorer).
3. Notice that the editor is **not active**, nor is a cursor placed within the editor.
4. Open an editor normally (double click a file from the explorer).
5. Notice that the editor is **active**, and has a cursor placed within the editor.

**Comment by akosyakov** [comment]
I'm not sure that it is a bug, i think in idea was that one can go through files in the tree and preview them without loosing the focus, i.e. navigator or git.

**Comment by vince-fugnitto** [comment]
> I'm not sure that it is a bug, i think in idea was that one can go through files in the tree and preview them without loosing the focus, i.e. navigator or git.

Ahh I see, the same is seen in vscode, there is however still the issue where the language mode among other things not being present unless the editor has focus.
