### ISSUE TITLE
Running vscode-extension-samples/tree-view-example

### ISSUE THREAD

**Issue by ibmerpaige** [theia-ide/theia#5053]
### Description
I get the following error messages when trying to execute the tree-view-example under the Theia master:

```
root WARN Plugin contributes items to a menu with invalid identifier: view/title
root INFO Config file tasks.json does not exist under file:///c%3A/Users/PaigeSullivan/WebstormProjects/vscode-extension-samples
root INFO [hosted-plugin: 7088] PLUGIN_HOST(7088) starting instance

root INFO [hosted-plugin: 7088] PLUGIN_HOST(7088): PluginManagerExtImpl/init()

root INFO [hosted-plugin: 7088] PLUGIN_HOST(7088): initializing(C:\Users\PaigeSullivan\WebstormProjects\theia\packages\plugin-ex
t-vscode\lib\node/plugin-vscode-init.js)

root INFO [hosted-plugin: 7088] PLUGIN_HOST(7088): PluginManagerExtImpl/loadPlugin(C:\Users\PaigeSullivan\WebstormProjects\theia
\plugins\tree-view-sample\out\extension.js)

root ERROR [hosted-plugin: 7088] Could not identify plugin for 'Theia' require call from C:\Users\PaigeSullivan\WebstormProjects
\theia\plugins\tree-view-sample\out\extension.js
```

### Reproduction Steps
1.  Clone theia master branch
2.  Clone microsoft/vscode-extension-examples
3.  Move tree-view-sample/ to theia/plugins
4.  Start Theia

**OS and Theia version:**

Windows 10x64, theia master branch

**Diagnostics:** 
See above

**Comment by akosyakov** [comment]
@ibmerpaige thank you for the issue, would you be able to have a look? not many of os uses windows, it's hard to track down bugs because of it. The typical issue on a windows bogusly retrieved paths; i.e. a frontend always should send normalized URIs and backend uses FileURI.fsPath to extract a os specific path. I'm not sure though that it's am issue here.

**Comment by ibmerpaige** [comment]
Okay, I will look at that and see if I can get it working.  I'm happy to help out anyway I can to bring full compatibility with VS Code extensions.
