### ISSUE TITLE
[shell] view containers and tabs

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5058]
Views and view container are the central components used by VS Code for UI contribu-
tions. Move the existing implementation from the plug-in system to core and
enhance it so it can be used everywhere in Theia.

As part of this we should add features and behavior to match their VS Code
counterpart as well as refactoring the existing widgets to use them.

View Container should become a special sort of widget with the following features:
- Can contain any number of Views
- Allows to show/hide contained views
- Allows to reorder the views through drag n’ drop

Features to add for View containers:
- The collapse behavior from VS Code shall be implemented
- Support toolbar actions

-----
TODOs:
 - [x] [[debug][ui/ux] Align the Debug View with VS Code](https://github.com/theia-ide/theia/issues/5175)

**Comment by akosyakov** [comment]
It has to be completed to support `onView` activation event properly.

**Comment by akosyakov** [comment]
@kittaakos Would you mind if i finish integration in the plugin system?

**Comment by kittaakos** [comment]
> Would you mind if i finish integration in the plugin system?

Please, thank you!

**Comment by akosyakov** [comment]
It was addressed by https://github.com/theia-ide/theia/pull/5665
