### ISSUE TITLE
[preferences] bogus initial preference group

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5066]
**Description**

There is a bogus preference group node which does not contain any child preferences.

<img width="387" alt="Screen Shot 2019-05-02 at 2 45 49 PM" src="https://user-images.githubusercontent.com/40359487/57098920-32fafc80-6ce9-11e9-9a25-3f9d70725892.png">

**Steps to reproduce**
1. Open the `preferences` widget (<kbd>F1</kbd> and select `Settings: Open Preferences`).
2. Notice the bogus group node.

Theia as of  c2e2308 (no plugins present).

**Comment by vince-fugnitto** [comment]
It has to do with the following preference:
https://github.com/theia-ide/theia/blob/c2e23083b905130276238477646b72d298d47d0d/packages/debug/src/browser/preferences/launch-preferences.ts#L28
And how we calculate the group name:
https://github.com/theia-ide/theia/blob/c2e23083b905130276238477646b72d298d47d0d/packages/preferences/src/browser/preferences-tree-widget.ts#L553-L555

---

Other preferences have the following format `{group-name}.{preference-name}`

**Comment by vince-fugnitto** [comment]
@akosyakov is this a preference that should not be displayed in the tree? 
I see that VSCode has the [same](https://github.com/Microsoft/vscode/blob/bb4baaa85275a1828c2448227912e646647d57e7/src/vs/workbench/contrib/debug/electron-browser/debug.contribution.ts#L253) preference defined.

**Comment by akosyakov** [comment]
If it is defined in user, workspace or workspace folder settings.json files then yes, if it is coming from launch.json then probably not.

Generally splitting looks bogus, obviously there can be a preference name without `.`.

**Comment by vince-fugnitto** [comment]
> Generally splitting looks bogus, obviously there can be a preference name without `.`.

If for whatever reason we can't calculate the group name, for example like in `launch`, I'll place these preferences under a common group called `Other`. Would that be acceptable?

**Comment by akosyakov** [comment]
Could be alright for now, alternatively for embeddable configurations use a section name as a group and it children as properties.
