### ISSUE TITLE
Recently used tasks section should respect configured tasks

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#5067]
### Description
I think it makes sense to use 'configured' task configuration (if it exists) instead of 'detected'' when we run task from 'recently used' tasks section.   

### Reproduction Steps
1. Run a 'detected' task.
2. Configure the task and edit it.
3. Run the task from 'recently used' section.

Expected behavior: configured task is running
Actual behavior: detected task is running 

Please see https://youtu.be/-nYgZ84-JnU

**Diagnostics:** 

I guess the problem is related to [filtering configurations](https://github.com/theia-ide/theia/blob/master/packages/task/src/browser/quick-open-task.ts#L189-L220)

**Comment by akosyakov** [comment]
cc @elaihau

**Comment by RomanNikitenko** [comment]
The behavior was changed: after configuring of `detected` task, this one is not present in `configured tasks` section.

I created the issue https://github.com/theia-ide/theia/issues/5747 to clarify and discuss the new behavior. 
@elaihau
