### ISSUE TITLE
[markers] include 'Collapse All' toolbar items

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5069]
**Description**

Proposal to add ~~`Clear All`~~ and `Collapse All` toolbar items to the `problems-widget`.

- ~~_Clear All_: clears all problem markers from the widget.~~
- _Collapse All_: collapses all problem marker nodes from the widget.

**Comment by akosyakov** [comment]
sounds good to me, there should be already icons for it, should be trivial to implement

**Comment by akosyakov** [comment]
It would be nice also to rework the outline view actions to put into toolbar instead of inside a widget.

**Comment by vince-fugnitto** [comment]
> It would be nice also to rework the outline view actions to put into toolbar instead of inside a widget.

I was thinking the same thing, thanks to the PR from @kittaakos :smile:
