### ISSUE TITLE
[commands] error on startup for 'workspace:removeFolder' command

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5070]
**Description**
On startup, the following error is thrown for the command `workspace:removeFolder` when the preference `workspace.supportMultiRootWorkspace` is enabled.

```bash
ERROR Error: A command with id 'workspace:removeFolder' does not exist.
```

**Comment by vince-fugnitto** [comment]
I believe it has to do with the `navigator-contribution` registering menu actions with the command `workspace:removeFolder` before it's been officially registered by the `workspace-contribution` which itself waits for the preferences to be ready before registering.

https://github.com/theia-ide/theia/blob/c2e23083b905130276238477646b72d298d47d0d/packages/navigator/src/browser/navigator-contribution.ts#L221

https://github.com/theia-ide/theia/blob/c2e23083b905130276238477646b72d298d47d0d/packages/workspace/src/browser/workspace-commands.ts#L293-L297

**Comment by a1994846931931** [comment]
Weird, I found the command `workspace:removeFolder` works just fine. The theia I was testing on is of commit id 481c02514738537c1fa9048f6b6def41fcee6433.

**Comment by vince-fugnitto** [comment]
@a1994846931931 it still happens to me on the latest master d196825.

With the preference `workspace.supportMultiRootWorkspace` preference enabled, reloading the application throws the error. The command does seem to work, but the uncaught error is still thrown.
