### ISSUE TITLE
[vscode][java] vscode debug plugin  does not work

### ISSUE THREAD

**Issue by yeweiasia** [theia-ide/theia#5077]
### Description
vscode java debug from [vscode-java-debug](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) does not work with [redhat Language support for Java](https://marketplace.visualstudio.com/items?itemName=redhat.java)

### Reproduction Steps
1.remove `"@theia/java": "^0.6.0","@theia/java-debug": "^0.6.0",` in `examples/browser/package.js`
2.recompile with yarn
3.put redhat.java-0.43.0.vsix and vscjava.vscode-java-debug-0.18.0.vsix into plugins directory 
4.start theia in `examples/browser` with command `yarn start --hostname 0.0.0.0`
5.open a java workspace, and start using codelens debug link
![image](https://user-images.githubusercontent.com/16164849/57217458-3f52c280-7025-11e9-8597-3796187c0728.png)

**OS and Theia version:**
ubuntu 18.04 with theia 0.6.0

**Diagnostics:** 
backend log:
![image](https://user-images.githubusercontent.com/16164849/57217366-04508f00-7025-11e9-8002-3796d6f4c244.png)
browser console:
no error output

**Comment by yeweiasia** [comment]
It seems that java debug can work properly if I replace the vscode-java-debug version to [0.15.0](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-debug/0.15.0/vspackage)

**Comment by svor** [comment]
fixed by https://github.com/theia-ide/theia/pull/5343
