### ISSUE TITLE
Default behavior of workspace.openTextDocument method

### ISSUE THREAD

**Issue by vzhukovskii** [theia-ide/theia#5079]
### Description
According to default behavior given in original vscode's [openTextDocument](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L583-L602) method, it should never open the document as it does in copied [implementation](https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/plugin/plugin-context.ts#L385-L404). To avoid such situation there was created following [pull request](https://github.com/theia-ide/theia/pull/5080) as temporary fix, but according to amount of code, there is a need to refactor the code to align common method behavior.

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/13076
