### ISSUE TITLE
The docker build script does not work

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#508]
from Gitter:

> WORKDIR /home/theia
RUN git clone https://github.com/theia-ide/theia \
&& cd theia \
&& yarn --unsafe-perm
WORKDIR /home/theia/theia/examples/browser
RUN cd ./theia/examples/browser && yarn run build
Executing docker build .
 Leads to
generator-theia: > yarn run clean && yarn run compile
lerna success run Ran npm script 'prepare' in packages:
lerna success - generator-theia
lerna info version 2.1.2
lerna info scope generator-theia
error An unexpected error occurred: "EACCES: permission denied, symlink '../../home/theia/theia/generator-theia/bin/rebuild.js' -> '/usr/bin/theia-rebuild'".
lerna ERR! exec Errored while executing 'yarn link' in 'generator-theia'
lerna ERR! execute Error: Command failed: yarn link

**Comment by akosyakov** [comment]
It seems that the reason is that npm scripts are running yarn without `--unsafe-prem` internally.

**Comment by akosyakov** [comment]
`unsafe-perm` is false by default and can be set to true with `yarn config set unsafe-perm true` instead of passing to each script

**Comment by marcdumais-work** [comment]
I can confirm that even with the (unmodified) Dockerfile from the repo, I get an error building : 

$ lerna exec --scope generator-theia --stream -- yarn link && yarn link generator-theia
lerna info version 2.1.2
lerna info scope generator-theia
yarn link v0.24.4
error An unexpected error occurred: "EACCES: permission denied, symlink '../../../home/theia/theia/generator-theia/bin/rebuild.js' -> '/usr/local/bin/theia-rebuild'".

**Comment by deboer-tim** [comment]
I've got the same EACCES: permission denied on theia-rebuild. Appears to be caused by this commit: https://github.com/theia-ide/theia/commit/d150fb899b66c47ae5b57b17dda5e14ffcd61ce7

**Comment by akosyakov** [comment]
@deboer-tim have you tried: `yarn config set unsafe-perm true`

**Comment by deboer-tim** [comment]
I tried changing the dockerfile to this:
  RUN git clone --depth 1 https://github.com/theia-ide/theia && \
    cd theia && \
    yarn config set unsafe-perm true && \
    yarn
It appears to set config ok:
  yarn config v0.24.4
  success Set "unsafe-perm" to "true".
But docker build still fails with the same error.

**Comment by marcdumais-work** [comment]
@akosyakov from the error it seems that we're trying to create a link to a place where we do not have write access: /usr/local/bin/ . It doesn't seem that this happens when I build locally, since my user also doesn't have write access in the path, but I get no error. 

Work-around: If I add the following line at the top of the Dockerfile, then it works (by-passing the perm issue): 

RUN chmod 777 /usr/local/bin

**Comment by deboer-tim** [comment]
FWIW, workaround worked for me too.

**Comment by akosyakov** [comment]
It seems to be the common issue when some tools are installed globally via NPM in the docker. E.g. the same for yo: https://github.com/yeoman/yeoman.github.io/issues/282.

We either should find a way to install nothing to the global or users should not use the root in the docker. The latter seems to be recommended.

**Comment by marcdumais-work** [comment]
BTW, I have noticed that by changing the Dockerfile to pull node 8 instead of node 7.10, the problem seems to go away.

**Comment by akosyakov** [comment]
It should not be an issue anymore with https://github.com/theia-ide/theia/pull/527.
