### ISSUE TITLE
[quality] fix 'overriden' typo in preferences

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5082]
**Description**

Fix minor typo occurences in the `preferences` extension. 
**overriden** should be **overridden**

https://github.com/theia-ide/theia/blob/508e33c4cb169f80343640edbebd74abc305052b/packages/core/src/browser/preferences/preference-proxy.ts#L49

https://github.com/theia-ide/theia/blob/508e33c4cb169f80343640edbebd74abc305052b/packages/core/src/browser/preferences/preference-proxy.ts#L49-L57
https://github.com/theia-ide/theia/blob/d19682560698585f325a48ff05afd86bca90306d/packages/core/src/browser/preferences/preference-service.ts#L89

https://github.com/theia-ide/theia/blob/aff18c8f31661e18b22d05f71b56b4ed65975093/packages/core/src/browser/preferences/preference-contribution.ts#L159-L161

https://github.com/theia-ide/theia/blob/aff18c8f31661e18b22d05f71b56b4ed65975093/packages/core/src/browser/preferences/preference-contribution.ts#L285-L293

https://github.com/theia-ide/theia/blob/aff18c8f31661e18b22d05f71b56b4ed65975093/packages/core/src/browser/preferences/test/mock-preference-service.ts#L55-L57

**Comment by vince-fugnitto** [comment]
:warning: watch out for the public instance, anyone calling the method (internal & external) would be broken!

**Comment by malieop** [comment]
Can i help on this one ?

**Comment by vince-fugnitto** [comment]
> Can i help on this one ?

I believe it's already being handled in #5087, but there should be other potential issues if you'd like to get started contributing in Theia :)

**Comment by vince-fugnitto** [comment]
Fixed by #5087
