### ISSUE TITLE
Working with the code in VS.Net 2017

### ISSUE THREAD

**Issue by nkiranrao** [theia-ide/theia#509]
can we have some steps/guide on how to open the solution on VS.Net 2017 and build.

**Comment by akosyakov** [comment]
@nkiranrao we do the build from [the command line](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#quick-start), including [incremental builds](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#watching), and use [VS code](https://code.visualstudio.com/) for editing.

If VS.Net 2017 has the built terminal you should be able to run the build scripts from it.

**Comment by nkiranrao** [comment]
I am actually new to the Nodejs / electron world, could you please point me to some basic details on how to work with application like these? I have mostly been working on the mvc world.

**Comment by akosyakov** [comment]
Please have a look at https://github.com/theia-ide/theia/blob/master/doc/Developing.md
If something is not clear we would be glad to clarify it.

**Comment by nkiranrao** [comment]
when I try to build using code, the build process hangs in the middle of `Yarn` execution. I tried to clear the cache and rebuild, but it always stops at the same spot. so I was wondering if somehow if I could build using VS.Net 2017 Make file, I should be able to understand what is going on here. Here is a log from `lerna-debug.log` when it hangs...

```
993 info hoist Finished pruning hoisted dependencies
994 silly installInDir cleanup D:\Source\theia\package.json
995 silly renameSync [ 'D:\\Source\\theia\\package.json.lerna_backup',
995 silly renameSync   'D:\\Source\\theia\\package.json' ]
996 error execute Error: Command failed: yarn install --mutex network:42424 --non-interactive --no-optional --concurrency==1
996 error execute error An unexpected error occurred: "https://registry.yarnpkg.com/@phosphor%2fwidgets: connect ETIMEDOUT 104.16.61.173:443".
996 error execute
996 error execute     at Promise.all.then.arr (D:\Source\theia\node_modules\lerna\node_modules\execa\index.js:236:11)
996 error execute     at <anonymous>
996 error execute     at process._tickCallback (internal/process/next_tick.js:188:7)
996 error execute  callback with error
996 error execute  { Error: Command failed: yarn install --mutex network:42424 --non-interactive --no-optional --concurrency==1
996 error execute error An unexpected error occurred: "https://registry.yarnpkg.com/@phosphor%2fwidgets: connect ETIMEDOUT 104.16.61.173:443".
996 error execute
996 error execute     at Promise.all.then.arr (D:\Source\theia\node_modules\lerna\node_modules\execa\index.js:236:11)
996 error execute     at <anonymous>
996 error execute     at process._tickCallback (internal/process/next_tick.js:188:7)
996 error execute   stack: 'Error: Command failed: yarn install --mutex network:42424 --non-interactive --no-optional --concurrency==1\nerror An unexpected error occurred: "https://registry.yarnpkg.com/@phosphor%2fwidgets: connect ETIMEDOUT 104.16.61.173:443".\n\n    at Promise.all.then.arr (D:\\Source\\theia\\node_modules\\lerna\\node_modules\\execa\\index.js:236:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
996 error execute   code: 1,
996 error execute   killed: false,
996 error execute   stdout: '',
996 error execute   stderr: 'error An unexpected error occurred: "https://registry.yarnpkg.com/@phosphor%2fwidgets: connect ETIMEDOUT 104.16.61.173:443".\n',
996 error execute   failed: true,
996 error execute   signal: null,
996 error execute   cmd: 'yarn install --mutex network:42424 --non-interactive --no-optional --concurrency==1',
996 error execute   timedOut: false }

```

**Comment by kittaakos** [comment]
@nkiranrao, can you ping `104.16.61.173:443` to see whether you can reach it?

**Comment by akosyakov** [comment]
> when I try to build using code, the build process hangs in the middle of Yarn execution.

your connection appears to be weak or npmjs is not responsive right now

> I tried to clear the cache and rebuild, but it always stops at the same spot.

I won't do it, yarn caches dependencies. Executing yarn again with cached dependencies can actually help.

>  so I was wondering if somehow if I could build using VS.Net 2017 Make file, I should be able to understand what is going on here.

I don't see how it can help, your make file at the end will call yarn and you will have the same issue.

**Comment by kittaakos** [comment]
@akosyakov, we might have to set the `--network-concurrency 1` flag as well on Windows. But I do not want to do it unless we can reproduce the same problem so that we can eventually verify the fix.

**Comment by akosyakov** [comment]
@kittaakos Could @nkiranrao just try to run `yarn  --network-concurrency 1`?

**Comment by akosyakov** [comment]
If it is the case I think we can add the first suggestion from here to the troubleshooting section: https://github.com/yarnpkg/yarn/issues/944#issuecomment-327453136

Having the custom yarn script will be annoying.

**Comment by kittaakos** [comment]
> @kittaakos Could @nkiranrao just try to run yarn --network-concurrency 1?

It worth a try.

**Comment by nkiranrao** [comment]
I think there was some issue with the proxy initially, I updated the `.yarnrc` file to fix the proxy issue, but now i am getting on to the following error 
```
lerna ERR! execute   stderr: 'error An unexpected error occurred: "https://registry.yarnpkg.com/@phosphor%2fwidgets: unable to get local is
suer certificate".\n',
```

any ideas what am I missing now?

**Comment by akosyakov** [comment]
@nkiranrao it is unrelated to Theia, you should google for yarn: https://github.com/yarnpkg/yarn/issues/841#issue-182469522

It seems that you can do `yarn config set strict-ssl false`.

**Comment by kittaakos** [comment]
I am just blindly guessing: `yarn config set strict-ssl false`?

**Comment by nkiranrao** [comment]
Tried all possible hacks on the net, but still stuck with this error
` execute cnpm upds:\users\kn3\.node-gyp\8.5.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling source file ..\src\win\pty.cc) [D:\Source\theia\node_modules\node-pty\build\pty.vcxproj]`

any ideas how to fix this...

**Comment by kittaakos** [comment]
Do you have Python2.x and the other requirements? (https://github.com/theia-ide/theia/blob/master/doc/Developing.md#windows)

**Comment by nkiranrao** [comment]
Thanks, I did try this and few more tricks on the net but I still can't get this built. Is there anything else I can try,  Below is the error I see while building.

```
999 error execute      Creating library D:\Source\theia\node_modules\node-pty\build\Release\winpty.lib and object D:\Source\theia\node_modules\node-pty\build\Release\winpty.exp
999 error execute   Generating code
999 error execute   Finished generating code
999 error execute   winpty.vcxproj -> D:\Source\theia\node_modules\node-pty\build\Release\\winpty.dll
999 error execute   winpty.vcxproj -> D:\Source\theia\node_modules\node-pty\build\Release\winpty.pdb (Full PDB)
999 error execute   pty.cc
999 error execute   win_delay_load_hook.cc
999 error execute c:\users\kn3\.node-gyp\8.5.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling source file ..\src\win\pty.cc) [D:\Source\theia\node_modules\node-pty\build\pty.vcxproj]
999 error execute gyp ERR! build error
999 error execute gyp ERR! stack Error: `D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
999 error execute gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
999 error execute gyp ERR! stack     at emitTwo (events.js:125:13)
999 error execute gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
999 error execute gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
999 error execute gyp ERR! System Windows_NT 10.0.14393
999 error execute gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
999 error execute gyp ERR! cwd D:\Source\theia\node_modules\node-pty
999 error execute gyp ERR! node -v v8.5.0

```

**Comment by kittaakos** [comment]
I am running out of ideas. What you can do, is to have a new shell, print out the node version, yarn version, python version and npm version. Then you can clone the repository again and execute `yarn`. Then you can attach the full shell content into this ticket as a text.

Also, you can fork the repository, modify the appveyor build by printing out the environment variables and dependency versions. And you can compare it with yours.

Unfortunately, we lack Windows users in the team, and we are not doing active development on Windows. We have set up the Windows CI and use VirtualBox for verifying and fixing OS related bugs on them, but I cannot help you with the Visual C++ Build Tools setup.

**Comment by hexa00** [comment]
```
execute c:\users\kn3\.node-gyp\8.5.0\include\node\uv-win.h(32): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling source file ..\src\win\pty.cc) [D:\Source\theia\node_modules\node-pty\build\pty.vcxproj
```
Seems like he's missing the winsock lib from windows.

I think it should be included in: windows-build-tools

I ran the https://github.com/theia-ide/theia/blob/master/doc/Developing.md#windows from a clean vm and it works...

Did you run the commands to get the prerequisites ?

**Comment by hexa00** [comment]
We've been testing on windows 10 however too, what version of windows are you on ?

**Comment by kittaakos** [comment]
You can also try to look into [this](https://github.com/nodejs/node-gyp/commit/a8d441a0a2db8406e1da63559bcf31b7d293b5e1).

**Comment by nkiranrao** [comment]
I am on windows 10 Ent 64 bit. may be one last help. As I am really new to the Node envorinment, could you pls help me understand if I have to start over again, uninstall all the node packages and do a clean start, what commands would I have to run. Also I have only VS.Net Professional on my laptop, is that a problem as the documents generally points to VS.Net 2015.

**Comment by hexa00** [comment]
You can run git clean -fdx from the theia directory this will clean it all.
Warning if you had any other files in there that is not part of the theia repo it will clean those too.

Make sure you follow https://github.com/theia-ide/theia/blob/master/doc/Developing.md#windows

**Comment by hexa00** [comment]
Oops I mean Make sure you follow: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#building-on-windows

**Comment by nkiranrao** [comment]
how does the files at the `C:\Users\kn3\.node-gyp\8.5.0\include\node` get populated form? I see  that this is missing a few `.h` files there.  BTW I did follow all the steps from the link you provided.

**Comment by hexa00** [comment]
I guess the node-gyp build script should be populating that.

**Comment by hexa00** [comment]
From what I read installing: https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk
this would help

**Comment by nkiranrao** [comment]
Thanks!!! this was the missing link I think. 
Now I am able to build it. I also deleted all complete folder and refetched the code from git repo. not sure which one actually helped. Thanks for the support!! really appreciate it.

**Comment by hexa00** [comment]
Cool! :) Have fun!

**Comment by akosyakov** [comment]
@nkiranra do we need to update or add something to windows troubleshooting section?

**Comment by nkiranrao** [comment]
I am not sure as my knowledge of the Node envorinment is limited. I tried so many different things, not sure what actually fixed the issue eventually. I think it might be the "windows-10-sdk" that might have been the issue. I have to repair this installation.
