### ISSUE TITLE
[no-void-expression] fix the return void declaration in menu.ts

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5090]
**Description**
Per the [`no-void-expression`](https://palantir.github.io/tslint/rules/no-void-expression/) rule, expressions of type void should not be returned explicitly since "it’s misleading [to] return the results of an expression whose type is void".

https://github.com/theia-ide/theia/blob/92c66ba07a3ed1b0916580c06f8306b0cc5ce43b/packages/core/src/common/menu.ts#L116

Here, the method `removeNode(id: string)` returns `void`, and therefore should be fixed to:
```ts
parent.removeNode(id);
return;
```

**Comment by vince-fugnitto** [comment]
@fangnx would you like to fix the issue? :smiley:

**Comment by fangnx** [comment]
Sure ;)
