### ISSUE TITLE
[Plugin-API] Improve window.createInput()

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#5109]
### Description
 
`window.createInput()` introduced in #5107  have only the base functionality, reused from QuickOpenExtImpl:
- value (Current input value)
- placeholder (Optional placeholder in the filter text)
- password (If the input value should be hidden. Defaults to false)
- prompt (An optional prompt text providing some ask or explanation to the user)
- onDidChangeValue (An event signaling when the value has changed)
- onDidAccept (An event signaling when the user indicated acceptance of the input value)
- validationMessage (An optional validation message indicating a problem with the current input value)
- show()

Functionality that is not supported by QuickOpenExtImpl but declared in InputBox:
- buttons (Buttons for actions in the UI)
- onDidTriggerButton (An event signaling when a button was triggered)
- step / totalSteps (An optional current / total step count)
- busy (If the UI should show a progress indicator)
- enabled (If the UI should allow for user input)

**Comment by JPinkney** [comment]
Hi, I’ve already started work on both https://github.com/theia-ide/theia/issues/5107 and https://github.com/theia-ide/theia/issues/5109 as well as implementing the QuickInput API as part of https://github.com/theia-ide/theia/issues/5084. It should be done in a week or two. I just wanted to let you know so we don’t duplicate work (if you were going to work on this issue).

**Comment by ira-gordin-sap** [comment]
Hi, could you please share some estimation for this item?

**Comment by JPinkney** [comment]
Everything that can be done currently is in a PR (https://github.com/theia-ide/theia/pull/5187) that i'm fixing up today
