### ISSUE TITLE
Unable to open multiple files in editor by dragging and dropping them to tab bar

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5114]
Currently, it is not possible to drag multiple files from the Explorer panel to the Tab Bar to open them all. Dragging and dropping multiple files to the Tab bar would only open **one file that is clicked on**.

I am wondering if this feature can be implemented as it is done in other IDEs, such as VS Code?

![](https://media.giphy.com/media/l0934CWNlT0wK5ldmh/giphy.gif)

**Comment by BroKun** [comment]
This issue is more related to 'filesystem', dnd events need to transfer resource list.
