### ISSUE TITLE
Quick start build fails in Ubuntu 18.10.

### ISSUE THREAD

**Issue by abalter** [theia-ide/theia#5123]
### Reproduction Steps

Ubuntu 18.10 in WSL

I tried with node installed two different ways:
* apt with PPA
* conda

```
(base) balter@spectre3:~/theia$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
```
(base) balter@spectre3:~/theia$ node -v
v12.2.0
(base) balter@spectre3:~/theia$ yarn -v
1.16.0
(base) balter@spectre3:~/theia$ npm -v
6.9.0
(base) balter@spectre3:~/theia$ which {node,npm,yarn}
/usr/bin/node
/usr/bin/npm
/usr/bin/yarn
(base) balter@spectre3:~$ git clone https://github.com/theia-ide/theia
Cloning into 'theia'...
remote: Enumerating objects: 52744, done.
remote: Total 52744 (delta 0), reused 0 (delta 0), pack-reused 52744
Receiving objects: 100% (52744/52744), 119.80 MiB | 8.27 MiB/s, done.
Resolving deltas: 100% (36653/36653), done.
Checking out files: 100% (1699/1699), done.
(base) balter@spectre3:~$ cd theia
(base) balter@spectre3:~/theia$ yarn
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-782779b7-d266-484a-895c-7ddca8697d11 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-782779b7-d266-484a-895c-7ddca8697d11 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-782779b7-d266-484a-895c-7ddca8697d11 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/balter/.cache/yarn/v4/npm-build-0.1.4-707fe026ffceddcacbfdcdf356eafda64f151046/node_modules/build/build.sh'".
info If you think this is a bug, please open a bug report with the information provided in "/home/balter/theia/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```

(node) balter@spectre3:~/theia_conda$ which {node,npm,yarn}
/home/balter/conda/envs/node/bin/node
/home/balter/conda/envs/node/bin/npm
/home/balter/conda/envs/node/bin/yarn
(node) balter@spectre3:~/theia_conda$ node -v
v11.14.0
(node) balter@spectre3:~/theia_conda$ npm -v
6.7.0
(node) balter@spectre3:~/theia_conda$ yarn -v
1.16.0
(base) balter@spectre3:~$ git clone https://github.com/theia-ide/theia  theia_conda
Cloning into 'theia_conda'...
remote: Enumerating objects: 52744, done.
remote: Total 52744 (delta 0), reused 0 (delta 0), pack-reused 52744
Receiving objects: 100% (52744/52744), 119.80 MiB | 8.48 MiB/s, done.
Resolving deltas: 100% (36653/36653), done.
Checking out files: 100% (1699/1699), done.
(base) balter@spectre3:~$ cd theia_conda/
(base) balter@spectre3:~/theia_conda$ conda activate node
(node) balter@spectre3:~/theia_conda$ yarn
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-8f44eb7c-ffbf-499c-9dfa-a22c495cf5e8 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-8f44eb7c-ffbf-499c-9dfa-a22c495cf5e8 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-8f44eb7c-ffbf-499c-9dfa-a22c495cf5e8 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[1/14] ⠂ fibers
[6/14] ⠂ @theia/node-pty
[3/14] ⠂ electron
[4/14] ⠄ native-keymap
error /home/balter/theia_conda/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/balter/theia_conda/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.14.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/balter/theia_conda/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/balter/theia_conda/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/balter/theia_conda/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/balter/.node-gyp/11.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/balter/.node-gyp/11.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/balter/theia_conda/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/balter/.node-gyp/11.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/balter/theia_conda/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package xkbfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbfile' found
gyp: Call to 'pkg-config x11 xkbfile --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/balter/theia_conda/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/home/balter/conda/envs/node/bin/node" "/home/balter/theia_conda/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/balter/theia_conda/node_modules/native-keymap

```


<!-- Provide logs and any other relevant diagnostic information -->





(base) balter@spectre3:~$ git clone https://github.com/theia-ide/theia
Cloning into 'theia'...
remote: Enumerating objects: 52744, done.
remote: Total 52744 (delta 0), reused 0 (delta 0), pack-reused 52744
Receiving objects: 100% (52744/52744), 119.80 MiB | 8.27 MiB/s, done.
Resolving deltas: 100% (36653/36653), done.
Checking out files: 100% (1699/1699), done.
(base) balter@spectre3:~$ cd theia
(base) balter@spectre3:~/theia$ yarn
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-782779b7-d266-484a-895c-7ddca8697d11 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-782779b7-d266-484a-895c-7ddca8697d11 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-782779b7-d266-484a-895c-7ddca8697d11 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/balter/.cache/yarn/v4/npm-build-0.1.4-707fe026ffceddcacbfdcdf356eafda64f151046/node_modules/build/build.sh'".
info If you think this is a bug, please open a bug report with the information provided in "/home/balter/theia/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
(base) balter@spectre3:~/theia$ node -v
v12.2.0
(base) balter@spectre3:~/theia$ yarn -v
1.16.0
(base) balter@spectre3:~/theia$ npm -v
6.9.0
(base) balter@spectre3:~/theia$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

**Comment by akosyakov** [comment]
Please make sure to use node 10.

**Comment by abalter** [comment]
Why so specific? 

I'm finding node/yarn/npm installs fragile already--at least in comparison to other package managers such as conda and apt. There is always some unmet dependency or version conflict that has to be dealt with by hand. Usually gyp.

I was able to successfully build a minimal Theia using [this recipe](https://www.theia-ide.org/doc/composing_applications). But it is not full-featured. I thought about playing around with adding things in from the package.json that comes with the clone and find where it stumbles.

**Comment by abalter** [comment]
So, I created a conda environment with node 10 `conda create -n node10 nodejs=10.8.0`. Then I tried to run yarn in that environment. Still got errors. 

```
(node10) balter@spectre3:~/theia$ yarn
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-9ad3ad6b-61c4-4346-bfb1-1938e847d130 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-9ad3ad6b-61c4-4346-bfb1-1938e847d130 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-9ad3ad6b-61c4-4346-bfb1-1938e847d130 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[6/14] ⠐ @theia/node-pty
[2/14] ⠐ dtrace-provider
[7/14] ⠐ drivelist
[4/14] ⠐ native-keymap
error /home/balter/theia/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/balter/theia/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/home/balter/conda/envs/node10/bin/node" "/home/balter/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/balter/theia/node_modules/nsfw
```

**Comment by raphaelsantos** [comment]
I am running into the same issue.

It would be nice to update this page, as it suggests to install node 8 instead of 10:
https://www.theia-ide.org/doc/Authoring_Extensions.html

I get the error above with both node versions.

**Comment by kittaakos** [comment]
> It would be nice to update this page, as it suggests to install node 8 instead of 10:
> https://www.theia-ide.org/doc/Authoring_Extensions.html

Was done in https://github.com/theia-ide/theia/commit/d89dccf65f226745bf746cfedd62da910177ff8e.

----

```
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
gyp ERR! System Linux 4.4.0-17134-Microsoft
```

> I get the error above with both node versions.

It seems to be a proxy issue: check [this thread](https://github.com/theia-ide/theia/issues/4144#issuecomment-456706105).

I am closing this, please reopen if required.
