### ISSUE TITLE
[markers] add 'copy' and 'copy message' problem-widget context menu items

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5132]
**Description**

In comparison to VSCode, the following context menu items are missing from 
the `problems-widget`.

<div align='center'>

<img width="397" alt="Screen Shot 2019-05-13 at 3 19 04 PM" src="https://user-images.githubusercontent.com/40359487/57648056-7deefc80-7592-11e9-85ca-14cff69b4b86.png">

</div>

---

**`Copy`**

Example:
```json
{
	"resource": "/Users/vincentfugnitto/workspace/theia/packages/navigator/src/browser/navigator-widget.tsx",
	"owner": "typescript",
	"code": "2531",
	"severity": 8,
	"message": "Object is possibly 'null'.",
	"source": "ts",
	"startLineNumber": 162,
	"startColumn": 13,
	"endLineNumber": 162,
	"endColumn": 32
}
```

**`Copy Message`**

Example:
```json
Object is possibly 'null'.
```

**Comment by vince-fugnitto** [comment]
@fangnx would you like to work on the issue?

**Comment by fangnx** [comment]
@vince-fugnitto Yes I will work on this

**Comment by akosyakov** [comment]
@vince-fugnitto you should announce @fangnx as a committer already :)
