### ISSUE TITLE
Can't get Theia Java support to work in Docker

### ISSUE THREAD

**Issue by deboer-tim** [theia-ide/theia#515]
I'm trying to get the Theia Java support to work using the Dockerfile provided, and although I can see syntax highlighting there was no further Java support. I hit the recent Dockerfile regression and worked around that, and I also couldn't find a JVM within the image so I added one and I can now manually start the JDT LS outside of Theia (from within the image) with no problem.

However, I still can't see any evidence that Theia has tried to start the LS itself (e.g. no LS data workspace) and can't find any logs from Theia. Are there any special things that you need to do to get this working outside of Docker, or any pointers to where I should look to continue debugging this? Thanks.

**Comment by svenefftinge** [comment]
Do you see anything in the output of the backend process?
Atm it is assumed that a java runtime is on the PATH.

**Comment by deboer-tim** [comment]
I've added Java + PATH to the dockerfile. No change to Theia, but I can docker exec in, cd to ~/theia/packages/java/lib/node/server, and run the LS via "java -... -data /tmp/workspace" ok. Where do I find the output of the backend process?

**Comment by svenefftinge** [comment]
It should be in the general logs of the image.

**Comment by deboer-tim** [comment]
Yeah, I guess that should have been obvious to me... Sorry.
Looking at the logs, there was the following: "Error: spawn java ENOENT". I spent the rest of the day trying to figure out why java couldn't be launched within the container (it can), why it wasn't on the PATH (it is), and why the PATH wasn't pick up in Theia's environment (it is). I eventually found the problem in java-contribution.ts - it is overriding the PATH entirely when it replaces the env STDIN/OUT values. If I hack it to add a value like 'PATH': '/myjava/path' it works.

The Java code assist is still missing some completions so I'm going to continue debugging and ensure my project config is ok, but I think java-contribution.ts should be fixed to not override/block the system PATH. Likewise I think it would help if there was a comment in the Dockerfile saying "if you want Java support you need to install your own Java here".

**Comment by akosyakov** [comment]
@deboer-tim you are welcome to open a PR to add comments to the Dockerfile and import the java extension.

**Comment by akosyakov** [comment]
@deboer-tim thanks, merged with https://github.com/theia-ide/theia/pull/585
