### ISSUE TITLE
Better support for tmux

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#516]
"[Tmux](https://en.wikipedia.org/wiki/Tmux)  is a software application that can be used to multiplex several virtual consoles, allowing a user to access multiple separate terminal sessions inside a single terminal window or remote terminal session."

It seems that tmux would be a useful tool to use within the Theia terminal. However at the moment, there are some things that do not work: 
- selection seems broken. 
- probably related, the browser's copy action is often not enabled when something is selected
- when by chance the copy action is enabled, what gets copied is not what's currently selected. 

I have tried tmux in the xterm.js demo application and the above problems are not present.

**Comment by marcdumais-work** [comment]
BTW, it seems that tmux works fine in VS Code, at least for the simple use-case of selecting some text, copying it and pasting it.

**Comment by simark** [comment]
I was stepping side by side the xterm.js code, both in Theia and the xterm.js example (cloned from their git repo) and found that the code was a bit different.  I realized that the example of xterm.js is based on the future major version (3.x.y), since that is the default branch of their git repo.  In that branch, there are a few fixes related to tmux.  So I tried to upgrade to use that version of xterm.js, and it seems to work better.

You can try the branch `xterm.js-v3` in my repo: https://github.com/simark/theia/tree/xterm.js-v3

**Comment by simark** [comment]
vscode uses this branch of xterm.js, which seems based on v3 (note the merge commits from origin/v3 into that branch), so it would explain why it works there.

https://github.com/Tyriar/xterm.js/commits/vscode-release/1.18

**Comment by simark** [comment]
In the `xterm.js-v3` Theia branch, I modified the Dockerfile in `examples/browser` to use that branch, so you can use it for testing.

**Comment by hexa00** [comment]
Can we use than branch from npm ? Is there a pre-release ?

**Comment by simark** [comment]
I don't think there's any packaged pre-release.  If we really wanted to, I guess we could use xterm.js from the v3 git branch.

**Comment by hexa00** [comment]
If it works with v3 I think we could package it and use it

**Comment by simark** [comment]
Or just use vscode's branch :)

**Comment by hexa00** [comment]
I guess, it has 27 commits ahead of master.. not sure what it contains of it has as vscode specific stuff in there.

**Comment by marcdumais-work** [comment]
I just tested @simark 's [branch](https://github.com/simark/theia/tree/xterm.js-v3) above using tmux and it worked fine. Bra job

**Comment by svenefftinge** [comment]
@marcdumais @simark can this ticket be closed then?

**Comment by simark** [comment]
I think so.
