### ISSUE TITLE
Make the logger accessible outside the inversify context

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#517]
It would be nice to be able to use the logger outside of the inversify context.

For example in the Globalize PR we would need to do this to avoid using console.log

An idea discussed has been to use a global variable to the logger singleton and bind that to the global console so that any use of console.log goes though our logger.

I would suggest theia's code still use logger.log however

**Comment by hexa00** [comment]
@svenefftinge @akosyakov  We need to do this for other things too like the MessageTranslation class in the globalize PR.

However I don't understand where we would export a global variable from the container.

It looks like the current place would be in src-gen/server.ts for example where the container is created but that doesn't make sense since a package won't be able to import that...

Any ideas on this ?

**Comment by svenefftinge** [comment]
I think it would be a side-effect on an existing global when the container is created.

**Comment by hexa00** [comment]
Haaa yes ok that would work good point thx! :)
We will have to watchout for that however, I think extensions will need to register a function to be called on container creation so that this can be setup properly

**Comment by hexa00** [comment]
Fixed in #562
