### ISSUE TITLE
Running "theia build" in hello-world-extension project browser-app folder breaks it all

### ISSUE THREAD

**Issue by maxhillaert** [theia-ide/theia#5182]
### Description
I'm using the project setup as suggested by the "Authoring Extension" gitbook section: https://www.theia-ide.org/doc/Authoring_Extensions.html

The setup seems to be brittle when you run yarn scripts at the wrong location within the project.  theia build in browser-app will break the bundles and make the extension disappear from the theia-app when started.

**Reproduction**

Execute the steps in the tutorial
1) yo theia-extension hello-world-extension
2) let it finish , which will run "yarn prepare" script from root of the workspace
3) cd browser-app
4) yarn start
5) Check for Hello Menu item in localhost:3000 and its there
6) Stop the server CTRL-C
7) still in browser-app, do "yarn prepare" which will run theia build
8) When it's finished do "yarn start"
9) Go to localhost:3000 and there is no sign of Hello menu item. No errors.

Any attempt to setup up a workflow with the watch scripts produces the same issue. It just doesn't work as it breaks the link between extension and browser-app.  You have to start from scratch and run the lerna command from root?

What is going on here? Am I using wrong versions of things? Is this known issue?

Thanks

**OS and Theia version:**

Windows 7
yarn 1.15.2
lerna 2.4.0
theia latest as of today

yarn list v1.15.2
├─ @msci/maml-theia-browser@0.0.0
├─ @theia/application-manager@0.6.1
├─ @theia/application-package@0.6.1
├─ @theia/callhierarchy@0.6.1
├─ @theia/cli@0.6.1
├─ @theia/core@0.6.1
├─ @theia/editor@0.6.1
├─ @theia/filesystem@0.6.1
├─ @theia/json@0.6.1
├─ @theia/languages@0.6.1
├─ @theia/markers@0.6.1
├─ @theia/messages@0.6.1
├─ @theia/monaco@0.6.1
├─ @theia/navigator@0.6.1
├─ @theia/node-pty@0.7.8-theia004
├─ @theia/outline-view@0.6.1
├─ @theia/output@0.6.1
├─ @theia/preferences@0.6.1
├─ @theia/process@0.6.1
├─ @theia/terminal@0.6.1
├─ @theia/textmate-grammars@0.6.1
├─ @theia/typescript@0.6.1
├─ @theia/userstorage@0.6.1
├─ @theia/variable-resolver@0.6.1
└─ @theia/workspace@0.6.1

**Comment by maxhillaert** [comment]
I'm trying to debug the theia while its running.  

I notice that my extension is being loaded and my breakpoint in that module is being hit
`.then(function () { return import('@msci/hello-world-extension/lib/browser/hello-world-extension-frontend-module').then(load) })`

The container of my module 

```
export default new ContainerModule(bind => {
    // add your contribution bindings here
    
    bind(CommandContribution).to(HelloWorldExtensionCommandContribution);
    bind(MenuContribution).to(HelloWorldExtensionMenuContribution);
```

is indeed being loaded in 

```
function load(raw) {
    return Promise.resolve(raw.default).then(module =>
        container.load(module)
    )
}

```
For some reason though none of its contributions are to be found in the theia code when I put a break point in for instance in MenuModelRegistry below at the this.contributions.getContributions() , my contributions aren't to be found.  

```
@injectable()
export class MenuModelRegistry {
    protected readonly root = new CompositeMenuNode('');

    constructor(
        @inject(ContributionProvider) @named(MenuContribution)
        protected readonly contributions: ContributionProvider<MenuContribution>,
        @inject(CommandRegistry) protected readonly commands: CommandRegistry
    ) { }

    onStart(): void {
        for (const contrib of this.contributions.getContributions()) {
            contrib.registerMenus(this);
        }
    }
```

Any tips as to where I should be looking?  Clearly it can find my code, but for some reason, because of where I ran theia build, something must be different and cause theia not to find the contributions of my module

**Comment by maxhillaert** [comment]
This is act

**Comment by akosyakov** [comment]
Can someone transfer issue to https://github.com/theia-ide/generator-theia-extension? GitHub does not allow me.

**Comment by vince-fugnitto** [comment]
The **`watch`** workflow was described [here](https://spectrum.chat/theia/general/running-theia-build-in-hello-world-extension-project-browser-app-folder-breaks~ebf332b7-fe3a-44c3-bfaf-21abcd68b4db?m=MTU1ODMxNjIyMjM0MQ==) if anyone had similar issues.

The main idea is the following:
- Perform `yarn` at the root of the repository.
- Start the browser application by `(cd browser-app && yarn start)`.
- In order to watch the extension, perform `(cd {extension-name} && yarn watch)` in a new terminal.
- In order to watch the application (so it can see changes from the extension), perform `(cd browser-app && yarn watch)` in a new terminal.

In this way, the application is running, the extension is being watched for changes, and the browser application is being watched for changes to the extension.

**Comment by vince-fugnitto** [comment]
> Can someone transfer issue to https://github.com/theia-ide/generator-theia-extension? GitHub does not allow me.

Sure, no problem!
https://github.com/theia-ide/generator-theia-extension/issues/36

**Comment by marcdumais-work** [comment]
> Can someone transfer issue to https://github.com/theia-ide/generator-theia-extension? GitHub does not allow me.

Looks-like there is a bug in the issue transfer feature. When selecting the destination GH repo, I see the list of repos for a fraction of a second, then the drop-down is empty...

**Comment by vince-fugnitto** [comment]
Closing as it's been transferred to https://github.com/theia-ide/generator-theia-extension/issues/36
