### ISSUE TITLE
vscode-java-debug plugin's weird behavior: debug button needs to be pressed twice to work

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#5189]
### Description
When I tried to deploy vscode-java-debug plugin on theia, I noticed a weird behavior of this plugin: debug button needs to be pressed twice to work. This happens whenever I refresh the browser. After the first click which runs super silently and produces neither error nor warning, the debug button works just fine. 

After I took a while to look at this issue, I found that it happens when the vscode-java-debug plugin tries to activate "redhat.java" plugin. Look at this function from source code of vscode-java-debug:

```typescript
export async function getJavaHome(): Promise<string> {
    const extension = vscode.extensions.getExtension("redhat.java");
    try {
        const extensionApi = await extension.activate();
        if (extensionApi && extensionApi.javaRequirement) {
            return extensionApi.javaRequirement.java_home;
        }
    } catch (ex) {
    }

    return "";
}
```

Notice the "await extension.activate()" function call, that's where the debug process "awaits forever" from the first click.

Then I looked into theia source code relating to plugins, and thought I found the answer. Theia override the "activate" funtion and here is how it works  (from plugin-ext/src/plugin/plugin-context.ts):

```typescript
    activate(): PromiseLike<T> {
        return this.pluginManager.activatePlugin(this.id).then(() => this.exports);
    }
```

Plus, this is the source code of function "activatePlugin" (from plugin-ext/src/plugin/plugin-manager.ts):

```typescript
    activatePlugin(pluginId: string): PromiseLike<void> {
        if (this.pluginActivationPromises.has(pluginId)) {
            return this.pluginActivationPromises.get(pluginId)!.promise;
        }

        const deferred = new Deferred<void>();
        this.pluginActivationPromises.set(pluginId, deferred);
        return deferred.promise;
    }
```

The logic behind the "blocking behavior" is simple, the "deferred.promise" is never resolved, which means the "then" function in "activate" function will never be executed (thus, the function never returns).

The problem remains, however, how should we solve this. I tried to add a line to resolve the promise before it's returned, and it seems works fine - this issue never happens again. But I am just not sure if this is the best way or even a proper way to solve the problem. So I decided that I should just write this issue, make a PR and then wait for comments from those who know it better.

### Reproduction Steps
1. Remove java and java-debug extensions from examples/browser/package.json;
2. Compile and run theia of commit ID 086ce7208da1 (current master);
3. Deploy redhat-java plugin of version 0.43.0 (current newest) and java-debug plugin of version 0.15.0 (newer version is available but seems incompatible with theia);
4. Open a java project, add a debug configuration, and click on the debug button ( either the green triangle one from debug extension or the "run | debug" button that reveals in the editor), and nothing shall happen;
5. Click the button again, and it works fine;
6. Refresh the browser and repeat process 3-4.

**OS and Theia version:**
OS: Linux
Theia: 086ce7208da1 (current master)

**Diagnostics:** 
see above.

**Comment by benoitf** [comment]
Thanks for the detailed report !

**Comment by a1994846931931** [comment]
Solved.
