### ISSUE TITLE
Can't build and start browser app after building and starting electron app 

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#520]
Using latest master. 
macOS 10.12.6
Node v7.10.0
npm 4.2.0
yarn 0.27.5

I have built and ran successfully the electron app with this command:
yarn \
&& yarn run rebuild:electron \
&& cd examples/electron \
&& yarn run start

After that, if I try to the equivalent for the browser and it didn't work:
$ yarn && yarn run rebuild:browser && cd examples/browser && yarn run start
...
Starting express on port '3000'.
Failed to start the backend application.
Error: The module '/Users/mark/git/theia/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mark/git/theia/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
(node:63558) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The module '/Users/mark/git/theia/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
(node:63558) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 11.22s.

**Comment by hexa00** [comment]
Dup/Related of #445

**Comment by MarkZ3** [comment]
Oops forgot about that one

**Comment by gbodeen** [comment]
This problem was not present in Theia 0.12.0 but is now back in Theia 0.13.0.

**Comment by akosyakov** [comment]
@gbodeen please open a new issue to get help, please provide what commands you run, make sure that you did `rebuild:electron`. Nothing about building for electron was changed in last 3 years, usually it is misconfiguration of dev environments or some missing command.
