### ISSUE TITLE
[search-in-workspace] rename 'Clear All' to 'Clear Search Results'

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5204]
**Description**

Rename the `search-in-workspace` command **`Clear All`** to **`Clear Search Results`**.

https://github.com/theia-ide/theia/blob/f39185a362d24456d12e187b47f6d978bc7d6048/packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts#L63

This aligns with [vscode](https://github.com/microsoft/vscode/blob/6d444df6669feb905909e636741bd7a770ed570a/src/vs/workbench/contrib/search/browser/searchActions.ts#L350), and is more informative than `Clear All`.

**Comment by bolariin** [comment]
I would like to resolve this
