### ISSUE TITLE
TypeScript parse error

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5225]
### Description
TypeScript parse error
![image](https://user-images.githubusercontent.com/10203793/58240422-8a870800-7d7d-11e9-9fe4-1037e957ada3.png)

in theia
![image](https://user-images.githubusercontent.com/10203793/58236422-70e1c280-7d75-11e9-937d-9deb07c2066a.png)

in vscode
![image](https://user-images.githubusercontent.com/10203793/58236432-76d7a380-7d75-11e9-9c44-60a27f397b3a.png)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
@502647092, as far as I know, the `JSON` definition comes from `typescript`. See [here](https://github.com/microsoft/TypeScript/blob/e6013335b9ed9c74fc0c6516a17af0f0504caca9/lib/lib.es2015.symbol.wellknown.d.ts#L145-L147). Please check whether you have `typescript` among your dependencies in the `package.json`. If everything seems correct on your side, can you please share a bare minimum project setup as I was unable to reproduce the issue you have reported. Thanks!

**Comment by 502647092** [comment]
@kittaakos 
https://ide.yumc.pw/#/home/project
you can test at this address
use docker image theiaide/theia:next

**Comment by 502647092** [comment]
@kittaakos can you help me ?

**Comment by kittaakos** [comment]
@502647092, I have checked your project setup yesterday, thank you,  but I wasn't able to figure out what could cause the problem. The closest issue I have found is this one: https://github.com/theia-ide/theia/issues/4865. Unfortunately, for some reason, I was not able to switch between the TS versions.

@akosyakov, any ideas what could be the problem?

**Comment by kittaakos** [comment]
@502647092, can you try to pin the TS version in the `.settings.json`?
See how we do it for Theia: https://github.com/theia-ide/theia/blob/7d37b1245ab15f91ffdcf8606ffe7b5efe02ba2f/.theia/settings.json#L13

**Comment by 502647092** [comment]
@kittaakos i set this config and switch ts version 
Solve this problem
![image](https://user-images.githubusercontent.com/10203793/58309972-2a08d100-7e38-11e9-9519-242b88487572.png)
![image](https://user-images.githubusercontent.com/10203793/58309982-312fdf00-7e38-11e9-96bb-229e7cf9cb3e.png)
But I think it's a BUG.

**Comment by kittaakos** [comment]
> Solve this problem

👍

> But I think it's a BUG.

Yes, please rephrase the issue title to indicate the nature of the problem. Thanks!

**Comment by 502647092** [comment]
@kittaakos I am not very good at English
you can edit this issue

**Comment by akosyakov** [comment]
Could some point me to a project with bogus setup? I want to try in VS Code to understand how they manage to auto-detect. We are looking in all node_modules of roots. Could it be that in VS Code `CircleCloutRobot` is a workspace root (in multi-root workspace) and in Theia you just open it as a folder of a single workspace root?
