### ISSUE TITLE
[tasks] update terminal title for user tasks

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5226]
**Description**

Currently, when executing a `task` (ex: shell), we launch a terminal with an incremental terminal name (ex: `Terminal 0`). I propose we instead replace the terminal title, with that of the task name.
This will allow users to easily identify which terminal consists of which running task.

If ever there are more than one task running of the same type, we can add append an incremental value as well.

|Before|After|
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/40359487/58245605-2d5e6880-7d23-11e9-9e7c-83ed3bf9b5bc.png) | ![image](https://user-images.githubusercontent.com/40359487/58245699-61398e00-7d23-11e9-9853-00a7494b88a6.png)|

**Comment by AndrienkoAleksandr** [comment]
Related https://github.com/theia-ide/theia/issues/4523

**Comment by akosyakov** [comment]
@vince-fugnitto sounds good

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto sounds good. Are you taking care about it?

Sure, I can handle it when I get a chance :)
