### ISSUE TITLE
Refreshing the page will cause the jdt process to increase and the oom phenomenon 

### ISSUE THREAD

**Issue by hackerhome5** [theia-ide/theia#5235]
Precondition：
1、install vscode-java、ms-python eg.
2、theia to be started
3、open java project in workspace 
3、at browser，f5 again and again

So: the jdt process to increase and the oom phenomenon

**Comment by AlexTugarev** [comment]
Any insights to share about this?

**Comment by xieyuanhuata** [comment]
> Any insights to share about this?

I have left Huawei, but my Git records are still the same. Can you help me delete this PR?thank you very much!

**Comment by xieyuanhuata** [comment]
I made a very outdated name for the sake of being cool. But the name is too unsafe.
so can you help me delete this pr,thank you very much

**Comment by xieyuanhuata** [comment]
I am a friendly and gentle technology lover，but the name "hackerhome5" is cazing and  misunderstanding，so I don't want to be scared。

**Comment by xieyuanhuata** [comment]
Can you help delete this pr,because i have submit another same one (5235)
