### ISSUE TITLE
[editor] The input box is always fixed in the upper left corner

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5237]
### Description
the input box of some input method is always fixed in the upper left corner.
E.g Microsoft Pinyin
![image](https://user-images.githubusercontent.com/35068357/58307473-52410180-7e31-11e9-90b1-9e53d9d1760b.png)

**Comment by svenefftinge** [comment]
Can you elaborate a bit more on this? I don't understand what's in the picture.

**Comment by kpge** [comment]
when inputting a character  with Chinese input method , the input box is always floating on the upper left corner, can not under where I typed
