### ISSUE TITLE
[scm] wrong icon for open changes

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#5245]
before the merge of the SCM PR it looked like this:

<img width="91" alt="Screen Shot 2019-05-24 at 13 00 24" src="https://user-images.githubusercontent.com/914497/58323495-6af6ea80-7e24-11e9-9bb3-84aced879200.png">

and now:

<img width="117" alt="Screen Shot 2019-05-24 at 13 00 37" src="https://user-images.githubusercontent.com/914497/58323397-1d7a7d80-7e24-11e9-90b2-f2fe91ac358f.png">

@vinokurig, cf. https://github.com/theia-ide/theia/pull/4279#issuecomment-492511793, @akosyakov's comment was not addressed

**Comment by vinokurig** [comment]
Thanks, working on it right now

**Comment by vinokurig** [comment]
fixed in https://github.com/theia-ide/theia/pull/5254

**Comment by akosyakov** [comment]
`Open File` is also affected.

**Comment by vinokurig** [comment]
Fixed the `Open File`
