### ISSUE TITLE
Cannot pull docker image of theiaide/theia

### ISSUE THREAD

**Issue by ziatdinovmax** [theia-ide/theia#5258]
### Description
Cannot pull docker image of **theiaide/theia** but can pull docker image of **theiaide/theia-python**

### Reproduction Steps
1. Install Docker on Linux (Debian)
2. Run `sudo docker pull theiaide/theia-python` (Success!)
3. Run `sudo docker pull theiaide/theia` (Fails!)
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /home/theia: invalid argument

**OS and Theia version:**
Debian GNU/Linux 9 (stretch)
Theia version: N/A

**Comment by marcdumais-work** [comment]
Hi @ziatdinovmax ,

I just tried to pull the theiaide/theia image and it worked. It may have been a glitch with one nightly build, self-corrected the next day. Strange it would fail like this during pull, though. Can you give it another try and report back?

```
marc@gimli:~/theia/examples/browser$ docker pull theiaide/theia
Using default tag: latest
latest: Pulling from theiaide/theia
e7c96db7181b: Pull complete 
df9eac31dfef: Pull complete 
0a20433d95a4: Pull complete 
d53b0db18c52: Pull complete 
2e1139a65c76: Pull complete 
fc96935cd16a: Pull complete 
3c17f5fc80d3: Pull complete 
Digest: sha256:999b00dfc7b640cf1cb06e5c3d08e5e7fb534484d0c2357435355e0e2f9b9fbc
Status: Downloaded newer image for theiaide/theia:latest
```

**Comment by ziatdinovmax** [comment]
No luck, unfortunately. However, I can easily pull theia-full (please see below).

```
ziatdinovmax@penguin:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
ziatdinovmax@penguin:~$ sudo docker pull theiaide/theia
Using default tag: latest
latest: Pulling from theiaide/theia
e7c96db7181b: Pull complete 
bbec46749066: Pull complete 
89e5cf82282d: Pull complete 
43bd485620a9: Extracting [==================================================>]   1.27kB/1.27kB
1868300d0559: Download complete 
528dd57b98b6: Download complete 
291517096657: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /home/theia: invalid argument
ziatdinovmax@penguin:~$ sudo docker pull theiaide/theia-full
Using default tag: latest
latest: Pulling from theiaide/theia-full
6abc03819f3e: Pull complete 
05731e63f211: Pull complete 
0bd67c50d6be: Pull complete 
3e2438b31826: Pull complete 
f31d5dacb221: Pull complete 
f1bc1065e876: Pull complete 
0d3520ffbf3e: Pull complete 
2b905554e3d6: Pull complete 
a70452cdf687: Pull complete 
18ea637a8998: Pull complete 
96a9186fdfe9: Pull complete 
5c3db7f164e0: Pull complete 
4ff11459e0c6: Pull complete 
e19eb51268d6: Pull complete 
264f060789ee: Pull complete 
b3d340097081: Pull complete 
1825117e93ea: Pull complete 
10021e9c7408: Pull complete 
d404c9dc44b7: Pull complete 
0a98110758a5: Pull complete 
Digest: sha256:1d857f12533d3e82d359e77c9952112676c09552abc0ffcfafe5f83a0298404d
Status: Downloaded newer image for theiaide/theia-full:latest
```

**Comment by marcdumais-work** [comment]
@ziatdinovmax I am able to pull the same image:
```
marc@gimli:~$ docker pull theiaide/theia
Using default tag: latest
latest: Pulling from theiaide/theia
e7c96db7181b: Already exists 
bbec46749066: Pull complete 
89e5cf82282d: Pull complete 
43bd485620a9: Pull complete 
1868300d0559: Pull complete 
528dd57b98b6: Pull complete 
291517096657: Pull complete 
Digest: sha256:3502b02825df3cdb208d57a0539a6561e4e34c8091f39961b0e607083e66c535
Status: Downloaded newer image for theiaide/theia:latest
```

On what type of platform is your Debian OS running? e.g.: on physical hardware, in a VM, in a container / 
cloud environment?

**Comment by marcdumais-work** [comment]
A couple of issues with the same docker error (not involving a Theia image): 

https://github.com/rootless-containers/rootlesskit/issues/48 : root cause seems to be docker uid/guid  mis-configuration.
https://github.com/kubernetes/minikube/issues/946 : root cause: problems running docker inside LXD container.

**Comment by ziatdinovmax** [comment]
It's a container on ChromeOS, which is apparently the reason why it didn't work and that has nothing to do with Theia :)
Thanks for your time and thanks for the great product! (I'm using it a lot via Gitpod)

> On what type of platform is your Debian OS running? e.g.: on physical hardware, in a VM, in a container /
> cloud environment?

**Comment by akosyakov** [comment]
@ziatdinovmax glad that you figure it out, please reopen if there is something else to resolve
