### ISSUE TITLE
[scm] proper main menu contribution

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5263]
It should be `SCM`, there should be a keybinding to toggle it as it was for git extension before.

Right now:
<img width="483" alt="Screen Shot 2019-05-27 at 10 57 02" src="https://user-images.githubusercontent.com/3082655/58408542-51e17a00-806e-11e9-9b2d-57a7cf96d44b.png">

@vinokurig Is it addressed somewhere already?

**Comment by vinokurig** [comment]
@akosyakov working on it now

**Comment by vinokurig** [comment]
Fixed in #5245
