### ISSUE TITLE
[scm] clean up git-commands methods declared as properties

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5264]
It makes sense only if they are used as React callbacks which is not the case.

cc @vinokurig

**Comment by vinokurig** [comment]
@akosyakov Could you please clarify what is the problem, is it related to https://github.com/theia-ide/theia/pull/5256?

**Comment by akosyakov** [comment]
It's minor. You don't need to look into it immediately.

Here for example:
https://github.com/theia-ide/theia/blob/89f71edc4b417b8ce717897018c2aa1210435cd4/packages/git/src/browser/git-commands.ts#L166-L169

`openFile` method is declared as a property, it is not necessary, it can be just a method. Such pattern should be only used to pass functions by a reference into react event handlers to improve performance.
