### ISSUE TITLE
[scm/git] bogus inline command contribution

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5265]
Right now:
<img width="650" alt="Screen Shot 2019-05-27 at 11 00 55" src="https://user-images.githubusercontent.com/3082655/58408769-cae0d180-806e-11e9-953c-b187fb9b64e3.png">

How it should be:
<img width="637" alt="Screen Shot 2019-05-27 at 11 02 24" src="https://user-images.githubusercontent.com/3082655/58408826-f06ddb00-806e-11e9-9943-4736b3b38887.png">

**Comment by akosyakov** [comment]
Also duplicate and without categories:
<img width="653" alt="Screen Shot 2019-05-27 at 11 03 37" src="https://user-images.githubusercontent.com/3082655/58408904-34f97680-806f-11e9-85b4-4f86f78eceef.png">

**Comment by akosyakov** [comment]
There should not be such concept as inline commands in Theia core. It is a matter of scm/git extension that they inline some.

**Comment by vinokurig** [comment]
I think it is fixed in https://github.com/theia-ide/theia/pull/5254

**Comment by akosyakov** [comment]
@vinokurig please add category `Git` to all registered git commands which have label but without `Git: ` in it. Somehow before they were not available in command palette, but now they are but without proper prefix.

**Comment by vinokurig** [comment]
> @vinokurig please add category Git to all registered git commands which have label but without Git: in it. Somehow before they were not available in command palette, but now they are but without proper prefix.

Done
