### ISSUE TITLE
[scm] unnecessary information in status bar

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5266]
i.e. `Git` suffix:
<img width="302" alt="Screen Shot 2019-05-27 at 11 20 07" src="https://user-images.githubusercontent.com/3082655/58410182-edc0b500-8071-11e9-8785-85d8266e8705.png">

It should be just repo name. A user can select it to reveal the repo and see detail information there. As it used to be before.

**Comment by vinokurig** [comment]
Fixed in https://github.com/theia-ide/theia/pull/5254
