### ISSUE TITLE
Build failed on ubuntu18, nodejs 10.15

### ISSUE THREAD

**Issue by dingbig** [theia-ide/theia#5275]
### Description

When I build theia ide by runing "yarn" on ubuntu18, x64, nodejs 10.15
I got errors:

### Terminal output

yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-68e88639-6ce0-476f-8491-bbc5ebd23952 > 
@theia
/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-68e88639-6ce0-476f-8491-bbc5ebd23952 > 
@theia
/debug > requestretry@3.1.0" has unmet peer dependency "request@2..".
warning "workspace-aggregator-68e88639-6ce0-476f-8491-bbc5ebd23952 > 
@theia
/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[10/14] ⠂ find-git-repositories
[8/14] ⠂ oniguruma
[-/14] ⠂ waiting...
[11/14] ⠂ 
@theia
/electron
error /home/d/theia/node_modules
/@theia
/electron: Command failed.
Exit code: 127
Command: node ./scripts/skip-replace-ffmpeg || (node ./electron-replace-ffmpeg && node ./electron-h264-test)
Arguments:

d@ide:~/theia$

### marc-dumais said

 is right - this build failure is a side-effect of a recent patch where we replace libffmpeg delivered with Electron. We are working on a follow-up patch that removes this side-effect. In the meantime you can work-around the failure by setting an environment variable before building: THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1

**Comment by akosyakov** [comment]
cc @marechal-p

**Comment by marechal-p** [comment]
@akosyakov @dingbig there are two ways of fixing this:

1. Temporarely disable the testing on install: https://github.com/theia-ide/theia/pull/5112.
  But somehow this never got merged, so I don't know what to do. I can re-open.
2. Finish the native test that will be able to run on any environment: https://github.com/theia-ide/theia/pull/5210.
  I don't have the time to finish the Windows port at the moment, but it is my next priority.
  Windows and Linux already work flawlessly.

**Comment by vince-fugnitto** [comment]
Closing as #5112 and #5210 are currently merged.
Please re-open if the issue persists.
