### ISSUE TITLE
Git history auto scroll to the top

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5276]
### Description
when i view the git history
is auto scroll to the top
![temp](https://user-images.githubusercontent.com/10203793/58445524-89fcc180-812f-11e9-93e3-b29a1bf066bb.gif)

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 Do you know how to reproduce it with master state with running git history on Theia repo? I cannot.

**Comment by 502647092** [comment]
@akosyakov i can't reproduce it
But sometimes this problem arises.
