### ISSUE TITLE
[vscode]Leaking java debug process

### ISSUE THREAD

**Issue by tom-shan** [theia-ide/theia#5279]
### Description
When start debugging using vscode java-debug extension, the debug process will remain in OS process list and never be killed by theia process if the page is reloaded.
If I don't kill the debug process manually and start a new debug session, the debug console will show the exception of "Address already in use".

### Reproduction Steps
* install jdk and maven
```
apt-get install openjdk-11-jdk
apt-get install maven
```
* git clone https://github.com/theia-ide/theia.git && cd theia
* Delete theia java and java-debug extensions, for I only want to use debug function provided by vscode java-debug extension
```
sed -i '/theia\/java/d' examples/browser/package.json
mkdir plugins
wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.44.0/vspackage -O plugins/redhat.java-0.44.0.vsix
wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-debug/0.15.0/vspackage -O plugins/vscjava.vscode-java-debug-0.15.0.vsix
```
* yarn
* cd examples/browser && yarn start
* Open a spring java project (you can git clone https://github.com/spring-projects/spring-petclinic ) and press F5 (for now you may need to press twice) to start debugging session.
* Click browser reload button and press F5 (Start Debugging button), the debug console will show error logs.
```
org.apache.catalina.util.LifecycleBase : Failed to start component [Connector[HTTP/1.1-8080]]
org.apache.catalina.LifecycleException: Protocol handler start failed
Caused by: java.net.BindException: Address already in use
```
**OS and Theia version:**
OS: Ubuntu 18.04
Theia version: latest master version

**Diagnostics:** 
1. click **Start Debugging** button and reload the page
![leaking-debug-process-p1](https://user-images.githubusercontent.com/7686800/58449976-7e18fb80-813f-11e9-8de4-bfa443844e0d.gif)
2. click **Start Debugging** button again, but failed to start the debug session
![leaking-debug-process-p2](https://user-images.githubusercontent.com/7686800/58449983-83764600-813f-11e9-9eaa-eaf3766b303b.gif)
3. there are some errors in **Debug Console**
![leaking-debug-process-p3](https://user-images.githubusercontent.com/7686800/58449990-8b35ea80-813f-11e9-87db-c59ce7eb6505.gif)
4. leaking java debug process
![normal-debug-process](https://user-images.githubusercontent.com/7686800/58463026-af0c2700-8165-11e9-80c5-daa558c0c552.PNG)

**Comment by akosyakov** [comment]
Please use direct urls to download:
```
wget https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/java/0.44.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -O plugins/redhat.java-0.44.0.vsix
wget https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-debug/0.15.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -O plugins/vscjava.vscode-java-debug-0.15.0.vsix
```

**Comment by akosyakov** [comment]
I was able to reproduce it. For some reasons java process is not killed as a child of plugin-host process.

**Comment by tom-shan** [comment]
> I was able to reproduce it. For some reasons java process is not killed as a child of plugin-host process.

I try to fix this bug by killing the child processes of plugin-host process in plugin-ext package.
I will create a PR later and please have a review.

**Comment by tom-shan** [comment]
For the [PR](https://github.com/theia-ide/theia/pull/5257) about plugin process cache is merged recently, this PR will not work.
So before startting theia, the plugin process cache should be overridden by setting the env variable below.
```
export THEIA_PLUGIN_HOST_MIN_KEEP_ALIVE=0
```

**Comment by akosyakov** [comment]
cc @amiramw
