### ISSUE TITLE
Markdown preview is not synchronized with the editor when scrolls

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#5280]
### Description
I guess it's more like a design problem. Currently, the preview window scrolls automatically only when the selected line is changed. And the first line in the preview window is corresponding to the selected line in editor. In vscode, however, it behaves quite differently: the preview window scrolls automatically when the editor is scrolled, and they are aligned based on the content of the first line. (But if you scroll the preview window instead, the editor will follow it, and behave exactly the same way as vscode does)

Should we adopt the behaviour of vscode on this? IMHO, the current behaviour is OK, but the one on vscode is more natural to me.

### Reproduction Steps
- Open a markdown and its preview on the other side
- Scroll the editor or the preview window, and see how the other one follows

**OS and Theia version:**
OS: linux
Theia: 0.6.0

**Diagnostics:** 
none

**Comment by vince-fugnitto** [comment]
I like the idea that the preview follows, especially for markdown :)
Like you said, we should adopt the vscode way, and make it so wherever you scroll from (editor or preview), the other follows.
