### ISSUE TITLE
Theia Dev Conf F2F Topics

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#5285]
This issue serves as a list of topics that would make sense to discuss face to face at theia dev con. There will be break-out rooms for deep-dive discussions.
If you're the instigator of a topic, please name the parties you think should participate

What | Instigator | Stakeholders
--|--|--
Reorganizations in the plugin engine as discussed in: https://github.com/theia-ide/theia/issues/3871 | @tsmaeder | @evidolob @akosyakov @benoitf

**Comment by dneary** [comment]
@tsmaeder FYI: There are 3 1-hour sessions in the schedule (two on day 1, one on day 2) which are designed to allow discussion of topics of general interest - my expectation is that people will use these sessions to agree what can be agreed quickly, and identify a small group for a break-out for those topics which need more time.

**Comment by svenefftinge** [comment]
@tsmaeder given theia dev con is over, can this issue be closed?

**Comment by AlexTugarev** [comment]
Also, the README.md can be updated.
