### ISSUE TITLE
Navigate and inline are lower case in the command menu

### ISSUE THREAD

**Issue by JPinkney** [theia-ide/theia#5291]
![2019-05-28-154410_1920x1080_scrot](https://user-images.githubusercontent.com/8839537/58507350-90a32d00-815f-11e9-9e9e-45b72b8aa3b0.png)

![2019-05-28-154610_1920x1080_scrot](https://user-images.githubusercontent.com/8839537/58507453-cf38e780-815f-11e9-9143-0e60d9a6d971.png)

I believe they are expected to be capitalised, unless there is some reason they are lower case.

**Comment by akosyakov** [comment]
That's a bug from scm, there should not be `navigation` and `inline`.

@vinokurig it should have been fixed in https://github.com/theia-ide/theia/pull/5254?

**Comment by vinokurig** [comment]
It is fixed in https://github.com/theia-ide/theia/pull/5254
