### ISSUE TITLE
The command for 'Clear Output' should be available as a quick open action.

### ISSUE THREAD

**Issue by westbury** [theia-ide/theia#5298]
PR https://github.com/theia-ide/theia/pull/5134 creates a command for the 'Clear Output' button in the output view toolbar.  This command should also be available as a Quick Open action (ctrl-shift-P), like in VS Code.

**Comment by vince-fugnitto** [comment]
The `Output: Clear Output` command already exists in the quick-commands menu, please re-open
the issue if this is not actually the case.

**Comment by westbury** [comment]
> The `Output: Clear Output` command already exists in the quick-commands menu

@vince-fugnitto you are correct.  I misunderstood how the quick-commands worked when I opened this ticket.  Thanks for closing it.
