### ISSUE TITLE
Refactor Git extension to use Scm where possible

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#5299]
### Description
`GitRepositoryProvider` and `ScmService` have duplicated functions. Need to refactor the Git extension to use Scm repositories

See https://github.com/theia-ide/theia/pull/5254#issuecomment-496487672

**Comment by akosyakov** [comment]
@vince-fugnitto https://github.com/theia-ide/theia/issues/5295 is a dup of this issue? let's do it after release please

**Comment by vinokurig** [comment]
yes
