### ISSUE TITLE
[scm] don't inject ScmWidget

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5306]
- remove `ScmWidget` from singleton scope that it can be garbage collected
- replace `ScmWidget` injections with `ScmContribution.widget`

**Comment by vinokurig** [comment]
It causes a bug: If close and then reopen the Scm tab the widget won't be updated by scm events.
Looks like this update is called to the old widget:
https://github.com/theia-ide/theia/blob/6f164f79e5b49389f9932ef72ee740ed59b07dcc/packages/scm/src/browser/scm-widget.tsx#L101

**Comment by akosyakov** [comment]
@vinokurig When a widget is disposed it must to release all listeners, when a new widget is created it should update on attachment.
