### ISSUE TITLE
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}

### ISSUE THREAD

**Issue by dhananjayharel** [theia-ide/theia#5311]
### Description
I started getting this error since yesterday.
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}

Whenever I build the editor using DockerFile after starting the docker the browser console gives this error.
Initially I thought because of my extension but then removed my extensions and built again but same error.

### Reproduction Steps

**OS and Theia version:**
Latest version compiled from docker
**Diagnostics:**

**Comment by akosyakov** [comment]
a dup of  https://github.com/theia-ide/theia/issues/5308
