### ISSUE TITLE
build partially through yarn to save time

### ISSUE THREAD

**Issue by yeonggyulim** [theia-ide/theia#5320]
### Description
Whenever I edit some code in one package, I do use  yarn and build all the packages and it takes around 5 minutes.

### Reproduction Steps
I want to edit only one package, for example filesystem package, and build not the every package, but the necessary ones and webpack to save time.

Is there any way to build the packages that I edited?

**Comment by kpge** [comment]
first ,U should run yarn in the edited package 
then ,U run yarn in the example/browser or example/electron
after they are completed, start theia

**Comment by yeonggyulim** [comment]
> first ,U should run yarn in the edited package
> then ,U run yarn in the example/browser or example/electron
> after they are completed, start theia

It works. Thank you so much!
