### ISSUE TITLE
Schema is missing

### ISSUE THREAD

**Issue by luxingxiao** [theia-ide/theia#5325]
Failed to start the frontend application
![image](https://user-images.githubusercontent.com/3615093/58703944-f51ef000-83dc-11e9-85ac-4bac97a721bb.png)

This is my configuration:
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next",
    "@theia/java": "next",
    "@theia/java-debug": "next",
    "@theia/debug": "next",
    "@theia/workspace": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}

**Comment by vince-fugnitto** [comment]
Thanks for the error, it's already been reported :)
Dupplicate of #5308
