### ISSUE TITLE
Default Layouting for Problems View, Terminal, Debug

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#533]
Now that we have a problem view (#26). And a terminal.

Would it make sense to have an area of the workspace dedicated to these kind of views ?
While I like that these are treated as a normal file buffers having no default layout for those is annoying.

I would like to have a container at the bottom where some types of views would open automatically.  Maybe you could still move them out but they would have a decent default layout...

And it would be nice to make this layouting configurable...

**Comment by svenefftinge** [comment]
It would be nice to allow attaching and detaching widgets from the sidebars (left, right, bottom).
So I could e.g. detach the file navigator which moves it to the main area and vice-versa. That allows also very reduced layouts for secondary windows (see #526).

**Comment by marcdumais-work** [comment]
A bottom panel is being added: see #1025

**Comment by spoenemann** [comment]
Solved with #1028.
