### ISSUE TITLE
Create custom filesystem

### ISSUE THREAD

**Issue by amitgilad3** [theia-ide/theia#5334]
I would like to implement my own filesystem - in my case i would like to create a in memory file system but im finding it hard to figure out how this is possible.
is there any documentation or could anybody give me a lead on where to start ??

**Comment by akosyakov** [comment]
You have to implement a new extension which contributes custom [FileSystem](https://github.com/theia-ide/theia/blob/0b456192efdb13a23844d15ff5300a12a239297b/packages/filesystem/src/common/filesystem.ts#L24) and rebind it in the frontend module. 

> is there any documentation or could anybody give me a lead on where to start ??

There is plenty of examples in the code. For general overviews see [here](https://www.theia-ide.org/doc/index.html)
