### ISSUE TITLE
[git] "Stopped/Started watching" git repo, on every change

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#5338]
### Description
Every time a file is changed, I see a pair of traces in the backend log, saying that the git repo watching has stopped and right after, started again. 

I do not know what this exactly means, but it sounds like it could be that the OS file watchers, watching a git repo, are being freed and re-allocated, again and again (hopefully not the case). 

### Reproduction Steps
- build and start the browser example
- watch the terminal where the backend was started
- open a file in theia's editor.
- make changes in the file, saving once in a while or letting auto-save do it for you
  -> each time a change is saved, a pair of traces (see below) appears in the B-E log.

**OS and Theia version:**
ubuntu 16.04, theia browser example app, built from latest master

**Diagnostics:** 

```
root INFO Stopped watching the git repository: file:///opt/ericsson-dev/theia
root INFO Started watching the git repository: file:///opt/ericsson-dev/theia
```

**Comment by akosyakov** [comment]
If it is reproducible we have to fix it asap. Probably caused by scm or again (

**Comment by akosyakov** [comment]
yes, i was able to reproduce @vinokurig Can you take care about it today? cc @evidolob

**Comment by vinokurig** [comment]
@akosyakov Yes, working on it

**Comment by vinokurig** [comment]
@akosyakov Are you sure that this bug is relates to the SCM PR? I've reverted it localy and I could reproduce the bug.

**Comment by akosyakov** [comment]
@vinokurig checking now against https://github.com/theia-ide/theia/commit/2a1c24973ed9833c54b5b2838f52b184f3343be2

**Comment by vinokurig** [comment]
I've prepared a PR about refactor Git module to SCM https://github.com/theia-ide/theia/pull/5339 that fixes this bug

**Comment by akosyakov** [comment]
@vinokurig i cannot reproduce it with revision before SCM PR


> I've prepared a PR about refactor Git module to SCM #5339 that fixes this bug

checking

**Comment by akosyakov** [comment]
#5339 is too big and breaking? is there a way for small fix of this issue?

**Comment by vinokurig** [comment]
I'll try to extract a particular fix for it

**Comment by vinokurig** [comment]
@akosyakov Looks like it is not possible to extract a particular fix. All the changes are needed. I am working on the comments  from the PR.

**Comment by akosyakov** [comment]
@marcdumais-work Can we do 7.0.1 without SCM fixes? I won't have time to review today and it will be breaking. And we do later 7.1.0 this week?

**Comment by lmcbout** [comment]
Thanks @kittaakos great improvement with issue #5284 , I notice that the watchers with electron  for the git repos start about 6 times, then if you wait about ~20-30 secondes, a timer error occurs and then  start/stop the git repo occurs in a loop. Was reproduce-able on a window environment this morning (~5-6 times in a row)

**Comment by vince-fugnitto** [comment]
> Thanks @kittaakos great improvement with issue #5284 , I notice that the watchers with electron for the git repos start about 6 times, then if you wait about ~20-30 secondes, a timer error occurs and then start/stop the git repo occurs in a loop. Was reproduce-able on a window environment this morning (~5-6 times in a row)

I don't believe it has to do with `electron`, the following can also be seen in the `browser` app.
