### ISSUE TITLE
[plug-in][tasks] Add ability to fetch all tasks

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#5342]
### Description
Add [tasks.fetchTasks()](https://github.com/microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L5059) API to provide ability to get all tasks available in the systems

**Comment by elaihau** [comment]
I created https://github.com/theia-ide/theia/pull/5348 as a draft of the implementation.
