### ISSUE TITLE
[Terminal] Remove the user prompt from the terminal title

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5345]
### Description
The title on the terminal is too long, we should reduce the text by removing the user prompt

### Reproduction Steps
![image](https://user-images.githubusercontent.com/419051/58806722-c70bfc80-85e4-11e9-8e9b-5984cbefeccc.png)

**OS and Theia version:**
Ubuntu 16.04
Theia 0.7.0

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@lmcbout I updated the title since it is more to do with the `terminal` and not the tasks themselves.

**Comment by rubenanapu** [comment]
To solve this you just need to modify the environment variable called PS1 on Linux.
You can do that on the .bashrc file.

**Comment by lmcbout** [comment]
It is define per user, so let close it.
