### ISSUE TITLE
maybe have a memory leak

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5355]
### Description
thread count 
![image](https://user-images.githubusercontent.com/10203793/58933366-94573500-8799-11e9-8212-4330614222a8.png)
load avg
![image](https://user-images.githubusercontent.com/10203793/58933380-a20cba80-8799-11e9-81b9-9b4a2b4a2854.png)
after i close theia
![image](https://user-images.githubusercontent.com/10203793/58933532-1f382f80-879a-11e9-94b3-17c7efff6bbe.png)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Could you enable debug level logging and check which ipc process is spawned so often? git or filesystem watching? Maybe the same as https://github.com/theia-ide/theia/issues/5338

**Comment by 502647092** [comment]
@akosyakov 
i reproduce this problem
When the Theia version is updated but the browser cache is not refreshed, many new IPC processes will be created in the back end.
