### ISSUE TITLE
[SCM] no password input box in the web UI when click 'pull'

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5356]
### Description
I had a private repository in github, and I had cloned it with HTTPS based authentication, but when i click 'pull' in the webui, the password input box shown on the backend console instead of fronted web ui, is there any way for user to input username and password on the web ui?

![image](https://user-images.githubusercontent.com/35068357/58953639-acdf4380-87c9-11e9-8027-b4e3cd0b400a.png)
![image](https://user-images.githubusercontent.com/35068357/58954129-dba9e980-87ca-11e9-9cef-d752df74b257.png)

### Reproduction Steps
1.clone a private repository with HTTPS based authentication
2.click 'pull' or 'push' on the web ui

**OS and Theia version:**
OS: ubuntu 18.04
Theia version: 0.7.0
**Diagnostics:**

**Comment by kittaakos** [comment]
@kpge, it won't work. See [here](https://github.com/theia-ide/theia/issues/1037). We support HTTP based authentication in the [electron version only](https://github.com/theia-ide/theia/issues/3397).
