### ISSUE TITLE
throw new Error("error message");  doesn't show on Theia

### ISSUE THREAD

**Issue by ShimonBenYair** [theia-ide/theia#5361]
### Reproduction Steps
In my vscode extension when i run : throw new Error("error message");
An error is displayed on the screen with the error message.
But in Theia the error is not display.
Is there any api in Theia to throw execptions ?

**Comment by vince-fugnitto** [comment]
I'm sorry if I confused, but do you mean no error is thrown on Theia's backend?

**Comment by benoitf** [comment]
@ShimonBenYair I'm not sure as well to fully understand. Throw an error is like the same in any JavaScript world.

**Comment by vince-fugnitto** [comment]
Closing the issue due to inactivity, please re-open if the issue persists.
