### ISSUE TITLE
[settings] Keybinding search should ignore the key order 

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5368]
In `Keyboard Shortcuts` UI, when we do a keybinding search, the results should include all combinations of keys. For example, searching `alt + shift` should be equivalent to searching `shift + alt`

In Theia:
![Screenshot from 2019-06-05 16-15-53](https://user-images.githubusercontent.com/25921074/58987347-4fd59480-87ad-11e9-93fe-8f782e310a5a.png)
![Screenshot from 2019-06-05 16-21-22](https://user-images.githubusercontent.com/25921074/58987680-00439880-87ae-11e9-8a91-453fb2d062b4.png)

In VS Code:
![Screenshot from 2019-06-05 16-16-04](https://user-images.githubusercontent.com/25921074/58987363-56fca280-87ad-11e9-82ac-8f9a7e946b32.png)

**Comment by vince-fugnitto** [comment]
@fangnx is it something you'd like to try? :)

**Comment by fangnx** [comment]
Yep I will do this this afternoon ;)
________________________________
