### ISSUE TITLE
Cannot open new file

### ISSUE THREAD

**Issue by ShalokShalom** [theia-ide/theia#5376]
Once I clicked the Getting started tab away, was it impossible to open up a new file. 

Docker, on Linux. 

The option in the menu was greyed out and inaccessible.

**Comment by kittaakos** [comment]
@ShalokShalom, do you see any errors?

**Comment by ShalokShalom** [comment]
No, zero. It is just greyed out. There is also no shortcut I could use, yeah?

**Comment by akosyakov** [comment]
> @ShalokShalom, do you see any errors?

@ShalokShalom please make sure that you checked browser console and backend logs as well.

**Comment by ShalokShalom** [comment]
I have already uninstalled your software.
