### ISSUE TITLE
Add support for user defined pictures in TreeView

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#5378]
### Description

Theia plugins may add View Containers which may contain a user defined tree. Each node of the tree should be able to accept and display user defined image from plugin's resources.

**Comment by akosyakov** [comment]
@mmorhun Is it something specific to theia plugins? or generally for vscode extension? Could you point out to corresponding docs if it is the later.

**Comment by mmorhun** [comment]
I meant support for images from resources in `iconPath` field of the tree node.

**Comment by akosyakov** [comment]
I remember implementing it already: https://github.com/theia-ide/theia/blob/214a90248e6b8c458622fd0fcd9d551b5c9d799f/packages/plugin-ext/src/plugin/tree/tree-views.ts#L229-L255

Are you sure that it does not work?

**Comment by mmorhun** [comment]
Sorry, my mistake.
