### ISSUE TITLE
Remove warning about the loaders when using webpack

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#538]
When compiling, and using webpack, there are lots of warning about adding loaders, An example: 
You may need an appropriate loader to handle this file type.
| {"version":3,"sources":["../../../src/addons/search/SearchHelper.ts"],"names":[],"mappings":";;AAgBA;IACE,sBAAoB,SAAc,EAAU,4BAAiC;QAAzD,cAAS,GAAT,SAAS,CAAK;QAAU,iCAA4B,GAA5B,4BAA4B,CAAK;IAK7E,CAAC;IAQM,+BAAQ,GAAf,UAAgB,IAAY;QAC1B,EAAE,CAAC,CAAC,CAAC,IAAI,IAAI,IAAI,CAAC,MAAM,KAAK,CAAC,CAAC,CAAC,CAAC;YAC/B,MAAM,CAAC,KAAK,CAAC;QACf,CAAC;QAED

**Comment by hexa00** [comment]
See also: https://github.com/sourcelair/xterm.js/issues/877

**Comment by hexa00** [comment]
Fixed #539
