### ISSUE TITLE
Theia server is still up when electron window has been closed

### ISSUE THREAD

**Issue by VietHungPhan** [theia-ide/theia#5383]
### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
Thanks for filing this issue, @VietHungPhan. I think this is the same as #5385.

As the other issue has a bit more details about the defect, I would like to close this one in favor of the other.

**Comment by kittaakos** [comment]
@VietHungPhan, can you please try with https://github.com/theia-ide/theia/pull/5400?
