### ISSUE TITLE
[electron] Multiple electron menus/appIcons when starting the electron example

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5385]
### Description
 

I can see multiple application icons on my Dock on macOS when I start the electron example.

![Screen Shot 2019-06-06 at 21 53 53](https://user-images.githubusercontent.com/1405703/59062369-edac8a80-88a5-11e9-9994-8bf1be15c93f.jpg)

Each has a different application menu.
 1. The visible:
![Screen Shot 2019-06-06 at 21 56 54](https://user-images.githubusercontent.com/1405703/59062421-103ea380-88a6-11e9-84ef-b860504ea737.jpg)

 2. The "hidden?":
![Screen Shot 2019-06-06 at 21 56 47](https://user-images.githubusercontent.com/1405703/59062446-1d5b9280-88a6-11e9-9617-61ccb4f63d9b.jpg)

### Reproduction Steps
`yarn --cwd ./examples/electron/ start`

**OS and Theia version:**
macOS

0b1b8532f

It is just a wild guess but #5360 could be related. We start something else we did not do before. Smells like a regression.

**Comment by kittaakos** [comment]
Each time I refresh the browser window, I have a new app icon on the Dock:
![Screen Shot 2019-06-06 at 22 14 44](https://user-images.githubusercontent.com/1405703/59063519-9360f900-88a8-11e9-8f95-fb76a4c5ec42.jpg)

**Comment by vince-fugnitto** [comment]
I get the same issue, I tried removing `plugin-dev` (the source of the `hosted-plugin-service`) from the example-electron application, and it had no effect. Moreover, I removed all plugin packages and it also had no effect so the root cause must be something else.

**Comment by vince-fugnitto** [comment]
@kittaakos 
I tested and it looks like I can only reproduce the bug on macOS. I've tested on Linux (Ubuntu 16.04) and I did not see the fault. I have yet to test on Windows but I just wanted to update you.
