### ISSUE TITLE
[quality] circular dependency in plugin-ext

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5388]
**Description**

There is a circular dependency present in the `plugin-ext` extension between the following files:
- `common/index.ts`
- `plugin/plugin-context.ts`
- `plugin/tree/tree-views.ts`

<div align='center'>

<img width="615" alt="Screen Shot 2019-06-06 at 8 41 17 PM" src="https://user-images.githubusercontent.com/40359487/59074900-d799cc80-889b-11e9-8248-cda4e83f380b.png">

</div>

**Comment by benoitf** [comment]
it could be nice to detect that at on build level (and throw error) so that travis can make the build failed

**Comment by kittaakos** [comment]
> it could be nice to detect that at on build level (and throw error) so that travis can make the build failed

We cannot do that, unfortunately. There are third party dependencies with cyclic modules.

https://github.com/theia-ide/theia/blob/eb61cba1ec8c9320a593b86df6220dfa660edc9a/dev-packages/application-manager/src/generator/webpack-generator.ts#L163

**Comment by akosyakov** [comment]
It does not really break anything, nice to have.

**Comment by benoitf** [comment]
@kittaakos could we just ignore the library that is having cyclic and let `failOnError:true`

**Comment by kittaakos** [comment]
Some background and clarification, maybe it is not valid anymore, but back in 2017 that was the case.

We ignore everything which is under the `node_modules` so in theory third part libs should not cause a problem even if any of their modules have a cycle. But even Node.js has cycles, and it only occurs on Windows. I would say, it is unsafe to fail. But we can try. +1 for trying to reduce the cycles.
