### ISSUE TITLE
Theia should preserve env LD_LIBRARY_PATH when launching child processes

### ISSUE THREAD

**Issue by meysholdt** [theia-ide/theia#5389]
Use Case: I want to package nodejs and glibc together with Theia. This requires me to set `LD_LIBRARY_PATH` to make nodejs use the right `*.so`s. 

This works to launch Theia, but it does not work for the `nsfw-watcher` child processes that Theia launches. 

Fix: The env `LD_LIBRARY_PATH` should be passed to the child processes.

Workaround: launch Theia with arg `--no-cluster` to prevent it from creating child processes.

**Comment by akosyakov** [comment]
I will be fine with passing all `process.env` to the file watcher process: https://github.com/theia-ide/theia/blob/eb61cba1ec8c9320a593b86df6220dfa660edc9a/packages/filesystem/src/node/filesystem-watcher-client.ts#L66-L73

**Comment by meysholdt** [comment]
this snippet lists all node processes and checks if they have env `foo` set. May be helpful for debugging this issue:

```
for id in `pgrep node`; do echo $id; (tr '\0' '\n' < /proc/$id/environ) | grep -i foo; done
```
