### ISSUE TITLE
Generate layout script error

### ISSUE THREAD

**Issue by Beetix** [theia-ide/theia#5390]
### Description
Running the generate layout script from the core package gives an undefined symbol error

### Reproduction Steps
From Theia root directory
* `yarn`
* `cd packages/core`
* `yarn generate-layout`

**OS and Theia version: Arch Linux or Gitpod with Theia master (ab8f4a52)**

**Diagnostics:** 
```
gitpod /workspace/theia/packages/core $ yarn generate-layout
yarn run v1.16.0
$ electron ./scripts/generate-layout
/workspace/theia/node_modules/electron/dist/electron: symbol lookup error: /workspace/theia/node_modules/native-keymap/build/Relea
se/keymapping.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5Lo
calIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
error Command failed with exit code 127.
```

**Comment by akosyakov** [comment]
cc @spoenemann

**Comment by AlexTugarev** [comment]
@Beetix you need to run `yarn run rebuild:electron` after `yarn` first, then it works fine.

**Comment by Beetix** [comment]
Ok thank you, it worked.
