### ISSUE TITLE
[SCM] Change repository icon in status bar not showing up on startup

### ISSUE THREAD

**Issue by qx-juilliard** [theia-ide/theia#5404]
### Reproduction Steps

- open in incognito mode or clear all localStorage data before opening Theia
- the database icon in the status bar corresponding to `SCM: Change repository` command is not showing up (
![image](https://user-images.githubusercontent.com/29387772/59155278-a95eed00-8a53-11e9-9be5-25d3ae7e73c5.png))

- after initial startup, refreshing makes the icon appear, fixing the problem

It seems that the only code responsible for rendering the icon is [here](https://github.com/theia-ide/theia/blob/afc349918c5ff4c9350cf64643c1851a4f9ae63c/packages/scm/src/browser/scm-contribution.ts#L99)

```ts
this.scmService.onDidChangeSelectedRepositories(repository => {
            if (repository) {
                const path = this.labelProvider.getName(new URI(repository.provider.rootUri));
                this.statusBar.setElement(CHANGE_REPOSITORY.id, {
                    text: `$(database) ${path}`,
                    tooltip: path.toString(),
                    command: CHANGE_REPOSITORY.id,
                    alignment: StatusBarAlignment.LEFT,
                    priority: 100
                });
            } else {
                this.statusBarCommands.forEach(id => {
                    this.statusBar.removeElement(id);
                });
            }
        });

```

However, I don't know why it is not fired during startup, perhaps we need something like `fireDidChangeSelectedRepositories` like in [here](https://github.com/theia-ide/theia/blob/afc349918c5ff4c9350cf64643c1851a4f9ae63c/packages/git/src/browser/git-repository-provider.ts#L108) to manually trigger the refresh?

(BTW why is the function name plural while in the corresponding `git-repository-provider.ts` module it's singular?)

**Comment by qx-juilliard** [comment]
Also in addition to having duplicate codes between @theia/git and @theia/scm, there seems to be two commands coexisting at the same time:

![image](https://user-images.githubusercontent.com/29387772/59155260-3d7c8480-8a53-11e9-96c0-8234fa6e99fe.png)

Are we in the process of shifting codes from git to scm extension?

**Comment by akosyakov** [comment]
@qx-juilliard we've already shifted, but it broke existing git support and did not deliver proper vscode git extension support. Working on redoing it, hopefully will release 0.7.2 next week.

**Comment by akosyakov** [comment]
@qx-juilliard you have multiple repos right? For one repo we don't show it.

**Comment by qx-juilliard** [comment]
Yes, that's why reloading the webpage will correctly bring up the icon

**Comment by akosyakov** [comment]
@qx-juilliard though so 😄 just checking
