### ISSUE TITLE
support markdown in notifications

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5415]
One can reproduce by publishing local branch to remove with VS Code git extension:
<img width="1298" alt="Screen Shot 2019-06-11 at 14 09 22" src="https://user-images.githubusercontent.com/3082655/59270756-97976880-8c52-11e9-9b74-cde77c5014d4.png">

**Comment by akosyakov** [comment]
cc @AlexTugarev

**Comment by akosyakov** [comment]
We probably also should replace `Code` with `Theia`? 😄

**Comment by AlexTugarev** [comment]
BTW, it’s apparently limited to links only. I tested with other md features, which are not supported. It seems even new lines are removed intentionally.
