### ISSUE TITLE
[problem view] Re-sizing the problem view puts the label on two lines

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5423]
### Description
When re-sizing the problem view with some "clang-tidy" warnings, the warnings get displayed on two line for the label "clang-tidy", but  the text just get shrink on one line with the "...", Since we use two lines, we should also wrap the text description.
  

### Reproduction Steps

![clang-tidyResize](https://user-images.githubusercontent.com/419051/59300371-08438280-8c5d-11e9-992e-6fb22a13f2b5.gif)

**OS and Theia version:**

**Diagnostics:** 
Theia 0.7.0
Ubuntu 16.04

**Comment by vince-fugnitto** [comment]
I previously noticed this error too with `clang-tidy` markers, it was the only time I was ever able to reproduce the issue.
