### ISSUE TITLE
[settings] add "search settings" to the Preferences widget 

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5438]
It would be helpful to have a "search settings" thing in the Preferences widget, since finding the right one among more than 100 items can be hard.

In VS Code:
![Screenshot from 2019-06-12 15-53-54](https://user-images.githubusercontent.com/25921074/59381949-9a658c80-8d2a-11e9-9bcb-04818d24994e.png)

**Comment by vince-fugnitto** [comment]
@fangnx there should be a major refactoring to align our `preferences` to that of vscode, and along with that a better search feature.

For now, all `tree` widgets in Theia have the ability to be filtered down by simply typing keys when the widget is active. The same is true for the preferences.

<div align='center'>

<img width="652" alt="Screen Shot 2019-06-12 at 4 38 32 PM" src="https://user-images.githubusercontent.com/40359487/59384605-8f155f80-8d30-11e9-9d1b-08b0d4dbaf3f.png">


</div>

**Comment by vince-fugnitto** [comment]
Closing for now until the major refactoring to the `preferences` widget is made.
