### ISSUE TITLE
[keybindings] keybinding update does not take immediate effect

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5439]
Currently, updating keybindings in the Keyboard Shortcuts UI & JSON does not take effect immediately. It requires restarting Theia to make it work.

_Originally posted by @elaihau in https://github.com/theia-ide/theia/pull/5436#issuecomment-501413764_

**Comment by vince-fugnitto** [comment]
Ahh, I'm sad since it used to work well :(

**Comment by akosyakov** [comment]
Oh, it's bad. @vince-fugnitto @fangnx are you looking into it?
