### ISSUE TITLE
Preference editor does not display "dirty" status properly

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#5445]
### Description

Preference editor displays "dirty" status when not changes are made.

### Reproduction Steps
1. go to preference editor
2. make a editor.font change in user preference
3. make one more editor.font change in workspace preference
4. switch from `workspace` tab back to `user` tab in preference editor

what happens: preference editor shows "dirty" status
expected: "dirty" status should not show up, as no changes are made

![Peek 2019-06-13 08-15](https://user-images.githubusercontent.com/37082801/59431684-739f6880-8db3-11e9-8389-cc93db657b04.gif)

**OS and Theia version:**

Gitpod. Chrome browser. Master branch as of June 13 2019 https://github.com/theia-ide/theia/tree/741876b3ecba8a968ecf1200eb231639eb3b4074

**Comment by elaihau** [comment]
Also, switching tabs back and forth in the preference editor messes up the "dirty" status:

![Peek 2019-06-13 08-49](https://user-images.githubusercontent.com/37082801/59433865-5e790880-8db8-11e9-9ad7-013ab104d5e0.gif)

I believe it is closely related to the first bug reported in this theia issue.

**Comment by elaihau** [comment]
I am no longer able to reproduce this problem on the master branch. Could you please double check and confirm? @lmcbout

**Comment by vince-fugnitto** [comment]
> I am no longer able to reproduce this problem on the master branch. Could you please double check and confirm? @lmcbout

I can no longer see the issue as of 150c15874ca14217061caa183349ff505410b015, we can open the issue again if it returns.
