### ISSUE TITLE
Not all changes to workspace preference take effect

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#5446]
### Description

Changes to **some** preferences don't take effect. 

### Reproduction Steps

1. open preference editor
2. update `git.decorations.colors` in the "User" tab of pref editor. At this point, changes take effect. Everything looks normal.
3. switch to the "Workspace" tab of pref editor. Update `git.decorations.colors`.

what happens: Changes in the "Workspace" tab don't take effect
expected: changes in the "Workspace" tab should take effect, as Workspace preferences should override those in User preference.

![Peek 2019-06-13 08-26](https://user-images.githubusercontent.com/37082801/59433177-f83fb600-8db6-11e9-8f4d-1dce638a64b5.gif)

**OS and Theia version:**

Gitpod. Chrome browser. This problem can also be reproduced in the example browser running in Chrome, Ubuntu 16.04.

Theia version: master branch as of June 13 2019 https://github.com/theia-ide/theia/tree/741876b3ecba8a968ecf1200eb231639eb3b4074

**Diagnostics:** 

1. Changes made to `editor.font` in "Workspace" tab worked properly.

2. Changes made to `git.decorations.colors` in the "Workspace" tab fires [resource.onDidChangeContents](https://github.com/theia-ide/theia/blob/741876b3ecba8a968ecf1200eb231639eb3b4074/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L55), and there are no logical issues in [the preference change handler](https://github.com/theia-ide/theia/blob/741876b3ecba8a968ecf1200eb231639eb3b4074/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L188) either. Error occurred in [this line](https://github.com/theia-ide/theia/blob/741876b3ecba8a968ecf1200eb231639eb3b4074/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L201), where `this.getScope()` returns 3 on the change made to the "Workspace" tab and schemaValidator considered it invalid.

**Comment by elaihau** [comment]
Could it be related to the refactoring made to preferences? @akosyakov

**Comment by akosyakov** [comment]
@elaihau yes, it can be, one has to debug though to see the root cause.
