### ISSUE TITLE
[0.7.2] Upcoming bugfix release

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#5448]
### Description

A `0.7.2` bugfix release was [requested](https://spectrum.chat/theia/general/0-7-2-bug-fix-release~9fd413e2-d4d6-437f-9351-a51a6aa61c52).

**Comment by marcdumais-work** [comment]
[0.7.2](https://github.com/theia-ide/theia/tree/0.7.2) branch pushed

Anyone want to help validate this?

**Comment by akosyakov** [comment]
@marcdumais commits for Akosh should be also the part: https://github.com/theia-ide/theia/commit/db8c80783655a25629aace1e5d5dd5f544f086d3 and and https://github.com/theia-ide/theia/commit/69c9d5106e609a3538a9463924cd03c1a32f2a03

I can do some shallow testing

**Comment by marcdumais-work** [comment]
Thanks @akosyakov . I have added the 2 commits from Akos above and pushed the latest version of the branch. Building locally now - you can test as well.

**Comment by akosyakov** [comment]
thanks @marcdumais-work we found one more issue: https://github.com/theia-ide/theia/issues/5449 looking into it

**Comment by lmcbout** [comment]
I tried this v0.7.2 and did not find any new issues not reported, seems to work fine on ubuntu

**Comment by akosyakov** [comment]
We've found one more git issue: https://github.com/theia-ide/theia/issues/5455 :(

**Comment by marcdumais-work** [comment]
> We've found one more git issue: #5455 :(

@akosyakov has a PR for this issue under review: https://github.com/theia-ide/theia/pull/5456 . So I'll wait for this before proceeding with `0.7.2`

**Comment by akosyakov** [comment]
after more testing i believe #5455 always was the case , but it will be good to cherry-pick https://github.com/theia-ide/theia/commit/8b52995a53eeb74a73a4b3aae5c79f4f7f2f1660 and after that it should be good

i won't be around today, can test only on Monday, please pick someone else for testing if you think it is required.

**Comment by marcdumais-work** [comment]
> it will be good to cherry-pick 8b52995 

Added. I pushed the updated `0.7.2` branch. 

@vinokurig would you and/or colleagues who worked on the `scm` extension be able to help test this, before we release?

**Comment by vinokurig** [comment]
As for now I've found a new issue: https://github.com/theia-ide/theia/issues/5476. Testing more.

**Comment by vinokurig** [comment]
Other works well for me.

**Comment by marcdumais-work** [comment]
Thanks @vinokurig . I plan to go ahead with `0.7.2` release later today, afternoon time here in Montreal.

**Comment by marcdumais-work** [comment]
done - 0.7.2 published: https://github.com/theia-ide/theia/releases/tag/v0.7.2
