### ISSUE TITLE
Cannot stage merged changes

### ISSUE THREAD

**Issue by 32leaves** [theia-ide/theia#5455]
### Description
During a rebase I had to merge changes. I cannot stage those changes using the SCM view (clicking the `+` button has no effect).

### Reproduction Steps
1. Rebase a branch so that changes need to be merged manually
2. Merge those changes
3. Try to stage those changes

**OS and Theia version:**
tested in gitpod.io

**Diagnostics:** 
there is no error on the console

**Comment by akosyakov** [comment]
In order to reproduce merge conflict: https://stackoverflow.com/questions/43702944/reproducing-git-merge-conflict-dd
