### ISSUE TITLE
Empty 'CHANGES' resource group is present in the SCM

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#5476]
### Description
 
Empty 'changes' resource group is present in the SCM
### Reproduction Steps

* Open a workspace with a git project
* Go to SCM 
Wong: an empty `CHANGES` resource group is shown: 
![screenshot-localhost-3000-2019 06 14-16-36-28](https://user-images.githubusercontent.com/7668752/59513020-9a989000-8ec2-11e9-85c2-b96a8cc3fe57.png)
Even if there are stage changes, an empty `CHANGES` resource group is shown as well:
![screenshot-localhost-3000-2019 06 14-16-37-38](https://user-images.githubusercontent.com/7668752/59513140-f19e6500-8ec2-11e9-99bc-4381f2e24120.png)

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
I have noticed this yesterday as well, created an issue and have changed my mind. It is the same in VS Code (Version 1.35.1 (1.35.1))

![Screen Shot 2019-06-14 at 15 41 06](https://user-images.githubusercontent.com/1405703/59513380-08d95480-8ebb-11e9-9fcd-244ccb64a8dd.jpg)
![Screen Shot 2019-06-14 at 15 41 31](https://user-images.githubusercontent.com/1405703/59513381-0971eb00-8ebb-11e9-8c69-975118c4fde0.jpg)

Although it is a tiny bit counterintuitive, I think it is not a bug.

**Comment by vinokurig** [comment]
Ok closing
