### ISSUE TITLE
Communication between frontend-backend via jsonrpc failed with error: "Request 'xxx' failed"

### ISSUE THREAD

**Issue by JustinBobby007** [theia-ide/theia#5496]
Theia version : 0.7.1

- Service interface definition: 
```
export const XXXService = Symbol('XXXService');
export interface XXXService {
  xxx(text: string): Promise<{filePath: string, content: string}>;
}
```

- Backend modules: 
```
bind(XXXService).to(XXXServiceImpl).inSingletonScope();
bind(ConnectionHandler).toDynamicValue(context => 
    new JsonRpcConnectionHandler("services/xxx", () => {
    context.container.get(XXXService);
    })
).inSingletonScope();  
```

- In frontend, bind and inject XXXService:
```
bind(XXXService).toDynamicValue(context => 
    WebSocketConnectionProvider.createProxy<XXXService>(context.container, "services/xxx")
).inSingletonScope();
```

- then invoke method xxx
```
let resultPromise = this.XXXService.xxx("hello");
resultPromise.then(obj => {
      console.log(obj);
}).catch(err => {
      console.log("error: " + err + ", " + err.stack);
});
```

- but throw exception as follows: 
  root INFO erroror: Error: Unhandled method xxx, Error: Request 'xxx' failed
    at Proxy.<anonymous> (http://127.0.0.1:3000/bundle.js:48252:33)
    at XXXContribution.push.../theia-vue-extension/lib/browser/xxx/xxx-contribution.js.XXXContribution.onStart (http://127.0.0.1:3000/27.bundle.js:992:30)
    at http://127.0.0.1:3000/bundle.js:27259:155
    at FrontendApplication.<anonymous> (http://127.0.0.1:3000/bundle.js:27338:46)
    at step (http://127.0.0.1:3000/bundle.js:26866:23)
    at Object.next (http://127.0.0.1:3000/bundle.js:26847:53)
    at http://127.0.0.1:3000/bundle.js:26841:71
    at new Promise (<anonymous>)
    at ../node_modules/@theia/core/lib/browser/frontend-application.js.__awaiter (http://127.0.0.1:3000/bundle.js:26837:12)
    at FrontendApplication.../node_modules/@theia/core/lib/browser/frontend-application.js.FrontendApplication.measure (http://127.0.0.1:3000/bundle.js:27330:16)

**Comment by akosyakov** [comment]
and `XXXServiceImpl` has `xxx` method?

**Comment by JustinBobby007** [comment]
> and `XXXServiceImpl` has `xxx` method?

@akosyakov  Yes, like the following
```
@injectable()
export class XXXServiceImpl implements BackendApplicationContribution, XXXService {
  async onStart(): Promise<void> {

  }

  xxx(text: string): Promise<{filePath: string, content: string}> {
    let result = {
      filePath: "/dist",
      content: "<tmeplate></tmeplate>"
    }
    return Promise.resolve(result);
  }
}
```

**Comment by akosyakov** [comment]
@JustinBobby007 Do you have an example somewhere? From code snippets it looks alright, maybe some details in the actual implementation.

**Comment by JustinBobby007** [comment]
@akosyakov Thanks for your time, and it's my mistake!
After several hours for comparing these codes with other examples which run without exception. Finally I found the difference in the ConnectionHandler bind:
Original code:
```
bind(ConnectionHandler).toDynamicValue(context => 
    new JsonRpcConnectionHandler("services/xxx", () => {
    context.container.get(XXXService);
    })
).inSingletonScope(); 
```
The second parameter 'targetFactory' in JsonRpcConnectionHandler should be defined like:
`() => context.container.get(HuaweiUxService)`

instead of
```
() => {
    context.container.get(XXXService);
    }
```

After modifying the parameter, the exception disappears and the backend interface can be invoked normally.

**Comment by akosyakov** [comment]
@JustinBobby007 glad you figured it out
