### ISSUE TITLE
[monaco] missing "toggle minimap" command

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5500]
We should add the "Toggle Minimap" command to the top bar menu and the quick-open.

**Comment by vince-fugnitto** [comment]
The way it works in VSCode is to have a command which updates the `editor.minimap.enabled` preference value at the `User` level. This should be quite easy to do.

https://github.com/microsoft/vscode/blob/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/src/vs/workbench/contrib/codeEditor/browser/toggleMinimap.ts#L26-L29
