### ISSUE TITLE
[keybindings] "edit" and "reset" icons not displayed properly

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5502]
Currently, the "edit" and "reset" icons would be replaced by `...` when the widget is resized, despite there is still enough space to display them properly. It should be fixed.

![theia-keybindings-3dots](https://user-images.githubusercontent.com/25921074/59630432-4b956980-9113-11e9-9a99-eb4ef4d79f9c.gif)

**Comment by fangnx** [comment]
I will have it fixed together with #5402.

**Comment by vince-fugnitto** [comment]
Closed in #5526
