### ISSUE TITLE
[terminal] 'terminal is not started'

### ISSUE THREAD

**Issue by BroKun** [theia-ide/theia#5506]
### Description
When I open the terminal, the console will report this error.

### Reproduction Steps
In my case, I started theia from the image, and there is no problem with the image running locally, but when I run it remotely, I get an error, which I think may be related to slower network interaction.

**Diagnostics:** 
```console
38.bundle.js:461 Uncaught (in promise) Error: terminal is not started
    at TerminalWidgetImpl.get [as processId] (38.bundle.js:461)
    at updateProcessId (90.bundle.js:10063)
    at TerminalServiceMainImpl.<anonymous> (90.bundle.js:10064)
```
After the terminal is created by the WidgetManager, the trackTerminal method of the TerminalServiceMain in the plugin-ext is triggered, but the processId of the current TerminalWidgetImpl does not guarantee that the start method call is completed when used, so the correct processId cannot be obtained.

**Comment by akosyakov** [comment]
@BroKun can you have a look?

**Comment by BroKun** [comment]
Yes , it is my pleasure to help.

**Comment by BroKun** [comment]
> @BroKun can you have a look?

Yes , it is my pleasure to help.
