### ISSUE TITLE
Make sure that node 8 is used

### ISSUE THREAD

**Issue by cdietrich** [theia-ide/theia#553]
if i try to build theia with node 6 the build will fail.
maybe we should specify a minimum node version somehow (e.g. via engine tag in package.json)

**Comment by hetenho** [comment]
I can add that and test that it works if this is still open :)

**Comment by akosyakov** [comment]
@hetenho sure, PRs are welcomed

**Comment by akosyakov** [comment]
PRs are welcomed. You need to add:
```json
  "engines": {
    "yarn": "1.0.x || >=1.2.1",
    "node": ">=7.9.0"
  }
```
before:
https://github.com/theia-ide/theia/blob/1a5800d814869b487082406a690f44e5e3aceaea/package.json#L5

@hetenho feel free to open the PR if you still want to.
