### ISSUE TITLE
[tasks] run clang-tidy as a task and generate problem markers

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5532]
**Description**

It would be nice to run `clang-tidy` as a task and generate problem markers to be visible in the `problems-view` and `editor`.

We need this to be merged first: [create problem markers from task output #5024s](https://github.com/theia-ide/theia/pull/5024)

**Comment by vince-fugnitto** [comment]
Do you mean running clang-tidy as a `task`?
We already support having `clang-tidy` as a preference and it creates problem markers.
