### ISSUE TITLE
[ui] octicons do not have the correct size in the statusbar

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5534]
**Description**

`octicon` icons present in the statusbar do not have the appropriate size as compared to other statusbar icons, it looks like the `octicons` are too large.

The `octicon` present in the screenshot is the last, the **tools** one.

<div align='left'>

<img width="445" alt="Screen Shot 2019-06-19 at 3 54 10 PM" src="https://user-images.githubusercontent.com/40359487/59795978-8251b800-92aa-11e9-98c8-51075ee7400d.png">

</div>

**Comment by magopian** [comment]
When is that icon displayed? Trying to reproduce locally ;)

**Comment by vince-fugnitto** [comment]
You can update any current icon from the statusbar to a `octicon` to test the bug.
For example, you can update the following `wrench` to [`tools`](https://octicons.github.com/icon/tools/), and test it by simply opening a `c++` file which will create the statusbar item.

https://github.com/theia-ide/theia/blob/711e3ce41f68a2a41423dcb50e537688578f9491/packages/cpp/src/browser/cpp-build-configurations-statusbar-element.ts#L50

This is the outcome:

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/59856364-c0031f00-9344-11e9-932e-29af370ec841.png)


</div>

**Comment by magopian** [comment]
Well, i've investigated a bit, and it seems the fontawesome icons are rendered as 12 pixels high, while the octicons are rendered as 16 pixels high.

However, I've checked the left [publish changes icon](https://octicons.github.com/icon/cloud-upload/) and it's by chance only 12 pixels high (the full sprite is 16 pixels, but there's two empty pixels at the top and the bottom, as you can see if you display the grid version).

This is not the case for the [octicons tools icon](https://octicons.github.com/icon/tools/) which takes the full 16 pixels of the sprite.

So if we decide to shrink the octicons to 12 pixels, the "publish changes" icon will appear very small, as you can see on the following screenshot:

<img width="177" alt="Capture d’écran 2019-06-20 à 16 48 00" src="https://user-images.githubusercontent.com/167767/59858402-33278800-937b-11e9-908a-84a67455614b.png">

I'm not sure what the correct approach would be here, but I think there's a few solutions:
- choose icons that look the same size: the current "cloud-upload" is exceptionnally small and the "tools" is exceptionnally large
- find a better set of icons
- add a parameter to specify how large the icon should be rendered (eg: shrink the tools one specifically)

This last solution seems like a hack and workaround at best, so I would advise against it, but maybe there's a strong will to keep using those exact same icons, and in that case it'll be hard to find a better solution ;)

**Comment by vince-fugnitto** [comment]
@magopian thank you for looking into it.

> choose icons that look the same size: the current "cloud-upload" is exceptionnally small and the "tools" is exceptionnally large

Theia is a framework and it's up to the developer to decide / override the icons for his application, but I assume when you state that we should choose icons that are similar in size I assume you mean within Theia.

> find a better set of icons

VSCode uses `octicons` in the statusbar and we'd like to support them as well.

In general, I assume we should check what vscode does to render `octicons` nicely https://github.com/microsoft/vscode/issues/74285

**Comment by magopian** [comment]
@vince-fugnitto I agree with all of the above, and I understand that supporting `octicons` is the way
the project is going.

That being said, this very issue is, I believe, aggravated by the two specific icons we're talking about (the [tools](https://octicons.github.com/icon/tools/) and [cloud-upload](https://octicons.github.com/icon/cloud-upload/) ones) that are very different in size.

I guess the best we could do for this issue is to display the `octicons` as 12px height (or actually 12.5px), and cope with the fact that the [cloud-upload](https://octicons.github.com/icon/cloud-upload/) one looks very small (because it is smaller than the average `octicon` out there).

I can give it a try, and see what the result is

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I agree with all of the above, and I understand that supporting `octicons` is the way
> the project is going.
> 
> That being said, this very issue is, I believe, aggravated by the two specific icons we're talking about (the [tools](https://octicons.github.com/icon/tools/) and [cloud-upload](https://octicons.github.com/icon/cloud-upload/) ones) that are very different in size.
> 
> I guess the best we could do for this issue is to display the `octicons` as 12px height (or actually 12.5px), and cope with the fact that the [cloud-upload](https://octicons.github.com/icon/cloud-upload/) one looks very small (because it is smaller than the average `octicon` out there).
> 
> I can give it a try, and see what the result is

Thank you for looking into it, I'm excited to see what you come up with!
