### ISSUE TITLE
How to report security issues

### ISSUE THREAD

**Issue by genady-p** [theia-ide/theia#5537]
I have found 2 security issues: XSS and Path traversal with Theia plugins.
How the issues should be reported without being exposed to everyone else?

**Comment by vince-fugnitto** [comment]
@genady-p it's alright to open an issue about any security flaw or vulnerability you may have discovered, it has been done previously in the past https://github.com/theia-ide/theia/issues/4440, and PRs are always most certainly welcome. Would you like to share how you discovered the issue?

**Comment by genady-p** [comment]
My concern is that since I share exact request payload, the 0-day might be used by someone else to attack existing theia environments.

**Comment by vince-fugnitto** [comment]
@genady-p I understand your concerns, ideally we'd set up the `security` tab in github to discuss security flaws but if you'd like email is fine (you can email me directly) :)

I verified the XSS vulnerability and it comes from `typedoc` which pulls `jquery` with the flaw but this is a `devDependency` so no need to worry.

**Comment by vince-fugnitto** [comment]
I'll close the issue for now, after performing an audit the issues are all present from `devDependencies`.
Offline discussions will be made in the meantime to fix any issues.
