### ISSUE TITLE
[ui]the cursor of tabBar  should not be pointer

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5538]
### Description
when I move mouse cursor on the tabBar but not on a icon in the bar , the cursor is still 'pointer', but it can not click.
I think it should be default instead
![image](https://user-images.githubusercontent.com/35068357/59847953-89ee8b00-9396-11e9-8d61-c4d7c5e6fb0c.png)

**Comment by magopian** [comment]
Oops sorry I meant to ping here before working on the PR and totally forgot... anyway, i've created a PR with a one-line change that seems to do the trick ;)
