### ISSUE TITLE
[keybindings] align keybindings-widget with vscode

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5544]
**Description**

The `keybindings-widget` should be more aligned with vscode:
1. remove the `command` column which displays a keybinding's `id`.
2. rename `scope` to `source`.
3. display the `id` for commands without a `label`.
4. reorder the columns (actions, command, keybinding, source)
5. prioritize the display of commands with `keybindings` above those without.

**Comment by lmcbout** [comment]
If I compare with old values, there are some some command missing: i.e. "Unstage all" + other commands.
Second, what about the commands which don't have a name, they used to show. Another thing, those un-label command show in vscode , so we just lost them now in Theia !!!
It looks like we only see the command having a keybinding defined for them
