### ISSUE TITLE
Please improve your build system! Maybe switch from yarn?

### ISSUE THREAD

**Issue by abalter** [theia-ide/theia#5565]
I can reproducibly create a clean Ubuntu install, install nodejs, npm, and yarn, and then have the simple build process [here](https://www.theia-ide.org/doc/composing_applications) fail with gyp errors.

I know there are more experienced programmers out there who obviously get things to work. But I'm also pretty sure I'm not the only person who runs into these problems and wants to give up.

The whole gyp error thing in Node is a huge problem, especially with gyp stuck on Python 2. There isn't anything you can do about that.

But I would really appreciate if the folks who have the know-how and authority to test their build system more extensively so that us mortal programmers can actually use Theia.

This is what I mean:

1. Install Ubuntu
1. Install nodejs, npm, yarn.
1. `sudo apt-get install libx11-dev libxkbfile-dev`
1. `mkdir ~/theia`
1. `cd ~/theia`
1. `vi package.json` and paste in the code below which I got from [here](https://www.theia-ide.org/doc/Composing_Applications.html)
1. `yarn
1. Get no errors
1. `yarn theia build`
1. Get no errors
1. `yarn theia start`

If you can get that to work consistently, then I'm happy to crawl back into my hole of ignorance.

__package.json__
```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

Note: 
```
(base) balter@spectre:~/theia$ lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
(base) balter@spectre:~/theia$ node --version
v8.11.4
(base) balter@spectre:~/theia$ npm --version
5.8.0
(base) balter@spectre:~/theia$ yarn --version
1.16.0
```

**Comment by abalter** [comment]
NOTE: I installed node, npm, and yarn with `sudo apt install ....`

**Comment by abalter** [comment]
NOTE 2: I created a Conda environment: `conda create -n node nodejs -y` and then did `npm install -g yarn`. I was able to successfully run the build.

**Comment by marechal-p** [comment]
Please avoid duplicates: https://github.com/theia-ide/theia/issues/5564
