### ISSUE TITLE
yarn  error? how should i do?

### ISSUE THREAD

**Issue by xinsuinizhuan** [theia-ide/theia#5574]
error D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | win32 | x64
gyp info spawn E:\Program Files\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\native-keymap\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\lllstandout\\.node-gyp\\12.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\lllstandout\\.node-gyp\\12.4.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\lllstandout\\.node-gyp\\12.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\native-keymap\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  string_conversion.cc
  keymapping.cc
  keyboard_win.cc
  win_delay_load_hook.cc
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(285): warning C4996: 'v8::String::NewFromUtf8': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(2890): note: �μ���v8::String::NewFromUtf8��������d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(286): warning C4996: 'v8::String::NewFromUtf8': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(2890): note: �μ���v8::String::NewFromUtf8��������d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(287): warning C4996: 'v8::String::NewFromUtf8': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(2890): note: �μ���v8::String::NewFromUtf8��������d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(288): warning C4996: 'v8::String::NewFromUtf8': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(2890): note: �μ���v8::String::NewFromUtf8��������d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(289): warning C4996: 'v8::String::NewFromUtf8': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(2890): note: �μ���v8::String::NewFromUtf8��������d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(308): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(311): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(314): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(317): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(320): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(322): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(364): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(365): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(366): warning C4996: 'v8::Object::Set': ������Ϊ�ѷ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(3358): note: �μ���v8::Object::Set��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(475): error C2660: ��v8::Function::Call��: ���������� 3 ������ [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8.h(4148): note: �μ���v8::Function::Call�������� (����Դ�ļ� ..\src\keyboard_win.cc)
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): error C2039: ��Handle��: ���ǡ�v8���ĳ�Ա [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\lllstandout\.node-gyp\12.4.0\include\node\v8-platform.h(16): note: �μ���v8��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): error C2065: ��Handle��: δ�����ı�ʶ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): error C2275: ��v8::Function��: ����������������ʽ�Ƿ� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
  d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): note: �μ���v8::Function��������
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): error C2065: ��arg0��: δ�����ı�ʶ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): error C2039: ��Cast��: ���ǡ�`global namespace'���ĳ�Ա [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(483): error C3861: ��Cast��: �Ҳ�����ʶ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
d:\eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\src\keyboard_win.cc(484): error C2065: ��arg0��: δ�����ı�ʶ�� [D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap\build\keymapping.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "D:\\Eclipse\\eclipse_theia\\src_run\\theia-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Eclipse\eclipse_theia\src_run\theia-master\node_modules\native-keymap

**Comment by kittaakos** [comment]
We do not yet support Node.js 12. See: https://github.com/theia-ide/theia/issues/5117

Please use a compatible Node.js version. For instance; `v10.15.3`. See: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites

Please close the task if it works with 10. Thank you!

**Comment by vince-fugnitto** [comment]
@xinsuinizhuan any update on if it currently works?

**Comment by xinsuinizhuan** [comment]
thank you! It works normal! I change the nodejs version,then it works normal!

**Comment by vince-fugnitto** [comment]
> thank you! It works normal! I change the nodejs version,then it works normal!

Great ! I'll close the issue for you then 😊
