### ISSUE TITLE
yarn run  with C++,but some error? how should i do?

### ISSUE THREAD

**Issue by xinsuinizhuan** [theia-ide/theia#5582]
root ERROR C/C++: I[13:39:47.405] <-- initialize(0)
I[13:39:47.407] --> reply:initialize(0) 1 ms

root ERROR C/C++: I[13:39:47.423] <-- initialized
I[13:39:47.423] unhandled notification initialized

root ERROR C/C++: I[13:39:47.426] <-- workspace/didChangeConfiguration

root ERROR C/C++: I[13:39:47.431] <-- textDocument/didOpen

root ERROR C/C++: I[13:39:47.431] Failed to find compilation database for e:\test\maxfunction\max_num.c

root ERROR C/C++: I[13:39:47.433] Updating file e:\test\maxfunction\max_num.c with command [e:\test\maxfunction] E:\Program Files\LLVM\bin\clang e:\test\maxfunction\max_num.c

root ERROR C/C++: I[13:39:47.458] <-- textDocument/codeAction(1)

root ERROR C/C++: I[13:39:47.458] --> reply:textDocument/codeAction(1) 0 ms

root ERROR C/C++: I[13:39:47.469] <-- textDocument/codeAction(2)
I[13:39:47.469] --> reply:textDocument/codeAction(2) 0 ms

root ERROR C/C++: I[13:39:47.505] Dropped diagnostic outside main file: : expected identifier or '('
I[13:39:47.505] Dropped diagnostic outside main file: : expected ')'
I[13:39:47.505] Dropped diagnostic outside main file: : expected ')'

root ERROR C/C++: I[13:39:47.537] Dropped diagnostic outside main file: : expected ')'

root ERROR C/C++: I[13:39:47.543] --> textDocument/publishDiagnostics

root ERROR C/C++: I[13:39:47.658] <-- textDocument/codeAction(3)

root ERROR C/C++: I[13:39:47.658] --> reply:textDocument/codeAction(3) 0 ms

root ERROR C/C++: I[13:39:47.661] <-- textDocument/codeAction(4)
I[13:39:47.661] --> reply:textDocument/codeAction(4) 0 ms

root ERROR C/C++: I[13:39:47.661] <-- textDocument/codeAction(5)
I[13:39:47.661] --> reply:textDocument/codeAction(5) 0 ms

root ERROR C/C++: I[13:39:47.663] <-- textDocument/codeAction(6)

root ERROR C/C++: I[13:39:47.663] --> reply:textDocument/codeAction(6) 0 ms

**Comment by vince-fugnitto** [comment]
I'll close this issue in favor for #5583
