### ISSUE TITLE
Cant able to build the docker container with my custom extension

### ISSUE THREAD

**Issue by dhananjayharel** [theia-ide/theia#5598]
### Description

I Cant able to build the docker container with my custom extension when I use 
theia@next versions in my latest.package.json

I have created some custom extensions and I a was able to use it in the theia editor having latest version.
For using @theia/php extension I had to build the theia editor with "next" packages as a dependency.
When I include my extensions which are already present in npm repo
then during the last step of build the process , the theia build command gets killed automatically and docker build fails.
When I remove my included extensions from latest.package.json then docker builds successfully.

Here is latest.package.json file

```json
{
    "private": true,
    "dependencies": {
        "typescript": "latest",
        "@theia/core": "next",
        "@theia/editor": "next",
        "@theia/editorconfig": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/git": "next",
        "@theia/json": "next",
        "@theia/keymaps": "next",
        "@theia/languages": "next",
        "@theia/markers": "next",
        "@theia/merge-conflicts": "next",
        "@theia/messages": "next",
        "@theia/mini-browser": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/outline-view": "next",
        "@theia/php": "next",
        "@theia/output": "next",
        "@theia/preferences": "next",
        "@theia/process": "next",
        "@theia/search-in-workspace": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/textmate-grammars": "next",
        "@theia/tslint": "next",
        "@theia/typescript": "next",
        "@theia/userstorage": "next",
        "@theia/workspace": "next",
        **"myextension":"0.0.0",
         "mycustomext":"0.0.2",**
    },
    "devDependencies": {
        "@theia/cli": "next"
    }
}
```

from the above file when I remove     
         "myextension":"0.0.0",
         "mycustomext":"0.0.2"
and build the docker again , then it works.

Do I need to create a compatible extensions again which should work with the "next" versions of the theia?

If I use "latest" version instead of "next" then php extension could not build and the 
theia build command again breaks causing the docker build fail.

**Comment by vince-fugnitto** [comment]
@dhananjayharel do you have the error logs for why your build fails with your custom extensions?

**Comment by akosyakov** [comment]
Could you prove a github repo to reproduce?

**Comment by dhananjayharel** [comment]
Actually I was able to build theia editor in docker build process.
The issue was my extensions were created with "@theia/core:latest"  version.
and I was building the theia with "next" versions in dockerbuild process.
I have created the extension with "@theia/core": "next" version and everything is working fine.

thanks!

**Comment by akosyakov** [comment]
@dhananjayharel thanks for getting back
