### ISSUE TITLE
Classpath is incomplete. Only syntax errors will be reported

### ISSUE THREAD

**Issue by yunliang-ding** [theia-ide/theia#5606]
After I install @theia/java, when I open the .java file Classpath is incomplete. Only syntax errors will be reported

**Comment by vince-fugnitto** [comment]
This is a fairly good explanation of what's occurring, I assume you did the same and opened a single `.java` file in your workspace.

https://github.com/redhat-developer/vscode-java/issues/107#issuecomment-263294221

**Comment by yunliang-ding** [comment]
> This is a fairly good explanation of what's occurring, I assume you did the same and opened a single `.java` file in your workspace.
> 
> [redhat-developer/vscode-java#107 (comment)](https://github.com/redhat-developer/vscode-java/issues/107#issuecomment-263294221)

Thank you very much for your answer. I'm trying to modify it

**Comment by vince-fugnitto** [comment]
No problem! Please let me know if the issue can be closed :)

**Comment by Sushmita-kan** [comment]
You will have to set up the classpath.
So, try this --> https://www.geeksforgeeks.org/how-to-set-classpath-in-java/
This has helped me with the same warning.

Let me know if this works for you.
