### ISSUE TITLE
'vscode.window.createInputBox()' is missing in Theia  

### ISSUE THREAD

**Issue by ShimonBenYair** [theia-ide/theia#5615]
currently the only option to use Input Box in Theia is by 'vscode.window.showInputBox()'.
But in my code i need also the input box events which are only available to use via the 'createInputBox' API and not in 'showInputBox' API.
We will appreciate to know if this feature is planned to be released and when.

**Comment by tetchel** [comment]
plus one. https://github.com/theia-ide/theia/issues/5501#issuecomment-502773205

**Comment by akosyakov** [comment]
@tetchel @ShimonBenYair Could you test whether it was addressed with this PR https://github.com/theia-ide/theia/pull/5187? please comment there

**Comment by tetchel** [comment]
The function is certainly there; it looks like you have done a good job summarizing the features that are still missing so I'll wait for those to be resolved :)

**Comment by akosyakov** [comment]
@tetchel #5187 was merged, could you check whether this issue was resolved please?

**Comment by tetchel** [comment]
Seems to be fixed, I noticed https://github.com/theia-ide/theia/issues/5882 while verifying.

**Comment by akosyakov** [comment]
@tetchel thanks for checking, closing
