### ISSUE TITLE
[scm] the order of icon in scm is different in Chrom and Firefox

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5620]
### Description
 the order of command icon in scm is different in Chrom and Firefox
![git action icon diff in firefox chrome](https://user-images.githubusercontent.com/35068357/60495518-87b7f500-9ce3-11e9-850b-7730ec0ba3dc.PNG)

### Reproduction Steps
* open instance in chrome and firefox
* open scm 

**OS and Theia version:**
* OS: ubuntu18
* chrome: 75.0.3770.100
* firefox: 60.7.2esr 
* theia :latest
**Diagnostics:**

**Comment by akosyakov** [comment]
@kpge Will you have chance to investigate the cause? PRs are welcomed if they don't involve big structural changes.

**Comment by vince-fugnitto** [comment]
It doesn't look like a problem for the `scm` widget but generally to all toolbar items.
It looks like chrome and firefox differ from the `priority` and will be reverses of each other.

For example, in the `search-in-workspace` widget:

**Firefox**
![image](https://user-images.githubusercontent.com/40359487/60508374-5c5be880-9c98-11e9-8fad-1dbfb82f0964.png)

**Chrome**
![image](https://user-images.githubusercontent.com/40359487/60508438-844b4c00-9c98-11e9-8c24-2e4bf3df7b8c.png)

**Comment by kpge** [comment]
I think the problem is here :
![image](https://user-images.githubusercontent.com/35068357/60513199-29057200-9d09-11e9-9809-a9b2a91743cb.png)
### chrome get the item before `items` is sorted, but Firefox get the item after they are sorted
* Chrome:
![image](https://user-images.githubusercontent.com/35068357/60513155-0f642a80-9d09-11e9-9e9f-c76d59381ed0.png)
* Firefox: 
![image](https://user-images.githubusercontent.com/35068357/60513291-784ba280-9d09-11e9-975d-99c5bb7f738c.png)

**Comment by kittaakos** [comment]
Isn’t the comparator function the strange? Assuming I have `left` and `right` with the following items:
```
"{"id":"search-in-workspace.refresh","command":"search-in-workspace.refresh","tooltip":"Refresh","priority":0}"
```
```
"{"id":"search-in-workspace.clear-all","command":"search-in-workspace.clear-all","tooltip":"Clear Search Results","priority":1}"
```
When I compare them, them following branch will return with `1`:
```
        if (left.group === undefined || left.group === 'navigation') {
            return 1;
        }
```
Meaning that `left` is greater than `right`, hence it should come after `right`, but the `priority` is the other way and ignored.

**Comment by kittaakos** [comment]
Also, I have managed to "break it" on Chrome:
![Screen Shot 2019-07-02 at 15 11 25](https://user-images.githubusercontent.com/1405703/60515386-cf3a8300-9cdb-11e9-9b28-9c66a9792529.jpg)

**Comment by akosyakov** [comment]
Could someone look at the comparator? It seems to be relatively easy fix. The logic should be following:
- items should be compare by groups first
- navigator group is special and always have the higher priority
- undefined group is navigator group as well
- if items have the same group then priority should be used for comparison within the group

It seems that the last point is not true for items within the navigator group.

**Comment by kittaakos** [comment]
```diff
diff --git a/packages/core/src/browser/shell/tab-bar-toolbar.tsx b/packages/core/src/browser/shell/tab-bar-toolbar.tsx
index 8978286cc..a6caeaccd 100644
--- a/packages/core/src/browser/shell/tab-bar-toolbar.tsx
+++ b/packages/core/src/browser/shell/tab-bar-toolbar.tsx
@@ -292,26 +292,18 @@ export namespace TabBarToolbarItem {
      */
     export const PRIORITY_COMPARATOR = (left: TabBarToolbarItem, right: TabBarToolbarItem) => {
         // The navigation group is special as it will always be sorted to the top/beginning of a menu.
-        if (left.group === undefined || left.group === 'navigation') {
-            return 1;
-        }
-        if (right.group === undefined || right.group === 'navigation') {
-            return -1;
-        }
-        if (left.group && right.group) {
-            if (left.group < right.group) {
-                return -1;
-            } else if (left.group > right.group) {
-                return 1;
-            } else {
-                return 0;
+        const compareGroup = (leftGroup: string | undefined = 'navigation', rightGroup: string | undefined = 'navigation') => {
+            if (leftGroup === 'navigation') {
+                return rightGroup === 'navigation' ? 0 : -1;
             }
-        }
-        if (left.group) {
-            return -1;
-        }
-        if (right.group) {
-            return 1;
+            if (rightGroup === 'navigation') {
+                return leftGroup === 'navigation' ? 0 : 1;
+            }
+            return leftGroup.localeCompare(rightGroup);
+        };
+        const result = compareGroup(left.group, right.group);
+        if (result !== 0) {
+            return result;
         }
         return (left.priority || 0) - (right.priority || 0);
     };
```
?

**Comment by kittaakos** [comment]
I will take care of it.
