### ISSUE TITLE
[ui]need title atribute in search result node

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5627]
### Description
when I want to kown which file in the search result, I should click it and preview it in the editor or expand the result area.
* Theia:
![search result](https://user-images.githubusercontent.com/35068357/60576556-3a558980-9db0-11e9-9b64-d23cbc0d669d.gif)
But in VsCode, I can get it just hover on the result, it's more convenient.
* vscode
![image](https://user-images.githubusercontent.com/35068357/60576018-278e8500-9daf-11e9-9ef3-c43fcebe8a7d.png)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
Closed by #5628
