### ISSUE TITLE
[notification] As a user I want to dismiss the notifications with `Esc`.

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5635]
### Description
 

So when I open a running workspace for instance in Gitpod, the following notifications great me:
![Screen Shot 2019-07-04 at 09 39 54](https://user-images.githubusercontent.com/1405703/60648294-f27e4300-9e3f-11e9-8d79-dd98d33d541a.jpg)

The notifications hide the _Command Palette_ so I want to dismiss them ASAP but instead of clicking on `Close`, `Close`, and `Close`, I want to tap-tap-tap (🐈 ) <kbd>Esc</kbd>. <kbd>Esc</kbd> should dismiss the notification no matter where the focus is. At least as I user I would expect this behavior. <kbd>Esc</kbd> would close the top-most item in the notification queue.

<kbd>Esc</kbd> must not dismiss a notification which requires an input. I do not know if there is such a notification, though.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@AlexTugarev are you planning look into it next days? It seems that it can be implemented without aligning with VS Code for now as well? Maybe we better to annotate  `help wanted`?

**Comment by AlexTugarev** [comment]
I can introduce a `notificationFocus` context and bind `esc` for current notifications in the next days.
