### ISSUE TITLE
[electron] DTraceProviderBindings.node complains about the node.js version

### ISSUE THREAD

**Issue by cdietrich** [theia-ide/theia#565]
I am getting following error message when running the electron example (using node 8.5.0)

```
    + 473 hidden modules
Starting express on port 'undefined'.
Allowed host is 'localhost'.
Error: The module '/Users/dietrich/git/theia/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
```

**Comment by akosyakov** [comment]
I don't think `dtrace-provider` is used. Does it really break?

**Comment by cdietrich** [comment]
it starts anyway so i am not sure if its really used

**Comment by GitAmod** [comment]
facing the similar issue, win 7. 

-------------------------------------------------------------------------------------------

Amod@Admin MINGW64 /theia/examples/electron (master)
$ yarn run start
yarn run v1.3.2
$ theia start
'C:\Program' is not recognized as an internal or external command,

operable program or batch file.

Done in 1.53s.

------------------------------------------------------------------------------------------

can you please suggest?

**Comment by GitAmod** [comment]
noticed that "theia start" fails for 'windows electron' with folder name having space.

for workaround, I have created new repo. without space in folder name. It's working now.

**Comment by hexa00** [comment]
The issue @GitAmod refers to is different I think.. see #858

**Comment by kittaakos** [comment]
I have this issues all the time. Fortunately, it does not cause any problems. Still, I agree with @cdietrich: it is annoying and causes confusion.

I will change the title.

**Comment by kittaakos** [comment]
I do not see the error anymore. Please reopen if it still happens.
