### ISSUE TITLE
Theia DAP extension for ABL languague

### ISSUE THREAD

**Issue by BelidePruthvi** [theia-ide/theia#5653]
We are planning to build a DAP for ABL languague and add that extension to theia. 
I couldn't find any documentation to add this extension to theia.
Could you provide us some documentation or give us an idea about how to do it?

**Comment by kpge** [comment]
If you want to use vscode extension, you can see this wiki:
[Testing VS Code Extensions](https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions)
* create plugins folder under Theia repo folder
* download an extension (vsix file) from VS Code Marketplace to plugins folder
* start Theia browser example

**Comment by akosyakov** [comment]
@BelidePruthvi Would https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl work? You can try it as @kpge suggested.

If it does not then you can either develop own VS Code extension to share it between VS Code and Theia or just Theia plugin: https://www.theia-ide.org/doc/Authoring_Plugins.html

**Comment by ankkumar-progress** [comment]
@akosyakov  @kpge 
I and @BelidePruthvi  work on the same team.
We can't use the  https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl and have to stick to the second option (VS Code extension to share it between VS Code and Theia).

Question:

 To create a theia extension for ABL DAP, we need to have a vscode extension for ABL DAP ?
 I was looking into java-debug and node-debug (thiea extension ), they are doing it in the above way.
    
Earlier we implemented ABL LSP theia extension  which was straight forward.

![image](https://user-images.githubusercontent.com/45970796/61226589-52c68c00-a740-11e9-95a2-e4d6ae480fa5.png)

I was wondering if there is something simple and similar to the above approach for DAP.

A follow up question:

Is there any proper documentation how to include a vscode extension into a theia extension?

**Comment by akosyakov** [comment]
> To create a theia extension for ABL DAP, we need to have a vscode extension for ABL DAP ?
I was looking into java-debug and node-debug (thiea extension ), they are doing it in the above way.

You can also use Theia APIs to add debugger support, see how it is done in nodejs and java debug Theia extensions. But general recommendation is to use VS Code extensions. For instance nodejs and java debug extensions are going to be deprecated, as soon as we completely move to use VS Code extensions.

> Is there any proper documentation how to include a vscode extension into a theia extension?

You don't need to include, you can just deploy vscode extensions as it is with Theia: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions

If you stumble over any bugs let us know.
