### ISSUE TITLE
File in editor goes dirty after "replace all" and is not saveable after

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5671]
### Description
File not saved after using "replace all". It seems we save automatically after a "replace all", but after selecting the "Cancel" button, then try to "replace all" again and the opened file remains dirty, Add code in the file and try to save has no effect either. Cannot reproduce all the times, but very often.

### Reproduction Steps
![SaveAfterReplaceCancel](https://user-images.githubusercontent.com/419051/60840046-99dedb00-a19c-11e9-9399-0788d8198b48.gif)

**OS and Theia version:**
Ubuntu 16.04
Theia 0.8.0

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@lmcbout I have a few questions about this issue:
1. at the time of the issue, did you have `auto-save` on?
2. were you testing on `master`?

**Comment by lmcbout** [comment]
@vince-fugnitto 
Auto-save = off
Configuration: On master, I did not succeed to reproduce this issue yet
On branch: fangnx-fnx-fix-5454, was able to reproduce and at some point, I couldn't even close any file editor, couldn't save any editor either.

**Comment by vince-fugnitto** [comment]
> Auto-save = off

@lmcbout  `replace-all` does not save automatically when `auto-save` is off in `master`.

I propose we close the issue. We should only open issues from `master`. It makes more sense that if the bug was found in the PR and is not reproducible on `master` that it should be part of the review and not as a new issue.

Can we close the issue?

**Comment by lmcbout** [comment]
@vince-fugnitto If we close this issue, then the following pr #5600 
cannot be merged since the observation comes from that pr which is just about ready

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto If we close this issue, then the following pr #5600
> cannot be merged since the observation comes from that pr which is just about ready

If the PR introduces the bug then it should not be merged.
I think this issue should be closed and the PR review should have this observation instead.

**Comment by lmcbout** [comment]
This issue can be closed. After deeper investigation, the save occurring after a replace all is not necessary related to issue #5454. Another issue with details  Issue #5740 is showing information why sometimes the editor freeze. It seems more related to "editor.formatOnSave" = true
