### ISSUE TITLE
Theia electron/browser target have to be rebuild for both to work

### ISSUE THREAD

**Issue by soerendomroes** [theia-ide/theia#5676]
### Description
After building a theia application I can only start the browser version and not the electron version. If I use yarn run rebuild:electron, the electron version works, but not the browser version. This errors in the theia repository and my own theia IDE.
Is it intended to always rebuild for the specific target?

### Reproduction Steps
I check out the theia repository and run yarn in it.
I run the browser example in theia/examples/browser via yarn start (works)
I run the electron example in theia/examples/electron via yarn start (does not work).

**OS and Theia version:**
Ubuntu 18.04.2 LTS, current master from 8.7.2019

**Diagnostics:** 
yarn run v1.13.0
$ theia start --plugins=local-dir:../../plugins
[...]/theia/node_modules/electron/dist/electron --plugins=local-dir:../../plugins [...]/theia/examples/electron/src-gen/frontend/electron-main.js: symbol lookup error: [...]/theia/node_modules/native-keymap/build/Release/keymapping.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
Done in 1.01s.

**Comment by vince-fugnitto** [comment]
@soerendomroes is it necessary to build both the example application targets simultaneously?

The command `yarn rebuild:electron` rebuilds the native modules for Electron so that it works correctly while it does not make sense to do so for the `browser` target.

**Comment by soerendomroes** [comment]
@vince-fugnitto It is not necessary, but it would be nice. If I rebuild the electron target the browser target stops working and has to be rebuild. If this is intended please close this issue ;)

**Comment by vince-fugnitto** [comment]
Thank you @soerendomroes for the issue, as far as I know it's the intended behavior.
Please note that both the `example-browser` and `example-electron` applications present within the main repository are for test purposes only, they are included as an easy way for theia developers to test pull requests. This may not be the case for theia-based applications, but generally products are built for a specific target or at least it is true for us :)

For example, we have the following distributions and apps (docker & electron) which are each built differently and are intended for different targets. https://github.com/theia-ide/theia-apps

**Comment by vince-fugnitto** [comment]
I hope this helps!

**Comment by soerendomroes** [comment]
Yes, I also use a different target for the bundled electron app and so forth, but for testing how the UI looks like in electron-app or specific browsers this was helpful.
Thank you for your answer.
