### ISSUE TITLE
Yarn 1.1 and tslint update causing linting errors

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#568]
I tracked this down to the whilespace   "check-separator", rule.

I'm not sure yet about the relationship between tslint and yarn.

tslint was also updated recently by 3b4276a626cae078cd2a3d35103573ba88946843

**Comment by akosyakov** [comment]
It seems that we should look into fixing peer dependencies warnings: https://github.com/yarnpkg/yarn/issues/4539#issuecomment-332165739

**Comment by hexa00** [comment]
In this case there is no peer dep warning for this...

**Comment by hexa00** [comment]
I made a reproducer project see the yarn issue referenced before

**Comment by kittaakos** [comment]
The Appveyor builds are failing for multiple independent PRs. I will look into this task and try to bump up the version.
What do we need? Please edit or comment:
 - [ ] Try out the TSLinter with the most recent Yarn.
 - [ ] Update documentation.
 - [ ] Update Travis and Appveyor configurations.
 - [ ] Update the docker file.

Failing PRs:
 - https://ci.appveyor.com/project/kittaakos/theia/build/1.0.1100
 - https://ci.appveyor.com/project/kittaakos/theia/build/1.0.1102
 - https://ci.appveyor.com/project/kittaakos/theia/build/1.0.1101

**Comment by hexa00** [comment]
I'm not sure that it is the yarn version that is problematic in those case ? 

We would need to check the chocolately.log to know what is going on.

However we can update to 1.2.1, the tslint errors are fixed in that version.

**Comment by kittaakos** [comment]
Any ideas, how to check the log?

**Comment by kittaakos** [comment]
I can confirm; it did not work with the latest version either.

**Comment by hexa00** [comment]
No I'm curious about how to get that log too :( Worst case execute a script that sends it somewhere ?

**Comment by kittaakos** [comment]
OK, I will check.

**Comment by kittaakos** [comment]
They must have some very serious issues, I cannot even submit a ticket on Appveyor's site:

```
We're sorry, but something went wrong

We've been notified about this issue and we'll take a look at it shortly.
```

**Comment by kittaakos** [comment]
The corresponding Appveyor issue can be tracked here: https://help.appveyor.com/discussions/problems/9054-cannot-install-yarn-with-choco
