### ISSUE TITLE
There should be a way to easily open the user settings (workspace/user)

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#569]
Maybe a simple menu contribution for now that opens the settings.json? Or two of them (one for workspace and one for user settings).

**Comment by svenefftinge** [comment]
The content for the user settings should be provided by some user-settings backend service to abstract over where the settings are stored. For example in containerized workspace scenario, I'd like to serve the settings from a central server database that manages user state. Same for personal keymap settings.

**Comment by epatpol** [comment]
Thanks for the pointers @svenefftinge, I've started modifying my keymaps PR in a local branch here https://github.com/epatpol/theia-1/commit/fcdb53181cc3b965378ba4e4a4ad3a6b2f30f4cd which adds a backend user storage server. Like you and @akosyakov mentionned you should be able to pull the resource using "user://keymaps.json".

**Comment by marcdumais-work** [comment]
I think this recently merged PR covers this issue: https://github.com/theia-ide/theia/pull/1892
