### ISSUE TITLE
Error while installing @theia/electron, node v12.2.0 npm 6.9.0 macOS

### ISSUE THREAD

**Issue by Lakkanna** [theia-ide/theia#5690]
### Description
Having problem while installing @theia/electron

![Screen Shot 2019-07-11 at 11 53 46 AM](https://user-images.githubusercontent.com/32791713/61027183-2672de80-a3d3-11e9-8320-ad98cb6480bd.png)

**OS and Theia version:**
OS: mac high sierra 10.13.6
Theia: 0.8.0
NPM: 6.9.0

**Diagnostics:** 
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/user1/hotelsoft/new-theia-setup/node_modules/@theia/electron/electron-h264-test.js'

**Comment by kittaakos** [comment]
> Having problem while installing @theia/electron

What do you mean by installing `@theia/electron`? What are you trying to achieve?
Strange that you get an error from `npm`, we [use `yarn`](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites).

 - Do you build Theia from the source? If yes, try to execute `git clean -ffxqd` and run `yarn` again.
 - Do you build your own application? If yes, please share your `package.json`, so that I can try to reproduce the issue.

**Comment by kittaakos** [comment]
If it is a Node.js version issue, [please switch to Node.js 10.x](https://github.com/theia-ide/theia/issues/5689).

**Comment by Lakkanna** [comment]
I'm creating own ide.
I want to use npm instead of yarn.
Node: v10.16.0(LTS)
npm: 6.9.0

```
{
  "name": "new-theia-setup",
  "version": "1.0.0",
  "keywords": [],
  "license": "MIT",
  "dependencies": {
    "@theia/callhierarchy": "0.8.0",
    "@theia/file-search": "0.8.0",
    "@theia/git": "0.8.0",
    "@theia/json": "0.8.0",
    "@theia/markers": "0.8.0",
    "@theia/merge-conflicts": "0.8.0",
    "@theia/messages": "0.8.0",
    "@theia/mini-browser": "0.8.0",
    "@theia/navigator": "0.8.0",
    "@theia/outline-view": "0.8.0",
    "@theia/preferences": "0.8.0",
    "@theia/preview": "0.8.0",
    "@theia/terminal": "0.8.0",
    "@theia/textmate-grammars": "0.8.0",
    "@theia/typescript": "0.8.0",
    "typescript": "3.5.3"
  },
  "devDependencies": {
    "@theia/cli": "0.8.0",
    "ts-loader": "6.0.4",
    "webpack": "4.35.3"
  }
}
```

**Comment by kittaakos** [comment]
> I want to use npm

You cannot. It won't work. The main reason we switched to `yarn` is to support workspaces.

And besides the workspace support, the [linking of binaries works differently](https://github.com/theia-ide/theia/issues/775). At least we used to have that issue with Node.js 8.x with the corresponding `npm` version.

**Comment by kittaakos** [comment]
I am closing this. Please reopen if required.
