### ISSUE TITLE
Searching file displays "No results found" while waiting the feed back from the search

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5698]
### Description
When performing a search file, between the time the user types something in the search text box and the answer to arrive, there is  a message being display: " No results found"
Why do we display this message?, why not just put "Searching", "Wait" or anything else but "No results found" 

### Reproduction Steps

![SearchNoFoundMessage](https://user-images.githubusercontent.com/419051/61078747-50d29500-a3ef-11e9-8898-b77ecf4d11c6.gif)

**OS and Theia version:**
Ubuntu and window
Theia 0.8.0

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
It looks like we render the `search-info` while waiting for the search to actually complete and at the time it displays the default for `0 results` which is `No Results Found.` until it re-updates when the search completes. I'm not sure it's a huge issue as we display `No Results Found` when there are no nodes in the tree and a search term is present.

**Comment by kittaakos** [comment]
> I'm not sure it's a huge issue

+1

But it's still a bug, isn't it?
