### ISSUE TITLE
Opener Handler improvements

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#57]
The OpenerHandler should be enhanced in the following ways:
 - [ ] OpenerOptions should provide information about where to open in the shell (main area, left, right, bottom dock)
 - [x] should provide and ID and a label, for 'open with'
 - [x] should have a `canHandle`method

**Comment by spoenemann** [comment]
> OpenerOptions should provide information about where to open in the shell (main area, left, right, bottom dock)

See WidgetOptions in [application-shell.ts](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/shell/application-shell.ts).
