### ISSUE TITLE
Problem creating an extension from stackoveflow

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#570]
This is from: https://stackoverflow.com/questions/46425991/theia-how-to-write-an-extension

I am trying to write an extension and have the following problem

    If i copy & paste the python extension, change python to python2 and the extension expression for files to py2 and include it in the browser example nothing happens (start never called)

    Same if i simply edit the existing python extension and change the constants like
    export const PYTHON_LANGUAGE_ID = 'python2';
    export const PYTHON_LANGUAGE_NAME = 'Python2';

what do i need to do to get my extension running

**Comment by cdietrich** [comment]
you can find the code https://github.com/cdietrich/theia/tree/try2 and https://github.com/cdietrich/theia/tree/try1

**Comment by kittaakos** [comment]
@cdietrich, I will try to reproduce the issue. Meanwhile, could you please confirm that you have the Python LS installed locally?

**Comment by cdietrich** [comment]
i dont have it, but thats the point, i get an error in the default example. but with my changes nothing happens. (no exception please install python language server)

**Comment by kittaakos** [comment]
I see your point now. Thanks for the clarification!

**Comment by cdietrich** [comment]
any news on this issue?

**Comment by cdietrich** [comment]
problem found. `python` is a default language in monaco and thus a registration is not needed. i propose to add one anyway for sake of consitency
