### ISSUE TITLE
Copy and Paste is Break by #5466

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5706]
### Description
@kittaakos @akosyakov 
Copy Download Link Break `Ctrl + C` on edit by #5466
![temp](https://user-images.githubusercontent.com/10203793/61166375-e80a2a80-a55e-11e9-87aa-c8ea06d51b50.gif)

### Reproduction Steps
look gif

**OS and Theia version:**
latest next version

**Diagnostics:**

**Comment by akosyakov** [comment]
@kittaakos Can you have a look at it or revert #5466?

**Comment by kittaakos** [comment]
We can either [revert](https://github.com/theia-ide/theia/pull/5708) it or have it [fixed](https://github.com/theia-ide/theia/pull/5709,) but then we cannot revert the [download link issue](https://github.com/theia-ide/theia/issues/5707).
