### ISSUE TITLE
Direct Download Url Support

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5707]
### Description
@kittaakos  @akosyakov 
before #5466 i have a script to auto sync theia workspace and server use direct download url
but after #5466 i can't do it
maybe can provide a permanent link for some file or dir

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
cc @kittaakos

**Comment by akosyakov** [comment]
> maybe can provide a permanent link for some file or dir

There is 1m timeout before a link is gone. If you script connect within 1m after triggering download, it should not it be enough?  Or you missing some additional APIs, i.e. to detect programmatically when download is prepared?

**Comment by 502647092** [comment]
@akosyakov before pr i can use workspace path direct download like `/home/project/xxxx`
but now i should use ui ti copy download link like `xxxx/file/download?id=xxxxxx`

**Comment by akosyakov** [comment]
We could provide a http-endpoint to get a link, so that you don't need a UI. Would it work?

**Comment by 502647092** [comment]
@akosyakov ok

**Comment by kittaakos** [comment]
> so that you don't need UI

You do not need UI. you have to do two separate requests instead. First, you get the download ID with an HTTP GET. This can be a [PUT if you want to download multiple files](https://github.com/theia-ide/theia/blob/6dd2579d01d61f093d258ad69978df0fc27aa184/packages/filesystem/src/browser/download/file-download-service.ts#L137-L139), then you perform another GET with the download ID.

```
curl -s http://localhost:3000/files/download?id=`node -pe 'JSON.parse(process.argv[1]).id' "$(curl -s curl http://localhost:3000/files/?uri=file:///Users/akos.kitta/git/theia/README.md)"` --output your-readme.txt
```
Note, here I have used Node.js to parse the download ID, but you are free to use whatever you want, for instance, [jq](https://stedolan.github.io/jq/).

@502647092, it would be great if you can adapt your scripts to the latest file download API, and get back to us if you could not use the proposed solution. If it works, I suggest closing this.

**Comment by 502647092** [comment]
@kittaakos Thank you
That's enough

**Comment by kittaakos** [comment]
> That's enough

I did not check for archives, feel free to reopen if you could not fully restore your scripts. Thanks!
