### ISSUE TITLE
Example browser tests cannot be executed inside examples/browser

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#571]
```
Akoss-MBP:theia akos.kitta$ cd examples/browser/
Akoss-MBP:browser akos.kitta$ yarn run test
yarn run v1.0.2
$ wdio
/bin/sh: wdio: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Akoss-MBP:browser akos.kitta$
```

`wdio` is missing as a dev depedndency.

**Comment by kittaakos** [comment]
Will be fixed as part of #165.

**Comment by hexa00** [comment]
@kittaakos could you extract that from the Git PR  ? 

It's relevant outside of it...

**Comment by kittaakos** [comment]
@akosyakov, what is the preferred way to add dev dependencies to the examples? Declaring it explicitly as a dev dependency although it is available at the parent too, or use `../../node_modules/.bin/wdio` from the npm script. Thanks!

+1 for declaring it explicitly as a dev dependency, so one can understand what is going on when looking into the example's package.json.

**Comment by hexa00** [comment]
Related: https://github.com/theia-ide/theia/pull/561
For the extensions we use ../../node_modules/.bin

I think we should use the same technique for the examples, it avoids having to copy the deps and manage the versions etc..

**Comment by kittaakos** [comment]
Then we need to change all binary calls to `../../node_modules/.bin` in the example npm scripts. Or do we want to fix it only for the tests?

```
    "prepare": "yarn run clean && yarn run build",
    "clean": "../../node_modules/.bin/theia clean && ../../node_modules/.bin/rimraf errorShots",
    "build": "../../node_modules/.bin/theia generate --target=browser && ../../node_modules/.bin/theia build",
    "watch": "../../node_modules/.bin/theia build --watch",
    "start": "../../node_modules/.bin/theia browser",
    "start:debug": "theia browser --loglevel=debug",
    "test": "../../node_modules/.bin/wdio",
    "coverage:compile": "../../node_modules/.bin/webpack --config coverage-webpack.config.js && ../../node_modules/.bin/shx cp src-gen/frontend/index.html lib",
    "coverage:remap": "../../node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/coverage-final.json --exclude 'frontend/index.js' && rimraf coverage/coverage.json",
    "coverage:report:html": "istanbul report --root coverage --format html",
    "coverage:report:lcov": "istanbul report --root coverage --format lcov",
    "coverage": "yarn coverage:compile && yarn test && yarn coverage:remap && yarn coverage:report:lcov && yarn coverage:report:html"
  },
```

I did not replace everything, it is already ugly. Or we can just leave as is and close this ticket.

**Comment by hexa00** [comment]
For that is using theia clin we don't need it. the bin is there an the cli finds the proper paths.

For the rest maybe we could use a script like theiaext ?

**Comment by akosyakov** [comment]
@kittaakos for theia you don't need it since `@theia/cli` is the dev dependency

**Comment by akosyakov** [comment]
also "coverage:compile" should be "theia  build --config coverage-webpack.config.js", it does copying and delegates to the webpack

**Comment by akosyakov** [comment]
You can do `yarn --ignore-scripts` in a workspace package before running npm scripts.

I've opened issues for yarn and lerna to improve it:
- https://github.com/yarnpkg/yarn/issues/4543
- https://github.com/lerna/lerna/issues/1031

**Comment by kittaakos** [comment]
Even without any `yarn`, `lerna`, or whatever scripts, one can do `../../node_modules/.bin/wdio`. I am closing this now.
