### ISSUE TITLE
two ':' in the code of  'mask'

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5711]
### Description
I find two ':' in the [code](https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/main/browser/view/view-registry.ts) , is this a mistake?
![image](https://user-images.githubusercontent.com/35068357/61215619-fa8e8a80-a73d-11e9-819f-b4e867a90d6c.png)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
@kpge, you can acquire a permanent link on GH: https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet
No need to printscreen and attach the source code anymore ;)

**Comment by vince-fugnitto** [comment]
@kpge it looks to be a mistake, would you like to take care of it?

https://github.com/theia-ide/theia/blob/6dd2579d01d61f093d258ad69978df0fc27aa184/packages/plugin-ext/src/main/browser/view/view-registry.ts#L57-L59

Based on other examples of `mask:`
https://github.com/theia-ide/theia/blob/6dd2579d01d61f093d258ad69978df0fc27aa184/packages/debug/src/browser/style/index.css#L159-L162

**Comment by akosyakov** [comment]
good catch, PRs are welcomed!
