### ISSUE TITLE
[ui/ux] inconsistency between 'no-markers' and 'no-outline' messages

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5716]
**Description**

There is an inconsistency between the `no-markers` and `no-outline` messages which are used to display when there are no information present in the view.

The `padding` values are inconsistent:

https://github.com/theia-ide/theia/blob/e830fbc2a32d62e3077e0179bfa2db5bb1f0b0c1/packages/markers/src/browser/style/index.css#L22-L24

https://github.com/theia-ide/theia/blob/e830fbc2a32d62e3077e0179bfa2db5bb1f0b0c1/packages/outline-view/src/browser/styles/index.css#L21-L25

---

<div align='center'>

<img width="856" alt="Screen Shot 2019-07-15 at 8 29 24 PM" src="https://user-images.githubusercontent.com/40359487/61257537-8ce35e00-a73f-11e9-9839-c7f35ac14973.png">

</div>

**Comment by akosyakov** [comment]
We should use relative padding with `--theia-ui-padding` variable.
