### ISSUE TITLE
[webview] icon of webview should be change when it appears on the left or right

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5722]
### Description
I think the size of webview icon has two problems:
* the size of webview icon is setted to `11px` in the code, which is smaller than other icon's size(`15px`)
https://github.com/theia-ide/theia/blob/da653c2692ad65c865ca5ba96b865b270cc916ff/packages/plugin-ext/src/main/browser/webview/theme-rules-service.ts#L123-L131
* when move the webview widget to left panel or right panel, the size should be `--theia-private-sidebar-icon-size`, the same as `tabbar-tabIcon`
![image](https://user-images.githubusercontent.com/35068357/61282257-9deaa880-a7ed-11e9-9ac1-1cdf83212862.png)

### Reproduction Steps
* install `cat coding` plugin in the `plugin` folder
* start theia 
* open cat coding 
* move the webview widget to left panel or right panel

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@kpge these icons are generated dynamically from plugin metadata, they cannot be defined in css. Generally you should be able to use css variables in dynamic rules as well.

**Comment by kpge** [comment]
@akosyakov I know icon path is defined in the metadata, so background-image can be generated dynamically, but the default variables can be defined in the css file. I will send a PR, and move the default definition to css file. If they can't be move, I will change it.
