### ISSUE TITLE
[quick-open] grey line when scrolling down quick-open menu in dark theme

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5732]
In the **dark theme**, when scrolling down the quick-open menu, I notice there is a thick grey line appearing at the top position, which looks strange.

It is probably the same grey shadow line used in the **light theme**. But it should not be part of the quick-open menu UI in the dark theme.

![theia-quickopen-line](https://user-images.githubusercontent.com/25921074/61315124-150f4500-a7cc-11e9-86c9-aff5bb27df5a.gif)

![image](https://user-images.githubusercontent.com/25921074/61315486-d9c14600-a7cc-11e9-9c9b-fc3955c1c9b7.png)

**Comment by vince-fugnitto** [comment]
You will need to overwrite the following monaco css property 
```css
.monaco-scrollable-element > .shadow {}
```

--- 

<div align='center'>


<img width="948" alt="Screen Shot 2019-07-16 at 2 06 08 PM" src="https://user-images.githubusercontent.com/40359487/61318379-efd20500-a7d2-11e9-852a-f29b809328e0.png">


</div>

**Comment by vince-fugnitto** [comment]
VSCode does have a divider but it is much more subtle, maybe we can align the look with them.
In my example, I removed the styling so no shadow was present anymore.
