### ISSUE TITLE
${workspaceFolder} variable starts with slash on windows

### ISSUE THREAD

**Issue by Vineg** [theia-ide/theia#5734]
### Description
${workspaceFolder} starts with slash on windows system e.g. /c:/Users/Vineg/theia-workspace

### Reproduction Steps
Run browser example on windows OS, open any local workspace

windows 7, theia 0.8.0

**Diagnostics:** 
![image](https://user-images.githubusercontent.com/1757455/61328010-d5277c80-a822-11e9-9455-2ed3080b7b57.png)

I debugged this issue a little and can see that workspace url fragment uses URI("file:///c:/Users/...").path which leaves first slash untouched.

This issue causes 

> Attribute 'program' does not exist ('{path}'). error.

**Comment by akosyakov** [comment]
See https://github.com/theia-ide/theia/wiki/Coding-Guidelines#frontend-fs-path in order to fix.
