### ISSUE TITLE
[plug-in][doc] Breaking behavior change in Theia plug-ins

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5743]
After checking https://github.com/theia-ide/theia/issues/5738 we realized that from now on, it is a must to add the following to the `package.json` of any Theia plug-ins:
```json
"activationEvents": [
  "*"
]
```
Otherwise, it won't activate.

Instead of forcing clients to update their package.json content with the wildcard `activationEvents`, we could check if the `theiaPlugin` top level property exists in the `package.json` and if it has either the `backend` or the `frontend` props. If so, but the `activationEvents` is not defined, we can infer a wildcard. So the Theia plug-in can still start without any modifications. Thoughts?

CC: @benoitf

**Comment by akosyakov** [comment]
@benoitf @evidolob please let us know whether it would be enough to add a record to the CHANGELOG or we should fix it before next release

**Comment by benoitf** [comment]
The entry should be enough (or failing with how to fix the plug-in)
Adding the default activationEvent with wildcard may be good but for example VS Code documentation says that it's never defaulted to * and has to be explicit. So maybe better to be in sync with VS Code.

Regarding che, all our plug-ins have already been updated for that change.

**Comment by akosyakov** [comment]
> The entry should be enough (or failing with how to fix the plug-in)

Ok, let's update the changelog then.

> Adding the default activationEvent with wildcard may be good but for example VS Code documentation says that it's never defaulted to * and has to be explicit. So maybe better to be in sync with VS Code.

For VS Code extensions, we won't do it. It will be incorrect. I am asking only about Theia plugins.

**Comment by benoitf** [comment]
> For VS Code extensions, we won't do it. It will be incorrect. I am asking only about Theia plugins.
yes I understood, I was just saying that it's better to align behavior between theia plug-in and VSCode extension

**Comment by kittaakos** [comment]
Thank you all for the clarification.
