### ISSUE TITLE
[problem view] Minor Improvements

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#575]
<img width="527" alt="screen shot 2017-09-27 at 16 41 21" src="https://user-images.githubusercontent.com/372735/30919895-f71593f8-a3a2-11e7-896b-90ab35c2e7f3.png">

- [x] The parent of the file, should be shown without the workspace prefix. Note that it should be the container that is shown not the full path.
- [x] marker without severity should have an icon

**Comment by jbicker** [comment]
https://github.com/theia-ide/theia/pull/774
