### ISSUE TITLE
yarn watch doesn't work for extension development

### ISSUE THREAD

**Issue by shortwavedave** [theia-ide/theia#5758]
### Description
yarn watch for the browser-app hangs after some errors and the theia browser-app never runs on localhost.

If I don't use yarn watch, I can't seem to get the rebuild command and yarn start to update the browser code - nothing changes.

What is the best way to develop an extension? should I do it in the theia code tree instead?

### Reproduction Steps
```
mkdir hello-world
cd hello-world
yo theia-extension hello-world
cd browser-app
yarn watch
```

**OS and Theia version:**
Linux
node: v8.16.0
@theia/core = 0.8.0

**Diagnostics:** 

> /hello-world/browser-app  $ yarn watch
> yarn run v1.17.3
> $ theia build --watch --mode development
> 
> Webpack is watching the files…
> 
> 
> Hash: 6bdad7c70b3ac029c81a
> Version: webpack 4.36.1
> Time: 6705ms
> Built at: 2019-07-19 17:20:46
>                                   Asset       Size  Chunks             Chunk Names
>                             0.bundle.js   11.8 KiB       0  [emitted]  
>                         0.bundle.js.map   18.3 KiB       0  [emitted]  
>  0a32a80243e05284a5d741c5dc093f31.woff2   23.8 KiB          [emitted]  
>                             1.bundle.js   22.7 KiB       1  [emitted]  
>                         1.bundle.js.map   24.3 KiB       1  [emitted]  
>                            10.bundle.js   31.5 KiB      10  [emitted]  
>                        10.bundle.js.map   29.3 KiB      10  [emitted]  
>                            11.bundle.js     59 KiB      11  [emitted]  
>                        11.bundle.js.map   63.6 KiB      11  [emitted]  
>  11d1a2390613abf202bfd2ebbd5c4500.woff2   88.6 KiB          [emitted]  
>                            12.bundle.js    578 KiB      12  [emitted]  
>                        12.bundle.js.map    683 KiB      12  [emitted]  
>                            13.bundle.js    195 KiB      13  [emitted]  
>                        13.bundle.js.map    201 KiB      13  [emitted]  
>                            14.bundle.js   14.9 KiB      14  [emitted]  
>                        14.bundle.js.map   15.3 KiB      14  [emitted]  
>                            15.bundle.js    301 KiB      15  [emitted]  
>                        15.bundle.js.map    317 KiB      15  [emitted]  
>                            16.bundle.js   76.2 KiB      16  [emitted]  
>                        16.bundle.js.map   84.7 KiB      16  [emitted]  
>                            17.bundle.js   23.2 KiB      17  [emitted]  
>                        17.bundle.js.map   18.5 KiB      17  [emitted]  
>                            18.bundle.js   58.2 KiB      18  [emitted]  
>                        18.bundle.js.map     64 KiB      18  [emitted]  
>                            19.bundle.js   17.9 KiB      19  [emitted]  
>                        19.bundle.js.map   15.4 KiB      19  [emitted]  
>                             2.bundle.js   44.9 KiB       2  [emitted]  
>                         2.bundle.js.map   40.8 KiB       2  [emitted]  
>                            20.bundle.js   17.3 KiB      20  [emitted]  
>                        20.bundle.js.map   15.2 KiB      20  [emitted]  
>                            21.bundle.js   15.3 KiB      21  [emitted]  
>                        21.bundle.js.map   12.4 KiB      21  [emitted]  
>                            22.bundle.js   1.79 MiB      22  [emitted]  
>                        22.bundle.js.map    210 KiB      22  [emitted]  
>                            23.bundle.js    564 KiB      23  [emitted]  
>                        23.bundle.js.map    997 KiB      23  [emitted]  
>                            24.bundle.js    298 KiB      24  [emitted]  
>                        24.bundle.js.map    292 KiB      24  [emitted]  
>                            25.bundle.js    156 KiB      25  [emitted]  
>                        25.bundle.js.map    137 KiB      25  [emitted]  
>                            26.bundle.js    178 KiB      26  [emitted]  
>                        26.bundle.js.map    144 KiB      26  [emitted]  
>                            27.bundle.js   90.7 KiB      27  [emitted]  
>                        27.bundle.js.map   76.4 KiB      27  [emitted]  
>                            28.bundle.js    105 KiB      28  [emitted]  
>                        28.bundle.js.map   78.9 KiB      28  [emitted]  
>                            29.bundle.js   44.5 KiB      29  [emitted]  
>                        29.bundle.js.map   24.6 KiB      29  [emitted]  
>                             3.bundle.js    116 KiB       3  [emitted]  
>                         3.bundle.js.map     97 KiB       3  [emitted]  
>                            30.bundle.js   32.5 KiB      30  [emitted]  
>                        30.bundle.js.map   35.6 KiB      30  [emitted]  
>                            31.bundle.js     22 KiB      31  [emitted]  
>                        31.bundle.js.map   17.3 KiB      31  [emitted]  
>                            32.bundle.js   13.8 KiB      32  [emitted]  
>                        32.bundle.js.map   9.21 KiB      32  [emitted]  
>                            33.bundle.js   22.4 KiB      33  [emitted]  
>                        33.bundle.js.map   21.1 KiB      33  [emitted]  
>                            34.bundle.js   14.4 KiB      34  [emitted]  
>                        34.bundle.js.map   16.8 KiB      34  [emitted]  
>                            35.bundle.js   14.4 KiB      35  [emitted]  
>                        35.bundle.js.map   16.8 KiB      35  [emitted]  
>                            36.bundle.js   4.38 KiB      36  [emitted]  
>                        36.bundle.js.map   2.78 KiB      36  [emitted]  
>                            37.bundle.js    7.5 KiB      37  [emitted]  
>                        37.bundle.js.map   5.76 KiB      37  [emitted]  
>                            38.bundle.js   9.35 KiB      38  [emitted]  
>                        38.bundle.js.map   15.3 KiB      38  [emitted]  
>                            39.bundle.js   10.9 KiB      39  [emitted]  
>                        39.bundle.js.map   7.86 KiB      39  [emitted]  
>                             4.bundle.js   20.6 KiB       4  [emitted]  
>                         4.bundle.js.map   15.5 KiB       4  [emitted]  
>                            40.bundle.js   8.39 KiB      40  [emitted]  
>                        40.bundle.js.map   5.94 KiB      40  [emitted]  
>                            41.bundle.js   13.7 KiB      41  [emitted]  
>                        41.bundle.js.map   16.3 KiB      41  [emitted]  
>                            42.bundle.js   13.7 KiB      42  [emitted]  
>                        42.bundle.js.map   16.3 KiB      42  [emitted]  
>                            43.bundle.js   13.7 KiB      43  [emitted]  
>                        43.bundle.js.map   16.3 KiB      43  [emitted]  
>                            44.bundle.js   13.7 KiB      44  [emitted]  
>                        44.bundle.js.map   16.3 KiB      44  [emitted]  
>                            45.bundle.js   13.7 KiB      45  [emitted]  
>                        45.bundle.js.map   16.3 KiB      45  [emitted]  
>                            46.bundle.js   13.7 KiB      46  [emitted]  
>                        46.bundle.js.map   16.3 KiB      46  [emitted]  
>                            47.bundle.js   13.7 KiB      47  [emitted]  
>                        47.bundle.js.map   16.3 KiB      47  [emitted]  
>                            48.bundle.js   13.7 KiB      48  [emitted]  
>                        48.bundle.js.map   16.3 KiB      48  [emitted]  
>                            49.bundle.js   3.05 KiB      49  [emitted]  
>                        49.bundle.js.map   2.49 KiB      49  [emitted]  
>                             5.bundle.js   64.6 KiB       5  [emitted]  
>                         5.bundle.js.map   67.4 KiB       5  [emitted]  
>                            50.bundle.js   1.97 KiB      50  [emitted]  
>                        50.bundle.js.map   1.56 KiB      50  [emitted]  
>                            51.bundle.js  787 bytes      51  [emitted]  
>                        51.bundle.js.map  613 bytes      51  [emitted]  
>                             6.bundle.js   24.8 KiB       6  [emitted]  
>                         6.bundle.js.map   16.9 KiB       6  [emitted]  
>    674f50d287a8c48dc19ba404d20fe713.eot    162 KiB          [emitted]  
>                             7.bundle.js     22 KiB       7  [emitted]  
>                         7.bundle.js.map   15.5 KiB       7  [emitted]  
>                             8.bundle.js   23.1 KiB       8  [emitted]  
>                         8.bundle.js.map   17.7 KiB       8  [emitted]  
>                             9.bundle.js    790 KiB       9  [emitted]  
>                         9.bundle.js.map    835 KiB       9  [emitted]  
>    912ec66d7572ff821749319396470bde.svg    434 KiB          [emitted]  
>  af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB          [emitted]  
>    b06871f281fee6b241d60582ae9369b9.ttf    162 KiB          [emitted]  
>  b1b07a0660cb1664f670dec2760a5ccb.plist   10.3 KiB          [emitted]  
>                               bundle.js   4.97 MiB    main  [emitted]  main
>                           bundle.js.map   5.19 MiB    main  [emitted]  main
>    cf2aabacdc2b3a5768b03545cb1d8330.svg     21 KiB          [emitted]  
>  de59a97248b44599e6747a27a943f738.woff2   19.8 KiB          [emitted]  
>  e19892df121e7f85c61754c54bbb7951.woff2   48.6 KiB          [emitted]  
>    e817279537a0417d042f62fbb1b99eea.gif   43.1 KiB          [emitted]  
>   f8f821a66b20e5801e35df5ec4565b30.wasm    583 KiB          [emitted]  
>   fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB          [emitted]  
>            vs/base/worker/workerMain.js    489 KiB          [emitted]  
>        vs/base/worker/workerMain.js.map    661 KiB          [emitted]  
>               vs/editor/editor.main.css    255 KiB          [emitted]  
>                vs/editor/editor.main.js   5.19 MiB          [emitted]  
>            vs/editor/editor.main.js.map   8.03 MiB          [emitted]  
>         vs/editor/editor.main.nls.de.js   41.3 KiB          [emitted]  
>         vs/editor/editor.main.nls.es.js   41.8 KiB          [emitted]  
>         vs/editor/editor.main.nls.fr.js   45.2 KiB          [emitted]  
>         vs/editor/editor.main.nls.it.js   43.5 KiB          [emitted]  
>         vs/editor/editor.main.nls.ja.js   45.9 KiB          [emitted]  
>            vs/editor/editor.main.nls.js   35.6 KiB          [emitted]  
>         vs/editor/editor.main.nls.ko.js   41.9 KiB          [emitted]  
>         vs/editor/editor.main.nls.ru.js     63 KiB          [emitted]  
>      vs/editor/editor.main.nls.zh-cn.js   34.2 KiB          [emitted]  
>      vs/editor/editor.main.nls.zh-tw.js   34.3 KiB          [emitted]  
>              vs/language/css/cssMode.js   28.2 KiB          [emitted]  
>            vs/language/css/cssWorker.js    597 KiB          [emitted]  
>  vs/language/css/monaco.contribution.js   2.11 KiB          [emitted]  
>            vs/language/html/htmlMode.js   27.3 KiB          [emitted]  
>          vs/language/html/htmlWorker.js    337 KiB          [emitted]  
> vs/language/html/monaco.contribution.js   2.14 KiB          [emitted]  
>                            vs/loader.js   77.8 KiB          [emitted]  
>                        vs/loader.js.map     88 KiB          [emitted]  
> Entrypoint main = bundle.js bundle.js.map
> [../hello-world/lib/browser/hello-world-contribution.js] 2.56 KiB {36} [built]
> [../hello-world/lib/browser/hello-world-frontend-module.js] 603 bytes {36} [built]
> [../node_modules/@theia/core/src/common/keyboard/layouts sync recursive ^\.\/.*\.json$] ../node_modules/@theia/core/src/common/keyboard/layouts sync ^\.\/.*\.json$ 1.39 KiB {main} [built]
> [../node_modules/moment/locale sync recursive ^\.\/.*$] ../node_modules/moment/locale sync ^\.\/.*$ 3 KiB {34} {35} {41} {42} {43} {44} {45} {46} {47} {48} [optional] [built]
> [../node_modules/vscode-textmate/release sync recursive] ../node_modules/vscode-textmate/release sync 160 bytes {34} {35} {51} [built]
> [./src-gen/frontend/index.js] 4.01 KiB {main} [built]
>     + 1311 hidden modules
> 
> WARNING in ../node_modules/vscode-textmate/release/main.js 23:15-27
> Critical dependency: the request of a dependency is an expression
>  @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js
>  @ ../node_modules/@theia/monaco/lib/browser/textmate/index.js
>  @ ../node_modules/@theia/textmate-grammars/lib/browser/js.js
>  @ ../node_modules/@theia/textmate-grammars/lib/browser/textmate-grammars-frontend-module.js
>  @ ./src-gen/frontend/index.js
> 
> WARNING in ../node_modules/vscode-textmate/release/main.js
> Module Warning (from ../node_modules/source-map-loader/index.js):
> (Emitted value instead of an instance of Error) Cannot find SourceMap 'main.js.map': Error: Can't resolve './main.js.map' in '/home/david/src/theia_extensions/hello-world/node_modules/vscode-textmate/release'
>  @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js 73:24-50
>  @ ../node_modules/@theia/monaco/lib/browser/textmate/index.js
>  @ ../node_modules/@theia/textmate-grammars/lib/browser/js.js
>  @ ../node_modules/@theia/textmate-grammars/lib/browser/textmate-grammars-frontend-module.js
>  @ ./src-gen/frontend/index.js
> 
> WARNING in ../node_modules/typescript-language-server/lib/commands.js
> Module Warning (from ../node_modules/source-map-loader/index.js):
> (Emitted value instead of an instance of Error) Cannot find source file '../src/commands.ts': Error: Can't resolve '../src/commands.ts' in '/home/david/src/theia_extensions/hello-world/node_modules/typescript-language-server/lib'
>  @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-contribution.js 93:17-67
>  @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
>  @ ./src-gen/frontend/index.js
>

**Comment by vince-fugnitto** [comment]
@shortwavedave did you previously start the application? (ex: `cd browser-app` and `yarn start`)
The `browser-app` is being watched for changes in your example but it requires the `browser-app` to be started.

Generally I do the following:
1. open a terminal to start the application (`cd browser-app` and `yarn start`)
2. open a new terminal to watch for changes to the `browser-app` (`cd browser-app` and `yarn watch`)
3. open any number of terminals to watch my extension (ex: `cd cpp-debug` and `yarn watch`)

**Comment by shortwavedave** [comment]
@vince-fugnitto Oh I see, thank you for the example. That appears to work, although the errors are still there. If the errors are not important, I'll close this thread.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Oh I see, thank you for the example. That appears to work, although the errors are still there. If the errors are not important, I'll close this thread.

The warnings are fine for the moment, thank you for the issue!
