### ISSUE TITLE
[doc] Pin yarn version (1.0.2) in the documentation

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#576]
Otherwise, build just fails:

```
kittaakos@DESKTOP-531EDFN MINGW64 ~/Desktop
$ yarn --version && npm --version && node --version && python --version && git clone https://github.com/theia-ide/theia.git && cd theia && yarn && code .
0.27.5
5.3.0


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.3.0 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

v8.2.1
Python 2.7.11
Cloning into 'theia'...
remote: Counting objects: 13452, done.
remote: Compressing objects: 100% (105/105), done.
Receiving objects: 100% (13452/13452), 32.90 MiB | 2.22 MiB/s, done.3305R
Resolving deltas: 100% (8733/8733), done.

yarn install v0.27.5
error The workspace feature is currently experimental and needs to be manually enabled - please add "workspaces-experimental true" to your .yarnrc file.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kittaakos** [comment]
Just in case one runs into the same problem, these are the steps to install the correct version of yarn. Yarn 1.1.0 breaks the TS linter for some reason, see #563 and #554 for more details. Earlier versions, such as 0.27.5 does not work.

 - Open PowerShell as an administrator.
 - Run: `choco install yarn --version 1.0.2 -y`. The version is important.

If you have accidentally installed the latest released yarn version, just like I did, you have to remove it, then install it.

 - Run PowerShell as an administrator.
 - Run: `choco uninstall yarn -y`.
 - Run: `choco install yarn --version 1.0.2 -y`

**Comment by MarkZ3** [comment]
I added some doc in https://github.com/theia-ide/theia/pull/579
Is this sufficient to close this?
