### ISSUE TITLE
Tests cannot be executed inside packages/yourExtension on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#577]
I think it is unrelated to #571 because it works on OS X but fails on Windows. Steps to reproduce:
```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\kittaakos\Desktop\theia> cd .\packages\git\
PS C:\Users\kittaakos\Desktop\theia\packages\git> yarn run test
yarn run v1.0.2
$ theiaext test
'nyc' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hexa00** [comment]
textext used the PATH env to append the correct path and uses strings with / directly
either PATH is not the right env var or we should parse the path better

**Comment by akosyakov** [comment]
try to run from the root: `npx lerna run test --scope @theia/git --stream`

**Comment by kittaakos** [comment]
OK, thanks!

**Comment by kittaakos** [comment]
Did not work either:
```
PS C:\Users\kittaakos\Desktop\theia> pwd

Path
----
C:\Users\kittaakos\Desktop\theia


PS C:\Users\kittaakos\Desktop\theia> npx lerna run test --scope @theia/git --stream
Command failed: C:\"Program Files"\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.
js config get cache --parseable
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by akosyakov** [comment]
looks like: https://github.com/zkat/npx/issues/110
try update to the latest npx: `npx install -g npx@latest` or without it with `./node_modules/.bin/lerna`

**Comment by kittaakos** [comment]
I will take care of this, as it blocks #165.

**Comment by kittaakos** [comment]
There are multiple solutions for this now:
 - From the root: `npx run test @theia/git`
 - From the package: `yarn --ignore-scripts && yarn run test`
 - Or you can even ignore anything and do it with `../../node_modules/.bin/mocha -w --opts ../mocha.opts src/**/*.spec.ts`

I am closing this now as it works.

**Comment by hexa00** [comment]
We should add this to the Developing.md

**Comment by hexa00** [comment]
I'm doing that now...
