### ISSUE TITLE
Terminal process tests fail locally on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#578]
Fails on both PowerShell and MINGW64

Clone the repo, run yarn, then yarn run test. That is very unfortunate, because this and #577 I cannot run the tests on Windows.

```
@theia/process:     2) test pipe stream
@theia/process:   5 passing (4s)
@theia/process:   2 failing
@theia/process:   1) TerminalProcess test exit:
@theia/process:      Uncaught Error: connect ENOENT \\.\pipe\winpty-conout-1236-2-1d332f7631b8403-36df3fd2ac80555f4c4348b22932e28a
@theia/process:       at Object.exports._errnoException (util.js:1024:11)
@theia/process:       at exports._exceptionWithHostPort (util.js:1047:20)
@theia/process:       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
@theia/process:   2) TerminalProcess test pipe stream:
@theia/process:      Uncaught Error: connect ENOENT \\.\pipe\winpty-conin-1748-1-1d332f763655d83-49deff32db8cde262dd73e21f8280140
@theia/process:       at Object.exports._errnoException (util.js:1024:11)
@theia/process:       at exports._exceptionWithHostPort (util.js:1047:20)
@theia/process:       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
@theia/process: npm ERR! code ELIFECYCLE
@theia/process: npm ERR! errno 2
@theia/process: npm ERR! @theia/process@0.1.1 test: `theiaext test`
@theia/process: npm ERR! Exit status 2
@theia/process: npm ERR!
@theia/process: npm ERR! Failed at the @theia/process@0.1.1 test script.
@theia/process: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@theia/process: npm ERR! A complete log of this run can be found in:
```

**Comment by hexa00** [comment]
Is that in your branch or ?
Master seems fine: latest commit appveyor is : https://ci.appveyor.com/project/kittaakos/theia/build/1.0.760

**Comment by kittaakos** [comment]
Yes, this happens on a branch (GH-165). And most importantly, these tests do not fail on the Windows CI for us either, it happens when I execute the tests locally.

**Comment by hexa00** [comment]
So locally for master it's OK ?

**Comment by kittaakos** [comment]
Good point, I will try that right now, and I will put the results here. (But a fresh clone build takes ~20 minutes on my VirtualBox.)

**Comment by hexa00** [comment]
I'm trying this out too... ouch 20 minutes! :(

**Comment by kittaakos** [comment]
It failed. [GH-578_Windows10_VB_log.txt](https://github.com/theia-ide/theia/files/1338199/GH-578_Windows10_VB_log.txt)

**Comment by hexa00** [comment]
It worked here...  you could try to print process.execPath and try to run it from the command line ?
It's quite weird..

**Comment by hexa00** [comment]
Looks like winpty is having issues, maybe you could check: https://github.com/rprichard/winpty#debugging-winpty ?

**Comment by kittaakos** [comment]
> you could try to print process.execPath and try to run it from the command line

Where to print `process.execPath`? I did run it from the command line, you can check the log.

**Comment by kittaakos** [comment]
I will try to take care of this, it blocks #165.

**Comment by kittaakos** [comment]
I cannot reproduce it anymore. I am closing this issue.
