### ISSUE TITLE
[filesystem] Use a FileSystem component in the backend?

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#5785]
As a general rule of thumb, anything with side effects should be injectable.

Filesystem APIs are one such thing. But in the [coding guidelines](https://github.com/theia-ide/theia/wiki/Coding-Guidelines#backend-fs), it is advised to rely on `fs-extra` or direct node-apis. But this makes it hard to test components that may use it.

For now I'm injecting the `FileSystem` component, even in the backend. But should we rather make some kind of simplier implementation solely for the backend, and only expose to the frontend the one currently implemented?

**Comment by akosyakov** [comment]
I don't think we want to abstract away from nodejs apis. Do you have an example of what you want to test? In most case I would just create testdata and test against fs. In other cases one can abstract fs specifically for some service like `PreferenceProvider` can be replaced for `PreferenceService`.

**Comment by marechal-p** [comment]
That works, but sometimes it would be useful to prevent a component from writing to the filesystem at all.  I was looking at changing the few occurrences of the filesystem being used on the backend, but it made me wonder how I would go about testing it, but I guess one way to go about it would be to break down methods so that the core that needs to be tested doesn't have side effects, and only test that.

I'll close for now and re-open if I encounter a strong need to do that again.
