### ISSUE TITLE
[electron] Please provide a way to disable the electron IP checks

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5787]
### Description
 

The electron codec check fails for me on a daily bases for downstream projects. This usually happens on both macOS and Windows when I switch between development branches and run `yarn`.

```
3.1".
[4/4] 🔨  Building fresh packages...
[1/5] ⠂ nsfw
[2/5] ⠂ electron
[-/5] ⠂ waiting...
[4/5] ⠂ electron
error /Users/akos.kitta/git/something/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/akos.kitta/git/something/node_modules/electron
Output:
/Users/akos.kitta/git/something/node_modules/electron/install.js:49
  throw err
  ^

```

Please give me a clear way to disable the codec check or fix it. As a workaround, I have to run `git clean -ffxqd` almost every time I switch a branch. Thank you!

### Reproduction Steps

**OS and Theia version:**
macOS and Windows
**Diagnostics:** 

Related: https://github.com/theia-ide/theia/issues/5642

**Comment by vince-fugnitto** [comment]
cc @marechal-p

**Comment by marechal-p** [comment]
Is the trace you sent the actual error log, or are you able to post something more detailled? In the meantime, you can skip the replacement and checks by setting `THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1` before hand.

**Comment by kittaakos** [comment]
> Is the trace you sent the actual error log, or are you able to post something more detailled?

I can't. That was all I saw in the log.

> THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1

Oh, I thought this is not available anymore. Thanks! 👍

**Comment by marechal-p** [comment]
@kittaakos It is not much but a very simple log file is written during install in the `@theia/electron` package, do you see anything like this? If so, what's the content?

I would rather fix the problem at hand :)

**Comment by kittaakos** [comment]
> If so, what's the content?

I do not have that state anymore. I will update and reopen the issue if it happens again.

**Comment by marechal-p** [comment]
Turns out it was my hash computation that was bogus :grimacing: 

Fix: https://github.com/theia-ide/theia/pull/5821
