### ISSUE TITLE
[quick-open] move Interface definition in common

### ISSUE THREAD

**Issue by hacke2** [theia-ide/theia#5797]
### Description
We should move `quick-open` to common as well to be able to call it from the backend. Like `packages/core/src/common/quick-pick-service.ts`

@akosyakov

**Comment by hacke2** [comment]
move `packages/core/src/browser/quick-open/quick-open-service.ts` to `packages/core/src/common/quick-open-service.ts`

**Comment by akosyakov** [comment]
- It should be done in backward-compatible manner, i.e. `quick-pick-service` file should steal exist in browser and reexport from common.
- It should be bound to the connection scope similar to the quick pick service that backend services in the connection scope could inject it.

Let's do it though later then we complete quick-pick, quick-input implementations for VS Code extensions. It is more important.
