### ISSUE TITLE
[quick-open] Apply dynamic quick pick items

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#5814]
### Description
 
The quick-pick menu must support dynamic items. Need to implement quick-pick `onDidChangeValue` emitter to be able to handle the input value and dynamically update quick pick items according to the input value. 
Can be tested against: https://github.com/microsoft/vscode-extension-samples/tree/master/quickinput-sample: _F1 => Quick Input Samples => quickOpen_

Depends on https://github.com/theia-ide/theia/pull/5187
### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
FYI, the link provided is broken https://github.com/Microsoft/vscode-extension-samples/tree/master/quickinput-samples

**Comment by vinokurig** [comment]
@vince-fugnitto Fixed the link

**Comment by vinokurig** [comment]
Is fixed by https://github.com/theia-ide/theia/pull/5187
