### ISSUE TITLE
Sometimes breakpoint moves into another line after some time

### ISSUE THREAD

**Issue by mmorhun** [theia-ide/theia#5827]
### Reproduction Steps

This bug could be reproduced quite often, but not all the time.
A scenario how to reproduce:

1. Generate a simple backend plugin using `Yeoman wizard` command.
2. Set a breakpoint into default command handler
3. Run the plugin in debug mode (using hosted instance for example)
4. Wait until debugger connects and invoke command to hit the breakpoint
5. Go back to Che Theia
5. The breakpoint moves for a few lines on its own.

Note, debugger stops exactly in the place where breakpoint was set, but the breakpoint marker moves, which can bring confusion especially when a user has many breakpoints.

![debugger-breakpoint-jump](https://user-images.githubusercontent.com/15607393/62193222-086c1e80-b380-11e9-9508-d7c006aea7c9.gif)

**OS and Theia version:**
Theia 0.8.0 (2c7485f)

**Comment by akosyakov** [comment]
I'm not sure whether it is a bug or bogus source maps. Moved breakpoints is not bug itself, since debugger receives breakpoints from a user, then try to apply them to running code and map them back to sources via source maps. If something is not matching it could be that debug adapter moves breakpoints bogusly.

**Comment by tsmaeder** [comment]
@mmorhun does the breakpoint move back to the original location when you stop debugging?

**Comment by mmorhun** [comment]
@tsmaeder yes, it moves back.

**Comment by mmorhun** [comment]
So, seems the problem is indeed in source maps.

**Comment by tom-shan** [comment]
During the debug process and after a new breakpoint is added, all breakpoints in the same ts file will becomes normal.

**Comment by akosyakov** [comment]
It could be that runtime context changed in the meantime, you can also just try to deactivate/activate breakpoints. Could someone the same in VS Code? If it is different maybe there is a bug with timing. Or try to debug it with Theia.

**Comment by tom-shan** [comment]
There are a [similar issue](https://github.com/microsoft/vscode-node-debug2/issues/176) of vscode-node-debug2. So I try to upgrade the node-debug and node-debug2 in https://github.com/theia-ide/theia/blob/master/packages/debug-nodejs/package.json#L52-L53 to the newest version(1.35.3 and 1.33.0), then the similar issue in my repo seems to be fixed.

**Comment by akosyakov** [comment]
@tom-shan Could you make a PR?

**Comment by tom-shan** [comment]
It's my pleasure.
