### ISSUE TITLE
[git] Add Git status bar

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#584]
Just like in VSCode.
Should list the remotes (maybe not) and the known branches. Also: ahead and behind.

When clicking on the branch, it should trigger a command with the `quick open widget` that helps in switching to and creating a new branch.

**Comment by svenefftinge** [comment]
Depends on #218

**Comment by svenefftinge** [comment]
the status bar now displays the current branch, but a command has not been bound yet.

**Comment by kittaakos** [comment]
I will take care of the rest:
 - creating a new branch and
 - check out existing ones.
