### ISSUE TITLE
After closing debugconsole, can not reopen debugconsole while running CodeLens

### ISSUE THREAD

**Issue by xieyuanhuata** [theia-ide/theia#5847]
step:
1、click the codelens link “Run”;
2、close the debugconsole；

plugins:
ms-python.python-2019.6.24221.vsix
ms-vscode.Go-0.11.4.vsix
redhat.java-0.47.0.vsix
shengchen.vscode-checkstyle-1.0.3.vsix
vscjava.vscode-java-debug-0.20.0.vsix
vscjava.vscode-java-dependency-0.5.1.vsix
vscjava.vscode-java-test-0.18.2.vsix
vscjava.vscode-maven-0.18.1.vsix

If I want to reopen debugcontole, I can only click the debugcontole option in the view menu

**Comment by xieyuanhuata** [comment]
![11](https://user-images.githubusercontent.com/50982164/62408966-18dffb80-b603-11e9-8635-9d684e13b10d.gif)

**Comment by xieyuanhuata** [comment]
![捕获](https://user-images.githubusercontent.com/50982164/62412000-61f97500-b62e-11e9-9608-78031f7051ff.PNG)

**Comment by akosyakov** [comment]
It can be configured in preferences as well as on launch configuration, see https://github.com/theia-ide/theia/blob/1f1fcd6ee1aadb80064898a823d7b13d779ddecb/packages/debug/src/browser/debug-preferences.ts#L38-L43
