### ISSUE TITLE
[pluginExt]  npm scripts showed when config.npm.enableScriptExplorer is false after npm extension installed

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5853]
### Description
when I installed `npm` extension from vscode, ther npm scripts eabled in the explorer widget, no matter what the value of  `config.npm.enableScriptExplorer ` is .
 
![image](https://user-images.githubusercontent.com/35068357/62433647-e8fe3880-b767-11e9-9417-87e0f44dd36f.png)
but the view should be enabled when `config.npm.enableScriptExplorer` is true
![image](https://user-images.githubusercontent.com/35068357/62433849-b1dc5700-b768-11e9-85a7-9287ca3ec8fc.png)

### Reproduction Steps
* install the `npm` version to theia plugins dir.
* compile the latest theia, and start theia example app.
**OS and Theia version:**
theia version: the latest version (b40a8d54380524dd1a8b05992ebf540b68806e92)
**Diagnostics:**

**Comment by akosyakov** [comment]
@kpge Would you like to investigate?

cc @elaihau

**Comment by akosyakov** [comment]
It is the view container issue. @AlexTugarev was mentioning that `when` closure is ignored. I will do a PR promptly.
