### ISSUE TITLE
Add Dockerfile to CI 

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#586]
The Dockerfile starts with FROM: node 7.10 so I"m pretty sure it's not working anymore...

We would need to add this to CI somehow too.

**Comment by akosyakov** [comment]
Do you mean to test the docker file on the CI?

**Comment by hexa00** [comment]
I mean we should first fix it.

Then find a way to build the docker image from the DockerFile and run the image with the test suite to make sure the image works.

**Comment by akosyakov** [comment]
ok, should be the separate stage then, scripts should belong to jobs of this stage, that stages before don't wait for docker to be installed

**Comment by hexa00** [comment]
Dockerfile is fixed by #592 

CI is still missing.

**Comment by akosyakov** [comment]
@hexa00 Are you going to look into CI?

**Comment by hexa00** [comment]
Yes

**Comment by kittaakos** [comment]
We have a bunch of Dockerfiles available here: https://github.com/theia-ide/theia-apps
