### ISSUE TITLE
some plugins are not loaded in time

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#5861]
### Description

Task providers are not registered on Theia startup. Take `npm` for example, the npm tasks are not loaded until `package.json` is opened.

![Peek 2019-08-05 09-45](https://user-images.githubusercontent.com/37082801/62469610-9b350080-b766-11e9-8be1-fdffdc03bbe8.gif)

### Reproduction Steps
See GIF

**OS and Theia version:**
Ubuntu 18.04. Chrome. Theia example-browser, master branch as of Aug 5 2019.

**Diagnostics:** 
Looks like "loading some plugins" is now event-driven?
Talked with @vince-fugnitto. We think probably it is related to this commit https://github.com/theia-ide/theia/commit/6021d795d61eafb214b234288f1568cae0cfa9f5 @akosyakov

**Comment by akosyakov** [comment]
Metadata should be loaded in advance, activation events only to run the extension code. Is it something what is contributed by code?

**Comment by akosyakov** [comment]
There is though one activation event which is not covered yet: https://github.com/microsoft/vscode/blob/051b669b61cd175cb06c8f4500498dbeef79114c/extensions/npm/package.json#L32

We should study maybe it should be activated before running any task.

**Comment by akosyakov** [comment]
@elaihau i will try to address it with a new activation event.
