### ISSUE TITLE
Change Theia baseUrl

### ISSUE THREAD

**Issue by fiurthorn** [theia-ide/theia#5862]
### Description

How to change the Theia baseUrl from *http://localhost:3000/* to *http://localhost:3000/theia/*

**Comment by akosyakov** [comment]
Theia is based on express js web server. You will need to google whether it allows to change base url.

**Comment by kpge** [comment]
It's hard to change the base url in theia,  you should change all the router where `app.use / app.get ...` appears.
I think you can use proxy to set the base url, such as  Nginx

**Comment by fiurthorn** [comment]
Using a Proxy works great, thanks.

**Comment by pawansingh00** [comment]
@fiurthorn Can you please elaborate and share some details on how using a proxy solved this?
For me even when I try to proxy it, it is dropping the **/theia** in further requests

like -> when this is hit -> `http://localhost:3000/theia/` the html content is served fine as below, but as can be seen it has this -> ` src="./bundle.js"`
and that is being loaded as -> `http://localhost:3000/bundle.js` dropping the `/theia` basepath

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <title>Eclipse Theia</title>
</head>

<body>
    <div class="theia-preload"></div>
    <script type="text/javascript" src="./bundle.js" charset="utf-8"></script>
</body>

</html>
```
