### ISSUE TITLE
API rate limit problem of appveyor build

### ISSUE THREAD

**Issue by tom-shan** [theia-ide/theia#5863]
### Description
https://ci.appveyor.com/project/kittaakos/theia/builds/26477407
https://ci.appveyor.com/project/kittaakos/theia/builds/26315393
There are two failed builds of appveyor CI in recent week.
Considering the low probability of this issue, we can assign a lower priority.

**OS and Theia version:**
Window

**Diagnostics:** 
`
error C:\projects\theia\node_modules\vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: C:\projects\theia\node_modules\vscode-ripgrep
Output:
Downloading ripgrep failed: Error: API rate limit exceeded for 67.225.165.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by tom-shan** [comment]
Maybe we can use [cache](https://www.appveyor.com/docs/build-cache/) like in https://github.com/theia-ide/theia/pull/5373.

**Comment by akosyakov** [comment]
Is it only about PRs from for forks? We should `GITHUB_TOKEN` set for our ci for branches from theia repo.

Caching sounds good as well.

**Comment by tom-shan** [comment]
Probably, I didn't check every failed build.

**Comment by tom-shan** [comment]
Sorry, I checked failed builds in recent month and found that only two builds which I listed above are failed for `API rate limit` problem.
So I think this issues can be ignored now.
