### ISSUE TITLE
Couldn't start browser example under Windows 10

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#587]
when I try to start the browser example with yarn run start I got this error:

child_process.js:107
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object.exports._forkChild (child_process.js:107:5)
    at Object.setupChannel (internal/process.js:244:8)
    at startup (bootstrap_node.js:69:16)
    at bootstrap_node.js:607:3

**Comment by UdoW** [comment]
[log.txt](https://github.com/theia-ide/theia/files/1340594/log.txt)

**Comment by akosyakov** [comment]
could you print your node version, npm version and yarn version?

**Comment by kittaakos** [comment]
Also the version of your Python, please. Thanks!

**Comment by kittaakos** [comment]
> could you print your node version, npm version and yarn version?

Maybe we should do it as part of `preinstall` so we do not have to ask for that each time explicitly. What do you think, @akosyakov?

**Comment by akosyakov** [comment]
> Maybe we should do it as part of preinstall so we do not have to ask for that each time explicitly.

I would like to simplify npm scripts when it is possible, this change will require adding new scripts.

We could try to warn users with engines attribute: https://github.com/theia-ide/theia/issues/553

Or create a bug template for github.

**Comment by kittaakos** [comment]
> will require adding new scripts.

One script, right?
`"preinstall": "printversions-or-whatever"`

**Comment by kittaakos** [comment]
If we can achieve this with engine attributes, taht is even better.

**Comment by UdoW** [comment]
node: v8.6.0
yarn: 1.0.2
npm: 5.4.2
Python: 2.7.13

**Comment by akosyakov** [comment]
Seems to be caused by spaces in paths: https://github.com/apparatus/fuge-runner/pull/18

**Comment by UdoW** [comment]
hmm, no spaces in the node installation nor in theia git clone dir.

**Comment by hexa00** [comment]
@kittaakos could this be the issue for #578 ? do you have spaces in the node exec path?

**Comment by UdoW** [comment]
How can I find out?

**Comment by UdoW** [comment]
I have an alias:    alias node='winpty node.exe'

**Comment by hexa00** [comment]
I get the same issue in my windows vm now.

**Comment by hexa00** [comment]
```
$ which node
/c/Program Files/nodejs/node
```
No spaces... 

yarn 1.0.2
node 8.3.0
python 2.7.13
npm 5.3.0

**Comment by hexa00** [comment]
Strangely if I try wdio it starts the backend properly! That's why appveyor is working.

**Comment by hexa00** [comment]
```
$ node src-gen/backend/main.js
Starting express on port 'undefined'.
{"name":"Theia","hostname":"DESKTOP-DS0FJTK","pid":1784,"level":30,"msg":"--root-dir= was not present. Falling back to current working directory: 'C:\\Users\\hexa\\src\\theia\\exa
mples\\browser'. [ [] ]","time":"2017-09-28T17:29:34.244Z","v":0}
```

It works with node so must be a problem with theia cli 
@akosyakov ^^

**Comment by hexa00** [comment]
@UdoW could you confirm that this is now fixed ?

**Comment by UdoW** [comment]
Yes, it works now. Thanks.
