### ISSUE TITLE
[question] should we publish the '@theia/ext-scripts' extension?

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5875]
**Description**

Extensions under dev-packages are all published except for `@theia/ext-scripts`.
Should `@theia/ext-scripts` also be published to npm (was there a reason for not publishing)?

**Reasoning**

It would be useful for extension developers to have as part of their `devDependencies` so they can benefit from useful Theia-specific development scripts. Currently if one wants to use the scripts provided by the `@theia/ext-scripts` extension they must manually copy the folder into their project (example: https://github.com/eclipse/theia-cpp-extension/pull/38)

**Comment by akosyakov** [comment]
I am not sure it can be used outside of theia repo context. It relies on project structure to reuse npm scripts. Plus it does not declare dependencies, but dev dependencies, which cannot be published. Extension developers are free to choose their own tools.

**Comment by vince-fugnitto** [comment]
> I am not sure it can be used outside of theia repo context. It relies on project structure to reuse npm scripts. Plus it does not declare dependencies, but dev dependencies, which cannot be published. Extension developers are free to choose their own tools.

Thank you for clarifying for me on why it wouldn't make much sense to be published :)
