### ISSUE TITLE
Multi-select quick picker does not allow multiple selection

### ISSUE THREAD

**Issue by DanTup** [theia-ide/theia#5881]
The VS Code quickpick API has a `canPickMany` property that allows multiple selections to be made, but that doesn't seem to work here - you just always get to pick one.

VS Code:

<img width="661" alt="Screenshot 2019-08-07 at 1 40 54 pm" src="https://user-images.githubusercontent.com/1078012/62623561-0fafa100-b919-11e9-8328-26706c5dfb5a.png">

Gitpod:

![Screenshot 2019-08-07 at 1 40 44 pm](https://user-images.githubusercontent.com/1078012/62623572-14745500-b919-11e9-9cd1-8a3bda100fdb.png)

**Comment by tetchel** [comment]
I think this is the same as my bug https://github.com/theia-ide/theia/issues/5673

**Comment by DanTup** [comment]
Oops, good spot - not sure how I didn't find that when searching (I forgot what the property was called until I was writing it up, so I probably searched badly!). I'll close this one - thanks!
