### ISSUE TITLE
[vscode] ignoreFocusOut option is not respected for InputBox and QuickPick

### ISSUE THREAD

**Issue by tetchel** [theia-ide/theia#5882]
Whether showQuickPick or createQuickPick (or InputBox) is used, I see the same behaviour; it is as though this property is not set / set to `false`.

https://code.visualstudio.com/api/references/vscode-api#QuickPickOptions
https://code.visualstudio.com/api/references/vscode-api#InputBoxOptions

**Comment by akosyakov** [comment]
@vinokurig @JPinkney do you think you can have a look into it?

**Comment by vinokurig** [comment]
@tetchel this should be fixed by https://github.com/theia-ide/theia/pull/5900, could you please test

**Comment by tetchel** [comment]
I verified #5900 works for QuickPick, thanks for that.

But InputBox needs the same change, so please don't close this until we have both.

**Comment by vinokurig** [comment]
@tetchel It should already work with InputBox, I've tested it by modifying the input-box action in the vscode quick-input sample. Could you please try to insert `ignoreFocusOut: true,` after this line: https://github.com/microsoft/vscode-extension-samples/blob/5fb626a4e383c41b8878f94045cff987b92b6bca/quickinput-sample/src/basicInput.ts#L26

**Comment by tetchel** [comment]
confirmed it does work. sorry, from the PR description i assumed it was quickinput only.
