### ISSUE TITLE
Enter is not working in editor

### ISSUE THREAD

**Issue by RomanNikitenko** [theia-ide/theia#5891]
### Description
Enter is not working in editor

### Reproduction Steps
Open some file and try to use Enter button.

**OS and Theia version:**
Ubuntu 18.04. Chrome.
0953ba77fe0b9c90bd7c122355acedc177ea5d0b

**Comment by azatsarynnyy** [comment]
reproduced on my side, also

**Comment by vince-fugnitto** [comment]
I believe it's caused during #5865

**Comment by akosyakov** [comment]
@vince-fugnitto Could you try before https://github.com/theia-ide/theia/commit/0953ba77fe0b9c90bd7c122355acedc177ea5d0b please to confirm?

**Comment by akosyakov** [comment]
@vince-fugnitto you are right, looking at `addKeyListener`: https://github.com/theia-ide/theia/blob/b40a8d54380524dd1a8b05992ebf540b68806e92/packages/core/src/browser/widgets/widget.ts#L206-L209

We should add return statements, i.e. 
```ts
    protected handleEscape(event: KeyboardEvent): boolean | void {
        const dialog = this.currentDialog;
        if (dialog) {
            return dialog['handleEscape'](event);
        }
        return false;
    }

    protected handleEnter(event: KeyboardEvent): boolean | void {
        const dialog = this.currentDialog;
        if (dialog) {
            return dialog['handleEnter'](event);
        }
        return false;
    }
```

Could someone do a PR please?

**Comment by akosyakov** [comment]
Also here: https://github.com/theia-ide/theia/commit/f48398e7dbcc9af711089802ad58b6fb05c8b661

we should do `return false` after if

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Could you try before [0953ba7](https://github.com/theia-ide/theia/commit/0953ba77fe0b9c90bd7c122355acedc177ea5d0b) please to confirm?

Yes I tried earlier, both 0953ba7 and `HEAD~1` and the problem was in 0953ba7
