### ISSUE TITLE
 Is there a reason why the watchFileChanges method should be called continuously?

### ISSUE THREAD

**Issue by lsjphd** [theia-ide/theia#5896]
In the Theia project, when the browser connects, an nsfw child process is created, and the root URI is attached to nsfw watcher through the watchFileChanges method.
After that, aren't all the files or directories in the workspace recursively detected? Why do I have to add URIs to nsfw via watchFileChanges every time I open the editor?

Is there a reason why you need to monitor additional subdirectories when the root directory is being monitored?

**Comment by akosyakov** [comment]
> Is there a reason why you need to monitor additional subdirectories when the root directory is being monitored?

Where does it happen? How can we reproduce it?

By default, Theia should watch only an entire workspace and opened files since they are not necessary belong to this workspace.

**Comment by lsjphd** [comment]
I didn't think that users could modify files not related to the workspace. Now I understand why watchers should be attached to each editor. Thank you
