### ISSUE TITLE
Restructure the repository to use separate extensions

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#59]
Because `npm link` only creates a symlink instead of prepublishing and copying content, as `npm install` does, it is recommended to use file dependencies for local development: http://stackoverflow.com/questions/14381898/local-dependency-in-package-json

In addition we should make sure that theia `prepublish` script includes other resources as styles and example consumes them from `lib` folder not from `src` as now.

**Comment by hexa00** [comment]
Is this still true after LDM ? Can we close this ?
@akosyakov ^^

**Comment by akosyakov** [comment]
It is still valid. We should try to decompose theia-core on separate extensions as @svenefftinge described.

**Comment by akosyakov** [comment]
It will be nice to structure in such way that we can open core, extensions, and examples in separate instances of VS code. Since there will be a lot of duplicate dependencies in node_modules and VS code will just go bananas watching them.

**Comment by hexa00** [comment]
OK I just changed the title to reflect that

**Comment by svenefftinge** [comment]
We should reconsider using 'lerna' with dependency hoisting. If we can 
 - have a linter that tells us when we use dependencies not listed in package.json
 - configure tsc to resolve against typescript modules from `src` instead of `lib` (cross package).

**Comment by svenefftinge** [comment]
Related https://github.com/Microsoft/TypeScript/issues/16792

**Comment by svenefftinge** [comment]
I manage to end up in *.ts when navigating by putting this into the example's tsconfig:

```js
{
   ...
    "baseUrl": "../..",
    "paths": {
      "theia-core/lib/*": [
        "src/*"
      ],
      "*": [
        "node_modules/*"
      ]
    }
}
```

We could list all our extensions in a commonly extended tsconfig, so tsc will reslve against the real src. Together with lerna and hoisted dependencies, we should also be able to use symbolic links again.

**Comment by akosyakov** [comment]
Done with #299
