### ISSUE TITLE
[git] Indicate a warning when the commit message exceeds the N character limit

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#590]
Something like: It is recommended to use the `Extended commit text` text input to separate the commit message header from the body.

**Comment by hexa00** [comment]
50 character ? where is that limit coming from ?

**Comment by marcdumais-work** [comment]
It seems it's a convention: 
[What’s with the 50/72 rule?](https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c)

**Comment by hexa00** [comment]
It seems he is talking about this personal experience... not sure I would call that a convention unless it's adopted by other people?

**Comment by marcdumais-work** [comment]
The limit seems to be respected at least by some editors. For example in vi the color changes for text that goes over the limit: 

![git-commit-text-50-chars-limit](https://user-images.githubusercontent.com/25749063/30985116-515b421c-a45d-11e7-97f5-e90fbb01cb32.gif)

**Comment by kittaakos** [comment]
See what [VSCode does](https://code.visualstudio.com/updates/v1_20#_git-commit-input-validation). We could get rid of the second input text field.
