### ISSUE TITLE
Syntax highlighting may break after a long line

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#5916]
### Description

It seems that if a line is longer than 401 chars, contents starting from the 402nd char will be ignored, which may break the syntax highlighting.

JSON
![json-syntax](https://user-images.githubusercontent.com/17487291/62848850-d6f43b00-bd0f-11e9-9280-d546c0c51b25.gif)

C
![c-syntax](https://user-images.githubusercontent.com/17487291/62848902-0e62e780-bd10-11e9-8e23-76b8e04aed62.gif)

### Reproduction Steps

1. Create a JSON file;
2. Type valid content but make one line very long;

**OS and Theia version:**
Ubuntu 18.04
Theia b23e3ccd53695df4c539a984655941456590367d

**Diagnostics:**

**Comment by akosyakov** [comment]
It is intended, to avoid hanging a browser minified files with a very long single line.

**Comment by akosyakov** [comment]
Closing it as a dup of https://github.com/theia-ide/theia/issues/4765. There is a suggestion to make it configurable via a preference. PRs are welcomed.

**Comment by 502647092** [comment]
@a1994846931931 
you can temp fix this problem
`sed -i s/lineLimit:400}/lineLimit:4000}/g /home/theia/lib/bundle.js`
