### ISSUE TITLE
Possible to open multiple editors for a file

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#5917]
### Description

It's possible to open multiple editors for one file by clicking terminal links with different paths but all lead to the single file.

![duplicate-file-editor](https://user-images.githubusercontent.com/17487291/62849804-9e566080-bd13-11e9-8ad5-6d4898ae973b.gif)

### Reproduction Steps

**OS and Theia version:**
Ubuntu 18.04
Theia b23e3ccd53695df4c539a984655941456590367d

**Diagnostics:**

**Comment by akosyakov** [comment]
@a1994846931931 Do you want to have a look? PRs are welcomed. I would try to debug `EditorManager.open` method and see why URIs is different from URI from the navigator. We have to normalize them to make the same.

**Comment by a1994846931931** [comment]
> @a1994846931931 Do you want to have a look? PRs are welcomed. I would try to debug `EditorManager.open` method and see why URIs is different from URI from the navigator. We have to normalize them to make the same.

OK. I am trying to solve it in the `terminal-linkmatcher-files` level.
