### ISSUE TITLE
snippet suggestion does not replace the input string

### ISSUE THREAD

**Issue by yeweiasia** [theia-ide/theia#5926]
### Description
snippet suggestion does not replace the input string, just append snippet to it

### Reproduction Steps
![autocompletion1](https://user-images.githubusercontent.com/16164849/62924018-c57b6380-bde1-11e9-898c-d61e29714acf.gif)

**OS and Theia version:**
ubuntu 18.04
theia 0.9.0
chrome 76.0.3809.100

**Diagnostics:**

**Comment by akosyakov** [comment]
PRs are welcomed! The issue is somewhere here: https://github.com/theia-ide/theia/blob/master/packages/monaco/src/browser/monaco-snippet-suggest-provider.ts#L22

**Comment by yeweiasia** [comment]
aha, I will take a look

**Comment by yeweiasia** [comment]
https://github.com/theia-ide/theia/pull/5931

**Comment by yeweiasia** [comment]
https://github.com/theia-ide/theia/pull/5963
