### ISSUE TITLE
Debug button remains opaque

### ISSUE THREAD

**Issue by tom-shan** [theia-ide/theia#5930]
### Description
When the debug button is clicked, this button remains opaque and will be
transparent only after another click event occurred in the same page.
![debug-button](https://user-images.githubusercontent.com/7686800/62932001-eb106900-bdf1-11e9-8031-7e3532937808.gif)

### Reproduction Steps

1 start debug session, you can use [this node demo repo](https://github.com/microsoft/vscode-remote-try-node.git)
2 click stop button
3 the stop button will never be transparent until you click anywhere in the same page.

**OS and Theia version:**
OS: ubuntu 18.04
Theia version: master 11badc

**Diagnostics:** 

this issue may be related to https://github.com/theia-ide/theia/commit/2e1d719c8454a0e87d64f1dd2424fa55d244648b#diff-cb367aa6c86884a6382b29179659ffd8R113

**Comment by akosyakov** [comment]
PRs are welcomed.

@tom-shan maybe you can tweak styles a bit in the debug extension to fix it
