### ISSUE TITLE
open workspace dialog tree is missing the root name

### ISSUE THREAD

**Issue by Limorerez** [theia-ide/theia#5934]
### Description
I've created an extension in which I subclass WorkspaceFrontendContribution and overwrote the implementation of **doOpenWorkspace**. The only change is that I transfer a different _rootStat_ parameter to **showOpenDialog**.  What I achieved is that each time a user presses the openWorkspace command, a dialog is opened with the specific folder at the root of the tree. 
This worked fine until we moved to 0.9.0.  Now the dialog opens and the root folder name (in the tree view)  is missing. I can see the sub-folders inside this folder and when I hover on the root of the tree I can see the full path of the specific folder but its name is missing in the tree view. 

### Reproduction Steps
This is my implementation for the doOpenWorkspace method: 

```ts
const HOME_USER_PROJECT_FOLDER = "/home/user/projects/";
protected async doOpenWorkspace(): Promise<URI | undefined> {
    const stat = await this.fileSystem.getFileStat(
      FileUri.create(HOME_USER_PROJECT_FOLDER).toString()
    );
   const [rootStat] = [stat];
   const props = await this.openWorkspaceOpenFileDialogProps();
   const workspaceFolderOrWorkspaceFileUri = await this.fileDialogService.showOpenDialog(
      props,
      rootStat
    );
    if (workspaceFolderOrWorkspaceFileUri) {
      const destinationFolder = await this.fileSystem.getFileStat(
      workspaceFolderOrWorkspaceFileUri.toString()
      );
     if (destinationFolder) {
        this.workspaceService.open(workspaceFolderOrWorkspaceFileUri);
        return workspaceFolderOrWorkspaceFileUri;
      }
    }
    return undefined;
  }
}
```

**OS and Theia version:**
0.9.0
**Diagnostics:** 
![projectsmissing](https://user-images.githubusercontent.com/4049399/62939372-cdcfa080-bdd9-11e9-99ef-163ad01f16aa.png)

**Comment by vince-fugnitto** [comment]
@Limorerez do you notice any logs in the console?

**Comment by Limorerez** [comment]
@vince-fugnitto Nothing suspicious: only this: 
[Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-F61EvOA9NwjZ9kdSTa3QEi8NXmQcexrgecdeMw6Hqik='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by vince-fugnitto** [comment]
@Limorerez I assume the extension itself is closed source? Else I'd gladly take a look at it for you.

**Comment by vince-fugnitto** [comment]
I used the code you provided and updated the repo's `doOpenWorkspace()` method and it 
worked correctly.

For reference:

```ts
    protected async doOpenWorkspace(): Promise<URI | undefined> {
        const HOME_USER_PROJECT_FOLDER = '/home/evinfug/Desktop/aaa';
        const stat = await this.fileSystem.getFileStat(
            FileUri.create(HOME_USER_PROJECT_FOLDER).toString()
        );
        const [rootStat] = [stat];
        const props = await this.openWorkspaceOpenFileDialogProps();
        const workspaceFolderOrWorkspaceFileUri = await this.fileDialogService.showOpenDialog(
            props,
            rootStat
        );
        if (workspaceFolderOrWorkspaceFileUri) {
            const destinationFolder = await this.fileSystem.getFileStat(
                workspaceFolderOrWorkspaceFileUri.toString()
            );
            if (destinationFolder) {
                this.workspaceService.open(workspaceFolderOrWorkspaceFileUri);
                return workspaceFolderOrWorkspaceFileUri;
            }
        }
        return undefined;
    }

```

**Comment by Limorerez** [comment]
@vince-fugnitto Is it possible that I should not use / at the end of the folder path? 
This is the only difference I can see between my code and yours: 
const HOME_USER_PROJECT_FOLDER = '/home/evinfug/Desktop/aaa';
vs
const HOME_USER_PROJECT_FOLDER = "/home/user/projects/";

**Comment by vince-fugnitto** [comment]
I updated the code to have the path `/home/evinfug/Desktop/aaa/` and I get the behavior you mentioned, the trailing `/` looks to be the issue. There was probably recent developments that may have changed URIs.

**Comment by Limorerez** [comment]
Great..Thanks a lot!

**Comment by vince-fugnitto** [comment]
> Great..Thanks a lot!

You're welcome :)

**Comment by vince-fugnitto** [comment]
@akosyakov should the issue be closed, or is there something on Theia's end that needs to be done?

**Comment by akosyakov** [comment]
I wonder why the parent display name is empty. I will expect that for `/home/evinfug/Desktop/aaa/` , parent dir is `/home/evinfug/Desktop/aaa`, not an empty.

**Comment by Limorerez** [comment]
I agree. This is a new behavior.
