### ISSUE TITLE
[SCM] Git init command

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#5936]
In case the workspace isn't a git repository (or other SCM repository) there is a weird message in the SCM widget. The SCM provider's should be asked if they can init a workspace and in case they do show a button to the user.

Leaving all the abstraction stuff aside, there should be a button to init a git repository :)

**Comment by akosyakov** [comment]
That how it looks in VS Code: https://code.visualstudio.com/docs/editor/versioncontrol#_initialize-a-repository

**Comment by svenefftinge** [comment]
We discussed to do the following:
 - register a command and toolbar (+) in git
 - fix the message to 'No repository found' (align rest with screenshot above)
 - make all other commands invisible when no repository found.
