### ISSUE TITLE
[debug] callstack not expanded on breakpoint stop

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#5949]
Starting a launch config with a breakpoint (nodejs) that hits, doesn't expand the call stack on the left. It should reveal the debug view and the call stack.

**Comment by akosyakov** [comment]
I think it should not happen always, as a user i would like to hide it have more space for the editor and debug console. So If i did it, it should not pop up again at least for the same session, so probably it should work only on the first stop.

**Comment by akosyakov** [comment]
@svenefftinge Actually, there is a preference `debug.openDebug` which allow to configure it: https://github.com/theia-ide/theia/blob/17bfcb2eee69acccade5106de050576f6c46206a/packages/debug/src/browser/debug-preferences.ts#L33-L37

Should we change a default to `openOnDebugBreak`?

**Comment by svenefftinge** [comment]
`openOnSessionStart` seems to be good. My main surprise was that the container for the call stack didn't expand.

**Comment by akosyakov** [comment]
> My main surprise was that the container for the call stack didn't expand.

It should be opened by default. But then if a user hides it on purpose, it would be strange to show it automatically. One can use a keyboard to control the debug session and hover over variables to see values without seeing the call stack. Or one can collapse the call stack to get more space for variables and then step over to see how variables updated. If call stack gets auto expanded in such cases it would be annoying.

**Comment by svenefftinge** [comment]
Turns out to be an initialization problem with view containers that is fixed on master already.
