### ISSUE TITLE
Git History open diff editor have error title

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5956]
### Description
![image](https://user-images.githubusercontent.com/10203793/63150585-c27ab000-c039-11e9-8757-509428c2025f.png)

### Reproduction Steps

- open git history
- open commit
- open diff editor

**OS and Theia version:**
git-commit: 9105c43ab

**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 I could not reproduce it from the master: 
<img width="1552" alt="Screen Shot 2019-08-16 at 09 54 41" src="https://user-images.githubusercontent.com/3082655/63152360-ed4e0f80-c00b-11e9-84ef-7d604dba5834.png">

If you can write done more concrete scenario, like how do you open git history from which context, which commit and which file maybe it would help to reproduce.

**Comment by akosyakov** [comment]
@vince-fugnitto maybe we introduced it by https://github.com/theia-ide/theia/commit/9105c43ab0fc0b386adbf698f74356055772d9c4#diff-030d37e8ae5f19ecc3c08047f819e016R100 not sure

@502647092 is there a change that you can have a look into it?

**Comment by vince-fugnitto** [comment]
Checking out master at e8a29ca5690548b1a7fa0a646274be2c3e9b0426, I can confirm that the issue is also present.

**Comment by akosyakov** [comment]
ok, someone has to figure out what is wrong, we also changed `NavigatableWidgetOpenHandler`, maybe it is the reason

I can have look earlier somewhere next week, if someone can before please do

**Comment by vince-fugnitto** [comment]
> ok, someone has to figure out what is wrong, we also changed `NavigatableWidgetOpenHandler`, maybe it is the reason

It has to do with the changes from https://github.com/theia-ide/theia/pull/5918.
Removing the call `normalizePath()` fixes the issue.

**Comment by akosyakov** [comment]
@a1994846931931 Would you have change to have a look at https://github.com/theia-ide/theia/issues/5956#issuecomment-522000190? It seems we missed some cases.

**Comment by a1994846931931** [comment]
> @a1994846931931 Would you have change to have a look at [#5956 (comment)](https://github.com/theia-ide/theia/issues/5956#issuecomment-522000190)? It seems we missed some cases.

@akosyakov Sure, I'll take a look at it soon. Maybe tomorrow morning, since it's late at night here and I happen to be on a train.

**Comment by a1994846931931** [comment]
The problem is caused by that empty path `''` will be normalized as `.` This is also the way how Node.JS path handle it. So it isn't a problem, until we call `URI.normalizePath()` on URI whose scheme is not `file`. A PR will come soon.
