### ISSUE TITLE
Preferences are ignored on reload of browser tab

### ISSUE THREAD

**Issue by soerendomroes** [theia-ide/theia#5984]
### Description
The workspace preference for `workspace.preserveWindow` is set to `true`. If I run my Theia instance in socket mode and connect to `localhost:3000` the first time I correctly get the right value for the preference. Reloading the browser tab causes the preference to be not correctly read and returning `false` (the default value). The settings.json still displays the correct value `true`.

### Reproduction Steps
Log a preference in some onStart method, for example in the GettingStartedWidget (I wanted to add a preference to safe whether this widget should be opened).

I added the following line
`console.log("preserveWindow", this.workspacePreferences["workspace.preserveWindow"])` in the onStart method of the GettingStartedWidget and injected the `WorkspacePreferences`.

**OS and Theia version:** ubuntu 18.04 LTS,  Theia 0.9.0-next.7fe439a3

**Diagnostics:** 
It does not matter whether I only set the preference in the user settings or in both or if only user settings exist.

**Comment by vince-fugnitto** [comment]
@soerendomroes 

Do you mind providing a bit more information on what the behavior was?
It is highly possible that when logging the preference value from the `onStart` method present in the `GettingStartedWidget` the default value was logged until the preferences were ready which would later update to it's correct value.

During my own tests I have enabled/disabled the `preserveWindow` preference and it worked correctly. The preference was also preserved upon reload.

**Comment by soerendomroes** [comment]
You are right. The preferences are not ready and the default value is logged. If I log the value later it is correct.
Do you have any suggestion how I can wait until the preferences are ready?

**Comment by vince-fugnitto** [comment]
> You are right. The preferences are not ready and the default value is logged. If I log the value later it is correct.
> I suppose `ready` fixes this problem.

I believe you can do something like:

```ts

@inject(WorkspacePreferences)
protected readonly workspacePreferences: WorkspacePreferences;

@postConstruct()
protected async init(): Promise<void> {
    await this.workspacePreferences.ready;
    this.workspacePreferences.onPreferenceChanged(change => {
        if (change.preferenceName === 'workspace.preserveWindow') {
            // perform actions
        }
    });
}


```
