### ISSUE TITLE
Add Language Support(STL)

### ISSUE THREAD

**Issue by akshaytaru2007** [theia-ide/theia#599]
Hi,

This is not an issue. I believe Theia currently supports  TypeScript, C/C++, Java, Python and Go Languages.
I want to support STL language to make Theia STL IDE. 
So my question is: Is there any way I can add support for STL language? If yes what changes I have to make? Or Do I have to create an extension in order to support STL?

**Comment by marcdumais-work** [comment]
Hi @akshaytaru2007,

Can you clarify which "STL" you are referring-to? ( https://en.wikipedia.org/wiki/STL )
![image](https://user-images.githubusercontent.com/25749063/31120484-8fd05160-a802-11e7-80e8-5fafd2e680bb.png)

In general, if there already exists a language server for a language, it's not hard to add support in Theia through an extension.

**Comment by akosyakov** [comment]
> So my question is: Is there any way I can add support for STL language? If yes what changes I have to make? Or Do I have to create an extension in order to support STL?

Hi, developing a Theia extension is not much different from developing a npm package. You can build it a node package and distribute it via npm.  Look at https://github.com/theia-ide/theia-extension-example. It demonstrates an extension developer setup.

**Comment by akshaytaru2007** [comment]
@marcdumais-work Thanks for reply.
I am referring to [State Logic](https://en.wikipedia.org/wiki/State_logic). Right now there is no Language server exists for this Language. 
Is it possible for you to provide any example for language extension for Theia?

**Comment by akosyakov** [comment]
> Right now there is no Language server exists for this Language.

Do you already have a compiler capable to cover LSP? If yes, look for SDKs to wrap your compiler into a language server, like [lsp4j](github.com/eclipse/lsp4j) or [vscode-languageserver](https://github.com/Microsoft/vscode-languageserver-node).

If not, have a look at [Xtext](https://www.eclipse.org/Xtext/). It is a framework to develop programming languages and it supports LSP. Here is a tutorial on building a language server with Xtext: http://typefox.io/tutorial-building-a-language-server-for-your-dsl.

> Is it possible for you to provide any example for language extension for Theia?

Look at any language extension in this repo to learn how to connect with an existing language server.

Particularly for Xtext Language Server, there is an example: https://github.com/TypeFox/theia-xtext. But Theia integration part is outdated: https://github.com/TypeFox/theia-xtext/issues/4. You are welcome to update it to the latest Theia. It could be a good exercise to learn about Theia integration with a Xtext-based language server.

**Comment by kittaakos** [comment]
There were no updates on this in the last year, I am closing it.
