### ISSUE TITLE
[vscode][plugin] Respect `when` condition for vscode plugins

### ISSUE THREAD

**Issue by vinokurig** [theia-ide/theia#6015]
### Description
 
Some vscode extensions have `when` condition provided in hair `pacage.json` file, e.g. the vscode github-pull-request extension has such condition in the view contribution: https://github.com/microsoft/vscode-pull-request-github/blob/d91e778705cd5af0785c5a05184ebc550334b409/package.json#L182
Since https://github.com/theia-ide/theia/pull/5855 was applied the plugin view is unavailable. 
### Reproduction Steps

1. Remove `git` from `theia/examples/browser/package.json`.
2. Download [vscode git extension](https://github.com/che-incubator/vscode-git/releases/download/1.30.1/vscode-git-1.3.0.1.vsix).
3. Create `plugins` folder in Theia's root and paste the plugin to it.
4. Clone the [vscode github extension](https://github.com/microsoft/vscode-pull-request-github.git) and compile it.
5. Start the github plugin as a Hosted Plugin.
6. Click the GitHub icon.

**WRONG:** The view is unavailable:
![screenshot-che-che 192 168 39 215 nip io-2019 08 15-10-21-47](https://user-images.githubusercontent.com/7668752/63514648-b8e9c000-c4f1-11e9-9d4d-c14e33b0152c.png)

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@vinokurig I believe it is already supported: https://github.com/theia-ide/theia/blob/5339bef84b447d457b15432f2b6a08368f95765f/packages/plugin-ext/src/main/browser/view/plugin-view-registry.ts#L112-L121

**Comment by vinokurig** [comment]
@akosyakov 
> @vinokurig I believe it is already supported: https://github.com/theia-ide/theia/blob/5339bef84b447d457b15432f2b6a08368f95765f/packages/plugin-ext/src/main/browser/view/plugin-view-registry.ts#L112-L121

It is, but it doesn't respect condition from the GitHub plugin: `"when": "!config.githubPullRequests.showInSCM && config.git.enabled"`
https://github.com/microsoft/vscode-pull-request-github/blob/d91e778705cd5af0785c5a05184ebc550334b409/package.json#L182
I'll rename the issue title

**Comment by akosyakov** [comment]
All preferences contributed by VS Code extensions should be already supported in `when` closure. These preferences are contributed by git and git pull request extensions, not by Theia. Are you sure that you have VS Code git extension installed?

**Comment by vinokurig** [comment]
@akosyakov 
> Are you sure that you have VS Code git extension installed?

yes, I can see contributed git preferences: 
![screenshot-localhost-3030-2019 08 23-14-15-13](https://user-images.githubusercontent.com/7668752/63589114-f06b7180-c5b0-11e9-82df-6db6683c6aae.png)
But they are not registered in the `ContextKeyService`

**Comment by akosyakov** [comment]
Sound like bug, they should be resolved from here: https://github.com/theia-ide/theia/blob/566ebda6b9ede33984ff0d06044e889b2191c9d7/packages/monaco/src/browser/monaco-frontend-module.ts#L140-L151 You can try to debug it.
