### ISSUE TITLE
change to launch schema by plugin system are not always recognized

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#6034]
It can be reproduced by:
- installing node and node2 vscode extensions;
- opening launch.json file, adding a new `node` launch configuration;
- and refreshing the page;
- expected that after the refresh `node` launch configuration is recognized as valid, but it does not happen always.

**Comment by a1994846931931** [comment]
Could it be related to #6046, as both `launch.json` and `settings.json` files have something to do with `FolderPreferenceProvider`?

**Comment by akosyakov** [comment]
@a1994846931931 it should be fixed in https://github.com/theia-ide/theia/pull/6035 Could you review please? Also try #6046 against it?

**Comment by a1994846931931** [comment]
> @a1994846931931 it should be fixed in #6035 Could you review please? Also try #6046 against it?

OK
