### ISSUE TITLE
how do we want to deal with Preference name collision

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#6037]
### Description

In current Theia, if a preference contributed by plugins has the same name with one from an extension, an error is thrown.

### Reproduction Steps

1. Add `typescript-language-features` vscode extension to Theia as a plugin.
2. Start Theia example browser, and check the console.
What happens: an error shows up:
`ERROR Preference name collision detected in the schema for property: typescript.tsdk`

![Screenshot from 2019-08-25 10-20-53](https://user-images.githubusercontent.com/37082801/63651420-896dca00-c722-11e9-9199-901eb13db555.png)

**OS and Theia version:**
Ubuntu 18.04. Theia master branch as of Aug 25 2019 ffcb3fa219e4df9410538965fde7c40a6a0e3d44. Example browser.

**Diagnostics:** 

`typescript.tsdk` is contributed by 
- typescript extension in Theia, and 
- typescript-language-features plugin (from vscode)

Do we need a mechanism to handle this scenario?

**Comment by akosyakov** [comment]
They should not be used together, either native Theia extension should be used or a VS Code extension. It does not make sense to have both.
