### ISSUE TITLE
[vscode] implement `env.openExternal` api

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#6039]
For example, It's required to install missing dart SDK for VS Code dart extension.

**Comment by chroberino** [comment]
Should `env.openExternal` in Theia do the same as in VS Code, i.e. use the OS' default application for opening a given URI? I am trying to use this call in a VS Code extension and in Theia files seem to always be opened within Theia (while in VS Code they open open in external apps).

**Comment by msujew** [comment]
@chroberino It is supposed to work exactly as in vscode. If it doesn't, please create a new bug report for this.
