### ISSUE TITLE
create a parser that can be used to parse the output of system processes

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#604]
The parser should be configurable so that we can use it in many different cases, such as parsing the output of builds and other processes. 

The starting point is a refactored version of "error parser" that has been previously reviewed by @hexa00 but never merged. WIP PR to come. 

A few things to potentially improve: 
- [ ] use the Theia event emitters instead of Node's
- [ ] ATM the parser is geared towards parsing for errors/warnings. It would be good to make it more generic. For example, we tentatively would like to use the parser to parse ripgrep's output to extract search results, for the "search within workspace" feature. Consider having the parser return/emit markers (Marker<object>, Marker<Diagnostic>? ) instead of internal type "IParsedEntry". 
- [ ] (Enhancement) add a registry for matchers, so that extension can contribute their own matchers, and that the parser can be called using the name of a registered matcher. 
...

**Comment by elaihau** [comment]
does https://github.com/theia-ide/theia/pull/5024 resolve this issue? @marcdumais-work @lmcbout

**Comment by lmcbout** [comment]
Yes it does. Thanks @elaihau
