### ISSUE TITLE
Workspace configuration that is registered by a VSCode plugin sometimes doesn't take effect

### ISSUE THREAD

**Issue by a1994846931931** [theia-ide/theia#6046]
### Description
Sometimes, VSCode plugin registered configurations doesn't work in workspace (user configuration does work, though). No error or warning is shown in the setting widget and everything seem to work nicely expect that the workspace configuration is actually ignored. It seems that these configuration is wrongly filtered.

### Reproduction Steps
This issue is kind of hard to reproduce. For one thing, it only happens in some VSCode plugins, for example, `cpptool`. For another, it doesn't always happen to them. So probably you need to try several times before it happens.

1. Launch theia with VSCode's cpptool plugin (attention: due to issue https://github.com/theia-ide/theia/issues/5899 , you need to clean `/tmp/vscode-unpacked/cpptool*` before restarting the background) or other VSCode plugins you want to test;
2. Play around with the configurations that is registered by the plugin, and make sure they work in user configuration;
3. Now refresh your browser and play around with the workspace configuration and see if they still take effect;
4. You may need to repeat step 3 several times;

There is another thing that I found interesting (or, weird) - the issue does not happen if all editors are closed. That is, it happens only when one or more files are opened.

#### Updated Reproduction Steps
Try reproduce by
https://github.com/theia-ide/theia/issues/6046#issuecomment-527334904

**OS and Theia version:**

Theia: 0.9.0
OS: Ubuntu

**Diagnostics:** 
None.

**Comment by a1994846931931** [comment]
It seems that it only happens for the first time the configuration is read. So if you make some changes to the workspace configuration and the plugin has a preference changed listener, the re-read configuration would be valid.

PS. The preference system is just so complicated and very difficult to diagnose. And the fact that `plugin-ext` is impossible to debug (am I wrong?) even adds to the difficulty.

**Comment by akosyakov** [comment]
> And the fact that plugin-ext is impossible to debug (am I wrong?) even adds to the difficulty.

@a1994846931931 it is possible, see https://github.com/theia-ide/theia/issues/3251#issuecomment-468166533 let me know if you need a help to get it running

**Comment by a1994846931931** [comment]
> > And the fact that plugin-ext is impossible to debug (am I wrong?) even adds to the difficulty.
> 
> @a1994846931931 it is possible, see [#3251 (comment)](https://github.com/theia-ide/theia/issues/3251#issuecomment-468166533) let me know if you need a help to get it running

@akosyakov Sorry, I mean debugging source code under `packages/plugin-ext`, not a VSCode extension.

**Comment by akosyakov** [comment]
> @akosyakov Sorry, I mean debugging source code under packages/plugin-ext, not a VSCode extension.

Which file? These source code runs in 3 different processes:
- main browser (use devtools)
- node backend (use Launch Backend configuration)
- and plugin host process, i.e. bootstrapping and communication code for VS Code extensions (from `plugin` folder) - https://github.com/theia-ide/theia/issues/3251#issuecomment-468166533 can be used to debug it

**Comment by a1994846931931** [comment]
## Diagnostic Update:

For workspace configurations, they are provided by `.theia/settings.json` and, will be validated and filtered by a schema. The schema will be updated when a plugin is loaded, through a series of events.   However in some cases, the VSCode plugin requires reading of preferences as soon as it's activated, and the preferences are read before it's refreshed, some configurations will then be filtered by the old schema.

This explains why this issue happens only:
1. For very the first time the workspace configuration is read;
2. When `package.json` of the VSCode plugin is very complicated (this requires a long time to parse the metadata);
3. For workspace configuration that is provided by `.theia/settings.json` (the validation process only works for `settings.json` under `.theia` folder). The logic behind it comes from the following lines:
https://github.com/theia-ide/theia/blob/1e67e74498a369c4665b28afd64e91ec5f6e0133/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L171-L174

Another interesting phenomenon is that, although user configuration is provided by `~/.theia/settings.json`, who is also under a folder named `.theia`, its values are not validated because the uri of this provider is `settings.json`, and in line
https://github.com/theia-ide/theia/blob/1e67e74498a369c4665b28afd64e91ec5f6e0133/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L173
`this.configurations.getPath(this.getUri())` would actually return `settings.json`, rather than expected `.theia` and, thus, https://github.com/theia-ide/theia/blob/1e67e74498a369c4665b28afd64e91ec5f6e0133/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L171
will return true directly.

## Proposal
Now that the cause of the problem is clear, the question of, how we should solve it, remains. I've attempted to solve it by adding schema-changed events `
        this.schemaProvider.onDidPreferenceSchemaChanged(() => this.readPreferences());` after https://github.com/theia-ide/theia/blob/1e67e74498a369c4665b28afd64e91ec5f6e0133/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L54-L56
but it just doesn't work for it still loses the race between refreshing of preference and preference reading from VSCode plugins.

So my proposal would be that, just remove https://github.com/theia-ide/theia/blob/1e67e74498a369c4665b28afd64e91ec5f6e0133/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L154-L157. After all, it only works for `setting.json` under workspace's `.theia` folder, which is strange because it behaves differently from configurations contributed by `${workspaceFolder}/.vscode/settings.json` or `~/.theia/settings.json`. So removing the process of validity should not cause a problem, or, will it? Have to admit that I'm not very confident of this modification but, nevertheless, a PR will be posted so you can check it out.

**Comment by a1994846931931** [comment]
## Updated Reproduction Steps

1. Download and deploy this simple test plugin on theia
[test-configuration-contribution-0.0.1.zip](https://github.com/theia-ide/theia/files/3568189/test-configuration-contribution-0.0.1.zip)
2. Add configuration `"test.testConfiguration": "new configuration"` to workspace configuration (you may need to create `.theia/settings.json` by your own;
3. Refresh the browser and watch the notification that says the read configuration from the workspace. It's expected to be `"test.testConfiguration": "new configuration"`, but it should probably be `"test.testConfiguration": "empty"` instead. You can also run `Show value of test.testConfiguration` command after that and the value should be correct then.
