### ISSUE TITLE
quickpick didn't open with 1 item 

### ISSUE THREAD

**Issue by i053322** [theia-ide/theia#6050]
### Description
In the new version of theia  ( theiaide/theia-full:next ) when I open quickpick with one item it doesn't show the item.
It works with multi items.

### Reproduction Steps
I created vsix from github ( with 1 item)
https://github.com/i053322/quickpickexample
Load the VSIX and press F1 and choose Hello World

**OS and Theia version:**
master

**Diagnostics:** 
I checked it on version 0.9.0 and it worked.
It it also worked on VS CODE

**Comment by akosyakov** [comment]
cc @JPinkney @vinokurig

**Comment by akosyakov** [comment]
> I checked it on version 0.9.0 and it worked.

@vince-fugnitto so it is not true? If it is not a regression then it is fine

> Removing this part of the code makes the quickPick [work] with a single item. Is this something we want to remove to align with VSCode?

For VS Code extensions APIs should work like in VS Code. In Theia core it can behave differently, maybe we need an option to align the plugin system behaviour with VS Code. We should look at all clients outside of the plugin system and see for them what we want. I won't surprise that it is different in VS Code as well for VS Code extensions and internal clients.

**Comment by akosyakov** [comment]
@vince-fugnitto I see, actually it sounds strange now that on show we don't show for a single item, but changing it now we break other clients like git extension.

I wonder can we add a flag like `runIfSingle` which is `true` by default, but set to `false` for the plugin system call? Could you do it?

**Comment by offer8** [comment]
@vince-fugnitto will it be part of next theia v0.10.0 release ?

**Comment by vince-fugnitto** [comment]
@offer8 yes it's included in last Thursday's release of v0.10.0
