### ISSUE TITLE
plugins are not loaded when theia is started without internet access

### ISSUE THREAD

**Issue by tom-shan** [theia-ide/theia#6055]
### Description
All the vscode plugins can not be loaded when my host machine has no Internat access.

we have two local vscode extensions which we downloaded from vscode marketplace:
1 [vscjava.vscode-java-dependency](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency)
2 [redhat.java](https://marketplace.visualstudio.com/items?itemName=redhat.java)

It should be noted that the **vscjava.vscode-java-dependency** extension depends on **redhat.java**(see https://github.com/microsoft/vscode-java-dependency/blob/master/package.json#L165).
When I start theia, theia plugin system will still try to download **redhat.java** from vscode marketplace. If my host has no Internat access, then all the plugins can not be loaded.

### Reproduction Steps

**OS and Theia version:**
centos 7
theia [6c4fa9c7](https://github.com/theia-ide/theia/commit/6c4fa9c7ff074ec9a028ae552ec096d6057ea9fd)
**Diagnostics:** 

related to https://github.com/theia-ide/theia/pull/5379 and https://github.com/theia-ide/theia/pull/6038

**Comment by akosyakov** [comment]
It is a regression caused by auto pulling extension dependencies. We should handle it gracefully and does not fail the whole deployment if one VS Code extension cannot be downloaded. cc @JPinkney 

@tom-shan I wonder how do you provide `redhat.java` then? If you don't do it then `vscjava.vscode-java-dependency` won't work properly either, no? Could you share a bit more info about settings.

**Comment by akosyakov** [comment]
@tom-shan Also If you can please help fixing it!

**Comment by tom-shan** [comment]
> @tom-shan I wonder how do you provide `redhat.java` then? If you don't do it then `vscjava.vscode-java-dependency` won't work properly either, no? Could you share a bit more info about your settings, i.e. plugins args or env variables?

No, `vscjava.vscode-java-dependency` won't work properly.
I just download `vscjava.vscode-java-dependency` from vscode markeplace and copy it to `plugins` directory.
>@tom-shan Also If you can please help fixing it!

Sure, please have a review.

**Comment by tom-shan** [comment]
In my local repo, I just comment these [3 lines](https://github.com/theia-ide/theia/blob/85b75768f702656db4ee8ff6eaad303be8102643/packages/plugin-ext/src/main/node/plugin-deployer-impl.ts#L136-L138) and workaround this issue.
