### ISSUE TITLE
plugin system should notify a user about loading and activation errors

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#6061]
- if a plugin fails to load/activate there should be an error notification with details
- If a plugin dependency is missing then a plugin should not be activated, and there should be a notification about missing dependency with suggestion to install an extension
- if a plugin dependency fails to load/activate then a plugin activation/loading should fail as well

cc @JPinkney

**Comment by amiramw** [comment]
- if a plugin activation throws exception should plugin host be tolerate and not fail all other plugins?
- if a plugin activation throws exception currently the exception is not logged anywhere. You must debug the host in order to find out what happened.
- if a plugin load/activation throws exception should it be reflected in the plugins view?

**Comment by akosyakov** [comment]
> if a plugin activation throws exception should plugin host be tolerate and not fail all other plugins?

no, a plugin cannot be activated if its dependencies are not activated

> if a plugin activation throws exception currently the exception is not logged anywhere. You must debug the host in order to find out what happened.

an error should be logged and a user should receive an error notification as well

> if a plugin load/activation throws exception should it be reflected in the plugins view?

It should be the same as in VS Code. Could you check what happens there? In anyway, for now error notifications would be enough to me.

**Comment by amiramw** [comment]
> no, a plugin cannot be activated if its dependencies are not activated

what about two plugins that are not dependent? Should the first failure prevent from the second to be activated?

**Comment by amiramw** [comment]
> It should be the same as in VS Code. Could you check what happens there? In anyway, for now error notifications would be enough to me.

VS Code does not reflect it in any way (only notification). I think we can do better but it is not high priority.

**Comment by akosyakov** [comment]
> what about two plugins that are not dependent? Should the first failure prevent from the second to be activated?

No, independent plugins should be activated independent. It is already a case I believe.

**Comment by amiramw** [comment]
> No, independent plugins should be activated independent. It is already a case I believe.

In the case of exception thrown on activation method the plugin host crashes. See my PR.

**Comment by amiramw** [comment]
@akosyakov can this issue be closed?

**Comment by akosyakov** [comment]
yes, resolved by https://github.com/theia-ide/theia/pull/6097 thank you @amiramw
