### ISSUE TITLE
[markers] add problem markers for failed tests

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#6065]
**Description**

Inspired by a feature in WebStorm, I propose that support problem markers for tests failures.
Perhaps using our task system and customized `problemMatchers`, we can use the output of a task to create problem markers in the editor for the location of a test failure.

For example, the feature in WebStorm looks like the following:

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/63951658-247ce180-ca4c-11e9-8131-7520be6d483e.png)

</div>

cc @elaihau do you think it'd be possible?

**Comment by elaihau** [comment]
> I propose that support problem markers for tests failures.

are you referring to tests written with frameworks such as mocha ? 

if so, i think it would be possible.

also i am thinking there might be vscode extensions that do the job already. take [this one](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) for example, from the `Test Explorer` we could easily tell which tests are failing, and it goes to the failed test's log when the test is selected.

maybe we could try it as a plugin in Theia in near future ?

**Comment by akosyakov** [comment]
I think Theia has all capabilities for it already, but it should be done by an external VS Code or Theia extension.

**Comment by vince-fugnitto** [comment]
I'm always unsure about whether features should be implemented internally, by an external extension, or by a plugin but I agree with you both, if the feature already exists (is already implemented somehow), then we should simply use it.
