### ISSUE TITLE
[scm] remove hover background on scm inline actions

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#6075]
**Description**

Remove the hover background on the _scm_ inline actions so it's consistent with other 
views (ex: `search-in-workspace`), and with VSCode.

The hover background gives off a bad UI especially on light themes.

**How to test:**
1. open a workspace under `git` source control (ex: 'theia')
2. update the color theme to the light theme (File > Settings > Change Color Theme)
3. perform some changes on a file
4. open the `scm` widget (View > SCM)
5. highlight over the change and highlight the buttons

_Example_: (highlighting over the `stage changes` button)

<div align='left'>

<img width="272" alt="Screen Shot 2019-08-30 at 1 47 49 PM" src="https://user-images.githubusercontent.com/40359487/64041788-5c5c5580-cb2e-11e9-8c01-50c1852f7f97.png">

</div>

---

cc @akosyakov do we want to align and simply remove the highlighting over the buttons like VSCode and other views?

**Comment by akosyakov** [comment]
@vince-fugnitto do as you think it is better
