### ISSUE TITLE
move Marker, ProblemMarker interfaces under "common"

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#608]
so that they can be used in the backend. They currently reside in the "browser" directory, that we usually mean to be for the frontend's use.

**Comment by svenefftinge** [comment]
Could you outline how and what part should be used from the backend? Is it only about the shape of problem markers?

**Comment by marcdumais-work** [comment]
@svenefftinge Yes, that's it; just so we can create typed marker JSON objects in the backend. We would then send the markers to the frontend and have the frontend extension deal with adding them to the marker manager.

**Comment by svenefftinge** [comment]
Ok, in that case it is much less code that should be moved to common.

**Comment by hexa00** [comment]
Fixed in #610
