### ISSUE TITLE
tabbar tree decorations hang UI with a lot of diagnostics

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#6083]
See to reproduce: https://github.com/theia-ide/theia/pull/6044#issuecomment-525200150

<img width="1395" alt="Screen Shot 2019-09-02 at 15 37 08" src="https://user-images.githubusercontent.com/3082655/64108889-8a909e00-cd97-11e9-80cf-fa785ddacb26.png">

**Comment by akosyakov** [comment]
@vince-fugnitto @fangnx I'm going to redesign API, since it is based right now on captions which cannot be unique. I'm not going to make it as a breaking change, it will be part of 0.10.1 bug fix.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto @fangnx I'm going to redesign API, since it is based right now on captions which cannot be unique. I'm not going to make it as a breaking change, it will be part of 0.10.1 bug fix.

Thank you for taking care of it, and I'm fine with it being a breaking change.
