### ISSUE TITLE
Rerendering of toolbar icons to consider changes in the visibility/enabled when expressions e.g. after click

### ISSUE THREAD

**Issue by corneliusludmann** [theia-ide/theia#6102]
### Description
There are 'when' expressions, that are evaluated in order to decide if a toolbar button should be visible resp. enabled or not (e.g. in VSCode plugins, [see example here](https://github.com/microsoft/vscode-maven/blob/19bde696fca4ec5acc06d68470a4e1d0ee515d70/package.json#L287)). The variables used in the when expressions could change at any time, especially after a click on an icon as in the [Maven VSCode plugin](https://github.com/microsoft/vscode-maven/blob/19bde696fca4ec5acc06d68470a4e1d0ee515d70/package.json#L287). Thus, it's necessary that the toolbar buttons is rerendered in some cases, e.g. after a click. Probably there are other cases that require a rerender as well.

### Reproduction Steps
Add the Maven VSCode plugin and click on the toolbar icons in the Maven widget that change the view (flat/hierarchical). The icon should change immediately after the click but it changes not before moving the mouse courser away and back to the toolbar.
![Peek 2019-09-04 10-20](https://user-images.githubusercontent.com/24960040/64238039-e5dca080-cefd-11e9-94fb-2837b9a3ba0b.gif)

**OS and Theia version:** Tested on #5901 

### See also
* #6082

**Comment by akosyakov** [comment]
resolved by https://github.com/theia-ide/theia/pull/5901
