### ISSUE TITLE
Preference schema validation issue (rust vscode extension)

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#6106]
when the rust extension for vscode is installed you'll see this error:

```
Uncaught Error: schema is invalid: data.properties['rust-client.channel'].type should be equal to one of the allowed values, data.properties['rust-client.channel'].type[1] should be equal to one of the allowed values, data.properties['rust-client.channel'].type should match some schema in anyOf
```

reason: it's reading `['rust-client.channel'].type = ["string", null]` which should be `['rust-client.channel'].type = ["string", "null"]`.

because the resulting schema cannot be compiled, this breaks the update of the [`validateFunction`](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/preferences/preference-contribution.ts#L212-L223) leaving the old version of the `validateFunction` in place. 

any call to the preference service requesting some affected preference key returns with empty result, i.e. preference not found.

**Comment by AlexTugarev** [comment]
cf. https://github.com/rust-lang/rls-vscode/pull/654

**Comment by akosyakov** [comment]
@AlexTugarev please try with https://github.com/theia-ide/theia/pull/6090

**Comment by AlexTugarev** [comment]
@akosyakov the mentioned PR is proposing to not call `schemaProvider.validate` at all. this will effectively disable validation at at all, no? 😕 

otoh, it won't actually solve the issue described ☝️ the `validateFunction` won't be updated once an invalid preference schema is added. I think the underlying issue is that adding the schema and validating are two independent steps.

**Comment by akosyakov** [comment]
> otoh, it won't actually solve the issue described ☝️ the validateFunction won't be updated once an invalid preference schema is added. I think the underlying issue is that adding the schema and validating are two independent steps.

What's the use of a scheme if don't do a validation anymore? I think doing warning check on a scheme is good to catch such issues, don't know why VS Code just swallow it and does not report back to VS Code extension developers. But rather than that we can move validation check to statically typed proxies in order to avoid breaking them and don't check anything in `PreferenceService` implementations to align with VS Code.
