### ISSUE TITLE
[multi-workspace] I cannot add a new folder to my workspace

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#6107]
### Description
 
I do not know if it is a bug or I just do not know how this feature works, but I cannot add a new folder. I set the user scoped `workspace.supportMultiRootWorkspace` to `true`. My workspace `settings.json` does not have the `workspace.supportMultiRootWorkspace` preference configured. The `Add Folder to Workspace...` menu item is not available for me in the explorer.

### Reproduction Steps

![screencast 2019-09-05 08-23-28](https://user-images.githubusercontent.com/1405703/64317276-80e58100-cfb7-11e9-839a-1f300dfa01f2.gif)

**OS and Theia version:**

macOS, `0.10.0-next.24bf9f28`

**Diagnostics:**

**Comment by akosyakov** [comment]
It is indeed working in VS Code through the context menu. As a workaround you should be able to use the quick command or `...` in the toolbar.

**Comment by vince-fugnitto** [comment]
For additional information, the command is not displayed in the context menu of the explorer when a multi-root workspace is present. In the presence of a single-root workspace, the command is visible in the context menu.

Also, if a root is selected, the command is also visible in the context menu.

**Comment by elaihau** [comment]
i had the same issue: https://github.com/theia-ide/theia/issues/5020

**Comment by kittaakos** [comment]
Duplicate of #5020.
