### ISSUE TITLE
false positive error tabbar icon

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#6109]
### Description
![image](https://user-images.githubusercontent.com/10203793/64323901-f4a77e00-cff7-11e9-85f8-ebee2387610f.png)

### Reproduction Steps

- open a ts file
- type some error code
- fix error code
- save file

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 you can disable problem decorators with preferences if it is annoying.

**Comment by vince-fugnitto** [comment]
It used to work correctly, I suspect that the error is from the changes in https://github.com/theia-ide/theia/pull/6044/commits/67a04cba04454b3c77399a5483f2544e204b38af

There are a few problems, for instance:
- tabbars now display `information` severity decorators which seem noisy.
- tabbars display `information` severity decorators at a higher priority than `error` (when an editor has both errors and infos, the infos are displayed in the decorator)
- tabbar decorations are not refreshed when the editor is updated/saved.

**Comment by akosyakov** [comment]
@vince-fugnitto I believe you that it was by my changes, but it used to hang the browser too :) anyway we should a fix now, could you have a look? i can do it after migrating Monaco.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I believe you that it was by my changes, but it used to hang the browser too :) anyway we should a fix now, could you have a look? i can do it after migrating Monaco.

@akosyakov not blaming you at all :) I know the original implementation was problematic and worse if it hangs the browser. I'll see if I can debug as to why when I get the chance.
