### ISSUE TITLE
Debug adapters cannot be fetched

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#6111]
cf. https://github.com/theia-ide/theia/pull/6110#issuecomment-528304473

builds are broken because debug adapter cannot be fetched.

`@theia/java-debug` and `@theia/debug-nodejs` are affected. 
one option is to get rid of them at all and use the vscode extension instead.

**Comment by akosyakov** [comment]
What do we do with theia apps fetching va code extensions? Like go?

What downstream native debug extensions do? Like debugging for cpp?

**Comment by svenefftinge** [comment]
Can we solve those issues where they happen? Generally we should not rely on downloading extensions from the marketplace, so I'd say it's best for those downstream builds to have the required bits checked in or hosted elsewhere. 
For this repository, however, it seems like we could get rid of that code alltogether.

**Comment by akosyakov** [comment]
For time being can we just exclude them from yarn workspaces?

**Comment by svenefftinge** [comment]
ok, will do

**Comment by akosyakov** [comment]
Ok, I’m fine with removing them.

**Comment by akosyakov** [comment]
> Can we solve those issues where they happen? 

I don’t think it is possible because our download script does not allow to set something like auth token for marketplace

**Comment by marcdumais-work** [comment]
> I don’t think it is possible because our download script does not allow to set something like auth token for marketplace

I think anyway that it's against the marketplace license/user agreement to use it from a non-Microsoft product. 

When individual license permits I think we are allowed to make the extensions available from an alternate place, like a GH release. So we could for now add them to one of our repos and download from there. Maybe we can create a new repo, `theia-ide/vscode-extensions` or such for this? 

At least until we have our own public registry.

**Comment by akosyakov** [comment]
> When individual license permits I think we are allowed to make the extensions available from an alternate place, like a GH release. So we could for now add them to one of our repos and download from there. Maybe we can create a new repo, theia-ide/vscode-extensions or such for this?

GitHub is not the best place. They have limited access rate as well. Maybe on some free CDN.

> At least until we have our own public registry.

Having our public registry will be the best.

**Comment by marcdumais-work** [comment]
> GitHub is not the best place. They have limited access rate as well. 

True. If we add GH downloads pass a certain point, it will probably fail even with GH Token. But until we reach that point, it should be ok? 

> Maybe on some free CDN.

Could be ok but harder to manage access rights for everyone who might need to update the extensions there.

**Comment by akosyakov** [comment]
> True. If we add GH downloads pass a certain point, it will probably fail even with GH Token. But until we reach that point, it should be ok?

ok, true, we pass GH token for rigrep everywhere, so probably everybody do the same already
