### ISSUE TITLE
ESLint VS Code extension installation fails

### ISSUE THREAD

**Issue by JonasHelming** [theia-ide/theia#6118]
### Description
When installing the ESLint VS Code extension, "taskDefinitions=>properties" is undefined and scanner-theia fails with TypeError: Cannot convert undefined or null to object
### Reproduction Steps
Install ESLint VS Code plugin

**OS and Theia version:**
Linux and Master

Will provide a fix...

**Comment by kittaakos** [comment]
Closed via https://github.com/theia-ide/theia/pull/6119.

Please reopen if I needed.
