### ISSUE TITLE
VS Code extension - menu when - condition with expression with config doesn't work

### ISSUE THREAD

**Issue by amiramw** [theia-ide/theia#6135]
### Description

When runnign vscode extension that has menu with when expression, the condition with config is ignored.
It should be supproted according to this: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

And it works fine in VS Code.

### Reproduction Steps

- Build vsix out of https://github.com/amiramw/vscode-config-when
- Load the vsix
- Disable setting editor.minimap.enabled
- Context menu on some file with suffix .workflow still shows Open Workflow Editor command even though the expression in package.json is `resourceFilename =~ /.+.workflow/ && config.editor.minimap.enabled != true`

This scenario works fine in VS Code.

**OS and Theia version:**
All

**Diagnostics:** 
N/A

**Comment by akosyakov** [comment]
@amiramw Could you please try against https://github.com/theia-ide/theia/pull/5901? We had the similar issue https://github.com/theia-ide/theia/issues/6102 and it seems to be resolved by #5901

**Comment by amiramw** [comment]
yes. it is resolved by #5901

**Comment by akosyakov** [comment]
resolved by https://github.com/theia-ide/theia/pull/5901
