### ISSUE TITLE
Folder Plugin not Working in Theia Build Local with Plugins of VS Code

### ISSUE THREAD

**Issue by Daniel-Dos** [theia-ide/theia#6136]
### Description
I have been using theia doing my own build.
and following this tutorial to use vs code plugin

https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

It doesn't work when I add the plugins in the folder.

only work when I use this command when theia is running

"1Alternatively, you can use the command "Deploy plugin by id" from the command palette. When asked for a parameter, enter the following: vscode:extension/<exension id>. "<extension id>" stands for the "Unique Identifier" from the extension homepage in the VS Code Marketplace."

but when leaving theia and restarting the plugins are not loaded and I have to do the same process again

### Reproduction Steps
 - 1 - download any extension 
 -  2 - create folder plugins and add your extension
 -  3- start theia and click in view > plugins with message :  
    
![plguin](https://user-images.githubusercontent.com/8139890/64494280-3b4be100-d261-11e9-8fd1-ce9b5ae93576.png)

-  4 - in Deploy plugin by id >  vscode:extension/<exension id> works 

- 5 - close Theia and start again , is not loader plugin . 

he not saved the plugins

**OS and Theia version:**
all

**Diagnostics:** 
N/A

**Comment by vince-fugnitto** [comment]
For additional information, what VSCode extension did you use when testing?
Can you include the logs when running the application?

**Comment by Daniel-Dos** [comment]
here the folder with extensions that use .

![pluginList](https://user-images.githubusercontent.com/8139890/64495794-f16cf600-d274-11e9-8ed0-5293fa82f967.png)

and with Theia in start 

![theia](https://user-images.githubusercontent.com/8139890/64495825-021d6c00-d275-11e9-83ae-39ac1523fec9.png)

now , if add any extension for example : vscode:extension/redhat.java

![new](https://user-images.githubusercontent.com/8139890/64495876-617b7c00-d275-11e9-9f1e-6fa0ba0e1c8b.png)

**Comment by vince-fugnitto** [comment]
@Daniel-Dos 
I tested it out myself and it works correctly:
I followed the following steps:
1. build Theia from sources
2. create a `plugin` directory at the root of the project
3. download a VSCode extension (`.vsix` file) - in my case the [`gitignore`](https://marketplace.visualstudio.com/items?itemName=codezombiech.gitignore) extension
4. start the application:

```bash
$ (cd examples/browser/ && yarn start)
yarn run v1.12.3
$ theia start --plugins=local-dir:../../plugins
root INFO Theia app listening on http://localhost:3000.
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler {
     unpackedFolder:
      '/private/var/folders/h2/m_txl3zj69x8nnhqmj03r2000000gn/T/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'codezombiech.gitignore-0.6.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      '/Users/vincentfugnitto/workspace/theia/plugins/codezombiech.gitignore-0.6.0.vsix',
     initPath:
      '/Users/vincentfugnitto/workspace/theia/plugins/codezombiech.gitignore-0.6.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /private/var/folders/h2/m_txl3zj69x8nnhqmj03r2000000gn/T/vscode-unpacked/codezombiech.gitignore-0.6.0.vsix
root INFO Resolved "codezombiech.gitignore-0.6.0.vsix" to a VS Code extension "gitignore@0.6.0" with engines: { vscode: '^1.18.0' }
``` 

I see that the extension is loaded:

<div align='center'>

<img width="1259" alt="Screen Shot 2019-09-08 at 7 13 40 PM" src="https://user-images.githubusercontent.com/40359487/64495889-40169200-d26d-11e9-8693-41631c43b244.png">


</div>

**Comment by vince-fugnitto** [comment]
> here the folder with extensions that use .
> 
> ![pluginList](https://user-images.githubusercontent.com/8139890/64495794-f16cf600-d274-11e9-8ed0-5293fa82f967.png)
> 
> and with Theia in start
> 
> ![theia](https://user-images.githubusercontent.com/8139890/64495825-021d6c00-d275-11e9-83ae-39ac1523fec9.png)
> 
> now , if add any extension for example : vscode:extension/redhat.java
> 
> ![new](https://user-images.githubusercontent.com/8139890/64495876-617b7c00-d275-11e9-9f1e-6fa0ba0e1c8b.png)

Where do you place your plugins?
From the logs I can see that they are not being loaded.

**Comment by Daniel-Dos** [comment]
I put the plugins in a plugin folder along with theia build files

![folder](https://user-images.githubusercontent.com/8139890/64495981-83c1c980-d276-11e9-9041-9940d7a6893f.png)

**Comment by vince-fugnitto** [comment]
> I put the plugins in a plugin folder along with theia build files
> 
> ![folder](https://user-images.githubusercontent.com/8139890/64495981-83c1c980-d276-11e9-9041-9940d7a6893f.png)

I assume you're running on docker, and that you've built your own ide?
You haven't built the application from sources (the main repository) as described in the first step of the guide?

**Comment by Daniel-Dos** [comment]
'm not climbing the docker,

I built the IDE itself as per this documentation 

https://www.theia-ide.org/docs/composing_applications

"Build your own IDE"

**Comment by vince-fugnitto** [comment]
> 'm not climbing the docker,
> 
> I built the IDE itself as per this documentation
> 
> https://www.theia-ide.org/docs/composing_applications
> 
> "Build your own IDE"

I see, the [guide](https://user-images.githubusercontent.com/8139890/64495981-83c1c980-d276-11e9-9041-9940d7a6893f.png) you initially [mentioned](https://github.com/theia-ide/theia/issues/6136#issue-490805156) is mainly for testing purposes. The first step in the guide describes building the application from sources. This means cloning the `theia` repository and building it, not composing an application.

**Comment by Daniel-Dos** [comment]
hi @vince-fugnitto ,

now work .
thanks .

**Comment by vince-fugnitto** [comment]
> hi @vince-fugnitto ,
> 
> now work .
> thanks .

Great! I'm glad :)
