### ISSUE TITLE
focus `Open workspace` button in the navigator on activation

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#6140]
<img width="1552" alt="Screen Shot 2019-09-09 at 12 10 53" src="https://user-images.githubusercontent.com/3082655/64510184-f70d1f00-d2fa-11e9-88e9-586787f91165.png">

Right now the root node is selected, which is not very useful. One even cannot use `tab` to give a focus to the button. Is it a button at all?

**Comment by akosyakov** [comment]
Also `...` -> `Auto Reveal` does not make sense in this context.

**Comment by kpge** [comment]
I think it's necessary to show the focus effect in navigator when the workspace is empty, because this can show user the navigator is focused, and press `tab` can select the button.
I will create a PR to fix other suggestion.

**Comment by akosyakov** [comment]
> I think it's necessary to show the focus effect in navigator when the workspace is empty, because this can show user the navigator is focused, and press tab can select the button.

Tab does not seem to select the button.
