### ISSUE TITLE
[proposal][question] Can we rename the Theia debug adapters when moving them out from the repository?

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#6154]
### Description
 

We discussed during our weekly call, the debug adapters (or at least the Java one) should go into its own repository.

Question: Can we consolidate the name of the debug adapter extensions?
Currently, we have `@theia/debug-nodejs` and `@theia/java-debug`. It would be great to have either `@theia/debug-yourLanguage` or `@theia/yourLanguage-debug`.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
I thought we discussed to delete them and replace with VS Code extensions in example apps?

**Comment by kittaakos** [comment]
> discussed to delete them

My understanding was different, but I am more than happy with the deletion. I guess we delete Java.

I am closing this.
