### ISSUE TITLE
Tabs in the side bar are shown in the reverse order

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#618]

**Comment by akosyakov** [comment]
will be fixed in https://github.com/theia-ide/theia/pull/391

**Comment by akosyakov** [comment]
@svenefftinge I think we need a way to reload clean, without reading from the local storage. Otherwise, it is impossible to get rid of the current state. It gets persisted again on the reload even if the local storage was cleaned.

**Comment by svenefftinge** [comment]
Long term, I'd like to allow opening and closing widgets in the sidebars and moving them. With that, this issue would go away automatically.

**Comment by hexa00** [comment]
Could be nice however to have the option to really clear things like: Clear workspace command from the command palette ?

It does happen that I just want to close everything and get back to a clean state.

**Comment by svenefftinge** [comment]
Is that not a 'close all' command?

**Comment by svenefftinge** [comment]
If we want to have a command that removes the layout information, we'd need to do a reload where we suppress storing the layout information, because that information is only present between unload and load.

**Comment by hexa00** [comment]
Yes well there's:

   - Close all editors
   - Close all widgets

If we close all of these won't we defacto clear the layout too ?

Like you planned to allow in the long term ?

In my
