### ISSUE TITLE
@theia/markers is mandatory

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#619]
If you omit `@theia-marker` as a dependency in a Theia app's `package.json`, you will get a runtime error:
```
contribution-provider.ts:31 Error: No matching bindings found for serviceIdentifier: ProblemManager
```
in the log. Is that the expected behavior?

**Comment by akosyakov** [comment]
It is a dup of https://github.com/theia-ide/theia/issues/369. Modules of transitive dependencies are not taken into the account right now. It will be fixed with https://github.com/theia-ide/theia/pull/391.

**Comment by JanKoehnlein** [comment]
Thanks. Closing as duplicate
