### ISSUE TITLE
[git] Support sign off option for commits

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#620]
ATM we require this for Theia submissions, so we might consider having the option present in our UI.

w-a: manually add the sign-off message as extended commit text

**Comment by akosyakov** [comment]
It would be nice to have it in the more drop down as in VS Code:
<img width="208" alt="screen shot 2018-03-06 at 08 01 59" src="https://user-images.githubusercontent.com/3082655/37018448-b3d95968-2114-11e8-9a37-d6e7dab925fc.png">
