### ISSUE TITLE
[git] Check why tests occasionally timeout and fail on Travis CI

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#627]
Maybe we just have to increase the default timeout.
Could be other problems too, so the promise cannot be resolved within 2 seconds.

**Comment by hexa00** [comment]
Tests using external programs or the file system could be delcared -slow and use 10sec timeout or something.

I do that for the Process tests

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/629
