### ISSUE TITLE
[git][ui] A long Git repository name truncates the toolbar item from the tab

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#640]
See attached image:

<img width="285" alt="screen shot 2017-10-13 at 17 09 10" src="https://user-images.githubusercontent.com/1405703/31553019-61ea910e-b039-11e7-9f1a-800affb95a13.png">

**Comment by marcdumais-work** [comment]
@jbicker I think you are working on git extension improvements. If you are not working on this particular issue here, we could attempt to tackle it. Please advise.

**Comment by svenefftinge** [comment]
The plan is to remove the combobox in favor of #1091
