### ISSUE TITLE
[ui] Odd selection when using the tree navigator in the WS root selector dialog

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#649]
See attached gif:
![theia_tree_navigator](https://user-images.githubusercontent.com/1405703/31652502-a1f5dc34-b31f-11e7-8344-72f7f1ad85c7.gif)

**Comment by kittaakos** [comment]
This problem only occurs when I click on the ?expand? placeholder-widget, and works correctly, when I selected the file name.

**Comment by jbicker** [comment]
fixed in https://github.com/theia-ide/theia/pull/655
