### ISSUE TITLE
[ui] Horizontal scroll  not visible

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#652]
When opening a file in the editor, the horizontal scroll should be visible with the same size as the vertical scroll

**Comment by spoenemann** [comment]
I don't see any problem there. Is it fixed in the meantime, or does it still occur for certain browsers?

**Comment by lmcbout** [comment]
@spoenemann  Just tested as well with the latest code on master, the horizontal scroll is visible.
We should close this PR now.

One question: Why do we show the vertical scroll bar when the code in the file is shorter than he view area. The vertical scroll let us scroll to show only the last line. Should we allow that or the vertical scroll should be "as-needed", meaning only visible when the code has more lines than the visible area ?

**Comment by spoenemann** [comment]
> One question: Why do we show the vertical scroll bar when the code in the file is shorter than he view area. The vertical scroll let us scroll to show only the last line. Should we allow that or the vertical scroll should be "as-needed", meaning only visible when the code has more lines than the visible area ?

That's a standard behavior of Monaco. It's the same in VS Code.

**Comment by lmcbout** [comment]
Works finein Firefox and Chrome, oso lets close this issue.
