### ISSUE TITLE
Support recently open workspaces

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#656]
See Later points of #603

**Comment by marcdumais-work** [comment]
from #1985 : 
@svenefftinge 
> This would not be useful in a cloud context, as that would be the responsibility of the workspace server.

I imagine that we might add one menu item in the ```File``` menu, something like ```Open Recent Workspace```, that would contain an ordered list of recent workspaces. Although probably not very useful in a cloud context, would this be undesirable? 

If so, for such cases, could we have an extension that provides such misc features/enhancements that are only useful for the deskop context? This way it would be easy not to include that extension when building a Theia for other contexts? However a single such extension could get crowded and deal with separate, diverse bits that should maybe not be together... 

Any alternative ideas on how to gracefully handle cases where a feature is applicable for an important subset of Theia use-cases, but undesirable for others?
