### ISSUE TITLE
Opening a workspace reloads theia

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#661]
When you open a workspace in the navigator, Theia reloads calling localhost:3000 

Thus losing all state in the frontend.

**Comment by hexa00** [comment]
Looking more into it this comes from workspace-service.ts:

```typescript
 protected async doOpen(uri: URI, options?: WorkspaceInput): Promise<void> {
+        const rootUri = uri.toString();
+        const valid = await this.isValidRoot(rootUri);
+        if (valid) {
+            // The same window has to be preserved too (instead of opening a new one), if the workspace root is not yet available and we are setting it for the first time.
+            const preserveWindow = !(await this.tryRoot);
+            await this.server.setRoot(rootUri);
+            this.openWindow(uri, Object.assign(options || {}, { preserveWindow }));
+            return;
+        }
+        throw new Error(`Invalid workspace root URI. Expected an existing directory location. URI: ${rootUri}.`);
+    }
```

Why do we need to reload the window ?

And if so we should restore the layout especially if there was no workspace there before.

**Comment by svenefftinge** [comment]
We restore layout on a per workspace basis and reload the frontend when the workspace root changes. Both are intended and work as designed. What is the issue?

**Comment by hexa00** [comment]
If you start a terminal or open a file with no workspace then open a workspace you lose your teriminal and opened file.

**Comment by akosyakov** [comment]
Maybe we just should not reuse the window but opens a new one as usual.

**Comment by hexa00** [comment]
Note i still don't get the relationship between the window and the workspace if anyone cares to elaborate ?

**Comment by akosyakov** [comment]
it is one to one, you cannot change the workspace, only open a new in another window

**Comment by hexa00** [comment]
Why ? I think we should look ahead with what vscode is doing with multi workspaces all we need is ui widgets to listen on a work space change event no ?

**Comment by akosyakov** [comment]
> Why ? I think we should look ahead with what vscode is doing with multi workspaces all we need is ui widgets to listen on a work space change event no ?

At some point in time probably yes, right now it will be a big effort. VS code took couples month to implement it. Before it was the same behavior: one workspace one window.

**Comment by hexa00** [comment]
My point is that vscode took a lot of time because of the refactor involved. But in our case that may not be an issue. And we may do well to avoid having to do a refactor like that int the future.

So while we may not support multi workspace now I don't see why the infrastructure for theia could be made with this in mind.

So my original question still stands what is the relationship between the window and the workspace ? Why is it there ?

**Comment by svenefftinge** [comment]
Having different workspaces is the reason why I want to open multiple Theia apps. That's why there is the relationship.

**Comment by hexa00** [comment]
Isn't it the opposite since there is a relationship we need to open multiple theia apps ?
Or we do not need do do that ? And we could choose to keep the same window ?

Seems that as it is now we do not open multiple apps we just reload for no reason ?

Also this may be a good idea if you open a new workspace, but if you had no workspace and open a once I don't think we should open a new app. WDYT ?

**Comment by akosyakov** [comment]
> Seems that as it is now we do not open multiple apps we just reload for no reason ?

Try to open a folder in an already opened workspace. In this case, you will get a new window.

**Comment by hexa00** [comment]
I do not, nothing happens and I have to manually reload for the change to take effect. At least in the browser example.

**Comment by hexa00** [comment]
See also #662 about this.

**Comment by akosyakov** [comment]
Then it is a bug it used to work.

**Comment by hexa00** [comment]
OK. 

So when we open a workspace we should:
 - Open a new workspace (To be handled in #662)
  
  But when we open the first workspace should we not keep the current layout if any ?

  And thus there is no reason to reload on in this case?

**Comment by akosyakov** [comment]
It complicates the logic, i.e. frontend code should listen to the workspace root changes and react. The reason is to keep it simple.

We could make it even simpler and always open a new window regardless whether a workspace was before. It should solve your issue to preserve the layout.

**Comment by hexa00** [comment]
>We could make it even simpler and always open a new window regardless whether a workspace was opened before. It should solve your issue to preserve the layout.

That would feel weird however since just opening theia and clicking open would open a new one.

I suggest the workaround for now would be to warn the user. WDTY?

**Comment by hexa00** [comment]
In the long run however thinking about multi-workspace I think we just consider having frontend code react to workspace root changes.

**Comment by svenefftinge** [comment]
Please, explain why. Both Atom and Vs Code do it like that, too. I don't see a usecase to change the workspace root without opening a new window or reloading.

**Comment by svenefftinge** [comment]
Also, let's keep multiple root directories for one workspace different from multiple workspaces. 
A workspace really is meant to be the place a user works in for a specific scope. We should restore layout for that no matter it has multiple roots or not. And, yes, when we allow multiple roots, we should allow adding and removing them to the current workspace, which should not change the layout or any other frontend state as much as possible.

For the case that no workspace or file has been specified to open, I still don't understand the use case, in which a user would first create state (opening terminals and files), then at a later point decide to open a workspace and expect to keep the state from before.

**Comment by hexa00** [comment]
For multi-root/ workspace:

  My point is that if we're going to allow multi-root we need to make sure that what is now the workspaceRoot can be changed.  Thus components need to react to this change. 

 And if we do design this this way we will be able to support:

   - Multi-root
   - Whatever window behavior we want, (new window/ replace the windows/ don't replace and just add a directory in the workspace)
 
 However if we don't design it like that and make it so that we have a direct relationship between the window and the workspaceRoot.  We can only support:

 - One workspace root
 - New windows for any new workspace root

So while I agree that it simplifies the code now.  I think it complicates things a lot more for the future. And that we should think about this more ?

For the case of no workspace, Theia is unique from other ides/editors in that it has a backend/frontend design.  And I've seen interest by many people to use it as an editor for sysadmin like tasks like opening a config file on a remote server or things like that. 

It could also be used as a an editor while using git commands for example git commit could bring up theia.

So some people may use it without a workspace and I think we should support that.

Now about keeping the state, I think in general we should not clear state without any warning to the user in any scenario.

The last thing a user wants is to lose some data or whatever he was doing before.

**Comment by svenefftinge** [comment]
We have a direct relation ship between "window and workspace". While atm a workspace can only have one root, we can for sure allow multiple roots for a single! workspace in future.

**Comment by svenefftinge** [comment]
> Now about keeping the state, I think in general we should not clear state without any warning to the user in any scenario.

I did not say we should lose state. The state is just associated to another context (no workspace context). The whole point is to use a 'workspace' as a scope for a certain workbench state, such that I get the context I was in back when I reopen a previously used WS. 

So when you initially open without a workspace and create state we keep it in that context, such that when the sysadmin comes back to 'no workspace' she will find the same context.

**Comment by hexa00** [comment]
>For the case that no workspace or file has been specified to open, I still don't understand the use case, in which a user would first create state (opening terminals and files), then at a later point decide to open a workspace and expect to keep the state from before.

>So when you initially open without a workspace and create state we keep it in that context, such that when the sysadmin comes back to 'no workspace' she will find the same context.

These 2 for me are contradictory ? But I like the later.

So opening a workspace from no-workspace context would open a new window correct ?

**Comment by kittaakos** [comment]
As part of the #838, we discussed the followings:

 - When the WS root **is not set** and the user selects one with the `Open...`, we **reload** the current window.
 - When the WS root **is set**, selecting a new one with the `Open...` will **open** a new window.

Both apply to electron and browser.

**Comment by kittaakos** [comment]
There is one significant difference between the WS root opening behavior in VSCode and Theia: VSCode does not open a new window when the user opens a new WS.

**Comment by hexa00** [comment]
>When the WS root is not set and the user selects one with the Open..., we reload the current window.

My only problem with that is losing the no-workspace state... is it saved like the workspaces states are saved on close?

**Comment by svenefftinge** [comment]
Yes, I added a special prefix for that. You can verify by reloading a browser in that context.

**Comment by hexa00** [comment]
OK closing this
