### ISSUE TITLE
[terminal][windows] As a developer I would like to use another terminal than `cmd.exe`

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#664]
Currently, it is hard-coded. It should be configurable.
See how VSCode does that: https://stackoverflow.com/questions/42606837/how-to-use-bash-on-windows-from-visual-studio-code-integrated-terminal

**Comment by hexa00** [comment]
+1 , Also is there a $SHELL env var enquivalent on windows ? We could not that too.

Note that if we add a preference for this we could make it so that it works with linux/osx too.

**Comment by hexa00** [comment]
Btw should we document that somewhere ? maybe in the terminal package Readme ?
