### ISSUE TITLE
[ui] inconsistent behaviour after selecting File menu option

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#668]
Initially: top menu "File"-> open ==> propose to "Open..." only a dialog with the same content as the side menu "Files" -> open workspace until a workspace/file is opened.
After you open a file, the top menu "Files" has three items ("New File, New Folder, Open...) why those menu items are not available initially ???

~~Second, If you select "New File", then it create a new file at the same location as the first file was opened from. If you select again "Open..." with a different location, create "New File" will now
create the new file where you select the second time.
It becomes very hard to find where you created each file since they get created in different folder depending whats was opened just before.
A suggestion would be to let the user selects the root folder where he wants to create a new File/Folder~~(moved to #683)

**Comment by hexa00** [comment]
Please split First and Second into 2 issues they are different.

**Comment by svenefftinge** [comment]
I can no longer reproduce the lack of items in the file menu. What I tried:
 - open without workspace
 - first action click on file menu:
<img width="286" alt="screen shot 2017-11-19 at 15 44 45" src="https://user-images.githubusercontent.com/372735/32991689-a260667c-cd40-11e7-9171-2430cd8a2288.png">

 - opening a workspace
 - first action click on file menu:
<img width="256" alt="screen shot 2017-11-19 at 15 44 56" src="https://user-images.githubusercontent.com/372735/32991692-af4b8d26-cd40-11e7-9b8f-b0c489d7f5a5.png">


Please reopen if I missed something.
