### ISSUE TITLE
[ui] Paste command definition

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#669]
Please use the browser's paste command or shortcut"  WHY  are we using the web "Paste" and not the THEIA command?

Second,
if we define the command "Paste" under the "Edit" menu ad we cannot use it, what is the purpose or defining it there ?

**Comment by lmcbout** [comment]
Select EDIT-> Paste  before having a workspace --> A dialogue appears "Please use the browser's paste command or shortcut"  --> Dialog remains forever on the screen. Solution, need to click on the dialog to make it goes away, If the user click anywhere else, it stays.

**Comment by hexa00** [comment]
Maybe we could have a little X in there to help the user figure out that he needs to click it to make it go away ?

**Comment by svenefftinge** [comment]
> Maybe we could have a little X in there to help the user figure out that he needs to click it to make it go away ?

I added a note to #185.

For the message, we chose to display a message to guide the user about this limitation. It is just not possible to access the clipboard from within a browser otherwise.
