### ISSUE TITLE
Developer documentation and issues

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#67]
As we spoke during the meeting, we should document (and improve if possible) the preferred development workflow.  I'm sure there are a lot of tricks to be more efficient that you guys use.

Right now I just run `cold:web:start` after doing changes to the backend.  Is there a more streamlined process for backend changes?

A major pain point is the strictness of the linting during development.  If I have a trailing whitespace or unused import (which happens regularly when developing) it's not possible to start the application.  The linting should be strict during CI (including when testing PR eventually), but I think it shouldn't be as strict during development (e.g. give warnings instead of errors).

**Comment by hexa00** [comment]
Closing this one.

We now have Developing.md and Internals.md 

Specific issues can be dealt with with their own issue.
