### ISSUE TITLE
[ui] workspace loosing focus on the expanded folder

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#672]
Open a workspace in theia: (a workspace having many folders (ex:Home folder))

Scroll and Expand a sub-folder --> focus  move on top of the workspace, so we don't see the expanded folder information,  need to use the scroll down to go back to the expanded folder.

**Comment by hexa00** [comment]
@lmcbout is this what you see: https://github.com/theia-ide/theia/issues/649

Looks like a duplicate and it's fixed now too.

Could you retest ?

**Comment by lmcbout** [comment]
Exactly, tested with the latest changes and has been fixed with #649
