### ISSUE TITLE
[ui] [enhancement] Open a file using double-click

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#673]
Double-click on a file in the workspace does not open it in the THEIA editor.

**Comment by akosyakov** [comment]
It should work already.

**Comment by lmcbout** [comment]
Select a file in the outside folder of THEIA (Home folder in UNIX), select, DRAP and DROP it in the  THEIA workspace EDITOR section --> THEIA goes away and is replace by a web editor with the URI of the file to open  instead of opening the file as a new file on THEIA editor.
2 options to consider:
- Should not replace the THEA URI application.  If the "Drag and Drop" use the web application , it should create a new tab on the web and open the file there
- If the user "Drop" his selection inside THEIA "Editor" section, it should open the file as a new file in THEIA application.

**Comment by lmcbout** [comment]
OK, seems it was caused by another issue (issue #671) , when I use my home folder as the workspace and theia was looping in the background that I did not notice at that time.
