### ISSUE TITLE
[ui] Drag & Drop data between 2 files

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#676]
Drag and Drop
Open two files, select some code in a file, use the mouse left button  and DRAG it to the next file and try to DROP it -> nothing happen

**Comment by epatpol** [comment]
Correct me if I'm wrong but I think VScode doesn't do anything either. What should it do? A copy/paste of the content or a cut/paste?

**Comment by hexa00** [comment]
I'm not sure we need to do this at all...

**Comment by vince-fugnitto** [comment]
Not sure why we need to have this functionality, other editors such as `vscode` do not do this as well.
The same can and should be achieved by **copy + paste**.
