### ISSUE TITLE
[ui] Inconsistency in menu "Selection"

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#679]
Initially, the Top menu "Selection" is empty until you have a workspace. After, if there is no opened file, all menu options are grayed out. 
2 options:
  - Why those options are not grayed out when there is no workspace ??
  - Why not hiding the menu until you have a workspace?

**Comment by hexa00** [comment]
Note that this would make sense if you have a file opened and still no workspace...

So it should depend on having the first editor.

**Comment by svenefftinge** [comment]
The selection menu is no more empty but disabled if no editor is active.
