### ISSUE TITLE
[ui] Using File menu "New File " creates a file in a location hard to find

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#683]
If you select "New File", then it create a new file at the same location as the first file was opened from. If you select again "Open..." with a different location, create "New File" will now
create the new file where you select the second time.
It becomes very hard to find where you created each file since they get created in different folder depending whats was opened just before.
A suggestion would be to let the user selects the root folder where he wants to create a new File/Folder (was initially in issue#668)

**Comment by kittaakos** [comment]
> I'm not sure that the implementation is confusing at the moment:

I second this. The behavior is the same as in VS Code.

Please reopen if needed.
