### ISSUE TITLE
[ui] Folder expand/un-expand when clicking anywhere in the navigator area

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#684]
In THEIA folder section, if I left click  in an empty area, it expand/un-expand the folder. Is it the desired behaviour ?

I would expect it if I select on a folder to expand/un-expand, but anywhere in the navigator area!

**Comment by jbicker** [comment]
I would say that it is desired. 
I suggest to enhance the behaviour by 
a) changing the background of a certain tree row if we hover it and 
b) change the mouse cursor to pointer just to make clear that you are on a clickable element.

**Comment by jbicker** [comment]
https://github.com/theia-ide/theia/pull/834

**Comment by svenefftinge** [comment]
#834 was merged
