### ISSUE TITLE
[ui][workspace] Open workspace select wrong folder

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#691]
when a workspace is opened, select File-> Open... allows you to open a parent of the current workspace, no other workspace are available to be opened, so I cannot select what I am looking for.
In the tree list, the top folder should be my current workspace. To select the parent folder or any other workspace, it should be done from the top selection of folder.
To explain my previous comment,
Check the video.
1- select a sub-sub folder as a workspace
2- Use open again to select another workspace: the parent folder is selected  in the tree list. In fact,  it should show the current workspace and the user would  need to select the parent folder on top of it, not inside the tree list.

![](https://user-images.githubusercontent.com/419051/31789424-145cc2bc-b4e0-11e7-858e-0e1b35ea34d2.gif)

**Comment by svenefftinge** [comment]
Not sure I understand. Are you saying we should not show the current workspace's parent folder in the dialog, but the workspace root itself?

It is done intentionally because many people put their workspaces into a single directory. OTOH, when you want to switch the workspace, you most likely don't want to go to a child of your current WS.

**Comment by hexa00** [comment]
This was surprising to me too I was expecting the current workspace directory.

The thing that is different from vscode for example here I think is that in theia there's only File->Open for now and no File-Open directory.

So if you plan to open a file it sure looks weird to get the workspace parent!

But if you open a directory while I find that weird it may be ok to open the parent.

Maybe we should have Open->File and Open->Directory ?

**Comment by svenefftinge** [comment]
Ok, then we might need to change the command's label, since opening files within the current workspace should be done through navigator or `CTRL+P`.

**Comment by svenefftinge** [comment]
That said in VS Code it seems to be exactly the same.

**Comment by hexa00** [comment]
For me in vscode Open File starts at the directory of the currently opened editor.
While Open Directory starts at the workspace parent...

Not sure what mean but it's the same...

**Comment by svenefftinge** [comment]
I only see `File -> Open ...` in the main menu bar. 
And it starts with the WS parent dir.

![open_file](https://user-images.githubusercontent.com/372735/32538169-693a5814-c465-11e7-8abf-8c8dda53f82b.gif)

**Comment by hexa00** [comment]
So strange what version are you on ?

Here's what I see:
![openfile-vscode](https://user-images.githubusercontent.com/698076/32559902-486fc130-c476-11e7-93f1-1fc7d28f35ae.gif)

**Comment by hexa00** [comment]
I'm on 1.17.2

**Comment by svenefftinge** [comment]
I too have 1.17.2 :)

**Comment by hexa00** [comment]
Yes it seems the gtk3 native dialog can't open a directory or a file at the same time.

I'll close this as the behavior is expected.
