### ISSUE TITLE
[ui] Synchronization between the navigator and the editor  is missing

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#711]
Navigating through the open file:  selecting an open file  does not highlight the file in the workspace navigator, seems there is no connection between  them, no listener.
![peek 2017-10-19 highlightfile](https://user-images.githubusercontent.com/419051/31889123-a9616c48-b7cc-11e7-87da-18df04ac2bee.gif)

**Comment by akosyakov** [comment]
It is a dup of https://github.com/theia-ide/theia/issues/227
