### ISSUE TITLE
[ui] Icon missing beside the menu "Code Editor"

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#712]
Menu Files -> Open With -> Code Editor: we should add an icon beside it, so it would look more in synch with the other type of editor "Yarn diagram" option
![peek 2017-10-23 open menuicon](https://user-images.githubusercontent.com/419051/31889420-c37e870e-b7cd-11e7-9522-2389d9e77abb.gif)

**Comment by akosyakov** [comment]
Generally, `iconClass` property should be added `EditorManagerImpl`.

What should be an icon? If it depends on a URI then a type of `OpenHandler.iconClass` should be changed to `string | (uri: URI) => string` and `EditorManagerImpl.iconClass` should be implemented by means of `FileIconProvider`.

**Comment by svenefftinge** [comment]
I think we could also question having an icon for the 'open diagram' in the first place.

**Comment by lmcbout** [comment]
I just notice that the menu item "Open With" have an icon only for the yarn diagram. The others "Open with" from Theia don't have any icons, should we remove the icon for the "Yarn diagram"

**Comment by svenefftinge** [comment]
Closing this as, the icon is not defined within this repository.
