### ISSUE TITLE
[debug mode] Opening a Diagram display traces on the console

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#713]
When opening a diagram , on the console, the "jsonrpc" data structure is displayed, we should put this in a debug level mode, not necessary show it on the console log all the times unless we are in debug mode.

**Comment by kittaakos** [comment]
Did we agree on logging YANG/Sprotty issues in the Theia repository? If no, could you please move this ticket to its proper place?

**Comment by hexa00** [comment]
@lmcbout If it's directly about yang please use its repo.

**Comment by lmcbout** [comment]
issue moved to yangster issue #19
