### ISSUE TITLE
[diagram][edition] Unable to select and move a section of a diagram

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#714]
In the diagram view, there is no edition, we cannot move the content to another location within the diagram, it moves the complete diagram.
![peek 2017-10-23 movingportiondiagram](https://user-images.githubusercontent.com/419051/31889848-36574936-b7cf-11e7-984a-1e767760dfea.gif)

**Comment by kittaakos** [comment]
Does this issue belong to here? Can you move to its own repository?

**Comment by lmcbout** [comment]
Issue moved to yangster  issue #20
