### ISSUE TITLE
Use icons for vertical tabs ? Like Files/Git/Extensions

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#716]
Should we use icons for these ?

It would look nicer and take less space.

**Comment by spoenemann** [comment]
I already prepared the CSS and TS code to enable this. Using icons in the side bars can be enabled by changing the `display` property in this block of `sidepanel.css`:

```
.p-TabBar.theia-app-sides .p-TabBar-tabIcon,
.p-TabBar.theia-app-sides .p-TabBar-tabCloseIcon {
  display: none;
}
```

Of course that makes sense only if the widgets have icons. Currently _Files_, _Git_ and _Extensions_ have no icon.
