### ISSUE TITLE
Manage file modifications outside of theia

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#717]
These include:

   File modifications: Contents have changed, (Show diff or prompt for reload etc..)
   Deleted file: See #560

**Comment by svenefftinge** [comment]
Could you elaborate what you mean? What is outside of theia?

**Comment by hexa00** [comment]
I mean like if an other process changes files that theia is watching like git or the user with command line commands like rm.

**Comment by svenefftinge** [comment]
But we have the file watching on the opened workspace, so that generally is managed. 
There might be clients like the editor manager that doesn't react on that, though. 
But what is this ticket about? What should be done here?

**Comment by hexa00** [comment]
Sorry I guess that wasn't clear.

But yes this is about reacting to those changes.

My plan was to break it down in smaller issues and keep this issues as "the discuss this as a whole" one. 

Like what is to be done when a file changes in the editor ? 
When a file is deleted ?

**Comment by hexa00** [comment]
Closing this it's too unclear.
