### ISSUE TITLE
Preview Widget

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#72]
A Preview Widget that is capable of opening files like
 - images 
 - html
 - markdown

and render the outcome. 
The preview widget should rerender on file changes, which should allow for a nice editing experience in splitted mode.
We might want to allow extending it by registering renderers.

**Comment by marcdumais-work** [comment]
A few other examples of file types it would be nice to support: plantuml, rst

**Comment by svenefftinge** [comment]
@akosyakov created a markdown viewer to illustrate the extension system:
https://github.com/theia-ide/theia-extension-example

**Comment by svenefftinge** [comment]
we have the preview facility.
