### ISSUE TITLE
The outline should properly release the reference to monaco model

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#726]
Right it does not do it at all, models are hanging.

**Comment by akosyakov** [comment]
This reference should be released when the editor is closed:
https://github.com/theia-ide/theia/blob/1394b779c774cd83cf43aac852b52fddf49abab6/packages/monaco/src/browser/monaco-outline-contribution.ts#L88

**Comment by akosyakov** [comment]
Also:
- [ ] the outline is not updated if another editor is selected
- [ ] the outline is not disposed if all editors are closed

**Comment by jbicker** [comment]
https://github.com/theia-ide/theia/pull/767

**Comment by svenefftinge** [comment]
the PR was merged
