### ISSUE TITLE
[Outline-view] dependency not added for electron example

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#730]
I noticed that the outline view dependency was added to the browser example but not to the electron example.

**Comment by akosyakov** [comment]
PRs are welcomed. You have to add `"@theia/outline-view": "0.2.0"` after: 
https://github.com/theia-ide/theia/blob/116222a7551917c59107a9288991a1e7e7cbe403/examples/electron/package.json#L20

Similar to: 
https://github.com/theia-ide/theia/blob/116222a7551917c59107a9288991a1e7e7cbe403/examples/browser/package.json#L17-L19

**Comment by hexa00** [comment]
@akosyakov this should have been part of the first PR so it's more a bug that it is not there.

Or you see a reason to change the way we've been working into making the examples different?

**Comment by moondef** [comment]
[PR](https://github.com/theia-ide/theia/pull/805)
