### ISSUE TITLE
Wasted space on the right of the terminal

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#735]
As of 3d1e719169f587299e7e40f18ad643c31d45fdc0, there is some wasted space in the right of the terminal:

![term](https://user-images.githubusercontent.com/1758287/31967368-b5b23512-b8db-11e7-9e88-50b6450247a8.png)

This is most likely due to https://github.com/sourcelair/xterm.js/issues/1081

**Comment by akosyakov** [comment]
I oppositive cannot see the whole output:
![screen shot 2017-10-24 at 23 15 05](https://user-images.githubusercontent.com/3082655/31968418-5376a73a-b911-11e7-967a-fb55846387d6.png)

**Comment by simark** [comment]
Weird, I don't know what happens in your case.

**Comment by simark** [comment]
We tried with @MarkZ3 on his Mac, and he sees the same as the rest of us (some wasted space).

**Comment by MarkZ3** [comment]
That wasn't on a "retina" display though.

**Comment by marcdumais-work** [comment]
This issue is fixed by #1022
