### ISSUE TITLE
application-package tests fail after 0.2.0

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#739]
```
@theia/application-package: extension-package

@theia/application-package: isOutdated

@theia/application-package: 1) @theia/core@next

@theia/application-package: ✓ @theia/core@latest (384ms)

@theia/application-package: ✓ @theia/core@0.1.0 (369ms)

@theia/application-package: 2 passing (2s)

@theia/application-package: 1 failing

@theia/application-package: 1) extension-package isOutdated @theia/core@next:

@theia/application-package: AssertionError [ERR_ASSERTION]: false == true

@theia/application-package: + expected - actual

@theia/application-package: -false

@theia/application-package: +true

@theia/application-package:

@theia/application-package: at Object.<anonymous> (src/extension-package.spec.ts:20:16)

@theia/application-package: at step (src/extension-package.spec.ts:38:23)

@theia/application-package: at Object.next (src/extension-package.spec.ts:19:53)

@theia/application-package: at fulfilled (src/extension-package.spec.ts:10:58)

@theia/application-package: at <anonymous>

@theia/application-package: at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by hexa00** [comment]
^^ @akosyakov

**Comment by kittaakos** [comment]
I will try to resolve this.

**Comment by kittaakos** [comment]
PR: #740.

**Comment by hexa00** [comment]
Could you explain what is going on here ? 
I don't understand how next is outdated compared to 0.2.0 ?

If publish is == next I guess I would get it.. so next commit should work without any change?

**Comment by hexa00** [comment]
I think since the test fail if publish === next we don't run the deloy stage in travis and thus we don't publish a new next and we're then stuck there.

We need to fix a proper fix for this otherwise each time we publish we will get into this situation

**Comment by kittaakos** [comment]
I cannot see a 0.2.0.next version after 0.2.0
```
     '0.2.0-next.01d56da4': '2017-10-24T11:35:17.464Z',
     '0.2.0-next.1394b779': '2017-10-24T11:58:49.517Z',
     '0.2.0-next.3d1e7191': '2017-10-24T20:54:04.048Z',
     '0.2.0': '2017-10-24T21:43:36.231Z' },
  homepage: 'https://github.com/theia-ide/theia',
  repository: 
   { type: 'git',
     url: 'git+https://github.com/theia-ide/theia.git' },
```

**Comment by kittaakos** [comment]
> We need to fix a proper fix for this otherwise each time we publish we will get into this situation

I do not have more time for this. That's why I came up with this quick fix for now. We can discuss it before releasing a new version, cannot we?

**Comment by hexa00** [comment]
@kittaakos yes most likely because of the situation I mentionned in my previous post...

Also what command do you use to see that? strangly doing a git show theia-core I get version 0.0.1-alpha.2...

**Comment by kittaakos** [comment]
`npm view @theia/core`.

**Comment by kittaakos** [comment]
Or you can try:
```
npm view @theia/core@next version --json
"0.2.0-next.3d1e7191"
npm view @theia/core@latest version --json
"0.2.0"
```

**Comment by hexa00** [comment]
Oops ok right it's @theia/core I guess we should delete theia/core

**Comment by hexa00** [comment]
Yeah so we publish 0.2.0 then the test fails because next === latest.

Deploy doesn't run thus there's no new next. And we're stuck.

I think we need to remove that test or mock the registry.

**Comment by hexa00** [comment]
Actually this fails if we publish something that is greater than next... 
I'm not 100% sure how the latest > next works

**Comment by akosyakov** [comment]
It should be enough to comment out `next` version for now. I will have a look how to fix it later.
