### ISSUE TITLE
Writing extensions

### ISSUE THREAD

**Issue by daveyc123** [theia-ide/theia#744]
Not sure if this is the best place to ask (please point me to a mailing list, irc channel or discussion group if one is available), but after reading the contribution guide it looks like issues are an appropriate place to ask questions.

I'm looking at building an extension to Theia. I'm able to run the steps in the Authoring Extensions.md and get the Hello World menu item to work correctly. I'm modifying the hello world code now, but I'm not sure how to get the changes to be reflected in the build. I can do a yarn in the root of the theia examples directory, but that has no effect.  I tried bumping the version of the hello-world-extension but that just leads to "Couldn't find package "hello-world-extension" on the "npm" registry.".

Any suggestions? What's the process for rebuilding after you've made changes to an extension?

**Comment by hexa00** [comment]
yarn from the root should work.

In general it should be similar to https://github.com/theia-ide/theia/blob/master/doc/Developing.md#rebuilding

Don't forget to restart your example.

You can also ask questions on gitter in #theia

**Comment by hexa00** [comment]
You can also try yarn build from the root and  then yarn build from the browser-app.

**Comment by daveyc123** [comment]
I tried yarn build with no success (returns "Command "build" not found."). Perhaps it is because I'm building from the directory yo setup for me, as opposed to the root of theia directory.

I'll setup gitter and follow up on there. Thanks for the quick reply.

**Comment by hexa00** [comment]
Note this was I think resolved on gitter @daveyc123 can we close ?

**Comment by akosyakov** [comment]
Hello @daveyc123, issues are perfect place to ask questions :)

For developing the browser example run from the root:

    npx lerna run watch --scope=browser-app --include-filtered-dependencies --parallel

For developing the electron example replace `browser-app` with `electron-app`.

This command run `watch` npm script in parallel on local packages matching `--scope` option and its local dependencies, e.g. `browser-app` and your extension. If you change the frontend part just reload the browser or electron window (see `view` menu) to apply changes. If you change the backend you should restart the backend.

**Comment by akosyakov** [comment]
@daveyc123 I've opened an issue to improve docs for the extension development: https://github.com/theia-ide/generator-theia-extension/issues/1. PRs are welcomed.

**Comment by daveyc123** [comment]
Great.  Thanks @akosyakov and @hexa00. Apologies for the delayed reply, I had forgotten that I had all github related content going straight to a different folder instead of my inbox.
