### ISSUE TITLE
Preferences do not support multiple frontends for one backend

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#749]
If you open a new tab with a new workspace the preference server will still use the old workspace. There should be a way for the frontend to tell the backend that a workspace has been set (unless there's another way to do it @svenefftinge @akosyakov)

**Comment by svenefftinge** [comment]
Yes, that's a known issue. Duplicate of #656.

**Comment by hexa00** [comment]
I don't get how this is linked to recently opened workspaces ?

This is more like the user opened a new workspace in new window but still gets the old preferences ?

**Comment by svenefftinge** [comment]
Right, I first understood it differently.

**Comment by marcdumais-work** [comment]
@epatpol is this issue still valid, with your recent changes?

**Comment by epatpol** [comment]
@marcdumais-work thanks for the ping, yes this can be closed as now every frontend has their own preference-service.
