### ISSUE TITLE
[outline] Outline does not get refreshed properly when altering the active editor

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#750]
See the attached gif:
![theia_outline_view_refresh](https://user-images.githubusercontent.com/1405703/32092863-7c751410-bafa-11e7-924c-8ac3f7c6ec8a.gif)

**Comment by akosyakov** [comment]
See https://github.com/theia-ide/theia/issues/726#issuecomment-339120228 as well

**Comment by svenefftinge** [comment]
Is fixed with #767 & #783
