### ISSUE TITLE
[git] Gracefully handle big number of modified files in git repo

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#758]
for example, take the (quite big) GDB git repo 
``` bash
git clone git://sourceware.org/git/binutils-gdb.git
```
and do: 
``` bash
git reset remotes/origin/users/pkoning/multi-target
```
You should be left with ~14000 modified files in the repo.  

Then open it Theia, using the gdb parent directory as workspace root. Notice that Theia is very slow, one node process is using 100% of a CPU. What's going on? Whatever it is, it seems to go on for a long while. 

*** Update: the lock issue below no longer happens ***

~~Also it seems not possible to fix the situation from within Theia: (I assume) the git extension has a lock on the repo, preventing e.g. a "git reset" from the terminal:~~

``` bash
$ git reset --hard
fatal: Unable to create '/opt/ericsson-dev/binutils-gdb/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
~~

**Comment by hexa00** [comment]
I wonder is that a problem even without the git extension ?
(You can dynamically uninstall it to test)

**Comment by marcdumais-work** [comment]
Hummm... hard to say. When I remove the git extension, it still seems to be present (UI still there, performance bad), except for the fact that it appears as installable, under the "extensions" tab. So I think it's not really removed. 

![peek 2017-10-30 09-00](https://user-images.githubusercontent.com/25749063/32172094-d3751172-bd50-11e7-9048-51fafaacc515.gif)

OTOH, if I start with the GDB repo in a nice state (checked-out to master, no modified files) then the performance is ok.

**Comment by hexa00** [comment]
Are you sure you reloaded ?

If I reload the Git tab is gone for me...

**Comment by marcdumais-work** [comment]
Maybe a bug? Here's what it looks like for me, using latest master: 

![peek 2017-10-30 10-26](https://user-images.githubusercontent.com/25749063/32176025-e982c3d6-bd5c-11e7-8f9e-0a895fdeea95.gif)

**Comment by marcdumais-work** [comment]
ok, so when I run Theia by doing "yarn run start" under examples/browser(*) , then I can install/uninstall extensions. In the scenario above, un-installing the git extension fixes the performance issues.

(*) vs starting the theia backend in vscode: when I do, it seems that installing or un-installing extensions is broken. I do not get the notifications telling me that the install is started, and later done and that I need to reload.

**Comment by kittaakos** [comment]
Git lock: https://github.com/Microsoft/vscode/issues/11918?
Performance: #701?

**Comment by marcdumais-work** [comment]
@kittaakos In my case I did not remove node_modules from .gitignore, so I do tot think it's related to #701.

**Comment by kittaakos** [comment]
@marcdumais-work but having too many files marked as new/modified/deleted have the same effect, right? That's what I meant.

**Comment by marcdumais-work** [comment]
@kittaakos yes, I see now: Indeed that seems to have the same effect.

**Comment by marcdumais-work** [comment]
BTW, I noticed the following in vs code, when testing the above by removing node_modules from .gitignore:

![image](https://user-images.githubusercontent.com/25749063/32271418-27e173b0-bed0-11e7-8be0-a35a417f0d0d.png)

So it seems that vs code detects this situation and protects itself? 

It seems that they limit it to showing 5000 changes in theit git view:
![image](https://user-images.githubusercontent.com/25749063/32271480-746a0d3c-bed0-11e7-8367-366a4ea03c25.png)

**Comment by kittaakos** [comment]
I can confirm, they have this feature/workaround.

**Comment by marcdumais-work** [comment]
I have confirmed that this is still an issue. I think there is just a limit to the number of modified files we can handle. We might have to limit that number, like VS Code does, and ignore those over that limit.

**Comment by kittaakos** [comment]
Let's see this with #1101. We made a slight performance improvement regarding the status.

+1 for limiting the change set to a constant. I look into this now.

**Comment by marcdumais-work** [comment]
@kittaakos I will re-test once dugite is updated, thanks for the info!

**Comment by kittaakos** [comment]
Locally, I am down to ~1500-2000 ms for getting the status with 5k item limit. Still, the UI update is slow. It could be the amount of data being serialized, or just the UI itself. I need to continue the investigation.

**Comment by marcdumais-work** [comment]
I just re-tested and the performance, with a lot of modified files, is much better. Thanks @kittaakos

**Comment by kittaakos** [comment]
I am glad you are satisfied with this, but neither the `dugite-extra` performance improvement nor the changeset limiting is on the master. We just fixed an issue with the watchers, so the listeners on the frontend do not receive multiple events for one single Git status change.

**Comment by marcdumais-work** [comment]
Thanks for the update. Somehow the performance impact on my machine has considerably lowered, when replicating the original setup above. It did take a few seconds to display the changes (which should improve with the limit), but the rest of Theia remains responsive.

**Comment by kittaakos** [comment]
> fixed an issue with the watchers

That was already 50% performance improvement in case. There will be more soon. I would propose to keep this issue closed, and one has to open a new one if required.

**Comment by marcdumais-work** [comment]
ok, let's do that.
