### ISSUE TITLE
[filesystem] Remove usage of `sync`-methods

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#762]
@hexa00 pointed out that we should not use any sync methods from fs (or fs-extra) in the backend. Because of the single threaded nature of node, those methods will block the whole server until the filesystem returns.

See also 
 - http://blog.mixu.net/2011/02/01/understanding-the-node-js-event-loop/

**Comment by svenefftinge** [comment]
There might be more usages in other modules, which should be checked, too.

**Comment by marcdumais-work** [comment]
I see that we do use the sync version of some fs functions in "node-filesystem". In getFileStat() / doGetStat(), exists() and doGetChildren() at least.

**Comment by kittaakos** [comment]
`doGetRecursive` is not used anymore. It should be used for `copy`.

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/773
