### ISSUE TITLE
Can't add loaders to generated webpack.config.js

### ISSUE THREAD

**Issue by daveyc123** [theia-ide/theia#766]
The theia dev tools generate a webpack.config.js based on https://github.com/theia-ide/theia/blob/ad1c4ade314d1f0652b7cd1084afe4cae7eac4ae/dev-packages/application-package/src/generator/webpack-generator.ts

Unfortunately, for my extension I need to add an additional webpack loader to support some of the dependencies that I'm using. Since the content of the webpack.config.js is static, I'm unable to do so.

Any suggestions welcome. Thanks.

**Comment by akosyakov** [comment]
You can create your my.webpack.config.js file which spreads the generated one and add another loader, something like:
```js
const genConfig = require('webpack.config.js')
module.exports = {
    ...genConfig,
    module: {
        // add your loader
    }
}
```

And then pass it to the build command:  `npx theia build -c my.webpack.config.js`.

See more about `theia` cli: https://github.com/theia-ide/theia/blob/master/dev-packages/cli/README.md#run

**Comment by akosyakov** [comment]
@daveyc123 Did it help? Can we close it?

**Comment by daveyc123** [comment]
I'm still having trouble with my deps, but it does look like the loader is getting added properly now. Thanks for the help. I ended up using webpack-merge...


const genConfig = require('./webpack.config.js')
const merge = require('webpack-merge');

module.exports = merge.smart({
    module: {
        rules: [
            {
               ...
           }
        ]
    }
}, genConfig);
