### ISSUE TITLE
"Open Problem View" should be "Open Problems View"

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#768]
@spoenemann wrote:
> The view is named "Problems", not "Problem".

**Comment by akosyakov** [comment]
It would be nice to provide steps which should be done for people who create the PR first time on the GitHub.

**Comment by kittaakos** [comment]
Rename the label [here](https://github.com/theia-ide/theia/blob/077f2fec5457a938998a8eb680819cd70b548d8d/packages/markers/src/browser/problem/problem-contribution.ts#L21), submit your PR.
