### ISSUE TITLE
[widget manager] make restoration of a widget optional

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#776]
IIUC, when we use the widget manager to create a widget, it saves the fact that the widget was opened, and attempts to restore the widget, when the Theia session is restored. 

However, in some cases, it may not make sense to restore a given widget. Is there a way to make the save/restoration part optional?

**Comment by svenefftinge** [comment]
We can certainly think about supporting that. 
Could you share the cases you have in mind?

**Comment by marcdumais-work** [comment]
When I create a terminal widget for a task, I do not think it's good to restore it in a subsequent session. In that case, the widget is only used to show the task's output, which is gone when we restore. So we get only an empty terminal being restored.

**Comment by svenefftinge** [comment]
I think it would be awesome if I get the widget for tasks and launches on reload. If they are terminated I could still see the output, if they are still running I see the progress.

**Comment by svenefftinge** [comment]
See also https://github.com/theia-ide/theia/issues/705

**Comment by hexa00** [comment]
@svenefftinge however we may use this api for internal theia tasks like starting a UML preview with plantuml or things like that. 

We will usually use a RawProcess for that but there may be situations where we need to user a TerminalProcess.

I think we should be able to opt-out from the restore.

**Comment by hexa00** [comment]
Moreover the use could be able to configure this...

**Comment by svenefftinge** [comment]
I didn't get the use case. You want to start a terminal process, that opens a terminal. But after reload you no longer want to see it? Why?

**Comment by svenefftinge** [comment]
A use case for not opening a widget after reload is when there is an error in restoring it, because e.g. the underlying resource (TerminalProcess, File) doesn't exist anymore.
But I see that more as error handling rather than a feature to turn off restoration for an entire class of widgets.

**Comment by marcdumais-work** [comment]
TL&DR I think we could side-step the widget manager's lack of selective restoration of widgets, for tasks. 

ATM, we create a new terminal widget for any task that uses a terminal process, as part of the creation of the task. 

An incremental improvement could be to have a new tasks widget, that contains one terminal widget and permits choosing which of the known task(s) is shown in the terminal. I am thinking that it will make more sense to restore the Task widget vs individual task's terminal widgets; it would then be the tasks widget's responsibility to fill itself with the appropriate tasks (i.e. it could always be restored safely). 

@hexa00 We could distinguish between "user-level" tasks and "system-level" tasks: with an appropriate flag for each task, the tasks widget might just show/restore tasks that were user-created. So if a plantuml extension starts a task to render a diagram, the underlying task would be a system task, and probably not shown to the user in the tasks widget (by default?).

**Comment by hexa00** [comment]
This would be like the Output vscode tab...

I think it's a good idea... + the user/system level tasks.

**Comment by svenefftinge** [comment]
Do we have a conclusion here? I really think that refreshing the browser should ideally not alter the state of the application. In that light, the desire to omit state restoration sounds wrong. If the user wants to get rid of state or opened widgets they should close them. Refreshing the browser should not be a way of getting rid of widgets I no longer want to see.

**Comment by hexa00** [comment]
I think we agree, that a more general widget will be managing the tasks output and this will always be restored.

Closing this. @marcdumais-work  reopen if there's something I missed.
