### ISSUE TITLE
[windows] Sub-menus seem to have an empty menu group on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#790]
It seems, that `File`, `Edit`, `Selection,` and `Help` sub-menus start with an _empty_ menu-group on Windows. It is not the case for other sub-menus.
![empty_menu_group_windows](https://user-images.githubusercontent.com/1405703/32484369-d2106106-c39f-11e7-8624-d70cce461685.gif)

(It worths to open the attached gif in its own tab to see the _empty_ groups.)

**Comment by svenefftinge** [comment]
Also `View`should be left to `Help`.

**Comment by kittaakos** [comment]
> Also `View` should be left to `Help`.

That issue exists on OS X too.

<img width="482" alt="screen shot 2017-11-09 at 16 24 01" src="https://user-images.githubusercontent.com/1405703/32613214-94345df2-c56a-11e7-8af8-257caa02c389.png">

**Comment by kittaakos** [comment]
The menu order issue does not occur when starting the electron application in development mode.

**Comment by kittaakos** [comment]
Oh, I think, I know what's the difference: accessing menu item slots by index. It varies based on the existence of the `Diagram` menu item.

**Comment by vince-fugnitto** [comment]
fixed by #3359 and #2608
