### ISSUE TITLE
[workspace] Workspace selection icon is missing

### ISSUE THREAD

**Issue by Nebiroth** [theia-ide/theia#796]
1. Clone latest Theia repo 
2. Execute yarn then yarn run start 
3. Click the "Files" button on the left hand side
4. No file names will be displayed and the button to select a new workspace is missing.

[Screenshot](https://imgur.com/a/MuLtv)

**Comment by marcdumais-work** [comment]
For me, the "Open Workspace" button is missing often, but not always. 

W-A: use File -> Open to open a new workspace.

**Comment by Nebiroth** [comment]
That seems to work for me.

**Comment by svenefftinge** [comment]
Yes, it was fixed in https://github.com/theia-ide/theia/commit/9ad7aed8444ccafa71ffc9446bf92bdd746cdee8
