### ISSUE TITLE
[osx] Select all does not work in text input

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#808]
I did not check other components, but this does not work in the Git tab. I cannot select all the text although the selection is there.

<img width="195" alt="screen shot 2017-11-09 at 16 44 49" src="https://user-images.githubusercontent.com/1405703/32614411-7a2224e6-c56d-11e7-8b98-6796dae36434.png">

**Comment by kittaakos** [comment]
It was in a bundled electron application.

**Comment by kittaakos** [comment]
Same in the new file dialog:
<img width="268" alt="screen shot 2017-11-10 at 09 44 14" src="https://user-images.githubusercontent.com/1405703/32649884-fff8b088-c5fb-11e7-8e1d-3c0961141bdb.png">

**Comment by kittaakos** [comment]
It works on Windows.

**Comment by akosyakov** [comment]
Resolved in #1415
