### ISSUE TITLE
[windows] Spawned processes leak on Windows 10

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#815]
Start a bundled electron application, kill the application, one can still see stale processes on Windows.

See: https://github.com/theia-ide/yangster-electron/issues/8
Also: https://github.com/Microsoft/vscode/issues/26807

**Comment by hexa00** [comment]
Is the node/electron process gone however ? 

Makes me think of the backend not stopping on windows after ctrl-c

**Comment by kittaakos** [comment]
Neither `0.7.1` nor `0.7.2` fixes the problem in the bundled electron application.

**Comment by kittaakos** [comment]
![gh-815](https://user-images.githubusercontent.com/1405703/32662802-05752b42-c62c-11e7-9678-2bc09deaa7df.gif)

**Comment by kittaakos** [comment]
PR: #816.

**Comment by kittaakos** [comment]
I try with [`ps-tree`](https://www.npmjs.com/package/ps-tree).

**Comment by hexa00** [comment]
But we're not using node-pty to create a LSP process ? 

How is this related?

**Comment by kittaakos** [comment]
I could ask the same, why do you want me to update node-pty if that does not fix my issue?

**Comment by hexa00** [comment]
@kittaakos I do not ? I said that because of #816 

I think like I said in #816 you should use RawProcess that may fix it...

**Comment by kittaakos** [comment]
Let's give it a try. Thanks for #817.

**Comment by kittaakos** [comment]
The problem still happens on Windows with a bundled application.

**Comment by akosyakov** [comment]
Which process? YANG LS?

**Comment by kittaakos** [comment]
Yes, the LS process.

**Comment by hexa00** [comment]
I think this is this issue: https://github.com/Tyriar/node-pty/issues/7

Note it doesn't happen if you use node directly it only happens when you use yarn start.

Maybe we could work around with a script to start it for now with node ?

**Comment by Tyriar** [comment]
https://github.com/Tyriar/node-pty/issues/7 is about pressing ctrl+c either not closing an application or corrupting the viewport in some way.

It's not totally clear to me what the problem is, but if it's about processes leaking under node-pty like https://github.com/Microsoft/vscode/issues/26807, then https://github.com/theia-ide/theia/pull/816 should have fixed this issue.

See the [release notes for 0.7.1](https://github.com/Tyriar/node-pty/releases/tag/0.7.1):

> All console processes running inside the pty should now be killed when killing the pty. This issue was observed frequently when running web servers via node-pty #122 via @the-ress, @Tyriar

**Comment by hexa00** [comment]
ok I have the same issue as described in https://github.com/Tyriar/node-pty/issues/7#issuecomment-326308297

But I'm not running inside node-pty it's directly git bash.  

Maybe git bash needs a simliar fix as:  https://github.com/rprichard/winpty/pull/130 from winpty

**Comment by kittaakos** [comment]
I do not see this anymore. I have verified it on my Windows 10 image with various Xtext based language servers.

I can confirm, the LS (`java`) process termination was successful. However, the process termination is not instantaneous on Windows. It is because the child processes do not die automatically on Windows when the parent process stops. We have to poll from the LS.

I am closing this.
