### ISSUE TITLE
Enabling general restarting of language servers via integration of `LanguageClient` with `ProcessManager`

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#817]
For example java-contribution.ts is using it's own process spawn...

We should use RawProcess for that since it keeps tracks of all processes in the application and can give kill/restart control to the user.

We should make this part of BaseLanguageServerContribution for the LSPs so that they all use the same logic.

**Comment by hexa00** [comment]
Note this could be TerminalProcess too incase we want to show the output somewhere... do we?

**Comment by kittaakos** [comment]
> can give kill/restart control to the user

I have made these changes in #841. How does it give control?

> Note this could be TerminalProcess too

I am not sure about this. There is no such thing as a `stderr` on the `ITerminal`.

**Comment by hexa00** [comment]
> I have made these changes in #841. How does it give control?

The plan is to give a user interface over ProcessManager so the use can perform actions on any process started by Theia.  

> I am not sure about this. There is no such thing as a stderr on the ITerminal.

stderr is still there even if it's not separate from stdout , but seems like RawProcess is the better option.

**Comment by akosyakov** [comment]
The goal is good but it should respect the LSP and implemented in the frontend to be properly hooked up with `LanguageClient`:
- The LSP defines how a server should be stopped: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown. One cannot just kill the process. It is managed by `LanguageClient`.
- A server should be started by `LanguageClient` and restarted as well to ensure that there is only one instance. One can hook into restart process.
- `LanguageClient` writes the output to a user, currently into the console. This output is not bound to one server, but only partly comes from it, basically, it is a per language. We should have something like `Output View`in vs code.

**Comment by hexa00** [comment]
> The LSP defines how a server should be stopped...
> A server should be started by LanguageClient and restarted as well to ...

Yes I think the LSP RawProcess could be specialized in a like LSPProcess such that we can do that.

However it would be nice to be able to do a raw kill on a process top a bit like the task manager in windows in case a process goes bad.

>LanguageClient writes the output to a user, currently into the console. This output is not bound to one server process, but only partly comes from it, basically, it is a per language. We should have something like Output Viewin vs code.

Seems OK

**Comment by svenefftinge** [comment]
What if we allow to register a 'beforeTerminate' listener on a process. The LanguageClient could send the shutdown notification. That same hook should be registered on the websocket, too.

**Comment by hexa00** [comment]
Fixed in #841

**Comment by kittaakos** [comment]
I was thinking about closing this task too, but a couple of things are not yet done here. Shall we open a follow-up or reopen this?

**Comment by hexa00** [comment]
Sorry I didn't know.

As you wish, maybe change the title a bit?

**Comment by kittaakos** [comment]
I am unsure either. I was somewhat just asking. Sorry for the confusion.

CC: @akosyakov, @svenefftinge

**Comment by akosyakov** [comment]
Enabling general restarting of language servers via integration of `LanguageClient` with `ProcessManager` should be done. But it could be a separate issue + we first need the process view.

**Comment by kittaakos** [comment]
Thanks! I update the title of this.

**Comment by kittaakos** [comment]
Depends on https://github.com/theia-ide/theia/issues/49.

**Comment by svenefftinge** [comment]
I think it would be better for the user to have a command that allows to restart a language server.
I would just execute restart language server, and the quick open would provide me with all currently running language servers. 
It is much better than looking up a language server process in a list of processes, trying to find the one that was spawned for the currently active client.

**Comment by svenefftinge** [comment]
In Vs code there is a specific one for TypeScript, but we could generalize it to allow restarting any language server.

**Comment by hexa00** [comment]
Yes that sounds nice, I always have trouble with the one in vscode and need to restart it... I expect it will be a common use case.

I think it's good that LSPs have restart command.  We could also trigger that from the Process View but that would just call that command so no need for the view to be done before this.

Actually many we could generalize that a bit and have anything that manages an underlying process or processes have a start/stop/restart command.  

The ProcessView could then use that to implement these functions. 

Still needs some thinking a bit.

**Comment by svenefftinge** [comment]
For the user it should not be too general. 'Restart Language Server' and then list the language servers and an 'all' option sounds just right to me.

**Comment by akosyakov** [comment]
ok, then it should be easily doable based on `LanguageClient`:
- show a quick item for each `LanguageClient`
- call `LanguageClient.stop` + `LanguageClient.start` to restart

**Comment by hexa00** [comment]
>For the user it should not be too general. 'Restart Language Server' and then list the language servers and an 'all' option sounds just right to me.

I agree I would even list them as their own command no need to do this in 2 steps since the command palette would take care of selecting the right one already so it would be ok to have

`Restart TS Language server`
`Restart CPP Language server`
`Restart all language servers`

I just mean we could in code a generic interface that once implemented provides those functions so that it's easy to require that in classes that manage processes.

**Comment by akosyakov** [comment]
We have now `Restart` command for each language server. Could it be closed?

**Comment by kittaakos** [comment]
Besides the `Restart` we have [`Start`](https://github.com/akosyakov) as well.
