### ISSUE TITLE
Restoration of Terminal widget often fails

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#818]
It seems that the automatic widget restoration is often not able to restore functional terminal widgets. I have noticed that if more than one terminal are in the same tab, only a single one is correctly restores. Also, in some cases, the presence of a single restored editor seems to prevent terminal widgets from restoring correctly. 

![peek 2017-11-10 10-12](https://user-images.githubusercontent.com/25749063/32664634-e7705da0-c5ff-11e7-9d7c-4c3afdc0a825.gif)

**Comment by svenefftinge** [comment]
The widget manager doesn't care whether the widget is active, visible or not. So I would search the issue in the Terminal's restore functionality.
