### ISSUE TITLE
Bind localhost by default

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#822]
The backend should listen on localhost so that we don't expose the FS and shell to the whole network.

**Comment by svenefftinge** [comment]
Why do you want to change the default for the server-mode?

**Comment by hexa00** [comment]
Because it's a security risk it it should need direct intervention to use 0.0.0.0 

Like mysql ngnix or any other server do never listen on all interfaces by default.

Otherwise without realising it you ca open fs and shell access to your loged in user over the network.

**Comment by svenefftinge** [comment]
But isn't the purpose of starting a server to let other hosts access it? A default of localhost, doesn't make sense in other scenarios then development, does it?

**Comment by svenefftinge** [comment]
> Like mysql ngnix or any other server do never listen on all interfaces by default.

Express and node seem to do, though.

**Comment by hexa00** [comment]
The idea in general for a server to listen on localhost by default is to leave time for the admin to configure it properly after installing it.  Otherwise just installing this server and starting it on installl may give a window to attackers to get into your system.

On BSD systems you even get a big warning and a setting to change in /etc/default each time something that listens to a port is installed.

For Theia this is very important I think since Theia gives direct shell access to the logged in user in a very easy way.

So just installing Theia and starting it anyone on the network (unless my port is firewalled properly) or like in an internet cafe... can use my account to do anything like do git commits/push or log in remote places I have access to using my unlocked ssh key.  Not to mention having access to all my files.
 
I think sharing a theia instance should be done with some authentification so that sharing with someone is not sharing with everyone at the same time.  Giving a specific link with a token for example.

If we had such authentification by default, and that the default was to deny someone that is not coming from localhost we could put it back to default to 0.0.0.0 but in the meantime I think it's way to easy to just open your shell to anyone.

**Comment by svenefftinge** [comment]
Ok, then could we please keep the default of `0.0.0.0` for our DockerFile? 
It doesn't make sense to start it with accessing only localhost and you can limit access through docker run.

**Comment by akosyakov** [comment]
If we do it, which host should be passed to accept connections on unspecified ipv4 and/or ipv6 addresses? Right now if `host` is omitted node handles it for us: https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback. How are we going to handle it if we override node defaults?

**Comment by hexa00** [comment]
>Ok, then could we please keep the default of 0.0.0.0 for our DockerFile?

Yes I think that's fine. The Dockerfile needs explicit configuration to be run and it's less of a risk being in a container. I'm adding it to the PR.

>If we do it, which host should be passed to accept connections on unspecified ipv4 and/or ipv6 addresses?

That is a problem for now I think we could assume that you can run either in ipv6 or in ipv4 using `::` and `0.0.0.0` as host respectively.

But I think we could improve this in general and provide a way to specify a list of ip addresses to bind and create https servers based on them. That way we could have a number of ipv6/ipv4 addresses.

I'll create an issue for it.

**Comment by hexa00** [comment]
@akosyakov  are you ok with this ? I'd like to merge the PR to add something else in the dockerfile...

**Comment by hexa00** [comment]
(PR #823 )

**Comment by hexa00** [comment]
Closing merged PR #823

**Comment by dannaf** [comment]
> The backend should listen on localhost so that we don't expose the FS and shell to the whole network.

> it's a security risk it it should need direct intervention to use 0.0.0.0

> without realising it you ca open fs and shell access to your loged in user over the network.

> it's way too easy to just open your shell to anyone.

All points that I strongly agree with.

\____

> > Ok, then could we please keep the default of 0.0.0.0 for our DockerFile?
> 
> Yes I think that's fine. The Dockerfile needs explicit configuration to be run and it's less of a risk being in a container.

**I don't think that it is fine to default to 0.0.0.0 in the Dockerfiles**.  It is just as dangerous.  (And, as noted, that is quite dangerous: a user accidentally exposing himself to nearly arbitrary code execution on his machine...)

Particularly, note that explicit configuration through the Dockerfile is not actually needed, as users can (and are encouraged to!) simply run `docker run ... theiaide/theia`, without themselves modifying the Dockerfile (or even inspecting it).  This use case can thus open a new user to extreme vulnerability.  And it is very likely to do so, since a new user will simply go to the docker hub and execute that command, and likely not even realize that he/she has just opened their machine to be controlled by anyone with the machine's reachable ip address...

Furthermore, it is inconsistent to have one default in the docker images than in the direct command line interface, and that can make an even less-new user expose himself (e.g. a user familiar with running theia locally and just starting with the docker images---again, users may start by running `docker run` with a pre-built image without inspecting the Dockerfile).  This inconsistency is also not documented on the docker hub instructions...

\_____

> isn't the purpose of starting a server to let other hosts access it? A default of localhost doesn't make sense in other scenarios besides development, does it?

A quite typical scenario, I would argue, is to start a server so that it can be accessed *securely* behind secured serving, for instance behind a reverse proxy with basic auth through https/TLS.  Such a scenario is implemented well by a reverse proxy running alongside theia and passing the requests to the theia port *after checking authentication*.  In such a setup, however, it is **important to restrict theia to listen only from the location of the reverse proxy** (which might be localhost..).

**Comment by pmarreck** [comment]
Just ran into this issue and spent quite a bit of time trying to debug it because I had installed Theia in a VM accessible via Tailscale and no matter what I tried I couldn't access it except from localhost.

Suggest continuing to default to only accepting connections from localhost for security reasons BUT HOLY CRAP HOW ABOUT DOCUMENTING THIS SOMEWHERE IN THE README? 🤣 Plus perhaps add how to actually configure it to run on arbitrary host and port, because I'm still looking for how to do that...

**Comment by paul-marechal** [comment]
@pmarreck One of the first logs when starting an app:

> root INFO Theia app listening on http://localhost:3000.

Theia apps also support an `--help` flag:

```
>npx theia start --help
main.js [workspace-directory] [options]

Options:
  --version                          Show version number               [boolean]
  --port, -p                         The port the backend server listens on.
                                                        [number] [default: 3000]
  --hostname, -h                     The allowed hostname for connections.
                                                 [string] [default: "localhost"]
  --ssl                              Use SSL (HTTPS), cert and certkey must also
                                     be set           [boolean] [default: false]
  --cert                             Path to SSL certificate.           [string]
  --certkey                          Path to SSL certificate key.       [string]
  --app-project-path                 Sets the application project directory
                           [default: "D:\sources\theia.patate\examples\browser"]
  --log-level                        Sets the default log level
                   [choices: "fatal", "error", "warn", "info", "debug", "trace"]
  --log-config                       Path to the JSON file specifying the
                                     configuration of various loggers   [string]
  --root-dir                         DEPRECATED: Sets the workspace directory.
  --plugins                          Provides further refinement for the
                                     plugins. Example:
                                     --plugins=local-dir:path/to/your/plugins
                                                                        [string]
  --plugin-max-session-logs-folders  The maximum number of plugin logs sessions
                                     folders to retain. Example:
                                     --plugin-max-session-logs-folders=5
                                                          [number] [default: 10]
  --extensionTestsPath                                                  [string]
  --pluginHostTerminateTimeout       Timeout in milliseconds to wait for the
                                     plugin host process to terminate before
                                     killing it. Use 0 for no timeout.
                                                       [number] [default: 10000]
  --pluginHostStopTimeout            Timeout in milliseconds to wait for the
                                     plugin host process to stop internal
                                     services. Use 0 for no timeout.
                                                        [number] [default: 4000]
  --vscode-api-version               Overrides the version returned by VSCode
                                     API 'vscode.version'. Example:
                                     --vscode-api-version=<Wanted Version>.
                                     Default [1.53.2]                   [string]
  --help                             Show help                         [boolean]
```

There's also a bit of documentation left and right (not great, I would agree):

https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#run-the-browser-based-example-application

Lastly I think this is a common networking mistake, Theia is no exception. It makes sense for me to run on localhost by default.

PRs are welcome! Documentation is definitively a point we can improve on.

**Comment by pmarreck** [comment]
If I can get it working via args, I would be happy to pull Theia down and make a PR for the docs just to smooth out the onboarding; I can include a note about its default secure config if that helps

**Comment by paul-marechal** [comment]
Regarding the error you linked: `theia start` is meant to be used within Theia applications. If you are working on a clone of the repo (which is not a Theia app but contains Theia apps) then yes you should run `yarn browser start` which is a shortcut to `cd examples/browser && npx theia start`, meaning you could do `yarn browser start --help`. Make sure the example applications are built.

> I used that node version because using anything later broke a dependency;

Yeah... It's actually just an arbitrary warning from a dependency that can work despite it. Using Node 12 is fine but FYI it's possible to use 14 if you tell Yarn to ignore the errors with `--ignore-engines`.

> can I pass `host` and `port` arguments to yarn browser maybe?

`yarn browser start --hostname 0.0.0.0 --port 1234`
