### ISSUE TITLE
Close commands

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#83]
We should have
- [ ] : Close
- [ ] : Close All
- [ ] : Close Others

in the main menu under file (last section) and in a context menu on the tabs.

**Comment by akosyakov** [comment]
PRs are welcomed. There are following tasks:
- [ ] add `closeOthers` method to the shell: https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/shell.ts#L329
- [ ] add close commands in the common frontend contribution based using the shell: https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/common-frontend-contribution.ts#L58
