### ISSUE TITLE
[UI] Navigator widget collapsed when first opening a workspace

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#830]
Select "File" menu -> "Open"
After selecting a new workspace in the dialog, select OK
Expected result: see the selected folder being display automatically in THEIA
What happen: the workspace is in THEIA, but not visible, I need to select the menu "Files" to be able to see my workspace.

**Comment by svenefftinge** [comment]
Are you asking for having the navigator expanded on first starting a workspace?

**Comment by lmcbout** [comment]
YES, When I select File-> Open, I am expecting the navigator to show me the workspace,  this is exactly what I am expecting. 
Any reason why the navigator should not show the just selected workspace!

**Comment by hexa00** [comment]
Personally I'm not sure it should be expanded with File->Open.

But when it is expanded already and you select Open Workspace from there it would make sense to keep it expanded.

**Comment by jbicker** [comment]
> But when it is expanded already and you select Open Workspace from there it would make sense to keep it expanded.

That depends on the workspace you open. I would expect the layout like it was as I've left the workspace. So I would leave the responsibility about the layout to the layout restorer as it is now.

**Comment by lmcbout** [comment]
It seems the team agrees here, but I have one question, when a new THEIA user will select the button: "File"-> "Open", select for the first time a new workspace, press the "OK" in the dialog window and he will not see anything in the THEIA navigator window,
1- Is he going to think it did not work and try to open again! (Ans still not show)
2- Is he going to select the "Files" menu button on the left side and see his workspace (May be )
3- Click anywhere until he sees his workspace was just squeeze on the left side, he just had to open it !
4- Think THEIA is not able to open his workspace 
I would suggest at least for the first time a user open a new workspace, it should be displayed automatically, the other times, the workspace will expand according to what the user did the last time he open this workspace

**Comment by hexa00** [comment]
He should now thee the title of the theia window change for the workspace name.

That was added recently.

Do you think that is enought ?

**Comment by lmcbout** [comment]
I think this is not enough

**Comment by hexa00** [comment]
>That depends on the workspace you open. I would expect the layout like it was as I've left the workspace. So I would leave the responsibility about the layout to the layout restorer as it is now.

Good point.

**Comment by marcdumais-work** [comment]
So to recap:
- by default, when first opening a workspace, the file navigator widget is in collapsed state
- when a workspace is closed (e.g. closing browser tab), the (expanded/collapted) state of the navigator widget is saved, and the next time that workspace is opened, restored. I think it would be weird not to do this

I have renamed the issue to reflect what it's about.

**Comment by marcdumais-work** [comment]
I do not have a strong opinion on this, but I do not mind the current behavior

**Comment by vince-fugnitto** [comment]
We must remember Theia is a framework, and the example/browser is just an example application.

The idea is that products would define themselves which views would be opened by default using the `initializeLayout` call. We set forth the constructs to allow products to do so, but by default it's not necessary for the `Files` widget to be opened by default. See [comment](https://github.com/theia-ide/theia/pull/3942#issuecomment-451390559).

**Comment by rubenanapu** [comment]
The solution implemented in the link below worked for me:

https://github.com/bayodesegun/theia/pull/1/files

If the link above goes down, the solution consists of basically modifying the `theia/packages/navigator/src/browser/navigator-contribution.ts` file, more specifically `initializeLayout` method.

It was changed from this:

```
async initializeLayout(app: FrontendApplication): Promise<void> {
        await this.openView();
}
```

to this:

```
async initializeLayout(app: FrontendApplication): Promise<void> {
        // Reveal 'Files' view when opening a workspace for the first time
        // See:
        //  https://github.com/eclipse-theia/theia/issues/830
        await this.openView({ activate: true, reveal: true });
    }
```
