### ISSUE TITLE
Unable to pull Docker image from Docker hub

### ISSUE THREAD

**Issue by jamesemwallis** [theia-ide/theia#839]
I seem to be unable to pull the Theia Docker image from [Theia Docker hub link](https://hub.docker.com/r/typefox/theia-browser/). Its a public repo and was updated 6 days ago so I'm assuming that the latest image has been pushed to it.

Command and output:
```
$ docker pull typefox/theia-browser                                                      
Using default tag: latest
Error response from daemon: manifest for typefox/theia-browser:latest not found
```

Am I doing something wrong / is anyone else unable to pull?

Thanks in advance.

**Comment by akosyakov** [comment]
Hey, it should be: docker pull typefox/theia
The repo for theia apps built from published extensions: https://github.com/theia-ide/theia-apps
@geropl would it be possible to deprecate theia-Browser?

**Comment by jamesemwallis** [comment]
I've tried that command instead of theia-browser and it works perfectly. 
You might want to make a comment on the theia-Browser image on Docker hub as it appears far above theia.

I'll close this issue as it works for me
Thanks again
