### ISSUE TITLE
Improve styling of theia gui

### ISSUE THREAD

**Issue by jbicker** [theia-ide/theia#846]

**Comment by svenefftinge** [comment]
The idea is to do a pass over the general styling, to clean it up and make it less noisy.

**Comment by jbicker** [comment]
First proposal:
<img width="1680" alt="theia - style - 11-2017" src="https://user-images.githubusercontent.com/28291421/32947824-2fb7d78a-cb9d-11e7-97eb-869395a95980.png">

**Comment by svenefftinge** [comment]
+1 for the proposal from my side. It is significantly cleaner and a great improvement IMHO.
