### ISSUE TITLE
Use native File Dialog

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#853]
On electron, for switching the workspace and opening an external file, we should use the OS native dialog. I think it is fair to say, that in the remote containerized context one rarely wants to even allow switching the workspace root. So the main use case would be the desktop version, anyways. Therefore, it might make sense to use the native one for the important case and keep the simple web one we have now for those other rare cases.

**Comment by hexa00** [comment]
Yes, btw we need to cover the case where electron is connected to a remote backend.

So the check should be electron && localhost backend.

**Comment by kaviththiranga** [comment]
+1 This is really worthy to have.

**Comment by vince-fugnitto** [comment]
@kittaakos can we close the issue thanks to your PR #3202 ?
