### ISSUE TITLE
open dialog: long names are formatted strangely

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#870]
I find it strange that when a directory name is cut because it's too long, the remaining part is shown centered instead of left-justified.

![image](https://user-images.githubusercontent.com/25749063/33143420-cef06554-cf87-11e7-8bca-301ae97fef61.png)

The long filenames in question:
``` bash
drwx------  3 root root     4096 Nov 22 05:16 systemd-private-136bdce8f99b4741aad6e2c7b2f7249e-colord.service-fTR5ev/
drwx------  3 root root     4096 Nov 22 05:16 systemd-private-136bdce8f99b4741aad6e2c7b2f7249e-rtkit-daemon.service-ofQcVk/
drwx------  3 root root     4096 Nov 22 05:14 systemd-private-136bdce8f99b4741aad6e2c7b2f7249e-systemd-timesyncd.service-RWr33S/
```

**Comment by svenefftinge** [comment]
Should be easily fixable with an overflow: hidden

**Comment by jbicker** [comment]
https://github.com/theia-ide/theia/pull/908
