### ISSUE TITLE
[git] problem with reported untracked files

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#871]
It doesn't happen all the time, maybe. But once it starts... Sometimes untracked files are reported twice, sometimes they're not reported at all. 

![theia-git-extension--double entries for new files](https://user-images.githubusercontent.com/25749063/33143746-d3384428-cf88-11e7-811b-76b7002083ed.gif)

**Comment by marcdumais-work** [comment]
I still see this bug or a very similar one.

**Comment by marcdumais-work** [comment]
The form of this bug that was reported by a user is that they have multiple git repos in their workspace, that have some file names in common (i.e. multiple repos contain a file named 'Dockerfile'). Changing one of those files, it's reported as changed by the git extension multiple times. 

But even if the workspace contains a single git repo, I can still see the issue first reported above, where added files are reported twice.

**Comment by akosyakov** [comment]
I hit the same bug with the latest master:
![screen shot 2017-11-27 at 12 46 57](https://user-images.githubusercontent.com/3082655/33266233-12082872-d375-11e7-8c7f-cef1ba3dc827.png)

**Comment by svenefftinge** [comment]
I could easily reproduce it locally before https://github.com/theia-ide/theia/commit/780c14f7ad2ca0eb37755f3abc65cbb3524b6439 but no longer afterward. 
And unfortunately, I still can't reproduce. There still is a concurrency problem in that code, which I will fix. I hope it goes away then. :-|
