### ISSUE TITLE
Theia simple examples

### ISSUE THREAD

**Issue by GitAmod** [theia-ide/theia#876]
Not sure where should I ask this, I am trying to get into Theia, can you please share examples mentioned in youtu.be/IY6nk5tilho? and other simple examples to start with (other than Theia git examples)

**Comment by akosyakov** [comment]
Please at the documentation: https://github.com/theia-ide/theia#documentation
We have a tutorial on developing the simple extension for Theia: https://github.com/theia-ide/theia/blob/master/doc/Authoring_Extensions.md
