### ISSUE TITLE
Widgets can be inflated twice by the layout restorer

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#879]
Widgets can get saved in the activeWidgets and in the main area for example.

Thus on inflate their restoreState function is called twice.

This can be problematic with widgets that have side effects associated with that function.

For example while working on #821 to restore a terminal, the terminal needs to attach to the terminal running on the backend, starting a websocket connection to do so.

When restoreState is called twice, 2 connections are made and thus I get the data from the terminal twice on the same widget.

From @svenefftinge on gitter this could be fixed by:

```
yes, in inflate/deflate you need to keep references for the widgets.
The first one needs to get serialized like now. 
Any subsequent references need to be serilaized as a references.
So some string that tells you which already created widget is references
```

**Comment by epatpol** [comment]
Indeed, I noticed that right now the terminal has a workaround for this by checking if its `restored` variable was already set...

**Comment by spoenemann** [comment]
Yes, it should be fixed by now. We only store the id of the active widget in ApplicationShell.LayoutData.
