### ISSUE TITLE
Try tslint-language-service with theia

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#892]

**Comment by akosyakov** [comment]
Seems like an extension is not needed, one can configure tslint as a plugin for ts: https://github.com/angelozerr/tslint-language-service#tslint-language-service.

We should try it for Theia repo.

**Comment by hexa00** [comment]
That's nice, we could add it to an FAQ or something. Or have an empty extension with the instructions?

**Comment by svenefftinge** [comment]
We have it by now, but it doesn't seem to be picked up always.

**Comment by akosyakov** [comment]
After enable logging, I see that tsserver cannot find tslint plugin if `yarn install` was not run. I've added the ability to see tsserver logs for user project and restart tsserver in this PR: https://github.com/theia-ide/theia/pull/2742
