### ISSUE TITLE
Show TypeScript version in the status bar

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#895]

**Comment by kittaakos** [comment]
Is this something you can get from the LS?

**Comment by vince-fugnitto** [comment]
We currently display the typescript version in the status-bar:
<img width="273" alt="screen shot 2019-01-03 at 1 54 04 pm" src="https://user-images.githubusercontent.com/40359487/50655772-162f0200-0f5f-11e9-9573-232a34c9371a.png">

**Comment by vince-fugnitto** [comment]
We currently display the typescript version in the status-bar:
<img width="273" alt="screen shot 2019-01-03 at 1 54 04 pm" src="https://user-images.githubusercontent.com/40359487/50655772-162f0200-0f5f-11e9-9573-232a34c9371a.png">
