### ISSUE TITLE
Notifications should provide feedback about the outcome of the executed git commands

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#896]
Originally from here: https://github.com/theia-ide/theia/pull/891#issuecomment-347221099

**Comment by svenefftinge** [comment]
Specifically, when a command fails, the error message should be shown.

**Comment by svenefftinge** [comment]
See also #759

**Comment by hexa00** [comment]
@svenefftinge yes that's the same except that I would like not just the errors but also the success to be reported.

**Comment by hexa00** [comment]
Maybe it's ok if the success is reported indirectly however, but if nothing at all changes in the UI it's hard to tell that something happened.

**Comment by svenefftinge** [comment]
Ok, I suggest to do this in two steps.
1) Show errors through notifications (this issue)
2) Have a git log view, that shows all the details (#759)
