### ISSUE TITLE
Git missing in Docker image if workspace a child of /

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#901]
I'm using Theia in a docker image where the workspace is specified as  /workspace (not under the home directory).  When I do this, the Git tab on the left margin is missing.   Is this a limitation or a bug?

**Comment by kittaakos** [comment]
@jopit, could you try `F1` > `Reset Workbench Layout`?

**Comment by jopit** [comment]
Resetting the workbench layout fixes it.  It's not obvious that's what's required, though (at least not to me).

**Comment by svenefftinge** [comment]
Closing as dupe, since it is due to #902
