### ISSUE TITLE
Terminal has unconsumed 'passthrough' keybindings

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#907]
CTRL+P (find file) doesn't work in the terminal context, but also doesn't seem to do anything and doesn't prevent default. As a result the browser's print dialog opens up. (cc @simark)

**Comment by simark** [comment]
Works for me on Linux, I assume you have the problem on Mac?

**Comment by simark** [comment]
When in the shell (anything that uses readline), the expected behavior would be the equivalent of the up arrow, to go back one command in the history.

http://www.bigsmoke.us/readline/shortcuts

**Comment by svenefftinge** [comment]
Yes, on mac that would be CTRL+P, while the bindings are for CMD+[k].

**Comment by svenefftinge** [comment]
That might be the issue, we should map them to CTRL also on mac. I.e. it also is CTRL-C on mac, for instance.

**Comment by simark** [comment]
Ok, as mentioned in the PR, I assumed it wouldn't work well on Mac, and since I don't have one I can't really test.  It would be much easier for somebody with access to a Mac to work on that.
