### ISSUE TITLE
[help wanted] custom filename extension support

### ISSUE THREAD

**Issue by DustFinger001** [theia-ide/theia#922]
Here is my problem, I got some file named custom filename extension (eg: **name.m** ), but i hope its could perform like **.xml** file or **.html** file in theia. Is any way to configure it. please help.
![image](https://user-images.githubusercontent.com/16345979/33475762-891671c4-d6ba-11e7-9570-62995fd5fec2.png)

**Comment by akosyakov** [comment]
You can register [LabelProviderContribution](https://github.com/theia-ide/theia/blob/ec299e503a8ee359672a6d2a48a694da7488e29d/packages/core/src/browser/label-provider.ts#L16-L41) which appends `.xml`  for your URIs and delegates to `LabelProvider`.

**Comment by DustFinger001** [comment]
@akosyakov thinks for help . besides , i also hope these files has The same performance as **.xml** file in editor. what can i do for it .
![image](https://user-images.githubusercontent.com/16345979/33477789-f667887e-d6c1-11e7-8745-5dde577838a8.png)
![image](https://user-images.githubusercontent.com/16345979/33477802-053e7c36-d6c2-11e7-8646-7c83a013fdb1.png)

**Comment by akosyakov** [comment]
You can try to find monaco language for xml and add your extension as an alias, kind of a hack. Or register a new monoac language, look at java extension.

**Comment by DustFinger001** [comment]
looks like writting a new language extension is better. thank you for your time @akosyakov
