### ISSUE TITLE
[electron][Windows][terminal] Currently, there is no way to paste anything into the `cmd.exe` based terminal

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#923]
It would be awesome to have a context menu for that in the electron application too.

**Comment by hexa00** [comment]
For me it works using the browser context menu ? (Right click -> paste)

Correct me if I'm wrong but that's the only way since even from theia Edit menu doing Paste ask you to use the browser's paste.

**Comment by hexa00** [comment]
(I tested on windows)

**Comment by kittaakos** [comment]
Thanks for checking it, I have updated the description and the title too.

**Comment by kittaakos** [comment]
My bad, confused with the cygwin/GitBash behavior which inserts the content os the clipboard on right click. We have a solution for that. I am closing it.
