### ISSUE TITLE
[navigator] directories that end with "-config" have a "config" icon

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#925]
Is that intended? Or was it only meant for config files? 

![image](https://user-images.githubusercontent.com/25749063/33481449-86b5f326-d662-11e7-9bdc-1594af60aa2f.png)

**Comment by svenefftinge** [comment]
No, it is not intended. I made so that also for folders the icon provider is used, such that e.g. `.git` would get a git icon.

**Comment by marcdumais-work** [comment]
Also, it seem that all sub-folders and files get the same icon: 
![image](https://user-images.githubusercontent.com/25749063/33482117-82624056-d665-11e7-9125-fa4f2b5ae5c9.png)
