### ISSUE TITLE
Investigate warnings on `npm install`

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#93]
npm WARN deprecated @types/promises-a-plus@0.0.27: Use '--lib es6' to get Promise types.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

**Comment by hexa00** [comment]
I think those warnings about the license are back since the restructuring

**Comment by hexa00** [comment]
There's no warnings anymore now it seems but the license is not in package.json anymore after #299 ?

**Comment by svenefftinge** [comment]
yes, I think that warning should be ignored as private packages are not published.
Can we close this one? no npm anymore :)

**Comment by hexa00** [comment]
yarn install v0.19.1
warning generator-theia@0.0.1-alpha.1: No license field
It's there for the generator however now
