### ISSUE TITLE
[git] Git API should expose a low-level `exec` function

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#936]
Git API should expose a low-level `exec` function so that Theia extension developers could implement their own functions which are not yet supported by Theia's Git API.

Later one could open a PR in Theia with these additional, custom Git commands. If those seem to be useful for general, public usage, we could merge those into our API.

**Comment by kittaakos** [comment]
So this was ignored and removed [here](https://github.com/theia-ide/theia/pull/899/files#diff-69295d120802b4b29a7814968dc5de90L53).

My test fails currently, and I have the following path:
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - **CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE**
 - **REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE**
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE\A
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE\B
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE\C

The marked lines are pointing to the same location but the FS path (strings) are different.

@akosyakov, do you have any advice on this?

**Comment by akosyakov** [comment]
@kittaakosI've replaced it with `fs.realpath` which should return a canonical name, i.e. resolve symlinks and normalize paths. It could be that it has bugs on Windows or I missed some places.

**Comment by kittaakos** [comment]
Ohh, I wanted to post this to #933. I move everything there. Sorry. And thanks for the hint. I try `fs-extra#realpath` outside from Theia.
