### ISSUE TITLE
Editors are not reopened after restart when using Electron example

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#943]
Using master as of commit 9f60988e63f50e395422540e730e190199ccce08
1. Start the Electron app from examples/electron, with 'yarn run start'
2. Open a file
3. Close windows and terminate the backend (Ctrl+C)
4. Re-run 'yarn run start': editor is not reopened.

This seems to work fine in the browser version.

**Comment by MarkZ3** [comment]
I should add, doing "Reset workbench layout" did not fix it.

**Comment by hexa00** [comment]
Confirmed.

The editors seems to be saved properly however I see in the Local Data:

```
"{\"mainArea\":{\"activeWidgets\":[{\"constructionOptions\":{\"factoryId\":\"code-editor-opener\",\"options\":\"file:///home/eantotr/src/theia/CONTRIBUTING.md\"}}],
\"main\":{\"type\":\"tab-area\",\"widgets\":[{\"constructionOptions\":{\"factoryId\":\"code-editor-opener\",\"options\":\"file:///home/eantotr/src/theia/CODE_OF_CONDUCT.md\"}},{\"constructionOptions\":{\"factoryId\":\"code-editor-opener\",\"options\":\"file:///home/eantotr/src/theia/CONTRIBUTING.md\"}}],\"currentIndex\":1}},\"leftBar\":{\"activeWidgets\":[{\"constructionOptions\"

```

Must be something with the restore...

**Comment by hexa00** [comment]
@svenefftinge  This is because now we store per location and that electron is using dynamic port allocation so since #905 the electron app restore is broken...

**Comment by svenefftinge** [comment]
I reverted it https://github.com/theia-ide/theia/commit/49a86f3761178b7282fa6181885a230e2631af55

**Comment by MarkZ3** [comment]
works, thanks!
