### ISSUE TITLE
Improve rendering of messages with many actions 

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia#955]
Theia renders the `actions` of an LSP `window/showMessageRequest` as buttons. If they are too many or have too long `titles`, they are rendered outside the viewport. We should render these differently. 

See https://github.com/theia-ide/theia-go-extension/issues/4

<img width="1439" alt="screen shot 2017-12-08 at 11 46 19" src="https://user-images.githubusercontent.com/377752/33762858-802ff2b6-dc0e-11e7-8a7e-abe4f25ed036.png">

In VSCode the same command is shown as

<img width="1169" alt="screen shot 2017-12-08 at 11 52 12" src="https://user-images.githubusercontent.com/377752/33762870-895a3b80-dc0e-11e7-949b-bd62fd74c7c4.png">

**Comment by svenefftinge** [comment]
The command in the go extension for VS CODE seems to be implemented using the `showQuickPick` API which uses the quick open widget internally. 
Since we only have `showMessage` on LSP we could optimize, to use the quick open, too if the number of commands is greater some threshold (e.g. 3).

**Comment by svenefftinge** [comment]
OTOH it makes sense to handle such long lists of commands in the general rendering, too. But there I would just do the rendering differently.

**Comment by AlexTugarev** [comment]
How about having a single `[ Show Options ]` button, to show the pick list for message with many actions?

**Comment by svenefftinge** [comment]
I think rendering something like a drop down, for options longer then 3 (excl. close) would be good.
For this specific case, however, I would like to use the quick open somehow.

**Comment by AlexTugarev** [comment]
@vince-fugnitto thanks for checking!
