### ISSUE TITLE
[backend application] BackendApplicationContribution # onStop() not working as it should?

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#959]
This might be related to the fact that we have more than one process, since recent changes. 

In the backend, the application reacts to the termination signal, giving a chance to the contributing extensions to do some cleanup before the main process exits. But it looks like that mechanism might be broken somewhat. 

I noticed that if an extension (e.g. terminals) spawns child processes in the backend and attempts to take care of killing them in its OnStop() method, something seems funny... 

Watching with the debugger, I can see that OnStop(), in process-manager.ts is actually called, but it doesn't have access to the information about running processes (this.processes) is always empty. This could cause the needed cleanups not to happen correctly. Note however that I can't see evidence of that happening with terminal processes (or tasks in my yet-to-be-merged PR): all spawned processes do seem to be killed, somehow.

**Comment by hexa00** [comment]
#953 may be linked to that too.

I think it may be that the master process is the one handling SIGINT and it's not passing it down to the slave process.

So the slave onStop() is not called.

We would need the signals to follow from master to slave or have the master tell the slave to shutdown using ipc.

**Comment by hexa00** [comment]
This is because ProcessManager wasn't bound properly... A fix is on the way
