### ISSUE TITLE
Last Line in terminal not visible

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#967]
The last line is covered, see below:

<img width="428" alt="screen shot 2017-12-12 at 11 35 32" src="https://user-images.githubusercontent.com/372735/33880079-b8b6d62a-df30-11e7-8fe2-bbb50d74811f.png">

**Comment by marcdumais-work** [comment]
@simark Wasn't there a xtermjs issue for this, that you either reported or found?

**Comment by marcdumais-work** [comment]
I was hoping that  this one was fixed, with XTermJS 3.x, but I still see it partially happen. It's a bit strange - as soon as I change the height of the terminal widget, it seems to then to "reserve" some buffer space between itself and the status bar: 

![peek 2018-01-25 06-40](https://user-images.githubusercontent.com/25749063/35386629-bc43a32c-019a-11e8-82ed-5d16c5de1f7f.gif)

**Comment by JanKoehnlein** [comment]
Could that be a layout problem in phosphor?

**Comment by marcdumais-work** [comment]
It could be. I just noticed something that might point towards that direction: when the last terminal line is partially hidden, as above, toggling a side-panel resets the terminal to a good state. 

![peek 2018-01-25 07-22](https://user-images.githubusercontent.com/25749063/35388142-954d4c40-01a0-11e8-8d40-9e3678260a35.gif)

**Comment by svenefftinge** [comment]
Haven't seen this in a while.
