### ISSUE TITLE
Drag & Drop limit of 100 files / folders 

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#968]
Drag and Drop issue: Cannot drag and Drop more than 100 files/folders from the same folder
If you Drag Theia  node modules into a workspace, only 100 folders/files will be copied, everything else will be drop with no warning. This is a follow up of issue #868 
See another ref : https://github.com/owncloud/core/issues/19834

**Comment by akosyakov** [comment]
@lmcbout is it still an issue?

**Comment by lmcbout** [comment]
@akosyakov let me test it , I don't know

**Comment by lmcbout** [comment]
@akosyakov Tested with many files (15000 files within a folder) and all files are moved with the Drag & Drop. With all the latest changes in this area, it works fine, so I will close this issue.
