### ISSUE TITLE
the documentation for `OpenHandler.canHandle` is bogus

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#971]
It should say that the handler is disabled if the returned number is zero, negative numbers are allowed or clients should be changed.

**Comment by akosyakov** [comment]
PRs are welcomed, you should change `a positive number` to`a nonzero number` here: https://github.com/theia-ide/theia/blob/1c96e7bd47f79e770a82b790a5f80b66aef85e36/packages/core/src/browser/opener-service.ts#L34

**Comment by vince-fugnitto** [comment]
Hi @akosyakov, do you propose instead we update the documentation to reflect the return type to  ```a positive nonzero number``` instead of ```a positive number``` to be as transparent as possible?

I'm looking at the code and don't see any references where we declare ```canHandle()```'s return type to be a negative value.

Let me know what you think.
