### ISSUE TITLE
Add onStarted FrontendApplication Contribution

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#973]
So that a extension dev can do something when the frontend is ready.

Like open a file.

**Comment by akosyakov** [comment]
> Like open a file.

It sounds like it should be a part of `initializeLayout`. Maybe we should improve on it and call it regardless whether previous layout state.

**Comment by hexa00** [comment]
>It sounds like it should be a part of initializeLayout. Maybe we should improve on it and call it regardless whether previous layout state is present.

Yes that was the plan that onStarted would be called all the time unlike `initializeLayout` 

I seems to me too that it's nicer to have a event that refers to the state of the application like `onStarted` instead of specifying a purpose to that event like calling it `initializeLayout`.

Since then you end up with things implementing `initializeLayout` when they have nothing to do with the layout and just want to be called when the app is started.

**Comment by vince-fugnitto** [comment]
I believe we now have this functionality with the use of the `onStart` hook. (used by the `getting-started` widget amongst others). Closing for the moment but can be re-opened if required.
