### ISSUE TITLE
Allow to modify a text editor's document

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#98]
Add following capabilities:
```ts
// Access and change a document value
value: string;
// Apply incremental changes to a document
applyEdits(edits: lsp.TextEdit[]): void
// Emit when a document value is changed
readonly onDidChangeValue: Event<lsp.TextDocumentDidChangeEvent>;
```

**Comment by AlexTugarev** [comment]
```
// Emit when a document value is changed
readonly onDidChangeValue: Event<lsp.TextDocumentDidChangeEvent>;
```

...would that be a translation for `onDidChangeContent` events, @akosyakov?

I need `TextEditorDocument.applyEdits`, and would tackle the rest of this.

**Comment by AlexTugarev** [comment]
@akosyakov, do you mean `TextDocumentDidChangeEvent` from services, `lsp.TextDocumentChangeEvent`, or `lsp.TextDocumentContentChangeEvent`? :-)

**Comment by akosyakov** [comment]
probably this issue is outdated, we already have `document` to access the value and `onDocumentContentChanged` to fire an event, only `applyEdits` is missing

btw https://github.com/theia-ide/theia/issues/1756 and https://github.com/theia-ide/theia/issues/1788 are related

**Comment by AlexTugarev** [comment]
Closing as outdated. Remaining issue is #1756.
