### ISSUE TITLE
The navigator styles are incorrectly located under the navigator extension

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#984]
Move the `index.css` from [`@theia/workspace`](https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/style/index.css) under to the navigator extension. The above-mentioned styles are currently used by the [`FileNavigatorWidget `](https://github.com/theia-ide/theia/blob/41cc3818c7dd094c3136e9cc5f85d3b952694a8d/packages/navigator/src/browser/navigator-widget.ts#L91) and it works because the navigator depends on the workspace module.

TODOs:
 - Move the `styles` folder from `@theia/workspace/src/browser` to `@theia/naviagtor/src/browser`.
 - Move the CSS loading from the [`workspace-frontend-module`](https://github.com/theia-ide/theia/blob/41cc3818c7dd094c3136e9cc5f85d3b952694a8d/packages/workspace/src/browser/workspace-frontend-module.ts#L21) to the [`navigator-frontend-module`](https://github.com/theia-ide/theia/blob/master/packages/navigator/src/browser/navigator-frontend-module.ts).
 - Adjust the CSS class names. (It should use the `naviagtor` prefix instead of the `workspace` one.)

**Comment by esquith** [comment]
I would like to give this a shot.

**Comment by akosyakov** [comment]
It was fixed with #993

**Comment by akosyakov** [comment]
@esquith thanks for the interest, you can look into other issues for beginners, e.g.: https://github.com/theia-ide/theia/issues/971
