### ISSUE TITLE
Add instructions on how to install golang-server to go extension readme

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#986]

**Comment by JanKoehnlein** [comment]
This should be obsolete now, as the new Go extension pulls the new Go language server as an npm dependency.

**Comment by hexa00** [comment]
Yes but the go-language-server needs it's go deps right ? like they are installed in the go-docker-image ? 

This is what I mean see PR: https://github.com/theia-ide/theia-go-extension/pull/5
