### ISSUE TITLE
Remove Java LSP from git

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#989]
We could do something like suggested in #988 or just remove the gulp execution from the build phase for now and require the user do it manually.

**Comment by svenefftinge** [comment]
I think we should remove all language extensions but the TypeScript one from this repo and host them in their own repo. The Java LSP should be packaged with the extension.

**Comment by AlexTugarev** [comment]
I think it's still not clear, how to proceed with `@theia/java`. 

Options:
1. Shall we just remove the archive from git (#1732) and keep `@theia/java` in `theia` repo?
1. Shall we consider to move `@theia/java` to another repo in a following step?

cc. @svenefftinge, @gorkem

**Comment by kittaakos** [comment]
Closed via #1732.
